### ISSUE TITLE
New feature: autocomplete

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1]
Search box should have autocomplete enabled.

Reference:
https://confluence.crbs.ucsd.edu/display/NIF/OntoQuestMain#OntoQuestMain-1%29Listallontologies

**Comment by cmungall** [comment]
Note: NIF now bypasses OQ for autocomplete, all via vocab table in solar

**Comment by harryhoch** [comment]
added in https://github.com/monarch-initiative/monarch-app/commit/739993b069dd031de28efc6891318875f6eab114, using jqery-ui-autocomplete widget. 

There might be some lingering glitches, but the core is there.
