### ISSUE TITLE
Add API call for comparing disease and model

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#10]
Should wrap this:
http://code.google.com/p/owltools/issues/detail?id=79

**Comment by cmungall** [comment]
Example:
http://secret-harbor-1370.herokuapp.com/compare/OMIM_143100/MGI:3698411.json

**Comment by frdougal** [comment]
Hello,
  I am trying to use this call and I receive this response: 

TypeError: Cannot call method "decodeToString" of undefined
ringo/httpclient.js, line 315

Script Stack

```
at ringo/httpclient.js:315 (anonymous)
at lib/monarch/api.js:67 (anonymous)
at lib/monarch/api.js:1574 (anonymous)
at lib/monarch/api.js:1567 (anonymous)
at lib/monarch/api.js:1341 (anonymous)
at lib/monarch/web/webapp.js:431 (anonymous)
at stick/lib/middleware/route.js:215 (route)
at stick/lib/middleware/params.js:102 (anonymous)
at stick/lib/middleware/static.js:62 (static)
at stick/lib/stick.js:37 (app)
at ringo/jsgi/connector.js:42 (handleRequest)
```

**Comment by frdougal** [comment]
I reviewed the output a bit.  I think this URL is causing the problem.  It doesn't return any results.  It tried shortening the URL a bit, but nothing works:
http://toaster.lbl.gov:9031/compareAttributeSets?a=HP:0000006&a=HP:0000726&a=HP:0000746&a=HP:0001300&a=HP:0002367&a=HP:0007159&b=MP:0005584&b=MP:0008751&b=MP:0002177&b=MP:0001261&b=MP:0002019&b=MP:0001340&b=MP:0002941&b=MP:0000297&b=MP:0005329&b=MP:0001732&b=MP:0010873&b=MP:0000690&b=MP:0000920&b=MP:0005093&b=MP:0002079&b=MP:0004924&b=MP:0003984&b=MP:0008189&b=MP:0008075&b=MP:0008803&b=MP:0002053&b=MP:0005386&b=MP:0003725&b=MP:0011229&b=MP:0001240&b=MP:0009838&b=MP:0002083&b=MP:0002229&b=MP:0005559&b=MP:0006386&b=MP:0002144&b=MP:0001928&b=MP:0008143&b=MP:0003932&b=MP:0001303&b=MP:0002553&b=MP:0003644&b=MP:0000627&b=MP:0011096&b=MP:0002075&b=MP:0001393&b=MP:0009378&b=MP:0000032&b=MP:0001921&b=MP:0002100&b=MP:0009429&b=MP:0004355&b=MP:0003859&b=MP:0002795&b=MP:0011096&b=MP:0010768&b=MP:0008143&b=MP:0005397&b=MP:0005352&b=MP:0001364&b=MP:0005376&b=MP:0001577&b=MP:0002675&b=MP:0001919&b=MP:0005370&b=MP:0009890&b=MP:0000604&b=MP:0008808&b=MP:0004609&b=MP:0002075&b=MP:0002412&b=MP:0006299&b=MP:0000284&b=MP:0003982&b=MP:0002064&b=MP:0001292&b=MP:0008788&b=MP:0000790&b=MP:0002166&b=MP:0000585&b=MP:0001806&b=MP:0005027&b=MP:0002494&b=MP:0004159&b=MP:0003984&b=MP:0005565&b=MP:0002144&b=MP:0002939&b=MP:0005508&b=MP:0005545&b=MP:0005289&b=MP:0000962&b=MP:0000439&b=MP:0000574&b=MP:0000592&b=MP:0009308&b=MP:0002006&b=MP:0002633&b=MP:0010117&b=MP:0001260&b=MP:0008496&b=MP:0008874&b=MP:0008111&b=MP:0001732&b=MP:0005621&b=MP:0003058&b=MP:0011108&b=MP:0000734&b=MP:0002169&b=MP:0002565&b=MP:0001222&b=MP:0009890&b=MP:0004509&b=MP:0005221&b=MP:0005386&b=MP:0000691&b=MP:0005452&b=MP:0001805&b=MP:0001392&b=MP:0011087&b=MP:0001212&b=MP:0000832&b=MP:0003566&b=MP:0008948&b=MP:0002109&b=MP:0003190&b=MP:0005463&b=MP:0001332&b=MP:0000097&b=MP:0008284&b=MP:0009267&b=MP:0003706&b=MP:0004896&b=MP:0000219&b=MP:0000467&b=MP:0001922&b=MP:0005039&b=MP:0001393&b=MP:0009293&b=MP:0000921&b=MP:0005458&b=MP:0006117&b=MP:0004748&b=MP:0003733&b=MP:0009278&b=MP:0005376&b=MP:0004189&b=MP:0005397&b=MP:0000933&b=MP:0001716&b=MP:0000737&b=MP:0008133&b=MP:0002078&b=MP:0000260&b=MP:0010881&b=MP:0004990&b=MP:0000063&b=MP:0005464&b=MP:0001265&b=MP:0001924&b=MP:0003331&b=MP:0006269&b=MP:0001967&b=MP:0002192&b=MP:0001688&b=MP:0009151&b=MP:0004762&b=MP:0006068&b=MP:0001405&b=MP:0011087&b=MP:0008805&b=MP:0005012&b=MP:0002064&b=MP:0000433&b=MP:0000385&b=MP:0001262&b=MP:0002398&b=MP:0008371&b=MP:0003631&b=MP:0002757&b=MP:0009160&b=MP:0003012&b=MP:0005390&b=MP:0000559&b=MP:0003205&b=MP:0000379&b=MP:0004215&b=MP:0008438&b=MP:0006260&b=MP:0001194&b=MP:0001192&b=MP:0005266&b=MP:0001891&b=MP:0002066&b=MP:0001515&b=MP:0010754&b=MP:0002981&b=MP:0002022&b=MP:0001505&b=MP:0003861&b=MP:0005168&b=MP:0003109&b=MP:0005159&b=MP:0005397&b=MP:0008078&b=MP:0002006&b=MP:0008658&b=MP:0010770&b=MP:0001130&b=MP:0002572&b=MP:0001922&b=MP:0006396&b=MP:0001504&b=MP:0001297&b=MP:0001212&b=MP:0001629&b=MP:0008261&b=MP:0002939&b=MP:0000536&b=MP:0001986&b=MP:0006325&b=MP:0003672&b=MP:0003633&b=MP:0002100&b=MP:0002407&b=MP:0011085&b=MP:0005017&b=MP:0005079&b=MP:0006099&b=MP:0011090&b=MP:0008045&b=MP:0002023&b=MP:0002882&b=MP:0000470&b=MP:0004411&b=MP:0000665&b=MP:0004804&b=MP:0000592&b=MP:0005464&b=MP:0000432&b=MP:0001056&b=MP:0009967&b=MP:0000284&b=MP:0006362&b=MP:0002182&b=MP:0004529&b=MP:0001846&b=MP:0010779&b=MP:0005562&b=MP:0010300&b=MP:0000166&b=MP:0009429&b=MP:0004174&b=MP:0004664&b=MP:0006281&b=MP:0002796&b=MP:0001829&b=MP:0008702&b=MP:0001823&b=MP:0001999&b=MP:0000524&b=MP:0001556&b=MP:0002962&b=MP:0002451&b=MP:0002498&b=MP:0000292&b=MP:0003083&b=MP:0003607&b=MP:0006309&b=MP:0000914&b=MP:0003638&b=MP:0003917&b=MP:0003718&b=MP:0000609&b=MP:0005122&b=MP:0005088&b=MP:0010025&b=MP:0001382&b=MP:0008098&b=MP:0004351&b=MP:0002398&b=MP:0011279&b=MP:0001845&b=MP:0000937&b=MP:0001541&b=MP:0001730&b=MP:0003271&b=MP:0011090&b=MP:0003658&b=MP:0004961&b=MP:0010286&b=MP:0003984&b=MP:0003229&b=MP:0003910&b=MP:0011098&b=MP:0004021&b=MP:0008277&b=MP:0004014&b=MP:0001262&b=MP:0003402&b=MP:0005027&b=MP:0000428&b=MP:0002418&b=MP:0005385&b=MP:0002100&b=MP:0000781&b=MP:0001463&b=MP:0008961&b=MP:0000208&b=MP:0008167&b=MP:0003292&b=MP:0010404&b=MP:0005241&b=MP:0002981&b=MP:0001196&b=MP:0000886&b=MP:0001265&b=MP:0011087&b=MP:0005445&b=MP:0001262&b=MP:0001178&b=MP:0003853&b=MP:0002020&b=MP:0002654&b=MP:0005380&b=MP:0010636&b=MP:0002697&b=MP:0001363&b=MP:0009703&b=MP:0003427&b=MP:0000414&b=MP:0006219&b=MP:0003631&b=MP:0000060&b=MP:0003055&b=MP:0008177&b=MP:0000432&b=MP:0000085&b=MP:0003984&b=MP:0002169&b=MP:0005179&b=MP:0008725&b=MP:0000585&b=MP:0001825&b=MP:0002591&b=MP:0010124&b=MP:0009115&b=MP:0005439&b=MP:0002412&b=MP:0005617&b=MP:0004163&b=MP:0000880&b=MP:0002026&b=MP:0004398&b=MP:0005386&b=MP:0002022&b=MP:0005560&b=MP:0003560&b=MP:0002135&b=MP:0011087&b=MP:0005397&b=MP:0002020&b=MP:0004686&b=MP:0002230&b=MP:0000049&b=MP:0001262&b=MP:0008587&b=MP:0005095&b=MP:0003631&b=MP:0005668&b=MP:0004738&b=MP:0004789&b=MP:0002765&b=MP:0011967&b=MP:0004431&b=MP:0003229&b=MP:0009968&b=MP:0005017&b=MP:0001402&b=MP:0002689&b=MP:0001038&b=MP:0003605&b=MP:0011098&b=MP:0002910&b=MP:0002083&b=MP:0005547&b=MP:0000435&b=MP:0006387&b=MP:0002968&b=MP:0001845&b=MP:0005391&b=MP:0009936&b=MP:0002644&b=MP:0010024&b=MP:0003718&b=MP:0001698&b=MP:0005608&b=MP:0004738&b=MP:0005338&b=MP:0002833&b=MP:0003662&b=MP:0000352&b=MP:0005404&b=MP:0004616&b=MP:0004076&b=MP:0005559&b=MP:0005370&b=MP:0008839&b=MP:0001190&b=MP:0001191&b=MP:0005018&b=MP:0009969&b=MP:0000130&b=MP:0002184&b=MP:0008392&b=MP:0005643&b=MP:0004047&b=MP:0001939&b=MP:0004142&b=MP:0005560&b=MP:0003385&b=MP:0006051&b=MP:0011427&b=MP:0003984&b=MP:0000474&b=MP:0001674&b=MP:0010508&b=MP:0000585&b=MP:0004852&b=MP:0003157&b=MP:0004609&b=MP:0002169&b=MP:0005262&b=MP:0006042&b=MP:0005208&b=MP:0008593&b=MP:0011481&b=MP:0005386&b=MP:0000750&b=MP:0005387&b=MP:0005402&b=MP:0000751&b=MP:0002458&b=MP:0005551&b=MP:0009742&b=MP:0005201&b=MP:0005205&b=MP:0002671&b=MP:0000592&b=MP:0008539&b=MP:0011967&b=MP:0011512&b=MP:0005264&b=MP:0002940&b=MP:0002183&b=MP:0005536&b=MP:0003717&b=MP:0003578&b=MP:0002376&b=MP:0002376&b=MP:0011091&b=MP:0010579&b=MP:0006405&b=MP:0002189&b=MP:0002633&b=MP:0000107&b=MP:0008947&b=MP:0002444&b=MP:0002183&b=MP:0009931&b=MP:0004369&b=MP:0001196&b=MP:0001262&b=MP:0001654&b=MP:0000063&b=MP:0002966&b=MP:0011098&b=MP:0002066&b=MP:0004618&b=MP:0005332&b=MP:0001363&b=MP:0002100&b=MP:0005387&b=MP:0011099&b=MP:0005017&b=MP:0002830&b=MP:0004025&b=MP:0011087&b=MP:0002191&b=MP:0000480&b=MP:0011098&b=MP:0000569&b=MP:0002429&b=MP:0003631&b=MP:0000565&b=MP:0000511&b=MP:0005375&b=MP:0000229&b=MP:0005065&b=MP:0001780&b=MP:0008111&b=MP:0004792&b=MP:0005202&b=MP:0001750&b=MP:0003308&b=MP:0005458&b=MP:0005599&b=MP:0008446&b=MP:0000841&b=MP:0005329&b=MP:0008456&b=MP:0000352&b=MP:0002833&b=MP:0011091&b=MP:0000371&b=MP:0009322&b=MP:0000367&b=MP:0005172&b=MP:0002705&b=MP:0005463&b=MP:0005292&b=MP:0001893&b=MP:0001516&b=MP:0001045&b=MP:0000607&b=MP:0001790&b=MP:0002083&b=MP:0000102&b=MP:0005026&b=MP:0005378&b=MP:0000715&b=MP:0000934&b=MP:0008553&b=MP:0009772&b=MP:0000520&b=MP:0000752&b=MP:0008158&b=MP:0001891&b=MP:0001473&b=MP:0001752&b=MP:0001332&b=MP:0002694&b=MP:0004187&b=MP:0011612&b=MP:0004336&b=MP:0009661&b=MP:0000511&b=MP:0008078&b=MP:0011087&b=MP:0001076&b=MP:0005634&b=MP:0011085&b=MP:0010210&b=MP:0001489&b=MP:0008450&b=MP:0003631&b=MP:0001982&b=MP:0004004&b=MP:0006138&b=MP:0002727&b=MP:0003339&b=MP:0002169&b=MP:0005111&b=MP:0003012&b=MP:0011085&b=MP:0001293&b=MP:0006395&b=MP:0005654&b=MP:0001867&b=MP:0005376&b=MP:0001732&b=MP:0002764&b=MP:0009868&b=MP:0005387&b=MP:0008025&b=MP:0001288&b=MP:0008181&b=MP:0000702&b=MP:0006143&b=MP:0000851&b=MP:0004029&b=MP:0005606&b=MP:0002239&b=MP:0000913&b=MP:0002792&b=MP:0001923&b=MP:0000737&b=MP:0003012&b=MP:0001156&b=MP:0001463&b=MP:0002463&b=MP:0005546&b=MP:0002703&b=MP:0005592&b=MP:0004673&b=MP:0009021&b=MP:0001698&b=MP:0010386&b=MP:0001785&b=MP:0009544&b=MP:0002078&b=MP:0005367&b=MP:0001399&b=MP:0005463&b=MP:0005397&b=MP:0004620&b=MP:0001258&b=MP:0005502&b=MP:0003077&b=MP:0000187&b=MP:0004953&b=MP:0001265&b=MP:0005361&b=MP:0004020&b=MP:0000864&b=MP:0000715&b=MP:0001935&b=MP:0001081&b=MP:0005385&b=MP:0002118&b=MP:0008396&b=MP:0002063&b=MP:0002018&b=MP:0009808&b=MP:0002442&b=MP:0005671&b=MP:0002006&b=MP:0004757&b=MP:0001360&b=MP:0002908&b=MP:0000691&b=MP:0002432&b=MP:0002432&b=MP:0005350&b=MP:0005387&b=MP:0003567&b=MP:0001262&b=MP:0002038&b=MP:0010373&b=MP:0002891&b=MP:0004084&b=MP:0000627&b=MP:0002114&b=MP:0002135&b=MP:0005606&b=MP:0009146&b=MP:0002451&b=MP:0001260&b=MP:0000933&b=MP:0005385&b=MP:0001698&b=MP:0008450&b=MP:0003354&b=MP:0002083&b=MP:0008516&b=MP:0002083&b=MP:0004810&b=MP:0008873&b=MP:0010323&b=MP:0008271&b=MP:0001303&b=MP:0000519&b=MP:0005376&b=MP:0000778&b=MP:0003934&b=MP:0003200&b=MP:0000119&b=MP:0001525&b=MP:0002629&b=MP:0005389&b=MP:0011096&b=MP:0008706&b=MP:0000745&b=MP:0005390&b=MP:0003984&b=MP:0002123&b=MP:0000951&b=MP:0002447&b=MP:0002206&b=MP:0000065&b=MP:0011087&b=MP:0004672&b=MP:0002602&b=MP:0008075&b=MP:0010878&b=MP:0005318&b=MP:0008560&b=MP:0001944&b=MP:0000876&b=MP:0008321&b=MP:0008126&b=MP:0001399&b=MP:0005034&b=MP:0008553&b=MP:0005584&b=MP:0000443&b=MP:0000592&b=MP:0005105&b=MP:0001790&b=MP:0005385&b=MP:0005333&b=MP:0000899&b=MP:0001524&b=MP:0002460&b=MP:0009108&b=MP:0008458&b=MP:0001488&b=MP:0010070&b=MP:0002026&b=MP:0005367&b=MP:0002086&b=MP:0004985&b=MP:0002075&b=MP:0008271&b=MP:0001925&b=MP:0005272&b=MP:0002083&b=MP:0002676&b=MP:0000111&b=MP:0009038&b=MP:0000267&b=MP:0004100&b=MP:0005291&b=MP:0001629&b=MP:0004702&b=MP:0009969&b=MP:0000108&b=MP:0000150&b=MP:0001260&b=MP:0002708&b=MP:0005318&b=MP:0003644&b=MP:0001926&b=MP:0002825&b=MP:0002092&b=MP:0005344&b=MP:0001211&b=MP:0005459&b=MP:0001053&b=MP:0005502&b=MP:0009645&b=MP:0000694&b=MP:0000601&b=MP:0001433&b=MP:0005027&b=MP:0008450&b=MP:0001685&b=MP:0001828&b=MP:0009322&b=MP:0005025&b=MP:0002795&b=MP:0000966&b=MP:0005464&b=MP:0003960&b=MP:0009914&b=MP:0011157&b=MP:0002161&b=MP:0001935&b=MP:0001539&b=MP:0003082&b=MP:0002144&b=MP:0009402&b=MP:0000370&b=MP:0004073&b=MP:0011252&b=MP:0003631&b=MP:0000240&b=MP:0000036&b=MP:0009788&b=MP:0003921&b=MP:0002940&b=MP:0001354&b=MP:0005448&b=MP:0001325&b=MP:0005397&b=MP:0002083&b=MP:0000914&b=MP:0005301&b=MP:0008025&b=MP:0002060&b=MP:0003631&b=MP:0001306&b=MP:0008664&b=MP:0000715&b=MP:0002727&b=MP:0002651&b=MP:0004618&b=MP:0000388&b=MP:0001552&b=MP:0005367&b=MP:0006320&b=MP:0010300&b=MP:0011704&b=MP:0008512&b=MP:0005034&b=MP:0001399&b=MP:0002310&b=MP:0003631&b=MP:0002659&b=MP:0001906&b=MP:0008045&b=MP:0005387&b=MP:0001393&b=MP:0011098&b=MP:0000035&b=MP:0004952&b=MP:0008753&b=MP:0004804&b=MP:0004762&b=MP:0005168&b=MP:0011098&b=MP:0011110&b=MP:0005384&b=MP:0008450&b=MP:0004856&b=MP:0011207&b=MP:0003886&b=MP:0000755&b=MP:0008337&b=MP:0001262&b=MP:0005293&b=MP:0008267&b=MP:0002451&b=MP:0001406&b=MP:0002727&b=MP:0002910&b=MP:0002036&b=MP:0002418&b=MP:0000588&b=MP:0008208&b=MP:0011902&b=MP:0000925&b=MP:0002841&b=MP:0000914&b=MP:0003840&b=MP:0000852&b=MP:0006009&b=MP:0004404&b=MP:0002083&b=MP:0000162&b=MP:0000599&b=MP:0001236&b=MP:0002802&b=MP:0002229&b=MP:0009177&b=MP:0001326&b=MP:0000240&b=MP:0002051&b=MP:0005668&b=MP:0005554&b=MP:0010019&b=MP:0003890&b=MP:0002411&b=MP:0011215&b=MP:0001522&b=MP:0005426&b=MP:0005581&b=MP:0011097&b=MP:0008168&b=MP:0001399&b=MP:0009006&b=MP:0001876&b=MP:0005551&b=MP:0003586&b=MP:0003012&b=MP:0011108&b=MP:0008577&b=MP:0011091&b=MP:0002876&b=MP:0002391&b=MP:0000414&b=MP:0005441&b=MP:0000222&b=MP:0001146&b=MP:0002118&b=MP:0001438&b=MP:0000702&b=MP:0003675&b=MP:0008034&b=MP:0008673&b=MP:0004452&b=MP:0002902&b=MP:0002060&b=MP:0002083&b=MP:0001392&b=MP:0003884&b=MP:0003717&b=MP:0005387&b=MP:0001958&b=MP:0001393&b=MP:0008706&b=MP:0000060&b=MP:0011087&b=MP:0001952&b=MP:0002115&b=MP:0005027&b=MP:0002668&b=MP:0005376&b=MP:0003313&b=MP:0001860&b=MP:0005386&b=MP:0002816&b=MP:0001297&b=MP:0008146&b=MP:0001967&b=MP:0001325&b=MP:0003364&b=MP:0003012&b=MP:0005331&b=MP:0010770&b=MP:0009435&b=MP:0009432&b=MP:0004989&b=MP:0002083&b=MP:0008673&b=MP:0000753&b=MP:0005616&b=MP:0011520&b=MP:0003890&b=MP:0010927&b=MP:0005202&b=MP:0002833&b=MP:0000013&b=MP:0002811&b=MP:0002089&b=MP:0001263&b=MP:0002407&b=MP:0000787&b=MP:0006410&b=MP:0002027&b=MP:0001293&b=MP:0000208&b=MP:0000767&b=MP:0011260&b=MP:0000182&b=MP:0004021&b=MP:0000285&b=MP:0008700&b=MP:0001473&b=MP:0001463&b=MP:0003329&b=MP:0011098&b=MP:0001402&b=MP:0005350&b=MP:0011091&b=MP:0002950&b=MP:0002891&b=MP:0000745&b=MP:0002442&b=MP:0011087&b=MP:0003631&b=MP:0009678&b=MP:0000079&b=MP:0001443&b=MP:0002145&b=MP:0001262&b=MP:0000413&b=MP:0002161&b=MP:0004323&b=MP:0004148&b=MP:0002764&b=MP:0000351&b=MP:0002417&b=MP:0003012&b=MP:0002743&b=MP:0001447&b=MP:0000465&b=MP:0009075&b=MP:0004046&b=MP:0001552&b=MP:0001698&b=MP:0000136&b=MP:0002196&b=MP:0004485&b=MP:0004862&b=MP:0004383&b=MP:0000562&b=MP:0000160&b=MP:0010221&b=MP:0008271&b=MP:0001265&b=MP:0003132&b=MP:0002705&b=MP:0003051&b=MP:0001260&b=MP:0000610&b=MP:0006036&b=MP:0001297&b=MP:0000747&b=MP:0001806&b=MP:0002703&b=MP:0002210&b=MP:0006138&b=MP:0010771&b=MP:0002113&b=MP:0005017&b=MP:0011101&b=MP:0002098&b=MP:0003208&b=MP:0003627&b=MP:0005493&b=MP:0002169&b=MP:0002865&b=MP:0000920&b=MP:0005455&

**Comment by harryhoch** [comment]
Chuck:

Looks like a problem with http://toaster.lbl.gov:9031/compareAttributeSets. Note that Chris’ example at 
http://secret-harbor-1370.herokuapp.com/compare/OMIM_143100/MGI:3698411.json

is also currently broken. Suggest you ask Chris what’s up.

harry
On 29 Oct 2013, at 10:53 AM, cborromeo notifications@github.com wrote:

> Hello,
> I am trying to use this call and I receive this response:
> 
> TypeError: Cannot call method "decodeToString" of undefined
> ringo/httpclient.js, line 315
> 
> Script Stack
> 
> at ringo/httpclient.js:315 (anonymous)
> at lib/monarch/api.js:67 (anonymous)
> at lib/monarch/api.js:1574 (anonymous)
> at lib/monarch/api.js:1567 (anonymous)
> at lib/monarch/api.js:1341 (anonymous)
> at lib/monarch/web/webapp.js:431 (anonymous)
> at stick/lib/middleware/route.js:215 (route)
> at stick/lib/middleware/params.js:102 (anonymous)
> at stick/lib/middleware/static.js:62 (static)
> at stick/lib/stick.js:37 (app)
> at ringo/jsgi/connector.js:42 (handleRequest)
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by cmungall** [comment]
Thanks for tracking the URL down to the owlsim server. Am looking into this. Seems to work with subsets of the above list.

**Comment by cmungall** [comment]
How are your servlet skills? Seems to be something happening at the servlet layer when the URL is too long...

**Comment by harryhoch** [comment]
Honestly, my servlet skills are pretty meager indeed. To start, I'd need some way to run this locally - would be pretty hard to see what 's going on without being able to look at the logs,etc...

**Comment by cmungall** [comment]
fix also deployed to heroku, so URL above works (but for future reference, the giant toaster URL will return a 413, you need to use POST for large requests)
