### ISSUE TITLE
Autocomplete in /analyze/phenotypes doesn't recognize "Drug Metabolism, Poor, CYP2D6-Related"

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1003]
Not sure what the underlying issue is but it is not possible to get to "Drug Metabolism, Poor, CYP2D6-Related" in beta.monarchinitiative.org/analyze/phenotypes. Interestingly, it does work fine on site search autocomplete.

![screen shot 2015-10-12 at 22 48 22](https://cloud.githubusercontent.com/assets/3658863/10446842/d4423d7a-7133-11e5-92d1-827f3c0a8d04.png)

![screen shot 2015-10-12 at 22 46 06](https://cloud.githubusercontent.com/assets/3658863/10446849/e35f1972-7133-11e5-883f-a0f380db43fc.png)

**Comment by kshefchek** [comment]
This sounds like an ontology issue, is Drug Metabolism, Poor, CYP2D6-Related miscategorized as a disease?

**Comment by kshefchek** [comment]
Looks like this is a disease without any phenotype annotations, so I'm thinking this is non-issue?  Please re-open if I'm incorrect.

**Comment by jmcmurry** [comment]
of course. face. palm. thanks.
