### ISSUE TITLE
compare API doesn't accept certain genotype IDs

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1004]
I was working on phenogrid genotype expansion. I used the `http://beta.monarchinitiative.org/compare` API to get data results by providing a list of phenotypes IDs and a list of genotype IDs, for example: 

`http://beta.monarchinitiative.org/compare/HP:0012774+HP:0002650/MGI:5575552,MONARCH:9b8f5c3332f6cee4a3759c3de8219891`

This URL doesn't generate a valid JSON response. It does sometimes if I remove the `MONARCH:` prefixed ID.

Can anyone examine this? Thanks!

**Comment by kshefchek** [comment]
This is a bug and we should be returning something here.  I imagine it's because the Monarch ID cannot be found, I can't find it in [SciGraph](http://rosie.crbs.ucsd.edu:9000/scigraph/graph/MONARCH:9b8f5c3332f6cee4a3759c3de8219891?project=*). Where is this ID coming from?

**Comment by yuanzhou** [comment]
I got it from here: http://beta.monarchinitiative.org/gene/MGI:96794/genotype_list.json

There are several genotypes IDs are prefixed with `MONARCH:`

**Comment by kshefchek** [comment]
@nlwashington these are coming from our production golr, is our production datagraph out of sync with this server?
