### ISSUE TITLE
Sometimes `metadata` property is missing in the compare results

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1005]
I'm getting a list of genotypes that are associated to a specific gene, then use the `compare` api to get matches between the genotypes and a list of phenotypes. I tried two mouse genes, during the compare phrase, the returned matches doesn't have the `metadata` property for the second genotypes/phenotypes query. 

![capture](https://cloud.githubusercontent.com/assets/195873/10488202/99acd99e-7265-11e5-8935-68741646318b.PNG)

Please click the image to see the full version.

**Comment by kshefchek** [comment]
Any chance you could the paste the failing queries here?  What is expected in the metadata field?

**Comment by yuanzhou** [comment]
Here is a query that returns the `metadata`:

http://beta.monarchinitiative.org/compare/HP:0000726+HP:0000746+HP:0001300+HP:0002367+HP:0000012+HP:0000716+HP:0000739+HP:0001332+HP:0001347+HP:0002063+HP:0002067+HP:0002172+HP:0002322+HP:0007159+HP:0009466+HP:0001972+HP:0003502+HP:0005190+HP:0001763+HP:0003318+HP:0001371+HP:0001380+HP:0001394+HP:0001156+HP:0001159+HP:0001004+HP:0010886+HP:0006530+HP:0004792+HP:0002816+HP:0000954+HP:0000974+HP:0000765+HP:0000602+HP:0002240+HP:0030084+HP:0000049+HP:0000028+HP:0000175+HP:0000204+HP:0000202+HP:0000316+HP:0000343+HP:0000349+HP:0002023+HP:0000327+HP:0002055+HP:0000394+HP:0000463+HP:0000431+HP:0000494+HP:0000484+HP:0000486+HP:0000508+HP:0009748+HP:0007018+HP:0001773+HP:0001769+HP:0003311+HP:0001544+HP:0001508+HP:0003196+HP:0001249+HP:0001187+HP:0001169+HP:0012774+HP:0002650/MGI:3811489,MGI:2170676,MGI:5443937,MGI:3628465

And this one doesn't:

http://beta.monarchinitiative.org/compare/HP:0000726+HP:0000746+HP:0001300+HP:0002367+HP:0000012+HP:0000716+HP:0000739+HP:0001332+HP:0001347+HP:0002063+HP:0002067+HP:0002172+HP:0002322+HP:0007159+HP:0009466+HP:0001972+HP:0003502+HP:0005190+HP:0001763+HP:0003318+HP:0001371+HP:0001380+HP:0001394+HP:0001156+HP:0001159+HP:0001004+HP:0010886+HP:0006530+HP:0004792+HP:0002816+HP:0000954+HP:0000974+HP:0000765+HP:0000602+HP:0002240+HP:0030084+HP:0000049+HP:0000028+HP:0000175+HP:0000204+HP:0000202+HP:0000316+HP:0000343+HP:0000349+HP:0002023+HP:0000327+HP:0002055+HP:0000394+HP:0000463+HP:0000431+HP:0000494+HP:0000484+HP:0000486+HP:0000508+HP:0009748+HP:0007018+HP:0001773+HP:0001769+HP:0003311+HP:0001544+HP:0001508+HP:0003196+HP:0001249+HP:0001187+HP:0001169+HP:0012774+HP:0002650/MGI:3722284,MGI:3698248,MGI:3811219,MGI:2167059

The `maxMaxIC` in `metadata` info is used to create the phenogrid color scores. 

![capture](https://cloud.githubusercontent.com/assets/195873/10489361/c976ad3a-726a-11e5-9d34-180a359f7f2b.PNG)
