### ISSUE TITLE
Add request for user feedback

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1009]
We need to be able to understand how people are using our resource and to be able to collect this information for funding purposes. 

Can we add some kind of banner at our site, something like Wikipedia does, that says "Like our resource? We need user stories to help keep us funded. Tell us how you are using our resource"

@pnrobinson @drseb @damiansm @julesjacobsen should probably do the same for the HPO and Exomiser sites.

**Comment by jmcmurry** [comment]
Related https://github.com/monarch-initiative/impact/issues/15

**Comment by jmcmurry** [comment]
Saw this and yet duplicated the ticket anyway. I will close this and move the comment to the new ticket since that is where the thread is now.
