### ISSUE TITLE
short finger should not be subclass of short stature

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#1011]
the newest load of our ontologies indicates that 
short finger http://localhost:8080/phenotype/HP:0009566
is an inferred subclass of short stature HP:0004322

this is not right.  please fix in the relevant ontology. @cmungall or @mellybelly

**Comment by cmungall** [comment]
There is something a bit funny about short finger, see linked ticket. But cannot replicate this in Protege.

I also don't see it here:
http://lurch.crbs.ucsd.edu:9000/scigraph/graph/neighbors/HP:0009566.json

**Comment by jmcmurry** [comment]
I can't replicate either; closing
