### ISSUE TITLE
User Feedback button and form

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1013]
For now, more obvious feedback button on each resource page rather than just in the "contact" menu

Thoughts? @cmungall @nlwashington @mellybelly @DoctorBud  Is there anything on this list easily doable by end of October?

**Comment by jmcmurry** [comment]
Related to https://github.com/monarch-initiative/impact/issues/15

**Comment by jmcmurry** [comment]
HTML mockup screenshot below:
![screen shot 2015-10-21 at 17 35 04](https://cloud.githubusercontent.com/assets/3658863/10654032/20e12aa0-781a-11e5-8e47-1e7926138e59.png)

Remaining to do:
- [x] Get consensus that these are the right questions to be asking @mellybelly 
- [ ] Get IRB approval (harry); we can collect still feedback for internal purposes before getting IRB approval, but it is best to have IRB in place if we ever want to be able to publicise or publish the feedback
- [x] Enable dropdown screen to be moved or at least resized / scrolled
- [ ] Change the behavior to go to next field on enter as well as tab
- [ ] Grey out the email field unless one of the "contact me" items is checked?
- [ ] Implement a way to capture the URL from which the feedback button was clicked

**Comment by harryhoch** [comment]
comments on questions

'How easy was the Monarch site to use and what can we do to make it better." is a bit clunky and might work better as two questions.

"where you able to accomplish your goals" & 
"What can we change to make the site more useful for you"

these questions frankly look like they get a bit too close to research to me.

Make sure the email is optional.

**Comment by DoctorBud** [comment]
Might want to give folks the option of progressive disclosure, with the easiest-to-answer and high-priority questions first, followed by a 'We'd like to hear more...' button that reveals a more detailed questionnaire. Otherwise you might turn people off that would otherwise give us 'light' feedback. And of course, there is the meta information about whether the user answered the short form or the long one.

I'd favor checkboxes, menu selection, and radio buttons over free text in the first section, if we decide to use progressive disclosure. That way we capture SOME feedback and don't scare people with big forms. We can and should evolve the feedback form as we move forward; the decisions we make now are not cast in stone. Part of what we will learn is what kind of feedback gathering is most effective.

**Comment by DoctorBud** [comment]
In a similar vein, I'd lose the Monarch-marketing text and just start with 'We use feedback from users like you'. The reasoning is that our users' time is valuable and their attention and feedback to Monarch is valuable, so let's make it easy for them.

**Comment by jmcmurry** [comment]
The first sentence was my stab at implementing the following recommendation of Harry's. I don't fundamentally object to it, but seeing the implementation, I favor dropping this info as it is already a bit crowded.

> but we should also add some surrounding text emphasizing our commitment to making good useful tools
> 
> -Harry
> 
> Might want to give folks the option of progressive disclosure, with the easiest-to-answer and high-priority questions first, followed by a 'We'd like to hear more...' button that reveals a more detailed questionnaire. 
> - Dan

Agreed, however, I think we can get away without a "more" button if we simplify a bit. How is this? It desperately needs some padding and layout help which I know Dan knows how to do better than I, but aside from that.

![screen shot 2015-10-21 at 22 04 58](https://cloud.githubusercontent.com/assets/3658863/10657437/50c622b8-7840-11e5-91ef-0f660301aea0.png)

**Comment by harryhoch** [comment]
@jmcmurry, I had thought we were going to avoid LIkerts. I strongly disagree with the claim that they are going to be useful in this context.

the four checkboxes are way too much legalese. Suggest that we just do everything internally for now and not use any of the information for testimonials, etc., until we go through an IRB review.

**Comment by DoctorBud** [comment]
I have a new version based upon Julie's draft at:

[https://rawgit.com/DoctorBud/6894e8cab7a9e9abb22f/raw/20f35a40fbd9b20820e0239b7dc09931d0214cd6/f3.html](https://rawgit.com/DoctorBud/6894e8cab7a9e9abb22f/raw/20f35a40fbd9b20820e0239b7dc09931d0214cd6/f3.html)

**Comment by harryhoch** [comment]
I like the draggability. Comments about legalese and Likert scales still stand.

Regarding the last question, it's usually best to not ask a yes/no question like that.  if we must ask about other data sources or tools, please ask "what data or tools would make Monarch more useful for you?"  However, that is similar to "How can we improve the Monarch experience?" that question should probably be rewritten in any case, perhaps to "How can we make Monarch more useful to you?"

Writing good survey questions is much harder than it might seem.

**Comment by jmcmurry** [comment]
> @jmcmurry, I had thought we were going to avoid LIkerts.

I don't think the "is useful to me" question was the right one, but was trying to incorporate Dan's suggestion of easy "light" feedback. I don't think we need the "how easy..." question, but I had a hard time cooking up something that was radio-buttonable. "How easy..." can be removed completely, I think, without losing a lot.

> it's usually best to not ask a yes/no question like "Do you have additional suggestions..."

If you prefer, we can phrase it differently, but chances of an answer comprised solely of "yes" is slim. "no" is harmless.

**Comment by harryhoch** [comment]
My suggestion would be to 
1. remove "how easy...."
2. combine how can we improve..." and "Do you have any additional comments" into one question reading "how can we make Monarch more useful for you".
3. collapse the multiple checkboxes into one.

**Comment by jmcmurry** [comment]
Fine to remove "how easy..."

How about: "What data, tools, or functionality would make Monarch more useful to you?" and nix the "other comments"

As for 3 we may find that 1 box is so restrictive that no one checks it. Is four boxes really so onerous? Dan what do you think?

**Comment by harryhoch** [comment]
What's wrong with "how can we make Monarch more useful?"  I can't think of anything that wouldn't be data, tools, or functionality, but users might. I'm also not sure how "tools" and "functionality" differ. 

as far as the four text boxes go, we have 
1. it is ok to publish aggregate analyses that include my feedback
2. it is ok to publicly quote my feedback or excerpts of my feedback

I think these two are hard to tease apart. I assume number 1 means that we might analyze it and include it in descriptive statistics or model, but users might not get that.
3. it is ok to contact me with questions about my feedback
4. it is ok to contact me to get general feedback about the Monarch user experience

again, since the feedback is about the monarch user experience, any questions that we might ask them about their feedback would transitively involve getting general feedback about Monarch. 

How about one that says 

"it is ok to quote my comments or to contact me to discuss my use of Monarch" 

I also vote against the user of "user experience". Not a term that I like.

**Comment by jmcmurry** [comment]
OK, how about
"it is ok to quote my comments"
"it is ok to contact me for clarification or additional feedback"
Differentiating these is IMHO important as the first requires no time investment on the part of the commenter, the second does. I was differentiating clarification from additional feedback because "clarification" may be things the commenter cares about whereas "additional feedback" sounds like an open invitation to be bugged about UX in perpetuity.

**Comment by jmcmurry** [comment]
Also, @DoctorBud could you put twitter back in the contact footer? Thanks
Love the dragging feature, nice.

**Comment by harryhoch** [comment]
@jmcmurry  we could always add text promising not to be pests...

**Comment by jmcmurry** [comment]
How about "it is ok to contact me for clarification or _occasional_ additional feedback" ? 

If not, what specific language do you propose? Regardless, I still think that differentiating the two would be useful. We ourselves don't write brilliant crystal clear tickets. We don't want a user to opt out of being contacted (for clarification) out of reluctance to OK an open-ended commitment.

**Comment by harryhoch** [comment]
@jmcmurry I can't imagine that we're going to have that many people coming in, and as I said, we can promise to be nice...

**Comment by jmcmurry** [comment]
Let's separate concerns. 
1) Do we say "promise not to be pests"
--I'm fine with this

2) Do we collapse the checkboxes into one.
--I don't think it is overwhelmingly important, but think there's more to lose by collapsing them. Collapsing has nothing to do with triaging the volume of people coming in, but with respecting the user by giving the user control about what s/he is contacted for. Not providing both options could make more people opt out altogether.

**Comment by harryhoch** [comment]
@jmcmurry, the reality is that we're not going to have many people who we'll be contacting much.

**Comment by jmcmurry** [comment]
But they don't know that. I do not understand the advantage of one but I am willing to role with it for the sake of moving this forward. We can change it later if we find people opt out of being contacted. Or that they click feedback button but don't follow through. Let's be sure to log that kind of aborted activity just in case.

**Comment by harryhoch** [comment]
@jmcmurry just saying that in the spirit of thinking that the assurance that we won't bug them might be enough. 

agreed. let's proceed and monitor closely.

**Comment by jmcmurry** [comment]
In trying to mock this up to just move forward and keep it to a single checkbox, I couldn't find a natural way to say "We won't pester" while retaining the familiar first person checkbox format. We could: 

#### A) switch from first to third person:
- [ ]  It is OK to quote my feedback or to follow up with me
  (We promise not to pester)
  
  -- At best this feels disjointed, and at worst confuses who the pronouns "We" and "You" actually refer to. 

#### B) Third person only
- [ ] It is OK for the Monarch team to quote your feedback and follow up with you (We promise not to pester)
  
  -- Departure from the industry standard (That the person checking the box is "I")

#### C) First person only
- [ ] It is ok to quote my feedback, or contact me to follow up, provided you don't pester me
  
  -- The tone is offputting (Makes it sound like we assume that the users are disengaged / demanding)

#### D) Separate the concerns into two checkboxes
- [x] It is OK to quote my feedback 
- [x] It is OK follow up with me about my feedback
  - Conveys respect for user's time, without a specific proviso. (Time commitment differs between being quoted (0 minutes), being contacted (? minutes)
  - Logically separates concepts which do not overlap.
  - Feels visually less busy to me

Thus in context, my complete proposal is as follows:

---

Specific feedback from users like you is essential to guide future development and improvement of the Monarch experience. We welcome you to answer the questions below and/or contact us via links below.

##### What did you come to the Monarch site to do?

---

##### What could we improve to make this task easier for you?

---
- [x] It is OK to quote my feedback 
- [x] It is OK follow up with me about my feedback

email: ______________

[button: More feedback]
Any additional comments

---

I strongly favor option D else B if we absolutely must. If you have any alternative specific language or changes please speak now as this needs to be built and deployed by Wednesday. Thanks

**Comment by pnrobinson** [comment]
I think Julie's suggestion (D) is logical and that most people would understand it.

**Comment by harryhoch** [comment]
@jmcmurry, (d) is fine. We should discuss whether or not we want to put together a formal plan to do qualitative work with interested users.

**Comment by jmcmurry** [comment]
@harryhoch I would love to do something formal, but perhaps we should consider how far we can get informally as well. The formal approach takes more time to plan and execute but is more readily reportable. The informal approach can be done as needed (more frequently and less systematically) to keep feature development from getting off-track.

I've put together a [little spreadsheet skeleton](https://docs.google.com/spreadsheets/d/1v7H-lidE6PsE9zllatHGpKKo5XMKfKUxKBy-XIuI76k/edit#gid=0) to organize contact info for the various user types we have met along the way who may be willing to provide light, informal feedback. It would be great if the members of the Monarch team could contribute some names or suggestions of other kinds of information we would want to organize for each person. Perhaps one representative from each of the organizations solicited for statements of support [here](https://docs.google.com/spreadsheets/d/1PeYIqX9jrevyvbbJrCtYVCoxbKk82hkyel_ztkcM640/edit#gid=0). I'm not proposing that the spreadsheet serve a full-metal-jacket "SalesForce" type tool, but we may want to capture relevant notes like "Willing to beta test monthly" or "Contact only about features related to variants" or whatever. Thoughts?

**Comment by DoctorBud** [comment]
I have a PR up [here](https://github.com/monarch-initiative/monarch-app/pull/1034).

Here's what ./feedback.txt looks like after a few Feedback sessions:

```
~/MI/monarch-app feedback1$ tail -f feedback.txt
{"version":"1","response":{"goal":"asdasdas","improve":"dsaadsadsd","OKQuote":"on","OKFollowup":"on","email":"asddsads","additional":""}}
{"version":"1","response":{"goal":"dsadsdas","improve":"sdadasdas","OKQuote":"on","OKFollowup":"on","email":"adsads","additional":""}}
{"version":"1","response":{"goal":"","improve":"","OKQuote":"on","OKFollowup":"on","email":"","additional":""}}
{"version":"1","response":{"goal":"","improve":"","OKQuote":"on","OKFollowup":"on","email":"","additional":""}}
{"version":"1","response":{"goal":"","improve":"","OKQuote":"on","OKFollowup":"on","email":"","additional":""}}
{"version":"1","response":{"goal":"Well, technically I didn't come to the Monarch site, it was delivered to my web browser, and thence to my eyes and head.","improve":"Single-page App","OKQuote":"on","OKFollowup":"on","email":"dan@example.com","additional":"Well, I'd really like one of the new Teslas."}}
```

Here are some sshots:

<img width="747" alt="navbar" src="https://cloud.githubusercontent.com/assets/2450553/10770162/073b5832-7ca7-11e5-9fff-f2669da7d40d.png">

<img width="932" alt="form" src="https://cloud.githubusercontent.com/assets/2450553/10770201/3c2c7b20-7ca7-11e5-9e28-8aeb5ecbb9dc.png">

<img width="684" alt="thanks" src="https://cloud.githubusercontent.com/assets/2450553/10770226/56c9652e-7ca7-11e5-8e3a-6f873bf3d9bd.png">

**Comment by DoctorBud** [comment]
Hmmm. looks like the checkboxes OKQuote and OKFollowup are always ON in the datafile, which is incorrect. I will fix that.

Also, I should add a timestamp and the current window.location info to the feedback record.

**Comment by DoctorBud** [comment]
Note that feedback.txt is always appended to, so multiple runs of the monarch server will accumulate feedback. Eventually, we probably want to have a feedback rotation and archival process that keeps feedback.txt from growing too large (although that would be wild success for Monarch if our feedback.txt got too large).

**Comment by jmcmurry** [comment]
+1 Yay @DoctorBud :) My only suggestions would be to 
a) make the background grey smoke in lieu of yellow
b) make the email field a bit narrower and left justified (if possible, not crucial)

**Comment by DoctorBud** [comment]
New PR is [here](https://github.com/monarch-initiative/monarch-app/pull/1035).

The feedback.txt has been enhanced to include more metadata, and the checkbox issue is fixed.

The UI has been adjusted as per Julie's feedback, although it was difficult to get the email shortened without the layout looking wonky, so I made the email field a whole-line field like the rest of the text. Also added a border to match the textareas. I cleaned up the Thanks alert so the close box is in a more standard position.

I separated the Contact Monarch bottom section some more and centered the text.

Here's some sample feedback.txt output from the screenshots that follow:

```
{"metadata":{"version":"1","href":"http://0.0.0.0:8080/","time-utc":"Tue, 27 Oct 2015 21:59:22 GMT","time-local":"October 27, 2015 at 2:59:22 PM PDT"},"response":{"goal":"To win a brand new car!!!","improve":"Give me a brand new car!!!","OKQuote":"true","OKFollowup":"true","email":"dan@example.com","additional":"I really think y'all should consider giving me a new Tesla. And maybe an iPhone 6S too.\n\nHere's some random HTML text to see if our JSON encodes properly:\n        <div id=\"collapsed-navbar\" class=\"nav-collapse collapse\">\n            <ul class=\"nav navbar-nav\">\n                <li class=\"dropdown\">\n                    <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\">\n                        <i class=\"icon-th-large\"></i>Browse <b class=\"caret\"></b></a>\n                    <ul class=\"dropdown-menu\">\n                        <li><a href=\"/disease\">Diseases</a></li>\n"}}
{"metadata":{"version":"1","href":"http://0.0.0.0:8080/","time-utc":"Tue, 27 Oct 2015 22:00:04 GMT","time-local":"October 27, 2015 at 3:00:04 PM PDT"},"response":{"goal":"to see what's up","improve":"show me what's up","OKQuote":"false","OKFollowup":"false","email":"nobody@example.com","additional":"nope"}}
{"metadata":{"version":"1","href":"http://0.0.0.0:8080/page/about","time-utc":"Tue, 27 Oct 2015 22:02:59 GMT","time-local":"October 27, 2015 at 3:02:59 PM PDT"},"response":{"goal":"I'm on the /about page to show that the location and time are captured. The time when I submit is about 3:03pm PST. Nothing else is checked or filled out.","improve":"","OKQuote":"false","OKFollowup":"false","email":"","additional":""}}
```

<img width="874" alt="form2" src="https://cloud.githubusercontent.com/assets/2450553/10774165/d9fccfe8-7cbc-11e5-879c-4fa0ca61a830.png">

<img width="593" alt="thanks2" src="https://cloud.githubusercontent.com/assets/2450553/10774172/e8ef22c6-7cbc-11e5-9469-a153cee8f6c5.png">

<img width="865" alt="form2_about" src="https://cloud.githubusercontent.com/assets/2450553/10774201/0f18d8ca-7cbd-11e5-8c63-b289bacd3741.png">

**Comment by jmcmurry** [comment]
+1 Great! Let's move onto more exciting things :)

**Comment by yuanzhou** [comment]
Can we add a simple form validation to the feedback form? I was checking out this form and hit the submit button without filling in anything and it showed me the Thank You message.

**Comment by jmcmurry** [comment]
+1, also, I would prefer that the button be styled consistently with our other buttons (standard blue one). Thanks

@DoctorBud could you perhaps handle both of these? Thanks :)

**Comment by jmcmurry** [comment]
Now that styling is done and is being merged today, I'm closing this.
