### ISSUE TITLE
make models clickable in model viewer

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#102]
It would be great if the models on the top of the viewer were links to their respective model pages.

**Comment by frdougal** [comment]
That's a good idea mellybelly.  When the user clicks a model label I use the genotype data for the MGI models (ex: /genotype/MGI_1101781.json) to populate the Item Details box.   This JSON does not contain an URL I can use.  Do you want me to make the columns clickable and open the Monarch genotype page (ex: /genotype/MGI_1101781) in a new tab?  This would replace the current behavior to display the data in Item Details.

**Comment by mellybelly** [comment]
Well, this is an interesting question. You could make the models viewer bigger if you didn't need the details box, which would be nice. I do think that the link should go to the model page as you suggest, in a new tab. Perhaps only display the phenotype subsumer in a hover over on the colored box and do away with the details box? The scoring is largely taken care of by the color coding.

**Comment by cmungall** [comment]
I find the click-to-view-in-box behavior a little unintuitive. I was expecting something on mouseover. The don't "look clickable". In fact I didn't realize you could get the metadata in the box until Nicole told me.

(I am famously terrible at navigating UIs however...)

**Comment by frdougal** [comment]
I think I need to explain the "logic" behind the Item Details box.  (Then again, if I have to explain it the box is probably not very useful...)  I thought there would be a lot of information about the models, phenotypes, and similarity scores.  I'm not a big fan of putting a lot of information into an onhover tooltip.  As a user, I get frustrated if I need to scroll a tooltip box.

I'm fine if we want to make the text labels for the phenotypes and models clickable.  These will open a new tab for the user to take them to the appropriate page.  We can use onhover events and bring up more info with a tooltip.  However, the OwlSim scores are really most innovative part of this visualization.  We should plan on using some real estate to explain the scoring metrics and what they mean.

**Comment by harryhoch** [comment]
superseded by various elements in https://github.com/monarch-initiative/monarch-app/issues/136
