### ISSUE TITLE
502 error for variant/MGI:3794632

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#1027]
i tried to get to
http://monarchinitiative.org/variant/MGI:3794632
or 
http://beta.monarchinitiative.org/variant/MGI:3794632

but it seems i only get a 502 error.
other pages seem to resolve okay.

**Comment by nlwashington** [comment]
false.  actually, i can't seem to load any of the tabs on the main monarch or beta.  for example:
http://monarchinitiative.org/gene/NCBIGene:64093

**Comment by kshefchek** [comment]
Replacing with https://support.crbs.ucsd.edu/browse/CRBS-10629
