### ISSUE TITLE
Monarch API Status

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1030]
It's very helpful to have a monarch api status page that shows all the available api and their status.

According to @cmungall and @DoctorBud there are two API status now:

http://beta.monarchinitiative.org/admin/introspect

http://monarchinitiative.org/status

**Comment by yuanzhou** [comment]
Can we also set up some API downtime monitoring services? @kshefchek 

I was using https://uptimerobot.com/ for a former project, and I got email notifications whenever the server or API experienced down times. Actually this morning I noticed some HTTP 502 form the beta server for a short time of period.

**Comment by kltm** [comment]
We like uptimerobot as well for many services. However, as memory usage, downtimes, CPU, and disk seem to be recurring issues  as the software develops, it might be worth spending a little time on a nagios or munin (meh) deployment to keep an eye on things.
