### ISSUE TITLE
Missing properties in compare API returned JSON

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1032]
@kshefchek  I think this issue is related to #1024  and #1004 

http://beta.monarchinitiative.org/compare/HP:0000726+HP:0000746+HP:0001300+HP:0002367+HP:0000012+HP:0000716+HP:0000739+HP:0001332+HP:0001347+HP:0002063+HP:0002067+HP:0002172+HP:0002322+HP:0007159+HP:0009466+HP:0001972+HP:0003502+HP:0005190+HP:0001763+HP:0003318+HP:0001371+HP:0001380+HP:0001394+HP:0001156+HP:0001159+HP:0001004+HP:0010886+HP:0006530+HP:0004792+HP:0002816+HP:0000954+HP:0000974+HP:0000765+HP:0000602+HP:0002240+HP:0030084+HP:0000049+HP:0000028+HP:0000175+HP:0000204+HP:0000202+HP:0000316+HP:0000343+HP:0000349+HP:0002023+HP:0000327+HP:0002055+HP:0000394+HP:0000463+HP:0000431+HP:0000494+HP:0000484+HP:0000486+HP:0000508+HP:0009748+HP:0007018+HP:0001773+HP:0001769+HP:0003311+HP:0001544+HP:0001508+HP:0003196+HP:0001249+HP:0001187+HP:0001169+HP:0012774+HP:0002650/ZFIN:ZDB-GENO-080606-613,ZFIN:ZDB-GENO-991201-127,ZFIN:ZDB-GENO-991130-127,ZFIN:ZDB-GENO-101216-3

This compare only returns the `a` part in the JSON, missing `b`, `metadata` and `resource`.

**Comment by kshefchek** [comment]
Also related: https://github.com/monarch-initiative/monarch-app/issues/1005

**Comment by yuanzhou** [comment]
`metadata` issue has been addressed in PR #1069 , my question is even if there's no matches `b`, why we still have `metadata.maxMaxIC` (used to generate color scale for Uniqueness calculation method in Phenogrid)? Does this mean the `metadata.maxMaxIC` is a fixed value? If so, we don't even need to get the `maxMaxIC` from `metadata` from each owlsim result. @harryhoch any thoughts?

Example: 

http://beta.monarchinitiative.org/compare/HP:0000726+HP:0000746+HP:0001300+HP:0002367+HP:0000012+HP:0000716+HP:0000739+HP:0001332+HP:0001347+HP:0002063+HP:0002067+HP:0002172+HP:0002322+HP:0007159+HP:0009466+HP:0001972+HP:0003502+HP:0005190+HP:0001763+HP:0003318+HP:0001371+HP:0001380+HP:0001394+HP:0001156+HP:0001159+HP:0001004+HP:0010886+HP:0006530+HP:0004792+HP:0002816+HP:0000954+HP:0000974+HP:0000765+HP:0000602+HP:0002240+HP:0030084+HP:0000049+HP:0000028+HP:0000175+HP:0000204+HP:0000202+HP:0000316+HP:0000343+HP:0000349+HP:0002023+HP:0000327+HP:0002055+HP:0000394+HP:0000463+HP:0000431+HP:0000494+HP:0000484+HP:0000486+HP:0000508+HP:0009748+HP:0007018+HP:0001773+HP:0001769+HP:0003311+HP:0001544+HP:0001508+HP:0003196+HP:0001249+HP:0001187+HP:0001169+HP:0012774+HP:0002650/ZFIN:ZDB-GENO-080606-613,ZFIN:ZDB-GENO-991201-127,ZFIN:ZDB-GENO-991130-127,ZFIN:ZDB-GENO-101216-3

Here is the JOSN output from this URL:

![capture](https://cloud.githubusercontent.com/assets/195873/11092328/86d9885c-8850-11e5-9d3e-93e4297082c2.PNG)

**Comment by yuanzhou** [comment]
I also tested several other compare URLs and noticed that the returned `metadata` content are the same. I'm guessing the `metadata` is fixed value. @kshefchek can you confirm this? The `metadata.maxMaxIC` is always 14.74287. 

There's also an email from @nlwashington a while ago:

Correct

**Comment by yuanzhou** [comment]
![c976ad3a-726a-11e5-9d34-180a359f7f2b](https://cloud.githubusercontent.com/assets/195873/11093623/4d6ae1e8-8859-11e5-9389-eaa41a8e7fc5.PNG)

**Comment by nlwashington** [comment]
yes, the metadata is concerning the entire owlsim server, and it's the stats on the entire corpus.

**Comment by nlwashington** [comment]
while the same no matter what compare or analyze call you do, it may change from build to build.

**Comment by yuanzhou** [comment]
@nlwashington what do you mean by "it may change from build to build"? Does this mean it's a fixed value but may vary sometimes? So hard code it in phenogrid is not a stable solution? I think as long as I can find it from each owlsim JSON, there's no need to hard code it. Chances are it may not be used if there's non"b".

**Comment by nlwashington** [comment]
no, you cannot hardcode these values.  anytime there is new data on our end, we restart the server and the values will be recomputed.  the content is added to the owlsim JSON before returning the result, so you should always get it back.

**Comment by yuanzhou** [comment]
@nlwashington got it, thanks a lot for the info.
