### ISSUE TITLE
Add a route for phenotypes identified by unique label

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1038]
Scenario:

A group wants to link to a monarch phenotype page; however, they have not stored the phenotype ID, only the string

Solution:

Create a route specific for terms; e.g.

`/lookup/HP/STRING`

This is probably better than overloading the `/phenotype/ID` route

Adding the ontology ID space helps uniquify and determine intent

Behavior:

Note that HP classes change their labels over time. However, a label is typically always retained as a synonym, unless it is egregiously wrong. However, there is no guarantee that a retired label is unique.

The procedure should be:
- look up by label first
- if not found, look up by exact synonym
- if not found look up by all synonyms
  - if 1 match, show
  - if >1 match, show list
- if not found, show message and show general search results

**Comment by nlwashington** [comment]
do they need to know that it has to be in "HP"?  because they can certainly hit `/search/search string`, which is maybe what the behavior should be anyway?

**Comment by cmungall** [comment]
For this particular use case, they know it's from HP, and the desired response is a page about the term, rather than a search

**Comment by jmcmurry** [comment]
in the spirit of CURIES, if relaxed, we could also do /lookup/HP:STRING

**Comment by jmcmurry** [comment]
@cmungall was there a particular user you had in mind for this? I assume we'd expect to receive labels pre-encoded, right? Even if the words are identical (eg. not synonyms etc), what about variants for spaces, capitalization, hyphenation etc. To do this properly for all edge cases would be a potential time sink. Naively, I would think that the search would do just as well here, provided that we do a much better job of ranking search. Thoughts?

**Comment by cmungall** [comment]
The use case here was some sources of annotations, e.g. the CSH MCS case studies seem to only store labels. It's probably better this plugs into search
