### ISSUE TITLE
Internal Server Error after a fresh installation

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1047]
Did a fresh installation of monarch-app this morning in order to fix some phenogrid-related issues, and saw this error in browser when accessing to the server:

```
{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}
```

But the beta.monarchinitiative.org is still running fine.

**Comment by kshefchek** [comment]
@yuanzhou can you tell me about your setup, what was the output from running ./install.sh?

**Comment by yuanzhou** [comment]
@kshefchek I just did a git clone of monarch-app first, then ran './install.sh' and './start-server.sh'.

**Comment by yuanzhou** [comment]
@kshefchek  I just did the fresh installation again to verify, and got the same error.

Here are my steps:

![capture1](https://cloud.githubusercontent.com/assets/195873/10855927/b4ee2dea-7f1a-11e5-834a-8a37662da8c3.PNG)

and I could see the server running message in console:

![capture](https://cloud.githubusercontent.com/assets/195873/10855940/c432920a-7f1a-11e5-8b9a-54477fe33a80.PNG)

But the error shows up again in browser:

![capture2](https://cloud.githubusercontent.com/assets/195873/10855946/cd082c50-7f1a-11e5-8c20-c1bb799b2774.PNG)

Same error with http://0.0.0.0:8080/

![capture3](https://cloud.githubusercontent.com/assets/195873/10855991/11d851de-7f1b-11e5-8c33-64466fef2af4.PNG)

**Comment by yuanzhou** [comment]
@DoctorBud did you notice the same issue with this HapiJS server?

**Comment by yuanzhou** [comment]
Interesting, I tried it again this morning and it worked all of sudden. Has anyone fixed this?
