### ISSUE TITLE
Simplify Monarch record URLs so that they do not rely on type (gene, disease, etc)

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1048]
It would be great if we could make a decision on where we would like to go with simplified URLs for our records. 

Users would like not to have to know what the type is for the identifier they're looking for. The resolver is great, but it would be better if folks didn't _need_ to know about its existence.

Options for consideration below; thoughts? @cmungall @nlwashington @kltm 
I prefer  monarchinitiative.org/record/HP:12345
a) intuitive 
b) simplifies routing logic
c) leaves the door open if we need to repurpose the /record/ path for redirection in the future
d) while /record/ isn't a universal 'convention' per se, it is common

This does not preclude using /genes/ path for operating on and visualizing groups of genes, for instance.

I like that our current design (eg. '/resolve/' is a verb and its current purpose is clear), but one limitation is that if we were to ever move to native resolution in the future as we are now discussing, the 'resolve' word would be a bit weird if you're not actually redirected. 

I am well aware of the limitations of our entity-level identification at present, and agree that fixing the issues is a ways away but it would be good to nevertheless make some good id design decisions now, so that when we have better identifier provenance in the future (tracking which ids disappear, change etc.), we are not _also_ stuck with mapping the old identifiers to the new ones. Is it possible to implement something whereby the resolve logic kicks in only if the desired URL is a 404? In any case for now it is simple to replace /gene/ with /record/.

In any case, I think we want to consider avoiding putting records directly underneath the homepage eg like monarchinitiative.org/HP:12345 as this would seem to unnecessarily complicate the routing logic. Right now we have only two kinds of pages, records and static HTML documentation like /about. But if we move in the future to lots of different kinds of things, eg maybe aggregate records or particular other kinds of tools etc, then we would be stuck jamming all that logic into one place in perpetuity.

**Comment by nlwashington** [comment]
I personally really like just using an identifier directly after monarchinitiative.org, without "resolve" or "lookup" or "gene" or "disease" or any other verb.  at least as an entry point.  i don't really care if it then redirects to a categorical page.

**Comment by kshefchek** [comment]
_meant for this to be a pull request_ - I've duplicated the functionality of /resolve/{id} to /{id} and moved /sources to /about/sources.  Behave test updated for the sources page and added new tests for /{id} resolving.

**Comment by jmcmurry** [comment]
Great; if we are not concerned with the technical scalability about having everything under the homepage directly, this is absolutely fine by me. Though I would say it would be fantastic if we could do away with the redirection to /gene/ pages unless we really need to.

**Comment by yuanzhou** [comment]
In terms of RESTful URI design, every single URI represents a resource. Based on this point of view, static pages and record pages are both resource pages. I like the way that some of the current URIs are designed. For example, `http://monarchinitiative.org/disease` is the entry point of the disease page, `http://monarchinitiative.org/disease/OMIM:305400` indicates a specific disease page. These URIs work as shortcuts if I want to go to the disease page directly in my browser. If `disease` doesn't appear in the URL, I lost my entry point to the default disease overview page.

From the SEO perspective, the appearance of "disease"  in URI is also more meaningful.

**Comment by jmcmurry** [comment]
You bring up good points, though ones we could still address in other ways aside from the URL. 
1) Traversability could be achieved in terms of breadcrumbs
2) SEO... I agree that dropping 'disease' probably causes a lower rank, but the real issue is probably how close a match is with the google search term. I'm not sure 'disease' would be a specific enough search term to put monarch in the first page of hits. We could theoretically use the curie prefix with a label suffix but there's a good reason we don't. We still need to get more unique content in each page. SEO should be another ticket, though we are probably a ways off from tackling that.

**Comment by jmcmurry** [comment]
@kshefchek has since implemented resolution at the root level (eg monarchinitiative.org/NCBIGene:6622) so this can be closed.
