### ISSUE TITLE
Autocomplete has seemingly duplicated entries

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#105]
@cmungall 

Autocomplete has duplicate entries, for example search on 
Choroidal degeneration
these are because of synonyms and equivalency axioms, however, since the landing page takes you to the choices, perhaps we can limit autocomplete to just one entry. Alternatively or in addition, we can autocomplete and append the category info. e.g.:
Choroidal degeneration (disease)
Choroidal degeneration (phenotype)
Either way, we should not have an entry for every synonym.
related to ticket #82 
![image](https://f.cloud.github.com/assets/796636/2100064/f0c6e05a-8f43-11e3-87f6-aff1354ca3df.png)

**Comment by mellybelly** [comment]
see ticket https://support.crbs.ucsd.edu/browse/LAMHDI-294

**Comment by cmungall** [comment]
We agreed as a first step to include the category in the autocomplete result shown to the user.

E.g. for this call
- http://beta.neuinfo.org/services/v1/vocabulary.json?prefix=adrenal&vocabulary=monarch

The DOID_9553 one should how up as

 "adrenal gland disease (Disease)"

If there is a null, just show "adrenal gland" 
or "adrenal gland" (UBERON_0002369)

(the nulls will gradually disappear)

**Comment by cmungall** [comment]
We can collapse in the monarch api.js level. As a first pass, collapse if the IDs are the same:

E.g. the following 2 results should be collapsed into 1:

```
{

    "uuid": "82daa5b2-2392-4633-b534-94948427a426",
    "term": "Adrenal gland dysplasia",
    "id": "HP_0011732",
    "category": null,
    "provider": "Monarch",
    "inferred": true,
    "acronym": false,
    "abbreviation": false,
    "synonyms": null,
    "definition": null

},
{

    "uuid": "44ede9f2-bf06-4782-830a-9d044d230afc",
    "term": "adrenal gland dysplasia",
    "id": "HP_0011732",
    "category": null,
    "provider": "Monarch",
    "inferred": true,
    "acronym": false,
    "abbreviation": false,
    "synonyms": null,
    "definition": nul
```

@harryhoch  will try this part

**Comment by harryhoch** [comment]
id filtering in https://github.com/monarch-initiative/monarch-app/commit/5d0fa27990a90f926c86f20b060b78d8c1e7ab8c.

**Comment by harryhoch** [comment]
@kltm, please add categories to responses, based on prefixes of IDs.

**Comment by nlwashington** [comment]
actually, add the categories themselves first (using the "category" attribute).

using prefixes of ids is another possible solution, as a second pass.

**Comment by kltm** [comment]
Assuming this all references the "main" search box in the navbar. I'll soon push with the following added features:
- category added as minor text, with namespace as fallback
- ID displayed on mouseover to help disambiguated repeated labels
- after-the-fact removal of duplicate IDs
- wait spinner so we know that something is actually happening
- styles for the above

**Comment by kltm** [comment]
@mellybelly what is the issue for the reopen? Please given a URL or procedure so it can be duplicated.

**Comment by mellybelly** [comment]
reopening as I am still seeing a related issue...
For example, autocomplete on 'macropenis'. You see two phenotype entries as below:
![image](https://f.cloud.github.com/assets/796636/2252822/0e7c43b8-9db0-11e3-9bb9-c2cfc3af0e29.png)
these are the equivalent classes MP_0003599 'large penis' and HP_0000040 'Enlarged penis'.
However, only one of these has a synonym "macropenis", the MP term. 
We should only be auto-completing on the term with the synonym.

**Comment by cmungall** [comment]
This is the expected behavior of autocomplete. In reality both terms have the synonym.

**Comment by mellybelly** [comment]
hmmm guess I was expecting to see only one? i guess part of the problem too, is that you don't really know why you are auto- completing on the term (especially with synonyms missing right now). I think our users are going to have a hard time understanding behavior of equivalent classes in general, not sure best behavior here?

**Comment by cmungall** [comment]
We can show IDs as well as category

**Comment by harryhoch** [comment]
Or at the very least source… “human phenotype” vs. “mammalian phenotype”, etc.?

On Feb 24, 2014, at 8:50 PM, Chris Mungall notifications@github.com wrote:

> We can show IDs as well as category
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by cmungall** [comment]
In some ways it's less confusing to show the IDs. Problem is the 
"mammalian" phenotype ontology is direct used for _mouse_ only. However, 
both ontologies are largely applicable to either mouse or human and 
indeed classes from one return genes from the "other" species.

Really there should only be one ontology here. There's only so much we 
can do at the UI level to compensate for work that needs to happen 
upstream. Can revisit for next release.

**Comment by cmungall** [comment]
We decided to remove an arbitrary item if it shares a label.

Possibly dangerous, esp as diseases share names with phenotypes, but we'll see how we go...

**Comment by mellybelly** [comment]
can we limit to within category?

**Comment by twhetzel** [comment]
@cmungall In reference to "We decided to remove an arbitrary item if it shares a label" - Are you removing items on-the-fly in the autocomplete or was the entry removed from the ontology?

**Comment by cmungall** [comment]
on the fly. See the commit above.
