### ISSUE TITLE
info@monarch email procedure

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1053]
@harryhoch just received a notification that he is unsubscribed from notifications to info@monarchinitiative.org. Does anyone know what may have triggered this?

What is the current process whereby these emails are triaged? Perhaps each email could be issued as a ticket within the operations repo (which is private)?

@cmungall @kshefchek @DoctorBud ? As we are now trying to do more to solicit this feedback, let's be sure we have a process to respond / address.

Thanks

**Comment by mellybelly** [comment]
i would very much like to have a tracking system, what we have now is pretty broken and reliant on me.

**Comment by jmcmurry** [comment]
lot of balls in the air but labeling this blocked so that we are sure to follow up asap

**Comment by jmcmurry** [comment]
This is now set up at OHSU
