### ISSUE TITLE
autocomplete poops out on long term labels

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#106]
For example, try autocompleting on:
Abnormality of calcium-phosphate metabolism
You can't find it.

http://tartini.crbs.ucsd.edu/phenotype/HP_0002924

Note that this class does not have any equivalence axioms and this is the primary label of the term. 

Not sure who to assign the autocomplete problems to @cmungall @harryhoch

**Comment by harryhoch** [comment]
I think this is an issue with the autocomplete service. Note that 

 curl "http://beta.neuinfo.org/services/v1/vocabulary.json?vocabulary=monarch&prefix=Abnormality of calc"

returns 20 items, starting with "Abnormality involving the diaphyses of the limbs", and ending with "Abnormality of alkaline phosphatase activity" 

It looks to me as if some of the text (perhaps after the space?) is not making it into the autocomplete calculation.

**Comment by jgrethe** [comment]
Making sure Davis and Chris are on this thread…

On Feb 6, 2014, at 10:34 AM, Harry Hochheiser notifications@github.com wrote:

> I think this is an issue with the autocomplete service. Note that
> 
> curl "http://beta.neuinfo.org/services/v1/vocabulary.json?vocabulary=monarch&prefix=Abnormality of calc"
> 
> returns 20 items, starting with "Abnormality involving the diaphyses of the limbs", and ending with "Abnormality of alkaline phosphatase activity"
> 
> It looks to me as if some of the text (perhaps after the space?) is not making it into the autocomplete calculation.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by jgrethe** [comment]
This:
http://beta.neuinfo.org/services/v1/vocabulary.json?vocabulary=monarch&prefix=Abnormality%20of%20calcseems
to work as you expect if it is encoded.

**Comment by mellybelly** [comment]
sorry proper URL for testing the first example, 'Abnormality of calcium-phosphate metabolism'
is 
http://tartini.crbs.ucsd.edu/phenotype/HP_0100530

For http://beta.neuinfo.org/services/v1/vocabulary.json?vocabulary=monarch&prefix=Abnormality%20of%20calc

I am getting this from services, which seems correct?

[{"uuid":"6da465b8-8887-4e35-b8d4-5713d08711b6","term":"Abnormality of calcium homeostasis","id":"HP_0004363","category":null,"provider":"Monarch","inferred":true,"acronym":false,"abbreviation":false,"synonyms":null,"definition":null},{"uuid":"16d734fb-e136-4495-8bf2-76d68f822107","term":"Abnormality of calcium-phosphate metabolism","id":"HP_0100530","category":null,"provider":"Monarch","inferred":false,"acronym":false,"abbreviation":false,"synonyms":null,"definition":null}]

The UI is still not autocompleting though. Perhaps the entry isn't reading the full typed string?
(actually all of the sudden there is no autocomplete working at all, maybe someone is fixing it ;-))

**Comment by cmungall** [comment]
I tried Harry's curl and got 2 results, not 20. So it seems services are fine. Might be in our UI?

I'm going to get a quick jquery lesson from @kltm to see if I can fix this

**Comment by cmungall** [comment]
It was a MDC (My Dumb Code) error. All is good now.
