### ISSUE TITLE
VT is not resolving

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#1065]
terms in VT aren't resolving.

i can go here directly:
http://beta.monarchinitiative.org/phenotype/VT:0000001

but the resolver indicates it isn't found:
http://beta.monarchinitiative.org/resolve/VT:0000001

**Comment by kshefchek** [comment]
We're still running off of production data scigraph, is beta scigraph stable?  If so I'll make the switch which should fix this.

**Comment by kshefchek** [comment]
Looks like we're currently loading beta data scigraph, and stage is down.  Blocked until I can test on one of these servers.

**Comment by kshefchek** [comment]
@nlwashington, this issue here is that the class is not typed as a phenotype.  Does it make sense to categorize VT:0000001 and all subclasses as phenotypes?  If so I'll make a ticket in configs.

**Comment by kshefchek** [comment]
This is fixed.
