### ISSUE TITLE
Monarch icon and Monarch label in left upper corner are both clickable

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#107]
@harryhoch may have some advice here too.

Perhaps use full Monarch Initiative logo (with the text) and do away with the monarch word? How do you make the logo look clickable (to go home)? 
In any case, it seems both are unnecessary and the monarch logo could be slightly more prominent.

**Comment by harryhoch** [comment]
the easy thing to do here would be to make the following changes:
1. the top navbar should only be found to the right of the vertical dividing line.
2. left sidebar gets extended to the top of the page.
3. The name "Monarch" is added on our near the logo.

Long-term we might want to consider reworking the top navbar and deprecating the sidebar..

**Comment by mellybelly** [comment]
replaced by #233
