### ISSUE TITLE
Having trouble loading data with monarch API

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1081]
This is for ontology expansion:
http://monarchinitiative.org/neighborhood/HP:0004388/10/OUTGOING/subClassOf.json

This is for getting the phenotype label:
http://monarchinitiative.org/phenotype/HP:0430010.json

Got 502 status code.

**Comment by nlwashington** [comment]
hmmm.  when i try those links, they also just spin and spin for me.  
but when i try running prod on my localhost it works just fine... and immediately on beta.  

not sure what the issue is here.  maybe @jnguyenx or @kshefchek has an idea?

**Comment by jnguyenx** [comment]
It seems that [sirius](http://sirius.monarchinitiative.org:8080/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=1000&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&facet.method=enum&fq=subject_closure:%22MGI:2676312%22%20OR%20object_closure:%22MGI:2676312%22&facet.field=subject_category&facet.field=subject_taxon&facet.field=subject_closure_label&facet.field=relation_closure_label&facet.field=evidence_closure_label&facet.field=object_category&facet.field=object_taxon&facet.field=object_closure_label&q=*:*) is down, I'll email the support...

**Comment by jnguyenx** [comment]
Now the Solr is back, but the 2 monarch urls are still not loading. I get a 502 Proxy error.

**Comment by yuanzhou** [comment]
I tested the two URLs on beta server and got 503 error. I think the first URL has something to do with SciGraph. The second one is just getting detailed info of a specific phenotype ID.

**Comment by yuanzhou** [comment]
Turned out that the beta server is down: http://beta.monarchinitiative.org/
