### ISSUE TITLE
biogrid is (incorrectly) evidence for everything

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#1084]
on here:
 http://stage.monarchinitiative.org/gene/NCBIGene:672

on the genotype/model/pathway/homolog/variant/etc tabs, biogrid shows up, along with all kinds of evidence types.  biogrid doesn't belong in any of those cases.  

need to figure out why it's showing up.  @jnguyenx this may be a golr-generation issue, or @kshefchek may need to comment on where it's coming from in golr.

**Comment by kshefchek** [comment]
These are generated from the "is_defined_by" field.

**Comment by jmcmurry** [comment]
This is no longer an issue, but for this particular example, biogrid doesn't show up on any of the source columns (for any of the tabs). Going to close this, but @kshefchek please reopen if the lack of any appearance of biogrid is a bug.
