### ISSUE TITLE
Data overview doesn't match info in tabs

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#109]
Besides #99 
there is also a problem with the gene count. 
See Angelman syndrome:
http://tartini.crbs.ucsd.edu/disease/OMIM_105830
It lists 1 gene in the Data Summary
but there are three on the genes tab (which are correct).
@nlwashington can also take a look.

**Comment by cmungall** [comment]
Yikes, there is "one" gene, it is "300005, 300203, 601623".

Did we ever get list retrieval from services working?

Until then the api should assume the fed query returns either a list or string, and will split if the latter. Also need to do ID mapping here?

**Comment by nlwashington** [comment]
well, the column is called "gene_ids".  so, yes, it should have been split.  and, no, it doesn't look like they give us a list, even though it clearly processes it (the source table actually has it delimited with pipes, but it is delivered to us with commas).

i should also fix the underlying data so that the ids are prefixed, and ensure that they are ncbi gene ids.

**Comment by nlwashington** [comment]
it also might be better to fetch these simply from the VariantPhenotype table (nif-0000-03216-9) instead of the nif-0000-03216-7 (-7 should have everything that -9 has).

**Comment by nlwashington** [comment]
I think we should pull this data from here:
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_151671-2
It is a more-complete list of disease-gene links from ClinVar.  See #115

**Comment by nlwashington** [comment]
We can't troubleshoot this completely until the data is fixed, so we can see a reasonable set of results.
https://support.crbs.ucsd.edu/browse/NIF-10234

**Comment by harryhoch** [comment]
Does this look ok?

**Comment by cmungall** [comment]
Looks good to me
