### ISSUE TITLE
Remove dependence on federation for spotlight

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1095]
We discussed either
1. removing spotlights
2. hardcoding a single spotlight
3. Doing a one time cache of all the legacy json to support rotating spotlights
4. rewriting spotlight code to use golr/sg

If nothing is done we will have to default to 1

**Comment by kshefchek** [comment]
Doing a one time cache of all the legacy json to support rotating spotlights - is currently implemented, if you see issues locally it is likely from clearing your local cache, see for example committed cache files: https://github.com/monarch-initiative/monarch-app/tree/master/cache/disease

**Comment by cmungall** [comment]
presumably we need to check these in now, as we will be cut off from the source soon

**Comment by kshefchek** [comment]
Everything should be fixed, the cache files are checked in and the app no longer attempts to fetch information from NIF in the case where the files are no available, see 542382d and 7ef60a22.

**Comment by jmcmurry** [comment]
@kshefchek closing this; pls reopen if still an issue
