### ISSUE TITLE
Add section showing list of inferred models, sorted by rank

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#11]
Current page has asserted models:
http://secret-harbor-1370.herokuapp.com/disease/OMIM_143100#model

And below that a "similar diseases" section that needs improved..

There should be an additional section showing the inferred models.

@nlwashington - what is the nlx ID for this view?

**Comment by nlwashington** [comment]
I've added a section for "similar models", defaulting to the top 25 and BMAasymIC for the scoring metric.  Right now this only shows mouse (as it is the only one loaded).  I added this under the "models" section.  Can easily be moved in the mustache template.
