### ISSUE TITLE
Encephalitis a subtype of testicular neoplasm????

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#110]
http://tartini.crbs.ucsd.edu/phenotype/HP_0010788

wrong:

![screen shot 2014-02-06 at 4 32 46 pm](https://f.cloud.github.com/assets/50745/2105547/66ac520a-8f8f-11e3-979c-8529edea5113.png)

and wrong:

![screen shot 2014-02-06 at 4 33 12 pm](https://f.cloud.github.com/assets/50745/2105550/7bae0f5e-8f8f-11e3-9fd7-2005714a870c.png)

**Comment by cmungall** [comment]
Confirmation that the issue does not reside in the ontology:

![screen shot 2014-02-06 at 4 23 15 pm](https://f.cloud.github.com/assets/50745/2105559/93222e90-8f8f-11e3-957d-2883f12fbd33.png)

No Encephalitis or CNS inflammation to be found

**Comment by cmungall** [comment]
Ontoquest is also returning sane descendants:

http://nif-services-stage.neuinfo.org//ontoquest-lamhdi/rel/parents/HP_0010788?level=5

**Comment by cmungall** [comment]
This issue is upstream of the monarch API - the federation query below is wrong:

http://beta.neuinfo.org/services/v1/federation/data/nlx_151835-1.json?includePrimaryData=true&count=1000&q=HP:0010788&includeSubclasses=true&

HP:0010788 = testicular neoplasm

```
"result": [

    {
        "Disorder": "<a class=\"external\" target=\"_blank\" href=\"http://www.omim.org/entry/109650\">Behcet Syndrome</a>",
        "Qualifier": "",
        "Phenotype": "<a class=\"external\" target=\"_blank\" href=\"http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0002383\">Encephalitis</a>",
        "Aspect": "organ abnormality",
        "Publication": "ORPHANET:117",
        "Evidence Code": "TAS Traceable Author Statement",
        "Onset": "",
        "Frequency": "occasional",
        "disorder_id": "OMIM:109650",
        "e_uid": "653c174e6762af6517a759c60e4ec0051ef5f3b151b9771d6b7949283cd61554",
        "disorder_database_prefix": "OMIM",
        "disorder_id_num": "109650",
        "disorder_name": "Behcet Syndrome",
        "disorder_qualifier": "",
        "phenotype_id": "HP:0002383",
        "phenotype_label": "Encephalitis",
        "publication_id": "ORPHANET:117",
        "evidence_code": "TAS",
        "onset": "",
        "frequency": "occasional",
        "aspect": "O",
        "synonyms": "BEHÇET DISEASE|http://www.orpha.net/consor/cgi-bin/OC_Exp.php?lng=en&Expert=117",
        "aspect_text": "organ abnormality"
    },
```

**Comment by cmungall** [comment]
Issue with closure, filed under closure ticket:

https://support.crbs.ucsd.edu/browse/LAMHDI-140

This is a showstopper methinks

**Comment by nlwashington** [comment]
Can't test until data issues are resolved with identifier queries:
https://support.crbs.ucsd.edu/browse/NIF-10234

**Comment by harryhoch** [comment]
This looks fixed - is it?
