### ISSUE TITLE
proxy errors on beta

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1100]
Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /search/smad2.

Reason: Error reading from remote server

Apache/2.2.15 (CentOS) Server at beta.monarchinitiative.org Port 80

**Comment by kshefchek** [comment]
I'm not able to replicate, @jmcmurry could you try again and see if it's resolved?

**Comment by jmcmurry** [comment]
This was when I was at Harvard; now that I'm at home, I can't replicate
either.
By way of this email, I can ask Richard Pearse to try again when he's on
campus.
Same search on production worked fine; that is what is a bit odd. Are the
ports different?

**Comment by jmcmurry** [comment]
I’m still getting a “Proxy Error” when connecting from the Harvard ethernet port (Proxy errors are showing on both “prod” and “demo”
-Richard

**Comment by kshefchek** [comment]
I'm getting the same errors as well now, we will likely need to involve sys admin.

**Comment by kshefchek** [comment]
See https://support.crbs.ucsd.edu/browse/CRBS-10729

**Comment by kshefchek** [comment]
crbs marked it as fixed, please reopen if you are still having issues.

**Comment by jmcmurry** [comment]
Per Richard: "It seems to be working much better at the moment. I was still getting the block a couple hours ago, but whatever’s been done since then has cleared up performance for now."
