### ISSUE TITLE
Some OMIA pages fail to resolve

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1115]
Species-specific ones work, e.g
http://monarchinitiative.org/disease/OMIA:001158-9796

But try navigating to parent in the hierarchy

gets routed to 404 via
http://monarchinitiative.org/resolve/OMIA:001158

**Comment by kshefchek** [comment]
Node not found: http://rosie.crbs.ucsd.edu:9000/scigraph/graph/OMIA:001158?project=*

But it's in the ontology graph:
http://kato.crbs.ucsd.edu:9000/scigraph/graph/OMIA:001158?project=*

Right now the resolver only looks at that the datagraph, is there a reason why this isn't loaded into the datagraph?

**Comment by nicolevasilevsky** [comment]
On a related note, I can't search for some of the species that were added from OMIA, for example, if I search for American Flamingo, I get an error: http://monarchinitiative.org/search/american%20flamingo

**Comment by kshefchek** [comment]
Our production scigraph server had not properly updated, this should resolve now.
