### ISSUE TITLE
Phenogrid not loading for OMIA pages

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1117]
Phenogrid is not loading on this page:

http://monarchinitiative.org/disease/OMIA:001461-9217

**Comment by nicolevasilevsky** [comment]
same issue with this page: http://monarchinitiative.org/disease/OMIA:000185-452646

**Comment by kshefchek** [comment]
We had to take down one of our services briefly, this should be working again.
