### ISSUE TITLE
Add Gene pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#112]
We need "gene" kinds of pages, filled with content.  We will assume (for now) that these pages are for a species-specific gene (not any kind of "uber gene").

At minimum, I think it ought to have the following kinds of tabs with information:
*_basic gene info (ids, symbols, names, genomic location, linkouts to NCBI/ENSEMBL/species-specific dbs)
*__we should be able to get this from the ncbi_gene view:  nif-0000-02801-1
*__and/or we might be able to get it from mygene.info (with other rest call already implemented)
*_phenotypes - annotations made to gene via genotype, variation, or directly
**_will have to case/switch on the taxon to get appropriate target table(s)
*_pathways - known involvement in a pathway (kegg, reactome, etc.)
**_fxns already written
*_orthology - organized by organism, we can get these from KEGG, PANTHER, homologene, etc.  (should we include a grid comparison of the phenotypes of this gene to it's orthologs?)
*_diseases - related a few ways:  (1) variants are known to be asserted models; (2) orthologs of gene are implicated; (3) phenotypes are similar to topX diseases
*_interactions --these could be acquired from http://code.google.com/p/psicquic/?
http://code.google.com/p/psicquic/wiki/PsicquicSpec_1_3_Rest, and/or our system (we have biogrid and some string already, will ingest more)
*_similar genes - similarity query by phenotype (in same or other organism)
*_models - organisms (genotypes, strains, cell lines) that this gene is known to be variant in

**Comment by kshefchek** [comment]
I'm having some trouble generating informative results with nif-0000-02801-1, so for now I'm going to obtain any additional information (species, genomic location, linkouts, etc.) from mygene. info. It seems the nif resource doesn't contain some common genes, for example:
http://beta.neuinfo.org/services/v1/federation/data/nif-0000-02801-1?exportType=data&q=672
(expecting gene ID 672, BRCA1)
http://beta.neuinfo.org/services/v1/federation/data/nif-0000-02801-1?exportType=data&q=7291
(expecting TWIST1)

Figured I'd post here in case I'm building the NIF URLs incorrectly.

**Comment by nlwashington** [comment]
Ah, this is interesting.
NCBI, of course, doesn't prefix their gene ids with anything, and therefore when i made this view i didn't either.
But, for ID queries to work correctly in the NIF system, they must be prefixed.  (otherwise partial matches would happen)

However, something seems strange...there appears to only be 62593 genes in the view (with none that match Homo sapiens).  That is suspiciously low.  Let me check things out.

**Comment by kshefchek** [comment]
Ah ok, I played around with adding NCBI:gene_ to the ids as well with no luck, it must be an issue with the view.  I'll keep the code in place that queries nif and just comment it out for now and leave mygene as a backup.

**Comment by nlwashington** [comment]
I've submitted a bug.  There is a serious discrepancy to the number of records that are reported in the curation interface (>14M) and the number that show up as available via services (65K).

https://support.crbs.ucsd.edu/browse/NIF-10354

**Comment by nlwashington** [comment]
I've reindexed the gene resource, and you ought to be able to do a search like this:
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-02801-1&b=0&r=20&fl=geneid:672

soon, i will be refactoring this view so that there will be a column, just like in the other views, that would be gene_label and gene_id.  i will update when this is ready.
also,you can filter by taxon_id or taxon_label.

**Comment by kshefchek** [comment]
Great!  My queries inside the webapp are working now.

**Comment by mellybelly** [comment]
Kent, I think this ticket can be closed?

**Comment by kshefchek** [comment]
Sure, we can break out any bugs and updates into new issues. Closing.
