### ISSUE TITLE
Need to list the species that a genotype is of

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#113]
http://tartini.crbs.ucsd.edu/genotype/MGI:5450523 
shows a genotype.  

but nowhere does it explain that it is a mouse.

This ought to be found in the taxon.id and taxon.label elements.

This should be displayed fairly prominently, perhaps even in the jumbotron for a genotype, or at least in the overview.

**Comment by sarahjkim** [comment]
There is actually nothing in the taxon objects at the moment. I will make the jumbotron display this when there is information in the JSON.

![screen shot 2014-02-12 at 1 20 46 pm](https://f.cloud.github.com/assets/4628853/2153757/b5190582-942b-11e3-8ca3-2e2d680e0acd.png)
