### ISSUE TITLE
Add content to overview tab

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1133]
Related ticket for variants and genotypes: https://github.com/monarch-initiative/monarch-app/issues/755

We want to add more content to our overview tabs and have this be the default/landing tab on all pages.

Some ideas:
- download buttons to id specific datasets (#1022)
- graphs/visualizations such as an ontology browser, charts, etc.
- Phenogrid icon/short explanation that links to compare tab

**Comment by jmcmurry** [comment]
Closing this but merging these comments with Chris' recent ticket. https://github.com/monarch-initiative/monarch-app/issues/1213
