### ISSUE TITLE
Additional species data for testing?

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#1138]
Have we loaded additional species data in the database? I've been using the following species for testing new Phenogrid features:
- Homo sapiens
- Mus musculus
- Danio rerio

I tried Drosophila melanogaster (taxon: 7227) but there's no matches from simsearch. If I have additional species for testing, I could cover some corner cases that can't be captured by the existing three species.

**Comment by jmcmurry** [comment]
This is now vestigial
