### ISSUE TITLE
Add linkouts to source for genotypes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#114]
All genotypes (or at least portions of them) probably originate at a MOD.  These should be hyperlinked in some way.

Most of the sources that we pull from nif have either an effective_genotype_url or intrinsic_genotype_url or something to that effect which could be used for hyperlinking.

**Comment by mellybelly** [comment]
the sources are listed in the new table view on the similar models tab, but no linkouts yet. 
on the actual model page. moving to may milestone

**Comment by mellybelly** [comment]
Sarah is this something you can fix?

**Comment by sarahjkim** [comment]
Fixed by a32d83f67d983b2dd9d2ba0bb0ef55c4f125a67f.
