### ISSUE TITLE
500 error for HP:0006862

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#1140]
i went here:
http://monarchinitiative.org/phenotype/HP:0006862

and after much time, i got a 500 error.

note that this term is an alt id.

**Comment by nlwashington** [comment]
Now it doesn't give a 500 error, but it just shows up with a blank page.  since it has an alt id, it should redirect to that page, or give me options. 
but i notice that if i query by that id directly by scigraph, i get nothing.  is this node/id even loaded?

**Comment by nlwashington** [comment]
when i looked in the hp.owl file, i find the id as an alternative to HP:0002131.  however, looking at the contents of [HP:0002131 in scigraph](http://monarch3-1.cslu.ohsu.edu/scigraph/graph/HP:0002131?project=%2A), that identifier isn't there as an altid.  @jnguyenx, is there trouble with the loading of the ontology?  perhaps it has trouble with the list of things (off by one errors or such)?

**Comment by jnguyenx** [comment]
http://www.ontobee.org/ontology/HP?iri=http://purl.obolibrary.org/obo/HP_0006862

Does not exist
