### ISSUE TITLE
Phenotype Analysis not working

### ISSUE THREAD

**Issue by wondermixtape** [monarch-initiative/monarch-legacy#1141]
Any submission gives error “ {"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred”}”

Tried with Safari, Chrome and Firefox

**Comment by jmcmurry** [comment]
+1 This is a problem I just encountered too.
http://monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0000252+HP%3A0003700+HP%3A0000648+HP%3A0002126+HP%3A0005750+HP%3A0001250+HP%3A0004325+HP%3A0002045&mode=search&target_species=all&limit=100

@kshefchek please investigate thanks.

**Comment by jmcmurry** [comment]
On stage it is working: http://stage.monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0000252+HP%3A0003700+HP%3A0000648+HP%3A0002126+HP%3A0005750+HP%3A0001250+HP%3A0004325+HP%3A0002045&mode=search&target_species=all&limit=100

**Comment by jmcmurry** [comment]
Fixed by switching owlsim to production server
