### ISSUE TITLE
stage has bonkers rendering bugs

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1147]
Don't even know how to describe this: @DoctorBud thoughts? CC: @kshefchek 

<img width="925" alt="screen shot 2016-01-13 at 2 00 33 pm" src="https://cloud.githubusercontent.com/assets/3658863/12309187/25933644-b9fe-11e5-9c8a-f6038fb32026.png">

**Comment by jmcmurry** [comment]
Refreshing the page seems to remedy it presently, however @harryhoch had a similar issue about an 3 hours ago on a different page (also stage)

**Comment by kshefchek** [comment]
I think this has to do with rendering client scripts with requireJS, see https://github.com/monarch-initiative/monarch-app/issues/1152#issuecomment-172955799

**Comment by DoctorBud** [comment]
I'd like to CLOSE this issue. I think that since we are running in bundled mode now, and requireJS is no longer being used, that this should not be happening. Also, there is no stage.m.org right now, there is only beta.m.org and that seems to be working.
