### ISSUE TITLE
Pull disease-gene links from ClinVar

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#115]
A more-complete set of disease-gene links can be acquired from here:

http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_151671-2

**Comment by nlwashington** [comment]
i am implementing this, but due to the new nif identifier bug, am unable to test if this is working correctly with subsumption.

**Comment by mellybelly** [comment]
I know work is almost complete on ClinVar data, moving to May milestone

**Comment by nlwashington** [comment]
this is actually complete.
still todo, is to add disase-variants.  but genes are in.
