### ISSUE TITLE
owlsim down?

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#1151]
i think that owlsim services might be down. 

i was poking hard at it via the /compare functionality wrapper in monarch-app, and now it's not returning the comparisons correctly.  for example:

http://www.monarchinitiative.org/compare/HP:0000006+HP:0000174+HP:0000194+HP:0000218+HP:0000238+HP:0000244+HP:0000272+HP:0000303+HP:0000316+HP:0000322+HP:0000324+HP:0000327+HP:0000348+HP:0000431+HP:0000452+HP:0000453+HP:0000470+HP:0000486+HP:0000494+HP:0000508+HP:0000586+HP:0000678+HP:0001156+HP:0001249+HP:0002308+HP:0002676+HP:0002780+HP:0003041+HP:0003070+HP:0003196+HP:0003272+HP:0003307+HP:0003795+HP:0004209+HP:0004322+HP:0004440+HP:0005048+HP:0005280+HP:0005347+HP:0006101+HP:0006110+HP:0009602+HP:0009773+HP:0010055+HP:0010669+HP:0011304/MP:0000278+MP:0001402+MP:0001511+MP:0001732+MP:0002083+MP:0002652+MP:0002795+MP:0003896+MP:0004566+MP:0005333+MP:0005598+MP:0005608+MP:0009416

also, i can't get to owlsim.crbs.ucsd.edu//getAttributeInformationProfile?a=HP:0001620
but i can get to http://owlsim.monarchinitiative.org//getAttributeInformationProfile?a=HP:0001620

not sure which is which for production?  where do we restart this?
cc @jnguyenx @cmungall

**Comment by kshefchek** [comment]
We're running  http://owlsim.monarchinitiative.org/ on production.  It appears to be up, but this brings up the point that we should have some owlsim tests that run periodically to catch any downtime.
