### ISSUE TITLE
Data sources page is virtually blank

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1152]
Not sure what is going on here:
http://stage.monarchinitiative.org/page/sources
http://monarchinitiative.org/page/sources
<img width="1394" alt="screen shot 2016-01-18 at 10 57 55 am" src="https://cloud.githubusercontent.com/assets/3658863/12400014/71434bb0-bdd2-11e5-9e7f-37108b24d2e3.png">

Needs to be reverted to functioning state asap as this page is referenced in R24 proposal. Perhaps something that went awry in NodeJS refactor? Should be straightforward to remedy, but let me know if not as this page could use some love anyway.

**Comment by kshefchek** [comment]
My guess is that this has to do with the require.js configuration, which we've since removed in favor of bundling with web pack (see http://monarch1-1.cslu.ohsu.edu/about/sources).  If this is the case it should be fixed with the next release.

**Comment by DoctorBud** [comment]
This is still a bug on beta and production.
Doesn't have anything to do with requireJS. I'll look into it.

**Comment by DoctorBud** [comment]
The URL `.../page/sources` is not the correct URL for the Source page. The correct URL is `.../about/sources` which is also where the About/DataSources menu leads. Please forget the `/page/sources` URL and do not distribute it.

I fixed the issue in https://github.com/monarch-initiative/monarch-app/pull/1186, where I redirect from the BAD url to the GOOD one.

Closing this Issue
