### ISSUE TITLE
analyze/phenotype page doesn't show input phenotypes when submitted

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#116]
1. enter phenotype on /analyze/phenotype
2. press search
3. page is refreshed with the input field left empty and with no indication of the terms that the user provided.

**Comment by cmungall** [comment]
I will add something to re-report inputs (together with report of any unresolvables).

Ideally we would like the user to be able to continue adding and subtracting from the selection list and iteratively searching. Discussed a few alternatives with @kltm, would take a bit of plumbing, I decided to punt for now

**Comment by mellybelly** [comment]
duplicates #243
