### ISSUE TITLE
gene symbol display error

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1164]
On this page I see the human gene on the homolog tab showing as "paired box 3" rather than PAX3

http://monarchinitiative.org/gene/MGI:97487

**Comment by kshefchek** [comment]
This was tracked to a dipper/omim parser issue, so we are blocked until we can regain access to there or come with an alternative way to fix.  We may be able to patch on the monarch-app side.

**Comment by kshefchek** [comment]
This is fixed now.
