### ISSUE TITLE
502 error accessing scigraph-ontology-dev.monarchinitiative.org/

### ISSUE THREAD

**Issue by frdougal** [monarch-initiative/monarch-legacy#1168]
On Feb 5 at 3:40 pm, I am encountering 502 Bad Gateway errors on this URL:

http://scigraph-ontology-dev.monarchinitiative.org/scigraph/vocabulary/autocomplete/parkin.json

This URL is specified twice in the server_config_dev.json file:

   "scigraph_url" : "http://scigraph-ontology-dev.monarchinitiative.org/scigraph/",
    "scigraph_data_url" : "http://scigraph-data-dev.monarchinitiative.org/scigraph/",

**Comment by kshefchek** [comment]
I've created a status page for our services that should help out in the future:
http://beta.monarchinitiative.org/services/status

We have two scigraph services running, ontology only and ontologies+data.

**Comment by jmcmurry** [comment]
I'm not getting a 502 anymore.
As Kent just mentioned, the ontology and data URLs are intentionally different; this isn't a duplication. 
I'm going to close, but please reopen and clarify any remaining blockers.
