### ISSUE TITLE
analyze/phenotype output is unclear

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#117]
the table columns are not easy to interpret....

**Comment by cmungall** [comment]
I think almost everything in the portal needs link to help/manual pages..

**Comment by harryhoch** [comment]
agreed. I would suggest alternative names and/or tooltip text for the existing table, but I'm not quite sure that I understand the output.

**Comment by harryhoch** [comment]
udpated and replaced by https://github.com/monarch-initiative/monarch-app/issues/170
