### ISSUE TITLE
return taxon from scigraph autocomplete method

### ISSUE THREAD

**Issue by frdougal** [monarch-initiative/monarch-legacy#1171]
In api.js, there is a function called: bbop.monarch.Engine.prototype.getVocabularyByTerm.  This function calls a SciGraph method.

I would like to show the taxon in the Monarch App autocomplete list.  I don't see taxon being returned in the JSON call: http://scigraph-ontology.monarchinitiative.org/scigraph/vocabulary/autocomplete/huntin.json.  Can we add the taxon to the data returned by this call?

Thanks,
chuck

**Comment by kshefchek** [comment]
Right now this requires two calls in scigraph, we implement something similar here: 
https://github.com/monarch-initiative/monarch-app/blob/master/js/monarch-common.js#L301
and
https://github.com/monarch-initiative/monarch-app/blob/master/js/search_form.js#L126

**Comment by jmcmurry** [comment]
@cborromeo if you have the info you need now, could you close this please? thanks

**Comment by kshefchek** [comment]
Going to close as we've moved autocomplete over to solr and include taxa when possible
