### ISSUE TITLE
need to create place on website for HPO layperson synonyms

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1178]
would like to showcase our layperson synonyms on the website somehow, when it is done.

@jmcmurry 
@mellybelly

**Comment by jmcmurry** [comment]
Thanks for bringing this up. Just to clarify, there are two issues really. One is how to showcase the synonym effort more generally, the other is how to engage the lay audience in exploring the data. The former is easy--the latter very hard. We discussed having altogether different UIs for these three basic audiences (researchers, physicians, patients). Regarding the former, Nicole, could you write up a blog post for this?

**Comment by nicolevasilevsky** [comment]
Starting a draft of the blog post here: https://docs.google.com/document/d/1MIlKWOUvDO3074MOaLzjIXjnPL3gB7zKJRQ_KpGPbVU/edit

**Comment by nicolevasilevsky** [comment]
Blog post is up: http://monarch-initiative.blogspot.com/

**Comment by nicolevasilevsky** [comment]
I added the blog post, but it is not showing up on the monarch homepage: https://monarchinitiative.org/ 

![image](https://cloud.githubusercontent.com/assets/6722114/14160772/8c9827a6-f693-11e5-9af5-b1f399bfeff9.png)
