### ISSUE TITLE
Search result failure for uticaria

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1196]
A friend's kids have [cold uticaria](http://monarchinitiative.org/disease/OMIM%3A120100) so I was curious to know if I could find it in Monarch. There was no autocomplete suggestion for uticaria so when I just pressed enter to search I got this, which I think we can all agree is bad, but I'm having a hard time working out what could be behind it. 

http://monarchinitiative.org/search/uticaria

<img width="622" alt="screen shot 2016-02-29 at 9 22 57 pm" src="https://cloud.githubusercontent.com/assets/3658863/13418507/d40f489c-df2a-11e5-86c5-fd6038c789d4.png">

If I search for "cold" and I wait very very patiently, I do get "cold uticaria familial" showing up in autocomplete. I also get sensible autocomplete results.

Thoughts?

**Comment by kshefchek** [comment]
SciGraph autocomplete/search isn't great with misspellings.  We have a suggestions service that we could use here as a patch:
http://scigraph-ontology.monarchinitiative.org/scigraph/vocabulary/suggestions/uticaria?limit=5

Oddly enough the correct spelling doesn't return the right suggestion:
http://scigraph-ontology.monarchinitiative.org/scigraph/vocabulary/suggestions/urticaria?limit=10

**Comment by jmcmurry** [comment]
I guess we should always return some kind of result, regardless, so if we handle the misspelling, the issue of handling "no results" will go away.

**Comment by kshefchek** [comment]
I'll add suggestions in from SciGraph, but we should also add as a TODO for the new solr based autocomplete and search, cc @cborromeo and @harryhoch.
