### ISSUE TITLE
Add API call for groupings/categories

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#12]
We want to be able to consolidate and/or make visually apparent some kind of higher-level group that an annotation term belongs too. In the first iteration, we'll hardcode the grouping to be the 1st level down of HP/Uberpheno.  

There needs to be an API call that returns the group/parent or whatever of a term, which itself leverages OQ.

**Comment by mellybelly** [comment]
Let me know if you need feedback in specifying these. Potentially use similar categories/groupings as phenotips?

**Comment by cmungall** [comment]
I suggest we add this as an annotation property; either of these two:
- hp.obo adds this as a subset tag (maximizes the benefit to most groups)
- we add annotation assertions in a separate owl file that is imported by monarch.owl

**Comment by nlwashington** [comment]
@cmungall, don't want to just use subclass relationships?

**Comment by mellybelly** [comment]
moving this to post-1.0 release

**Comment by jmcmurry** [comment]
@kshefchek can this be closed now?

**Comment by kshefchek** [comment]
Sure the above is referencing ontoquest, we've done this with scigraph, I think it's safe to close.
