### ISSUE TITLE
Need to update community listserve info page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1203]
On this page:
http://monarchinitiative.org/page/about
we link at the bottom of the box to this link:
http://mail.monarchinitiative.org/mailman/listinfo/users
which does not resolve.

We need more prominent and functional links to our list serves. 
info@monarchinitiative.org
community@monarchinitiative.org 

@jmcmurry @kshefchek @DoctorBud can you help?
This is important for our GSoC students to access.

**Comment by jmcmurry** [comment]
There was a strange link in our GSOC organization profile that didn't resolve. I updated to just the info@monarchinitiative.org address. See also above linked issue.

**Comment by jmcmurry** [comment]
I think this can now be closed; reopen if I'm mistaken
