### ISSUE TITLE
update architecture doc on website

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1206]
We need to have a more up to date version - the version up there now still refers to DIsco.
@jmcmurry can you modify the slide you made for @kshefchek  to replace?

**Comment by jmcmurry** [comment]
@kshefchek made an even newer version of the slide. I'm not sure where it is but will ask him to find and post it. Thanks

**Comment by kshefchek** [comment]
[architecture_tldr_2016-01-20.pdf](https://github.com/monarch-initiative/monarch-app/files/407857/architecture_tldr_2016-01-20.pdf)

I created a minified version of the flow chart for our NCI demo, but we likely want something in between the two.

**Comment by kltm** [comment]
"GOlr", "OWL".

**Comment by cmungall** [comment]
Need a png of the diagram

**Comment by jmcmurry** [comment]
of architecture_tldr_2016-01-20.pdf? or Some other representation?

**Comment by cmungall** [comment]
Previously we had two pages

 - software, with a description of the arch (horrendously out of date)
 - REST API (out of date)

I'm going to collapse these into a single services page. This can also describe the overall arch briefly, but most people just want to be able to use it

**Comment by jmcmurry** [comment]
great that sounds fine. But are the contents of the above PDF what you're looking for or should we talk about doing something else?

**Comment by cmungall** [comment]
probably something else that better reflects what is there and how someone might use our services

**Comment by cmungall** [comment]
https://github.com/monarch-initiative/monarch-app/commit/1d0cccbe405d8a416dce33e39050138382d06730#diff-24365fe76abbacc784788096b64ac9fb
