### ISSUE TITLE
ontologies documentation still points at google code

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1207]
https://code.google.com/archive/p/phenotype-ontologies/

need to point at the github site(s)

**Comment by iamkoehler** [comment]
point to https://github.com/obophenotype ?

**Comment by cmungall** [comment]
EDIT:

Sorry, I didn't realize this was in the monarch tracker

Not sure pointing at an org is so useful, obophenotype is very broad, upheno is probably the best place

~~Too late to make changes now.~~

~~In any case, it already points to upheno~~

**Comment by TomConlin** [comment]
see also 
[https://github.com/monarch-initiative/dipper/issues/268](https://github.com/monarch-initiative/dipper/issues/268)

**Comment by jmcmurry** [comment]
If it is too late to make changes I suggest we close this ticket and instead make sure that all our code is free from Google code references as per monarch-initiative/dipper#268. Reopen this ticket if necessary.
