### ISSUE TITLE
Add sorting capability to tables

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#121]
I'd like to be able to sort the various tables by various columns.  For example, on the disease tab for this phenotype:
http://tartini.crbs.ucsd.edu/phenotype/HP_0000003

i want to sort on the 'disease' column or perhaps on the 'frequency' column.

ideally, any column header on any tab on any page could be used to sort.

**Comment by cmungall** [comment]
Given that these are currently static html tables, this should be done client side using some standard jquery lib. @kltm what do you recommend? @sarahjkim would you be able to add this?

**Comment by sarahjkim** [comment]
It looks like it might not be too hard to do with this plugin: http://tablesorter.com/docs/ or this one: http://joequery.github.io/Stupid-Table-Plugin/. I'll look into it more.

**Comment by harryhoch** [comment]
Sarah, apparently tablesorter was considered relatively old as of 2011.  this blog post: http://blog.jqueryui.com/2011/02/unleash-the-grid/ has some pointers to others that might be more up to date..

**Comment by kltm** [comment]
Anecdotally, we've been using tablesorter for some time--it's simple and works as expected. I can show you how it works if you're interested.

**Comment by harryhoch** [comment]
ah. go with the familiar. …

On Feb 12, 2014, at 5:39 PM, kltm notifications@github.com wrote:

> Anecdotally, we've been using tablesorter for some time--it's simple and works as expected. I can show you how it works if you're interested.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300
