### ISSUE TITLE
Gather requirements for an index for autocomplete

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1210]
The goal of this ticket is to gather technical requirements for a solr core to support an autocomplete widget, with outcome being some shared document that outlines these requirements.  Let's limit the discussion to autocomplete and split site search out into a separate issue/document.

My two cents:
We want a solr index of all of the node id, primary label, synonyms, taxon (common name) from our data scigraph.  This would include additional entities in comparison to our current autocomplete, including models, variants, genotypes, etc.

Additional features/considerations:
1. Uber gene label
   - Autocomplete on one gene for a collection of homologs, and send to an intermediate page.  We want to only expose genes in which we have some association data (other than homology).  Similarly on this uber gene page, only expose genes in which we have data.
2. Uniquify labels for entities, where the same label is used across species or data types (ie disease and phenotype)

**Comment by cmungall** [comment]
didn't see this when I made my comments here #1008

**Comment by jmcmurry** [comment]
In the absence of meaningful collapsing of species, if I had to distill autocomplete improvements into just two things, it would be (i) performance and (ii) "in all results"; are either of these tractable?

**Comment by kshefchek** [comment]
duplicate of closed issue https://github.com/monarch-initiative/monarch-app/issues/1008
