### ISSUE TITLE
Annotation profile scoring service doesn't work when connecting from Java 7

### ISSUE THREAD

**Issue by sdumitriu** [monarch-initiative/monarch-legacy#1216]
Since the scoring service at https://monarchinitiative.org/score now requires https, clients running on Java7 (or Java6) can't connect anymore since the https configuration doesn't use any of the ciphers supported by Java7. Consider enabling TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA as well.

More details: https://www.ssllabs.com/ssltest/analyze.html?d=monarchinitiative.org

**Comment by sdumitriu** [comment]
Even with Java8, Let's Encrypt certificates aren't trusted: https://community.letsencrypt.org/t/which-browsers-and-operating-systems-support-lets-encrypt/4394

**Comment by jnguyenx** [comment]
I've added the configuration for Java7, can you try again?

**Comment by sdumitriu** [comment]
Now it works, thanks.

Well, connecting to the host works, but now the whole monarchinitiative.org site appears to be down (502 Bad Gateway).

**Comment by jnguyenx** [comment]
Yeah we're upgrading the app, should be back shortly, thanks!
