### ISSUE TITLE
example searches near search box

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#122]
I think we need perma-examples near the search box.  I found this kind of list on the NextBio website, and I liked the way they did it.  We should have something similar.

![screen shot 2014-02-10 at 4 30 19 pm](https://f.cloud.github.com/assets/5124411/2132670/c848b126-92b3-11e3-9873-1241ee6693bd.png)

**Comment by harryhoch** [comment]
fixed by https://github.com/monarch-initiative/monarch-app/commit/870fe691442dc8933dc489ea0362910dc2388852

**Comment by sarahjkim** [comment]
I think this commit broke lots of things:
1. It changed the width of the navbar, so the site is no longer correctly dynamically responsive.
2. It changed the height of the navbar so spacing is off and content is hidden behind the thicker bar.
3. It reduced content window.

I'd like to suggest an alternative. I think if we really want examples at the search bar, it should be a hover effect that doesn't change the size of the navbar.

**Comment by harryhoch** [comment]
@sarahjkim, apologies if this change fouled things a bit. I think we can find some way to have examples that are up permanently without causing problems. A couple of thoughts:
1. I honestly don't see the problem with the navbar height, but it's not a big deal. We can change .navbar min-height and content padding-top to adjust the navbar height as needed. Yes, this does make a small reduction to the content window, but we can make this up with mods to spacing elsewhere if we need it. 
2. The width of the navbar can be tweaked by changing the width of #search, and the sample text and div for the search field in navbar.mustache. Can we shorten those to fit in the 180px that had previously been used? @nlwashington, can you suggest appropriate sample text?

**Comment by nlwashington** [comment]
I am not sure if @sarahkim messed things up, or if it was me. I will spend
time this morning reverting and figuring things out. Please don't commit
anything until then.

**Comment by harryhoch** [comment]
@nlwashington i think any fouling up on this issue would have been the result of my changes to the CSS. The navbar height and search width should be separate from the other issues that you're working on. That said, I will stay away until you give the all clear.

**Comment by harryhoch** [comment]
@sarahjkim , https://github.com/monarch-initiative/monarch-app/commit/26dc4e51fad203d3ca7ba36e6d5dd9d2e10befbd changes the width to make it closer to what it was before. If it is still not dynamically responsive the way that you'd like, can you try to do some css magic to make it work the way it should? 

I've always had a brain block with CSS, and I'm clearly hitting it this time. thanks..
