### ISSUE TITLE
bad cert?

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#1225]
www.monarchinitiative.org throws a cert that firefox and chrome complain about as not being configured properly.

**Comment by DoctorBud** [comment]
Lose the `www.`, that's the problem. In general, the `www.` prefix is deprecated.

However, many users will expect www to work, so we need to support it.

Looking at:
   http://serverfault.com/questions/358616/nginx-https-www-redirect-to-non-www?rq=1

Our options are to add `www.` to our certificate, which might be a hassle, depending on how LetsEncrypt works. I think this is the correct way.

Easier is to set a REDIRECT back to the browser telling it to stop using www.

**Comment by harryhoch** [comment]
yes. they should be equivalent urls.

**Comment by TomConlin** [comment]
#1209

**Comment by harryhoch** [comment]
thanks, @TomConlin, I should have caught that. @DoctorBud, I think people will be typing www... should be fixed.
