### ISSUE TITLE
analyze phenotypes leads to ajax error

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#1238]
https://monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0002067+HP%3A0001363+HP%3A0001159+HP%3A0030217+HP%3A0000678+HP%3A0001627+HP%3A0012594+MP%3A0000248&mode=search&target_species=all&limit=100

returns an ajax error  - see figure below.

Performance is generally not great - it looks like it's timing out. Sometimes, but not always, better on the second try.
@cmungall , @yuanzhou, is this an owlsim performance issue?

![2016-04-21_11-27-19](https://cloud.githubusercontent.com/assets/174707/14714741/26baa6ca-07b4-11e6-8568-2e443fe39542.png)

**Comment by cmungall** [comment]
To test the underlying owlsim call, this is what gets called:

https://monarchinitiative.org/owlsim/searchByAttributeSet?a=HP%3A0002067&a=HP%3A0001363&a=HP%3A0001159&a=HP%3A0030217&a=HP%3A0000678&a=HP%3A0001627&a=HP%3A0012594&a=MP%3A0000248&limit=100

For me returns in < 0.2s

**Comment by harryhoch** [comment]
yes. returns quickly for me as well. @yuanzhou , any idea what's up?

**Comment by cmungall** [comment]
could be other API calls that are wrapped

**Comment by harryhoch** [comment]
@cmungall, most likely. @yuanzhou, please dig into this.

**Comment by yuanzhou** [comment]
@harryhoch I just tested and didn't see any error message, it seems the owlsim was not responding very well yesterday.

**Comment by harryhoch** [comment]
@yuanzhou, perhaps, but that wouldn't explain why it ran quickly on the direct call, but slowly later...

**Comment by harryhoch** [comment]
I think this might have been an anomaly.
