### ISSUE TITLE
Literature pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#124]
We need 'literature' pages.

These should have tabs just like our other pages summarizing the mentioning of:

*models (asserted)
*genotypes
*diseases
*phenotypes
*pathways
*genes
*related publications -- this last one will be interesting... we can do the easy thing of "other publications that mention X (like genes, or same author, or whatever), but a novel idea is related publications based on phenotype!

*analyze -- our analyze functions ought to let us "search" for publications based on phenotypes too.  how cool is that?

**Comment by nlwashington** [comment]
If we want better search, say by author, we will need NIF to include authors in their literature indexing.  See JIRA ticket: https://support.crbs.ucsd.edu/browse/NIF-9854

**Comment by harryhoch** [comment]
see also https://github.com/monarch-initiative/monarch-app/issues/175

**Comment by nlwashington** [comment]
Literature indexing now includes authors and grant ids:

http://beta.neuinfo.org/services/v1/literature/pmid?pmid=22080565

**Comment by nlwashington** [comment]
These would have the form 
http://www.monarchinitiative.org/literature/PMID:22080565
There are a couple of ways we could "label" that identifier.  My initial thought is to just use the title of the article.  And the jumbotron should include a short citation (first author et al (year) issue:pages) as a subtitle.
The basic information about an article in the first tab should be populated with data acquired by the literature service, 
http://beta.neuinfo.org/services/resource_LiteratureService.html as described in #123.  
Which should show authors, title, short journal title (issue, pages, etc), mesh terms, and abstract.

**Comment by nlwashington** [comment]
We can initially populate a "similar papers" table that uses the /literature/moreLikePmid service.  This would be very cool.

**Comment by nlwashington** [comment]
@ccondit do you do any indexing with the ontology for literature services?  for example, it appears i can do this query:  http://beta.neuinfo.org/services/v1/literature/search?q=HP:0000478, but i don't think it's actually matching on 'abnormality of the eye', which is the ontology term that it's matching to.  have you considered this?

**Comment by ccondit** [comment]
Negative - that query is not correctly interpreted (it's just finding the numeric portion, I believe). Are you trying to perform closure queries on the literature index?

**Comment by nlwashington** [comment]
yes, that was my thought.  is that possible and/or good idea?  it might seem that it would have to go through some kind of annotation layer first, right (which could certainly provide many false positives)?

**Comment by nlwashington** [comment]
for the genes tab, we would need to access the l2_nif_0000_02801_data_gene2pubmed in nif.

**Comment by ccondit** [comment]
> yes, that was my thought. is that possible and/or good idea?

Oh, it's possible - but there's a problem with ambiguity of labels.
The federation closures are much more straightforward.

> it might seem that it would have to go through some kind of annotation layer first, right (which could certainly provide many false positives)?

You mean via some sort of human annotation?

**Comment by nlwashington** [comment]
no, by annotation i meant using your annotation services.

**Comment by ccondit** [comment]
> no, by annotation i meant using your annotation services.
> 
> Will have the same problem. Cat is a gene symbol, an organism, and probably
> many other things as well...

**Comment by sarahjkim** [comment]
@nlwashington @cmungall 
I started the skeleton for literature pages, and currently similar pages works by pulling from the moreLikePmid NIF Literature Service call.

![screen shot 2014-07-01 at 6 01 06 pm](https://cloud.githubusercontent.com/assets/4628853/3450758/5c38dfe8-0184-11e4-9e17-fc12688068d3.png)
![screen shot 2014-07-01 at 6 01 01 pm](https://cloud.githubusercontent.com/assets/4628853/3450759/5c46989a-0184-11e4-9b12-01990cc3dc66.png)
![screen shot 2014-07-01 at 6 00 56 pm](https://cloud.githubusercontent.com/assets/4628853/3450760/5c51087a-0184-11e4-92fa-5b173af9a316.png)

**Comment by jmcmurry** [comment]
This skeleton is still there: http://beta.monarchinitiative.org/literature/PMID:15459382
This looks like a very nice feature; moving to wishlist.

**Comment by nlwashington** [comment]
To populate all the tabs, we need the literature associations to be loaded into golr.

This is dependent on https://github.com/monarch-initiative/configs/issues/10.

**Comment by nlwashington** [comment]
@kshefchek would be nice to bring this back as well.
can you add back the display of the abstract, if available?

**Comment by cmungall** [comment]
Dupe: #1019
