### ISSUE TITLE
Discrepancy between UI and Uberpheno for term label ZP:0000306

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1240]
@kshefchek @TomConlin could you please investigate this?

In [the monarch UI](https://monarchinitiative.org/phenotype/ZP:0000306), we display the term label of `ZP:0000306` as `Abnormal(ly) dead whole organism`

[UPheno](http://www.berkeleybop.org/ontologies/upheno.obo) documents it as `increased occurrence of programmed cell death`

These are loosely related terms, but surely not equivalent.

**Comment by kshefchek** [comment]
The labels come from SciGraph, we just need to figure out where ZP classes are imported in http://purl.obolibrary.org/obo/upheno/monarch.owl
cc @cmungall

**Comment by iamkoehler** [comment]
> UPheno documents it as increased occurrence of programmed cell death

this seems really old and outdated. probably created before we made the IDs stable.

I guess it is better to look at: http://compbio.charite.de/jenkins/job/zp-owl/

But I is still a mystery how ZP is imported to monarch. Related to https://github.com/monarch-initiative/dipper/issues/283

**Comment by kshefchek** [comment]
Sounds like we're comparing against an older version of upheno, so I'm assuming this is a non issue? Please re open if I'm wrong.
