### ISSUE TITLE
searching on string returns an error: 15q13.3 homozygous microdeletion syndrome

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1245]
Searching on this string in monarch returns an error:
15q13.3 homozygous microdeletion syndrome

{"statusCode":500,"error":"Internal Server Error","message":"An internal server error occurred"}

Using OSX Chrome

**Comment by jmcmurry** [comment]
I believe this is a parsing error with the dot. Eg. 1.1 also fails.

**Comment by jmcmurry** [comment]
duplicate
