### ISSUE TITLE
duplicates on phenotype page

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1247]
On this page, there are two duplicates: https://monarchinitiative.org/disease/DOID:11984
Disease: Glycogen Storage Disease 2
has phenotype:  Abnormal EKG

![image](https://cloud.githubusercontent.com/assets/6722114/15233862/d57ec3e6-1860-11e6-84b0-fc803b8a7180.png)

**Comment by jmcmurry** [comment]
I can't reproduce this, but perhaps because I can't even see it as there are thousands of rows. Something might have changed to make duplicate rows discontiguous. I downloaded the data and didn't find a dup there either, however, so going to close this.
