### ISSUE TITLE
Skolemize the blank-node IRI

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/monarch-legacy#1249]
Request the path

https://monarchinitiative.org/.well-known/genid/*

lead to either:
a static page about blank node identifiers in general which says something like:
the supplied identifier is for a "RDF blank node" which has no existence 
beyond an organizing convenience within the dataset it is found.
or: 
a dynamic page that also includes any additional properties for the blank node 
we have (such as an rdfs:label)

Reason: 
Monarch does not in general mint identifiers, but we must for blank nodes
which are effectively existential assertions there is such a node. 

Logically, before such a node can be reasoned over it must be made concrete
(Skolem normal form).

Some of our tools may handle this internally but others, Protege in particular,
do not. So we produce datasets with fake IRIs.
That is, we mint identifiers which are deliberately broken (404).

Despite not currently being for generated for public consumption, these IRIs 
will inevitably escape and that should not be a mistake.

We could throw up anything to catch these so they don't 404, 
but since there is a recommended standard, deploying it correctly 
would be a good example to the other identifier minters we may collaborate with.

see https://www.w3.org/TR/rdf11-concepts/#dfn-blank-node

Effect
For normal use blank nodes keep their curie (without "MONARCH" on each & every) 
    _:abc123
which can be expanded to
    https://monarchinitiative.org/.well-known/genid/abc123 
for Protege etc.

Anyone seeing the IRI can figure out where it comes from,
Any following the link will get the identifier type and possibly more.

I would like to move away from having test specific code paths within the ingest
scripts. Having blank nodes be just one more curi/prefix with a proper persistent
resolvable IRI lends itself to allowing any subset of data be as testable as 
any other without any special processing on the part of the ingest scripts.

Anther possible uses for this mechanism is a destinations for the blank node @id
that will end up being created in the Json-LD based PhenoPackets which will be 
much more difficult to prevent leaking than dipper test sets.

**Comment by jmcmurry** [comment]
@TomConlin  Can you provide a specific (rather than general) scenario where this is a problem? What impact, if any, would skolemizing have on performance of our queries?

**Comment by TomConlin** [comment]
@cmungall this ticket starts with where the Skolemize IRI should go

**Comment by cmungall** [comment]
what is this .well-known URI?

one option is to add support for blank nodes in SciGraph and Golr. Worthwhile in the long run, but not minor.

Can we catalog the cases where blank nodes are used? Maybe we can just mint URIs, eg using UUIDs, pseudo-skolemization patterns. Of course we still need to build the UI templates that will display something useful for these.

I suspect many of the blank nodes we have are bad smells about overmodeling

Apart from associations, for which we may want to have a specific pattern

**Comment by TomConlin** [comment]
I interpret the the spec to be literal.  

"http://host/.well-known/genid/"  
not unlike   "http://host/robots.txt"  

seems I may not be the only one who interpreted it this way

[google search](https://encrypted.google.com/#hl=en&q=%22%2F.well%2Dknown%2Fgenid%22)

**Comment by cmungall** [comment]
Wasn't aware of that, thanks.

Another reason to avoid them (except in positions where they will not be 
exposed, e.g. OWL Restrictions)

**Comment by kshefchek** [comment]
Added with https://github.com/monarch-initiative/monarch-app/pull/1496, please see https://beta.monarchinitiative.org/.well-known/genid/asdf/asdf and reopen as needed.

**Comment by TomConlin** [comment]
thanks Kent
