### ISSUE TITLE
Information on orthologs should be more visible on gene pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1257]
This ticket replaces #351 (which I will close as it is specified around the old nif API)

this is something the original lamhdi supported that we don't do too well. we need to fan out first over orthologous-to and then has-phenotype. this could be visualized as a tree or a table, or a faceted view, not really important we just need to do it.

we could in theory do this entirely via scigraph as it's essentially graph oriented. However, we don't have central logic to calculate gene2phenotype, except what is materialized in solr.

solr doesn't support joins so if we do it via solr we need to pre-join

```
```

**Comment by balhoff** [comment]
May not be relevant but you have ever tried the joins in Solr 4? https://wiki.apache.org/solr/Join

I used to use them for Phenoscape and they worked well.

**Comment by mellybelly** [comment]
@jmcmurry @DoctorBud can you cook up display options, I like the idea of tree or faceting preferable to table

**Comment by mellybelly** [comment]
See also on the Amigo tacker: Display options showing all direct annotations to any member of ortholog set https://github.com/geneontology/amigo/issues/355
similar functionality needed for Monarch

**Comment by cmungall** [comment]
Good to know. cc @kltm

**Comment by jmcmurry** [comment]
As we now have [ortholog phenotypes tabs](https://monarchinitiative.org/gene/NCBIGene:6622#ortholog-phenotypes), I'm not sure what remains to be done on this particular ticket. @cmungall please advise.
