### ISSUE TITLE
Annotator html markup links not clickable

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1264]
See [annotate text](https://monarchinitiative.org/annotate/text?q=Lewis+%281978%29+found+7+affected+males+and+5+affected+females+in+3+consecutive+generations+of+a+Caucasian+kindred.+As+in+the+X-linked+Nettleship-Falls+form+of+ocular+albinism+%28300500%29%2C+the+patients+showed+reduced+visual+acuity%2C+photophobia%2C+nystagmus%2C+translucent+irides%2C+strabismus%2C+hypermetropic+refractive+errors%2C+and+albinotic+fundus+with+foveal+hypoplasia.+The+skin+lesions+showed+macromelanosomes+as+in+X-linked+ocular+albinism.+Deafness%2C+which+was+accompanied+by+vestibular+hypofunction%2C+lentigines+even+in+unexposed+areas%2C+optic+nerve+dysplasia%2C+and+dominant+inheritance+distinguished+this+form+of+ocular+albinism.+%28In+the+LEOPARD+syndrome+%28151100%29+vestibular+function+is+normal.%29%0D%0A%0D%0ABard+%281978%29+described+a+kindred+that+was+atypical+of+Waardenburg+syndrome+%28see+193510%29+in+several+ways.+Although+the+nasal+root+was+prominent%2C+one+affected+person+had+dystopia+of+the+inner+canthi+or+lower+puncta.+The+face+in+some+showed+striking+freckling+of+pale+skin.+Symptomatic+vestibular+disturbance+was+another+unusual+feature.+Lewis+%281989%29+expressed+the+opinion+that+the+family+reported+by+Bard+%281978%29+as+an+instance+of+Waardenburg+syndrome+in+fact+had+this+disorder.+Lewis+%281989%29+had+also+been+told+of+2+other+small+families+with+the+syndrome.+Goldberg+%281966%29+described+a+Waardenburg+syndrome+family+with+apparent+ocular+albinism.%0D%0A%0D%0AMorell+et+al.+%281997%29+presented+an+update+of+the+clinical+findings+in+the+family+of+Bard+%281978%29.+The+deafness+was+sensorineural+and+congenital.+Heterochromia+iridis+was+a+prominent+feature+in+1+sibship+in+which+both+segmental+iris+bicolor+and+complete+heterochromia+occurred.+Most+of+the+affected+individuals+showed+transillumination+defects+of+the+iris.+Hypopigmentation+of+the+fundus+was+mild+in+some%2C+moderate+in+others%2C+and+severe+in+yet+others.+Almost+all+affected+individuals+had+strabismus+and+visual+acuity+defects.+One+individual+with+a+prominent+white+forelock%2C+characteristic+of+Waardenburg+syndrome%2C+was+pictured.+%0D%0A++++++++++++++++++++++++)

Links are no longer clickable, likely a css issue.  Also, the hover box is no longer visible.

**Comment by jmcmurry** [comment]
This appears to have been fixed? @kshefchek?
