### ISSUE TITLE
Phenogrid broken on disease group pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1267]
For example:
https://monarchinitiative.org/disease/DOID:0060060
-> compare
TypeError: this.state.gridSkeletonData.xAxis is undefined

cc @yuanzhou

**Comment by kshefchek** [comment]
This is probably from our DRY violation, which I'm probably responsible for:
https://github.com/monarch-initiative/monarch-app/blob/master/js/phenogridloader-onclick.js
https://github.com/monarch-initiative/monarch-app/blob/master/js/phenogridloader-no-species.js

We should find a way to merge these.

**Comment by yuanzhou** [comment]
I think I can get this fixed very easily. I guess I forgot  to update https://github.com/monarch-initiative/monarch-app/blob/master/js/phenogridloader-onclick.js when I pushed all new changes.

**Comment by yuanzhou** [comment]
Fixed via https://github.com/monarch-initiative/monarch-app/commit/37adec48478526a46fbe0c89c53b11382ab283b1

**Comment by kshefchek** [comment]
Thanks!
