### ISSUE TITLE
no way to search for pmids

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1269]
pasting the pmid into the search box doesn't work, and gives an error if it is pasted like this: PMID:22860064. (This is in the system on this page: https://beta.monarchinitiative.org/phenotype/ZP:0014325) 

<img width="1440" alt="error" src="https://cloud.githubusercontent.com/assets/796636/15808295/1d27ec92-2b29-11e6-8ba0-49863da01826.png">

Searching just the local id itself gives results, but none of them are correct:
<img width="672" alt="unfound" src="https://cloud.githubusercontent.com/assets/796636/15808314/8de929e6-2b29-11e6-9d1b-4582f001ab39.png">

Related to #124

**Comment by kshefchek** [comment]
Edit: fixed with 1834ba0
