### ISSUE TITLE
Anatomy pages

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1271]
We need to introduce anatomy pages for classes in UBERON.
Tabs would be: 
- Expression (Tissue-specific data from BGee)
- Phenotypes (Where there is an associated anatomical part).

As usual we would use the logical definitions to subsume subclasses; however, there is some question in my mind about the type of relationships that are valuable to traverse. Eg. what does the "Overview" tab look like. What hierarchies do we expose?

For instance, it would be nice to see all phenotypes associated with the brain and all its sub-parts. But it would also be nice to see all phenotypes associated with the circulatory system and its components. These are functionally related but positionally dispersed. These subtleties have been relevant before for phenotypes, but for anatomy it seems especially difficult and important. I'm not that familiar with the UBERON structure, so perhaps this is easier than I'm giving it credit for. From a UI standpoint, though, I don't see this as terribly straightforward.

Please discuss. @cmungall @mellybelly

**Comment by cmungall** [comment]
Depends on https://github.com/monarch-initiative/dipper/issues/147

As a first pass the anatomy page could have the generic ontology info/graph (note: we will need part-ofs in hierarchy), plus a single tab for gene. We may be able to spin separate tabs and populate via scigraph from some extensive metadata in the ontology, e.g. images, species.

The phenotype tab on the anatomy page will require more thought. We will probably want an `affects` closure in phenotype associations, populated by following P->has-part->inheres-in|inheres_in_part_of

**Comment by jmcmurry** [comment]
nice viz: http://genome.ucsc.edu/cgi-bin/hgGtexTrackSettings?hgsid=571665579_afGfPWeYJLcu0466KHATIRd3eI0e&c=chr9&g=gtexGene

**Comment by cmungall** [comment]
cc @fbastian

**Comment by selewis** [comment]
I'll be visiting this group on Thursday if you have specific questions
you'd like me to ask.

**Comment by cmungall** [comment]
Looks like all the background work is done!

## First pass

 - [x] Dipperize https://github.com/monarch-initiative/dipper/pull/407
 - [x] Test query https://scigraph-data.monarchinitiative.org/scigraph/graph/neighbors/MGI%3A2685856?depth=1&blankNodes=false&relationshipType=RO%3A0002206&direction=BOTH&entail=false&project=*
 - [x] Add golr view https://github.com/monarch-initiative/monarch-cypher-queries/blob/master/src/main/cypher/golr-loader/gene-anatomy.yaml
 - [x] Test a solr query https://solr.monarchinitiative.org/solr/golr/select/?fq=subject_closure%3A%22MGI%3A2685856%22&fq=object_category%3A%22anatomy%22&rows=1000&fl=subject%2Csubject_label%2Crelation%2Cobject&facet.mincount=1&facet=off&wt=json&q=%2A%3A%2A&facet.limit=0
 - [x] [Check closure includes part of](https://github.com/SciGraph/golr-loader/issues/17) **IMPORTANT**
 - [x] Add a demo notebook
 - [x] Add a tab https://beta.monarchinitiative.org/gene/MGI:2685856

Here is an example command line query demonstrating this works:

```
qbiogolr.py MGI:2685856 -C anatomy
MGI:2685856     RO:0002206      UBERON:0003499;UBERON:0000922;UBERON:0005147;UBERON:0001068;UBERON:0001911;UBERON:0003220;UBERON:0000992;UBERON:0001844;UBERON:0000081;UBERON:0002116;UBERON:0006518;UBERON:0002048;UBERON:0001736;UBERON:0001343;UBERON:0001155;UBERON:0002197;UBERON:0008971;UBERON:0000982;UBERON:0000966;UBERON:0000947
```

## Second pass

 - [ ] scores

**Comment by cmungall** [comment]
I just realized I had the checklist here #1312

**Comment by jmcmurry** [comment]
Would love to see this happen. It would be important to demonstrate for Uberon proposal; when will this go in?

**Comment by cmungall** [comment]
Example of querying: https://github.com/biolink/ontobio/blob/master/notebooks/Gene_Expression.ipynb

(note: this uses an in-memory version of uberon so the lack of cached part-of closure in solr doesn't affect this)

**Comment by kshefchek** [comment]
Added with https://github.com/monarch-initiative/monarch-app/pull/1496

**Comment by jmcmurry** [comment]
When will this be live?

**Comment by kshefchek** [comment]
Hopefully in time for GSA (or COB today).
