### ISSUE TITLE
count for related diseases always says 1000

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#128]
currently, every disease has 1000 related diseases.  this is because we perform a query to fetch 1000 diseases.  i am surprised that it reports 1000 and not 25 (since 25 is what is shown).  

so we either don't want to include this metric in the overview, or we want to filter it.

if we filter, we should give a count that is above a certain cutoff (based on the score).  perhaps we should pick an arbitrary cutoff?  like filter the score of the matches to within 50% of the top score (which is itself).

for example, ORPHANET_209 has a top score of 5.54496.  a 50% cutoff would be any diseases with a score > 2.7725 (which would give lots, but probably < 1000).  or a 75% cutoff would be any diseases with a score > 4.15872 (which would give only itself).

this will be easy once there is a uniform score like phenodigm (0..100).

**Comment by sarahjkim** [comment]
The data counter counts the number of items in the JSON blob (not what is displayed). Sorry I hadn't realized there was sometimes a discrepancy. I can change this.

**Comment by cmungall** [comment]
Another option is to report the top scoring hit or n hits (where n is fairly low) in the overview tab

**Comment by sarahjkim** [comment]
I have updated the counter as of commit a1b0fd5046.

**Comment by harryhoch** [comment]
this appears to be fixed.
