### ISSUE TITLE
Add support to merge owlsim calls from multiple ID spaces

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1280]
Owlsim 2 does not have taxon support, so we set taxon limits by limiting ID space (OMIM, ZFIN, etc.)  However, we are currently losing results by only mapping to one ID: 
https://github.com/monarch-initiative/monarch-app/blob/master/lib/monarch/api.js#L4015

TODO, for human diseases we need [OMIM, Orphanet, DOID, etc.], for ZFIN genes we need to add NCBIGene.  For wormbase, WB should be Wormbase.

This needs to be fixed for our latest release.

**Comment by cmungall** [comment]
Wait, don't we use ZFIN as the clique leader for zebrafish genes?

We don't have any leaf annotations to DOID, only inferred

We should think more broadly about the Orphanet case, what we do about 
OMIM overlap

But yes WB should be fixed before next release. Annoyingly WB is used as 
prefix in GO

**Comment by kshefchek** [comment]
@cmungall see the latest data in https://github.com/monarch-initiative/monarch-owlsim-data/tree/master/data

```
    We don't have any leaf annotations to DOID, only inferred
```

I'll have to check these, perhaps we need to adjust the golr loader script?

```
    Wait, don't we use ZFIN as the clique leader for zebrafish genes?
```

Apparently not, see https://github.com/monarch-initiative/SciGraph-docker-monarch-data/blob/master/src/main/resources/monarchLoadConfiguration.yaml.tmpl#L131

**Comment by kshefchek** [comment]
Looking at the two column file used to load owlsim, it looks like the DOID ids are for non leaf diseases, so we can continue to filter these out.  Let me know what we should do about Orphanet, also OMIA and MESH ids in there.

1/3 of the IDs in the ZFIN gene_phenotype file are NCBIGene.

**Comment by kshefchek** [comment]
per @cmungall, we should try to regenerate the flat files with a preference for the correct ID spaces (for ZFIN).  Holding off on supporting Orphanet in the human disease/phenotype id space.

**Comment by jmcmurry** [comment]
Because local IDs in WormBase collide across types, it is actually better if we uniquify the prefixes with the corresponding type. WB-gene, WB-taxon, for instance.

**Comment by cmungall** [comment]
Actually the local IDs (part after ':') don't collide, the CURIEs are of the form

`WormBase:WBGene00000001`

**Comment by jmcmurry** [comment]
While it is true that the after-the-colon fragments don't collide for the entity types that we are currently interested in, consider that:

a) They have 20 different types in their corpus
b) Across this entire corpus the after-the-colon fragments do occasionally collide (by their own admission)
c) In any case, no two entity types can be resolved with a single URL pattern anyway

This to me suggests that typing in the prefix would be sensible unless we are able to implement context-sensitive prefix expansion. Am I overthinking this?

<img width="121" alt="screen shot 2016-06-14 at 4 19 42 pm" src="https://cloud.githubusercontent.com/assets/3658863/16063032/001140ac-324c-11e6-9be0-b6fd6accdef8.png">

**Comment by kshefchek** [comment]
I think we're over thinking this, for the sake of owlsim we only care about gene IDs at the moment.  But this is good food for thought when we start including variants, genotypes, and models.

**Comment by cmungall** [comment]
Yes.

It would be good to get an example of an after-the-colon collision, this
surprises me. It wouldn't surprise me if there was some confusion in
answering the question, and people were thinking purely of the numeric
part, but I don't know
