### ISSUE TITLE
Show blipkit disease merge on disease pages

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1283]
I've been getting requests for being able to view and up to date blipkit view of the merged diseases (e.g. https://github.com/monarch-initiative/monarch-disease-ontology/blob/master/src/mondo/images/mdo-doid-14330.png) for any given disease- perhaps it would be nice to generate something for the disease pages in monarch for this purpose? Not exactly the same as an ontology navigation tool, but more provenance/integration info. @cmungall

**Comment by cmungall** [comment]
Can you say more about the use case?

I think the color coded by source views are not of interest to general 
users, but are very useful for people aware of different 
ontologies/resources. If this is correct, something in the mondo repo 
may be more appropriate?

**Comment by cmungall** [comment]
I think this is going to be out of scope for the monarch app for a while. To do this we'd need to load all native disease ontologies which would introduce contradictions/incorrect paths. If this is a requirement should be done in a separate app. A reduced scope visualization may be in scope for the monarch app (e.g. color coding by xrefs) but we can make a new ticket
