### ISSUE TITLE
Some genotypes are not linked from coriell, not clear why

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1292]
<img width="1373" alt="screen shot 2016-07-11 at 9 22 26 am" src="https://cloud.githubusercontent.com/assets/3658863/16738301/fc853b7e-4749-11e6-97d5-ee26834c82a2.png">

Is this is an issue with the resolvability of the genotype identifiers?

**Comment by kshefchek** [comment]
The genotype is a blank node and thus not linked out anywhere.  It is likely not a resource in Coriell but assembled from information in the database.  Coriell models of Parkinson's are available in the models tab.  Can we triage this in some "add documentation" ticket?
