### ISSUE TITLE
Analyze Phenotypes: Confusing gene selection

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1297]
We need to think pretty carefully about how to improve the selection/input for gene sets. Hard problem to solve properly. Right now it is very confusing and hard to see the impact of any selection on the gene side as the new text appearing in the box is really too subtle and truly frustrating. I think the UI behavior should ideally be similar for both phenotype and gene selection because both kinds of inputs have a) labels b) identifiers and c) taxa. 

Consider this:
1) detect whether user is typing or pasting (mouse or keyboard paste). If pasting, activate scigraph annotator. If typing, activate autocomplete instead. In the pasting scenario, show a PatientArchive-like interface with the recognized entities highlighted, and recognized entities in the selection interface.

In the meantime, I wondered if we could at least do some of this?
For this release, all I really care about is fixing the hint text. That is low risk and really necessary.

![analyze phenotypes hint text](https://cloud.githubusercontent.com/assets/3658863/16741377/d9543b06-4757-11e6-9e41-48a3ca16eaa6.png)

**Comment by harryhoch** [comment]
@jmcmurry, please clarify - exactly which text should be changed?
@yuanzhou, how hard would these changes be?

**Comment by jmcmurry** [comment]
@harryhoch the changes below would be great. It could probably be even better; let me know if you have suggestions to clarify. The current behavior is so out of line with industry standards it is hard to know how to tell the user what to expect or how to use it. Until we have the resources to really fix the interface it should at least be narrated more clearly. I'm just a bit stumped.

<img width="884" alt="screen shot 2016-07-11 at 11 23 02 am" src="https://cloud.githubusercontent.com/assets/3658863/16741833/e97573ea-4759-11e6-9aec-5ca430575b0a.png">

**Comment by harryhoch** [comment]
Ok, so short term you just want those four pieces of text to be changed to your recommendations in red, right?

@yuanzhou, can you make those changes?

Medium term, I see a couple of possibilities:
1. we might try to improve the parsing so that Gene IDs could be entered alongside gene names, leaving us with something like the phenotype entry. I don't know how hard this would be in terms of validation.
2. we could hide the gene id entry in a separate tab or collapsed box, on the theory that this will be behavior for "expert" users.

**Comment by jmcmurry** [comment]
> Medium term, I see a couple of possibilities:
> 1. we might try to improve the parsing so that Gene IDs could be entered alongside gene names, leaving us with something like the phenotype entry. I don't know how hard this would be in terms of validation.

+1, but this is hard, not only in terms of validation but also in terms of UI. Entry of IDs or labels should ideally be possible in both scenarios (gene and phenotype). This is why just not worrying about the format so much and just going for the SciGraph annotator might really help. Comma separated? tab separated? line separated?...SciGraph doesn't care. Extra words? SciGraph doesn't care. I wouldn't invest too much effort trying to get the input validation just so.

> 1. we could hide the gene id entry in a separate tab or collapsed box, on the theory that this will be behavior for "expert" users.

100% agree; The tricky thing is the 'orthologs' 'paralogs' part which is still relevant, whether you enter Gene IDs or Gene symbols.

**Comment by harryhoch** [comment]
ok. let's discuss these possibilities..

**Comment by yuanzhou** [comment]
I've updated the hint text and sent the PR #1306 

![capture](https://cloud.githubusercontent.com/assets/195873/16769248/eaae45e0-4815-11e6-9468-74a2d9877307.PNG)

Please merge if everything looks good for the release purpose.

**Comment by jmcmurry** [comment]
I'm going to close this particular ticket as short-term fixes are done.

**Comment by jmcmurry** [comment]
Longer term goals broken out here: https://github.com/monarch-initiative/monarch-app/issues/1333
