### ISSUE TITLE
orphanet logo is cut off

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1299]
<img width="181" alt="screen shot 2016-07-11 at 11 56 32 am" src="https://cloud.githubusercontent.com/assets/3658863/16742861/915ae348-475e-11e6-9e04-830767cac898.png">

https://beta.monarchinitiative.org/phenotype/HP%3A0000316

**Comment by kshefchek** [comment]
We need to replace the image file, see:
https://github.com/monarch-initiative/monarch-app/blob/master/image/source-orphanet.png
