### ISSUE TITLE
Add annotation sufficiency score to genotype & disease pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#130]
We should show the 1-5 star rating on genotype and disease pages (and gene and variant in the future) based on the annotation_sufficiency score.

**Comment by nlwashington** [comment]
We should show the annotation sufficiency score (star rating?) for any given phenotypic profile.  We can use our sufficiency score owlsim service to fetch this.   These could be displayed on the Phenotype tab, or on the jumbotron.

The REST to get the score is like:
http://tartini.crbs.ucsd.edu/score?annotation_profile={"id":"UDP_3138", "features":[{"id":"HP:0000505"},{"id":"HP:0000479"},{"id":"HP:0001010"},{"id":"HP:0000044"},{"id":"HP:0001251"},{"id":"HP:0002072"},{"id":"HP:0007319"},{"id":"HP:0001300"}]}

but i've already written the relevant api function... it we should just call getInformationProfile with the annotations.

this will use the same categories as phenotips (first degree from root of HPO) as the basis of calculation.

**Comment by nlwashington** [comment]
Sarah, can you set up the framework for this?  For testing, assume there is an "annotation_sufficiency" score within the phenotype_association object on any disease, gene, or genotype page, can you add a star rating on the phenotype tab.

http://stackoverflow.com/questions/1987524/turn-a-number-into-star-rating-display-using-jquery-and-css

**Comment by nlwashington** [comment]
Additionally, next to the score, we're going to need a "?" popup that explains what the rating is.  I can provide language for that.

**Comment by sarahjkim** [comment]
Alright. I'll start working on this. :)

**Comment by sarahjkim** [comment]
What "?" popup text would you like?

**Comment by nlwashington** [comment]
For this item, let's try this:

The annotation score reflects how the breadth and depth of annotations for this <thing> compares to all of the other phenotypic profiles in our corpus. A high score means that the <thing> is richly annotated, both across a diverse set of phenotypic categories, as well as in the number and specificity of each of the phenotypes.

can you fill in the <thing> dynamically depending on what page type you are on (disease, gene, genotype)?

**Comment by sarahjkim** [comment]
The text can vary according to the page. It will actually be hardcoded into the page.

**Comment by sarahjkim** [comment]
@nlwashington I finished adding the stars to each phenotype tab on the disease, gene, and genotype pages. If the annotation_sufficiency score is null, it defaults to 0 stars. Else, it will show the correct number of stars. Once you've finished populating the JSON, maybe we can hide the stars if the annotation_sufficiency score is null.

**Comment by nlwashington** [comment]
added to disease pages with commit b7eace3
