### ISSUE TITLE
Hyperlink logo to source record?

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1300]
Thoughts?

<img width="181" alt="screen shot 2016-07-11 at 11 56 32 am" src="https://cloud.githubusercontent.com/assets/3658863/16743042/68dad7ce-475f-11e6-8188-017944384126.png">

Along with this idea would be to include the source record / link in the tsv download.

**Comment by jmcmurry** [comment]
Perhaps also a "more" button would be appropriate here too, like the way we've done with PMIDs.

<img width="172" alt="screen shot 2016-07-11 at 2 23 14 pm" src="https://cloud.githubusercontent.com/assets/3658863/16747251/15a932c6-4773-11e6-843c-81bcc1660a06.png">

**Comment by jmcmurry** [comment]
also related, could we use the proper HPO logo. Though I must admit that the font in the logo is really quite fine and ill suited to legibility at this scale. Could we adapt @drseb ?

Also teeeeeeny tiny suggestion that I can happily postpone indefinitely; any chance of getting the transparent versions of the logos? They look slightly odd with white boxes on the light grey background.

**Comment by pnrobinson** [comment]
I think that we should probably think harder about the HPO logo -- We need to add a doohickey or two that will suggest the connection between DNA and phenotype or whatever. But for now we can just use gimp to get rid of the whiteness. Where did you get the original from Julie, here? (http://human-phenotype-ontology.github.io/img/placeholder.jpg).

**Comment by mellybelly** [comment]
we should also make a HPO+Monarch logo for use in attribution in other sites

**Comment by pnrobinson** [comment]
+1
Anyone wanna take a 1st stab?

**Comment by jmcmurry** [comment]
> Where did you get the original from Julie, here? (http://human-phenotype-ontology.github.io/img/placeholder.jpg).

Probably?

I previously did try to mock up some HPO logos before I knew this one existed. I got nowhere. Normally I have a half way decent idea to start with. In this case, incredibly hard. Plus you need three versions of the logo:

1) Horizontal
2) Stacked
3) Favicon sized

1 and 2 also need to have versions that work on a dark background without looking silly. If you guys come up with any ideas, I can run with them, but I'm stumped on this one.

**Comment by jmcmurry** [comment]
I'm going to close this as it is an approximate duplicate. https://github.com/monarch-initiative/monarch-app/issues/822 is more comprehensive.
