### ISSUE TITLE
Three replicates of "Marfan syndrome disease" in autocomplete

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1302]
<img width="566" alt="screen shot 2016-07-11 at 2 15 35 pm" src="https://cloud.githubusercontent.com/assets/3658863/16747041/f90838e8-4771-11e6-8c28-9a99c480b6ff.png">

**Comment by jmcmurry** [comment]
Also two duplicates of Marfanoid craniosynostosis syndrome

**Comment by cmungall** [comment]
MonDO has two classes with the same label for Marfan: https://github.com/monarch-initiative/monarch-disease-ontology/issues/101

I don't know why the AC is showing 3 though

**Comment by kshefchek** [comment]
The third is an OMIA class.

**Comment by cmungall** [comment]
The label for all OMIA classes is suffixed "in other animals" to 
disambiguate

**Comment by kshefchek** [comment]
This class OMIA:000628-9913 ! "Marfan Syndrome" 
has a parent OMIA:000628 ! "Marfan syndrome (in other animals)"

See https://monarchinitiative.org/disease/OMIA:000628-9913

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-app/pull/1546
