### ISSUE TITLE
Analyze Phenotypes: Phenogrid widget extends beyond page boundaries. C elegans repeated.

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1304]
<img width="1366" alt="screen shot 2016-07-11 at 2 46 47 pm" src="https://cloud.githubusercontent.com/assets/3658863/16747985/628dbc3a-4776-11e6-80d6-b0d0f8699d09.png">

This makes it virtually impossible to see that there options to be had and thus getting to additional hits within human is also impossible.

**Comment by jnguyenx** [comment]
@jmcmurry can you please include the link to the page?

**Comment by jmcmurry** [comment]
It seems to happen anytime there are specific wormbase phenotypes present in the inputs. Eg. https://monarchinitiative.org/analyze/phenotypes?input_items=WBPhenotype%3A0000848&mode=search&target_species=all&limit=100&gene_list=

**Comment by harryhoch** [comment]
@yuanzhou ?

**Comment by yuanzhou** [comment]
I think it's because the rendered SVG is wider than the viewpoint of the page. I tried to resize the page and could reproduce the overflow. The web page is using fluid layout, while the rendered SVG is fixed width.

**Comment by harryhoch** [comment]
So, we probably need to limit the number of species shown by default I thin that would be easiest. @yuanzhou, what do you think?

**Comment by jmcmurry** [comment]
I think it works with the 5 species x 10 hits each; the main issue in the above is that worm is repeated. That issue has since been addressed though.

**Comment by harryhoch** [comment]
This is fixed.
