### ISSUE TITLE
missing fly genotypes - bad link

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1311]
https://monarchinitiative.org/phenotype/FBbt:00015899PHENOTYPE 
this page links to
https://monarchinitiative.org/genotype/http://www.monarchinitiative.org/MONARCH_FBgeno328111

**Comment by kshefchek** [comment]
Will be resolved in the next scigraph load.  This is resulting from a combination of using ntriples for flybase, and changing the curie map between updates.
