### ISSUE TITLE
Default to wildcard endings in search results

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1313]
Currently, the search results page leaves out partial matches. This may be by design, but it leads to weird behavior. For instance when searching for "PAX" (free text search in all results) you don't get matches for PAX6, for example.

https://monarchinitiative.org/search/pax

**Comment by jnguyenx** [comment]
Cause by how the labels are defined:

> clinvar_test.ttl:    rdfs:label "PAX3, 1-BP DEL, 556C" ;
> clinvar_test.ttl:    rdfs:label "PAX3, 18-BP DEL, EX2" ;
> kegg_test.ttl:    rdfs:label "some variant of PAX6" ;

https://monarchinitiative.org/search/some%20of%20variant%20PAX6 will return PAX6's.

Fix: search for `*PAX*` instead of `PAX*`.

**Comment by jmcmurry** [comment]
whoa, wildcard search actually does work; changing the phrasing of this ticket accordingly.
https://monarchinitiative.org/search/pax*

The issue Jeremy raised is still pertinent, but the desired behavior is still the same. It will also help us to get a step closer to addressing the punctuation issues. wilson v wilson's. Are there scenarios where wildcarding everything will lead to too many results (note that before implementing this, if we implement this, we would need to ensure that ranking is done a whole lot better than it currently is.) @cmungall? @mellybelly?

**Comment by jmcmurry** [comment]
This is now live on beta. Provisionally closing it
