### ISSUE TITLE
WS2B records are confusing or improperly classified.

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1318]
@cmungall, @kshefchek  thoughts?

https://monarchinitiative.org/disease/NCBIGene:7488 and https://monarchinitiative.org/disease/OMIM:600193 seem like they should be equivalent based on their content. However it isn't immediately clear to me why there is a disease described in NCBI Gene instead of somewhere else. Clearly WS2B must be the causal gene for this disease, but something about it still feels like it needs clarification or fixing. 

If these are legit records and classifications, it may be a MONDO issue instead as these should probably be merged.

**Comment by kshefchek** [comment]
This will be fixed when the beta servers are pushed to production.

**Comment by jmcmurry** [comment]
Great; can we assume it will also fix the related issues?
<img width="231" alt="screen shot 2016-07-26 at 3 27 30 pm" src="https://cloud.githubusercontent.com/assets/3658863/17157638/8e28beb4-5345-11e6-8f8a-3d153aaf935a.png">
<img width="248" alt="screen shot 2016-07-26 at 3 25 28 pm" src="https://cloud.githubusercontent.com/assets/3658863/17157640/9075240a-5345-11e6-803f-abebfaf722e7.png">
<img width="307" alt="screen shot 2016-07-26 at 3 28 55 pm" src="https://cloud.githubusercontent.com/assets/3658863/17157664/b30cc414-5345-11e6-9379-06cb3a58eebf.png">

**Comment by jmcmurry** [comment]
I think this issue is a duplicate of this one: https://github.com/monarch-initiative/dipper/issues/356 @kshefchek please confirm.

**Comment by kshefchek** [comment]
Yes, iirc these are either from omim-ncbi incorrect eqs, or an older version of mondo.owl, either way it should be fixed in the next data release.  We could collapse all of these cases into one ticket if that makes sense.
