### ISSUE TITLE
terminology

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#132]
We should get our "not quite ready for prime-time" language to be consistent. Most of the pages say "sneak peek", but the banner on some pages says "This is the beta interface". Which is it - sneak peek or beta? I can make the change if we have a consensus.

**Comment by cmungall** [comment]
These are orthogonal. tartini is the beta site, and the beta message only shows up on the beta. Compare with the link you follow to the production site. Necessary as google is indexing tartini right now.

**Comment by harryhoch** [comment]
Ah. Didn't see the logic. Apologies....
