### ISSUE TITLE
I can not start monarch-app using command "npm run start"

### ISSUE THREAD

**Issue by liuzhuo14** [monarch-initiative/monarch-legacy#1323]
I cloned monarch-app from GitHub repo. and installed it in following steps:
1. Install nvm（Node Version Manager）for managing NodeJS
2. Install NPM and NodeJS
3. run "npm version", make sure node version is 0.12.2 and npm version is 3.4.0
4. Download and install Monarch: clone and run ./install.sh in monarch-app root directory
5. run "npm run start"

At the last step I got an error:
`[gulp] Downloading https://raw.githubusercontent.com/phenopackets/phenopacket-format/master/schema/phenopacket-schema.json... undefined% Done
node: bad option: --harmony_destructuring

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "start"
npm ERR! node v0.12.2
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE
npm ERR! monarch-app@0.0.1 start: `gulp build && NODE_PATH=lib/monarch node --harmony_destructuring lib/monarch/web/webapp_launcher.js`
npm ERR! Exit status 9
npm ERR!
npm ERR! Failed at the monarch-app@0.0.1 start script 'gulp build && NODE_PATH=lib/monarch node --harmony_destructuring lib/monarch/web/webapp_launcher.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the monarch-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && NODE_PATH=lib/monarch node --harmony_destructuring lib/monarch/web/webapp_launcher.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls monarch-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/liuzhuo/monarch-app/npm-debug.log`

Then I remove the --harmony_destructuring option of "start" command in package.json, because the error said --harmony_destructuring is a bad option. But I could not start monarch-app either and got a new error:
`[gulp] Downloading https://raw.githubusercontent.com/phenopackets/phenopacket-format/master/schema/phenopacket-schema.json... undefined% Done
Starting server. Platform: NodeJS. Environment: dev. Port: 8080.
NODEVERSION: v0.12.2
defaultConfigFile: conf/server_config_dev.json golrConfigFile: conf/golr-conf.json
defaultConfig: {"type":"dev","app_base":"","scigraph_url":"https://scigraph-ontology-dev.monarchinitiative.org/scigraph/","scigraph_data_url":"https://scigraph-data-dev.monarchinitiative.org/scigraph/","golr_url":"https://solr-dev.monarchinitiative.org/solr/golr/","owlsim_services_url":"https://beta.monarchinitiative.org/owlsim","analytics_id":""}
/home/liuzhuo/monarch-app/lib/monarch/phenopacket.js:15
class PhenoPacket {
^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/liuzhuo/monarch-app/lib/monarch/phenopacket-builder.js:2:19)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "node" "/usr/bin/npm" "run" "start"
npm ERR! node v0.12.2
npm ERR! npm  v3.4.0
npm ERR! code ELIFECYCLE
npm ERR! monarch-app@0.0.1 start: `gulp build && NODE_PATH=lib/monarch node lib/monarch/web/webapp_launcher.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the monarch-app@0.0.1 start script 'gulp build && NODE_PATH=lib/monarch node lib/monarch/web/webapp_launcher.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the monarch-app package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build && NODE_PATH=lib/monarch node lib/monarch/web/webapp_launcher.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls monarch-app
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/liuzhuo/monarch-app/npm-debug.log`

How can I cover these errors and start monarch-app ? 
Thank you for help!

**Comment by kshefchek** [comment]
We recently updated our code to require >node 4.4.1, could you try running the app with 4.4.1?

**Comment by liuzhuo14** [comment]
Thank you @kshefchek. I installed node 4.4.1 and npm 3.4.0, and clone the new repo.
But I got a new error. When I run install.sh, I got this error:

`buffer.js:140
    throw new TypeError('must start with number, buffer, array or string');
    ^
TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:140:11)
    at new Buffer (buffer.js:62:10)
    at Request.downloadHandler [as _callback] (/home/liuzhuo/prog/monarch-app/node_modules/gulp-download/index.js:37:57)
    at self.callback (/home/liuzhuo/prog/monarch-app/node_modules/gulp-download/node_modules/request/request.js:187:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/home/liuzhuo/prog/monarch-app/node_modules/gulp-download/node_modules/request/request.js:813:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
`

Then, after I run install.sh, the app seem to be installed. But when I run "npm run start", I was stacked here:

`[12:42:00] Finished 'build' after 7.76 μs
[gulp] Downloading https://raw.githubusercontent.com/phenopackets/phenopacket-format/master/schema/phenopacket-schema.json... undefined% Done
Starting server. Platform: NodeJS. Environment: dev. Port: 8080.
NODEVERSION: v4.4.1
defaultConfigFile: conf/server_config_dev.json golrConfigFile: conf/golr-conf.json
defaultConfig: {"type":"dev","app_base":"","scigraph_url":"https://scigraph-ontology.monarchinitiative.org/scigraph/","scigraph_data_url":"https://scigraph-data.monarchinitiative.org/scigraph/","golr_url":"https://solr.monarchinitiative.org/solr/golr/","owlsim_services_url":"https://monarchinitiative.org/owlsim","analytics_id":""}
#USE_BUNDLE enabled
bbop.monarch.Engine Using pre-set configuration:
bbop.monarch.Engine Using pre-set golr configuration:
HapiJS Server running at: http://0.0.0.0:8080
`

**Comment by liuzhuo14** [comment]
I realized that the last sentence means monarch-app is running. so I try to access http://myServerAddress:8080, but I got an ETIMEDOUT error:

`HapiJS Server running at: http://0.0.0.0:8080
blog: get new results
Debug: internal, implementation, error
    Error: connect ETIMEDOUT 216.58.197.97:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1057:14)
`

How to fix it?

**Comment by jnguyenx** [comment]
@liuzhuo14 can you please delete the generated folder `node_modules/` and start over by running the `install.sh` script? I guess that there are some leftovers from your previous try.
