### ISSUE TITLE
Fix Inconsistent tab label and URL

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1326]
`https://monarchinitiative.org/gene/NCBIGene:6622#ortholog-phenotypes` vs tab title which says `homolog phenotypes`. 

Are we including paralog phenotypes in the results? If so we should change https://monarchinitiative.org/gene/NCBIGene:6622#ortholog-phenotypes to https://monarchinitiative.org/gene/NCBIGene:6622#homolog-phenotypes

If we are not including paralog phenotypes, why not?

**Comment by kshefchek** [comment]
See https://github.com/SciGraph/golr-loader/issues/16#issuecomment-231207027

**Comment by jmcmurry** [comment]
@jnguyenx does your yaml fix in  SciGraph/golr-loader#16 (comment) include changing tab title "homolog phenotypes"?

**Comment by jnguyenx** [comment]
No I didn't touch the UI. But we're not capturing paralogs anymore, it was a mistake. It should be fixed with the next load.

**Comment by jmcmurry** [comment]
Thanks @jnguyenx that's fine. @kshefchek can you change the tab title please?

**Comment by kshefchek** [comment]
Sure thing, will update the tab title when the solr table only contains orthologs.
