### ISSUE TITLE
organize and update publications

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#133]
Nicole V. can help coordinate this, will let her know.

**Comment by sarahjkim** [comment]
The Publications page is http://tartini.crbs.ucsd.edu/page/pubs. Please let me know what you'd like fixed/added. I think there are now some dead links, but I'm not sure what publications to put on the page.

**Comment by cmungall** [comment]
The page is blank....

**Comment by mellybelly** [comment]
Sarah, please remove the mendelay link population and instead add this static info for now. The mendelay info is all papers of relevance, not just ours. I think we can do something more sophisticated later, but need to fix for this release.

1: Van Slyke CE, Bradford YM, Westerfield M, Haendel MA. The zebrafish anatomy
and stage ontologies: representing the anatomy and development of Danio rerio. J 
Biomed Semantics. 2014 Feb 25;5(1):12. doi: 10.1186/2041-1480-5-12. PubMed PMID: 
24568621; PubMed Central PMCID: PMC3944782.

2: Köhler S, Doelken SC, Mungall CJ, Bauer S, Firth HV, Bailleul-Forestier I,
Black GC, Brown DL, Brudno M, Campbell J, FitzPatrick DR, Eppig JT, Jackson AP,
Freson K, Girdea M, Helbig I, Hurst JA, Jähn J, Jackson LG, Kelly AM, Ledbetter
DH, Mansour S, Martin CL, Moss C, Mumford A, Ouwehand WH, Park SM, Riggs ER,
Scott RH, Sisodiya S, Van Vooren S, Wapner RJ, Wilkie AO, Wright CF, Vulto-van
Silfhout AT, de Leeuw N, de Vries BB, Washingthon NL, Smith CL, Westerfield M,
Schofield P, Ruef BJ, Gkoutos GV, Haendel M, Smedley D, Lewis SE, Robinson PN.
The Human Phenotype Ontology project: linking molecular biology and disease
through phenotype data. Nucleic Acids Res. 2014 Jan;42(Database issue):D966-74.
doi: 10.1093/nar/gkt1026. Epub 2013 Nov 11. PubMed PMID: 24217912; PubMed Central
PMCID: PMC3965098.

3: Robinson PN, Köhler S, Oellrich A; Sanger Mouse Genetics Project, Wang K,
Mungall CJ, Lewis SE, Washington N, Bauer S, Seelow D, Krawitz P, Gilissen C,
Haendel M, Smedley D. Improved exome prioritization of disease genes through
cross-species phenotype comparison. Genome Res. 2014 Feb;24(2):340-8. doi:
10.1101/gr.160325.113. Epub 2013 Oct 25. PubMed PMID: 24162188; PubMed Central
PMCID: PMC3912424.

4: Druzinsky R, Mungall C, Haendel M, Lapp H, Mabee P. What is an anatomy
ontology? Anat Rec (Hoboken). 2013 Dec;296(12):1797-9. doi: 10.1002/ar.22805.
Epub 2013 Oct 11. PubMed PMID: 24127438.

5: Arighi CN, Carterette B, Cohen KB, Krallinger M, Wilbur WJ, Fey P, Dodson R,
Cooper L, Van Slyke CE, Dahdul W, Mabee P, Li D, Harris B, Gillespie M, Jimenez
S, Roberts P, Matthews L, Becker K, Drabkin H, Bello S, Licata L,
Chatr-aryamontri A, Schaeffer ML, Park J, Haendel M, Van Auken K, Li Y, Chan J,
Muller HM, Cui H, Balhoff JP, Chi-Yang Wu J, Lu Z, Wei CH, Tudor CO, Raja K,
Subramani S, Natarajan J, Cejuela JM, Dubey P, Wu C. An overview of the
BioCreative 2012 Workshop Track III: interactive text mining task. Database
(Oxford). 2013 Jan 17;2013:bas056. doi: 10.1093/database/bas056. Print 2013.
PubMed PMID: 23327936; PubMed Central PMCID: PMC3625048.

6: Dahdul WM, Balhoff JP, Blackburn DC, Diehl AD, Haendel MA, Hall BK, Lapp H,
Lundberg JG, Mungall CJ, Ringwald M, Segerdell E, Van Slyke CE, Vickaryous MK,
Westerfield M, Mabee PM. A unified anatomy ontology of the vertebrate skeletal
system. PLoS One. 2012;7(12):e51070. doi: 10.1371/journal.pone.0051070. Epub 2012
Dec 10. PubMed PMID: 23251424; PubMed Central PMCID: PMC3519498.

7: Mungall CJ, Torniai C, Gkoutos GV, Lewis SE, Haendel MA. Uberon, an
integrative multi-species anatomy ontology. Genome Biol. 2012 Jan 31;13(1):R5.
doi: 10.1186/gb-2012-13-1-r5. PubMed PMID: 22293552; PubMed Central PMCID:
PMC3334586.

8: Dahdul WM, Lundberg JG, Midford PE, Balhoff JP, Lapp H, Vision TJ, Haendel MA,
Westerfield M, Mabee PM. The teleost anatomy ontology: anatomical representation 
for the genomics age. Syst Biol. 2010 Jul;59(4):369-83. doi:
10.1093/sysbio/syq013. Epub 2010 Mar 29. PubMed PMID: 20547776; PubMed Central
PMCID: PMC2885267.

9: Mungall CJ, Gkoutos GV, Smith CL, Haendel MA, Lewis SE, Ashburner M.
Integrating phenotype ontologies across multiple species. Genome Biol. 2010 Jan
8;11(1):R2. doi: 10.1186/gb-2010-11-1-r2. PubMed PMID: 20064205; PubMed Central
PMCID: PMC2847714.

10: Washington NL, Haendel MA, Mungall CJ, Ashburner M, Westerfield M, Lewis SE. 
Linking human diseases to animal models using ontology-based phenotype
annotation. PLoS Biol. 2009 Nov;7(11):e1000247. doi:
10.1371/journal.pbio.1000247. Epub 2009 Nov 24. PubMed PMID: 19956802; PubMed
Central PMCID: PMC2774506.

11: Mabee PM, Arratia G, Coburn M, Haendel M, Hilton EJ, Lundberg JG, Mayden RL, 
Rios N, Westerfield M. Connecting evolutionary morphology to genomics using
ontologies: a case study from Cypriniformes including zebrafish. J Exp Zool B Mol
Dev Evol. 2007 Sep 15;308(5):655-68. Review. PubMed PMID: 17599725.

12: Mabee PM, Ashburner M, Cronk Q, Gkoutos GV, Haendel M, Segerdell E, Mungall
C, Westerfield M. Phenotype ontologies: the bridge between genomics and
evolution. Trends Ecol Evol. 2007 Jul;22(7):345-50. Epub 2007 Apr 9. PubMed PMID:
17416439.

13: Buttigieg PL, Morrison N, Smith B, Mungall CJ, Lewis SE; ENVO Consortium. The
environment ontology: contextualising biological and biomedical entities. J
Biomed Semantics. 2013 Dec 11;4(1):43. doi: 10.1186/2041-1480-4-43. PubMed PMID: 
24330602; PubMed Central PMCID: PMC3904460.

14: Köhler S, Doelken SC, Ruef BJ, Bauer S, Washington N, Westerfield M, Gkoutos 
G, Schofield P, Smedley D, Lewis SE, Robinson PN, Mungall CJ. Construction and
accessibility of a cross-species phenotype ontology along with gene annotations
for biomedical research. Version 2. F1000Res. 2013 Feb 1 [revised 2014 Jan
21];2:30. doi: 10.12688/f1000research.2-30.v2. eCollection 2013. PubMed PMID:
24358873; PubMed Central PMCID: PMC3799545.

15: Andersson R, Gebhard C, Miguel-Escalada I, Hoof I, Bornholdt J, Boyd M, Chen 
Y, Zhao X, Schmidl C, Suzuki T, Ntini E, Arner E, Valen E, Li K, Schwarzfischer
L, Glatz D, Raithel J, Lilje B, Rapin N, Bagger FO, Jørgensen M, Andersen PR,
Bertin N, Rackham O, Burroughs AM, Baillie JK, Ishizu Y, Shimizu Y, Furuhata E,
Maeda S, Negishi Y, Mungall CJ, Meehan TF, Lassmann T, Itoh M, Kawaji H, Kondo N,
Kawai J, Lennartsson A, Daub CO, Heutink P, Hume DA, Jensen TH, Suzuki H,
Hayashizaki Y, Müller F; FANTOM Consortium, Forrest AR, Carninci P, Rehli M,
Sandelin A, Kawaji H, Baillie JK, de Hoon MJ, Haberle V, Lassmann T, Kulakovskiy 
IV, Lizio M, Itoh M, Andersson R, Mungall CJ, Meehan TF, Schmeier S, Bertin N,
Jørgensen M, Dimont E, Arner E, Schmid C, Schaefer U, Medvedeva YA, Plessy C,
Vitezic M, Severin J, Semple CA, Ishizu Y, Young RS, Francescatto M, Alam I,
Albanese D, Altschuler GM, Arakawa T, Archer JA, Arner P, Babina M, Rennie S,
Balwierz PJ, Beckhouse AG, Pradhan-Bhatt S, Blake JA, Blumenthal A, Bodega B,
Bonetti A, Briggs J, Brombacher F, Burroughs AM, Califano A, Cannistraci CV,
Carbajo D, Chen Y, Chierici M, Ciani Y, Clevers HC, Dalla E, Davis CA, Detmar M, 
Diehl AD, Dohi T, Drabløs F, Edge AS, Edinger M, Ekwall K, Endoh M, Enomoto H,
Fagiolini M, Fairbairn L, Fang H, Farach-Carson MC, Faulkner GJ, Favorov AV,
Fisher ME, Frith MC, Fujita R, Fukuda S, Furlanello C, Furuno M, Furusawa J,
Geijtenbeek TB, Gibson AP, Gingeras T, Goldowitz D, Gough J, Guhl S, Guler R,
Gustincich S, Ha TJ, Hamaguchi M, Hara M, Harbers M, Harshbarger J, Hasegawa A,
Hasegawa Y, Hashimoto T, Herlyn M, Hitchens KJ, Ho Sui SJ, Hofmann OM, Hoof I,
Hori F, Huminiecki L, Iida K, Ikawa T, Jankovic BR, Jia H, Joshi A, Jurman G,
Kaczkowski B, Kai C, Kaida K, Kaiho A, Kajiyama K, Kanamori-Katayama M, Kasianov 
AS, Kasukawa T, Katayama S, Kato S, Kawaguchi S, Kawamoto H, Kawamura YI,
Kawashima T, Kempfle JS, Kenna TJ, Kere J, Khachigian LM, Kitamura T, Klinken SP,
Knox AJ, Kojima M, Kojima S, Kondo N, Koseki H, Koyasu S, Krampitz S, Kubosaki A,
Kwon AT, Laros JF, Lee W, Lennartsson A, Li K, Lilje B, Lipovich L, Mackay-sim A,
Manabe R, Mar JC, Marchand B, Mathelier A, Mejhert N, Meynert A, Mizuno Y, de
Lima Morais DA, Morikawa H, Morimoto M, Moro K, Motakis E, Motohashi H, Mummery
CL, Murata M, Nagao-Sato S, Nakachi Y, Nakahara F, Nakamura T, Nakamura Y,
Nakazato K, van Nimwegen E, Ninomiya N, Nishiyori H, Noma S, Nozaki T, Ogishima
S, Ohkura N, Ohmiya H, Ohno H, Ohshima M, Okada-Hatakeyama M, Okazaki Y, Orlando 
V, Ovchinnikov DA, Pain A, Passier R, Patrikakis M, Persson H, Piazza S,
Prendergast JG, Rackham OJ, Ramilowski JA, Rashid M, Ravasi T, Rizzu P, Roncador 
M, Roy S, Rye MB, Saijyo E, Sajantila A, Saka A, Sakaguchi S, Sakai M, Sato H,
Satoh H, Savvi S, Saxena A, Schneider C, Schultes EA, Schulze-Tanzil GG,
Schwegmann A, Sengstag T, Sheng G, Shimoji H, Shimoni Y, Shin JW, Simon C,
Sugiyama D, Sugiyama T, Suzuki M, Suzuki N, Swoboda RK, 't Hoen PA, Tagami M,
Takahashi N, Takai J, Tanaka H, Tatsukawa H, Tatum Z, Thompson M, Toyoda H,
Toyoda T, Valen E, van de Wetering M, van den Berg LM, Verardo R, Vijayan D,
Vorontsov IE, Wasserman WW, Watanabe S, Wells CA, Winteringham LN, Wolvetang E,
Wood EJ, Yamaguchi Y, Yamamoto M, Yoneda M, Yonekura Y, Yoshida S, Zabierowski
SE, Zhang PG, Zhao X, Zucchelli S, Summers KM, Suzuki H, Daub CO, Kawai J,
Heutink P, Hide W, Freeman TC, Lenhard B, Bajic VB, Taylor MS, Makeev VJ, Hume
DA, Hayashizaki Y. An atlas of active enhancers across human cell types and
tissues. Nature. 2014 Mar 27;507(7493):455-61. doi: 10.1038/nature12787. PubMed
PMID: 24670763.

16: Meehan TF, Vasilevsky NA, Mungall CJ, Dougall DS, Haendel MA, Blake JA, Diehl
AD. Ontology based molecular signatures for immune cell types via gene expression
analysis. BMC Bioinformatics. 2013 Aug 30;14:263. doi: 10.1186/1471-2105-14-263. 
PubMed PMID: 24004649; PubMed Central PMCID: PMC3844401.

17: Roncaglia P, Martone ME, Hill DP, Berardini TZ, Foulger RE, Imam FT, Drabkin 
H, Mungall CJ, Lomax J. The Gene Ontology (GO) Cellular Component Ontology:
integration with SAO (Subcellular Anatomy Ontology) and other recent
developments. J Biomed Semantics. 2013 Oct 7;4(1):20. doi:
10.1186/2041-1480-4-20. PubMed PMID: 24093723; PubMed Central PMCID: PMC3852282.

18: Maynard SM, Mungall CJ, Lewis SE, Imam FT, Martone ME. A knowledge based
approach to matching human neurodegenerative disease and animal models. Front
Neuroinform. 2013 May 14;7:7. doi: 10.3389/fninf.2013.00007. eCollection 2013.
PubMed PMID: 23717278; PubMed Central PMCID: PMC3653101.

19: Smedley D, Oellrich A, Köhler S, Ruef B; Sanger Mouse Genetics Project,
Westerfield M, Robinson P, Lewis S, Mungall C. PhenoDigm: analyzing curated
annotations to associate animal models with human diseases. Database (Oxford).
2013 May 9;2013:bat025. doi: 10.1093/database/bat025. Print 2013. PubMed PMID:
23660285; PubMed Central PMCID: PMC3649640.

20: Doelken SC, Köhler S, Mungall CJ, Gkoutos GV, Ruef BJ, Smith C, Smedley D,
Bauer S, Klopocki E, Schofield PN, Westerfield M, Robinson PN, Lewis SE.
Phenotypic overlap in the contribution of individual genes to CNV pathogenicity
revealed by cross-species computational analysis of single-gene mutations in
humans, mice and zebrafish. Dis Model Mech. 2013 Mar;6(2):358-72. doi:
10.1242/dmm.010322. Epub 2012 Oct 25. PubMed PMID: 23104991; PubMed Central
PMCID: PMC3597018.

21: Osumi-Sutherland D, Reeve S, Mungall CJ, Neuhaus F, Ruttenberg A, Jefferis
GS, Armstrong JD. A strategy for building neuroanatomy ontologies.
Bioinformatics. 2012 May 1;28(9):1262-9. doi: 10.1093/bioinformatics/bts113. Epub
2012 Mar 7. Erratum in: Bioinformatics. 2012 Aug 1;28(15):2091. PubMed PMID:
22402613.

22: Thomas PD, Wood V, Mungall CJ, Lewis SE, Blake JA; Gene Ontology Consortium. 
On the Use of Gene Ontology Annotations to Assess Functional Similarity among
Orthologs and Paralogs: A Short Report. PLoS Comput Biol. 2012;8(2):e1002386.
doi: 10.1371/journal.pcbi.1002386. Epub 2012 Feb 16. PubMed PMID: 22359495;
PubMed Central PMCID: PMC3280971.

23: Chen CK, Mungall CJ, Gkoutos GV, Doelken SC, Köhler S, Ruef BJ, Smith C,
Westerfield M, Robinson PN, Lewis SE, Schofield PN, Smedley D. MouseFinder:
Candidate disease genes from mouse phenotype data. Hum Mutat. 2012
May;33(5):858-66. doi: 10.1002/humu.22051. Epub 2012 Mar 16. PubMed PMID:
22331800; PubMed Central PMCID: PMC3327758.

24: Köhler S, Bauer S, Mungall CJ, Carletti G, Smith CL, Schofield P, Gkoutos GV,
Robinson PN. Improving ontologies by automatic reasoning and evaluation of
logical definitions. BMC Bioinformatics. 2011 Oct 27;12:418. doi:
10.1186/1471-2105-12-418. PubMed PMID: 22032770; PubMed Central PMCID:
PMC3224779.

25: Tirmizi SH, Aitken S, Moreira DA, Mungall C, Sequeda J, Shah NH, Miranker DP.
Mapping between the OBO and OWL ontology languages. J Biomed Semantics. 2011 Mar 
7;2 Suppl 1:S3. doi: 10.1186/2041-1480-2-S1-S3. PubMed PMID: 21388572; PubMed
Central PMCID: PMC3105495.

26: Meehan TF, Masci AM, Abdulla A, Cowell LG, Blake JA, Mungall CJ, Diehl AD.
Logical development of the cell ontology. BMC Bioinformatics. 2011 Jan 5;12:6.
doi: 10.1186/1471-2105-12-6. PubMed PMID: 21208450; PubMed Central PMCID:
PMC3024222.

27: modENCODE Consortium, Roy S, Ernst J, Kharchenko PV, Kheradpour P, Negre N,
Eaton ML, Landolin JM, Bristow CA, Ma L, Lin MF, Washietl S, Arshinoff BI, Ay F, 
Meyer PE, Robine N, Washington NL, Di Stefano L, Berezikov E, Brown CD, Candeias 
R, Carlson JW, Carr A, Jungreis I, Marbach D, Sealfon R, Tolstorukov MY, Will S, 
Alekseyenko AA, Artieri C, Booth BW, Brooks AN, Dai Q, Davis CA, Duff MO, Feng X,
Gorchakov AA, Gu T, Henikoff JG, Kapranov P, Li R, MacAlpine HK, Malone J, Minoda
A, Nordman J, Okamura K, Perry M, Powell SK, Riddle NC, Sakai A, Samsonova A,
Sandler JE, Schwartz YB, Sher N, Spokony R, Sturgill D, van Baren M, Wan KH, Yang
L, Yu C, Feingold E, Good P, Guyer M, Lowdon R, Ahmad K, Andrews J, Berger B,
Brenner SE, Brent MR, Cherbas L, Elgin SC, Gingeras TR, Grossman R, Hoskins RA,
Kaufman TC, Kent W, Kuroda MI, Orr-Weaver T, Perrimon N, Pirrotta V, Posakony JW,
Ren B, Russell S, Cherbas P, Graveley BR, Lewis S, Micklem G, Oliver B, Park PJ, 
Celniker SE, Henikoff S, Karpen GH, Lai EC, MacAlpine DM, Stein LD, White KP,
Kellis M. Identification of functional elements and regulatory circuits by
Drosophila modENCODE. Science. 2010 Dec 24;330(6012):1787-97. doi:
10.1126/science.1198374. Epub 2010 Dec 22. PubMed PMID: 21177974; PubMed Central 
PMCID: PMC3192495.

28: Mungall CJ, Bada M, Berardini TZ, Deegan J, Ireland A, Harris MA, Hill DP,
Lomax J. Cross-product extensions of the Gene Ontology. J Biomed Inform. 2011
Feb;44(1):80-6. doi: 10.1016/j.jbi.2010.02.002. Epub 2010 Feb 10. PubMed PMID:
20152934; PubMed Central PMCID: PMC2910209.

29: Diehl AD, Augustine AD, Blake JA, Cowell LG, Gold ES, Gondré-Lewis TA, Masci 
AM, Meehan TF, Morel PA, Nijnik A, Peters B, Pulendran B, Scheuermann RH, Yao QA,
Zand MS, Mungall CJ. Hematopoietic cell types: prototype for a revised cell
ontology. J Biomed Inform. 2011 Feb;44(1):75-9. doi: 10.1016/j.jbi.2010.01.006.
Epub 2010 Feb 1. PubMed PMID: 20123131; PubMed Central PMCID: PMC2892030.

30: Gkoutos GV, Mungall C, Dolken S, Ashburner M, Lewis S, Hancock J, Schofield
P, Kohler S, Robinson PN. Entity/quality-based logical definitions for the human 
skeletal phenome using PATO. Conf Proc IEEE Eng Med Biol Soc. 2009;2009:7069-72. 
doi: 10.1109/IEMBS.2009.5333362. PubMed PMID: 19964203; PubMed Central PMCID:
PMC3398700.

31: Hancock JM, Mallon AM, Beck T, Gkoutos GV, Mungall C, Schofield PN. Mouse,
man, and meaning: bridging the semantics of mouse phenotype and human disease.
Mamm Genome. 2009 Aug;20(8):457-61. doi: 10.1007/s00335-009-9208-3. Epub 2009 Aug
2. PubMed PMID: 19649761; PubMed Central PMCID: PMC2759022.

32: Yandell M, Moore B, Salas F, Mungall C, MacBride A, White C, Reese MG.
Genome-wide analysis of human disease alleles reveals that their locations are
correlated in paralogous proteins. PLoS Comput Biol. 2008 Nov;4(11):e1000218.
doi: 10.1371/journal.pcbi.1000218. Epub 2008 Nov 7. PubMed PMID: 18989397; PubMed
Central PMCID: PMC2565504.
