### ISSUE TITLE
Inconsistency / error in gene/genotype relationships

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1337]
Links from genotype to genes are frequently missing even when reciprocal links exist.

| [Genotype](https://monarchinitiative.org/genotype/MGI:2653759) | [Gene](https://monarchinitiative.org/gene/MGI:3590178) |
| --- | --- |
| <img width="1398" alt="screen shot 2016-08-17 at 5 23 15 pm" src="https://cloud.githubusercontent.com/assets/3658863/17757882/5b80374c-649f-11e6-8b02-d4cfeb22edd7.png"> | <img width="1396" alt="screen shot 2016-08-17 at 5 23 00 pm" src="https://cloud.githubusercontent.com/assets/3658863/17757885/5d432256-649f-11e6-8a26-543d9aec2028.png"> |

Some gene tabs on genotype pages (eg. [dbSNPIndividual:14829](https://monarchinitiative.org/genotype/dbSNPIndividual:14829)) show up with an n=1 but an error message.

<img width="1364" alt="screen shot 2016-08-17 at 5 03 48 pm" src="https://cloud.githubusercontent.com/assets/3658863/17757789/a4e851b8-649e-11e6-8660-f4171ce729c1.png">

**Comment by kshefchek** [comment]
I've fixed the second half of the ticket, see https://beta.monarchinitiative.org/genotype/dbSNPIndividual:14829
