### ISSUE TITLE
Add model comparison view to analyze/phenotypes

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#134]
We'd like to have the model comparison grid displayed when the analyze/phenotypes link is selected.  With commit https://github.com/monarch-initiative/monarch-app/commit/0c76f2c2af9fde0f57bb8bdf63edc475964117d3, I have checked in a basic demonstration of the functionality, but it's just tacked on to the end of the result page. 

Would it be possible to get this laid out and themed so that it would be easier to find? I'm thinking that a tabbed version similar to the other pages would be easiest.

**Comment by cmungall** [comment]
I made a start on this
- note that the grid view appears hardcoded for mouse. Try target=ZFIN to see. @cborromeo how do we fix this?
- Need @sarahjkim to look at my html and perhaps fix the CSS.

Try the following URL - this is a typical URL constructed from hitting the search button:

```
/analyze/phenotypes/?target=ZFIN&input_items=MP%3A0000788%0D%0AMP%3A0000822%0D%0AMP%3A0000914%0D%0AMP%3A0000929%0D%0AMP%3A0000930%0D%0AMP%3A0001286%0D%0AMP%3A0001393%0D%0AMP%3A0001688%0D%0AMP%3A0001698%0D%0AMP%3A0001732%0D%0AMP%3A0001787%0D%0AMP%3A0002064%0D%0AMP%3A0002083%0D%0AMP%3A0002151%0D%0AMP%3A0002950%0D%0AMP%3A0003012%0D%0AMP%3A0003424%0D%0AMP%3A0003651%0D%0AMP%3A0004948%0D%0AMP%3A0005657&limit=100
```

This lands us in the query tab. Ideally we would land someone in grid or table view.

**Comment by cmungall** [comment]
Note it's a bit hard to test the whole workflow here as vocabulary services appear to be non-responsive

**Comment by harryhoch** [comment]
Thanks, Chris. @cborromeo, note that we should indicate the data sources for both the left and right sides of the viewer.

@cmungall, I see the grid. Is the content wrong, or is there some other problem?

**Comment by harryhoch** [comment]
Ok. I see the problem. modeltype.js is hard-coded to pass target_species=10090  to simsearch. 

@cmungall, is there a good way to get the taxon id from the targets "ZFIN", etc  in Analyze.mustache? Or should we just hard-code the IDs into webapp.js as needed?

**Comment by nlwashington** [comment]
can you add a radio button/selection to pick the target species, and then feed that into the analyze?  perhaps default to mouse?

target_species=
7955 for fish
9606 for human
10090 for mouse

**Comment by cmungall** [comment]
@harryhoch - you should pass in species. I will change the form such that the parameters are species, not the artificial "target". The translation to "target" in the final call to owlsim services will be handled deeper in api.js, so the client does not need to worry about it.

**Comment by cmungall** [comment]
OK, the webform now uses "species" as a parameter. Somehow this needs to be passed to _loadData in modeltype.js, rather than the hardcoded 10090. @cborromeo or @harryhoch ...

**Comment by harryhoch** [comment]
I can look at this tomorrow....

On Feb 15, 2014, at 6:43 PM, "Chris Mungall" <notifications@github.com<mailto:notifications@github.com>> wrote:

OK, the webform now uses "species" as a parameter. Somehow this needs to be passed to _loadData in modeltype.js, rather than the hardcoded 10090. @cborromeohttps://github.com/cborromeo or @harryhochhttps://github.com/harryhoch ...

**Comment by harryhoch** [comment]
Made changes so model grid should handle ZFIN, etc appropriately - https://github.com/monarch-initiative/monarch-app/commit/5e77c9f50c97064aa1a0e71d59bcd17ab53a4bf1. 

@cmungall, please verify that the results look right to you.

This worked much better once I fixed consistency issues that had zebrafish at 7995 in some spots.

**Comment by cmungall** [comment]
Thx for fixing the IDs.

Not quite following the logic. The grid js takes "target_species" as an argument. This is passed via a hidden param. The actual form param is "species"....

Also we seem to have lost the tabbing but I don't think that was this commit

**Comment by harryhoch** [comment]
Right. we can probably just use “species”…

On 17 Feb 2014, at 1:07 PM, Chris Mungall notifications@github.com wrote:

> Thx for fixing the IDs.
> 
> Not quite following the logic. The grid js takes "target_species" as an argument. This is passed via a hidden param. The actual form param is "species"....
> 
> Also we seem to have lost the tabbing but I don't think that was this commit
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by harryhoch** [comment]
Ok, Chris. could use some guidance on the right mustache way to do this. The problem is that this is a two-phase page. during the first phase, you input species and target terms. The, you hit search, and the page reloads.  We currently squirrel away the input phenotype terms in the hidden field. I was doing the same thing with the species.

It might be possible to just use the existing select for the species, but I'm not sure I know the best way to use mustache to set that value. any suggestions?

**Comment by cmungall** [comment]
OK, I will take a crack at it

**Comment by harryhoch** [comment]
thanks

**Comment by cmungall** [comment]
actually, I'm not really sure how modeltype is being initialized. Presumably analyze.mustache needs to pass some parameters somewhere?

**Comment by harryhoch** [comment]
See the document ready call in Analyze.js

**Comment by cmungall** [comment]
OK, all that remains now is to get a decent tab view working. @sarahjkim we can take a look at this tomorrow

(or if anyone else wants to take a shot - it's pretty hard to test the rest of the interface until the ID bug is fixed...)

**Comment by harryhoch** [comment]
thanks
