### ISSUE TITLE
gene symbol doesn't show up for the reactome row

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1341]
[Here](https://beta.monarchinitiative.org/gene/NCBIGene%3A4609:pathways) the gene symbol doesn't show up for the reactome row.
<img width="1389" alt="screen shot 2016-08-22 at 11 34 38 am" src="https://cloud.githubusercontent.com/assets/3658863/17866749/951cfb14-685c-11e6-98f4-94ee4c5488ad.png">

**Comment by kshefchek** [comment]
Ticket opened in dipper, see https://github.com/monarch-initiative/dipper/issues/364

Oddly enough it is displaying correctly on production, see https://monarchinitiative.org/gene/NCBIGene%3A4609

**Comment by jmcmurry** [comment]
indeed odd; what do you think the underlying issue is?
