### ISSUE TITLE
Ensure HTML validates

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#135]
Make sure all HTML tags are closed, and indentation is correct.

HTML should validate using external validator; e.g.

http://html5.validator.nu/?doc=http%3A%2F%2Ftartini.crbs.ucsd.edu%2Fphenotype%2FMP_0000854

**Comment by cmungall** [comment]
I've done this for disease, needs done for other pages.

Not super-high priority but good practice and makes editing and reuse easier

**Comment by harryhoch** [comment]
Which violations should we consider important Are the </link> warnings not worth worrying about?
