### ISSUE TITLE
Beta vs prod data is massively different

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1351]
I know that there were some issues with Marfan modeling that were recently cleaned up. Is this difference legit? Even the title is different... @pnrobinson, @cmungall 
### [Beta](https://beta.monarchinitiative.org/disease/OMIM:154700)

<img width="885" alt="screen shot 2016-09-02 at 3 48 50 pm" src="https://cloud.githubusercontent.com/assets/3658863/18220234/c9ffd63c-7124-11e6-9951-06e2f31d33c4.png">
### [Prod](https://monarchinitiative.org/disease/OMIM:154700)

<img width="921" alt="screen shot 2016-09-02 at 3 48 40 pm" src="https://cloud.githubusercontent.com/assets/3658863/18220235/ca2fdbac-7124-11e6-981e-f644abb607d5.png">

**Comment by pnrobinson** [comment]
Much better. But...
1) The cow model of Marfan is well known and should be there. There are also a bunch of different mouse models that are missing.
2) LTBP2 is related to the "Marfan gene" FBN1 but does not cause Marfan (see: http://omim.org/entry/602091?search=ltbp2&highlight=ltbp2  -- the diseases are phenotypically similar but not the same thing)

**Comment by jmcmurry** [comment]
How is this much better? This entry on Prod has no phenotypes?

**Comment by pnrobinson** [comment]
I mean that 14 genes is a massive error. Some of the genes are not related at all...

**Comment by jmcmurry** [comment]
I think you're confusing beta and production? Beta seems broken for all kinds of reasons to me:
1) 15 genes
2) no phenotypes, no models, no variants, etc

That's to say it seems to have gotten worse instead of better.

**Comment by cmungall** [comment]
The label issue is red herring (we expect labels to change). In fact Marfan is a red herring.

There are **no** phenotypes loaded on Beta. I don't know if this is intentional, e.g due to known downtime/reload, @jnguyenx or @kshefchek may have the answer, is it to do with beta being temporarily repurposed for udp demos?

We have behave tests - if this was unintentional it should be caught.

**Comment by kshefchek** [comment]
@cmungall correct we are reloading and did not change the beta configuration.
