### ISSUE TITLE
model grid enhancements

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#136]
1. grid should do something useful when no matches are found.
2. each side of the grid should list the source of the phenotypes listed.

**Comment by harryhoch** [comment]
Other issues:

-Needs more context to aid interpretation
- Looks a bit strange if all items have the same score,or if it just one row
- Not clear that each column in the model view is a model, particularly given that the columns are sometimes really just gene names. 
- Not clear that the model view columns are ordered by score.

We need to tell users where they can go from the model view, particularly with links from models.

 Highlighting a cell in the model view might lead to a message indicating presence in diseases/models, etc.
- the dynamic mouse over on the model view makes it hard to access links that sometimes arise in the detail view. If you happen to mouse over something else on the path to get to the link, the detail view will change and you won’t be able to select the link

**Comment by frdougal** [comment]
I'll try to separate some of these issues.  
(paraphrasing from above)
- SubIssue1: if the data just contains one row it looks strange.  
  Response: I don't know what else to do if there is one row.  Do I just list the matching models in a table?
  -SubIssue2:Not clear that each column in the model view is a model, particularly given that the columns are sometimes really just gene names.
  Response: This is mostly a data issue.  I can only display what is returned by the comparison call.  Sometimes it is genes sometimes it is a model genotype.  The data returned by the comparison doesn't provide any insight into what category is being returned.
  -SubIssue3: We need to tell users where they can go from the model view, particularly with links from models
  Response: I can make a URL based off the MGI ID returned and use that to link to the /genotype/MGI_12334 web page.  But I don't think we get a large amount of data from the model.

**Comment by frdougal** [comment]
Issue: "grid should do something useful when no matches are found."
I think the system now greys out the "Similar Models" tab if nothing is found.  Here is an example:
/disease/OMIM_163950

In the output I see a line like: "#Sim Diseases:0"  I think this is determining whether to enable the Similar Models tab.

**Comment by harryhoch** [comment]
fine. 

On March 14, 2014 at 8:20:54 PM, cborromeo (notifications@github.com) wrote:

> Issue: "grid should do something useful when no matches are found."
> I think the system now greys out the "Similar Models" tab if nothing is found. Here is an  
> example:
> /disease/OMIM_163950
> 
> In the output I see a line like: "#Sim Diseases:0" I think this is determining whether  
> to enable the Similar Models tab.
> 
> —
> Reply to this email directly or view it on GitHub.  

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics  
harryh@pitt.edu 412 648 9300
