### ISSUE TITLE
Fix behave testing framework

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1382]
@kltm, @jnguyenx says that the behave tests are broken (not failing legitimately, but broken). Can you clarify what needs to be done to fix them?

**Comment by kltm** [comment]
There are many problems :
- Firefox versions are in between stable testing frameworks (marionette vs. wire vs. legacy), which sometimes require their own version-specific executables to run (until they eventually find their way in permanently)
  - PhantomJS also has some painful quirks (sizing, etc.)
    - although, its most serious problem being that it's not a real web browser
  - As does Chrome(ium)
  - The goal here is to be able to roll out testing in a very standard way (dpkg, etc.) on very standard hosts/dev environments (Ubuntu LTS) with a minimum of external packages (brittle and security risk)
- shifting python selenium/webdriver versions seem to be pretty hit and miss right now
- travis ci is hopelessly out-of-date and sticking to their guns

This whole stew is quite unpleasant. For AmiGO, we have various luck depending on the platform, but it works for the periodic checking of our production site and local dev just fine. We have mostly worked around there problems by having additional environment probing in environment.py for behave.

**Comment by kltm** [comment]
From the call this morning, it would probably be best to just dump everything that doesn't work with FF for the time being and just use phantom--there are too many new items and data checks that need to be worked on for blockers here.

(As well, behave can use other http clients besides the browsers.)

FF (or Chrome or whatever) functionality should be re-added in the future to--you can't beat the full quirky testing of a real browser.

**Comment by jmcmurry** [comment]
cc: @DoctorBud

**Comment by kshefchek** [comment]
Switched to phantomJS with https://github.com/monarch-initiative/monarch-app/pull/1389, tests fixed
