### ISSUE TITLE
Upgrade golr-manager to support new searchable field triplets

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-legacy#1387]
At the moment the schema.xml is ahead of the golr-manager, I'm making hacks to wire things together, which will be removed when the golr-manager supports the new triplets searchable fields.

**Comment by jnguyenx** [comment]
golr-manager ticket: https://github.com/berkeleybop/bbop-manager-golr/issues/4

golr-schema PR: https://github.com/berkeleybop/golr-schema/pull/3

**Comment by kshefchek** [comment]
This bit of code has been replaced by biolink where we are using pysolr as a manager/API layer.
