### ISSUE TITLE
Fix mygene.info flags to query the appropriate database

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#139]
Currently fetchGeneInfoFromMyGene in api.js does not generate any output.  Typically this is caused by querying a gene ID in the wrong format.  I need to add some functionality to identify the database of the input gene and add the appropriate flag in the MyGene api call.
For example for OMIM:601622
This is the API call:
http://mygene.info/v2/query?q=OMIM:601622&species=human,mouse,rat,zebrafish,fruitfly,worm
returns: {}

This is what we need:
http://mygene.info/v2/query?q=mim:601622&species=human,mouse,rat,zebrafish,fruitfly,worm

returns: {"hits": [{"entrezgene": 7291, "name": "twist family bHLH transcription factor 1", "_score": 18.106695, "symbol": "TWIST1", "_id": "7291", "taxid": 9606}], "total": 1, "max_score": 18.106695, "took": 27}

List of flags documented here:
http://mygene.info/doc/query_service.html

**Comment by mellybelly** [comment]
@nlwashington @kshefchek what is the status? please close, fix, or move to May milestone.

**Comment by kshefchek** [comment]
This function is configured for NCBI, MGI, and OMIM IDs, please reopen if I should add any additional functionality.
