### ISSUE TITLE
Selecting target group on analyze page does not return phenogrid

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1391]
If I go to https://monarchinitiative.org/analyze/phenotypes

And type: Microalbuminuria 
and Select Target: Mus Musculus (genes)

Phenogrid fails to load, but the table confirms there are mouse hits.

**Comment by kshefchek** [comment]
I can take a pass unless there is something obvious @yuanzhou ?

**Comment by pnrobinson** [comment]
The search also returns items like

Homo sapienshttp://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=9606Karyomegalic interstitial nephritishttps://monarchinitiative.org/disease/OMIM:614817

which is not a mouse gene.

-P

Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.orgmailto:peter.robinson@jax.org

www.jax.org

The Jackson Laboratory: Leading the search for tomorrow's cures

**Comment by yuanzhou** [comment]
@kshefchek I reproduced this error and saw the error message in debugger:

![capture](https://cloud.githubusercontent.com/assets/195873/20141273/92d23088-a65d-11e6-880d-9907e204d3d5.PNG)

Please just go ahead and do whatever you think can fix this.
