### ISSUE TITLE
Investigate lost gene-variant mappings on disease pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1398]
Our unit tests are failing due to losing variant to gene mappings:
https://travis-ci.org/monarch-initiative/monarch-app/builds/180568340#L2241

See: https://beta.monarchinitiative.org/disease/OMIM:182212#variants
vs
https://monarchinitiative.org/disease/OMIM:182212#variants

**Comment by TomConlin** [comment]
nothing obvious reported changed at ClinVar reading through the last several months of release notes 

ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/release_notes/ 

they do mention changing rules for intergenic/intronic snps to be referenced via  sequences that actually include the region of sequence the snp is in. (which rules out sequences only representing a genes exons)

**Comment by TomConlin** [comment]
Looking for references to  'NCBIGene:6497' (in various forms) in the current ClinVar data release is coming up empty.

that is the SKI gene from the example

**Comment by kshefchek** [comment]
They must have undocumented adjustments, if you look at:
/ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet[@ID='10391']

The gene id is under
MeasureRelationship[@Type="within single gene"]

whereas before we were looking in:
'MeasureRelationship[@Type="variant in gene"]')

I also noticed we are mistyping multi loci variations as SNVs.  It's probably worth revisiting the data and modelling in the new year.

For example:
https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/ClinVarVariant:156118?project=%2A
https://www.ncbi.nlm.nih.gov/clinvar/variation/156118/

UPDATE: this better shows the type mapping:
https://scigraph-data-dev.monarchinitiative.org/scigraph/cypher/execute?cypherQuery=START+n+%3D+node%3Anode_auto_index%28iri%3D%27ClinVarVariant%3A156118%27%29+match+%28n%29-%5B%3Atype%5D-%28x%29+return+x&limit=10

**Comment by TomConlin** [comment]
the repertoire of MeasureRelationship Types is currently:

     540074 genes overlapped by variant
     176970 within single gene
      24746 within multiple genes by overlap
       5698 asserted, but not computed
        439 near gene, upstream
        374 variant in gene
         54 near gene, downstream

with `variant in gene`  our original exclusive filter,  clearly loosing favor 

@mbrush you are going to want to update the cmap
when you modeled this a year ago it consisted solely of  

    678988 variant in gene

**Comment by mbrush** [comment]
Proposal for relation to use for linking the variant (e.g. ClinVarVariant:17681) to affected genes (e.g. NCBIGene:672) - given the following <MeasureRelationship> values:
 
- **'within single gene'**  -> GENO:0000418 #  has_affected_locus (guessing here there will always be only one affected gene)
- **'genes overlapped by variant'**  -> GENO:0000418 #  has_affected_locus  (guessing here there will be cases where there are more than one affected gene)
- **'within multiple genes by overlap'**  -> GENO:0000418 #  has_affected_locus (guessing here there will be cases where there are more than one affected gene)
- **'variant in gene'**  -> GENO:0000418 #  has_affected_locus
- **'near gene, upstream'** ->  RO:0002528 # 'is upstream of sequence of'
- **'near gene, downstream'** -> RO:0002529 # 'is downstream of sequence of'
- **'asserted, but not computed'** -> ??? (no idea what this means)

I updated the clinvar cmap to include an annotation on the has_afffected_locus property that specifies the mappings. And I emailed ClinVar to ask about the 'asserted, but not computed' relation.

**Comment by mbrush** [comment]
@kshefchek  re: mis-typing of variants.  Below is a count of variant types from the ClinVar advanced search interface. The vast majority are 'simple' SNVs, but we should explore how to identify those that are not and type them accordingly. 

![image](https://cloud.githubusercontent.com/assets/5184212/22720505/1cf61812-ed60-11e6-8b1d-9a93a1c887b7.png)

**Comment by TomConlin** [comment]
xmlstarlet sel -t -v './ReleaseSet/ClinVarSet/ReferenceClinVarAssertion/MeasureSet/Measure/@Type' ClinVarFullRelease_00-latest.xml.gz  | sort | uniq -c | sort -nr
     306280 single nucleotide variant
      27984 Deletion
      10886 Duplication
       7819 copy number gain
       7142 copy number loss
       2744 Insertion
       2152 Indel
       584 Variation
       252 Translocation
       240 Microsatellite
        96 protein only
        38 Complex
        31 Inversion
         8 fusion
@mbrush

**Comment by TomConlin** [comment]
moved to
https://github.com/monarch-initiative/dipper/issues/420
