### ISSUE TITLE
Fetch all models annotated with an MP term

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#14]
Need API call that can fetch all models annotated with a given MP term.  (This, or something like it, may already be implemented.)  

I think first iteration we will probably have to hardcode this to a set of views.  At first nif_0000_21427_10 for mouse and nlx_151835-1 for human disease, but eventually we will need this to be a bit more loosey and do a generic federation query and filter the results on "genotype" concepts.

**Comment by cmungall** [comment]
pheno = fetchPhenotypeInfo(id)
pheno.disease_associations
pheno.phenotype_associations

You can get example json by using a url like

/phenotype/:id/disease_associations.json
/phenotype/:id/genotype_associations.json

**Comment by nlwashington** [comment]
So, in addition to what chris mentioned above, you can also query with a list of phenotypes, like:

http://localhost:8080/simsearch/phenotype/?input_items=MP:0000788,MP:0000802&target_species=10090&limit=25

where the target_species can presently be:
10090 - mouse genes (phenotypes aggregated at the level of a gene, not a genotype)
9606 - human diseases (OMIM only)

you can also add a limit (or cutoff, i've allowed either parameter) for the topX.

**Comment by mellybelly** [comment]
I think this can be closed?
@cmungall
