### ISSUE TITLE
add monarch mendelay group to our citations page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#141]
We should start a public mendelay group that people can join to see our publications. There is also a plugin where this can be pushed into a public website.

**Comment by kltm** [comment]
Just food for thought, but I would also point out the very easy to use and completely open Zotero ( http://zotero.org )--one of the major competitors to Mendelay.

**Comment by cmungall** [comment]
agreed we should consider zotero
