### ISSUE TITLE
Add clinvar image source

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#142]
Please add the ClinVar icon for an image source:

http://www.clinvar.com/

**Comment by pnrobinson** [comment]
By the way, when did Clinvar get a "dot-com" suffix? Will this data be remaining free?

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Nicole Washington [notifications@github.com]
Gesendet: Montag, 24. Februar 2014 23:17
An: monarch-initiative/monarch-app
Betreff: [monarch-app] Add clinvar image source (#142)

Please add the ClinVar icon for an image source:

http://www.clinvar.com/
