### ISSUE TITLE
The glossary page is useless

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1428]
It must die

**Comment by jmcmurry** [comment]
I didn't realize this page was even here. I agree that these terms are not of particular relevance to our users, however, perhaps there are some terms that would be? Eg. even "phenotype" as this is slippery.

**Comment by cmungall** [comment]
Note that it's gone in my PR.

I'm not sure it's worth trying to keep a glossary up to date. But we should try and have ubiquitous context sensitive help throughout the site though.
