### ISSUE TITLE
User request 1 - haploinsufficient lethal loci list

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/monarch-legacy#1432]
Request ID# | Completed? | Date | User initiating request (deidentified) | Description | Who is assigned | Link to more info
--- | --- | --- | --- | --- | --- | ---
1 | Y | Jan 2017 | basic science @ OHSU | requested a list of haploinsufficient lethal loci, specifically from mice and/or humans | Kent | https://www.dropbox.com/sh/y8ou3i2rx97djuv/AAC1Ec-K1-QCPxufTnkrVIV5a?dl=0 Link requires a password - ask Lilly for it

**Comment by pnrobinson** [comment]
This is a good place to start to explore haploinsufficiency scores. I do not know if there has been an update.
http://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1001154
