### ISSUE TITLE
User Request #6 - download g2p association data

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/monarch-legacy#1440]
Request ID# | Completed? | Date | User initiating request (deidentified) | Description | Who is assigned | Link to more info
--- | --- | --- | --- | --- | --- | ---
6 | Y | Feb 2017 |  Genomics scientist | Is the monarch genotype-phenotype association data available as a download or by request? | Kent/Jeremy | https://www.dropbox.com/sh/uwe814c4vmcm0xs/AACvwQ9cyNXEvzCzoOn4nVR4a?dl=0 Link requires a password - ask Lilly for it

**Comment by lwinfree** [comment]
@kshefchek @jnguyenx Can one of you answer this? The original email is in the dropbox link, or you can send me your answer & I can email the user that requested it.
Thanks!

**Comment by cmungall** [comment]
Per genotype: https://api.monarchinitiative.org/api/#!/bioentity/get_genotype_phenotype_associations

in bulk, we only have gene-phenotype in public
https://api.monarchinitiative.org/api/#!/mart/get_mart_gene_associations_resource

@jnguyenx or @kshefchek could probably add a route for genotype-phenotype in a few minutes. However, we'd want to spend some time testing this, since these are potentially much larger

**Comment by cmungall** [comment]
https://github.com/biolink/biolink-api/issues/44

**Comment by cmungall** [comment]
The other option is to download the ttl but this is difficult to use for most people

**Comment by jmcmurry** [comment]
are you doing away with support for the solr endpoint?
eg. 

https://solr.monarchinitiative.org/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=csv&rows=100000&start=0&fl=subject,subject_label,subject_taxon,subject_taxon_label,object,object_label,relation,relation_label,evidence,evidence_label,source,is_defined_by,qualifier&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&facet.method=enum&csv.encapsulator=%22&csv.separator=%09&csv.header=true&csv.mv.separator=%7C&fq=object_category:%22phenotype%22&fq=subject_closure:%22dbSNPIndividual:19638%22&facet.field=subject_taxon_label&q=*:*

**Comment by cmungall** [comment]
we don't want to give out URLs like that. biolink currently wraps solr calls. but we can change things under the hood. E.g we iterate over chunks

**Comment by cmungall** [comment]
and we can also cache common calls

**Comment by lwinfree** [comment]
emailed a response to the user.
