### ISSUE TITLE
User Request #7 - phenotype annotation sufficiency score

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/monarch-legacy#1441]
Request ID# | Completed? | Date | User initiating request (deidentified) | Description | Who is assigned | Link to more info
--- | --- | --- | --- | --- | --- | ---
7 | Y | Feb 2017 |  Genomics scientist | Hello, is the Monarch phenotype annotation sufficiency score documented anywhere?  All I could find was http://phenoday2014.bio-lark.org/pdf/6.pdf but the link is dead. | Julie | https://www.dropbox.com/sh/7xmozdwtok5zk4l/AABpQ62u86iLEggj5J4hbkpya?dl=0 Link requires a password - ask Lilly for it

**Comment by lwinfree** [comment]
@jmcmurry Do you know where/if the annotation sufficiency score is documented?

**Comment by jmcmurry** [comment]
I wish I knew! One place to start is: http://monarch-initiative.blogspot.com/2015/01/how-to-annotate-patients-phenotypic.html. @kshefchek do you know?

**Comment by kshefchek** [comment]
I must have a copy somewhere, where would be the appropriate place to host the file?

**Comment by lwinfree** [comment]
What about linking it here for the immediate future?

**Comment by kshefchek** [comment]
I went through my harddrive and old emails and can't find a hard copy or attachment, looks like I always referred to the url as well. @mellybelly or @nlwashington should have a copy.

**Comment by mellybelly** [comment]
It used to be here: http://phenoday2014.bio-lark.org/pdf/6.pdf
I think @jmcmurry put it on zenodo for persistence?

**Comment by mellybelly** [comment]
I uploaded to doc the parent directory, please put somewhere more appropriate
https://github.com/monarch-initiative/monarch-app
PhenoDay_SufficiencyScore_camera_ready_final.pdf

**Comment by pnrobinson** [comment]
?What about having a page with all Monarch publications that either have our own copy of articles like this and anything open access or links to PubMed/PMC etc? That would be nice for users who want to get to know about us. We could structure it by topics etc.

-Peter


Peter Robinson

Professor of Computational Biology

The Jackson Laboratory for Genomic Medicine

10 Discovery Drive

Farmington, CT 06032

860.837.2095 t | 860.990.3130 m

peter.robinson@jax.org<mailto:peter.robinson@jax.org>

www.jax.org

Robinson lab: https://robinsongroup.github.io/

The Jackson Laboratory: Leading the search for tomorrow's cures

________________________________

**Comment by lwinfree** [comment]
Phenotype annotation sufficiency score is here: https://doi.org/10.5281/zenodo.834091
