### ISSUE TITLE
Add test URLs for modeltype.js to urltest_cfg.js

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#145]
Chuck, can you add a test URL for the service you call to https://github.com/monarch-initiative/monarch-app/blob/master/tests/urltest_cfg.js

**Comment by harryhoch** [comment]
@cmungall, took a stab at addressing this through https://github.com/monarch-initiative/monarch-app/commit/1942ddf110432988d54c31ab3264c485d7a4414a

Currently, phenogrid gets loaded when we call a url like /disease/DOID_14330, and then calls a /simsearch URL. 

We currently have tests for both. 

I added something to the /disease/DOID_14330 call, adding a clause to look for a label created by phenogrid. 

Does this make sense? 

I don't have the jenkins url, so I can't verify.
