### ISSUE TITLE
Put Monarch on NCBI Linkouts

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1450]
see https://www.ncbi.nlm.nih.gov/projects/linkout/

@jmcmurry

**Comment by jmcmurry** [comment]
https://github.com/monarch-initiative/impact/issues/57

**Comment by lwinfree** [comment]
@jmcmurry I will email them. They ask "please describe the type of NCBI database records to which you would like to apply links" Do you have input for this question?

**Comment by lwinfree** [comment]
I have been in communication with NCBI Linkout & they are reviewing our request now. I will update this as I hear back from them!

**Comment by lwinfree** [comment]
We've been approved!  🎉  Now working on next steps. From email:

The Monarch Initiative db was approved for inclusion in Gene.
To participate in LinkOut, we would need LinkOut files from you.  Please see the information at the below URL, especially the section on "File Preparation" for details on how to create the Identity and Resource files- both files are needed:
 
http://www.ncbi.nlm.nih.gov/projects/linkout/doc/nonbiblinkout.html
 
When you are ready, please send a small sample of these two files to linkout@ncbi.nlm.nih.gov. We will review the files and will provide you with feedback.
 
If you decide to use LinkOut XML for your files, please validate them at the below URL before sending them:
 
http://www.ncbi.nlm.nih.gov/projects/linkout/doc/validate.shtml

**Comment by jmcmurry** [comment]
Woot!

**Comment by pnrobinson** [comment]
WTG!

**Comment by TomConlin** [comment]
So to start we need to get them a properly formated `resource.xml` with all the `NCBIGene:nnn`  we have  (just returning the `nnn` part)

have a list of  [941k NCBIGene IDs](https://data.monarchinitiative.org/pub/distinct_ncbigeneid.list)  (7.8M ) from the upcoming release

NCBI has size limitations on the files they accept which means we will most likely want to avoid `.xml` and will probably have to split up  the  `.cvs` given the constants they require

**Comment by lwinfree** [comment]
@jmcmurry do you have an opinion on this? We need to come up with an abbreviated name for Monarch, although NCBI has final say: "NameAbbr (required): A short one word name for the resource provider or library. NameAbbr may only include alpha and numeric characters; spaces and special characters such as hyphens are not allowed. Because this element must be unique, NCBI reserves the right to adjust it as necessary."

**Comment by TomConlin** [comment]
change our name to MONI:?

**Comment by lwinfree** [comment]
I'm starting a [google spreadsheet](https://docs.google.com/spreadsheets/d/1Hz1u3BPBboCGTgMx4SkWO9gS-ky2m0Cij8PFN5HufA0/edit?usp=sharing) for the resource.csv file. 
Also, the email asks for a small sample, so I think we could probably give them a short list of genes initially and finish the entire list while we wait for feedback from them.

**Comment by TomConlin** [comment]
@lwinfree  
please consider not doing that.
gdoc is a word processor not a text editor 
writing program artifacts in a word processor is always bad. 
It ultimately needs to be generated  
I would suggest:  start a file generator and put it in GH

**Comment by lwinfree** [comment]
@TomConlin can you help with the file generator? thx for the feedback - I'm gonna use a spreadsheet as a mock-up to help me keep track of what we need to do & then actually submit the csv produced from the program like you suggest :)

**Comment by TomConlin** [comment]
+1

**Comment by jmcmurry** [comment]
I think "monarch" is the best prefix. Is there a char limit?

**Comment by lwinfree** [comment]
hey @TomConlin here is the list of taxon id [taxon_id_NCBI_linkout.txt](https://github.com/monarch-initiative/monarch-app/files/1069844/taxon_id_NCBI_linkout.txt)
😃

**Comment by TomConlin** [comment]
Hi @lwinfree  

So sorry, have to be careful about the rocks we turn over. 
the good news is we have more than a score of species
but we may want to check on what some of them are.
I bet some will be species/strain etc but others may not be real.
 
Below; the first number is how many I see   
(don't get too excited by the counts as taxons also showed up in bnode identifiers)  
the second number is the NCBITaxon ID

 
```
cut -f3 -d' ' ntriples/*.nt | grep "NCBITaxon" | sed 's|.*NCBITaxon\([1-9_]*\).*|\1|g' | tr -d '_' | sort | uniq -c | sort -nr

 711152 7227
 546206 1
 245654 96
 203657 7955
 170246 9913
 150755 6239
  82878 9823
  62837 9
  60906 8364
  57577 9598
  57113 13616
  53624 9544
  50721 37
  49945 9615
  48119 9796
  42614 9258
  39893 28377
  36360 9685
  35928 46245
  35887 7234
  35387 7238
  34774 7
  33193 7245
  32735 726
  32317 724
  32090 7217
  31168 7222
  30237 7244
  30081 723
  29433 722
  23334 31
  14961 7668
  13269 737
  13032 4
  12723 6669
  12140 28584
  11952 7425
  11131 7176
  10670 3
  10473 7159
   9952 7375
   9857 132113
   9385 39758
   9297 7394
   9256 136
   9146 77166
   8997 32264
   8971 6945
   8937 13
   8873 83485
   8855 79782
   8835 126957
   8810 7165
   8645 13249
   8486 4932
   8303 746
   8197 143995
   8078 7463
   8010 3474
   7860 4896
   7859 43151
   7738 121225
   7245 7719
   6023 44689
   2062 994
   1082 562
    546 8
    535 7224
    505 7229
    468 7241
    428 7226
    340 29
    303 9825
    275 7264
    218 9986
    218 9925
    188 94
    178 7243
    170 85
    169 951
    166 97
    160 39442
    156 7246
    153 6
    152 7257
    150 57486
    147 7221
    145 93934
    135 42
    133 9545
    126 89462
    121 5
    120 7263
    119 9793
    118 91
    113 7233
    110 9541
    109 9669
    108 47316
    105 9838
    105 8932
    105 32536
    103 725
    103 2
    102 9691
    101 9593
    101 9483
    100 9555
     99 9978
     99 9597
     98 9994
     98 79684
     98 72
     98 61622
     98 43179
     98 42254
     98 38626
     98 379532
     98 23
     98 127582
     97 9733
     97 9646
     97 9531
     97 9371
     97 51337
     97 37293
     97 336983
     97 2913
     97 27679
     97 1737458
     96 9915
     96 9785
     96 9568
     96 9365
     96 89399
     96 61853
     96 419612
     96 34839
     96 1329
     96 123
     96 118797
     95 9974
     95 9837
     95 9798
     95 9361
     95 74533
     95 73337
     95 61621
     95 246437
     95 2254
     94 8479
     93 88558
     93 52644
     93 216574
     93 1988
     93 18699
     92 988
     92 93
     92 8496
     92 43346
     92 38654
     91 59538
     91 181119
     90 9478
     90 9172
     90 345164
     90 321398
     90 1433
     89 8954
     89 55661
     89 185453
     89 176946
     88 482537
     88 28737
     87 9739
     87 9157
     87 13735
     87 13146
     87 12839
     86 9135
     86 8839
     86 8469
     86 7918
     86 59894
     86 59729
     86 48883
     86 146911
     86 137
     85 9244
     85 9233
     85 7897
     85 59463
     85 51338
     85 381198
     84 9755
     84 188379
     84 1291
     84 1182
     83 94835
     83 441894
     82 8897
     82 6496
     81 328815
     80 932674
     80 9238
     80 144197
     80 125878
     79 9713
     79 44394
     78 57
     77 32644
     76 94827
     76 7868
     75 244447
     74 47314
     74 35
     73 7216
     68 7268
     68 7231
     68 57412
     68 47315
     68 279965
     68 175836
     68 111875
     67 8255
     67 176
     67 12153
     66 7994
     66 795
     66 57397
     66 54374
     65 7998
     65 487
     65 48699
     65 42514
     65 363
     65 187382
     65 15
     65 11354
     64 8969
     64 8153
     64 57421
     64 5267
     64 437
     63 7266
     63 5438
     63 48698
     63 28743
     63 24
     62 92
     62 8128
     62 73
     62 188344
     61 56313
     61 54383
     59 8187
     59 7218
     57 95455
     57 56723
     56 46793
     56 215358
     55 7274
     55 125945
     54 82
     53 3263
     51 7225
     51 157
     50 7282
     50 41375
     49 468
     47 7249
     47 47313
     46 8625
     46 186283
     44 2715
     43 7283
     43 46244
     43 32382
     41 51159
     40 477815
     40 47
     40 25992
     39 7291
     38 73917
     36 67534
     35 134
     34 727
     34 112146
     32 7271
     30 8355
     30 75366
     30 452646
     29 133981
     28 7297
     28 1266728
     27 94111
     27 76712
     27 7455
     27 7262
     27 7247
     26 7273
     26 46829
     26 35531
     25 7239
     25 69217
     25 67532
     24 7293
     24 7284
     24 7279
     24 193351
     23 7255
     23 7228
     23 67533
     23 157293
     23 133982
     22 46794
     22 137354
     22 133978
     22 132243
     21 95624
     21 88883
     21 73156
     21 7261
     21 141217
     20 7252
     20 583
     19 89887
     19 73155
     19 169138
     18 61426
     18 55946
     18 348
     18 271
     18 214822
     18 195
     18 17
     18 15413
     17 7248
     17 271511
     16 9844
     16 934
     16 7235
     16 54
     16 46895
     16 46827
     16 46791
     16 3884
     16 161732
     16 16
     16 133974
     16 116
     15 89888
     15 7962
     15 65963
     15 4679
     15 34677
     15 133991
     14 88884
     14 73157
     14 7232
     14 5791
     14 46893
     14 46792
     14 296644
     14 214823
     14 186284
     14 133975
     13 9939
     13 941
     13 7299
     13 7295
     13 65965
     13 58311
     13 4684
     13 46796
     13 38839
     13 38838
     13 377587
     13 296643
     13 193234
     13 137353
     13 133984
     13 116222
     12 88882
     12 8835
     12 7277
     12 7269
     12 7259
     12 477816
     12 133996
     11 7256
     11 7236
     11 7219
     11 66368
     11 65964
     11 5831
     11 46435
     11 13399
     11 13398
     10 95452
     10 95451
     10 94114
     10 77772
     10 7278
     10 5595
     10 25145
     10 223247
     10 223246
     10 195712
      9 9899
      9 985
      9 9627
      9 95623
      9 95456
      9 9411
      9 8989
      9 46822
      9 32
      9 198725
      9 198719
      9 187394
      9 119223
      8 98362
      8 9612
      8 95457
      8 76946
      8 74549
      8 7287
      8 7281
      8 728
      8 7258
      8 72469
      8 7213
      8 65966
      8 658227
      8 311477
      8 21868
      8 198721
      8 14
      8 133997
      8 133994
      8 133993
      8 133992
      8 133983
      8 114631
      7 95454
      7 95453
      7 94112
      7 88886
      7 7267
      7 72474
      7 71
      7 65156
      7 614
      7 51166
      7 494514
      7 4683
      7 46825
      7 4682
      7 46819
      7 46818
      7 46814
      7 46795
      7 43679
      7 37174
      7 198716
      7 189258
      7 1891767
      7 133999
      7 133998
      7 133979
      7 1196
      6 95625
      6 879
      6 7289
      6 72471
      6 67531
      6 61
      6 593
      6 57874
      6 57873
      6 48321
      6 4832
      6 48319
      6 483
      6 24288
      6 212812
      6 212811
      6 188284
      6 188275
      6 139975
      6 126591
      6 11676
      6 113
      5 9695
      5 9643
      5 9614
      5 95458
      5 9539
      5 88887
      5 88885
      5 8848
      5 77773
      5 77129
      5 76
      5 74535
      5 729
      5 7275
      5 7272
      5 7254
      5 6928
      5 62324
      5 6118
      5 59523
      5 5141
      5 46797
      5 44481
      5 434
      5 37349
      5 3488
      5 271514
      5 261
      5 244254
      5 21
      5 193352
      5 18829
      5 188288
      5 188287
      5 188286
      5 188282
      5 141216
      5 137355
      5 126477
      5 12
      5 1162223
      4 99
      4 987
      4 9858
      4 98
      4 9783
      4 9696
      4 9694
      4 9649
      4 95512
      4 937288
      4 9322
      4 8996
      4 88889
      4 88888
      4 88686
      4 8512
      4 7959
      4 7957
      4 77774
      4 7713
      4 7251
      4 61386
      4 6136
      4 55945
      4 4913
      4 4835
      4 48344
      4 48338
      4 47665
      4 46844
      4 46831
      4 46828
      4 46824
      4 46799
      4 45455
      4 42413
      4 39
      4 38358
      4 37965
      4 376
      4 338458
      4 31227
      4 311483
      4 311482
      4 311481
      4 31148
      4 311479
      4 311478
      4 311476
      4 311475
      4 311474
      4 28454
      4 28285
      4 27
      4 2547
      4 252916
      4 251465
      4 251463
      4 2389
      4 198723
      4 198722
      4 19872
      4 198718
      4 189257
      4 188293
      4 188291
      4 18828
      4 188278
      4 188277
      4 186842
      4 184
      4 154833
      4 154831
      4 1385377
      4 129248
      4 12287
      4 119
      3 998
      3 9946
      3 9938
      3 9897
      3 9888
      3 9861
      3 9791
      3 9773
      3 9767
      3 9749
      3 969
      3 9689
      3 9654
      3 959
      3 958
      3 9579
      3 9542
      3 9534
      3 9518
      3 9515
      3 9315
      3 9263
      3 9217
      3 882
      3 87177
      3 866
      3 86521
      3 8523
      3 8296
      3 82678
      3 81824
      3 7373
      3 713
      3 7119
      3 69
      3 68352
      3 6661
      3 64279
      3 6182
      3 61455
      3 61379
      3 588
      3 57662
      3 57661
      3 551
      3 49666
      3 4957
      3 4956
      3 4954
      3 48881
      3 46821
      3 46758
      3 43597
      3 4252
      3 387621
      3 38666
      3 35525
      3 34892
      3 34882
      3 337
      3 329852
      3 3288
      3 32443
      3 28985
      3 289242
      3 286459
      3 27717
      3 277
      3 273489
      3 271515
      3 255217
      3 244
      3 2387
      3 233251
      3 213645
      3 198717
      3 19121
      3 17877
      3 175771
      3 1639
      3 156757
      3 154832
      3 1486
      3 1423
      3 1392
      3 137356
      3 1314
      3 128
      3 1187
      2 9945
      2 9873
      2 9865
      2 986
      2 984
      2 9833
      2 9721
      2 9697
      2 9651
      2 9644
      2 9622
      2 9595
      2 9538
      2 946
      2 9447
      2 9397
      2 9375
      2 9363
      2 93398
      2 93397
      2 93393
      2 93392
      2 9336
      2 9226
      2 91753
      2 899
      2 89632
      2 89252
      2 887131
      2 8868
      2 8863
      2 8855
      2 8843
      2 8792
      2 86665
      2 86251
      2 8616
      2 85549
      2 841
      2 83773
      2 8346
      2 8265
      2 7788
      2 774
      2 7729
      2 77151
      2 77128
      2 76711
      2 7641
      2 75
      2 7386
      2 7175
      2 7153
      2 71412
      2 712
      2 7111
      2 69297
      2 69232
      2 685
      2 6728
      2 67
      2 666
      2 66189
      2 6492
      2 645
      2 6421
      2 6412
      2 62873
      2 5833
      2 5811
      2 5679
      2 56459
      2 553
      2 55
      2 546
      2 544437
      2 52
      2 5165
      2 51129
      2 499226
      2 4934
      2 473964
      2 473865
      2 46894
      2 468371
      2 46834
      2 46833
      2 46823
      2 46817
      2 46816
      2 46813
      2 46811
      2 46745
      2 46218
      2 46
      2 4577
      2 4565
      2 45474
      2 45264
      2 4513
      2 4498
      2 43455
      2 429
      2 428978
      2 42752
      2 418985
      2 4127
      2 41269
      2 3988
      2 39733
      2 39722
      2 39411
      2 38598
      2 384
      2 3818
      2 37185
      2 363716
      2 36166
      2 35845
      2 35743
      2 3566
      2 35655
      2 35572
      2 3557
      2 33616
      2 33528
      2 32962
      2 328397
      2 32482
      2 32392
      2 293
      2 287
      2 28456
      2 28355
      2 27766
      2 27681
      2 273922
      2 273921
      2 271516
      2 2711
      2 252781
      2 229288
      2 2257
      2 218682
      2 218681
      2 218679
      2 218678
      2 218677
      2 217136
      2 213647
      2 213646
      2 213644
      2 198
      2 19628
      2 194198
      2 192847
      2 191766
      2 1916
      2 1912
      2 189268
      2 189256
      2 186193
      2 184616
      2 1831
      2 178772
      2 1649241
      2 162425
      2 1616
      2 151761
      2 151758
      2 1513
      2 1491
      2 1397
      2 135829
      2 135828
      2 135827
      2 1351
      2 132
      2 1318
      2 129951
      2 1299
      2 1247
      2 12288
      2 12232
      2 12227
      2 12183
      2 12161
      2 12145
      2 12136
      2 11988
      2 11913
      2 116992
      2 115
      2 11337
      2 11276
      2 111
      2 11
      1 955
      1 953
      1 9523
      1 9521
      1 9519
      1 9487
      1 93395
      1 81
      1 7993
      1 78454
      1 7742
      1 7432
      1 7429
      1 7427
      1 7426
      1 7253
      1 7242
      1 6941
      1 6413
      1 543946
      1 499227
      1 48981
      1 4836
      1 48359
      1 48351
      1 48349
      1 48343
      1 48335
      1 48333
      1 48331
      1 4833
      1 48323
      1 48311
      1 4831
      1 477951
      1 45351
      1 443256
      1 42898
      1 428974
      1 428973
      1 397
      1 359927
      1 271513
      1 271512
      1 252922
      1 252918
      1 252917
      1 252912
      1 251469
      1 251468
      1 251467
      1 251466
      1 251461
      1 25146
      1 251459
      1 251457
      1 251453
      1 251447
      1 2411
      1 213648
      1 1979162
      1 1861794
      1 1827
      1 171
      1 144
      1 13686
      1 133976
      1 1333721
      1 132241
      1 12957
      1 12286
      1 12285
      1 12144
      1 11866
      1 11788
      1 1162292
      1 1162224
      1 1162222
      1 1162221
      1 11292
      1 11274
      1 11272
      1 112
```

**Comment by cmungall** [comment]
I think it's better to be conservative here, many of our gene pages are dead ends.

should be easy to get this from solr via biolink.

**Comment by lwinfree** [comment]
+1 to Chris' comment

**Comment by jmcmurry** [comment]
Just to follow up on a few things from our conversation today; please correct/clarify:

1) There are a few IDs in Monarch that were perhaps generated in error with the assumption that if we encountered a numeric ID that it was from NCBI; Tom I don't remember was this error the case for Gene or for Taxon or for both? Either way, this assumption, in some cases may not have been correct. Therefore, Tom has suggested that we crosswalk and validate all of our NCBIGene IDs to ensure that they in fact correspond to valid IDs. Of course their validity doesn't guarantee that the source data REALLY meant to reference that data and not some other data, however, we should DEFINITELY remove any IDs that don't resolve at all, and perhaps the wrong IDs will provide some clues to investigate the offending source in more detail. How we go about this, is up for grabs. I believe Tom suggested that we pull down the whole NCBI gene list. [This file ](ftp://ftp.ncbi.nih.gov/gene/DATA/gene_info.gz)seems to be 2.5 GB unzipped; too large to even open to see if contents are what we want. 

2) I decided that for now, we would only give NCBIGene the IDs for which we have corresponding either phenotype or disease data. We can investigate what additional information of Monarch's may be worthwhile, but should first investigate what other sources of data are already being linked out by NCBI so that we do not simply mirror primary sources of data that are already there. Tom and Kent can help with those analytics in due time, but critical path is just getting the list of genes for which we have g2p/g2d. For the latter, Lilly will adapt [the jupyter notebook](https://github.com/monarch-initiative/monarch-analysis/blob/master/notebooks/get-human-genes.ipynb).

On a separate note, I'm having hard time understanding your comment, above Tom wrt taxon. I understand that blank nodes were counted and am not being misled by the counts. However, those TaxIDs themselves are weird. Eg. TaxID "1" ([https://www.ncbi.nlm.nih.gov/taxonomy/1](https://www.ncbi.nlm.nih.gov/taxonomy/1)) is actually "root". What does this even mean in our data? Perhaps that is a separate conversation though.

**Comment by TomConlin** [comment]
Hi Lilly
Here is a list of  1,155 NCBIGene identifiers which do have phenotypes in Monarch  
(or will when the 201706 release makes it to production)  
[ncbigeneid_with_phenotype.txt](https://github.com/monarch-initiative/monarch-app/files/1087354/ncbigeneid_with_phenotype.txt) 

If there are other tasks associated with getting the linkout file ready please let me know.

thanks

**Comment by lwinfree** [comment]
Thanks Tom! Out of curiosity, do you have any idea when the newest release
will make it to production?

**Comment by iamkoehler** [comment]
@TomConlin is this the number of human genes? If yes, this is way to low.

Doing 
`wget http://compbio.charite.de/jenkins/job/hpo.annotations.monthly/lastSuccessfulBuild/artifact/annotation/ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt`
and
`awk '{print $1}' ALL_SOURCES_ALL_FREQUENCIES_genes_to_phenotype.txt | sort | uniq | wc -l`
gives me **3408** human genes with at least one HPO-term in the HPO-project data.

Am I comparing apples with oranges here?

**Comment by kshefchek** [comment]
Yes 1115 seems low, our solr index is reporting 4494 human genes with phenotype associations: 
[https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&indent=on&wt=json&rows=0&start=0&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=10000000&facet.method=enum&fq=subject_category:%22gene%22&fq=object_category:%22phenotype%22&fq=subject_taxon:%22NCBITaxon:9606%22&facet.field=subject&q=*:*](https://solr.monarchinitiative.org/solr/golr/select/?defType=edismax&indent=on&wt=json&rows=0&start=0&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=10000000&facet.method=enum&fq=subject_category:%22gene%22&fq=object_category:%22phenotype%22&fq=subject_taxon:%22NCBITaxon:9606%22&facet.field=subject&q=*:*)

**Comment by TomConlin** [comment]
@drseb  @kshefchek  it is not a count of genes in Monarch, it is a small set I am maximally confident are ncbigene pages at monarch with directly attributable phenotypes, after the LinkOuts are working we will expand the set to include more of the inferred results we observe in production.

@lwinfree  I keep my fingers crossed and watch http://ci.monarchinitiative.org/view/dev/ then http://ci.monarchinitiative.org/view/prod/ after http://ci.monarchinitiative.org/view/dipper has finished making RDF.  I have not had a hand in this next stage yet.

**Comment by kshefchek** [comment]
When pulling these directly from our RDF data, also consider that not all NCBI gene identifiers are genes, some are loci, for example:
https://www.ncbi.nlm.nih.gov/gene/?term=100188834

Theres a long discussion here:
https://github.com/monarch-initiative/dipper/issues/273

We ideally want to filter these out, the advantage of using scigraph or solr is that these are not categorized as genes.

**Comment by jmcmurry** [comment]
### Just to summarize:

1) Tom will now provide a list of the genes we currently have live on our site.
2) Lilly will then write a script to compare that 'live' list with the list filtered for reliable, uncontested genes (Tom provided above).
3) The intersection of those two lists will be what we provide to NCBI
4) We will evaluate the LinkOut process to make sure all is working smoothly
5) We will expand the gene list to include additional genes for which we have other relevant data by way of inferences. That will require a deeper dive into QC.

Please correct / clarify as needed.

**Comment by kshefchek** [comment]
I'm probably confusing things, but also feel free to use the code I wrote for the NAR paper, that collects human genes with phenotype or disease data supported by at least one of hpoa, omim, orphanet, or clinvar (filtering likely pathogenic and below out of the set).

https://github.com/monarch-initiative/monarch-analysis/blob/master/nar/human-gene-coverage.py#L216

**Comment by TomConlin** [comment]
[biolink_filtered_ncbigeneid_with_phenotype.txt](https://github.com/monarch-initiative/monarch-app/files/1092713/biolink_filtered_ncbigeneid_with_phenotype.txt)


the intersection is small 85 genes which makes it a great test file

**Comment by lwinfree** [comment]
@TomConlin Could you please tell me more about the file you just posted? Is it the list of genes that is in common between the list you provided earlier (ncbigeneid_with_phenotype.txt) with the list of all genes currently in Monarch? If so, there are only 85 genes? Thanks for the help!

**Comment by TomConlin** [comment]
email a replied to Lilly earlier repeating it here 

yes exactly right  
the intersection of the set I previously generated and  
what I find in the biolink API for associations with phenotypes
is 85 genes.

will add that the specific endpoint I used was 
https://api.monarchinitiative.org/api/mart/gene/phenotype/NCBITaxon%3A9606

**Comment by lwinfree** [comment]
Closing as this is now a part of https://github.com/monarch-initiative/monarch-app/issues/1563
