### ISSUE TITLE
duplicate classes when frequency is indicated

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#146]
For example see this disease page:
http://tartini.crbs.ucsd.edu/disease/OMIM_264090
click on phenotypes tab and sort on the phenotypes column. In this image, you can see that there are two phenotypes, chryptochidism and enlarged penis, that have duplicate entries where one has no frequency indicated and the other has a frequency. 
![image](https://f.cloud.github.com/assets/796636/2252778/0eb6b40e-9daf-11e3-9ce3-0cec9ac925d9.png)

Behavior could either be to collapse these or to display the PMID source, making it more obvious that these are distinct entries. If we did the latter though, we would need to work on the counts because the overview page is counting these twice.

**Comment by cmungall** [comment]
Is this a data bug?

Do we have separate PMIDs for each? We should always show PMIDs

**Comment by mellybelly** [comment]
I think think these do likely have different PMIDs or are separate annotations made at different times that haven't been merged? punting till may milestone.

**Comment by nlwashington** [comment]
yes, these have different sources.  often one is drawn from PMID, the other from an ORPHANET entry.  the current interface now makes that obvious.  would you like those merged?

**Comment by mellybelly** [comment]
I guess I kind of do expect in this table that each row is a different phenotype, and therefore the number of rows=#phenotypes listed on the tab. Lower priority though, moving to july.

**Comment by mellybelly** [comment]
@nlwashington assigning to November release

**Comment by jmcmurry** [comment]
As we are no longer displaying phenotype frequency column, I think this ticket is at least temporarily no longer relevant. Please reopen and clarify if necessary.
