### ISSUE TITLE
Can I get all gene and phenotype/disease associations in Monarch?

### ISSUE THREAD

**Issue by zhengj2007** [monarch-initiative/monarch-legacy#1460]
I am interested to get all gene (all different organism) and phenotype or disease associations in Monarch.
On Monarch website, I can select abnormal phenotype and list genes like following link:
https://monarchinitiative.org/phenotype/HP:0000118#genes

On this page, it has a button TSV, which allow me to view/download gene/phenotype associations up to 100,000 rows. However, there are total 452283 rows for this kind associations. Is it possible that I can download all associations in one click?

Thanks!

**Comment by kshefchek** [comment]
We are working on adding tsv mart downloads as a service in our new API service: 
https://api.monarchinitiative.org/api/#!/mart/get_mart_disease_associations_resource
https://api.monarchinitiative.org/api/#!/mart/get_mart_gene_associations_resource

Right now these return json -  I'll add an issue to the biolink tracker and post it here.

EDIT: https://github.com/biolink/biolink-api/issues/77
and https://github.com/biolink/biolink-api/issues/78,
https://github.com/monarch-initiative/monarch-app/issues/1461

**Comment by zhengj2007** [comment]
Thanks for your quick response!

I tried the API. However, it only returned gene and phenotype association. If its output can be same as current TSV download would be great since it contains the labels of phenotype term, evidence codes and references. 

Besides, the current API requires to provide Taxon ID. If I am interested in more than one kinds of organisms, what should I do? Is it possible to make a drop down list to show all availble organisms in the database for users to choose?

I am interested to access the Rest API using program, such as Java. Do I need to provide authorization information? If it is, what information should I give? APIkey? Is there any tutorial on the structure of returned Json object? 

Thanks!

**Comment by kshefchek** [comment]
See this notebook as an example while we work on biolink: https://github.com/monarch-initiative/monarch-analysis/blob/master/notebooks/fetch-monarch-data.ipynb

**Comment by zhengj2007** [comment]
Thanks, Kent!

**Comment by kshefchek** [comment]
Also see: https://data.monarchinitiative.org/tsv/

**Comment by qjwang2001** [comment]
Hi, there: I am new and trying to do something similar to what @zhengj2007 was doing. Just wondering why the number of genes in the parenthesis after Genes is different/less than the total?

Also what is the relationship between this APP and LAMHDI or ClinVar?

Thanks.
