### ISSUE TITLE
Move TSV generation from solr to biolink

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1461]
Right now our TSV buttons hyperlink to a solr call with the necessary query params.  The biolink mart service would be an improvement as it paginates over the solr results and can return the entire download (instead of cutting off at 100k).

Blocked by: https://github.com/biolink/biolink-api/issues/77, https://github.com/biolink/biolink-api/issues/78

**Comment by cmungall** [comment]
Should hopefully be resilient but not sure about inviting possibly large numbers of parallel clicks from users and bots...

**Comment by kltm** [comment]
Yeah...you may want to actually benchmark that, or look at our benchmarks. We can talk about this at some point too.
https://github.com/geneontology/amigo/issues/193
Specifically: https://github.com/geneontology/amigo/issues/193#issuecomment-215283962

**Comment by kshefchek** [comment]
perhaps for the major association categories we should just generate these for each release and serve them from data.monarchinitative.org

**Comment by kshefchek** [comment]
closing see: https://github.com/monarch-initiative/monarch-app/issues/1483#issuecomment-323157281
