### ISSUE TITLE
MMRRC variant syntax looks ... odd

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1467]
This label notation looks strange to me: ````Sec24d<?>````
Also lack of any identifiers, or hyperlinks seems strange.
Are these source IDs not resolvable in MMRRC?
https://monarchinitiative.org/model/MMRRC:040238#variants

**Comment by kshefchek** [comment]
Moved to https://github.com/monarch-initiative/dipper/issues/485
