### ISSUE TITLE
Check for recursion when generating ontology view

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1468]
We are getting a "too much recursion" error when generating the ontology tree view here:
https://beta.monarchinitiative.org/phenotype/HP%3A0002527

I dont see any obvious cycles, but it's possible this view is not complete:

https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/HP:0002527.png?&depth=25&blankNodes=false&relationshipType=subClassOf&direction=OUTGOING&project=*

Regardless, we should be defensive of cycles in ontology graphs.

**Comment by cmungall** [comment]
this class is apparently a subclass of itself

https://scigraph-ontology-dev.monarchinitiative.org/scigraph/graph/neighbors/HP%3A0000118?depth=1&blankNodes=false&relationshipType=subClassOf&direction=OUTGOING&entail=false

**Comment by kshefchek** [comment]
In the latest release we only look at direct parents and children.  The ontology was also fixed upstream.
