### ISSUE TITLE
IDs and synonyms not showing up on overview page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#147]
For example, I land on this page 
http://tartini.crbs.ucsd.edu/phenotype/MP_0003599
by autocompleting on macropenis, but nowhere on this page does it say "macropenis", the aka and ID fields both say undefined, though I can see the URI. 

see #105 for autocomplete example.

**Comment by cmungall** [comment]
Looks like a bug in the api, OQ is returning correct results:

http://nif-services-stage.neuinfo.org//ontoquest-lamhdi/concepts/term/MP_0003599

investigating

**Comment by cmungall** [comment]
Note: this fix also restored definitions (now being returned bia IAO frags in OQ)
