### ISSUE TITLE
documentation for link-outs on Monarch App

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/monarch-legacy#1474]
We should have a page on Monarch web app that documents linking to entries & external sources/databases. See [incoming_curie_map.yaml](https://github.com/monarch-initiative/dipper/blob/master/dipper/incoming_curie_map.yaml) created by Julie. 

Examples of documentation I like:
- http://omim.org/help/external
- http://omim.org/help/linking *this is my favorite*
- http://www.ensembl.org/info/docs/webcode/linking.html

We could also publish this information in a blog with examples when the time comes.

cc @jmcmurry

**Comment by lwinfree** [comment]
This is what I have so far @jmcmurry. If I've missed anything, please let me know by telling me the organization, and I'll add it! I'm thinking about adding links to the ontologies too. 

## Genes and gene features
| organization | URL | example |
|------|-------|----|
| NCBIGene **(clique leader)**\* | 'http://monarchinitiative.org/NCBIGene:##' | https://monarchinitiative.org/NCBIGene:6622 |
| ENSEMBL | 'http://monarchinitiative.org/ENSEMBL:##' | https://monarchinitiative.org/ENSEMBL:ENSG00000145335 |
| HGNC: HUGO Gene Nomenclature Committee | 'http://monarchinitiative.org/HGNC:##' | https://monarchinitiative.org/HGNC:11138 |
| KEGG-hsa: Kyoto Encyclopedia of Genes and Genomes - Human | 'http://monarchinitiative.org/KEGG-hsa:##' | https://monarchinitiative.org/KEGG-hsa:6622 |
| FlyBase | 'https://monarchinitiative.org/FlyBase:FBgn##' | https://monarchinitiative.org/FlyBase:FBgn0036212 |
| Xenbase | 'https://monarchinitiative.org/Xenbase:XB-GENE-##' | https://monarchinitiative.org/Xenbase:XB-GENE-1014191 |
| RGD: Rat Genome Database | 'https://monarchinitiative.org/RGD:##' | https://monarchinitiative.org/RGD:3729 |
| MGI: Mouse Genome Informatics | 'https://monarchinitiative.org/MGI:##' | https://monarchinitiative.org/MGI:1277151 |
| ZFIN: Zebrafish Information Network | 'https://monarchinitiative.org/ZFIN:ZDB-GENE-##' | https://monarchinitiative.org/ZFIN:ZDB-GENE-980526-166 |
| Wormbase | 'https://monarchinitiative.org/WormBase:WBGene##' | https://monarchinitiative.org/WormBase:WBGene00000415 |

\***Redirection from equivalent gene ids to to the NCBIGene, where available and appropriate**

## Diseases
| organization | URL | example |
|-----|-----|-----|
|  OMIM: Online Mendelian Inheritance in Man \***(clique leader)** | 'http://monarchinitiative.org/OMIM:##' | https://monarchinitiative.org/OMIM:602404 |
| Orphanet: rare diseases and orphan drugs| 'http://monarchinitiative.org/Orphanet:##' | https://monarchinitiative.org/Orphanet:2828 |
| UMLS: unified medical language system | 'http://monarchinitiative.org/UMLS:##' | https://monarchinitiative.org/UMLS:CN202824 |
| MESH: Medical Subject Headings | ' http://monarchinitiative.org/MESH:##' |https://monarchinitiative.org/MESH:D010300 |
| Disease Ontology ID | ' http://monarchinitiative.org/DOID:##' | https://monarchinitiative.org/DOID:14330 |

\***Redirection from equivalent disease ids to OMIM, where available and appropriate**

## Phenotypes
| ontology | URL | example |
|-----|-----|-----|
| HP: Human Phenotype Ontology | 'http://monarchinitiative.org/HP:##' | https://monarchinitiative.org/HP:0400004 |
| MP: Mammalian Phenotype Ontology | 'http://monarchinitiative.org/MP:##' | https://monarchinitiative.org/MP:0003878 |
| Uberpheno: phenotype ontology | 'https://monarchinitiative.org/UPHENO:##' | https://monarchinitiative.org/UPHENO:0001001 |
| UBERON: anatomy ontology | 'http://monarchinitiative.org/UBERON:##PHENOTYPE'| https://monarchinitiative.org/UBERON:0001690PHENOTYPE|

**Comment by kltm** [comment]
`Hyoto` -> `Kyoto`

**Comment by jmcmurry** [comment]
Looks good, please make it so

**Comment by mellybelly** [comment]
Can we move this to a page on the app?

**Comment by lwinfree** [comment]
Yes that's the plan @mellybelly :)

**Comment by lwinfree** [comment]
done, under Documentation tab
