### ISSUE TITLE
update organizations on our website

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/monarch-legacy#1479]
the attribution at the bottom should read:
The Monarch Initiative is a collaboration between Oregon Health & Science University, 
    The Jackson Laboratory, Lawrence Berkeley National Laboratory, Charité - Universitätsmedizin Berlin, Garvan Institute of Medical Research, 
    and William Harvey Research Institute, Barts & The London School of Medicine & Dentistry, 
    Queen Mary University of London, and the Renaissance Computing Institute, University of North Carolina at Chapel Hill

I will do this soon.

**Comment by lwinfree** [comment]
see [issue](https://github.com/monarch-initiative/monarch-app/issues/1495) when fixing

**Comment by jmcmurry** [comment]
It is quite the eye-ful. I think each institute on its own line would make things easier to read:

The Monarch Initiative is an international collaboration between the following institutions:

- Oregon Health & Science University
- The Jackson Laboratory
- Lawrence Berkeley National Laboratory
- Charité - Universitätsmedizin Berlin
- Garvan Institute of Medical Research
- William Harvey Research Institute
- Barts & The London School of Medicine & Dentistry, Queen Mary University of London 
- Renaissance Computing Institute, University of North Carolina at Chapel Hill

**Comment by lwinfree** [comment]
+1

**Comment by lwinfree** [comment]
note to self: check license info & make sure accurate - also add separate license page

**Comment by lwinfree** [comment]
done
