### ISSUE TITLE
Searches that include "disease", "gene", "phenotype"

### ISSUE THREAD

**Issue by tkonopka** [monarch-initiative/monarch-legacy#1481]
The search results page has strange formating when the query string includes "disease", "gene", "phenotype", or taxon keywords.

The issue is related to query-string highlighting using &lt;em&gt; tags. When the query includes the special words, the decoration now unnecessarily acts on parts of the results table. The net effect on the "Category" and "Taxon" columns is visual clutter, but in the "Term" column it causes broken links.

Examples: 
https://monarchinitiative.org/search/Parkinson%20disease
https://monarchinitiative.org/search/chloroplast%20gene
https://monarchinitiative.org/search/blood%20phenotype
https://monarchinitiative.org/search/troglodytes

**Comment by jmcmurry** [comment]
Yowza; this is awful. Thanks for pointing it out. @DoctorBud could you look into this please?

**Comment by DoctorBud** [comment]
Fixed in https://github.com/monarch-initiative/monarch-app/pull/1490/
