### ISSUE TITLE
Document data downloads better on website

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1483]
<img width="223" alt="screen shot 2017-08-11 at 10 21 39 am" src="https://user-images.githubusercontent.com/3658863/29224386-fe495658-7e7e-11e7-8220-6ee835375deb.png">

Change the above heading to "Monarch data downloads and services" and document data.monarchinitiative.org. This is a major oversight that should be remedied asap. If I have time I will do it myself today else as this fix is easy, perhaps @lwinfree and @putmantime could tackle.

**Comment by lwinfree** [comment]
Will take a crack at it!

**Comment by putmantime** [comment]
@lwinfree Happy to help as well.

**Comment by kshefchek** [comment]
From interacting with users and collabs I would say most just want tsv data dumps, so higher impact would be offering tsv files in data.monarch.  This is not to deter this effort just my two cents.  Eventually this should come from biolink but even just a jenkins job that gets tsvs from solr and scp's them to data.monarch would be a quick improvement.

**Comment by jmcmurry** [comment]
+1

**Comment by kshefchek** [comment]
I've written a script to pull down tsv's from solr and have put the output here: https://data.monarchinitiative.org/tsv/.  I'll add this to jenkins and make a readme.

Script: https://github.com/monarch-initiative/monarch-analysis/blob/master/monarch/dump-data.py

**Comment by kshefchek** [comment]
cc @julesjacobsen this may be useful for exomiser

**Comment by lwinfree** [comment]
this is done - found under About header
