### ISSUE TITLE
publications are out of date

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1488]
https://monarchinitiative.org/page/pubs

Can we come up with a better way to autopopulate these? @kltm might have ideas

**Comment by kltm** [comment]
My go-to idea for this kind of thing is to use an internal (or public) Zotero group and then populate off of its feed--essentially like the blog mechanism you already have, but with a longer cache update.

**Comment by lwinfree** [comment]
I've updated them on beta, they just have been pushed to the live site yet
