### ISSUE TITLE
502 Bad Gateway for Exomiser

### ISSUE THREAD

**Issue by hhx037** [monarch-initiative/monarch-legacy#1489]
Hi,

the link provided for the online version of Exomiser [http://monarch-exomiser-web-dev.monarchinitiative.org/exomiser/] now gives a 502 Bad Gateway error. I tried several times over the past hour, in two different browsers, clearing cache and cookies, all unsuccessfully.

Could someone please look into this?

Cheers,

Stephane

**Comment by kshefchek** [comment]
cc @julesjacobsen

**Comment by julesjacobsen** [comment]
It's behaving itself now. btw there is a nicer link for this now:

  http://exomiser.monarchinitiative.org/exomiser/

**Comment by hhx037** [comment]
That's great, thanks a lot.

Yes, the address is indeed much better now! 😊

Steph
