### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#149]
We should have log files that track which pages are accessed, when, etc...

**Comment by kltm** [comment]
Probably a job for Google Analytics (standard) or, if you're expecting a lot of machine traffic (or need customization/privacy), Pikwik.

**Comment by harryhoch** [comment]
Those are probably fine for a start, but we might want something more homegrown later...

**Comment by kltm** [comment]
I gotta ask: what would you want that those two wouldn't offer?

**Comment by harryhoch** [comment]
detailed sequences of specific page requests by IP would be great. I haven't found that on Analytics, but I haven't looked too hard. Do they have that functionality?

**Comment by kltm** [comment]
Last I checked, they both have that--they essentially create a session and you can see how people move through the pages.

**Comment by harryhoch** [comment]
ok fine. let's start with Google Analytics and then move elsewhere if needed.

**Comment by cmungall** [comment]
Do we have analytics embedded? Reopened.

**Comment by kltm** [comment]
I believe this is fixed now, with separate dev and prod variables. Prod is defined with one for a new property for the time being, but we can switch it or share it out when the time comes.
