### ISSUE TITLE
Footer is occasionally mislinked

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#1495]
On some pages, there seems to be some missing tag or mislinking in the footer; for example:

https://monarchinitiative.org/page/services

![footer](https://user-images.githubusercontent.com/2687900/30777873-f0d20f52-a079-11e7-8173-05552ebfe89c.png)

The bulk of the links are to SciGraph, and while some bounding boxes link to sources, the text itself also link to SciGraph.

Could possibly be fixed if there is a pass with #1064

**Comment by lwinfree** [comment]
will try to fix soon
