### ISSUE TITLE
API call: Given disease id, what are the top X models

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#15]
This should have a parameter that specifies the number of models to return by rank (default to 10).  Because we have several scoring mechanisms, this will default to just one of them (maybe BMAasymIC), but eventually should be configurable.

Initially this is clearly going to fetch just mouse models.  But in the future we'll probably need to parametrize the target species.

This will need to draw on nlx_152525-10 to get the mouse models by rank.

This should return a list of (model id, label, score, metric).  (The individual attribute comparisons is supplied by another call...although it could technically be all rolled into one if we wanted it to.)

**Comment by frdougal** [comment]
Hi Nicole: have you implemented this call?  Thanks Chuck

**Comment by nlwashington** [comment]
This is the syntax for fetching the data from NIF, to be hidden in the Monarch app.
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-10?filter=rank:5

We will need to write a loop to wrap this (can't do greater/lessthan queries yet) until implemented https://support.crbs.ucsd.edu/browse/NIF-9270

**Comment by nlwashington** [comment]
there was a call to fetch models, that returned a flat table-like structure:
{"a":{"type":"disease","id":"OMIM:162400"},"b":{"type":"disease","id":"OMIM:115150"},"metric":"NUMANNOTS_B","score":"100.0","value":"","source":"Monarch/PhenoDigm","resource":"nlx_152525-3"} 

but this isn't great.

how is this json object for a getSimilarThings()-type of function

{"a":  {"id":"OMIM:162400", "type":"disease"},
"b":  {
  {"id":"OMIM:115150", 
    "type":"disease", 
    "score": {"metric":"maxIC", "score":"100.0", "rank":"1"},
  {"id":"OMIM:141900", 
    "type":"disease", 
    "score": {"metric":"maxIC", "score":"110.0", "rank":"2"},
"source":{"id":"nlx_152525-3",label:"Monarch Disease-x-disease"} }

i could also structure it so that the score is actually an array of score(s).

**Comment by frdougal** [comment]
Hi Nicole,
  I think this JSON looks fine.  I can write a .sort javascript function to reorder the elements according to their scores.  I just want to double check something. I should expect results that include models, right?  I should expect something more like this:

{"a": {"id":"OMIM:162400", "type":"disease"},
"b": {
{"id":"MGI:584664",
"type":"model",
"score": {"metric":"maxIC", "score":"100.0", "rank":"1"},
{"id":"MGI:351233",
"type":"model",
"score": {"metric":"maxIC", "score":"110.0", "rank":"2"},
"source":{"id":"nlx_152525-3",label:"Monarch Disease-x-model"} }

Thnaks,
Chuck

**Comment by frdougal** [comment]
yes.  i'm writing it generically so you can fetch any kind of comparisons.  should be committed today.

**Comment by nlwashington** [comment]
How's this?
            "a": {
                "id": "OMIM:118200",
                "label": "Charcot-Marie-Tooth Disease, Demyelinating, Type 1b",
                "type": "disorder"
            },
            "b": {
                "id": "MGI:3711319",
                "label": "Psap<tm1Suz>/Psap<tm1Suz> [involves: 129P2/OlaHsd]",
                "type": "effective_genotype"
            },
            "score": {
                "metric": "BMAasymIC",
                "score": "6.6163985601",
                "rank": "5"
            },
            "metadata": {
                "metric_stats": {
                    "metric": "BMAasymIC",
                    "maxscore": "8.45"
                },
                "avgIC": "8.567",
                "maxIC": "12.234"
            },
            "source": {
                "id": "nlx_152525-10",
                "label": "OwlSim: Disease-x-mouse_genotypes",
                "a_type": "disorder",
                "b_type": "effective_genotype",
                "a_source": "nlx_151835-1",
                "b_source": "nif-0000-00096-6"
            },
            "resource": "nlx_152525-10"
        }

**Comment by frdougal** [comment]
I just have a few questions.  How does the "b" object repeat?  I'm assuming "b" is the "top X models" being returned.  Therefore, I would expect something where the b objects are returned in an array (see below).  This returns several b objects but only one "metadata" object representing the overall max/avg score.

"a": {
"id": "OMIM:118200",
"label": "Charcot-Marie-Tooth Disease, Demyelinating, Type 1b",
"type": "disorder"
},
"b_objects" : ["b0": {
"id": "MGI:3711319",
"label": "Psap<tm1Suz>/Psap<tm1Suz> [involves: 129P2/OlaHsd]",
"type": "effective_genotype"
},
"score": {
"metric": "BMAasymIC",
"score": "6.6163985601",
"rank": "5"
},
"b1": {
"id": "MGI:437474",
"label": "Model1",
"type": "effective_genotype"
},
"score": {
"metric": "BMAasymIC",
"score": "6.6163985601",
"rank": "5"
}
} ],
"metadata": {
"metric_stats": {
"metric": "BMAasymIC",
"maxscore": "8.45"
},
"avgIC": "8.567",
"maxIC": "12.234"
},
"source": {
"id": "nlx_152525-10",
"label": "OwlSim: Disease-x-mouse_genotypes",
"a_type": "disorder",
"b_type": "effective_genotype",
"a_source": "nlx_151835-1",
"b_source": "nif-0000-00096-6"
},

"resource": "nlx_152525-10"
}

**Comment by frdougal** [comment]
yes, at the moment it's an array of a-b pairs, with the properties of the pair all part of a flat structure, which means that the metadata (m) does repeat for each pair.  i've gone back and forth in my head as to whether i should do 

option 1:  {a,[b1,b2,b3...b(n)],m }

or

option 2:  [{a,b1,m},{a,b2,m},{a,b3,m}]

(with the latter (#2) being the current output.)

would you prefer option 1?

**Comment by frdougal** [comment]
Honestly it doesn't matter to me.  I was just wondering how it was going to handle the repeats.

From: Nicole Washington <nlwashington@lbl.gov<mailto:nlwashington@lbl.gov>>
Date: Tuesday, December 17, 2013 2:39 PM
To: "Borromeo, Charles" <chb69@pitt.edu<mailto:chb69@pitt.edu>>
Cc: monarch-initiative/monarch-app <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [monarch-app] API call: Given disease id, what are the top X models (#15)

yes, at the moment it's an array of a-b pairs, with the properties of the pair all part of a flat structure, which means that the metadata (m) does repeat for each pair.  i've gone back and forth in my head as to whether i should do

option 1:  {a,[b1,b2,b3...b(n)],m }

or

option 2:  [{a,b1,m},{a,b2,m},{a,b3,m}]

(with the latter (#2) being the current output.)

would you prefer option 1?

On Dec 17, 2013, at 11:26 AM, Borromeo, Charles wrote:

I just have a few questions.  How does the "b" object repeat?  I'm assuming "b" is the "top X models" being returned.  Therefore, I would expect something where the b objects are returned in an array (see below).  This returns several b objects but only one "metadata" object representing the overall max/avg score.

"a": {
"id": "OMIM:118200",
"label": "Charcot-Marie-Tooth Disease, Demyelinating, Type 1b",
"type": "disorder"
},
"b_objects" : ["b0": {
"id": "MGI:3711319",
"label": "Psap<tm1Suz>/Psap<tm1Suz> [involves: 129P2/OlaHsd]",
"type": "effective_genotype"
},
"score": {
"metric": "BMAasymIC",
"score": "6.6163985601",
"rank": "5"
},
"b1": {
"id": "MGI:437474",
"label": "Model1",
"type": "effective_genotype"
},
"score": {
"metric": "BMAasymIC",
"score": "6.6163985601",
"rank": "5"
}
} ],
"metadata": {
"metric_stats": {
"metric": "BMAasymIC",
"maxscore": "8.45"
},
"avgIC": "8.567",
"maxIC": "12.234"
},
"source": {
"id": "nlx_152525-10",
"label": "OwlSim: Disease-x-mouse_genotypes",
"a_type": "disorder",
"b_type": "effective_genotype",
"a_source": "nlx_151835-1",
"b_source": "nif-0000-00096-6"
},

"resource": "nlx_152525-10"
}

**Comment by nlwashington** [comment]
Ok, I have created the function: 
fetchThingsSimilarToADisease = function(id,target_species,cutoff,metric)

which requires id and target_species (taxon id), and will default to 25 for a cutoff and BMAasymIC for the metric.  

this will return to you a JSON blob of the structure:
a: query item, 
b:[list,of,similar,things, above,the,cutoff,with,scores],
metadata (about the analysis, that you can use for doing stuff with the scores)
source (info about the source, mostly for under-the-hood stuff, linking, and display -- i could remove)

this will work with either '10090' for mouse genotypes/models OR '9606' to get human diseases.

right now we only have two precomputed analysis tables, one for disease-x-disease and disease-x-mouse, but will be adding fish shortly.

this is a convenience function that requires the query to be a disease identifier.  i will write a more-generic function that will allow for other kinds of query entities as well (like genes, genotypes), that will give you a similarly-structured json blob.

i have called this function on the disease pages for both mouse models and diseases requesting the top 25, so that you can find the models attached to the disease like obj.similar_models, as a hashmap per organism.  similar_diseases is the same way. we can easily change the cutoff.

i've fixed up the app, so that now you can see the similar diseases, and added a new table for similar_models on the disease pages.  

have a looksy.  :)

let me know if there's anything missing in the json.

**Comment by harryhoch** [comment]
cool!

**Comment by pnrobinson** [comment]
Hi everybody,
by the way, something that would be very useful would be a classification of the diseases found in omim and elsewhere as monogenic, polygenic, trait, somatic mutation etc., i.e., it would be nice to have a small hierarchy for "type". This is very difficult to do by parsing morbid map, and would be extremely valuable to the community.
-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: nlwashington [notifications@github.com]
Gesendet: Dienstag, 17. Dezember 2013 20:04
An: monarch-initiative/monarch-app
Betreff: Re: [monarch-app] API call: Given disease id, what are the top X models (#15)

How's this?
"a": {
"id": "OMIM:118200",
"label": "Charcot-Marie-Tooth Disease, Demyelinating, Type 1b",
"type": "disorder"
},
"b": {
"id": "MGI:3711319",
"label": "Psap<tm1Suz>/Psap<tm1Suz> [involves: 129P2/OlaHsd]",
"type": "effective_genotype"
},
"score": {
"metric": "BMAasymIC",
"score": "6.6163985601",
"rank": "5"
},
"metadata": {
"metric_stats": {
"metric": "BMAasymIC",
"maxscore": "8.45"
},
"avgIC": "8.567",
"maxIC": "12.234"
},
"source": {
"id": "nlx_152525-10",
"label": "OwlSim: Disease-x-mouse_genotypes",
"a_type": "disorder",
"b_type": "effective_genotype",
"a_source": "nlx_151835-1",
"b_source": "nif-0000-00096-6"
},
"resource": "nlx_152525-10"
}

**Comment by frdougal** [comment]
Hi Nicole,
  Thanks for the call.  I added it as an URL call in the webapp.js file.
I'm encountering two issues:
1.  I tested my call using OMIM_127750 "Dementia, Lewy Body".  The default
   cutoff is "5".  In this case, the code returns over 50 results.  Several
   of the matching models have the same IC scores and rank:
   "metric":"BMAasymIC","score":"4.3934629617","rank":"4"

Therefore, the "5" cutoff is not met.  I don't know what to suggest in
this case.  The front-end code may need to handle this.  I'm not sure.
1.  When I try to look at the disease page for "Dementia, Lewy Body"
   (http://localhost:8080/disease/OMIM_127750) I encounter an error related
   to the new genTableOfSimilarModels call:

lib/monarch/web/webapp.js, line 254
Script Stack    at lib/monarch/web/webapp.js:254 (anonymous)
    at ringo/mustache.js:318 (anonymous)
    at ringo/mustache.js:249 (anonymous)
    at ringo/mustache.js:257 (anonymous)
    at ringo/mustache.js:67 (anonymous)
    at ringo/mustache.js:172 (anonymous)
    at ringo/mustache.js:170 (anonymous)
    at ringo/mustache.js:63 (anonymous)
    at ringo/mustache.js:172 (anonymous)
    at ringo/mustache.js:170 (anonymous)
    at ringo/mustache.js:63 (anonymous)
    at ringo/mustache.js:446 (anonymous)
    at ringo/mustache.js:470 (anonymous)
    at lib/monarch/web/webapp.js:257 (anonymous)
    at stick/lib/middleware/route.js:215 (route)
    at stick/lib/middleware/params.js:102 (anonymous)
    at stick/lib/middleware/static.js:62 (static)
    at stick/lib/stick.js:37 (app)
    at ringo/jsgi/connector.js:42 (handleRequest

From:  nlwashington notifications@github.com
Reply-To:  monarch-initiative/monarch-app
<reply+i-20405972-e7426f1879b38d75437804fc7d2d15f4f0182c56-5503816@reply.gi
thub.com>
Date:  Tuesday, December 17, 2013 6:17 PM
To:  monarch-initiative/monarch-app monarch-app@noreply.github.com
Cc:  "Borromeo, Charles" chb69@pitt.edu
Subject:  Re: [monarch-app] API call: Given disease id, what are the top X
models (#15)

Ok, I have created the function:
fetchThingsSimilarToADisease = function(id,target_species,cutoff,metric)
which requires id and target_species (taxon id), and will default to 25
for a cutoff and BMAasymIC for the metric.
this will return to you a JSON blob of the structure:
a: query item, 
b:[list,of,similar,things, above,the,cutoff,with,scores],
metadata (about the analysis, that you can use for doing stuff with the
scores)
source (info about the source, mostly for under-the-hood stuff, linking,
and display -- i could remove)
this will work with either '10090' for mouse genotypes/models OR '9606' to
get human diseases.
right now we only have two precomputed analysis tables, one for
disease-x-disease and disease-x-mouse, but will be adding fish shortly.
this is a convenience function that requires the query to be a disease
identifier.  i will write a more-generic function that will allow for
other kinds of query entities as well (like genes, genotypes), that will
give you a similarly-structured json blob.
i have called this function on the disease pages for both mouse models and
diseases requesting the top 25, so that you can find the models attached
to the disease like obj.similar_models, as a hashmap per organism.
similar_diseases is the same way. we can easily change the cutoff.
i've fixed up the app, so that now you can see the similar diseases, and
added a new table for similar_models on the disease pages.
have a looksy.  :)
let me know if there's anything missing in the json.
‹
Reply to this email directly or view it on GitHub
<https://github.com/monarch-initiative/monarch-app/issues/15#issuecomment-3
0801754>.

**Comment by nlwashington** [comment]
for item 1 (more items returned than requested):

Well, it is behaving as best as I can do for you... yes, there are several matches that score equally well.... that's the scoring algorithm, nothing I can do about that.  Therefore, if their scores are equal, their ranks are equal.  

What would you like to be the behavior in this case?  I don't think it's right for the server to arbitrarily choose one of the fifty to return; I think it would need to be handled by the client.  

It happens that I gave the items the equivalent ceiling rank rather than the floor, which I could change in the future.  But if I changed that, then sometimes you might only get 4 results when you ask for 5, if the "5th" is equally ranked with another 50.  Somewhat similar problem.  

Note that no matter what, there might be a case where we have more items than requested that score as the very top/ceiling model.  so if i make them equally the top hit, you'd have to deal with that; and if i made them equally the floor of the set, you'd get no results.  what would you do in that case?  

One possibility for presentation is to randomly choose one of the fifty to show with a "more" option which would allow the user to expand to see all equivalently-scoring models.

Second, I'm not sure what the problem is with the http://localhost:8080/disease/OMIM_127750 example.  I got it to load fine.  try deleting your cache (monarch-app/cache/disease/key-OMIM_127750.json).  in fact, i would delete all of the disease cache when there's been major updates to the code.  see if that fixes the bug.

**Comment by frdougal** [comment]
Hi Nicole,
  Thanks for the reply.  I thought a bunch of identical scores could have been a bug.  I will limit the number of models shown through the UI.

Clearing the cache fixed the error.  Thank you.
Chuck

**Comment by nlwashington** [comment]
ok, the top X models for a given disease can be retrieved from the precomputed disease tables with:
http://localhost:8080/simsearch/disease/OMIM_304120&target_species=10090
where target_species=9606 to get the topX matching diseases or target_species=10090 to get topX mice

in the future, this will hopefully be computed on-the-fly.
