### ISSUE TITLE
Resolve incorrect IDs to zero padded equivalents

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#1502]
For example: https://monarchinitiative.org/disease/DOID:50202 would resolve to https://monarchinitiative.org/disease/DOID:0050202

This is tricky because curies are stored as strings in solr, so we have no mechanism to infer that 50202 == 0050202.  I think this why search does not catch this:
https://monarchinitiative.org/search/DOID:50202

Also note that this is not supported in the purl resolver:
http://purl.obolibrary.org/obo/DOID_50202

My vote is that we put the onus on downstream users.

See original ticket here: https://github.com/monarch-initiative/dipper/issues/531

**Comment by balhoff** [comment]
> My vote is that we put the onus on downstream users

I agree.

**Comment by jmcmurry** [comment]
I agree about putting the onus on downstream users, however, I think there is a middle ground between 404 and assuming what the ID ought to be.

The ideal graceful degradation (in the fullness of time) could be a more appropriate warning message in the browser. Eg. if the prefix is recognized, but the fragment isn't, have the user check the ID for things like padding, casing, delimiters, if the prefix is recognized but the wrong case, have them fix and report. Ideally we would also have some kind of regex we could apply to the fragment too to
validate? Autoreport an issue? Maybe I'm over the top. Identifiers obsession is hard to put down. I'll stop now. *Backs away slowly*... [sirens]
