### ISSUE TITLE
searching for diseases leads to incorrect page

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1514]
searching for 'fanconi anemia' and 'breast cancer' leads to the wrong page. Both searches lead to this page:
https://monarchinitiative.org/disease/KEGG-ds%3AH00031 

I see this in chrome and firefox when autocompleting on the terms

**Comment by nicolevasilevsky** [comment]
If I type fanconi anemia and do not autocomplete, then click on the first hit on this [page](https://monarchinitiative.org/search/fanconi%20anemia), it takes me to this [page](https://monarchinitiative.org/disease/GeneReviews:NBK1401), which also seems wrong.

**Comment by lwinfree** [comment]
when searching for fanconi anemia & not autocompleting, this KEGG page is the 3rd hit & the 1st hit is also a weird page. The "real" page is the 2nd hit. 
<img width="898" alt="screen shot 2017-10-26 at 1 22 37 pm" src="https://user-images.githubusercontent.com/17657625/32075171-c64fc24c-ba50-11e7-929e-888484542a8e.png">

**Comment by kshefchek** [comment]
This is an issue with kegg and gene reviews diseases not being merged with mondo.  I'm not sure the original requirement for having these ids, but they either need be included in the mondo pipeline or removed on the dipper side.

Does anyone recall the use case for the gene reviews ingest? @cmungall @mellybelly

**Comment by kshefchek** [comment]
looks like we're getting MONDO for most of these now (one stray OMIM in there).
