### ISSUE TITLE
BioLink API "GET /bioentity/phenotype/{id}/anatomy/" Not Functioning

### ISSUE THREAD

**Issue by Superraptor** [monarch-initiative/monarch-legacy#1519]
Hi! First, I'd like to say amazing work here, I'm a huge fan of the Monarch Initiative application and the API has been an amazing resource as of late.

Second, my apologies if this is the wrong place to post this. I'm specifically referring to the BioLink API documentation as seen [here](https://api.monarchinitiative.org/api/#!/bioentity/get_phenotype_anatomy_associations).

Essentially, there are two provided examples, "ZP:0004204" and "MP:0008521". The first provides the following output:

```
[
  {
    "label": "muscle pioneer",
    "categories": null,
    "types": null,
    "synonyms": null,
    "description": null,
    "consider": null,
    "deprecated": null,
    "id": "ZFA:0001086",
    "replaced_by": null
  }
]
```

While the second produces:

```
[]
```

I thought it might work with another Mammalian Phenotype identifier, so I tried MP:0003279 (aneurysm), but it still provided:

```
[]
```

Further, I tried a Human Phenotype Ontology identifier (HP:0100790, hernia) and got the same result. All of these calls resulted in a 200 response.

Is this how the function should be working? Or is it still in development? Thanks so much!

**Comment by kshefchek** [comment]
Thanks for the ticket! I've moved this over to the biolink repo and added you as a watcher, see https://github.com/biolink/biolink-api/issues/122
