### ISSUE TITLE
lowercase pmids in display

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#152]
http://tartini.crbs.ucsd.edu/disease/OMIM_606744

references such as:
pmid:11781686

this probably needs pushed way upstream to phenotype-commons svn. But we should have a few layers of defense. Ingest should probably be kept simple, just process as-is, warts and all. But href mechanism should probably be defensive in UI.

**Comment by cmungall** [comment]
Also PubMed here:

http://127.0.0.1:8282/phenotype/HP_0000218

**Comment by nlwashington** [comment]
This is a data issue.  We can do some cleanup in DISCO at view-creation time.  See https://support.crbs.ucsd.edu/browse/LAMHDI-350.

@cmungall and @pnrobinson, I am not sure where to file this ticket upstream?

**Comment by nlwashington** [comment]
The sql has been fixed to scrub this resource.  Data should appear correct on beta.
