### ISSUE TITLE
Add links to VarSome

### ISSUE THREAD

**Issue by lwinfree** [monarch-initiative/monarch-legacy#1526]
See https://varsome.com/how-do-i-create-link-varsome/ for help.
Current issue is that they link on gene symbols, not identifiers. Julie has emailed them for clarification on this point.

**Comment by amassouras** [comment]
Added ability to query by HGNC identifier, for example https://varsome.com/gene/HGNC:1100

**Comment by lwinfree** [comment]
done - see https://monarchinitiative.org/gene/HGNC:1101 for example
