### ISSUE TITLE
Potential scigraph issues with latest release

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1529]
This seems unusual

Marfan:
https://monarchinitiative.org/disease/MONDO:0007947

There are two children Marfan type 2. One is a MESH class, MESH:C535911. This is not in MONDO

If we ask scigraph about this
https://scigraph-ontology.monarchinitiative.org/scigraph/graph/neighbors/MESH:C535911?depth=1&blankNodes=false&direction=BOTH&entail=false

it has things like:

```
{
"sub": "MESH:C535911",
"obj": "MONDO:0007947",
"pred": "subClassOf",
"meta": {
"equivalentOriginalNodeSource": [
"http://purl.obolibrary.org/obo/UMLS_C2698016"
],
"isDefinedBy": [
"http://purl.obolibrary.org/obo/upheno/monarch.owl"
],
"lbl": [
"subClassOf"
],
"equivalentOriginalNodeTarget": [
"http://purl.obolibrary.org/obo/OMIM_154700"
]
}
},
```

UMLS:C2698016 is not in mondo either

something has likely leaked into the import chain?

**Comment by kshefchek** [comment]
I noticed we're still importing http://purl.obolibrary.org/obo/upheno/doid/bridge.owl, which imports http://purl.obolibrary.org/obo/upheno/doid/mondo.owl, and this is the old version of mondo?  I'm guessing the doid/bridge.owl file should be removed all together.

**Comment by cmungall** [comment]
Good catch, that will be the cause of all kinds of nonsense

sorry I should have tested beta more...

**Comment by kshefchek** [comment]
My fault, should have caught this when I updated mondo, https://github.com/monarch-initiative/monarch-ontology/commit/245ba14f0f2cf0bd9bb372e09d120bdc89cbafc0

**Comment by kshefchek** [comment]
Looks like the latest scigraph load has fixed this.  The subClassOf edges between FA group A and FA also decreased from 35 to 12.  [dev](https://scigraph-ontology-dev.monarchinitiative.org/scigraph/cypher/execute?cypherQuery=MATCH%20(groupA%3ANode{iri%3A%27http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0009215%27})-[edge%3AsubClassOf]-%3E(fa%3ANode{iri%3A%27http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019391%27})%20RETURN%20DISTINCT(COUNT(edge))&limit=10) vs  [production](
https://scigraph-ontology.monarchinitiative.org/scigraph/cypher/execute?cypherQuery=MATCH%20(groupA%3ANode{iri%3A%27http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0009215%27})-[edge%3AsubClassOf]-%3E(fa%3ANode{iri%3A%27http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0019391%27})%20RETURN%20DISTINCT(COUNT(edge))&limit=10)
