### ISSUE TITLE
Some disease description text has strange references embedded

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1535]
Have a look at the description [here](https://monarchinitiative.org/MONDO:0007947).

"At least 25% of cases are due to a new ( de novo ) mutation.[76][10605] Treatment is based on the signs and symptoms in each person.[10605]"

I don't know what these numbers are meant to be, but it is cruft that should be omitted.

**Comment by cmungall** [comment]
Can you file on mondo tracker?

Not sure if we have resources to rewrite the gard scraper but if not I'll hack in some perl to strip these
