### ISSUE TITLE
json empty with analyze results

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#154]
I went to this address directly:
http://tartini.crbs.ucsd.edu/analyze/diseases/?input_items=HP:0011344,HP:0002197,HP:0007202,HP:0001303,HP:0002133,HP:0001631,HP:0000156,HP:0010804,HP:0000280,HP:0000425,HP:0007930,HP:0000023,HP:0001252,HP:0000505,HP:0012382,HP:0002019,HP:0012448,HP:0001622

And then i hit the json button,

and the result was empty, even though there are items populating the table in the display.

**Comment by mellybelly** [comment]
still empty, on prod too.

**Comment by jmcmurry** [comment]
@kshefchek @yuanzhou could you investigate this please? The JSON button does work to produce results, however, the no results page nevertheless shows up, leading the user to think that it is not worth clicking on the json.

**Comment by kshefchek** [comment]
The mode parameter is required for the html table/json button.  The phenogrid renders as it most likely has a default to fall back on.

This seems to be an issue with coming to this page from annotate text.  I will update the url so that we automatically set the mode parameter to search.

**Comment by yuanzhou** [comment]
@kshefchek just a side note: the "search" mode uses "+" instead of the "," in the URL to separate the phenotypes.
