### ISSUE TITLE
When a non-MONDO ID is used for disease page, it assumes it's a leaf node disease

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1542]
compare
https://monarchinitiative.org/disease/MONDO:0019588#phenotypes

with
https://monarchinitiative.org/disease/Orphanet:90636#phenotypes

These are equivalent, so the number of phenotypes is the same as expected. However, the latter does not show which diseases are associated with which disease, which is incorrect.

The reason for this is presumably because we do a SciGraph call to test if a class is a leaf node. If it is a leaf node then we don't show the breakdown by disease, since there is only one. The SciGraph test is presumably failing or not being called correctly.

**Comment by kshefchek** [comment]
fixed with https://github.com/monarch-initiative/monarch-app/pull/1556
