### ISSUE TITLE
ClinVar submissions using MONDO Ids?

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/monarch-legacy#1551]
@mellybelly, while the new mondo ids are fantastic. I was looking for a path for resolving the "equivalent ids" that appear in the UI so that I can convert a MONDO id to an equivalent code system that ClinVar accepts in the submission form (Orphanet, OMIM, MedGen?).

Do you have any suggestions or guidance on how Clingen or others could use the MONDO db or the UI and its APIs (if these are available) to get the list of "equivialent ids" for a specific MONDO id so that we can try to pick the best candidate to pass on to ClinVar.

We need a near term suggestion (like immediate plan) and are open to hearing about the longer term   approach if you have any.

**Comment by cmungall** [comment]
## UI based approaches

 - OLS is updated most frequently. When we submit to OLS, the xrefs corresponds to equivalency
 - Monarch may not have the latest MONDO as it is an integrated release. You will see annotations on MONARCH

## Programmatic

 - Python API + downloaded local files: We recommend http://ontobio.readthedocs.org
 - Web / REST-like APIs
    - OLS API
    - Monarch SciGraph API (but may lag)
 - Queries
    - SPARQL queries over OntoBee (soon: monarch rdf store)

Let us know which is best for you and I can provide more concrete examples.

**Comment by kshefchek** [comment]
@larrybabb okay if I close?  Please reopen if this is unresolved.
