### ISSUE TITLE
Gene pages says no phenotypes to compare even when phenotypes present

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#1555]
https://monarchinitiative.org/gene/NCBIGene:1080#compare

![image](https://user-images.githubusercontent.com/50745/37438800-e21d6df2-27b1-11e8-8c87-135d9ab1b4b2.png)

**Comment by jmcmurry** [comment]
I thought this might be another clique leader issue, but it is not. Same thing happening here: https://monarchinitiative.org/gene/HGNC:1884#compare

**Comment by kshefchek** [comment]
The good news is that this isn't affecting all genes.

The underlying solr query returns a 248 mb json doc?!  The evidence portions of the json results are the culprit, and aren't needed for phenogrid so I'll make the adjustment to just return the fields we need.
