### ISSUE TITLE
text for home page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#156]
lets start with this, I'll get better examples for the links (the X,Y,Z) tomorrow, you can use what is there now if you like. Please free to play with it :-).

The Monarch Initiative
(tagline) Enabling navigation across a rich landscape of phenotypes, diseases, models, and genes for translational research.

(short description - smaller font?)
Semantically describing this data enables novel computational methods to identify previously unknown relationships and suggest novel biological insights. Our goal is to provide usable tools that will help biomedical researchers harness the power of these computational approaches.

For the boxes, perhaps play with coloring these differently using our color scheme, or we can try to develop an icon for each:

Diseases
Explore genetic diseases, find similar models, examine phenotypes, and identify related genes. Try looking at: X,Y, Z.

Models
Find model systems that recapitulate various aspects of human disease or phenotypes. Sample models: X,Y,Z.

Phenotypes
See which diseases, models, and genes are linked to an observed phenotype. For example, X, Y, Z.

Phenotype characterization  
Learn which diseases and models are most similar to a set of phenotypic observations in human, mouse, or zebrafish. For example, view a patient phenotype profile including the following phenotypes: (list 5-7 that have a good match).

also, please spell out the institutions on the front page attributions.
Thx

**Comment by harryhoch** [comment]
Looks good to me. 

On 5 Mar 2014, at 5:31 PM, Melissa Haendel notifications@github.com wrote:

> Explore genetic diseases, find similar models, examine phenotypes, and identify related genes. Try looking at: X,Y, Z.
> 
> Models
> Find model systems that recapitulate various aspects of human disease or phenotypes. Sample models: X,Y,Z.
> 
> Phenotypes
> See which diseases, models, and genes are linked to an observed phenotype. For example, X, Y, Z.
> 
> Phenotype characterization
> 
> Learn which diseases and models are most similar to a set of phenotypic observations in human, mouse, or zebrafish. For example, view a patient phenotype profile including the following phenotypes: (list 5-7 that have a good match).
> 
> also, please spell out the institutions on the front page attributions.
> Thx
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by cmungall** [comment]
We'll have a first pass out later today.

Also include a prominent link to /analyze/phenotypes (search by phenotype profile)?

**Comment by mellybelly** [comment]
Yes that was the idea behind the phenotype characterization box, so that we could have four boxes for now.
