### ISSUE TITLE
case insensitive identifier prefix retrieval

### ISSUE THREAD

**Issue by TomConlin** [monarch-initiative/monarch-legacy#1562]
https://monarchinitiative.org/OMIM:153640  
and 
https://monarchinitiative.org/omim:153640  

should return the same page 
just as 
https://monarchinitiative.org/OMIM:153640 
and 
https://monarchinitiative.org/OMIM_153640
already return the same page

**Comment by kshefchek** [comment]
See https://github.com/monarch-initiative/monarch-app/issues/1429
