### ISSUE TITLE
Phenogrid 'Access-Control-Allow-Origin' error

### ISSUE THREAD

**Issue by tkonopka** [monarch-initiative/monarch-legacy#1565]
Phenogrid support seems to have stopped for outside requests, in particular, IMPC.

After sending an ajax request for phenogrid data and a long wait, the browser console displays

`
Failed to load https://monarchinitiative.org/compare/[...]
: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.mousephenotype.org' is therefore not allowed access. The response had HTTP status code 504.
`

This seems to be a configuration issue at monarchinitiative.org. Could you comment, please?

**Comment by kshefchek** [comment]
It looks like we need to reboot owlsim, see https://github.com/monarch-initiative/monarch-devops/issues/114

@tkonopka can you provide a sample query that is failing?

**Comment by tkonopka** [comment]
That reboot seems to have solved the issue. Thank you. The widgets now seem to work on the mousephenotype site.

For the record, a relevant query is this:

https://monarchinitiative.org/compare/HP:0000486+HP:0000006+HP:0011349/MP:0005236

But my understanding was the failure arose only when sending the query from one domain to another.

**Comment by kshefchek** [comment]
Yes it's strange that this manifested as a cross origin request instead of a time out, but I'm fairly certain it was the cause.

**Comment by balhoff** [comment]
I frequently see (at least in Safari) that various server-side problems calling services from JavaScript get reported as cross origin problems, even when they're not.
