### ISSUE TITLE
"disease" mapping between DO and MONDO

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/monarch-legacy#1569]
Is there a resource that clarifies the way DO's top level terms (disease + children) are mapped into MONDOs top level terms?

I'm not clear why DO's "disease" (DOID:4) and "disease of anatomical entity" (DOID:7) get flattened and mapped to Monarch's "disease" (MONDO:0000001) term?  I see this in Orphanet as well.

Can someone help clarify this root level mismatching of ontological terminologies? It would be helpful when trying to work with groups that want to coalesce around Monarch but come from the DO camp versus the Orphanet camp.

**Comment by cmungall** [comment]
All diseases are diseases of anatomic entities (the concept of AE as defined in caro/uberon is broad and covers everything from a macromolecular complex through to a whole organism). 

These merges by proxy are fairly rare but always deliberate.

We will add axiom annotations to document this

**Comment by kshefchek** [comment]
Should this be in the MONDO repo?  I'm going to close as this appears to be a design decision.
