### ISSUE TITLE
SLC7A13 constraint data mismatch

### ISSUE THREAD

**Issue by vgainullin** [monarch-initiative/monarch-legacy#1574]
There seem to be conflicts between ExAC constraint scores from broad and the ones provided through mygene.info. Why not go by source data?
SLC7A13 example: 
https://monarchinitiative.org/gene/HGNC:23092
https://mygene.info/v3/query/?q=23092&fields=exac
http://exac.broadinstitute.org/gene/ENSG00000164893

**Comment by putmantime** [comment]
This was a mistake on our end.  Mygene is assuming that 23902 is an entrez id, when we are giving it an HGNC numerical id in this case.  Addressed this https://github.com/monarch-initiative/monarch-app/pull/1576  by mapping prefixes to make mygene calls with proper prefix:numerical id pairs.

**Comment by kshefchek** [comment]
This fixed a while back but we finally pushed it to production.  @vgainullin thanks for reporting and let us know if the numbers still look off.
