### ISSUE TITLE
update news and events on monarch site

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1584]
could we add some new upcoming events on the monarch news and events feed?

We could add the upcoming GCC/BOSC conference: 
https://galaxyproject.org/events/gccbosc2018/

and ICBO:
http://icbo2018.cgrb.oregonstate.edu/

**Comment by jmcmurry** [comment]
Agreed, but I think this is best routed through twitter than by some tertiary mechanism.

**Comment by nicolevasilevsky** [comment]
there is currently a news and events section though, with nothing posted since March. I thought we could add a couple new things so it didn't look so out of date.

![image](https://user-images.githubusercontent.com/6722114/39160569-dff8bf3e-4720-11e8-89b0-81b2721cf06a.png)

**Comment by lwinfree** [comment]
@nicolevasilevsky I can add some stuff when I update the releases page soon, but the main problem here is that we have to manually update it. I'm hoping to change that for the next gen Monarch site so we have something automated (or more automated).

**Comment by nicolevasilevsky** [comment]
Thanks @lwinfree. If you could add GCC/BOSC and ICBO, then we'll have upcoming events listed until Aug.

**Comment by lwinfree** [comment]
closed via PR https://github.com/monarch-initiative/monarch-app/pull/1585
