### ISSUE TITLE
FlyBase genotype data showing with html <up> tags instead of superscripts

### ISSUE THREAD

**Issue by sjm41** [monarch-initiative/monarch-legacy#1599]
E.g.
https://monarchinitiative.org/gene/FlyBase:FBgn0033688#genotypes
https://monarchinitiative.org/gene/FlyBase:FBgn0263933#genotypes

**Comment by kshefchek** [comment]
Thank you for your feedback! I am going to merge this with https://github.com/monarch-initiative/monarch-app/issues/754

**Comment by sjm41** [comment]
OK, thanks!
