### ISSUE TITLE
zebrafish genomic data seems to be off

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-legacy#1605]
This might be more related to dipper:

Was looking at my favorite ZFIN gene:
https://monarchinitiative.org/gene/ZFIN%3AZDB-GENE-990415-200

and I see that its unavailable for viewing:

![screen shot 2018-06-22 at 3 07 25 pm](https://user-images.githubusercontent.com/751274/41801203-ff38bab6-762d-11e8-9e09-13fdca7960e5.png)

Clicking on the link I see that this *seems* to be true:

- http://jbrowse.alliancegenome.org/jbrowse/index.html?data=data%2FDanio%20rerio&loc=25%3A15029032..15049772&tracks=All%20Genes&highlight=

But searching in JBrowse I see that this is false:

- http://jbrowse.alliancegenome.org/jbrowse/index.html?data=data%2FDanio%20rerio&loc=25%3A14928504..14957540&tracks=All%20Genes&highlight=

Also, if I check ZFIN, I see the correct location:

http://zfin.org/ZDB-GENE-990415-200

as it is on the alliance:

https://www.alliancegenome.org/gene/ZFIN:ZDB-GENE-990415-200

Probably an ingest from a bad build.

**Comment by nathandunn** [comment]
Not seeing this for other organisms.

**Comment by nathandunn** [comment]
But am seeing this for EVERY zfin gene.

**Comment by kshefchek** [comment]
Iirc this widget only communicates with mygene and jbrowse. @nathandunn I believe you wrote this widget are you able to debug?

**Comment by nathandunn** [comment]
I see.  The problem is my gene.info has the wrong position:

https://mygene.info/v3/query?q=ZFIN%3AZDB-GENE-990415-200&fields=summary%2Cgenomic_pos%2Cname%2Csymbol%2Ctaxid&species=7955 <https://mygene.info/v3/query?q=ZFIN:ZDB-GENE-990415-200&fields=summary,genomic_pos,name,symbol,taxid&species=7955>

Even though the right one is listed here, but this is out of date:

http://zfin.org/action/mapping/detail/ZDB-GENE-990415-200 <http://zfin.org/action/mapping/detail/ZDB-GENE-990415-200>

As Ensemble seems to have the incorrect one:

http://uswest.ensembl.org/Danio_rerio/Location/View?db=core;g=ENSDARG00000103379;r=25:15029041-15049781 <http://uswest.ensembl.org/Danio_rerio/Location/View?db=core;g=ENSDARG00000103379;r=25:15029041-15049781>

I’m going to close this.   Either ZFIN is ahead or behind ENSEMBL.   Either way, it will eventually get fixed.  I’ll notify folks there just in case.
