### ISSUE TITLE
Remove sidebar

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#161]
Remove the left-hand sidebar
Widen the jumbotron to the full width of the window.
Move the Monarch logo with text to top right of jumbotron

**Comment by sarahjkim** [comment]
@harryhoch @mellybelly @nlwashington @cmungall 
I tried removing the sidebar, and I ended up really really liking how it looked. My changes are currently in the remove-sidebar branch. Please check it out, and if you all like it, too, then I can merge it with master. Please note that I still will need to add the Monarch logo back to the pages if/when we actually remove the sidebar.
https://github.com/monarch-initiative/monarch-app/tree/remove-sidebar

**Comment by cmungall** [comment]
nice

![screen shot 2014-03-28 at 6 36 56 pm](https://cloud.githubusercontent.com/assets/50745/2556848/abaedf1a-b6e2-11e3-9122-f3c12f3ed905.png)

**Comment by harryhoch** [comment]
yes! +10

On Mar 29, 2014, at 3:37 AM, Chris Mungall notifications@github.com wrote:

> nice
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by nlwashington** [comment]
Yes, i think it looks great.  i think we'll want to use the full monarch initiative logo (with the words, image/logofull.png...though, i think some of the whitespace should be trimmed).

**Comment by nlwashington** [comment]
merge merge!

**Comment by sarahjkim** [comment]
I merged. Just need to add the logo to the pages now. :)

**Comment by mellybelly** [comment]
I love it!

**Comment by cmungall** [comment]
Leaving as open as we need the logo back

**Comment by harryhoch** [comment]
superseded by https://github.com/monarch-initiative/monarch-app/issues/233
