### ISSUE TITLE
Better representation of causal genes versus modifier genes

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1613]
It isn't clear at first blush what the difference is between modifier genes and causal genes. The information is there, but rows aren't even sorted. Moreover ``contributes_to`` is not the same as ``modifies``. https://monarchinitiative.org/disease/MONDO:0009061#genes

Consider having these two types of genes on two different tabs or in two separate sections.

cc: @pnrobinson, @mbrush

**Comment by kshefchek** [comment]
Please see https://monarchinitiative.org/disease/MONDO:0009061 for an updated view.  In terms of the legacy app I am hoping this is good enough, please reopen if not.
