### ISSUE TITLE
Do something better with lists of references

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#162]
Long lists of PMIDS as refs are not helpful. Can we do something clearer, perhaps a histogram of pubs by year?
![monarch-refs](https://f.cloud.github.com/assets/174707/2353702/a68a38d2-a5a7-11e3-83d4-d22ab59edcc0.png)

**Comment by cmungall** [comment]
Such as a [more] link - see #158 

For an example, see "Direct annotation" column in
http://amigo2.berkeleybop.org/cgi-bin/amigo2/amigo/search/bioentity
