### ISSUE TITLE
misalignment of counts on disease page for genes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#1628]
on disease page with genes

<img width="1767" alt="screen shot 2018-09-24 at 10 21 05 am" src="https://user-images.githubusercontent.com/796636/45957733-b29e4b80-bfe3-11e8-824a-fb56b6b5fb3c.png">

the tab has a diff count than the table.

**Comment by cmungall** [comment]
9 genes, 14 annotations

I'm not sure there is an immediate fix here, but with the new portal we don't have to stick rigidly to an annotation-centric view. I think if you are on entity S, you should first see the list of entities O1, O2, .. for each object category, and then after that drill down to annotations, cc @kltm

**Comment by kshefchek** [comment]
See related https://github.com/monarch-initiative/monarch-app/issues/1263

**Comment by jmcmurry** [comment]
It would also be more productive to first [check on alpha](https://alpha.monarchinitiative.org/disease/MONDO:0016033#gene), which has issues, but some of these things have been remedied.

**Comment by jmcmurry** [comment]
as this is a duplicate, I'm going to close.
