### ISSUE TITLE
incorrect phenotype associated with 'psoriasis'

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1631]
not sure if this is the right place to report this - on the page for 'psoriasis' in the alpha site, one of the phenotypes listed is 'confusion', which I believe must have been added as a result of text mining, and is incorrect. 

In this referenced paper (https://www.ncbi.nlm.nih.gov/pubmed/10438729), it says "However, most data are **contradictory and confusing** due to inexact definition of SPP." 

I don't think confusion is a correct phenotype for psoriasis. The source is HPOA, but I don't know what that refers to.

https://monarch-initiative.github.io/monarch-ui/disease/MONDO:0005083#phenotype

**Comment by kshefchek** [comment]
Moved to https://github.com/monarch-initiative/hpo-annotation-data/issues/167
