### ISSUE TITLE
Understanding Equivalent Ids between Monarch & EBI OLS version of records

### ISSUE THREAD

**Issue by larrybabb** [monarch-initiative/monarch-legacy#1632]
@cmungall ClinGen is using the EBI OLS service to access MONDO ids for diseases for their expert curation application (aka Variant/Gene Curation Interfaces or VCI and GCI).  One of the features that we support is the ability to submit the VCI interps to ClinVar. However, ClinVar does not allow certain disease ontologies due to their internal dependency on MedGen as a source for all disease/phenotype info. 

In any case, ClinGen has decided to define a rule for transforming MONDO ids to the "best MedGen equivalent term" in order to bridge the gap between our curated records and the clinvar submission form.

To do this, we were thinking of using the EBI OLS rest API to lookup the MONDO term associated with our variant interp record and then dig through the equivalent ids to find Orphanet, OMIM or MeSH ids (since those are acceptable to ClinVar's MedGen database).  

Here's the issue I am seeing.  When I go to the Monarch Initiative website and lookup a term like 
MONDO:0009861.  I see the following

![image](https://user-images.githubusercontent.com/959003/47017916-7c0aab00-d121-11e8-91b0-e3808117f20c.png)

There are 5 equivalent ids. 

However, when I go to EBI OLS and look this up I see the following:

![image](https://user-images.githubusercontent.com/959003/47018083-f3d8d580-d121-11e8-8bc6-9b5d4c368827.png)

The users (and I) expect there to be some consistency in what is portrayed as "equivalent" terms whether it is shown in Monarch's site or EBI OLS's site.  

The API to OLS has a Xref term that contains a MONDO:equivalent_to association which reflects what is shown in the OLS screen shot (highlighted) above, but SCIT is not even listed as an id in the Monarch side? And, four of the Monarch equivalent ids (Orphanet, Mesh, NCIT and OMIM) are not even marked as equivalent_to in OLS's record.

I realize that there's a possibility that I'm looking at different MONDO datasets, but I'm somewhat confident that it does not explain the disconnect here. 

I'm not sure we should be using the EBI OLS service to access MONDO as it seems like it might not be preserving the accurate representation of data from Monarch.

Can someone explain why these differences exist? And, how tool developers that wish to use the Monarch data should determine the proper dataset to consume?  As a tool developer we need to be confident that the data is consistent over time and between sources that we are told are "reliable" by Monarch in so much as we have put our confidence in the Monarch ontology as a definitive resource for diseases/phenotypes.

Thank you.

**Comment by cmungall** [comment]
Synchrony:

OLS usually picks up the release within 1-3 days. Monarch is an integrated release and will lag further behind.

I see we are causing some further confusion here. Historically Monarch has distributed xrefs assigned by others in the OWL version. The idea is that people use equivalence axioms in the OWL.

To further the confusion, Monarch UI is calling xrefs "Equivalent IDs". Monarch devs: this should be fixed so that this reads "cross-references"

But we should also fix on the MONDO release side. We should just filter any xrefs we disagree with (we do this for the obo release which OLS picks up). This will be done on next release for the OWL.

Sorry it's so confusing..

**Comment by larrybabb** [comment]
Thanks @cmungall.

I have to say that while it is great that you are going to fix this, I am certain that the community has been relying on the "Equivalent IDs" list in Monarch to manually correlate terms in ClinGen as well as private lab systems for commercial tools that use Monarch data.

I am not an ontologist and don't really have experience with the OWL representation, but to take the layman's perspective. It is a bit odd that Monarch has both a "References" and "Equivalent IDs" list.  with some non-scientific inspection it seems like every term in the Equivalent IDs list is in the References list. So, I look at References as a superset of xrefs, maybe obsoleted, duplicates or not directly equivalent.  The Equivalent IDs in monarch do seem like real equivalents.  

I've worked with folks at clinical labs to refine their disease terms (very big efforts) by using these "Equivalent IDs" in monarch.

I think I'm hearing (based on the above) that that work could be compromised at best or completely wrong at worst.  If OLS has it right then we really do need these views to come together and I will need to figure out how to deal with the mapping efforts we've done over the past year or more.

Any advice or guidance on how to best deal with the level of incorrectness of the equivalent id lists in monarch would be helpful.  Can you produce a list that shows the incorrect representations?

**Comment by kshefchek** [comment]
@larrybabb in reviewing our code your assessment is correct, the equivalent list are the identifiers MONDO asserts are equivalent, and the cross references are the identifiers MONDO asserts are cross references.

Chris is right in that the Monarch database will tend to lag behind the current version of MONDO by nature of our integration and QC process.  I don't think this has compromised your efforts, but perhaps a larger conversation is in order so that we're supporting your work to the best of our ability.

**Comment by cmungall** [comment]
Hold on, I think I made a mistake when describing the UI...

**Comment by cmungall** [comment]
Yes, @kshefchek is quite correct, I read the ticket too quickly while distracted at a meeting, the equivalent IDs are indeed the equivalents. The difference is purely a matter of synchrony.

The xrefs are under what is called "references". These are a bit problematic for the reasons I mentioned above, we should rename this "cross-references", and in fact there is no reason to show these for MONDO.

**Comment by larrybabb** [comment]
This is a relief. 
So my takeaway is that the equivalent ids in Monarch are correct and they will eventually show up in EBI OLS via the next MONDO update.  

I did find it a bit hard to believe that the equivalent cross references showing in the OLS screen shot above where simply an old version of MONDO, but I will look for the next update to see if these equivalent ids do end up syncing with Monarch's representation.

It would be very helpful if the community could have access to the consistent set of equivalent ids from either source. For now ClinGen is using OLS as an API solution to integrate with their applications, but the users often use Monarch's website directly to view and access terms and equivalents.  

I think there should be some way to coordinate these releases better or maybe if Monarch could offer some of the API benefits of the OLS Rest services it would then allow one source to be used - Monarch.

That would be the best solution from our standpoint.

**Comment by cbizon** [comment]
So what's the difference between exactMatch and equivalentTo?

**Comment by cmungall** [comment]
Hi @cbizon 

The monarch site shows "equivalent IDs" (which are the OWL equivalent classes axioms), and "references" (which are xref annotations).

The OWL release also includes SKOS annotations. SKOS is formally weaker than OWL logical axioms. So there may be cases where we can assert skos exact match where the concepts are not equivalent, e.g. if one is obsolete. But we don't show this on the site. There are some consumers that use these.

**Comment by cbizon** [comment]
Thanks - this fits with what I understood, (we use the exact matches & they are super useful) but I guess I'm wondering about the 'skos is formally weaker than owl logical axioms' part.  Can you explain that a bit more or point me somewhere to read about it?

**Comment by monicacecilia** [comment]
Hello, hello. 

I know that you may not have had this in mind anymore, but we want to share with you that in its current form, the now renamed 'Mappings' field on the Monarch (beta) pages ([linked example](https://beta.monarchinitiative.org/disease/MONDO:0009861)), and the 'xref' field on the OLS pages ([linked example](https://www.ebi.ac.uk/ols/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0009861)) are analogous to each other. That is, the information is the same (I don't want to use the word 'equivalent' here, hehe). 

We are in the process of switching over to the new Monarch UI, which will display this information as shown below. 

Please feel free to test the new UI, and share any thoughts and feedback with us on our [helpdesk](https://github.com/monarch-initiative/helpdesk).  

-----------------

### Monarch UI (beta)
<img width="1314" alt="Screen Shot 2020-02-05 at 4 03 42 PM" src="https://user-images.githubusercontent.com/1714621/73894377-23d54c00-4831-11ea-95e2-1021ff6d8b07.png">

### OLS website
<img width="783" alt="Screen Shot 2020-02-05 at 3 20 10 PM" src="https://user-images.githubusercontent.com/1714621/73894387-2e8fe100-4831-11ea-9654-ecf98a2c8bc1.png">

**Comment by pnrobinson** [comment]
The look and feel is great!
I found one logical bug:
https://github.com/monarch-initiative/monarch-app/issues/1655
-Peter
