### ISSUE TITLE
lack of concordance between data archive and monarch-app

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#1634]
From Varsome: "It seems though we have stumbled upon a strange situation. Browsing your website we found this https://monarchinitiative.org/disease/MONDO:0018937#genes. There are some genes associated to the MONDO:0018937 entry. But on the gene_diseases association file you provide here https://archive.monarchinitiative.org/latest/tsv/gene_associations/ there are no associations listed. Is there some other way to extract those associations between genes and diseases other than this file?"

@kshefchek @TomConlin is this an issue of the files being out of sync with their release? Or is it a closure issue (or something else).

**Comment by kshefchek** [comment]
@jmcmurry you are right, this is a difference between inferred vs direct associations for disease classes. These associations are retrievable in Biolink.
