### ISSUE TITLE
monarch team page is out of date

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1641]
https://monarchinitiative.org/page/team

Is there a plan to update this? I can help if needed.

**Comment by monicacecilia** [comment]
Hi @nicolevasilevsky - not a plan, that I know of, but if it is a simple change, it can perhaps be done. @kshefchek can assess whether it is still timely and appropriate to do it, vs. waiting for new UI. Thank you!

**Comment by kshefchek** [comment]
I'm working on it for the upcoming data release, how does https://beta.monarchinitiative.org/page/team look?

**Comment by nicolevasilevsky** [comment]
Some minor comments:
Remove Univ of Pitt from the list of participating institutions

Anne - "She will be working on environments and traits in monarch." -> She is working on environments and traits in monarch.

For OHSU, move Lilly and Brian to the bottom of that group, since they are alumni

Pitt - move to the very bottom, since everyone is an alum

LBNL - Suzi is an alum now, Eric needs a bio, give Seth the ? icon like Tomasz has, or maybe just a silhouette, like
![image](https://user-images.githubusercontent.com/6722114/54572611-c67ca600-49a5-11e9-8446-4e601fcde693.png)

**Comment by kshefchek** [comment]
Fixed with the latest release
