### ISSUE TITLE
Downloading Monarch data

### ISSUE THREAD

**Issue by rgb4268** [monarch-initiative/monarch-legacy#1644]
I download Monarch data routinely, using calls such as 
https://monarchinitiative.org/disease/MONDO:0004569.json

Lately, we have been facing frequent HTTP Timeout responses – 504 responses. I have set my read and connect timeout parameters to high. Normally, if I wait a couple of minutes, and try again, it then works.

Note: This used to work without errors even a couple of months ago.

Is there some server issue at the moment?
Thanks so much!

**Comment by kshefchek** [comment]
@git-cambridge I've made some changes that I think will improve performance.  Please let us know if you continue to have timeout issues.

Also would like to invite you to test out our (somewhat) new API at https://api.monarchinitiative.org/api
Eventually we will deprecate the https://monarchinitiative.org/{type}/{id}.json API.

**Comment by rgb4268** [comment]
Thank you kshefchek!

**Comment by rgb4268** [comment]
Do you have any idea when this deprecation will happen please?

**Comment by monicacecilia** [comment]
Hi @git-cambridge, we don't have a set date for the switch yet, but we will be sure to make announcements ahead of the change through our site and on social media. In the mean time, please let us know if you are having success or have any questions trying the new API. Feel free to open a new ticket if you do.
