### ISSUE TITLE
link to layperson blog post links to old blog site

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#1648]
The link to the blog post about the layperson terminology on the front page of Monarch links to the old blog: http://monarch-initiative.blogspot.com/2016/03/finally-medical-terminology-that.html

![image](https://user-images.githubusercontent.com/6722114/56149021-7242f280-5f60-11e9-8409-8c5754bc7cf5.png)

**Comment by monicacecilia** [comment]
Thanks for catching that, Nicole. 
In his copious amounts of free time, @kshefchek will be the one addressing this one. :bowtie: Thanks in advance, Kent.

**Comment by kshefchek** [comment]
I'm not able to locate the equivalent (or similar) blog post on https://medium.com/@MonarchInit, can someone post the link?

**Comment by nicolevasilevsky** [comment]
it is here: https://medium.com/@MonarchInit/finally-a-medical-terminology-that-patients-doctors-and-machines-can-all-understand-97ccbd97d2e8

Thanks @kshefchek

**Comment by kshefchek** [comment]
thanks!

**Comment by kshefchek** [comment]
Updated the link, let me know if there are any others I should change
