### ISSUE TITLE
analyze/phenotypes and other pages need ontology navigation

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#171]
Going between   the analyze/phenotype  results and ontobee  is confusing. Monarch should directly include ontology browsing tools.

**Comment by nlwashington** [comment]
Agreed.  @cmungall is this something @kltm could work on?

**Comment by cmungall** [comment]
Assigned.

However, ontology browsing capabilities should be built off of SciGraph, not OQ1. This places outside the 2014-06 release.

This ticket therefore now refers to some kind of interim solution that involves sending people to a more appropriate site (e.g. MGI for MP)

**Comment by kltm** [comment]
I see this is assigned to me, but I have no idea what's going on here.

**Comment by kltm** [comment]
Again, this should probably be somebody else's item.

**Comment by mellybelly** [comment]
@kltm this is about potentially reusing some of the AmiGO2 ontology browsing features. This isn't happening for October and isn't spec'd out at all yet. I'll assign to harry for UI team to specify but your input welcome.

**Comment by kltm** [comment]
@mellybelly ah yes--that makes sense then.

For A2 widget reuse, there are two possible levels: complete reuse (in which case we would need a matching server available) and widget drawing reuse (which might require some rewriting of the widget, or maybe introducing an abstraction layer).

**Comment by jmcmurry** [comment]
Something about the history of this ticket, re: milestones appears a bit off. (Eg. nowhere does it say Thanksgiving release?). In any case it is way out of scope for this week, so I'd like to move it to Christmas.

**Comment by jmcmurry** [comment]
This has been kinda overtaken by events. The ontology browser now does exist in Monarch. It is in need of improvement, but this ticket isn't the place for it, so closing.
