### ISSUE TITLE
Add asserted and orthology models to models tab

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#173]
Some MODs create assertions between a model and a disease, in particular MGI but also now data coming from ZFIN and flybase. These should be added back to the models tab (we used to have them there, but they disappeared a while back).

We could also include models based on orthology, for single-gene diseases to start with. These would be a third kind of model different from asserted models or from inferred based on phenotype. Many of these will be overlapping with the other two categories, but maybe if we use an open/close mechanism it might be helpful as a third bin on the bottom of the models tab.

ask @nlwashington for data/services details.

**Comment by nlwashington** [comment]
Chuck, since you plunked in the similarity matrix into this tab, can you additionally resurrect the old table that used to exist (in addition to your matrix).  Please go ahead and fit it under your matrix.

**Comment by harryhoch** [comment]
@cborromeo, can you look at this?

**Comment by mellybelly** [comment]
@cmungall I see asserted cell lines but not asserted models on some of the pages I am looking at. Have the asserted models been added back?

**Comment by nlwashington** [comment]
assigning this to myself as i believe that i need to review the data in disco
