### ISSUE TITLE
Minor model viewer enhancements

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#177]
Minor enhancements:
1. Use more whitespace from Left to Right, have labels not overlapping the model boxes.
2. Change the text on the model legend to indicate that darker is more similar (e.g. Score Scale => 
less similar => more similar
(or some variation)
3. Bring back the genotypes to the top row, and make them clickable to a model page.
4. Perform better highlighting as per #144 
5. Widen the colored boxes 
6. In the info box, the Input and the Output should indicate the species/source such as human/mouse. the score should be titled "similarity score" and/or match whatever nomenclature is used for no. 2.
7. consider adding term info for hover over on the term.
8. Add some kind of vertical separator, so that it is clear that the columns are the phenotypes of any given model.
9. Add model info to the item details - on long lists it would be nice to know which model you are looking at. Also, will the item details float down on the long lists? It doesn't seem to be doing this now.

**Comment by harryhoch** [comment]
deprecated based on more recent modifications.
