### ISSUE TITLE
Add graph navigation to model viewer

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#178]
It would be great if the phenotypes of the model viewer were laid out graphically, so that there was an ability to collapse/expand nodes to see the similarity across models/organisms in different bins. Currently there isn't a correlation between adjacent phenotypes. It would be better to see the nervous system ones grouped together, for example. Obviously some nodes fall into multiple different categories, but we can play around with showing them multiple times and/or highlighting those differently, etc.

**Comment by harryhoch** [comment]
Just discussed this with @cborromeo . There are non-trivial issues regarding the semantics of such changes - what does it mean to collapse the nodes, and how does it affect the notion of which models/phenotypes match? Should we recompute scores with each roll-up/drill-down? We need to make some decisions in these areas before we can implement.

**Comment by nlwashington** [comment]
I cleared the milestone.  This will take discussion.

**Comment by harryhoch** [comment]
moving to https://github.com/monarch-initiative/phenogrid/issues/128.
