### ISSUE TITLE
Gene Info problem

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#179]
Disease pages like http://localhost:8080/disease/OMIM_127750

have gene links of the form http://localhost:8080/gene/NCBIGene:2629

This leads to a call to bbop.monarch.Engine.prototype.fetchGeneInfoFromMyGene(NCBI:2629)

which seems to fail because the 
query http://mygene.info/v2/query?q=symbol:NCBI:2629&species=9606 fails.

**Comment by nlwashington** [comment]
fixed query, so it ought to fetch the right thing now.  will be seen next time the api version is incremented/cache is flushed.
