### ISSUE TITLE
identifier searches broken with colon

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#183]
i can get here:
http://localhost:8080/disease/OMIM_262500

but this is messed up:
http://localhost:8080/disease/OMIM:262500

the latter used to work and look identical to the underscore version.

this used to work, but i don't know when it broke.
@kshefchek i think your recent commit broke something here, i see that you've mucked with the bbop.monarch.Engine.prototype.getFederationNifId code.   can you fix this?

**Comment by nlwashington** [comment]
actually, it is totally messed up, it seems to totally revert to the record for OMIM:173420, no matter what id i enter with a colon.

**Comment by kshefchek** [comment]
I just pushed some code that removed my edits to bbop.monarch.Engine.prototype.getFederationNifId , I no longer see a disease cache folder, could this be part of the problem?

**Comment by nlwashington** [comment]
actually, i don't know if it was @harryhoch or @kshefchek, but one of you squashed my changes, i think.  things got funky after my commit https://github.com/monarch-initiative/monarch-app/commit/b95eb73b29c07ea6fddc22615d9a49bffa7a842f

**Comment by harryhoch** [comment]
I haven't been touching anything in those areas...

On Mar 14, 2014, at 12:26 AM, "Nicole Washington" <notifications@github.com<mailto:notifications@github.com>> wrote:

actually, i don't know if it was @harryhochhttps://github.com/harryhoch or @kshefchekhttps://github.com/kshefchek, but one of you squashed my changes, i think. things got funky after my commit b95eb73https://github.com/monarch-initiative/monarch-app/commit/b95eb73b29c07ea6fddc22615d9a49bffa7a842f

**Comment by kshefchek** [comment]
Harry just updated the css files so I'll take the blame for this one.  Perhaps a revert is in order if it's not too hard to re-update the css files?

**Comment by nlwashington** [comment]
can we revert just your changes @kshefchek?  i think it can be done with a date stamp.
http://stackoverflow.com/questions/17935750/revert-all-commits-by-a-specific-author-since-specific-time

**Comment by nlwashington** [comment]
This might be a better idea.
http://stackoverflow.com/questions/1463340/revert-multiple-git-commits?rq=1

i might try this.

**Comment by nlwashington** [comment]
somehow, it seems like kent's branch became the master, instead of being merged into the master, which may explain some things.

**Comment by nlwashington** [comment]
the colon vs underscore issue seems to be okay as of commit d98208852456f85ab4bd4a0961be8e65fc873de7, but breaks b95eb73b29c07ea6fddc22615d9a49bffa7a842f.  it appears i am the culprit, somehow.  i don't know what in the world i did.

**Comment by nlwashington** [comment]
i will delicately work on fixing this in the AM.  sorry for the confusion everyone.  i believe i merged a very old version of the api back into the repo, and since mergers are really hard to undo, i will need to revert to an old version and manually add the updates.

**Comment by kshefchek** [comment]
This looks like it could be a problem with widgets.js, when I copy the widgets.js code from:
https://github.com/monarch-initiative/monarch-app/commit/de6c7971fe5166db4ebdfe6a55ead76014bebf1d#diff-f17f2e71d9308538823ff81b4bc18617
It seems to fix it.

Instead of a git revert, is it worth considering just changing this file back and adding the xref url features code to see what could be causing these bugs?

**Comment by nlwashington** [comment]
really?  i tried https://github.com/monarch-initiative/monarch-app/commit/de6c7971fe5166db4ebdfe6a55ead76014bebf1d and that does indeed seem better, but if you think you found the solution, please commit.  i'm banging my head against the wall trying to figure out how to revert.

**Comment by frdougal** [comment]
Can we check stuff into git or is it still under repairs?

On Mar 14, 2014, at 1:07 PM, "Nicole Washington" <notifications@github.com<mailto:notifications@github.com>> wrote:

really? i tried de6c797https://github.com/monarch-initiative/monarch-app/commit/de6c7971fe5166db4ebdfe6a55ead76014bebf1d and that does indeed seem better, but if you think you found the solution, please commit. i'm banging my head against the wall trying to figure out how to revert.

**Comment by nlwashington** [comment]
yep.  commit away!
