### ISSUE TITLE
need workaround for missing disease terms in ontology

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#187]
some of the diseases that we've analyzed are not found in the ontoquest uberdisease file.  the monarch disease pages still load, but the jumbotron is blank.

we need a workaround that will lookup the labels for these in our resources.  this is the case for all orphanet diseases, but also for out-of-synch omim diseases.  also the case for kegg diseases, if we happen upon them.

for example, 
http://localhost:8080/disease/OMIM_216340 is missing a name in the jumbotron, but it is clearly in omim and our resources because it has a label (for example, in the 'related diseases' tab the top hit is itself, with the name 'Yunis-Varon Syndrome').

**Comment by mellybelly** [comment]
@ShahimEssaid may be interested in this ticket.
