### ISSUE TITLE
Get orthology calls

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#19]
we need a method to fetch orthologs given a gene id
getGeneOrthologs(sourceGeneID,targetSpecies)

I've written a view that integrates the ortholog calls from panther, and some other databases, specifically for human-to-model orthology.  It presently includes mouse and fish orthology.

see:  http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-14.json?includePrimaryData=true&q=ENSEMBL_ENSG00000160818

Is this the right strategy?  Do we want to expand this view to include all ortholog calls between all organisms, or just keep this simple with human-to-other?

**Comment by mellybelly** [comment]
This probably needs to be resolved pretty soon, but not for Jan release. 
@cmungall thoughts?

**Comment by mellybelly** [comment]
@nlwashington @kshefchek I think this can be closed? Homologs are populating...

**Comment by nlwashington** [comment]
I believe this has been implemented.
