### ISSUE TITLE
pathway tabs not functioning

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#190]
Hi All,

The pathway tabs appear to be broken as of the last commit, for example:
http://tartini.crbs.ucsd.edu/disease/OMIM_260300
http://tartini.crbs.ucsd.edu/disease/OMIM_146500

I'll take a look and see what could have broken this portion of the page.

**Comment by nlwashington** [comment]
Try clearing your cache.

**Comment by kshefchek** [comment]
I can see the tabs again...not sure what happened.
