### ISSUE TITLE
consider remove h3 header above tables in tabs

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#192]
the h3 headers within the tabs seems completely redundant with the tab label in most cases.  we would get back precious real estate if we got rid of them.  

do you (@cmungall @harryhoch @mellybelly)  have a compelling reason to keep them?

**Comment by cmungall** [comment]
I don't think so

**Comment by mellybelly** [comment]
I agree can ditch. however, the tabs don't "connect" to their pages. The tab you are on is dark gray, the ones with data white, and ones without light gray.  Perhaps would be better to make the tab you are on contiguous (e.g. same color) with the page for it?

**Comment by sarahjkim** [comment]
Should I keep the JSON download buttons in the tabs? They are currently in the Phenotypes and Related Diseases tabs.

**Comment by nlwashington** [comment]
naw, i think the json button in the jumbotron is sufficient for now.
