### ISSUE TITLE
search by id doesn't work

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#195]
i tried searching by id with "ORPHANET:2790", and it doesn't work...it returns 0 results.

note that http://tartini.crbs.ucsd.edu/disease/ORPHANET_2790 has phenotypes.

the search box in the header ought not to be restricted to just ontology terms...i think it should match on many things in our system.

**Comment by nlwashington** [comment]
@harryhoch  or @cmungall,  i take it search by id isn't being put into this release?

**Comment by harryhoch** [comment]
Not that I know of.

On 9 Jun 2014, at 12:39 PM, Nicole Washington notifications@github.com wrote:

> @harryhoch or @cmungall, i take it search by id isn't being put into this release?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by cmungall** [comment]
What do you mean by search by ID. Do you mean partial matches, etc? IDs in fields other than primary key?

It would be simple to reroute a search where there term is (ORPHANET|OMIM|MIM|..):nnn to the relevant page.

**Comment by nlwashington** [comment]
well, right now in the "search" box at the top of our website, i get no matches when i search for "ORPHANET:2790".  i get no autocomplete matches and if i hit enter anyway, i get a stacktrace.  i think i should be able to search for any ontology term by id, and it should route me to the correct page.

**Comment by cmungall** [comment]
Ah yes, the autocomplete would require upstream changes

**Comment by cmungall** [comment]
IDs searches now get rerouted for a subset of prefixes.

For unmatched prefixes there is a semi-graceful (ie no stacktrace) page /unknown/PREFIX:FRAGMENT that just fails with the generic error.

**Comment by cmungall** [comment]
Removing from release. Upstream fix in vocabulary services still required for optimal behavior

**Comment by mellybelly** [comment]
@ccondit @kshefchek I think we might be ready to enable this with the new scigraph services?

**Comment by kshefchek** [comment]
This should work once we switch back to geoffrey.

**Comment by ccondit** [comment]
There's no implementation to autocomplete on CURIEs at this point. Is this a requirement for SciGraph?

**Comment by kshefchek** [comment]
Looks like it only works for gene IDs with the NCBIGene: prefix, I thought it might work for everything.

**Comment by nlwashington** [comment]
perhaps the autocomplete service isn't what we need to use for this; i doubt people will be trying to autocomplete on a number... most likely they will want to paste in an id and have it match something exactly...that would just be a graph lookup by id, right?

**Comment by ccondit** [comment]
Yes. Id lookup should work with any registered CURIE. This should work for both /vocabulary and /graph services.

**Comment by kshefchek** [comment]
If we pattern match on a curie should I only run the search on vocabulary/id?  I'm getting some strange results when running it in vocabulary/search, for example:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/search/HP:0000118?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&category=disease

**Comment by kshefchek** [comment]
Actually reading the ticket...it looks like we would want to enter an ID and redirect to the correct page?  That should be doable.  I'll update the code in the webapp.

**Comment by ccondit** [comment]
@kshefchek that geoffrey /vocabulary/search issue should be fixed.
