### ISSUE TITLE
gracefully deal with owlsim server downtime

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#198]
we should be able to handle downtime from the owlsim server, but right now the entire page says 'something went wrong'

much of the rest of the webpages in monarch should be able to render without owlsim server running.  the data for the remaining good tabs should be rendered, and those where it failed could have the 'something went wrong, please refresh' error.

for example:

FETCHING: http://owlsim.crbs.ucsd.edu//searchByAttributeSet data={"a":"HP:0001324","target":"OMIM","limit":1}
RESULT: [object Object]
STATUS: 502
Status != 200. ExchangeObj source= ({connection:sun.net.www.protocol.http.HttpURLConnection:http://owlsim.crbs.ucsd.edu//searchByAttributeSet?a=HP%3A0001324&target=OMIM&limit=1, done:true, content:"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/searchByAttributeSet\">GET&nbsp;/searchByAttributeSet</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at owlsim.crbs.ucsd.edu Port 80</address>\n</body></html>\n", contentBytes:{}})
Throwing error:[object Object]
  :type=fetchUrl
  :url=http://owlsim.crbs.ucsd.edu//searchByAttributeSet
  :status=502
  :message=error fetching http://owlsim.crbs.ucsd.edu//searchByAttributeSet response code=502 src=({connection:sun.net.www.protocol.http.HttpURLConnection:http://owlsim.crbs.ucsd.edu//searchByAttributeSet?a=HP%3A0001324&target=OMIM&limit=1, done:true, content:"<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>502 Proxy Error</title>\n</head><body>\n<h1>Proxy Error</h1>\n<p>The proxy server received an invalid\r\nresponse from an upstream server.<br />\r\nThe proxy server could not handle the request <em><a href=\"/searchByAttributeSet\">GET&nbsp;/searchByAttributeSet</a></em>.<p>\nReason: <strong>Error reading from remote server</strong></p></p>\n<hr>\n<address>Apache/2.2.15 (CentOS) Server at owlsim.crbs.ucsd.edu Port 80</address>\n</body></html>\n", contentBytes:{}})

**Comment by cmungall** [comment]
It would be non-trivial to have this kind of partial fail mode. For example, when fetching object X for this first time, if component Y can't be reached, then the cached object for X should include a kind of stub that indicates that Y is unavailable. Subsequent accesses to the cached X should retry retrieval of Y such that the uncached state of Y does not persist.

For now the best strategy is to ensure uptime of all services. Hopefully production will have higher uptime than beta.

In the future we can break things down more into their subcomponents. This will also allow us to be more asynchronous - e.g. each tab loads separately

**Comment by mellybelly** [comment]
moving to july

**Comment by jmcmurry** [comment]
Not sure where this stands, but because it seems both valuable and hard, I'm moving to wishlist.
