### ISSUE TITLE
search results show term info as undefined

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#203]
search results show terms that are listed as undefined. Will we have this info available in the release?
![slide1](https://f.cloud.github.com/assets/796636/2528275/dbbac5f6-b50d-11e3-9170-d7708e471e95.png)

**Comment by cmungall** [comment]
Dependent on https://support.crbs.ucsd.edu/browse/NIF-10531

**Comment by mellybelly** [comment]
currently not showing undefined (better) but not pulling info (so leaving open)
