### ISSUE TITLE
new icon buttons for homepage

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#207]
Attached are the pngs for the four boxes and also an arrow, should we decide to use this. 
![arrow](https://cloud.githubusercontent.com/assets/796636/2550714/324dbfd0-b686-11e3-82bb-edf56957f0f8.png)
![diseasesicon](https://cloud.githubusercontent.com/assets/796636/2550715/3251f7ee-b686-11e3-8b86-fe712cb286fb.png)
![eyeicon](https://cloud.githubusercontent.com/assets/796636/2550716/32565f78-b686-11e3-8461-36f4b5784225.png)
![genesicon](https://cloud.githubusercontent.com/assets/796636/2550717/32571b66-b686-11e3-816f-9e26b0b4e086.png)
![modelsicon](https://cloud.githubusercontent.com/assets/796636/2550718/325a147e-b686-11e3-9fbd-e7224b5d68be.png)

Lets first try simply replacing the four boxes with these icons, and using the following text next to each:
Diseases: Learn about diseases
Models: Find models of disease
Genes: Identify variants
Phenotypes: Explore phenotypes

**Comment by mellybelly** [comment]
ok here is some hover over text for the new homepage arrows:
top arrow: Diseases are described with phenotypes
right arrow: Phenotype profiles are shared across species
bottom arrow: Models suggest candidate genes
left arrow: Diseases relate to genetic variation

**Comment by harryhoch** [comment]
works for me. 
On Mar 28, 2014, at 11:17 PM, Melissa Haendel notifications@github.com wrote:

> ok here is some hover over text for the new homepage arrows:
> top arrow: Diseases are described with phenotypes
> right arrow: Phenotype profiles are shared across species
> bottom arrow: Models suggest candidate genes
> left arrow: Diseases relate to genetic variation
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by mellybelly** [comment]
Hi Sarah, 
So we are hoping we can get a sneak peek out this week. Can you prioritize the home page? 

Harry- would like feedback but I think that the colors for the entity pages might be better if they were a bit bolder than now. we just need some pizazz. We also need the monarch initiative logo bigger and with the label on the homepage, maybe all the pages? What color should the homepage be?

**Comment by harryhoch** [comment]
Melissa:

Colors are hard. I think we want a common color scheme throughout the site in terms of background colors. Perhaps we could use some of the alternative colors that Skillen suggested, with the logo in a different color on each of the page types?  The main font - “Phenotype”, etc. - could change accordingly to make the connection. 

Looking at the Monarch colors that Skillen suggested, I like the Blue (#44A293), Orange (#EA763B), Dark Red (#461313), or Red (#DD3835) for the logo and/or text. If you want background colors, I would stick to the Gray (#E5E5E5) or perhaps the light blue (#A4D6D4). I’d have to see it to say any more than that…

-harry

On Apr 1, 2014, at 8:02 PM, Melissa Haendel notifications@github.com wrote:

> Hi Sarah, 
> So we are hoping we can get a sneak peek out this week. Can you prioritize the home page?
> 
> Harry- would like feedback but I think that the colors for the entity pages might be better if they were a bit bolder than now. we just need some pizazz. We also need the monarch initiative logo bigger and with the label on the homepage, maybe all the pages? What color should the homepage be?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by sarahjkim** [comment]
@mellybelly I finished the front page. Please take a look and let me know if you'd like anything changed.

**Comment by cmungall** [comment]
Hold on, it's not deploying to tartini, let me investigate….

**Comment by cmungall** [comment]
OK, that's it. There was a big queue of stuff in Jenkins

**Comment by harryhoch** [comment]
Sarah, this looks really nice. What happened to the Monarch logo?

On Apr 2, 2014, at 3:25 PM, Sarah Kim notifications@github.com wrote:

> @mellybelly I finished the front page. Please take a look and let me know if you'd like anything changed.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by mellybelly** [comment]
we are getting there...
can we center the main text at the top, remove the subtext "Semantically describing this data enables novel computational methods to identify previously unknown relationships and suggest novel biological insights. Our goal is to provide usable tools that will help biomedical researchers harness the power of these computational approaches." 

add the monarch logo (with the monarch initiative text associated).

Also - there is a lot of whitespace left to right. can we add some kind of vertical squeezing to the layout? this is true on all pages. ideas here?

**Comment by mellybelly** [comment]
Here are a few new pngs to play with for homepage. 
new icon for models, blackened dna icon, and text added back. one image has shadows, other doesn't. see which you like better.
![homepage-mockupv4noshadow](https://cloud.githubusercontent.com/assets/796636/2616375/ed7323ac-bc05-11e3-89a4-c131062f4317.png)
![homepage-mockupv4](https://cloud.githubusercontent.com/assets/796636/2616376/ed76b31e-bc05-11e3-90ed-52fdac5b2a1a.png)

**Comment by mellybelly** [comment]
slightly updated version, use this one.
![homepage-mockupv4](https://cloud.githubusercontent.com/assets/796636/2616670/5f5c675a-bc09-11e3-8644-d5404bb871c5.png)
