### ISSUE TITLE
Genes in model viewer that are in pathways should be highlighted

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#208]
We need some way of knowing in the model viewer when a phenotypically similar gene is annotated to a pathway. Basically I want to know how do the most phenotypically similar genes relate to one another? Right now I have to search KEGG outside the system, this should be doable inside our system.

Even better - anywhere in the system- be able to select a set of entities (genes, phenotypes, diseases, models), infer their related genes for the latter three, and display using cytoscape plugin any relationships between them.

**Comment by harryhoch** [comment]
Let’s discus. Might make sense to rol our own instead of using cytoscape
On Mar 28, 2014, at 4:57 PM, Melissa Haendel notifications@github.com wrote:

> We need some way of knowing in the model viewer when a phenotypically similar gene is annotated to a pathway. Basically I want to know how do the most phenotypically similar genes relate to one another? Right now I have to search KEGG outside the system, this should be doable inside our system.
> 
> Even better - anywhere in the system- be able to select a set of entities (genes, phenotypes, diseases, models), infer their related genes for the latter three, and display using cytoscape plugin any relationships between them.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by nlwashington** [comment]
As for the first issue (highlighting genes in the same pathway), @mellybelly  is this necessary for the June release?

**Comment by harryhoch** [comment]
Not yet implemented, but moving discussion to https://github.com/monarch-initiative/phenogrid/issues/132
