### ISSUE TITLE
no genotypes showing up on phenotype page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#209]
For example
http://tartini.crbs.ucsd.edu/phenotype/HP_0000316
with 715 diseases related, there should be related genes/genotypes.

**Comment by cmungall** [comment]
Caused by this:
https://support.crbs.ucsd.edu/browse/NIF-10528

**Comment by nlwashington** [comment]
hmmm, still no genes or genotypes showing up.  Genes should at least be inferred from the diseases, and possibly from genotypes in the models.  @kshefchek can you check on this?

**Comment by kshefchek** [comment]
I can see 39 models when I run the app locally, @cmungall could you clear the phenotype cache? I think that should fix it.

**Comment by nlwashington** [comment]
yes, this is fixed on my localhost.
