### ISSUE TITLE
add genes landing page text

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#213]
Highlighted genes
EPHB2 (human)
BLOC1S3 (human)
TWIST1 (human)
(add) Shh (mouse) : http://tartini.crbs.ucsd.edu/gene/NCBIGene:20423

Gene set highlight: Genes involved in neural crest development:
Sema3c (mouse) http://tartini.crbs.ucsd.edu/gene/NCBIGene:20348
nrg1 (zebrafish) http://tartini.crbs.ucsd.edu/gene/NCBIGene:796461  
(this doesn't resolve right now)
Bmpr1a (mouse) http://tartini.crbs.ucsd.edu/gene/NCBIGene:12166
RALDH2 (human) http://tartini.crbs.ucsd.edu/gene/NCBIGene:8854
(this doesn't resolve right now)

**Comment by sarahjkim** [comment]
Does the comment on #211 apply here about not putting the species between the parenthesis?

**Comment by cmungall** [comment]
No it doesn't, the genes truly are specific-specific here. Kepp as is.
