### ISSUE TITLE
disclaimer for comparisons only using "abnormal" phenotypes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#214]
we need to make a note/disclaimer somewhere that says that we only take into consideration "abnormal" phenotypes when doing comparisons or search.  this is not obvious to anyone (even ourselves).  

this should be indicated both on the analyze page, as well as on the related diseases tab.

**Comment by mellybelly** [comment]
replaced by #231

**Comment by mellybelly** [comment]
actually #231 doesn't take care of the related diseases tab.

**Comment by sarahjkim** [comment]
Is there a particular text you'd like me to change/add to the related diseases tab?

**Comment by mellybelly** [comment]
How about "Comparisons are based on abnormal phenotypes" ?
