### ISSUE TITLE
disclaimers

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#216]
do we need some kind of disclaimer saying that we aren't a physician and the site is provided for research purposes only?  i've seen legal c.y.a. language like this on other sites.

**Comment by harryhoch** [comment]
Seems like that would be a good idea.
On Mar 29, 2014, at 6:25 AM, Nicole Washington notifications@github.com wrote:

> do we need some kind of disclaimer saying that we aren't a physician and the site is provided for research purposes only? i've seen legal c.y.a. language like this on other sites.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by kltm** [comment]
It would be best to actually run it by the legal department (or whoever would best handle it) for the hosting institution, rather than trying to apply somebody else's disclaimer/notice--if push comes to shove, you're going to need that okay from the beginning.

**Comment by harryhoch** [comment]
Agree with @kltm. NIF and Biogrid (for example), have quite detailed terms of use pages with significant content. This will require some careful thought and consultation with appropriate counsel.

**Comment by jmcmurry** [comment]
While not the most exciting task, this is really important especially as we move toward more buzz. I am willing to pick up the thread but need to know:
A) Who the appropriate general counsel members are to contact at OHSU
B) Whether when I speak with OHSU counsel, whether I should advocate that LBL, UPitt (others?) general counsel be summoned simultaneously or in succession. What approach has worked best so far?

Broader "terms of use" are outside the scope of this ticket and may take months to get through. Let's tackle this disclaimer issue first.

@mellybelly please advise. Thanks.

NIF and BioGrid were mentioned, but I think our use case calls for disclaimers closer to those seen on portals like WebMD. We will see what counsel say.
- Based on WebMD
  
  > The Site Does Not Provide Medical Advice
  > The contents of the MONARCH Site, such as text, graphics, images, information obtained from MONARCH licensors, and other material contained on the MONARCH ("Content") are for informational purposes only. The Content is not intended to be a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read on the MONARCH Site.
  > If you think you may have a medical emergency, call your doctor or 911 immediately. WebMD does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on the Site. Reliance on any information provided by MONARCH, MONARCH employees, others appearing on the Site at the invitation of MONARCH, or other visitors to the Site is solely at your own risk.
  > The Site may contain health- or medical-related materials that are sexually explicit. If you find these materials offensive, you may not want to use our Site.
- Based on NIF
  
  > YOUR USE OF THE MONARCH SITES, SERVICES OR ANY WEB SITE TO WHICH THEY ARE LINKED IS AT YOUR SOLE RISK. THE MONARCH SITES/SERVICES AND THEIR CONTENT ARE PROVIDED FOR USE ON AN "AS IS" AND "AS AVAILABLE" BASIS. MONARCH MAKES NO REPRESENTATIONS OR WARRANTIES WITH RESPECT TO THE MONARCH SITES/SERVICES OR THEIR CONTENTS AND HEREBY DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT RELATING TO THE MONARCH SITES/SERVICES, THEIR CONTENT OR ANY WEB SITE TO WHICH THEY ARE LINKED.
  > 
  > NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM MONARCH OR THROUGH OR FROM THE MONARCH SITES/SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THE TERMS OF USE. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, MONARCH STRONGLY RECOMMENDS THAT YOU INDEPENDENTLY VERIFY ANY MEDICAL TREATMENT INFORMATION UPON WHICH YOU CHOOSE TO RELY.
- Based on BioGrid's
  
  > EACH USER'S USE OF THE MONARCH SITES IS AT HIS OR HER SOLE RISK. THE MONARCH SITES ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS AND THE MONARCH CONSORTIUM ASSUMES NO RESPONSIBILITY FOR THE TIMELINESS, DELETION, OR MIS-DELIVERY. EACH USER WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO HIS OR HER COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL. THE MONARCH CONSORTIUM EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. SPECIFICALLY, THE MONARCH CONSORTIUM MAKES NO WARRANTY THAT (i) THE MONARCH SITES OR ANY SERVICE THEREON WILL MEET YOUR REQUIREMENTS, (ii) ANY USER ACCESS WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, (iii) THE QUALITY OF ANY CONTENT, PRODUCTS, SERVICES, INFORMATION OR OTHER MATERIAL OBTAINED BY ANY USER WILL MEET HIS OR HER EXPECTATIONS, AND (iv) ANY ERRORS IN THE SOFTWARE WILL BE CORRECTED. EXCLUDING ONLY DAMAGES ARISING OUT OF THE MONARCH CONSORTIUM'S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT, THE MONARCH CONSORTIUM SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA OR OTHER INTANGIBLE LOSSES (EVEN IF THE MONARCH CONSORTIUM HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), RESULTING FROM ANY USER'S USE OR INABILITY TO USE ANY BioGRID SITES OR SERVICES THEREON; THE COST OF PROCUREMENT OF SUBSTITUTE SERVICES; UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA; STATEMENTS OR CONDUCT OF ANY THIRD PARTY ON THE MONARCH SITES; OR ANY OTHER MATTER RELATING TO THE MONARCH SITES. IN NO EVENT SHALL THE MONARCH CONSORTIUM's TOTAL CUMULATIVE LIABILITY TO ANY USER OR OTHER PARTY UNDER THESE TERMS OF SERVICE OR OTHERWISE EXCEED $1,000.00. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES OR THE LIMITATION OR EXCLUSION OF LIABILITY FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES. ACCORDINGLY, SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. NOTHING HEREIN SHALL BE DEEMED TO CREATE AN AGENCY, PARTNERSHIP, JOINT VENTURE, EMPLOYEE-EMPLOYER OR FRANCHISOR-FRANCHISEE RELATIONSHIP OF ANY KIND BETWEEN THE MONARCH CONSORTIUM AND ANY USER OR OTHER PERSON OR ENTITY NOR DO THESE TERMS OF SERVICE EXTEND RIGHTS TO ANY THIRD PARTY. AS NOTED ABOVE, THE  MONARCH CONSORTIUM DOES NOT AND CANNOT CONTROL THE ACTIONS OF MONARCH SITE USERS, VISITORS OR LINKED THIRD PARTIES. WE RESERVE THE RIGHT TO REPORT ANY MALFEASANCE THAT COMES TO OUR ATTENTION TO THE APPROPRIATE AUTHORITIES. WE DO NOT GUARANTEE CONTINUOUS UNINTERRUPTED OR SECURE ACCESS TO  MONARCH SITES. OPERATION OF  MONARCH SITES MAY BE SUBJECT TO INTERFERENCE FROM NUMEROUS FACTORS OUTSIDE OUR CONTROL. FURTHER, SCHEDULED AND PREVENTIVE MAINTENANCE AS WELL AS REQUIRED AND EMERGENCY MAINTENANCE WORK MAY TEMPORARILY INTERRUPT SERVICES OR ACCESS TO THE WEBSITE. THE DISCLAIMERS OF WARRANTY AND LIMITATIONS OF LIABILITY APPLY, WITHOUT LIMITATION, TO ANY DAMAGES OR INJURY CAUSED BY THE FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, ALTERATION OF OR USE OF ANY ASSET, WHETHER ARISING OUT OF BREACH OF CONTRACT, TORTIOUS BEHAVIOUR, NEGLIGENCE OR ANY OTHER COURSE OF ACTION BY THE  MONARCH CONSORTIUM.
