### ISSUE TITLE
autocomplete on a disease shows no results

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#218]
search for Gaucher's disease, choose the last autocomplete entry (just Gaucher's disease (disease))

http://stage.monarchinitiative.org/search/Gaucher's%20disease

Presumably all diseases in the autocomplete should have a page in the system? Is this because its a DO term but has no mapping to OMIM?
This one is DOID_1926

**Comment by nlwashington** [comment]
nope, i can see it here:
http://stage.monarchinitiative.org/disease/DOID_1926

i bet there's some funkiness with the apostrophe in this case.

**Comment by nlwashington** [comment]
closing, as probably related to #287.
