### ISSUE TITLE
odd navigation on phenotype page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#220]
So if you are on this phenotype page for obesity:
http://tartini.crbs.ucsd.edu/phenotype/HP_0001513
there are three tabs, overview, disease, and genotype.
diseases are as expected, but nowhere does it say that on the "genotypes" tab that these are mouse models. A user might be expecting human genotypes here otherwise.
Perhaps relabel this tab Models? 
@nlwashington @harryhoch what do you think? On the disease page we have a "similar models" tab, but I suspect that here on the phenotype page where the phenotype isn't really unique to any species, that we'll want eventually want to show human variants related to a phenotype as separate from model genotypes.

**Comment by harryhoch** [comment]
I agree - the tab should be called “models”.  They aren’t really genotypes - those mice are mice that have specific targeted mutations, not definitive genotypes. 

Defining these terms more clearly might be a reasonable idea.  “Genotype” is particularly a terms that is used far too loosely..

-harry

On Apr 1, 2014, at 8:47 PM, Melissa Haendel notifications@github.com wrote:

> So if you are on this phenotype page for obesity:
> http://tartini.crbs.ucsd.edu/phenotype/HP_0001513
> there are three tabs, overview, disease, and genotype.
> diseases are as expected, but nowhere does it say that on the "genotypes" tab that these are mouse models. A user might be expecting human genotypes here otherwise.
> Perhaps relabel this tab Models? 
> @nlwashington @harryhoch what do you think? On the disease page we have a "similar models" tab, but I suspect that here on the phenotype page where the phenotype isn't really unique to any species, that we'll want eventually want to show human variants related to a phenotype as separate from model genotypes.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300
