### ISSUE TITLE
issues with OMIM:614871 disease page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#221]
http://stage-monarch.monarchinitiative.org/disease/OMIM_614871

this page has some strange things happening.
1.  there's no name in the jumbotron
2.  there's no class hierarchy being shown from the ontology
3.  there's multiple diseases shown on the "phenotypes" tab.  why are they showing up?  which are correct, or all?  if this is a grouping class, why aren't the relationships showing up in the ontology?

**Comment by mellybelly** [comment]
I'm seeing problems on other omim pages, that I have linked to from elsewhere:
http://stage.monarchinitiative.org/disease/OMIM_266910

**Comment by harryhoch** [comment]
@cmungall  can we fix this before release today?

**Comment by cmungall** [comment]
No, Need to update merged disease ontology. For now all we can do is place a notice if we have no metadata

**Comment by nlwashington** [comment]
hopefully this will get addressed with https://support.crbs.ucsd.edu/browse/LAMHDI-338

**Comment by nlwashington** [comment]
The two omim links mentioned above now work.  
Note that there are differences between stage and tartini.

Tartini has phenotypes and matches tabs that are enabled.
Stage only has "related diseases".

@cmungall i believe a recent change i made in master branch enables the matches tab.  but, i don't understand the difference on the phenotypes tab, unless there is a big data difference between them (seeing as stage runs off of prod data, and tartini runs off of beta data)

**Comment by nlwashington** [comment]
this seems fixed after commit b201f17
