### ISSUE TITLE
Update release info page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#225]
Updated text for the release page. @nlwashington @cmungall  @harryhoch please edit. We need to decide if KEGG viewer will be added in by tomorrow.

Sneek Peek Release (April 2014)

We welcome user testers! please use the feedback button (link), email info@monarchinitiative.org, or use the git tracker(link) to relay your suggestions. 

Why are we calling this a Sneek Peek? Because we plan to incrementally add functionality over the next few months based on your feedback. 

The Sneek Peek currently includes data from human, mouse, and zebrafish. The system allows comparison of phenotype profiles (either a disease related set or a user-defined set) across organisms using the OWLsim algorithm and a suite of integrated phenotype, and disease ontologies, all of which have been enhanced for this purpose.

Functionality includes the ability to explore the relationships between models, diseases, genes, and phenotypes, the ability to compare phentoypes across models to investigate the degree to which they recapitulate a disease, and a KEGG Pathway view by which one can see how the phenotypes related to a given disease are distributed in a network.

Services (link) include an API to retrieve the models most related to any given set of phenotypes, as well as an API call for an annotation sufficiency score for the given set. These services are being used within Phenotips and by the NIH Undiagnosed Disease Program to compare human undiagnosed disease phenotype profiles against model systems to aid in prioritization of gene candidates.

Monarch 1.0 Release (anticipated July 2014)
In our first official release we plan to include numerous additional data sources, such as D. melanogaster, C. elegans, rat, yeast, ClinVar, Undiagnosed Disease Program phenotypes, Bgee comparative gene expression, and more.

New functionality in the user interface will include JBrowse integrated genome views with genotype and phenotype data, and the ability to query gene expression data via anatomy to prioritize phenotype similarity results based on co-expression/tissue specificity.
New services will include an ID resolution service over all data and ontology sources and the ability to query on any group of semantic entities in the system (such as genes, diseases, anatomy, etc).

**Comment by harryhoch** [comment]
Looks reasonable. We also need to discuss the status of the model viewer. 

I would argue against saying as much about the July release.  Suggest  cutting out the paragraph that begins.. “New functionality…..”

-harry
On 3 Apr 2014, at 11:39 AM, Melissa Haendel notifications@github.com wrote:

> Updated text for the release page. @nlwashington @cmungall @harryhoch please edit. We need to decide if KEGG viewer will be added in by tomorrow.
> 
> Sneek Peek Release (April 2014)
> 
> We welcome user testers! please use the feedback button (link), email info@monarchinitiative.org, or use the git tracker(link) to relay your suggestions.
> 
> Why are we calling this a Sneek Peek? Because we plan to incrementally add functionality over the next few months based on your feedback.
> 
> The Sneek Peek currently includes data from human, mouse, and zebrafish. The system allows comparison of phenotype profiles (either a disease related set or a user-defined set) across organisms using the OWLsim algorithm and a suite of integrated phenotype, and disease ontologies, all of which have been enhanced for this purpose.
> 
> Functionality includes the ability to explore the relationships between models, diseases, genes, and phenotypes, the ability to compare phentoypes across models to investigate the degree to which they recapitulate a disease, and a KEGG Pathway view by which one can see how the phenotypes related to a given disease are distributed in a network.
> 
> Services (link) include an API to retrieve the models most related to any given set of phenotypes, as well as an API call for an annotation sufficiency score for the given set. These services are being used within Phenotips and by the NIH Undiagnosed Disease Program to compare human undiagnosed disease phenotype profiles against model systems to aid in prioritization of gene candidates.
> 
> Monarch 1.0 Release (anticipated July 2014)
> In our first official release we plan to include numerous additional data sources, such as D. melanogaster, C. elegans, rat, yeast, ClinVar, Undiagnosed Disease Program phenotypes, Bgee comparative gene expression, and more.
> 
> New functionality in the user interface will include JBrowse integrated genome views with genotype and phenotype data, and the ability to query gene expression data via anatomy to prioritize phenotype similarity results based on co-expression/tissue specificity.
> New services will include an ID resolution service over all data and ontology sources and the ability to query on any group of semantic entities in the system (such as genes, diseases, anatomy, etc).
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by mellybelly** [comment]
That sounds fine Harry, Sarah please go ahead with that.
