### ISSUE TITLE
Fix model page population

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#235]
The models pages doesn't seem to be populating properly, see
http://stage-monarch.monarchinitiative.org/model/MGI:5450464
for example. 
we should see asserted models in the table, as well as phenotypically similar diseases, as well as models that are similar.

needs genes and alleles tab too.

**Comment by cmungall** [comment]
We discussed today.
- Bryan will get stuff into the integrated view
- Chris will figure out how to better integrate gene grid and model table (harder than I thought will have to punt)
- Chris will change tab to be "matches" (done)
- Need some kind of signage (todo)

**Comment by mellybelly** [comment]
@kshefchek this was assigned to you, but I'm thinking its a punt till july problem?

**Comment by nlwashington** [comment]
see related #422

**Comment by nlwashington** [comment]
i have broken this down into new specific tickets:
https://github.com/monarch-initiative/monarch-app/issues/550
https://github.com/monarch-initiative/monarch-app/issues/551
https://github.com/monarch-initiative/monarch-app/issues/519
