### ISSUE TITLE
autocomplete on disease leads to no results

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#236]
try autocompleting on 'obesity (disease)'

**Comment by cmungall** [comment]
Works on beta/tartini, no results on stage/production, correct?

**Comment by mellybelly** [comment]
obesity (disease) doesn't seem to be showing up in autocomplete on tartini. will check others, autocomplete very slow on tartini
meaning yes, problem on stage, not on tartini

**Comment by cmungall** [comment]
@jingjingbic, there is a bug with production OQ

http://services.monarchinitiative.org/ontoquest/concepts/search/obesity

Returns with 200 (success), but the message is:

<failure><message>java.lang.NullPointerException</message></failure>

**Comment by mellybelly** [comment]
Is this fixed? I don't seem to be able to autocomplete on obesity as a disease by itself anymore, and see same autocomplete results on all tiers.

**Comment by nlwashington** [comment]
this appears to be working on tartini and stage.  closing.
