### ISSUE TITLE
models retrieval giving proxy error

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#237]
clicking on a model in the table view, even when it is a mouse, for example:
http://stage.monarchinitiative.org/model/MGI:3833851
is giving me a proxy error

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>

<h1>Proxy Error</h1>

<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/model/MGI:3833851">GET&nbsp;/model/MGI:3833851</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>

<hr>

<address>Apache/2.2.15 (CentOS) Server at stage.monarchinitiative.org Port 80</address>
</body></html>

**Comment by cmungall** [comment]
Who knows, seems to be fixed now
