### ISSUE TITLE
No way to update list on "Analyze phenotypes"

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#243]
Often times you may wish to change your query list of phenotypes and see how this changes your results. The back button erases the entry, and there doesn't seem to be a way to update them in the Analyze phenotypes results page.

**Comment by mellybelly** [comment]
Harry, please comment on whether this is punt until july release item and/or assign.

**Comment by harryhoch** [comment]
Yes, I think it's a punt.

**Comment by cmungall** [comment]
I think this is more important now that we have other entry points to search-by-profile (aka analyze phenotypes).

For example, if I start here
http://127.0.0.1:8282/gene/NCBIGene:64436

Click on the phenotype tab,
Then click "analyze phenotypes"

I end up in the table tab of the analyze phenotypes page. I see a list of mixed results - mouse, human. I would at least like to be able to refine my search by species. But the "query" tab is unaware of how we got there.

Ideally on landing on this page we could incrementally add phenotypes and remove them.

@kltm and @sarahjkim may be able to tackle this together

**Comment by kshefchek** [comment]
Looks like I've introduced a bug when updating the gene object, the analyze phenotypes link contains a misformated taxon id: target_species=NCBITaxon:10090

I can update the code to include the right taxon id, or should I leave out the target_species option?

**Comment by nlwashington** [comment]
this should probably be fixed downstream but if you strip off the "NCBITaxon:", it should work.

**Comment by kshefchek** [comment]
Just had to change taxon.id to taxon.label in the api, this is fixed now and the grid tab should also show results.

**Comment by harryhoch** [comment]
fixed with fix to 484
