### ISSUE TITLE
Disable ZP pages until ZP disaster resolved

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#246]
https://code.google.com/p/bio-ontology-zp/issues/detail?id=4

**Comment by nlwashington** [comment]
@cmungall we should come up with a plan for fixing this in a coordinated (disco and front-end) for this release.

**Comment by nlwashington** [comment]
see jira https://support.crbs.ucsd.edu/browse/LAMHDI-353 and https://support.crbs.ucsd.edu/browse/LAMHDI-352

**Comment by nlwashington** [comment]
i am closing this issue (as they are turned off) and opening a new one for the reinstatement for june release #356.
