### ISSUE TITLE
Model landing page content

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#248]
Model spotlight: Blue Meanie Mouse
A mutation in Cc2d2a (coiled-coil and C2 domain containing 2A) was identified in an ENU screen for recessive cardiovascular development phenotypes in Dr. Cecilia Lo's laboratory, NHLBI Cardiovascular Development Consortium (CvDC). Homozygotes demonstrate cardiovascular defects and congenital heart defects ( such as transposition of the great arteries, double outlet right ventricle, and tricuspid atresia; Preaxial digit duplication/polydactyly; duplex and cystic kidneys; cleft palate; and eye defects. 
http://stage.monarchinitiative.org/genotype/MGI:5313509

Highlighted models:
Zebrafish chd7 Morpholino knockdown: http://stage.monarchinitiative.org/genotype/MONARCH:ZDB-GENO-960809-7_ZDB-GENE-070912-179_ZDB-MRPHLNO-111012-1_
Zebrafish mib<ta52b>/mib<ta52b>
http://stage.monarchinitiative.org/genotype/ZFIN:ZDB-GENO-980202-1107
Zebrafish cald1<MO1-cald1 (4 ng)>
http://stage.monarchinitiative.org/genotype/MONARCH:ZDB-GENO-030619-2_ZDB-GENE-090313-229_ZDB-MRPHLNO-090413-1_4_ng
Mouse Tgfb2<tm1Doe>/Tgfb2<tm1Doe> [involves: 129P2/OlaHsd \* Black Swiss]
http://stage.monarchinitiative.org/genotype/MGI:2668213
Mouse Vegfa<tm1Pec>/Vegfa<tm1Pec> [involves: 129S1/Sv \* 129X1/SvJ]
http://stage.monarchinitiative.org/genotype/MGI:3047228

Model set highlight: Models of Charcot-marie-tooth Disease
Mouse: Ndrg1<tm1Myta>/Ndrg1<tm1Myta> [involves: 129S1/Sv \* 129X1/SvJ \* C57BL/6] http://stage.monarchinitiative.org/genotype/MGI:3043397
Mouse : Pmp22<Tr-2J>/Pmp22<+> [C57BL/6J-Pmp22<Tr-2J>/GrsrJ]
http://stage.monarchinitiative.org/genotype/MGI:5515892 

---

Note, I will likely add a few more to the set list shortly....

**Comment by cmungall** [comment]
I think we should hold on the ZFIN ones until #246 is sorted, but we can have sarah add them later if you prefer
