### ISSUE TITLE
add faq for disease-matches

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#249]
I noticed that for my disease, 
http://monarchinitiative.org/disease/OMIM_601455

that the top hit only has 2 matches Fdg4; whereas the 13th hit Gars has 5 matches.

This didn't make sense.

But, that's because Fdg4 only has 8 annotations whereas Gars has 47.  Therefore, Gars is basically penalized because there are many additional annotations that don't match the disease in question.

This should be explained in an FAQ for the disease:match tab.

**Comment by nlwashington** [comment]
@harryhoch how should we handle FAQs?  should we have an FAQ on the monarch site, where we start collecting these questions?  should they be page-specific?  this is somewhat specific to the widget, so should it be bundled with the widget?

**Comment by harryhoch** [comment]
I think we could have an FAQ link with the widget. That’s probably not a bad idea. 
On 21 May 2014, at 1:47 PM, Nicole Washington notifications@github.com wrote:

> @harryhoch how should we handle FAQs? should we have an FAQ on the monarch site, where we start collecting these questions? should they be page-specific? this is somewhat specific to the widget, so should it be bundled with the widget?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by harryhoch** [comment]
We have a phenogrid faq. Please open a new issue if that is not sufficient
