### ISSUE TITLE
Homepage image does not render on iphone

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#254]
this may be a comnection issue - the image is quite large (should it be reduced? what is best practice for image size on home pages these days?)

**Comment by nlwashington** [comment]
fwiw, the home page loaded on my android.

**Comment by sarahjkim** [comment]
It seems to be loading fine on my iPhone.
![img_6562](https://cloud.githubusercontent.com/assets/4628853/2623687/66e5c946-bd01-11e3-9355-1cf8e9422f2b.PNG)

**Comment by cmungall** [comment]
OK fair enough. It is rather slow to load on this hotel wifi connection 
however..

**Comment by nlwashington** [comment]
well, it is currently 300 dpi, at 8"x10".  we probably could decrease the resolution and actual size to make it load faster.  at least down to 150 dpi, and perhaps even a 50% size without losing anything.

**Comment by jgrethe** [comment]
If anyone has Photoshop you can optimize by choosing the appropriate Web output….  If you don’t - I have Photoshop and can take a crack at it…

Cheers,
Jeff

On Apr 5, 2014, at 3:27 PM, Nicole Washington notifications@github.com wrote:

> well, it is currently 300 dpi, at 8"x10". we probably could decrease the resolution and actual size to make it load faster. at least down to 150 dpi, and perhaps even a 50% size without losing anything.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.
