### ISSUE TITLE
add gene summary to gene overview

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#257]
when the gene_summary is added to the ncbi gene table nif-0000-02801-1 view, the summaries should be displayed on the overview tab

for example, see summary field here:
http://www.ncbi.nlm.nih.gov/gene?cmd=Retrieve&dopt=full_report&list_uids=4882

this is the data ingest ticket:
https://support.crbs.ucsd.edu/browse/LAMHDI-317

**Comment by nlwashington** [comment]
Please add summary to the mygene.info downloads, like:

http://mygene.info/v2/gene/1017?fields=name,symbol,summary

and please add the summary to the overview tab on a gene page.

**Comment by kshefchek** [comment]
Added summaries from mygene with 360040a898fdc7c18d5019667b7b3d48a9c43a6d.  This works; however, mygene doesn't seem to have the best support for model organisms.  Here are examples using the gene linkes on the gene main page:
Human Gene (has summary):
http://tartini.crbs.ucsd.edu/gene/NCBIGene:8854
Mouse (no summary):
http://tartini.crbs.ucsd.edu/gene/NCBIGene:20423
Fish (no summary):
http://tartini.crbs.ucsd.edu/gene/NCBIGene:796461

**Comment by nlwashington** [comment]
hm.  well, that's the way the cookie crumbles, i guess.  the summaries aren't available via ncbi either.

@cmungall , we could consider using the human summary if the model summary isn't available.  what do you think?

**Comment by nlwashington** [comment]
closing this for now.  we should consider using summaries from geneReviews in the future.

**Comment by nlwashington** [comment]
These do not appear in the gene pages.  Reopening.

**Comment by kshefchek** [comment]
Closing as duplicate of #863
