### ISSUE TITLE
erroneous alleles retrieved for Dr adcy5

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#258]
On the gene page for Dr adcy5:
http://monarchinitiative.org/gene/NCBIGene:562619

I erroneously get 881 variants.

According to the genotypes (for which there are 3), there should be only 1 allele, s2000.

**Comment by kshefchek** [comment]
This is fixed, can I update api.js or should I hold off and pushing any changes to github?

**Comment by nlwashington** [comment]
@cmungall push this update?

**Comment by cmungall** [comment]
Go ahead and update. I will selectively clear the cache for all genes 
after I push your fixes to production

**Comment by kshefchek** [comment]
Fixed by b5e3ba95c36eceb647c19803386a12ba4f66dec5
