### ISSUE TITLE
too many pathways for Dr adcy5

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#259]
On the gene page for Dr adcy5:
http://monarchinitiative.org/gene/NCBIGene:562619

I get 33 pathways.

I just don't think this is accurate.  Please QC and report back.

**Comment by kshefchek** [comment]
This seems to reflect the NIF tables accurately:

http://nif-services.neuinfo.org/servicesv1/v1/federation/data/nlx_152525-4?exportType=data&filter=id:562619&filter=source:%22NCBIGene%22&filter=mapped_source:KEGG

Gives us dre:562619

http://nif-services.neuinfo.org/servicesv1/v1/federation/data/nlx_31015-4?exportType=data&filter=gene_id:%22dre:562619%22

Gives us ko:K08045

http://nif-services.neuinfo.org/servicesv1/v1/federation/data/nlx_31015-3?q=%22ko:K08045%22&exportType=data

Returns 33 results

**Comment by nlwashington** [comment]
wow!  i had no idea.  well, great.  :)  will close!
