### ISSUE TITLE
JSON button does not work on gene pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#260]
The .json pages return an error for the gene pages:

ringo/jsgi/connector.js, line 90
Script Stack

```
at ringo/jsgi/connector.js:90 (commitResponse)
at ringo/jsgi/connector.js:46 (handleRequest)
```

For example:
http://www.monarchinitiative.org/gene/NCBIGene:1756.json

I spent some time trying to fix this a few weeks back with no luck, @nlwashington and @cmungall any suggestions?

**Comment by harryhoch** [comment]
Kent:

Based on a quick look, it looks like a problem with Fetching DiseaseGene Associations from OMIM:

Fetching DiseaseGene Associations from OMIM (nif-0000-03216-7) for NCBIGene:1756
FETCHING: http://beta.neuinfo.org/services/v1/federation/data/nif-0000-03216-7.json data={"exportType":"data","count":1000,"q":"NCBIGene:1756","includeSubclasses":true,"project":["gene_id","gene_label","disease_id","disease_label","publication_label","publication_id","gene_ids","gene_labels","publication_ids","omim_id","omim_ids","omim_label","omim_labels"]}
RESULT: [object Object]
STATUS: 500
Status != 200. ExchangeObj source= ({connection:sun.net.www.protocol.http.HttpURLConnection:http://beta.neuinfo.org/services/v1/federation/data/nif-0000-03216-7.json?exportType=data&count=1000&q=NCBIGene%3A1756&includeSubclasses=true&project=gene_id&project=gene_label&project=disease_id&project=disease_label&project=publication_label&project=publication_id&project=gene_ids&project=gene_labels&project=publication_ids&project=omim_id&project=omim_ids&project=omim_label&project=omim_labels

…….

-harry

On Apr 7, 2014, at 1:50 PM, kshefchek notifications@github.com wrote:

> The .json pages return an error for the gene pages:
> 
> ringo/jsgi/connector.js, line 90
> Script Stack
> 
> at ringo/jsgi/connector.js:90 (commitResponse)
> at ringo/jsgi/connector.js:46 (handleRequest)
> 
> For example:
> http://www.monarchinitiative.org/gene/NCBIGene:1756.json
> 
> I spent some time trying to fix this a few weeks back with no luck, @nlwashington and @cmungall any suggestions?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by kshefchek** [comment]
Duplicate of #303
