### ISSUE TITLE
highlight known causative genes or models on grid view

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#264]
Example: HSPG2 is known to be the causative gene for Schwartz-jampel Syndrome, Type 1

This should be shown in the grid view (and should also be shown in the table underneath but this is probably a related ticket).

Unclear how best to show this. Show gene in bold? Highlight whole column (example attached in screenshot)

![screen shot 2014-04-08 at 1 03 45 pm](https://cloud.githubusercontent.com/assets/50745/2646593/6f29fe74-bf40-11e3-806b-96760291a55f.png)

**Comment by frdougal** [comment]
I recently fixed the IE issue where the x axis labels didn't appear.  After the fix, there's a wee gap between the labels and the axis line below.  Perhaps we can put an icon below the causative genes?

**Comment by harryhoch** [comment]
How about a different background color for the column? shade it somehow?

On Apr 8, 2014, at 1:42 PM, cborromeo notifications@github.com wrote:

> I recently fixed the IE issue where the x axis labels didn't appear. After the fix, there's a wee gap between the labels and the axis line below. Perhaps we can put an icon below the causative genes?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by harryhoch** [comment]
Chris, we were just looking into this. How can we get the causative gene out of the disease info? - I don't see it there.

**Comment by nlwashington** [comment]
When you fetch the disease, like ...OMIM:12345.json, there is a gene_associations object...those are your genes of interest.

**Comment by harryhoch** [comment]
should we highlight all of those?

**Comment by cmungall** [comment]
Yes. There will typically only be a few

**Comment by nlwashington** [comment]
To get to the orthologous genes of known causitive disease-genes, it is less straightforward.  At the moment, you'd have to do a series of calls to get the orthologs of the genes in the gene_associations object.  Basically, for each gene in the gene_associations, you'd have to do the .../gene/NCBIGene:12345.json call and pull out the gene ids in the orthologs object.  Iterating will obviously be awful for performance.  We could consider adding a orthologous_gene_associations object to the disease page to make this faster, or perhaps adding an ortholog list to each of the genes in the current gene_associations (I like this option better), which just pushes the joining upstream and will make the initial generation of the disease page take longer.  Maybe that's fine.  
This should probably be moved into either a cypher query or sparql query in dipper.

**Comment by nlwashington** [comment]
to decrease the time of adding orthologs as above, requires a little refactoring of the source data nlx_84521-1, panther) in NIF.  i'm redoing the index now, hope to have a first version of this today.

**Comment by nlwashington** [comment]
considering we currently don't ever show human genes in the grid, i suppose you have to wait for the ortholog objects to be present.  although, you could solve the problem using the strategy above, by fetching the gene object for any of the associations to get the orthologs.

**Comment by nlwashington** [comment]
ok, i've worked on this problem in the api, and i now think that the best thing to do is to iterate over the genes that are in the disease-gene association object, calling the .../gene/<geneid>.json and retrieving the ortholog list.  often there will only be one gene in that list (there is infrequently very many, so i think this is fine).  this has the side benefit that you would then have the phenotypes of the gene at your disposal, if you wanted to add the causative gene into the list of comparative results (if it wasn't previously there), as in ticket #361.

**Comment by harryhoch** [comment]
not yet implemented. discussion moved to https://github.com/monarch-initiative/phenogrid/issues/133
