### ISSUE TITLE
bring back "sneak peek"

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#265]
can we bring back the "sneak peek" logo?

**Comment by harryhoch** [comment]
Done via https://github.com/monarch-initiative/monarch-app/commit/2ea61dfd2d79f70f82b36aa5265a305396f74acb. 

added sneak peek logo images and edited all related templates. A bit of a pain, but seemed like the clearest way to make this happen. Should probably consider abstracting out the logo pieces of the templates into a sub-template.
