### ISSUE TITLE
Typo on "releases" page

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#266]
On the "releases" page, on the second line, "sneek" is misspelled (should be "sneak").

http://monarchinitiative.org/page/releases

Other minor thing- it would be nice to make the hyperlinks open in a new window.

**Comment by nicolevasilevsky** [comment]
Additional typos:
In the 3rd paragraph, "sneek" is misspelled.

In the 4th paragraph, "phenotype" is misspelled:
"...the ability to compare phentoypes across models..."

**Comment by harryhoch** [comment]
fixed typos via https://github.com/monarch-initiative/monarch-app/commit/39f002b8a1e88be63bf348e4f7fc9f8d0911af11.

not changing links to open in new window - I personally don't like that sort of behavior....
