### ISSUE TITLE
display variantion in HGVS notation 

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#27]
All (at least human) variants should be displayed in HGVS notation.

I think this should be the default for human mutations, and perhaps a configurable option (by the user) for other species.

**Comment by mellybelly** [comment]
moving to May milestone

**Comment by nlwashington** [comment]
moving to june milestone.  i think we can make this happen.

**Comment by nlwashington** [comment]
human variants will be in hgvs notation, when ClinVar is pulled in.  closing, as it effectively duplicates #357.
