### ISSUE TITLE
wonky variant display on gene page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#270]
on this zebrafish page:
http://monarchinitiative.org/gene/NCBIGene:799627
there are very many variants (881) displayed, that don't seem to have anything to do with the gene, ptpn21. presumably these are variants in ZFIN that have no known locus?

**Comment by kshefchek** [comment]
This was fixed after the release: https://github.com/monarch-initiative/monarch-app/issues/258

**Comment by cmungall** [comment]
Look fine on stage
http://stage.monarchinitiative.org/gene/NCBIGene:562619

Will roll stage to production tomorrow
