### ISSUE TITLE
links on pages should stay in monarch unless in citation or source columns

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#271]
For example on the variant page:
http://monarchinitiative.org/gene/NCBIGene:799627
The variant links on the first column take you to ZFIN, rather than a variant page in monarch. Perhaps in this case column 1 shouldn't be linked, and instead the source column linked?

**Comment by kshefchek** [comment]
These are linked internally; however, there appears to be some configuration that forwards the link to ZFIN.  For example, one variant is linked here:
http://monarchinitiative.org/variant/ZFIN:ZDB-ALT-080908-15

But if you click on the above link it takes you to ZFIN.

**Comment by kshefchek** [comment]
Currently all variant pages are redirected, this is commented in webapp.js:
//since we don't have allele or variant pages,
//we will redirect to the sources for now
Should we make this more specific to certain variant pages?  Or this is okay to leave as is for now?

**Comment by mellybelly** [comment]
I think this is a done for now. we can revisit as we get more/different kinds of pages.
