### ISSUE TITLE
PathFinder demo in monarch-labs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#277]
Find and visualize paths between any arbitrary two entities

**Comment by cmungall** [comment]
Note: temporarily assigned to @ccondit - once SciGraph / GraphQuest / whatever we call it goes into github this will be partitioned into discrete chunks for Chris and @kltm (Seth)

**Comment by kltm** [comment]
Committed /labs path and a basic demo to get started. Can fill it in once the service is completely specified and I've got a manager.

**Comment by cmungall** [comment]
Service requests to go here: https://github.com/SciCrunch/SciGraph/

**Comment by cmungall** [comment]
Spec here: http://kato.crbs.ucsd.edu:9000/scigraph/docs/

We are currently using this: http://kato.crbs.ucsd.edu:9000/scigraph/docs/#!/graph/getShortestPath

But I think we want this (all paths): http://kato.crbs.ucsd.edu:9000/scigraph/docs/#!/graph/getPath

For the autocomplete on the demo we want this: http://kato.crbs.ucsd.edu:9000/scigraph/docs/#!/vocabulary/findByPrefix

But we can easily wrap this in a /autocomplete2/ call with a monarch URL
