### ISSUE TITLE
Add data graph to homepage as entry point

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#279]
It would be great to have an indication on the homepage as to what data is contained in the system. Harry mocked-up a view of this below. Ideally it would be interactive, and one could click on any aspect of the chart to navigate to a set of results. 

![monarch-front-page-graphs-20140411](https://cloud.githubusercontent.com/assets/796636/2726213/3d2947f4-c5b7-11e3-9547-43f6a51da8cc.png)

@nlwashington @harryhoch discussed this last week.

**Comment by harryhoch** [comment]
Yes, indeed. @nlwashington constructed a table 
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_152525-17 with  relevant data. Thoughts on how we could condense the 5M+ records in that table to something manageable would be very much appreciated. @mellybelly - let's discuss possible designs.

**Comment by nlwashington** [comment]
@kshefchek is going to take a stab at a mockup for phenotype coverage by organism (not gene coverage).  I discovered that @ccondit has implemented the closure over facets, like http://beta.neuinfo.org/services/v1/federation/facets/nif-0000-00096-6.json?q=HP:0000478&includeSubclasses=true&exportType=data, which gets the mouse phenotypes for 'abnormality of the eye'.  This should get us started.

Also, the idea here would be that while the very first time that the graphs are generated (after scrubbing the cache), they might take a long time to load, but the resulting visits would have the graph data already, and would be fast for the user.

**Comment by harryhoch** [comment]
Great. @kshefchek , are you looking at doing something interactive/D3-ish? Let's discuss design. 

@nlwashington, it might be possible to script the construction of the cache, and to run regularly as a cron job if necessary.

**Comment by kshefchek** [comment]
Hi Harry,
My plan is to convert the output from NIF to a D3 friendly JSON format and go from there.  I'm open to different designs, did you have something in mind?

**Comment by harryhoch** [comment]
I think Melissa shared some mockups that I had put together? Those are just some ideas. Perhaps we can have a chat sometime about ideas?

On May 21, 2014, at 9:29 PM, kshefchek notifications@github.com wrote:

> Hi Harry,
> My plan is to convert the output from NIF to a D3 friendly JSON format and go from there. I'm open to different designs, did you have something in mind?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by nlwashington** [comment]
Yep, they are actually in this ticket.  Kent and I have been over them, and he's using those as a starting point.  Starting easy and then we'll build out from there.

**Comment by harryhoch** [comment]
perfect.
On May 21, 2014, at 10:01 PM, Nicole Washington notifications@github.com wrote:

> Yep, they are actually in this ticket. Kent and I have been over them, and he's using those as a starting point. Starting easy and then we'll build out from there.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by mellybelly** [comment]
![image](https://cloud.githubusercontent.com/assets/796636/3054286/ff4a5534-e1b5-11e3-93de-1817a601f9c6.png)

**Comment by mellybelly** [comment]
Adding few other mockups from Harry. Idea was to have Kent start prepping data/api calls and hopefully when ready and with more ideas in hand can work with harry and becky on front end implementation. 

![image](https://cloud.githubusercontent.com/assets/796636/3054304/1ebce6f2-e1b6-11e3-9206-3c482a92fee2.png)
![image](https://cloud.githubusercontent.com/assets/796636/3054307/27b06d1a-e1b6-11e3-8ac5-2fb191b43661.png)

**Comment by kshefchek** [comment]
It looks like for zebrafish, worm, and fly data I will have to use their associated ontologies for the NIF facets queries.  Do we have mappings from these ontologies (GO, WB, FB) back to similar HP terms?  I can try matching them by exploring the various ontologies; for example, for HP:0000707 I could use GO:0007399,  WBPhenotype:0000604, FBbt:00005093.

**Comment by nlwashington** [comment]
This should get taken care of upstream, in the ontology, right @cmungall?
Or should kent make a workaround for now since there aren't the phenotype
equivalence axioms for those organisms?

**Comment by cmungall** [comment]
I'm afraid I'm not following.

Also, I very much doubt any faceting involving the ontology will work correctly.

I tried the query above, which gives me:

```
{

    "count": 223,
    "value": "retinal degeneration"

},
{

    "count": 211,
    "value": "abnormal eye morphology"

},
```

These can't be using the closures, as the count for abnormal eye morphology is necessarily the same or more than it's descendants.

**Comment by nlwashington** [comment]
oh, i see.  you're right @cmungall.  what's happening is that the closure is working to retrieve the facets, but not for the facet counts.  @ccondit is that expected behavior?  is that what should happen?  we _could_ then compute the sum ourselves over the set of all facets, but is that what we should do?  hm, alternatively, we could just write an external script that will do the computation, which will also surely remove redundancies in the data (which is a concern i have anyway).

**Comment by ccondit** [comment]
The facet counts are for discrete values in the in the Solr index and do not take the hierarchy into account. Solr has support for ["hierarchical faceting"](https://wiki.apache.org/solr/HierarchicalFaceting) but we haven't played around with it at all...

**Comment by kshefchek** [comment]
Given that facet counts do not currently support closures and hierarchical faceting, should I write a script to query nlx_152525-17 (either using the REST interface or querying the postgres db directly) and then use OwlSim to map these ontologies to similar HP or MP terms?  I see we have some bridging axioms between phenotype ontologies here http://code.google.com/p/phenotype-ontologies/source/browse/trunk/src/ontology/wbphenotype/

Am I on the right track?  @cmungall and @nlwashington a quick OwlSim walkthrough may be helpful.

**Comment by cmungall** [comment]
Kent, is this a script that is run in advance or something integrated into the api and executed at page generation time?

It could be done the way you describe but it sounds awkward, especially the part about querying at the sql level.

For this release, can we provide simplified statistics (e.g. just about # of phenotypes, not broken down by any kind of phenotype hierarchy), and work on a cleaner method for getting facets integrated with reasoning (whether by solr, extending the existing indexing technique, using the golr closure-storing tecthique, or by doing it all via SciGraph)

**Comment by kshefchek** [comment]
We could run this in advance as part of the precomputed pipeline.  We have a perl script to query the database directly using the DBI module, which may be faster than querying over http/rest (we could go that route too).  Or alternatively, we could integrate this into the API and cache the results.  What do you think is best?

**Comment by nlwashington** [comment]
If you have time today, let's discuss.  I have some ideas.

**Comment by kshefchek** [comment]
@nlwashington what would be the correct way to query ontoquest to get all of the HPO subclasses of HP:0000118?  I figure it may be better to generate these IDs dynamically rather than hard code them into the API.

I have tried:
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/concepts/term/HP_0000118
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/subclasses/HP_0000118
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/children/HP_0000118

**Comment by nlwashington** [comment]
@cmungall should we use the new scigraph services for this?  (i think @kshefchek means to get the direct subclasses).

**Comment by nlwashington** [comment]
@kshefchek, also, i have a configuration file with the hardcoded "categories" that you can use for now if you'd like.  they are in the conf/summary_categories.json, and loaded into  

var categories = engine.config.summary_categories;

**Comment by kshefchek** [comment]
Ah ok, I'll go ahead and use conf/summary_categories.json, thanks!

**Comment by nlwashington** [comment]
by the looks of the logs, it does seem that something like
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/all/HP_0000118?level=1
should work, but i don't understand why nothing is retrieved.
i wonder if there's some kind of IP recognition for those services?

**Comment by cmungall** [comment]
There is currently an issue with this OQ instance - @jingjingbic is looking into it

Don't call the service directly - if you go via the monarch API then we can swap in SciGraph seamlessly

**Comment by cmungall** [comment]
Actually you may need to write a new method as the existing ones are geared towards getting all class info as a blob.

The code is a bit awkward as we use E4X to parse  the XML (OQ has no JSON)

Hmm, may be better to do this directly off of the scigraph instance on kato

**Comment by kshefchek** [comment]
I've pushed a prototype to the datagraph branch.  When you run the app locally the graph can be found here:
http://localhost:8080/labs/datagraph

The page caches the json data used to generate the graph so subsequent requests should load quickly.  Some thoughts:
- Right now the HP terms and labels are hardcoded so a next step would be to generate these from ontoquest or scigraph.
- Should this be converted to a horizontal bar chart?
- The graph is not interactive - we need to add some fun D3 interactive stuff
- Graph/Div labels, statements, etc. The HTML presentation needs some work

**Comment by kshefchek** [comment]
I've made a few updates here:
- HP classes and labels are generated by querying ontoquest
- Converted graph to a horizontal bar chart
- Some basic interactivity (bars link to phenotype pages, change color on hover) but needs work
- Graph sorted by mouse phenotype counts (can update to sort by human or sum across all organisms/phenotype)

**Comment by nlwashington** [comment]
just saw this, not dissimilar overview: http://wodaklab.org/iRefWeb/statistics/index

**Comment by nlwashington** [comment]
@kshefchek @harryhoch @mellybelly can this be considered closed?
