### ISSUE TITLE
robot.txt

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#28]
Add a robots.txt with a stanza to allow indexing, with a delay. cc @kltm @harryhoch

**Comment by kltm** [comment]
https://en.wikipedia.org/wiki/Robots_exclusion_standard#Nonstandard_extensions

**Comment by mellybelly** [comment]
Can someone comment on the status of this?

**Comment by cmungall** [comment]
oops, I made a dupe:
#224

This is done, if people agree with the settings (follow the commit message in the other ticket)
