### ISSUE TITLE
Need species column on Analyze Phenotypes tool

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#282]
When you pick species: all, you need to know which species the data is from. 
If it is a single species, perhaps this can be listed at the top rather than listing in every row.
Not sure who would fix this, maybe also @nlwashington.

**Comment by mellybelly** [comment]
@sarahjkim perhaps you might be able to fix this?

**Comment by nlwashington** [comment]
i have now added taxon object to the simsearch function... this could be called.  alternatively, i've written a somewhat hacky mapIdentifierToTaxon(id) function, which makes some assumptions about how ids are formatted, but will return a taxon(id,label).
