### ISSUE TITLE
Bring brain connectivity mappings into Neo4j

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#283]
We decided at the Berkeley hackathon to bring this in. Rather than going the D2RQ route we'll use the lightweight method.
1. Add a new mapping into conf/rdf-mapping. See the gene interaction map.json file for an example
2. Test it locally (see Makefile)
3. Commit and push

**Comment by jingjingbic** [comment]
New mapping file has been pushed to the source tree.

**Comment by jingjingbic** [comment]
The file name is connectivity-map.json
