### ISSUE TITLE
make sure phenotype count in tab uses uniq phenotypes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#284]
when here:

http://monarchinitiative.org/gene/NCBIGene:19378

this indicates that there are 112 phenotypes.
but several of the phenotypes are redundant (they just have different pmids).  the count in the tab should be generated from a unique list of identifiers.

**Comment by kshefchek** [comment]
Would it be better to have 1 phenotype and a list of pmids for these cases?  That would fix the count issue and eliminate the phenotype redundancy.  I imagine I would just need to add a few lines of code where I uniquify the phenotypes (currently the table is made unique by phenotype-evidence).

**Comment by kshefchek** [comment]
How does this look? http://tartini.crbs.ucsd.edu/gene/NCBIGene:19378

**Comment by cmungall** [comment]
Looks good.

Aside for all of us - I love how you can now do a profile search with the set of phenotypes. Should we be thinking about changing the language here - not really an analysis? Maybe a more unified way of thinking about this is that we can query by individual items or sets of items. For set queries you can either see everything or most similar things.

**Comment by kshefchek** [comment]
Wanted to make a note here that this is only fixed for model organisms, since human phenotypes are a separate function in the API (since these are all inferred from diseases).  Right now it doesn't seem to be an issue but we may run into this same bug for human genes down the road.
