### ISSUE TITLE
fixes to genotype tab on gene pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#285]
when here:http://monarchinitiative.org/gene/NCBIGene:19378

i notice a few problems:
1.  on genotypes tab, rename column header "effective genotype ID" --> "genotype"
2.  genes don't list all the genes that are in the genotype.  either list all genes that are part of the genotype per row, or remove the "genes" column.
3.  evidence column is empty.  (remove this column?)

@cmungall , since phenotypes for genes are effectively inferred from something else (genotypes in this case, other times variants, and still other times diseases), should there be an inferred_from column (which would list the genotype)?

**Comment by kshefchek** [comment]
No longer relevant with new pages.
