### ISSUE TITLE
inferred genes to disease not quite right

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#286]
if i look on this page for Alzheimers Disease:
http://monarchinitiative.org/disease/OMIM_104300
There are 25 genes listed.

But if i navigate to its parental term, Alzheimers Disease:
http://monarchinitiative.org/disease/DOID_10652
There are only 19 genes.

Similarly for a more-distant disease, 'Dementia':
http://monarchinitiative.org/disease/DOID_1307
still only 19 genes.

Something is not right with the inheritance here.  @cmungall Is it an ontology issue or a data issue?

**Comment by cmungall** [comment]
Hmmm

The parent gets 19:
http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-03216-7.json?exportType=data&q=DOID:10652&includeSubclasses=true

The child gets 16:
http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-03216-7.json?exportType=data&q=OMIM:104300&includeSubclasses=true

This is as expect

So if fed returns 16 for the child, where do the 25 on the page come from?

**Comment by cmungall** [comment]
ahh, clinvar. Need to add this to the closure set

**Comment by cmungall** [comment]
actually not sure what's going on here. But the IDs without labels in the gene sets in the child look suspicious

**Comment by mellybelly** [comment]
Can this be fixed for 1.0 release?

**Comment by nlwashington** [comment]
i think this is good now.  cognitive disorder (parent of dementia, http://tartini.crbs.ucsd.edu/disease/DOID_1561) lists 118 genes now > Alzheimer's at 83.  reopen if there is a problem.
