### ISSUE TITLE
Partial autocompletes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#289]
All non-autocompleting queries should become site search against free text as discussed at hackathon. @cmungall @harryhoch may have ideas about how to implement. 

Partial autocompleting matches to internal strings, second words, etc, should also be listed- these aren't autocompleting at all now, for example, Lou Gehrig's disease won't autocomplete on "Gehrig"

**Comment by harryhoch** [comment]
I know very little about the current implementation of the vocabulary search. One possibility might be for the site search would be to crawl site content,  and add it to the auto-complete index, with a very low weight, but I'm not quite sure how that all plays out in practice.

More to the point, we need to delineate exactly what the "site search"would entail.

As far as partial autocompletes, what we have now is basically a prefix search. It might be as simple as a configuration flag to change this to a substring search that would address the case above, but the results would look very different.

Appropriate handling and removing of punctuation might also help with "Gehrig's" or "Parkinson's".  That should be configurable from Solr as well.

**Comment by mellybelly** [comment]
I think it would be great to have partial matches in the autocomplete - right now you often don't see what you are looking for even though it is there. This could be shown with bolding lower on the list than exact matches (seems pretty standard).

However, the user should still be able to execute a search with no autocomplete that matches on anything on the site. Here is where we need to define how the results are displayed- Perhaps there are an entities matched list as well as an "any field string match" list? Harry what is best/most common practice here? We want to help user not end up with no results as much as possible. On the other hand, we also don't want thousands of pages.

**Comment by harryhoch** [comment]
1. Regarding partial matches, I think this can be done reasonably easily through solr, probably with a reindex. We should test before deployment.
2. For the "no autocompletes matching", we need to define what sort of cases that we might hit and why. For example, if someone uses an outdated gene name, that might be a reason for a match without an autocomplete. I think best practice in that case would be to try to display the result along with some indication of _why_ it matched. 

Agreed that the 0/10^6 search result extremes are what we want to avoid. Autocomplete, faceting helps, and other means of categorizing/explaining search results are probably the best approaches...

**Comment by cmungall** [comment]
I renamed this ticket to partial search as that appears to be what we're talking about, and made a new ticket #291 for site search.

For getting the desired search results there should be no reason for us to use different services from scicrunch (just different sources) let's try and have a unified approach here.

**Comment by harryhoch** [comment]
@cmungall, completely agreed that we should use similar services and unify approaches, but there might be some tweaking needed to configurations...

**Comment by jgrethe** [comment]
Hello Everyone,
Catching up on the thread after being taken down for the count end of last week by what I started coming down with in Berkeley…  It seems you are talking about a tiered strategy - first try partial matches (or search) against the vocabulary/ontology and if no results then default to a global search across all MONARCH data resources?

It seems the only thing that may be missing (service wise) is the partial match against the vocabulary/ontology as the global search should be able to be completed via the standard data queries that are currently implemented. Has anyone asked Chris C. about this yet? 

Cheers,
Jeff

On Apr 20, 2014, at 11:29 AM, Chris Mungall notifications@github.com wrote:

> I renamed this ticket to partial search as that appears to be what we're talking about, and made a new ticket #291 for site search.
> 
> For getting the desired search results there should be no reason for us to use different services from scicrunch (just different sources) let's try and have a unified approach here.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by mellybelly** [comment]
moving to current release, @jgrethe or @ccondit can you comment on the feasibility of fixing for this release? or please move to the july release.

**Comment by nlwashington** [comment]
i like the way that amazon does its autocomplete...  it gives you categories to filter on if you'd like exact matches, and also gives you other searches to autocomplete on:

![screen shot 2014-09-12 at 9 46 14 am](https://cloud.githubusercontent.com/assets/5124411/4253158/bb226bfe-3a9c-11e4-824a-ccc6b8b944ee.png)

**Comment by harryhoch** [comment]
Yes, absolutely. we discussed this notion of "faceted autocomplete" last year - https://support.crbs.ucsd.edu/browse/LAMHDI-221

**Comment by nlwashington** [comment]
i also very much like this one:

![screen shot 2014-09-12 at 10 47 47 am](https://cloud.githubusercontent.com/assets/5124411/4253853/110b9146-3aa5-11e4-8812-ccdf1220537e.png)

**Comment by kshefchek** [comment]
There are a few ideas being thrown around in this ticket, such as autocompleting on second words and faceted autocomplete.  Maybe it's best to break these out into new tickets and figure out who can tackle this (@ccondit?)

**Comment by kltm** [comment]
The GOlr data would hopefully be populated for this (and hopefully scigraph wouldn't be bugged for trivial things like this). However, no PoTS solution that I know of would supply a widget for our arbitrary backend, meaning that a new widget would have to be constructed and tested for this.

It's easy to slide into a discussion of the best possible widget, but the original parameters of the ticket is for just a grab bag autocomplete in all fields that do not have a specialized one. This would be easy to implement out of the box with what is available now.

**Comment by jmcmurry** [comment]
"i like the way that amazon does its autocomplete... it gives you categories to filter on if you'd like exact matches, and also gives you other searches to autocomplete on:" - @nlwashington 

In the case of Amazon, I use this feature all the time and love it; however, there a search for "yoga" yields over 800,000 results, so a quick filtering is welcome. Any one of the Amazon categories in the dropdown gets you to a search space of 5,000 to 20,000 results. 

In Monarch, the scope is much smaller and it seems like we may be getting too fast into the weeds. One thing we are currently missing in Monarch autocomplete is an "in all categories" option. That would already be a search of at most a few thousand results.

Currently, autocomplete funnels users into sometimes overly specific searches which can often look like dead ends, even if they aren't really. See for instance the first few results in a search for Pax2 have no data clearly linked. I don't have any easy fixes, per se, just thought I would chime in and see what we can come up with together. Maybe search results could be ranked according to how rich the associated data is? Just  a thought.

![screen shot 2015-10-07 at 18 44 18](https://cloud.githubusercontent.com/assets/3658863/10355669/78250734-6d23-11e5-8925-4c49b81cda3c.png)

![screen shot 2015-10-07 at 18 39 02](https://cloud.githubusercontent.com/assets/3658863/10355602/ebf1c0fe-6d22-11e5-8847-40512cb8b978.png)
![screen shot 2015-10-07 at 18 39 14](https://cloud.githubusercontent.com/assets/3658863/10355603/eff3f7ee-6d22-11e5-8272-b1b42709c154.png)
![screen shot 2015-10-07 at 18 39 25](https://cloud.githubusercontent.com/assets/3658863/10355604/f2b1e2d4-6d22-11e5-9be3-50c0b4946de1.png)

**Comment by harryhoch** [comment]
@jmcmurry, the problem with the autocomplete is that before you get to the screen that you reference above, you will see "PAX2 gene" coming up many times in the autocomplete list. it would really be nice to have the organism as well.

Completely agreed that we should aim for doing substring match and for not showing pages with no data.

**Comment by jmcmurry** [comment]
Organism categories are implemented now on Beta; discussing tomorrow would be great.

**Comment by kshefchek** [comment]
The original ticket is asking for autocomplete on second words, this has been resolved by the using the StandardTokenizerFactory and EdgeNGramFilterFactory in solr.
