### ISSUE TITLE
monarch app needs "your feedback here" input box

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#29]
Ideally this would feed right into this git tracker.
One consideration is that the user may or may not want to provide an email, or otherwise be logged in. Further, most will not be git users so would be anonymous tickets even though we'd want to ideally have their contact info.

**Comment by mellybelly** [comment]
Wondering if you can address this Sarah? 
related to #55

**Comment by sarahjkim** [comment]
I had some clarification questions. This Feedback page would have an input box, and the input box would create a new issue by an anonymous user?

**Comment by mellybelly** [comment]
Lets do a box that can be edited, with optional email field, that goes to info@monarchinitiative.org 
(even though I don't like those). Perhaps we don't really want these to go to the git tracker.

**Comment by mellybelly** [comment]
Ok, so there are now two email lists set up:
support@monarchinitiative.org, which feed into our internal JIRA. This can be used for "your feedback welcome"
users@monarchinitiative.org, which users can sign up for to receive notifications. 
We should still use the info@monarchinitiative.org to send emails to us. This can be used for "contact us".

Sound good?

see https://support.crbs.ucsd.edu/browse/LAMHDI-286

**Comment by kltm** [comment]
Sorry to drop in, but I think there might be a few problematic things with having a "contact us" form directly wired into the framework. Looking around real quick, I haven't been able to find much about ringo implementations of SMTP, which might mean either an immature implementation or writing something yourselves. Speaking from experience, security-wise, Bad Things happen around handling and sending mail (e.g. becoming a spam relay). And escaping to a shell is a Very Bad Idea (losing control of a machine).

It might be better to have that outside of the framework proper, maybe pushing it onto something a little more stable, like you have a wiki somewhere or something. Or as an alternative, if you want to have something a little friendlier than a mailto link, maybe create a Google form or something similar to handle feedback? Somebody might have a better idea or more experience with that.

**Comment by cmungall** [comment]
Agreed.

Don't we have a separate thing we can link to / help system for NIF? @harryhoch

**Comment by kltm** [comment]
I suppose alternatively, you could bring in something like javax.mail, which you could operate through the rhino interface, but I think that might get a bit weird and heavy, even before you get to the rhino part:

 http://docs.oracle.com/javaee/5/api/javax/mail/package-summary.html

 Being able to ride on a complete external system would seem like the way to go.

**Comment by harryhoch** [comment]
Chris, Seth...

@jgrethe has raised the possibility of using the olark/zendesk stack that they have adopted for NIF/Scicrunch tools.  Given that experience, I would suggest we follow their lead. 

Jeff, what do we need to do to get those tools installed?

**Comment by kltm** [comment]
Seems to be a closed-source paid-for service?

**Comment by harryhoch** [comment]
nominal fee - should not cost more than the high 2 digits for the year. I certainly prefer something open-source and free, but if it's effective and that cheap....

**Comment by harryhoch** [comment]
superseded by https://github.com/monarch-initiative/monarch-app/issues/184

**Comment by mellybelly** [comment]
I am reopening until we have a plan...

**Comment by mellybelly** [comment]
short term fix, please add link to open email in jumbotron.

**Comment by harryhoch** [comment]
done, via https://github.com/monarch-initiative/monarch-app/commit/a2d748ffa28e4f1b41aa458f8efb336ffd0c896c. 
Closing as per more permanent fix as per https://github.com/monarch-initiative/monarch-app/issues/184
