### ISSUE TITLE
no info for some diseases

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#294]
http://monarchinitiative.org/disease/DOID_12358

This has absolutely no information. We need _something_ here.  Why isn't there even a link to ear?  At minimum, we ought to be able to compute similar diseases by primary anatomical region.  Is there decomps or xrefs available?

**Comment by nlwashington** [comment]
ok, this now has at least the name of the disease, and some xrefs.  but NO DEFINITION, and no phenotypes.
getting at least one phenotype for each disease before this release probably isn't possible.  @cmungall can you comment if we should try to do that?

**Comment by cmungall** [comment]
In theory we should be able to use DO logical definitions to specify minimal phenotypes:

```
 / DOID:4 ! disease
  is_a DOID:7 ! disease of anatomical entity
   is_a DOID:863 ! nervous system disease
    is_a DOID:0050155 ! sensory system disease
     is_a DOID:2742 ! auditory system disease
      is_a DOID:5100 ! middle ear disease
       is_a DOID:10754 ! otitis media <-- inflammation
        is_a DOID:11180 ! non-suppurative otitis media
         is_a DOID:9739 ! eustachian tube disease <-- 'euastachian tube phenotype'
          is_a DOID:12358 ! patulous eustachian tube 
```

However,  these defs were auto-generated by me and have not been vetted

There may be subtle errors. E.g. I may have defined

eustachian tube disease = disease and affects some eustachian tube

However, the text def says that inflammation is always present, so the owl expression above is too weak

ie DO says that ET diseases are always inflammatory.

**Comment by cmungall** [comment]
For now, we should just do a test, if no phenotypes are present show an explanation and possibly a link to further documentation.

"
This disease has no phenotypes associated. This may be for a number of reasons. Our current primary focus is on phenotypes for genetic diseases - in future versions we should have phenotypes for common diseases
"

**Comment by jmcmurry** [comment]
Assuming that we don't expect tabs to have data, this now looks to be fine. We have a description. The only thing that looks out of place is that there's no hyperlink on the identifier. @nlwashington can we close this?

![screen shot 2015-10-20 at 10 45 24](https://cloud.githubusercontent.com/assets/3658863/10616010/cc91a4fa-7717-11e5-96c8-2f8c51a024c2.png)

**Comment by nlwashington** [comment]
well, the real point is actually that there ought to be a minimum of a single phenotype for any disease, right?  i mean, at least we have something here, but it's a shame that we can't even have one single phenotype.  if this will be covered by getting in the common diseases, then i guess we can defer to that ticket (https://github.com/monarch-initiative/dipper/issues/116), whenever it will get finished, and close this.  i'll punt that decision to @cmungall or @mellybelly.
