### ISSUE TITLE
Comparing to Humans

### ISSUE THREAD

**Issue by frdougal** [monarch-initiative/monarch-legacy#300]
I added some functionality to the model viewer allowing the user to select the comparison organism from a drop-down.  The choices are: human (9096), mouse (10090), and zebrafish (7955).  zebrafish and mouse work fine.  Human throws an error and a 500 error.  I apologize for the length of the messages, but I can't attach text files in the issue tracker.

You can see the problem on the "matches" tab on this page:
http://tartini.crbs.ucsd.edu/disease/OMIM_255800

To reproduce, select "Homo sapiens" from the drop-down.  Here is the URL being retrieved:

http://localhost:8080/simsearch/phenotype/?input_items=HP:0000007,HP:0000023,HP:0000160,HP:0000205,HP:0000272,HP:0000293,HP:0000347,HP:0000369,HP:0000396,HP:0000470,HP:0000482,HP:0000508,HP:0000518,HP:0000545,HP:0000581,HP:0000768,HP:0000926,HP:0000939,HP:0001239,HP:0001249,HP:0001265,HP:0001324,HP:0001374,HP:0001537,HP:0001620,HP:0001621,HP:0001762,HP:0001763,HP:0002047,HP:0002230,HP:0002486,HP:0002673,HP:0002750,HP:0002751,HP:0002812,HP:0002938,HP:0003016,HP:0003044,HP:0003202,HP:0003273,HP:0003417,HP:0003712,HP:0004322,HP:0005830,HP:0006473,HP:0006499,HP:0007740,HP:0008734,HP:0012368,HP:0000069,HP:0000160,HP:0000175,HP:0000211,HP:0000232,HP:0000252,HP:0000272,HP:0000293,HP:0000294,HP:0000298,HP:0000316,HP:0000343,HP:0000347,HP:0000368,HP:0000396,HP:0000426,HP:0000470,HP:0000482,HP:0000486,HP:0000505,HP:0000508,HP:0000518,HP:0000534,HP:0000545,HP:0000581,HP:0000600,HP:0000767,HP:0000768,HP:0000772,HP:0000787,HP:0000912,HP:0000926,HP:0000944,HP:0000998,HP:0001083,HP:0001276,HP:0001288,HP:0001315,HP:0001324,HP:0001376,HP:0001537,HP:0001557,HP:0001561,HP:0001601,HP:0001763,HP:0001883,HP:0001883,HP:0002047,HP:0002092,HP:0002093,HP:0002104,HP:0002167,HP:0002486,HP:0002645,HP:0002650,HP:0002652,HP:0002750,HP:0002804,HP:0002808,HP:0002857,HP:0002983,HP:0003042,HP:0003179,HP:0003198,HP:0003202,HP:0003306,HP:0003307,HP:0003326,HP:0003457,HP:0003712,HP:0004322,HP:0004325,HP:0004349,HP:0005930,HP:0007018,HP:0008056,HP:0008872,HP:0009743,HP:0010978,HP:0011001,HP:0011675,HP:0100543,HP:0100569,HP:0100612,HP:0100795,HP:0100813&target_species=9096

HERE IS THE RESULTING OUTPUT AND ERROR STACK TRACE:

{"input_items":"HP:0000007,HP:0000023,HP:0000160,HP:0000205,HP:0000272,HP:0000293,HP:0000347,HP:0000369,HP:0000396,HP:0000470,HP:0000482,HP:0000508,HP:0000518,HP:0000545,HP:0000581,HP:0000768,HP:0000926,HP:0000939,HP:0001239,HP:0001249,HP:0001265,HP:0001324,HP:0001374,HP:0001537,HP:0001620,HP:0001621,HP:0001762,HP:0001763,HP:0002047,HP:0002230,HP:0002486,HP:0002673,HP:0002750,HP:0002751,HP:0002812,HP:0002938,HP:0003016,HP:0003044,HP:0003202,HP:0003273,HP:0003417,HP:0003712,HP:0004322,HP:0005830,HP:0006473,HP:0006499,HP:0007740,HP:0008734,HP:0012368,HP:0000069,HP:0000160,HP:0000175,HP:0000211,HP:0000232,HP:0000252,HP:0000272,HP:0000293,HP:0000294,HP:0000298,HP:0000316,HP:0000343,HP:0000347,HP:0000368,HP:0000396,HP:0000426,HP:0000470,HP:0000482,HP:0000486,HP:0000505,HP:0000508,HP:0000518,HP:0000534,HP:0000545,HP:0000581,HP:0000600,HP:0000767,HP:0000768,HP:0000772,HP:0000787,HP:0000912,HP:0000926,HP:0000944,HP:0000998,HP:0001083,HP:0001276,HP:0001288,HP:0001315,HP:0001324,HP:0001376,HP:0001537,HP:0001557,HP:0001561,HP:0001601,HP:0001763,HP:0001883,HP:0001883,HP:0002047,HP:0002092,HP:0002093,HP:0002104,HP:0002167,HP:0002486,HP:0002645,HP:0002650,HP:0002652,HP:0002750,HP:0002804,HP:0002808,HP:0002857,HP:0002983,HP:0003042,HP:0003179,HP:0003198,HP:0003202,HP:0003306,HP:0003307,HP:0003326,HP:0003457,HP:0003712,HP:0004322,HP:0004325,HP:0004349,HP:0005930,HP:0007018,HP:0008056,HP:0008872,HP:0009743,HP:0010978,HP:0011001,HP:0011675,HP:0100543,HP:0100569,HP:0100612,HP:0100795,HP:0100813","target_species":"9096"}
|Input| = 135
Input: HP:0000007,HP:0000023,HP:0000160,HP:0000205,HP:0000272,HP:0000293,HP:0000347,HP:0000369,HP:0000396,HP:0000470,HP:0000482,HP:0000508,HP:0000518,HP:0000545,HP:0000581,HP:0000768,HP:0000926,HP:0000939,HP:0001239,HP:0001249,HP:0001265,HP:0001324,HP:0001374,HP:0001537,HP:0001620,HP:0001621,HP:0001762,HP:0001763,HP:0002047,HP:0002230,HP:0002486,HP:0002673,HP:0002750,HP:0002751,HP:0002812,HP:0002938,HP:0003016,HP:0003044,HP:0003202,HP:0003273,HP:0003417,HP:0003712,HP:0004322,HP:0005830,HP:0006473,HP:0006499,HP:0007740,HP:0008734,HP:0012368,HP:0000069,HP:0000160,HP:0000175,HP:0000211,HP:0000232,HP:0000252,HP:0000272,HP:0000293,HP:0000294,HP:0000298,HP:0000316,HP:0000343,HP:0000347,HP:0000368,HP:0000396,HP:0000426,HP:0000470,HP:0000482,HP:0000486,HP:0000505,HP:0000508,HP:0000518,HP:0000534,HP:0000545,HP:0000581,HP:0000600,HP:0000767,HP:0000768,HP:0000772,HP:0000787,HP:0000912,HP:0000926,HP:0000944,HP:0000998,HP:0001083,HP:0001276,HP:0001288,HP:0001315,HP:0001324,HP:0001376,HP:0001537,HP:0001557,HP:0001561,HP:0001601,HP:0001763,HP:0001883,HP:0001883,HP:0002047,HP:0002092,HP:0002093,HP:0002104,HP:0002167,HP:0002486,HP:0002645,HP:0002650,HP:0002652,HP:0002750,HP:0002804,HP:0002808,HP:0002857,HP:0002983,HP:0003042,HP:0003179,HP:0003198,HP:0003202,HP:0003306,HP:0003307,HP:0003326,HP:0003457,HP:0003712,HP:0004322,HP:0004325,HP:0004349,HP:0005930,HP:0007018,HP:0008056,HP:0008872,HP:0009743,HP:0010978,HP:0011001,HP:0011675,HP:0100543,HP:0100569,HP:0100612,HP:0100795,HP:0100813
Query:HP:0000007,HP:0000023,HP:0000160,HP:0000205,HP:0000272,HP:0000293,HP:0000347,HP:0000369,HP:0000396,HP:0000470,HP:0000482,HP:0000508,HP:0000518,HP:0000545,HP:0000581,HP:0000768,HP:0000926,HP:0000939,HP:0001239,HP:0001249,HP:0001265,HP:0001324,HP:0001374,HP:0001537,HP:0001620,HP:0001621,HP:0001762,HP:0001763,HP:0002047,HP:0002230,HP:0002486,HP:0002673,HP:0002750,HP:0002751,HP:0002812,HP:0002938,HP:0003016,HP:0003044,HP:0003202,HP:0003273,HP:0003417,HP:0003712,HP:0004322,HP:0005830,HP:0006473,HP:0006499,HP:0007740,HP:0008734,HP:0012368,HP:0000069,HP:0000160,HP:0000175,HP:0000211,HP:0000232,HP:0000252,HP:0000272,HP:0000293,HP:0000294,HP:0000298,HP:0000316,HP:0000343,HP:0000347,HP:0000368,HP:0000396,HP:0000426,HP:0000470,HP:0000482,HP:0000486,HP:0000505,HP:0000508,HP:0000518,HP:0000534,HP:0000545,HP:0000581,HP:0000600,HP:0000767,HP:0000768,HP:0000772,HP:0000787,HP:0000912,HP:0000926,HP:0000944,HP:0000998,HP:0001083,HP:0001276,HP:0001288,HP:0001315,HP:0001324,HP:0001376,HP:0001537,HP:0001557,HP:0001561,HP:0001601,HP:0001763,HP:0001883,HP:0001883,HP:0002047,HP:0002092,HP:0002093,HP:0002104,HP:0002167,HP:0002486,HP:0002645,HP:0002650,HP:0002652,HP:0002750,HP:0002804,HP:0002808,HP:0002857,HP:0002983,HP:0003042,HP:0003179,HP:0003198,HP:0003202,HP:0003306,HP:0003307,HP:0003326,HP:0003457,HP:0003712,HP:0004322,HP:0004325,HP:0004349,HP:0005930,HP:0007018,HP:0008056,HP:0008872,HP:0009743,HP:0010978,HP:0011001,HP:0011675,HP:0100543,HP:0100569,HP:0100612,HP:0100795,HP:0100813
|Query| : 135
EXCLUDE PIDs: 
PIDs (pre-filter): HP:0000007,HP:0000023,HP:0000160,HP:0000205,HP:0000272,HP:0000293,HP:0000347,HP:0000369,HP:0000396,HP:0000470,HP:0000482,HP:0000508,HP:0000518,HP:0000545,HP:0000581,HP:0000768,HP:0000926,HP:0000939,HP:0001239,HP:0001249,HP:0001265,HP:0001324,HP:0001374,HP:0001537,HP:0001620,HP:0001621,HP:0001762,HP:0001763,HP:0002047,HP:0002230,HP:0002486,HP:0002673,HP:0002750,HP:0002751,HP:0002812,HP:0002938,HP:0003016,HP:0003044,HP:0003202,HP:0003273,HP:0003417,HP:0003712,HP:0004322,HP:0005830,HP:0006473,HP:0006499,HP:0007740,HP:0008734,HP:0012368,HP:0000069,HP:0000160,HP:0000175,HP:0000211,HP:0000232,HP:0000252,HP:0000272,HP:0000293,HP:0000294,HP:0000298,HP:0000316,HP:0000343,HP:0000347,HP:0000368,HP:0000396,HP:0000426,HP:0000470,HP:0000482,HP:0000486,HP:0000505,HP:0000508,HP:0000518,HP:0000534,HP:0000545,HP:0000581,HP:0000600,HP:0000767,HP:0000768,HP:0000772,HP:0000787,HP:0000912,HP:0000926,HP:0000944,HP:0000998,HP:0001083,HP:0001276,HP:0001288,HP:0001315,HP:0001324,HP:0001376,HP:0001537,HP:0001557,HP:0001561,HP:0001601,HP:0001763,HP:0001883,HP:0001883,HP:0002047,HP:0002092,HP:0002093,HP:0002104,HP:0002167,HP:0002486,HP:0002645,HP:0002650,HP:0002652,HP:0002750,HP:0002804,HP:0002808,HP:0002857,HP:0002983,HP:0003042,HP:0003179,HP:0003198,HP:0003202,HP:0003306,HP:0003307,HP:0003326,HP:0003457,HP:0003712,HP:0004322,HP:0004325,HP:0004349,HP:0005930,HP:0007018,HP:0008056,HP:0008872,HP:0009743,HP:0010978,HP:0011001,HP:0011675,HP:0100543,HP:0100569,HP:0100612,HP:0100795,HP:0100813
PIDs (post-filter): HP:0000007,HP:0000023,HP:0000160,HP:0000205,HP:0000272,HP:0000293,HP:0000347,HP:0000369,HP:0000396,HP:0000470,HP:0000482,HP:0000508,HP:0000518,HP:0000545,HP:0000581,HP:0000768,HP:0000926,HP:0000939,HP:0001239,HP:0001249,HP:0001265,HP:0001324,HP:0001374,HP:0001537,HP:0001620,HP:0001621,HP:0001762,HP:0001763,HP:0002047,HP:0002230,HP:0002486,HP:0002673,HP:0002750,HP:0002751,HP:0002812,HP:0002938,HP:0003016,HP:0003044,HP:0003202,HP:0003273,HP:0003417,HP:0003712,HP:0004322,HP:0005830,HP:0006473,HP:0006499,HP:0007740,HP:0008734,HP:0012368,HP:0000069,HP:0000160,HP:0000175,HP:0000211,HP:0000232,HP:0000252,HP:0000272,HP:0000293,HP:0000294,HP:0000298,HP:0000316,HP:0000343,HP:0000347,HP:0000368,HP:0000396,HP:0000426,HP:0000470,HP:0000482,HP:0000486,HP:0000505,HP:0000508,HP:0000518,HP:0000534,HP:0000545,HP:0000581,HP:0000600,HP:0000767,HP:0000768,HP:0000772,HP:0000787,HP:0000912,HP:0000926,HP:0000944,HP:0000998,HP:0001083,HP:0001276,HP:0001288,HP:0001315,HP:0001324,HP:0001376,HP:0001537,HP:0001557,HP:0001561,HP:0001601,HP:0001763,HP:0001883,HP:0001883,HP:0002047,HP:0002092,HP:0002093,HP:0002104,HP:0002167,HP:0002486,HP:0002645,HP:0002650,HP:0002652,HP:0002750,HP:0002804,HP:0002808,HP:0002857,HP:0002983,HP:0003042,HP:0003179,HP:0003198,HP:0003202,HP:0003306,HP:0003307,HP:0003326,HP:0003457,HP:0003712,HP:0004322,HP:0004325,HP:0004349,HP:0005930,HP:0007018,HP:0008056,HP:0008872,HP:0009743,HP:0010978,HP:0011001,HP:0011675,HP:0100543,HP:0100569,HP:0100612,HP:0100795,HP:0100813
TypeError: Cannot read property "target_idspace" from undefined
    at lib/monarch/api.js:3170 (anonymous)
    at lib/monarch/web/webapp.js:1207 (anonymous)
    at stick/lib/middleware/route.js:215 (route)
    at stick/lib/middleware/params.js:102 (anonymous)
    at stick/lib/middleware/static.js:62 (static)
    at /Users/chb69/git/monarch-app/lib/monarch/web/sanitize.js:7 (anonymous)
    at stick/lib/stick.js:37 (app)
    at ringo/jsgi/connector.js:42 (handleRequest)

**Comment by frdougal** [comment]
assigned to Chris and changes it to a bug

**Comment by frdougal** [comment]
I fixed this issue.  This was a classic ID10T error.  I thought I was looking for human phentoypes using taxon 9606.  Instead, I was looking for 9096 which is a blue eared-pheasant.  Apparently my taxon id is 63221.

**Comment by cmungall** [comment]
I'd actually love to get both these species into Monarch...
