### ISSUE TITLE
Finding the phenotypes of particular genes

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/monarch-legacy#304]
I wanted to locate all phenotypes in any organism given a particular Drosophila gene. (i.e. including phenotypes from it's orthologus genes) 

Apparently we cannot yet search for genes of any other species except human. (even though the data must be in there).

I also wanted to search for set of genes (furry, tricorner, & mical) because these all can mess up the actin cytoskeleton.

**Comment by nlwashington** [comment]
I am splitting this up into multiple tickets and closing this one.  The first item will be solved partly with #351, and displayed with #325.  Do you have other ideas for display?  Please add to the other ticket(s).

Item two has been moved to #354.  

Item three is more complicated and needs to be expanded.  See #355.
