### ISSUE TITLE
clicking on phenotype failed

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/monarch-legacy#305]
After searching on the phenotype "  actin cytoskeleton filament morphology abnormal" and clicking on the result the site returned an empty page with the message "sorry, something went wrong"

p.s. If there is just one result it would be nice to go directly to the page without having to click through. seems  quite unnecessary for the user.

**Comment by cmungall** [comment]
Example:
http://monarchinitiative.org/Phenotype/WBPhenotype_0001587

```
              <!-- Developer Error Message -->
                <!-- Cannot call method &quot;indexOf&quot; of undefined -->
                <!-- Stack Trace: -->
                <!--    at lib/monarch/web/webapp.js:732 (anonymous)
    at lib/monarch/web/webapp.js:732 (anonymous)
    at stick/lib/middleware/route.js:215 (route)
    at stick/lib/middleware/params.js:102 (anonymous)
    at stick/lib/middleware/static.js:62 (static)
    at /var/home/bamboo/start-monarch-server/lib/monarch/web/sanitize.js:7 (anonymous)
    at stick/lib/stick.js:37 (app)
    at ringo/jsgi/connector.js:42 (handleRequest)
```

Diagnosis: worm phenotype ontology not yet fully integrated

**Comment by cmungall** [comment]
More general issue

http://monarchinitiative.org/Phenotype/random1234567

Should be more informative

**Comment by cmungall** [comment]
Still not ideal as you would expect to see data there
