### ISSUE TITLE
/gene/ json results need tweaking

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#306]
E.g.
Note some of these will require further discussion

http://127.0.0.1:8282/gene/NCBIGene:388552.json
- add a JSON LD context
  - fields like 'summary' should be mapped in the context (what annotation property should we use @mellybelly ?)
- phenotype associations IDs aren't unique (Chris/Nicole)
- We have taxon and tax_xref. Should probably be unified
  - id should always be a CURIE
  - label should contain label
- diseases
  - some don't have labels
- interactions
  - ""affinity chromatography technology" etc should be mapped to a URI in our JSON LD context. @mellybelly  which vocabulary?

General
- use null rather than "" for no data

**Comment by cmungall** [comment]
Note we have

```
    "source": {
        "id": "nlx_151671-2",
        "label": "ClinVar, via Office of Rare Diseases (9435)"
    }
```

And

```
"source": {

    "id": "nlx_151671-2",
    "label": "ClinVar, via NCBI curation"

}
```

The relationship between id and label is functional.

The via part should probably be modeled in the relationship between data and source (it is already?)

**Comment by mellybelly** [comment]
@cmungall I would use OBI or ERO for techniques for the interactions. We'll need these for expression and phentoyping in some cases too. We should pull in a slice of these two ontologies - assays and techniques. @mbrush can you help with this?

For summary, maybe one of these:
http://purl.org/dc/terms/description
http://www.w3.org/2004/02/skos/core#definition
Probably prefer the former.

**Comment by mbrush** [comment]
@mellybelly the techniques in the BioGrid interaction data map to the PSI-MI 'ontology' (http://purl.obolibrary.org/obo/mi.owl), which is actually a pretty rich vocabulary.  We should consider if we would use the IRIs from this ontology, or try to get terms into OBI/ERO with mappings to PSI-MI terms. As for any additional techniques needed, I can work to get them into OBI and/or ERO as needed.

BioGrid techniques are here: http://wiki.thebiogrid.org/doku.php/experimental_systems
Earlier JIRA ticket about this is here: https://support.crbs.ucsd.edu/browse/NIF-11813

**Comment by kshefchek** [comment]
No longer relevant but we should create a new issue for exporting data as JSON.
