### ISSUE TITLE
Phenogrid obscured by table

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#310]
http://monarchinitiative.org/disease/DOID_12798

![screen shot 2014-04-26 at 5 51 11 pm](https://cloud.githubusercontent.com/assets/50745/2810192/1b5efd0c-cda6-11e3-9327-7c2865a39382.png)

**Comment by frdougal** [comment]
I think I fixed this:

![image](https://cloud.githubusercontent.com/assets/5503816/2836084/4b650aea-cff5-11e3-834a-206571131b72.png)
