### ISSUE TITLE
Tooltip for phenogrid cells - showing species in phenotype label is confusing

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#311]
The algorithm appears to be to append (Human) for HP and (Mouse) for MP.

This is potentially confusing. HP classes can categorize mouse phenotypes and vice versa.

I think it better to show the ID here

**Comment by harryhoch** [comment]
@cmungall, I think this needs some discussion. Coming from the outside world, it seems confusing to me that concepts from one organism's phenotype ontology should categorize phenotypes from another organism.  

Which approaches would be least likely to confuse users who don't know anything about phenotype representation?

**Comment by nlwashington** [comment]
As we've discussed live, I think removing the species label (and also not showing the class id) is preferable.  Note, however, it would be nice if the current class labels were hyperlinked.  not sure how doable that is.

**Comment by cmungall** [comment]
Sounds good. The hyperlink should be as simple as "/phenotype/"+ID (we need to abstract out the linking into a CommonJS lib that can be used by the js widgets, but hardcoding ok for now...)

**Comment by harryhoch** [comment]
@nlwashington short term, I agree with removing the species label and not showing the ID is reasonable. hyperlinking the labels shouldn't be hard.

Long term, there is a broader problem of the content of the phenotype ontologies. if, for example, we get an HP class categorizing the mouse phenotype, that might confuse some users. It seems to me that users have to have had your thinking pretty deeply into the world that we're living in to understand that sort of linkage...

**Comment by boesb** [comment]
Closed. Species removed from tooltip.

**Comment by mellybelly** [comment]
Ok so this seems to me to still be confusing. See attached figure, I'm looking at diseases against diseases, and my match has a short snout. I think that might bother some clinicians.
![image](https://cloud.githubusercontent.com/assets/796636/4328495/0ba988a8-3f86-11e4-9518-49978145a4ae.png)

Perhaps we need to preferentially show the HP term label when its humanX human? and similarly the other context-specific ones?

**Comment by cmungall** [comment]
owlsim-2 treats equivalents as equivalents (ie substitutible with no loss of meaning), and these are inferred equivalent by the axioms in the ontology. The owlsim-v3 rest API will preserve the original query, papering over this issue. However, even here there is no control over mousy terms showing up as the MICA.

There are ways around this of vary complexity, but it's far simpler to avoid hacks make the ontology tell the truth / show the model you want to see, then the algorithm will do the right thing. For example, you can model snout as being a non-human protrusion of the midface. The phenotypic relationship to midface would be subclass, not equivalentTo. Or we can avoid encoding character state in the ontology and just model everything as midface.

**Comment by cmungall** [comment]
This one is easy to fix
![screen shot 2014-09-18 at 5 03 50 pm](https://cloud.githubusercontent.com/assets/50745/4329070/7cb7474c-3f90-11e4-803f-332339608342.png)

**Comment by harryhoch** [comment]
Is there any way we can add some heuristics here? for example, a   disease x disease search should probably never result in any non-human phenotypes, even as subsumers..

**Comment by harryhoch** [comment]
@cmungall, I'm not sure how to get around this - are you suggesting that we should pull synonyms? I'm not sure when. Is this something that should be done in the UI level or in the owlsim level?

**Comment by nlwashington** [comment]
we may be able to service this by querying scigraph for terms and filtering by taxon.  tbd.

**Comment by harryhoch** [comment]
not implemented, but discussion moved to https://github.com/monarch-initiative/phenogrid/issues/134
