### ISSUE TITLE
grid view assumes columns are genes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#313]
![screen shot 2014-04-28 at 8 59 29 am](https://cloud.githubusercontent.com/assets/50745/2819402/1b6e5808-ceee-11e3-9508-2140bcd5b57a.png)

http://tartini.crbs.ucsd.edu/analyze/phenotypes/?input_items=MP_0002639+MP_0004704+MP_0002135+HP_0000133+MP_0000548+HP_0001518&limit=100&target_species=9606

The columns here are diseases. We may have genotypes soon. Maybe best to use neutral search language here like Query & Target/Match

**Comment by frdougal** [comment]
no problem.  Just a few questions:
1.  I modified the "Phenotype comparison (grouped by [Organism] genes)" to display either genes or diseases.  It will show diseases if the Organism = Homo sapiens
2.  Which neutral search terms should we use and where?  Do I change the "Gene Label" in the mouse over to "Target/Match"?  Or is it just the Target?

**Comment by frdougal** [comment]
I spoke to Nicole.  I will use the JSON returned from the simsearch call to determine type.  I will use the B_type returned in the source object to determine the type:

"source":{"target_idspace":"MGI","b_type":"gene","b_source":"nif-0000-00096-6","a_type":"phenotype_profile","label":"OwlSim Server: http://owlsim.crbs.ucsd.edu/"}}
