### ISSUE TITLE
Moved OMIM records should show metadata or get user to right place

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#314]
For example, see diseases on this page:
http://monarchinitiative.org/phenotype/HP_0100257
Which has an entry that states "Moved to 615465"
clicking on the link takes you here
http://monarchinitiative.org/disease/OMIM_300571
Which has no information.
@nlwashington  may also have ideas.

**Comment by nlwashington** [comment]
Hm.  yes, what shall we do here.  this means that when @pnrobinson curated this resource, the data was in the OMIM_300571 entry, but OMIM has now deprecated it and it should be OMIM:615465....meaning 300571 is effectively a synonym.  i can clean up these kinds of titles at ingest/view building time.  need to make a NIF ticket for that.  also, @pnrobinson, do you have any plans on back-curating?  do a report of these be helpful?

**Comment by pnrobinson** [comment]
Hi,

this happened becasue this entry:
http://omim.org/entry/300571
was revised by OMIM and moved to the other indicated entry. Our pipeline currently catches the "other" entries, and we have an entry for 615465, but it seems we do not have all of the "moved" entries. If you can easily make a list of them I will clean things up. The old entry is not to be regarded as a synonym. I think the semantics is best captured by "Obsolete, consider MIM:XXXYYY"
So for now I have deleted our old annotation for 300571, and the annotation for 615465 is already OK

-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Nicole Washington [notifications@github.com]
Gesendet: Dienstag, 29. April 2014 02:13
An: monarch-initiative/monarch-app
Cc: Robinson, Peter
Betreff: Re: [monarch-app] Moved OMIM records should show metadata or get user to right place (#314)

Hm. yes, what shall we do here. this means that when @pnrobinsonhttps://github.com/pnrobinson curated this resource, the data was in the OMIM_300571 entry, but OMIM has now deprecated it and it should be OMIM:615465....meaning 300571 is effectively a synonym. i can clean up these kinds of titles at ingest/view building time. need to make a NIF ticket for that. also, @pnrobinsonhttps://github.com/pnrobinson, do you have any plans on back-curating? do a report of these be helpful?

**Comment by nlwashington** [comment]
here's the current "moved" entries i currently have.  it affects 86 disorders and 686 phenotypes.

**Comment by nlwashington** [comment]
sorry.  that was terrible.  (note the above is what happens when you include an attachment in an email reply.  clearly, don't do that.)

**Comment by nlwashington** [comment]
For this particular entry, i still see:

Moved To 246560

However, I believe this is an upstream data issue, and not an interface issue; closing this ticket.

**Comment by nlwashington** [comment]
See data issue https://support.crbs.ucsd.edu/browse/LAMHDI-363

**Comment by pnrobinson** [comment]
Hi Nicole,

recently I cleaned up the "moved" records. Unless there are new moved records, you should not be seeing any if you have the latest files.

-Peter

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Nicole Washington [notifications@github.com]
Gesendet: Montag, 9. Juni 2014 18:49
An: monarch-initiative/monarch-app
Cc: Robinson, Peter
Betreff: Re: [monarch-app] Moved OMIM records should show metadata or get user to right place (#314)

See data issue https://support.crbs.ucsd.edu/browse/LAMHDI-363
