### ISSUE TITLE
Need Recent events and news feed

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#316]
Sarah or @harryhoch do you have ideas about this should be implemented?
We need to be showing off our talks and latest release info.

**Comment by harryhoch** [comment]
A couple of thoughts:
1. Link to a blogger/wordpress, etc. blog. Easy, but less less integrated than other possibilities.
2. Wrap the site content with a CMS. More flexible, in terms of additional functionality like user registration/authentication, but somewhat more difficult to manage.
3. Find existing blog components that might be integrated. I just ran a quick check, but couldn't find anything. 
4. Roll our own facilities for submitting and then displaying news items. A bit more code to write, but shouldn't be prohibitive.

**Comment by kltm** [comment]
I've had experience with all of the above, and I think anything but variations of 1 are probably way more work and hassle than they're worth. Can go into detail if anybody is interested.

**Comment by harryhoch** [comment]
I can't disagree

**Comment by kltm** [comment]
Options then range from having a heavier CMS (like using drupalgardens)  to just a blog/something light on one of the more popular sites (blogger?). Depending on your needs, you might be able to do something with github.io as well. What are the needs?
- News/blog
- Twitter push?
- Users/login (assuming not)
- General documentation
- Good URLs?
- ???

**Comment by harryhoch** [comment]
@kltm, we might have some other tickets along these lines, but I'm not going to dig them up  now.
I think the needs are:
-  news/blog
-  twitter pull
-  other social media (g+, etc)
-  documentation and urls.

User authentication has been discussed as a goal as well.... Others? @cmungall , @mellybelly - any thoughts?

**Comment by kltm** [comment]
When you say social media, do you mean push/pull functionality, or do you intend to keep them fairly separate. Obviously, a lot easier that way.

BTW, manual twitter pull is actually a huge PITA now that they're trying to make money. For another site we just ended up consuming their widget.

Integrating authentication (and I'm assuming authorization?) can be a rather larger deal unless you are going to be your own provider or farm it out.

**Comment by harryhoch** [comment]
No clear plan - just thinking that we should be able to hook into those means of spreading the word. 
Twitter widget is probably fine. 

Mozilla persona has been suggested for auth/auth....

**Comment by kltm** [comment]
Persona only does authentication.

**Comment by kltm** [comment]
Then it might be easier to do something quick that has an escape route and meets core needs for now, and then upgrade/migrate when/if there is a need for more later.

**Comment by harryhoch** [comment]
agreed
On Apr 29, 2014, at 4:01 PM, kltm notifications@github.com wrote:

> Then it might be easier to do something quick that has an escape route and meets core needs for now, and then upgrade/migrate when/if there is a need for more later.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by kltm** [comment]
Started playing around with blogger. http://monarch-initiative.blogspot.com
Naturally, ignore the theme for now. I can add people through the admin interface, just send me your google account info (I can create burners if necessary).

Also started looking at different ways to present the remote info on the main monarchinitiative site (/labs/blog-scratch), starting with getting the realtime feed off the blog (should at least be cached). Other possibilities are JS widgets and maybe pulling something through Jenkins.

**Comment by mellybelly** [comment]
Cool!
can you add melissa, nicole Vasilevsky, nicole Washington, anita bandrowski, maryann martone?
also our URL has no dash, does this matter?

**Comment by kltm** [comment]
@mellybelly "monarchinitiative" was already taken, so I just grabbed this instead. If at a later point we want to switch to another name or platform, it shouldn't be a big deal and what we do/learn should be directly transferable.

**Comment by kltm** [comment]
@mellybelly we can also setup our own custom URL for it, like maybe blog.monarchinitiative.org or something.

**Comment by kltm** [comment]
@nicolevasilevsky I've added your account, but removed your email from this thread: crawlers.

**Comment by kltm** [comment]
Could somebody email google account details for: anita bandrowski and maryann martone?

**Comment by kltm** [comment]
Somebody working on UX should take over integration, but I've put together a starting point for incorporating the blog/news feed onto the landing page (and tried some other template cleaning):

http://tartini.crbs.ucsd.edu/labs/blog-scratch

Besides that, the feed is grabbed live every time. I'm sure Google can handle it, but it is a remote serial call on the server so it could be written faster a lot of ways.

**Comment by mellybelly** [comment]
Seems mostly implemented. just need write and get homepage view sorted out. @kltm close or reassign as needed.

**Comment by kltm** [comment]
Yeah, likely done now.

**Comment by nlwashington** [comment]
@cmungall or @kltm do we want to add google analytics to our blogger?  there is a special spot to specify it.  if so i need an id.

**Comment by cmungall** [comment]
Yes, we do

**Comment by kltm** [comment]
You'll want a different code than the main site. Create a new item and assign it to me.
