### ISSUE TITLE
consider removing right column of subsuming phenoytpes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#323]
At the phenoscape meeting, it was suggested that instead of showing the right-hand column of subsuming phenotypes, that we instead show the subsumer and the actual match in the hover over. what do you all think? @harryhoch @nlwashington ? It could really simplify the hierarchical display on the left side.

**Comment by boesb** [comment]
Completed. Right label column removed. Subsumer information in tooltip
