### ISSUE TITLE
ALL gene pages have error loading.

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#324]
this page:

http://monarchinitiative.org/gene/NCBIGene:7291

has an error.

it is linked from the main gene page.

**Comment by kshefchek** [comment]
It looks like all of the gene pages are failing at various calls to NIF (if I comment out one it fails at the next).  Have any changes been made to the content or perhaps the fetchURL function that could cause this?

**Comment by kshefchek** [comment]
Actually, it makes it through some of the queries to NIF and I start having issues when fetching disease and phenotype linkages, here is an example:

Fetching DiseaseGene Associations from OMIM (nif-0000-03216-7) for NCBIGene:1756
FETCHING: http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-03216-7.json data={"exportType":"data","count":1000,"q":"NCBIGene:1756","includeSubclasses":true,"project":["gene_id","gene_label","disease_id","disease_label","publication_label","publication_id","gene_ids","gene_labels","publication_ids","omim_id","omim_ids","omim_label","omim_labels"]}
RESULT: [object Object]
STATUS: 500
[object Object]
    at lib/monarch/api.js:4516 (anonymous)
    at lib/monarch/api.js:4445 (anonymous)
    at lib/monarch/api.js:2122 (anonymous)
    at lib/monarch/api.js:2003 (anonymous)
    at lib/monarch/api.js:789 (anonymous)

**Comment by nlwashington** [comment]
can you log this as blocker into the JIRA tracker?
assign to condit, and please tag anita, me, chris m, grethe, gupta.

**Comment by kshefchek** [comment]
I think this is related to the includeSubclasses flag, was this parameter deprecated?
http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-03216-7.json?q=%22NCBIGene:1756%22&includeSubclasses=true
I'll go ahead log this in Jira.

**Comment by kshefchek** [comment]
While investigating this I realized that running start-server-dev.sh still uses production NIF federation services.  Is the configuration correct in /conf/server_config_dev.json?
