### ISSUE TITLE
ortholog phenotype matrix viewer

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#325]
i would really like a new "ortholog" phenotype viewer, that is very similar to the phenotype matrix viewer.  here's what would go into it:

on any gene page, there are already a set of orthologs/homologs in the json blob.  i want the columns of the matrix viewer to be populated with the phenotypes for either the genes (first pass) or the genotypes (second pass) containing orthologs of the gene.

so, given the set of phenotypes for this gene (presumably aggregated from either the genotypes, variants, or diseases), do a pairwise comparison (there is a "compare" API call) to the phenotypes of the orthologs of the gene.  use the ortholog gene ids to fetch the phenotypes from their relevant organism (fetchPhenotypeInfo(gene_id)).  this will get you back the aggregated phenotypes for genes per organism.  this is a good first pass.  then, run the compare call between the two sets of phenotypes.  render in matrix.

the column header needs to make the species obvious...  so perhaps prefix the gene label with the species label, or consider coloring the text.  the overall score should probably be indicated (for the whole profile vs whole profile).

if the compare API call doesn't get you what you need, please log necessary requirements here, and assign this back to me.

**Comment by nlwashington** [comment]
@harryhoch here's the phenotype matrix viewer ticket to look at selected comparison targets.  while this ticket is specifically for an "ortholog" viewer, the same general methods would be used to compare a "query" set of phenotypes to any (user) selected set of targets.

**Comment by nlwashington** [comment]
you can now call the compare function to get back comparison data of any query entity to a set of targets.  this, combined with a function to fetch a set of orthologs (which we basically already have) is all that's necessary to generate a grid comparing orthologous gene/phenotypes.

**Comment by harryhoch** [comment]
ok. Let's try to discuss soon how we might implement this piece.

**Comment by mellybelly** [comment]
@harryhoch who should work on this? I added to May release.

**Comment by harryhoch** [comment]
Perhaps @davism84? Let's discuss tomorrow.

**Comment by kshefchek** [comment]
This is assigned to me but not sure that makes sense, @harryhoch feel free to reassign.  Moved to wishlist.

**Comment by harryhoch** [comment]
not implemented, but discussion moved to https://github.com/monarch-initiative/phenogrid/issues/135
