### ISSUE TITLE
duplicate gene associations

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#326]
One some diseases the gene tab has duplicates showing. for example:
http://monarchinitiative.org/disease/OMIM_259775
Probably because KEGG genes not mapped?

**Comment by kshefchek** [comment]
This should be fixed again (the changes should show up when we clear the disease cache).  However, we need to figure out a way to deal with duplicate diseases with different IDs.  For example, below we have the same disease with both OMIM and MESH IDs.
![screenshot from 2014-05-21 20 59 18](https://cloud.githubusercontent.com/assets/1467299/3048657/612e93b0-e14c-11e3-8a6f-6437a216d399.png)

**Comment by kshefchek** [comment]
Primary issue is fiixed, will make a new issue to address how to handle the same disease with different IDs.
