### ISSUE TITLE
Variant links are broken

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#327]
the OMIM links take you to OMIM, but not to a specific page. 
See for example the variants on this page:
http://monarchinitiative.org/disease/OMIM_259775

**Comment by cmungall** [comment]
This was fixed on dev already. Will be there next release

**Comment by kshefchek** [comment]
Duplicate of #245  (see example: http://tartini.crbs.ucsd.edu/disease/OMIM_259775)
