### ISSUE TITLE
button for feedback has issues on android

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#328]
See screenshot. Overlapping issues with tabs and button on android.
![screenshot_2014-05-02-17-55-33](https://cloud.githubusercontent.com/assets/5124411/2869221/eb32fa4a-d25d-11e3-9991-941a314192fb.png)

**Comment by kltm** [comment]
Since this is a flow issue, it can be similarly reproduced by making your browser window really small on any platform, including desktops.

**Comment by mellybelly** [comment]
yes there is a related ticket for this #200

**Comment by sarahjkim** [comment]
I actually already fixed this with commit 66cdc50c76d3488585ecc771021b33527ee5fe23. The changes haven't been pushed to the site yet though (I think).
