### ISSUE TITLE
models tab needs species indicated on phenotype pages

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#329]
for example on this phenotype page:
http://monarchinitiative.org/phenotype/MP:0005208
you don't know that these are mice

**Comment by sarahjkim** [comment]
@nlwashington The taxon object is not filled at the moment. I'm thinking the problem may be in fetchGenoPhenoAsAssociationsBySpecies in api.js, but you would probably know where things are better than I do. How should I go about fixing this?

**Comment by nlwashington** [comment]
You're right, this needed fixing upstream in the data.
So, I'm refactoring the views to include taxon_id/label in the phenotype tables.  
I will include fall-back mechanisms in the monarch-api based on view id, but it should be phased out.

**Comment by nlwashington** [comment]
ok, reindexing the data sources now (fish had an id, i added a label; i've updated mouse to include both id/label; worm already had the items).  they should be fixed on beta services soon.

**Comment by nlwashington** [comment]
in the mean time, go ahead and add a taxon column, and assume it will be part of the genotype object.

**Comment by nlwashington** [comment]
added defult taxon/fallback for when views don't contain the taxon information with commit 17e9651
