### ISSUE TITLE
broken genotype link

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#330]
the genotype links on the phenotype pages have an error.
for example on this page:
http://monarchinitiative.org/phenotype/MP:0005208
linking to this page:
http://monarchinitiative.org/genotype/MGI:2178287

**Comment by kshefchek** [comment]
This appears to be related to the includeSubclasses=true issue with NIF production.  When I run this locally using production services it fails at the first query that uses this parameter.  When I switch to beta federation services the page populates.  So this should be fixed when Larry deploys NIF beta to production (https://support.crbs.ucsd.edu/browse/NIF-10730)

**Comment by kshefchek** [comment]
The genotype pages are working now, please reopen if any pages are still showing an error.
