### ISSUE TITLE
Support JSONP?

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#332]
CORS support added via https://github.com/monarch-initiative/monarch-app/commit/fd1fe918272342afb1ed3d9865f20b07c18dacf3, which adds cors-middleware to ringo middleware chain. 

If CORS is deemed insufficient, we should add JSONP. Proposed steps:
1. revise all calls in webapp.js that call response.js to call formattedResults() instead, passing in .fmt as "jsonp" as needed.
2. Revise ajax calls in  modeltype widget and other reusable client-side  requests to use JSONP instead.

Note the CORS and JSONP are not mutually exclusive -both can be retained if desired.

**Comment by cmungall** [comment]
Is this required for the 06 milestone

**Comment by harryhoch** [comment]
No. @kltm expressed a preference for JSONP over CORS, but CORS works, is supported in the stick middleware configuration,  and can be hidden from the browser via jQuery Ajax calls, so we should be fine.
