### ISSUE TITLE
PARK4 no diseases/phenotypes?

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#333]
http://monarchinitiative.org/gene/NCBIGene_60454

**Comment by kshefchek** [comment]
This may be content related versus a programming issue, although the fact that it's not generating any results suspicious.  I haven't validated all of the NIF queries, but for disease relationships these calls all resulted in 0 hits.

http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-03216-7?exportType=data&q=%22NCBIGene:60454%22

Clinvar
http://neuinfo.org/servicesv1/v1/federation/data/nlx_151671-2?exportType=data&q=%22NCBIGene:60454%22

KEGG
http://neuinfo.org/servicesv1/v1/federation/data/nlx_31015-2?exportType=data&q=%22NCBIGene:60454%22

Orphanet
http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-21306-2?exportType=data&q=%22NCBIGene:60454%22

**Comment by kshefchek** [comment]
I've looked into this a little bit more...

Parkinson Disease 4, Autosomal Dominant (OMIM:605543) is linked to the gene SNCA (NCBIGene:6622).
Disease page: http://tartini.crbs.ucsd.edu/disease/OMIM_605543
Gene page: http://tartini.crbs.ucsd.edu/gene/NCBIGene:6622

This is the linkage that appears in OMIM.  On NCBI, SNCA is listed as AKA: PD1; NACP; PARK1; PARK4
So presumably these other gene symbols have been replaced with SNCA, but we now have multiple NCBI gene IDs for the same gene.  Should we attempt to deal with this programmatically (i.e. forward or pull content from other gene pages in this case) or do we need to validate NCBI gene with an alternative source to remove any "outdated" gene IDs.

**Comment by cmungall** [comment]
Ah yes I forgot that PRK4 was SNCA

Looking at
http://www.ncbi.nlm.nih.gov/gene?cmd=Retrieve&list_uids=60454

Maybe we just eliminate anything that isn't on the reference genome (either in DISCO or at time of triple dumping)? If we exclude this bogus record users can still find SCNA via a search for "PARK4" due to synonyms.

**Comment by nlwashington** [comment]
i believe this has been fixed.  we now see phenotypes for the original identifier in this list (probably because we look up equivalent gene identifiers via xref queries).
