### ISSUE TITLE
cleanup of phenotype tab

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#337]
the table view of the phenotypes (for a gene, or otherwise) is nice, but could use some love.

for example:

http://tartini.crbs.ucsd.edu/gene/NCBIGene_6469

there are many repeated phenotypes.  sometimes they are repeated because of citations (should these be collapsed?), sometimes they are repeated because of diseases that they are part of.  

but, also, it would be really nice if we could group this long list into something sensible, instead of just alphabetical.  consider grouping the terms, under some parent term (top-level HPO) or navigating with a graph/tree.  for example, "abnormality of nasopharynx" and "abnormality of the nose" ought to be grouped together.

even a little bit of grouping would go a long way.

**Comment by nlwashington** [comment]
now that i'm thinking about it, maybe even a summary table at the top of each page that fills in a square when a basic category has phenotypes would be good.

**Comment by cmungall** [comment]
great idea

implementation in the current arch. may be a bit tricky as the part that knows about the sub-phenotype categories (owlsim server) isn't typically invoked when building the phenotype list.

but the best long term solution may simply be to have a faceted browser, like amigo
http://amigo.geneontology.org/amigo/gene_product/UniProtKB:Q15465

it would be easy to have one facet be the sub-root node groupings for any ontology

**Comment by nlwashington** [comment]
also, need to make sure the count on the tab is accurate... right not it does not uniquify the phenotypes.

**Comment by jmcmurry** [comment]
I'm going to close this and open a new ticket
