### ISSUE TITLE
bogus no data found in analysis grid for many phenotypes

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#338]
from this page:
http://localhost:8080/gene/NCBIGene:20423

i clicked the "analyze phenotypes" button on the phenotype tab which opened another page where it did the analysis.  a table showed up of results, but the grid was empty.

![screen shot 2014-05-12 at 2 15 37 pm](https://cloud.githubusercontent.com/assets/5124411/2950431/b78ddb82-da1a-11e3-8fe7-24b461a47823.png)

it used this url:
http://localhost:8080/analyze/phenotypes/?input_items=MP:0009890+MP:0000875+MP:0006097+MP:0000854+MP:0000849+MP:0002066+MP:0001393+MP:0000880+MP:0000852+MP:0000873+MP:0002182+MP:0000886+MP:0000889+MP:0000872+MP:0004098+MP:0006098+MP:0002083+MP:0006030+MP:0002858+MP:0004315+MP:0003069+MP:0004369+MP:0000033+MP:0000041+MP:0003161+MP:0000554+MP:0002110+MP:0005104+MP:0000562+MP:0011087+MP:0009743+MP:0011089+MP:0004313+MP:0004354+MP:0004506+MP:0004509+MP:0004508+MP:0010701+MP:0001176+MP:0010907+MP:0001181+MP:0009887+MP:0009883+MP:0004538+MP:0005650+MP:0002151+MP:0001785+MP:0000914+MP:0000565+MP:0003054+MP:0000432+MP:0000090+MP:0002058+MP:0009937+MP:0000109+MP:0003743+MP:0004419+MP:0000926+MP:0005163+MP:0009901+MP:0000832+MP:0001265+MP:0004100+MP:0000939+MP:0000955+MP:0000934+MP:0001698+MP:0000830+MP:0000434+MP:0009584+MP:0001935+MP:0004274+MP:0004275+MP:0000851+MP:0001262+MP:0002175+MP:0005380+MP:0001297+MP:0002741+MP:0002109+MP:0005371+MP:0005430+MP:0004372+MP:0004358+MP:0008985+MP:0002765+MP:0002764+MP:0006279+MP:0005389+MP:0004007+MP:0003321+MP:0002191+MP:0009844+MP:0002950+MP:0006126+MP:0002633+MP:0005385+MP:0000774+MP:0004712+MP:0000551+MP:0003425+MP:0004201+MP:0000266+MP:0002135+MP:0002114+MP:0000428+MP:0003723+MP:0011090+MP:0000932+MP:0004880+MP:0001704+MP:0001691+MP:0011732+MP:0000937+MP:0005157+MP:0003984+MP:0004355+MP:0002728+MP:0000564+MP:0005109+MP:0000571+MP:0005606+MP:0002235+MP:0012270+MP:0001700+MP:0000270+MP:0003885+MP:0001730+MP:0011098+MP:0000291+MP:0004980+MP:0000925+MP:0002184+MP:0004173+MP:0002233+MP:0000141+MP:0004981+MP:0004200+MP:0000088+MP:0000137+MP:0000572+MP:0005306+MP:0000566+MP:0003932+MP:0000558+MP:0012139+MP:0005391+MP:0003012+MP:0001325+MP:0001286+MP:0001340+MP:0003634+MP:0001330+MP:0008056+MP:0000433+MP:0002234+MP:0001178+MP:0002264+MP:0004553+MP:0011024+MP:0001175+MP:0002282+MP:0003120+MP:0010975+MP:0006290+MP:0004251+MP:0002948+MP:0002060+MP:0001218+MP:0011109+MP:0002169+MP:0002115+MP:0004276+MP:0002006+MP:0000087+MP:0001293+MP:0000787+MP:0008540+MP:0002196+MP:0010059+MP:0009903+MP:0004872+MP:0004268+MP:0011380+MP:0000820+MP:0000780+MP:0000808+MP:0004277+MP:0012091+MP:0000074+MP:0009888+MP:0003451+MP:0002081+MP:0001718+MP:0001719+MP:0004180+MP:0009211+MP:0005384+MP:0003631+MP:0006042+MP:0000929+MP:0000639+MP:0002909+MP:0008291+MP:0002665+MP:0000646+MP:0001748+MP:0002768+MP:0008302+MP:0011011+MP:0004551+MP:0006382+MP:0010976+MP:0011086+MP:0008489+MP:0005386+MP:0005376+MP:0010897+MP:0010942+MP:0011071+MP:0009703+MP:0010915+MP:0001861+MP:0005388+MP:0010940+MP:0002691+MP:0002544+MP:0000561+MP:0002102+MP:0003953+MP:0006306+MP:0010771+MP:0003704+MP:0000377+MP:0000414+MP:0011101+MP:0000378+MP:0000388+MP:0000383+MP:0001243+MP:0011100+MP:0000468+MP:0010784+MP:0000150+MP:0004620+MP:0002543+MP:0000107+MP:0009204+MP:0000453+MP:0000547+MP:0001697+MP:0011108+MP:0000556+MP:0000455+MP:0000077+MP:0004442+MP:0000438+MP:0010030+MP:0004658+MP:0004507+MP:0000149+MP:0000159+MP:0004473+MP:0004423+MP:0005298+MP:0005296+MP:0000956+MP:0012089+MP:0000783+MP:0000557+MP:0000474+MP:0002116+MP:0000138+MP:0003345+MP:0002898+MP:0000164+MP:0012517+MP:0002932+MP:0004634+MP:0000166+MP:0003189+MP:0000163+MP:0001222+MP:0001219+MP:0003809+MP:0011028+MP:0010825+MP:0002284+MP:0001284+MP:0001302+MP:0000102+MP:0010994+MP:0005390+MP:0006402+MP:0005358+MP:0000094+MP:0000118+MP:0000128+MP:0000462+MP:0003283+MP:0006261+MP:0005493+MP:0000473+MP:0003271+MP:0003130+MP:0000495+MP:0005213+MP:0000467+MP:0000496+MP:0000767+MP:0001046+MP:0003793+MP:0005359+MP:0002650+MP:0002576+MP:0002818+MP:0004576+MP:0000897+MP:0008948+MP:0003424+MP:0009545+MP:0004137+MP:0003710+MP:0008004+MP:0002908+MP:0005381+MP:0001513+MP:0002874+MP:0001489+MP:0004269+MP:0012257+MP:0006197+MP:0000484+MP:0002726+MP:0011085+MP:0001732+MP:0004101+MP:0002064+MP:0003115+MP:0010949+MP:0001954+MP:0010768+MP:0002132+MP:0008789+MP:0000443+MP:0009905+MP:0003078+MP:0000460+MP:0002080+MP:0001406+MP:0010149+MP:0005643+MP:0000755+MP:0001399+MP:0001402+MP:0001906+MP:0008947+MP:0003244+MP:0011333+MP:0011378+MP:0005325+MP:0003672+MP:0011426+MP:0004505+MP:0000536+MP:0011360+MP:0003626+MP:0003446+MP:0002990+MP:0002989+MP:0000519+MP:0001672+MP:0003632+MP:0004196+MP:0005508+MP:0002127+MP:0005621+MP:0002092+MP:0012528&limit=100&target_species=10090

**Comment by cmungall** [comment]
This is what it looks like on production

![screen shot 2014-05-12 at 5 05 47 pm](https://cloud.githubusercontent.com/assets/50745/2952014/65e69284-da32-11e3-8ca4-1ae933c1c898.png)

**Comment by frdougal** [comment]
There is code on tartini that handles this situation more gracefully

**Comment by cmungall** [comment]
Looks better, but what is the situation exactly? The table view is fine

**Comment by boesb** [comment]
I'm getting a 413 Error on my localhost and now on tartini when I click on  the Grid View tab.

GET http://tartini.crbs.ucsd.edu/simsearch/phenotype...05621,MP:0002092,MP:0012528&target_species=10090

413 FULL head

**Comment by harryhoch** [comment]
Becky: 

I’m hoping that we can meet at noon and discuss this and the other issue. Will this suffice, or would you like to talk at 9 as well?

thanks,

harry

On May 12, 2014, at 9:26 PM, BeckyBoes notifications@github.com wrote:

> I'm getting a 413 Error on my localhost and now on tartini when I click on the Grid View tab.
> 
> GET http://tartini.crbs.ucsd.edu/simsearch/phenotype...05621,MP:0002092,MP:0012528&target_species=10090
> 
> 413 FULL head
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by nlwashington** [comment]
this is now blocked by #341

**Comment by harryhoch** [comment]
I think this is fixed
