### ISSUE TITLE
Replace Source with Image

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#34]
Could I get a list of the sources I need to make images for as well as a way to replace the strings with the images (API call?).

**Comment by nlwashington** [comment]
sites that we'll need icons for (not sure if all are necessary):
zfin.org
omim.org
human-phenotype-ontology.org
http://www.informatics.jax.org/  (mgi)
flybase.org
wormbase.org
http://www.ncbi.nlm.nih.gov/pubmed
http://decipher.sanger.ac.uk/
http://www.orpha.net
http://ccr.coriell.org

**Comment by cmungall** [comment]
We need the logos to show up for attribution on the right column e.g. in http://tartini.crbs.ucsd.edu/disease/DOID_14330
