### ISSUE TITLE
refactor gene-phenotype inference

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#342]
i think the methods employed to infer the phenotypes to a gene (via disease) may be missing some relationships (due to missing gene-disease relationships), as well as duplicating computations.

from what i can tell in the code, you're re-querying for gene-disease relationships in fetchOmimDiseasePhenotypeAsGeneAssocations, when the gene-disease relationships have already been fetched in fetchDiseaseGeneAssociations.  i believe you could just use the disease-gene relationships in the disease_associations object, to then query for the phenotypes attached to the disease ids.  this will also make the page render faster, since the same queries won't be performed twice.  (also the former only queries OMIM, but we need to be querying many resources, as shown in the latter.)

**Comment by kshefchek** [comment]
Ah ok, when I saw #341 I thought it might have to do with my original code not completely utilizing fetchDiseaseGeneAssociations() for this intermediate step.  I'll go ahead and update the code to pipe the IDs from this function to fetch gene-phenotype relationships.
