### ISSUE TITLE
remove/change inheritance from "phenotype" table

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#343]
I think listing the heritability in the phenotype table is confusing (as a row entry, not as a column entry).  for example:

http://localhost:8080/gene/NCBIGene:55636

has two entries for "autosomal dominant inheritance".

i think this should be a property of the disease (and for every phenotype that is part of the disease).  so, either it should be listed in a separate column, or it should be filtered out of the table.   this could be done by adding a filter on "aspect", to only get those of "O/organ abnormality"

also, because it is added as a phenotype association, it is being used in phenotype similarity queries, which i don't think is quite right (yet).  filtering it out of the query would take care of this.

**Comment by cmungall** [comment]
Seems reasonable. Can we add the filter at the level of the UI?

**Comment by harryhoch** [comment]
This page could benefit from a bit of rework...
1. If this is the CHD7 page, why does the name of the gene need to show in every row?
2. I agree that inheritance should be a property of the disease, not the gene, but I'm not sure what you mean by the "aspect".
3. If the phenotypes all associate with one disease, as in the table, do we need to list the disease every time?
4. More generally, the whole "phenotypic abnormality" subtree in HP certainly seems relevant to phenotypes, but they aren't really phenotypes per se, are they?
