### ISSUE TITLE
Showed marked up text in /annotate/text/ interface

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#344]
See http://tartini.crbs.ucsd.edu/annotate/text

The results list the spans. It should be possible to use these spans to show marked up text, with each span in the text hyperlinked to the concept, (with the ID shown in subscript?)

**Comment by nlwashington** [comment]
ooh, that sounds great.

**Comment by selewis** [comment]
sweet, 

assume picking the ontologies of choice is next (or using the ontology as a column header?)

**Comment by cmungall** [comment]
It can only use the ontologies that are loaded for the SciGraph instance, which on kato is the monarch.owl import chain. I think we could add new things to this chain there as needed (e.g. ENVO - even though it's not used within Monarch yet it doesn't do any harm to load it).

The API allows you to filter out categories but not ontologies - would not be hard as a post-processing step. But given that we are using a reasonably well-coordinated set of orthogonal ontologies it's useful to see them all a lot of the time. The main use case would be some kind of taxon based filtering (e.g. you wouldn't want to see Uberon whale terms, or a lot of WBPhenotype terms for a human medical text)

**Comment by cmungall** [comment]
There's actually scope for a lot of possible fun post-processing; for example, combining Es and Qs to make a class expression to find the closest matching pre-coordinated term; inferring disease-gene assocations based on proximity in the text... but we need text mining experts like @hdeitze and Anika to temper any naive ideas...

**Comment by sarahjkim** [comment]
I finished adding the marked up text view. Let me know what you all think! :)

![screen shot 2014-05-20 at 2 40 00 pm](https://cloud.githubusercontent.com/assets/4628853/3033665/666783b8-e067-11e3-94ea-95c45e165c55.png)
![screen shot 2014-05-20 at 2 40 04 pm](https://cloud.githubusercontent.com/assets/4628853/3033666/6668de34-e067-11e3-9508-b37af1913489.png)
![screen shot 2014-05-20 at 2 41 09 pm](https://cloud.githubusercontent.com/assets/4628853/3033688/7c9ffe30-e067-11e3-9b06-45e8efc3dfa0.png)
![screen shot 2014-05-20 at 2 40 06 pm](https://cloud.githubusercontent.com/assets/4628853/3033667/666abb1e-e067-11e3-9bab-b8705dea6d50.png)
![screen shot 2014-05-20 at 2 40 12 pm](https://cloud.githubusercontent.com/assets/4628853/3033668/666c141e-e067-11e3-9a8b-b06bfa2f39a4.png)

**Comment by nlwashington** [comment]
I've just submitted a request for an updated service that would allow for masking of certain kinds of words (such as articles or by length):  https://support.crbs.ucsd.edu/browse/NIF-10815

**Comment by cmungall** [comment]
Nice! I think we can call this one done.

**Comment by jgrethe** [comment]
Hi Chris,
Seems like the app page is picking up the stop words as well (“females in”).  

Cheers,
Jeff

On May 20, 2014, at 4:29 PM, Chris Mungall notifications@github.com wrote:

> Nice! I think we can call this one done.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by cmungall** [comment]
Was this for @ccondit or me? This is what the SciGraph instance on kato is returning to us...

**Comment by jgrethe** [comment]
Was to you (Chris M.) originally as I wasn't sure where the stop words were being picked up.

Added a new bug (#19) for this bug.

Cheers,
Jeff

On May 20, 2014, at 5:29 PM, Chris Mungall notifications@github.com wrote:

> Was this for @ccondit or me? This is what the SciGraph instance on kato is returning to us...
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.
