### ISSUE TITLE
RDF mapping generates AnnotationAssertionAxioms rather than ObjectPropertyAssertion axioms

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#345]
OK, one of the annoying features of working in a dual RDF and OWL world.

In RDF you just make bunches of triple S P O, etc

When this is mapped to OWL a few things happen. Formally, P must be explicitly mapped to one of
- AnnotationProperty
- DataProperty
- ObjectProperty

Now, the OWLAPI does some "repairing" behind the scenes, and assumes AnnotationProperty if none if specified

This results in S P O being treated as

```
 AnnotationAssertion(P S O)
```

Rather than

```
ObjectPropertyAsertion(P S O)
```

The latter is always what we want for things like gene-gene interactions. The latter is only for metadata we don't want to reason over (e.g. class S belongs to go slim O)

We will probably want different behavior in SciGraph too. Traversal generally makes more sense for OPA.

We can always force things to be OPs by pushing a triple into the mapping. Look at ncbi-gene-map.json for an example:

```
        "objects" : [
            {
                "id" : "RO:0002162",
                "rdf:type" : "owl:ObjectProperty"
            }
        ],
```

However, it's kind of tedious to assert this for all OPs in every mapping.

Ideally things would be smarter. We could have every derived triple set import RO which would solve the issue, but this complicates things (would rather avoid imports in the dumped ttl).

Maybe the mapper should simply assume that all predicates used to connect two individuals are OPs, unless overridden?

Until resolved, each conf file should have a declaration like the one above (sorry...)

**Comment by ccondit** [comment]
@cmungall Is this resolved to your satisfaction with the new SciGraph work?

**Comment by jmcmurry** [comment]
Just echoing the question. @cmungall Is this resolved to your satisfaction with the new SciGraph work? cc: @kshefchek
