### ISSUE TITLE
Phenotype tab label displays incorrect count

### ISSUE THREAD

**Issue by boesb** [monarch-initiative/monarch-legacy#347]
Question to Nicole:

I took a quick look at one other disease:  /disease/OMIM_105830 – Angelman Syndrome and found:

Phenotype Tab – says 58
There are actually only 50 unique phenotypes in the list
Human – 39 phenotypes (in viewer)
Mouse – 28 phenotypes (in viewer)
Zebrafish – 3 phenotypes (in viewer)

Is there a logical reason for the discrepancy?

From Nicole:

So, from what i can tell, for this disease, there are 48 unique phenotypes:
["Abnormality of the teeth", "Abnormality of the tongue", "Absent speech", "Autosomal dominant inheritance", "Behavioural/Psychiatric Abnormality", "Blue irides", "Brachycephaly", "Broad-based gait", "Cerebral cortical atrophy", "Clumsiness", "Cognitive impairment", "Constipation", "Deeply set eye", "Drooling", "EEG abnormality", "Exotropia", "Fair hair", "Feeding difficulties in infancy", "Flat occiput", "Hernia of the abdominal wall", "Hyperactivity", "Hyperreflexia", "Hypopigmentation of the skin", "Hypoplasia of the maxilla", "Incoordination", "Intellectual disability, progressive", "Intellectual disability, severe", "Limb tremor", "Macroglossia", "Malar flattening", "Mandibular prognathia", "Motor delay", "Muscular hypotonia", "Myopia", "Neurological speech impairment", "Nystagmus", "Obesity", "Paroxysmal bursts of laughter", "Postnatal microcephaly", "Progressive gait ataxia", "Protruding tongue", "Scoliosis", "Seizures", "Sleep-wake cycle disturbance", "Sporadic", "Strabismus", "Wide mouth", "Widely spaced teeth"]

clearly, the math on the tab header is not computing this right, it is not uniquifying the phenotypes before generating the count... that is a bug to fix

**Comment by nlwashington** [comment]
in the phenogrid, the differences are due to the fact that the smaller number are the only ones that match to the organism displayed.  therefore, there are may unmatched phenotypes (in the case of zfish that means 47 unmatched phenotypes!)

i will work on removing the redundancy in the count.
