### ISSUE TITLE
some classes i can't find (owlsim vs monarch)

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#350]
when i run an owlsim service, like:

http://owlsim.monarchinitiative.org/compareAttributeSets?a=HP:0001770&a=HP:0002650&a=HP:0002020&a=HP:0001263&a=HP:0002360&a=HP:0000718&a=HP:0002028&a=HP:0001985&a=HP:0100512&a=HP:0002342&a=HP:0000708&a=HP:0001290&a=HP:0001251&b=HP:0012450&b=HP:0001263&b=HP:0002020&b=HP:0003128&b=HP:0001943&b=HP:0001251&b=HP:0000733&b=HP:0000729&b=HP:0002307&b=HP:0002058&b=HP:0011410

i end up with some classes like:

```
"id": "NBO:0000243PHENOTYPE",
"IC": 3.09858746922118,
"label": "behavioral phenotype phenotype"

"id": "GO:0048878PHENOTYPE",
"IC": 3.046291971010673,
"label": "chemical homeostasis phenotype"
```

and if i try those identifiers directly, they don't have any data:
http://monarchinitiative.org/phenotype/GO:0048878PHENOTYPE
http://monarchinitiative.org/phenotype/NBO:0000243PHENOTYPE

is this an ontology syncing issue, or something else?

**Comment by cmungall** [comment]
syncing. 

it's in the beta OQ load
http://tartini.crbs.ucsd.edu/phenotype/GO:0048878PHENOTYPE

However, this load has not been used for making the closures, hence no data underneath yet

**Comment by mellybelly** [comment]
presumably not an issue?

**Comment by jmcmurry** [comment]
This appears to have been addressed; please reopen and clarify if not.
