### ISSUE TITLE
getPhenotypesOfOrthologs(geneid) API call

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#351]
In order to complete the ortholog matrix viewer for #325, we'll need a convenience API call that will fetch the phenotypes of all orthologs for a given gene.  This will wrap a series of inconvenient functions that will fetch the phenotypes by querying several NIF resources.  Some ID mapping may need to happen in order to get the function to happen correctly.

**Comment by cmungall** [comment]
replaced by #1257
