### ISSUE TITLE
reinstate ZP pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#356]
the ZP pages were turned off because there were issues with this ontology.  these need to be reinstated once we've solved the issues in jira:

https://support.crbs.ucsd.edu/browse/LAMHDI-353 and 
https://support.crbs.ucsd.edu/browse/LAMHDI-352

**Comment by cmungall** [comment]
Will test this after next closure load

**Comment by cmungall** [comment]
Order

1: Regenerate views to map to ZP IDs using http://purl.obolibrary.org/obo/zp/zp-mapping.txt
2: Redump Danio_rerio on phenotype-ontologies svn
3. Restart owlsim server (cjm)
4: Reindex for closures (cjm to coordinate with ccondit)

**Comment by nlwashington** [comment]
OK, @cmungall  NEED TURN TURN THESE BACK ON!

**Comment by cmungall** [comment]
Sorry, won't happen for some time. ZP doesn't work with our existing closure strategy. They are effectively root nodes as far as the closure is concerned.

**Comment by nlwashington** [comment]
sadness.

**Comment by nlwashington** [comment]
@cmungall, if we make the switch to scigraph, can we put ZP pages back in?

**Comment by cmungall** [comment]
Afraid the calculation of paths still explodes for federation queries. Need to discuss using golr strategy with @ccondit 

We can try reinstating the pages and see how they look but I think it will be unintuitive

**Comment by jmcmurry** [comment]
I believe that this has been resolved; please reopen if this is not the case.
