### ISSUE TITLE
add clinvar variant data

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#357]
we need to add the clinvar variant data into our interface.  ideally, we will use the HGVS notation for human variant labels that come from clinvar (#27).  we will need to make sure that we uniquify identical variants from clinvar and omim.  

@cmungall, what variant id shall we standardize on?  for the mods we don't typically have mappings to dbSNP (rs####) or dbVar, only the internal identifiers.  for clinvar, we usually have the dbSNP/dbSNV, but we would probably have an internal clinvar identifier.  i figure cascading priority:  (dbSNP, dbSNV, ClinVar, OMIM, other)

the data will be drawn from either nlx_151671-1, or a new one to be created by Bryan (based on the XML).  we could start on the nlx_151671-1, though some refactoring might need to happen.

**Comment by mellybelly** [comment]
for full display in the UI we'll need Mesh/UMLS integrated into our disease ontology. I suspect this is a july release item. Adding @ShahimEssaid
