### ISSUE TITLE
JSONP

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#36]
JSONP output from API calls may be needed for AJAX functionality for deployment of widget on non-Monarch sites.

**Comment by cmungall** [comment]
ringo 0.10 version of stick has jsonp support

**Comment by harryhoch** [comment]
https://github.com/monarch-initiative/monarch-app/commit/01a3f96f3ec074a04b3a1550f5cab2642dd859c0 contains preliminary fix, which should be replaced with ringo 0.10 when we upgrade.
