### ISSUE TITLE
CORS for owlsim.monarchinitiative.org

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#360]
Installation and configuration of the model widget in a third-party site will require access to an owlsim server specified in the javascript file. @cmungall, is it possible to enable CORS support on the OWLSim server?

**Comment by cmungall** [comment]
Are you talking to the owlsim server directly or via the monarch REST API?

**Comment by harryhoch** [comment]
No longer relevant -
