### ISSUE TITLE
consider always including orthologous genes in disease match grid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#361]
it might be really useful to show (maybe by optional selection) the orthologs of the known disease-causing gene.

the idea would be in the grid, we would add as fixed columns, the phenotype profiles of the orthologs of the known disease causing genes.  this would rely on a call such as #351.  it seems we might want to see the top hits in context to the orthologs.

**Comment by nlwashington** [comment]
so, let's say we're on a disease page.  the workflow for the grid would be:
1.  do a search for the similar matches by phenotype search (what's done now).
2.  given the list of orthologs for the gene(s) in the disease-associations, call directly the compare service for any of the genes that were not found in the above search, like .../compare/OMIM:12345/Gene:1+Gene:2+Gene:3...
3.  merge the lists together and sort.  (or put the orthologs first, as suggested by zfin.)

**Comment by harryhoch** [comment]
still undone, see https://github.com/monarch-initiative/phenogrid/issues/136 for further discussion
