### ISSUE TITLE
add overall model score to statically display

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#362]
In order to be more transparent about how relevant a whole profile match is in the phenogrid, statically displaying the similarity score and/or rank in a row at the top of the table/below the column header would be really useful (around where the oval is in the screenshot).  currently, this is only available when hovering.    it would give immediate feedback to the user about how close the hits are (often there is a big difference between the top hit and the successive ones).
![screen shot 2014-05-21 at 4 29 36 pm](https://cloud.githubusercontent.com/assets/5124411/3048071/23fea9c8-e140-11e3-848c-69302829c3d8.png)

**Comment by boesb** [comment]
Included in last commit: https://github.com/monarch-initiative/monarch-app/commit/95d404a00c4c18eee2e76ec62fa6c4489fe2e0a0

**Comment by nlwashington** [comment]
looks great.
