### ISSUE TITLE
add additional species for orthology

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#364]
In order to be able to link to and present the OMIA phenotype data, we'll need to make sure the orthology calls for all the OMIA species are pulled into our system.  

Currently I don't think we get those from PANTHER.  @cmungall how do we go about getting those other species from PANTHER, as i don't think they are in the standard ortholog file we ingest (horse, pig, cat, dog, etc)?  or should we use other orthology calls?  i might be able to get them from OMIA directly, if necessary.

**Comment by cmungall** [comment]
I was just speaking to Paul T an hour ago, didn't get this in time...

I guess homologene is the next port of call (I thought at least some of
those were in the 85 genomes covered by QfO and thus panther)

On Wed, May 21, 2014 at 4:41 PM, Nicole Washington <notifications@github.com

**Comment by nlwashington** [comment]
Well, on our site, this is what i see panther pulling:

http://tartini.crbs.ucsd.edu/gene/SOX9

and i see tons of data on sox9 orthologs here:
http://www.pantherdb.org/genes/gene.do?acc=HUMAN|Ensembl=ENSG00000125398|UniProtKB=P48436

and i only see selected organisms here:
https://neuinfo.org/mynif/search.php?q=Ensembl:ENSG00000125398&t=indexable&nif=nlx_84521-1&b=0&r=20

i pull the ref genome orthologs from a file here:
ftp://ftp.pantherdb.org/ortholog/9.0/

but there is another ortholog file (orthologs_HCOP.tar.gz).  do you think i should pull that instead?  (it's twice the size)

**Comment by nlwashington** [comment]
yep, those are in the bigger ortholog file.  i will work on pulling those records too. @kshefchek  i will assign this to me until the data issues are resolved.  see related data ticket in JIRA https://support.crbs.ucsd.edu/browse/LAMHDI-356

**Comment by nlwashington** [comment]
i have ingested the other file, and am building a view.  however, between the two ortholog files from the ftp site i list above, i can only find 21 species total.  i do not know where the rest of the 85 you speak of, @cmungall. 
here's what i got:
ANOCA,ARATH,BOVIN,CAEEL,CANFA,CHICK,DANRE,DICDI,DROME,HORSE,HUMAN,MACMU,MONDO,MOUSE,ORNAN,PANTR,PIG,RAT,SCHPO,YEAST

**Comment by nlwashington** [comment]
there's actually not all that much even with homologene.  ensembl compara, however, has many many more genomes (for SOX9 it has 68 orthologs):
http://uswest.ensembl.org/Homo_sapiens/Gene/Compara_Ortholog?db=core;g=ENSG00000125398;r=17:70117161-70122561;t=ENST00000245479

**Comment by nlwashington** [comment]
there do appear to be many more ortholog calls present in the panther interface than are available via download.  (for example, there are many species listed here that i do not have http://www.pantherdb.org/genes/gene.do?acc=HUMAN|Ensembl=ENSG00000095002|UniProtKB=P43246)

i have sent them an email asking how i can get them.

**Comment by nlwashington** [comment]
i have now added some of the basic other organisms (a total of 20), for example:
http://tartini.crbs.ucsd.edu/gene/Ensembl:ENSG00000152492

other species to be added after release.

**Comment by jmcmurry** [comment]
It seems like this issue may have been overtaken by events, if not directly resolved.
I'm not sure whether /gene/ is still meant to work with a label rather than an id, but I suspect not (http://tartini.crbs.ucsd.edu/gene/SOX9 equivalent would be beta.monarchinitiative.org/gene/SOX9 which does not work). We have loads of species in the system now, so I'm going to tentatively close this ticket. Please reopen and clarify if necessary.
