### ISSUE TITLE
updates to lit tab

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#367]
here's a few details that would be good to change on the new literature tab:
1.  need to add source column (what source made the annotation between the disease and the paper?)
2.  have the table start sorted in reverse chronological order (newest first)
3.  to save real estate, maybe just list the first 3 authors and then an et al.  perhaps the "et al" can be a toggle to expand if there user wants to see the rest of the author list.
4.  i think remove the pmid column.
5.  hyperlink the title of the paper, and have it go to pubmed.  this should be the widest column.  consider using the [more...] also if real estate is an issue.
6.  column order:  object | data type | title | year | authors | journal | source
7.  use the short form of the journal (i believe you get both a long and short form)
8.  maybe instead of "object" use "associated with" or something like that.
9.  make sure you uniquify the list of pubs (by pmid) when calculating the number in the tab (as you'll see repeats  of the same article via different objects).

**Comment by sarahjkim** [comment]
The NIF call appears to be missing some information (see commit message above for more details).
http://beta.neuinfo.org/services/v1/literature/pmid.json?pmid=20301714
http://www.ncbi.nlm.nih.gov/pubmed/20301714
