### ISSUE TITLE
Show penetrance, inheritance, and progression separately from phenotypes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#372]
I think it is confusing to have these characteristics in the same list as the phenotypes on a disease page. Its also not quite right to count these as phenotypes.  Can they be filtered to the top as a separate list? This can be accomplished by use of the HPO root nodes to sort them. Perhaps with a toggle to open/close the list?

For example on this page:
http://tartini.crbs.ucsd.edu/disease/OMIM_607060
there are "11 phenotypes", but three are not really phenotypes. When you go to the model viewer, you see only 7 (one is missing), that are proper phenotypes.

**Comment by sarahjkim** [comment]
It looks like this issue may have been resolved? I only see 8 phenotypes at the moment.

**Comment by nlwashington** [comment]
yep, this was resolved with commit d0ec9238e0ff4d7f2eacd599e95bd6caaf786541
