### ISSUE TITLE
keep phenotype profile in left column of grid view

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#373]
Even if there is no matches to phenotypes, it would be better to keep the query phenotype profile displayed in the left column. For example there are often not very good matches for zebrafish, but we want to see what is not matching.

**Comment by boesb** [comment]
Since there is no useful grid information for the non-matched phenotypes, would it make sense to display the non-matches outside of the grid in their own separate space – maybe there could be a button for “See Non-Matching Phenotypes” ?

**Comment by mellybelly** [comment]
yes I like this idea Becky.

**Comment by nlwashington** [comment]
i too like the idea of placing unmatched phenotypes (from the query) outside of the grid.  I feel like those phenotypes might get lost if they are at the bottom left-hand corner of the grid.  Can you try it with a show/hide non-matching phenotypes?  i suppose if you are to include them in the grid itself, you could grey them out (not sure if that's greyed text or grey background, to reflect that nothing matches them)

**Comment by boesb** [comment]
Fixed - "View Unmatched Phenotypes" toggle is below the grid.
