### ISSUE TITLE
Make fetchPubFromPMID calls more robust

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#374]
Currently builds are failing:
http://build.berkeleybop.org/job/check-monarch-urls/

here is the call:

```
FETCHING: http://beta.neuinfo.org/services/v1/literature/pmid.json?pmid= 14581620&pmid=20080219&pmid=16928994&pmid=11912187&pmid=11164829&pmid=12169661&pmid=2202907&pmid=10716451&pmid=14575238&pmid=16571625 data={}
RESULT: [object Object]
STATUS: 500
 FAILED 
```

This gives a 200 when I try it... it may be something to do with the stray space introduced before the first pmid? This may be a data problem needing fixed.

In any case, the consuming code should be defensive.

I recommend letting the httpclient object take care of URL construction - we shouldn't need to join on '&'

We should also add more fine grained unit tests.

**Comment by cmungall** [comment]
In fetchDiseaseInfo, I recommend replacing the substring-based methods with regexs.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions

**Comment by cmungall** [comment]
Hard to tell but I bet that dodgy pmid contains the annoying character you always get when you try and copy and paste an ID from the pubmed website...

**Comment by jgrethe** [comment]
Without the stray space in the beginning I am able to make the call can get the results:

[
{
"abstract":
"",
"affiliation":
[],
"authors":
[
"IbaÃ±ez-Tallon I",
"Gorokhova S",
"Heintz N"
],
"day":
15,
"grantAgencies":
[
"NIGMS NIH HHS",
"NINDS NIH HHS"
],
"grantIds":
[
"GM 07739",
"P01 NS 30532"
],
"hasAbstract":
true,
"journal":
"Human molecular genetics",
"journalShort":
"Hum. Mol. Genet.",
"meshHeadings":
[
"Animals",
"Axons",
"Disease Models, Animal",
"Dyneins",
"Female",
"Genetic Linkage",
"Humans",
"Hydrocephalus",
"Kartagener Syndrome",
"Male",
"Mice",
"Mice, Inbred C57BL",
"Mice, Inbred CBA",
"Mice, Knockout",
"Molecular Sequence Data",
"Mutagenesis, Insertional",
"Transgenes"
],
"month":
3,
"pmcid":
null,
"pmid":
"11912187",
"score":
0,
"snippets":
[],
"title":
"Loss of function of axonemal dynein Mdnah5 causes primary ciliary dyskinesia and hydrocephalus.",
"year":
2002
},
{
"abstract":
"",
"affiliation":
[],
"authors":
[
"Wagner C",
"Batiz LF",
"RodrÃ­guez S",
"JimÃ©nez AJ",
"PÃ¡ez P",
"TomÃ© M",
"PÃ©rez-FÃ­gares JM",
"RodrÃ­guez EM"
],
"day":
24,
"grantAgencies":
[],
"grantIds":
[],
"hasAbstract":
true,
"journal":
"Journal of neuropathology and experimental neurology",
"journalShort":
"J. Neuropathol. Exp. Neurol.",
"meshHeadings":
[

…

On May 24, 2014, at 12:54 PM, Chris Mungall notifications@github.com wrote:

> Currently builds are failing:
> http://build.berkeleybop.org/job/check-monarch-urls/
> 
> here is the call:
> 
> FETCHING: http://beta.neuinfo.org/services/v1/literature/pmid.json?pmid= 14581620&pmid=20080219&pmid=16928994&pmid=11912187&pmid=11164829&pmid=12169661&pmid=2202907&pmid=10716451&pmid=14575238&pmid=16571625 data={}
> RESULT: [object Object]
> STATUS: 500
>  FAILED 
> This gives a 200 when I try it... it may be something to do with the stray space introduced before the first pmid? This may be a data problem needing fixed.
> 
> In any case, the consuming code should be defensive.
> 
> I recommend letting the httpclient object take care of URL construction - we shouldn't need to join on '&'
> 
> We should also add more fine grained unit tests.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.
