### ISSUE TITLE
Closure not being used when querying phenotype by disease

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#375]
Pages like this show zero phenotypes:
http://tartini.crbs.ucsd.edu/disease/DOID_14330

It looks like the closure flag is not being used? Or something else going wrong?

Compare:

http://beta.neuinfo.org/services/v1/federation/data/nlx_151835-1.json?exportType=data&q=DOID:14330&includeSubclasses=true&limit=10

http://beta.neuinfo.org/services/v1/federation/data/nlx_151835-1.json?exportType=data&q=DOID:14330&includeSubclasses=false&limit=10

**Comment by nlwashington** [comment]
the top link (true) returns 129 results, while the other (false) returns zero.  is that not accurate?

**Comment by cmungall** [comment]
Yes, so my hypothesis is that somehow the "true" flag is not being set 
by api.js, but I haven't check this. Either way, the problem is not in 
fedeartion queries but downstream.
