### ISSUE TITLE
comparison method violates it's general contract

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#376]
I got a "Comparison method violates it's general contract" with this url:

http://tartini.crbs.ucsd.edu/gene/ENSEMBL:ENSG00000233816

I have absolutely no idea what that means!

**Comment by nlwashington** [comment]
This is also true with the NCBIGene version:
http://tartini.crbs.ucsd.edu/gene/NCBIGene:3447
But works fine on prod:
http://monarchinitiative.org/gene/NCBIGene:3447

**Comment by kshefchek** [comment]
This appears to be a java related error (from a quick google search) and it's tough to figure out without a stack trace.  I can't replicate it when I run it locally in both dev and production configurations.  Tried clearing the gene cache and this didn't work either.  Will investigate.

**Comment by cmungall** [comment]
It's somewhere in uniquifyResultSet

**Comment by cmungall** [comment]
Scratch that, I was wrong, it;s after

**Comment by cmungall** [comment]
OK, I know what this is. The reflexive case. Every element of the array is both before itself and after itself! Will fix
