### ISSUE TITLE
Grid view no longer works in phenotype profile searches

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#377]
E.g.

http://127.0.0.1:8282/analyze/phenotypes/?input_items=HP:0000164+HP:0000252+HP:0000717+HP:0000729+HP:0000733+HP:0001063

Click on 'grid view'

**Comment by harryhoch** [comment]
default taxon wasn't being set properly - fixed via https://github.com/monarch-initiative/monarch-app/commit/29d735bd366d95db6d2a2e37b7a63ae5a215d76e.
