### ISSUE TITLE
OMIM gene pages are loading as diseases

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#378]
OMIM gene pages (the ones with asterisks) are currently loading as diseases. For example:
http://monarchinitiative.org/disease/OMIM_611592
is actually the FARS2 gene:
http://www.omim.org/entry/611592
These should be ID mapped to EntrezGenes and resolved as genes, I believe.

I see the same on tartini, though I can see pathway mapping there based on the gene FARS2 relationship to the "disease"

**Comment by cmungall** [comment]
I think we should implement this via a redirect in webapp

ideally we would not have any data with omim-as-genes in the first place 
- ie. map in advance - but it's hard to avoid this

**Comment by mellybelly** [comment]
@kshefchek is this something you can help with?

**Comment by kshefchek** [comment]
Sure I can help with this.  For gene page redirects we could use nlx_152525-4.  @nlwashington  do we have a similar table for disease IDs and any other relevant data types?

**Comment by nlwashington** [comment]
yes, for genes, you can just look at 152525-4.

unfortunately, some omim diseases are synonymous with genes.  

for diseases, you'd (hopefully) query the ontology.

@cmungall maybe we should consider using a DOID as the preferred id instead of an OMIM id, esp in the cases where a geneid = diseaseid.

**Comment by kshefchek** [comment]
So what we need to do is query the ontology (via ontoquest?) and if the OMIM ID is not synonymous with a gene redirect the page to the appropriate NCBIGene page.  What would be the correct ontoquest query to determine if the OMIM ID represents a disease?

**Comment by nlwashington** [comment]
also, @mellybelly how are you getting to this?  where is this link that you clicked on?

**Comment by mellybelly** [comment]
Good question. 

autocompleting on FARS2 on prod takes me to an NCBI gene, and autocompleting on 'Combined Oxidative Phosphorylation Deficiency 14' takes me to an OMIM disease page.

Bad bug reporting on my part, it was probably a link from some phenotype match or phenotype page. I don't think I simply put the info into the URL, I ended up there. Will investigate further.

**Comment by nlwashington** [comment]
i think this is closed.
http://monarchinitiative.org/disease/OMIM_611592 does not resolve anymore.  however, http://monarchinitiative.org/gene/OMIM_611592 does resolve and is redirected to the NCBIgene page for FARS2.
