### ISSUE TITLE
pathways not showing up

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#379]
i think that @cmungall recent commit 017474bcddd7d586da869a485607e7fa5125ac55 to fix a closure has affected fetching pathways.

for example, i don't see any pathways here:

http://monarchinitiative.org/gene/NCBIGene:80326

**Comment by cmungall** [comment]
Yes, correct. Commit not yet in production, so this works:
http://tartini.crbs.ucsd.edu/gene/NCBIGene:80326
