### ISSUE TITLE
phenogrid: not showing values for some columns

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#383]
Example:

http://tartini.crbs.ucsd.edu/disease/OMIM_211800

The second column, Fam20a amongst others, has no cells lit.

Fam20a shares the phenotype of 'calcified arteries'.

Not sure if this is a UI issue or an OWLSim API call issue.

The fact there is a blank row seems suspicious

**Comment by boesb** [comment]
Fixed in latest commit: https://github.com/monarch-initiative/monarch-app/commit/95d404a00c4c18eee2e76ec62fa6c4489fe2e0a0
