### ISSUE TITLE
sorting of grid rows by frequency/usefullness

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#384]
the order of the rows in the grid might make a big difference to interpretation of display.

one way to order the grid would be to sort the rows by the simple count of the number of models that share that phenotype.  another would be to use the sum of the IC (of the LCS) of the row (descending), which would help to add a quality of uniqueness to the sorting.  this would push the most informative and the most used to the top.

(i thought this had already been implemented, but doesn't seem to have yet).

for example,

in http://localhost:8080/disease/OMIM_309350, 'full cheeks' has few models with that phenotype.  from what i can see, only 7 of the models actually have that phenotype (that is the number of squares filled in).  whereas 'hyperteleorism' has many more (already 14 in the top 25!).  clearly, the row for hyperteleorism should be listed above 'full cheeks'.

**Comment by boesb** [comment]
What you’re seeing now is the implementation of ranking of phenotypes based on the sum of the LCS scores from all models across one phenotype – in descending order.  But this may not be the most effective method.  I can try your first suggestion to see if works any better.

**Comment by boesb** [comment]
Three sort methods included: Alphabetize, Sums of LCS, # Model Matches 3c7ce08c656b9e8dee71a3ce740a198b9576b563
