### ISSUE TITLE
mini-map doesn't seem to reflect what's in the main phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#385]
I feel like the navigation map for the phenogrid doesn't exactly reflect what i see in the grid.

for one thing, in this shot from http://localhost:8080/disease/OMIM_309350, the minigrid has many more color variation than the main grid does.  the main grid only has the darkest blue colors, while the mini grid actually has the full spectrum of colors.
also, in the mini grid it looks as if there are some phenotypes that appear to be in every model, but when i look at the actual grid i do not see that pattern.  i certainly don't see it with the very faint color turquoise.

also, the grey highlighted area of the mini-grid might not actually reflect what we are seeing in the actual grid...  i find the rectangular shape odd when the viewable area is more-or-less square (or possibly even a rectangle in the other direction).
![screen shot 2014-05-29 at 9 18 21 am](https://cloud.githubusercontent.com/assets/5124411/3120091/443f128c-e74d-11e3-8454-52d52ff0af59.png)

**Comment by nlwashington** [comment]
here's another good example with just 4 phenotypes:
http://localhost:8080/disease/OMIM_185500

first, notice how the colors don't correspond between the two maps. in the main grid, it looks like the top row should be light blue, but the minimap has it being all dark blue; second, there's a whole bunch of whitespace between rows in the minimap; third, the whitespaces in the minimap just don't seem to correspond with the whitespaces of the same rows in the main grid.
![screen shot 2014-05-31 at 3 10 37 pm](https://cloud.githubusercontent.com/assets/5124411/3140257/713328a4-e910-11e3-8bce-82b59fc8d80c.png)

**Comment by nlwashington** [comment]
and another for http://localhost:8080/disease/OMIM_252010
here, it looks like what is in the first couple of rows is shown about 1/3 of the way down the minigrid.  it looks like there should be several other sparsely populated rows above the common dark blue ones.
![screen shot 2014-05-31 at 3 43 31 pm](https://cloud.githubusercontent.com/assets/5124411/3140335/17042e46-e915-11e3-9e26-20f678b831c0.png)

**Comment by boesb** [comment]
I’ll use one of these examples and try to deconstruct the map.

**Comment by nlwashington** [comment]
with reporting this, i'm just interested in making sure all the right data is rendered... so i just don't know if the discrepancies are errors in the main map, in the minimap, or something between the two.  i just want to make sure data isn't lost.  while the minimap may not stay around forever (though i think it can be useful as a grand topology of the disease), it is a good check/balance on the main grid.

**Comment by boesb** [comment]
When sorting of phenotypes was added, the sort needed to happen both in the grid and the minimap.  The minimap was not sorted so it didn't reflect the matches in the grid.  It is now sorted and matches the grid in the latest commit:  5b97968007281f4cedb2d18d2719f46e9e48740e
