### ISSUE TITLE
change labels for grid calculations

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#386]
i find the labels for the grid view calculation coloring confusing.  consider the following (please suggest a more succinct version of them):

'IC of subsumer' --> phenotype uniqueness
'euclidian distance' --> 'distance between phenotypes'
'information content similarity' -->  ratio of phenotype uniqueness of query and that in-common
(ok, this last one is really hard to write.  but 'IC similarity' is certainly a misnomer.)

**Comment by nlwashington** [comment]
most of this has been now implemented by @BeckyBoes.  can we try a further change, with nice concise labels, as we discussed on our call this week, and which is what is written up in the faq/popup/documentation:

Phenotype uniqueness --> Uniqueness
Distance between phenotypes --> Distance
Ratio of blah blah blah --> Ratio(q)

**Comment by boesb** [comment]
Fixed 3c7ce08c656b9e8dee71a3ce740a198b9576b563
