### ISSUE TITLE
add row header to indicate the score

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#387]
I like the new row with the overall model score.  Can you add a row header to indicate that it is a 'score', or 'similarity' or 'sim score' or something.

Also, maybe add a (?) link to explain what it is, with language something like:

The score indicated at the top of each column, below the target label, is the overall similarity score between the query and target.  Briefly, for each of the targets (columns) listed, the set of Q(1..n) phenotypes of the query are pairwise compared against all of the T(1..m) phenotypes in the target.  Then, for each pairwise comparison of phenotypes (q x P1...n), the best comparison is retained for each q and summed for all p1..n.  The raw score is then normalized against the maximal possible score, which is the query matching to itself.  Therefore, range of scores displayed is 0..100.  For more details, please see (Smedley et al, 2012 http://www.ncbi.nlm.nih.gov/pubmed/23660285 and http://www.owlsim.org).

**Comment by boesb** [comment]
Row of scores added with Informational text
