### ISSUE TITLE
allow users to fetch additional models (>100)

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#388]
right now the grid viewer is hard-coded to fetch the top 100 targets.  but i might want to see more.  is there a way to fetch more?  perhaps you can add a button to fetch the next 100?

**Comment by VincentIII** [comment]
This seems like an issue that would be outside of the Phenogrid code.  When in overview a limit of 10 per call is passed, where it will attach to the call only 10 each.  If you manually set a limit for when loading a single species, it will load that, but if you don't a limit (like what is happening now), it will auto default to 100 after the call is already made.  

I tried forcing the _loadSpeciesData function to load 150 instead when loading a single species and it does load upto 150 models, but the time it takes the load is noticeably longer.  This could be implemented into phenogrid easily with a text-field or some sort of controls in Phenogrid, but it might be wise to make sure that passing a number higher than the default doesn't cause other loading issues

**Comment by harryhoch** [comment]
not completed. discussion moved to https://github.com/monarch-initiative/phenogrid/issues/137
