### ISSUE TITLE
configurable row sorting in phenogrid.

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#389]
I think there are various ways that the rows can be sorted in the phenogrid to enhance usability, and we might want to leave that up to the user for their preference.  Some options that I might like to try are:

*alphabetical by phenotype label
*by count of models with matches in the row  (this is akin to frequency that it is seen in the subset of models being displayed)
*by IC (of the LCS phenotype, this is akin to the frequency of the phenotype in the whole corpus)
*by sum of all IC(LCS) matches in the row
*grouped by category  (you can't do that yet, but soon)

*we might also think about a sort that is weighted by the rank/score of the model it's in.  for example, a phenotype that is found only in the top 5 models would be displayed higher on the list than a phenotype that is only found in models 95-99.  

See related ticket #384.

**Comment by boesb** [comment]
Fixed - sort features have been added.
