### ISSUE TITLE
too much whitespace on header of phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#391]
i think there's waaaaaaay too much whitespace displaying above the phenogrid... at least a quarter of my screen is taken up with titles, select boxes, and mega whitespace.  

can we move things around to decrease the whitespace and fill it in with more of the good stuff (like data)?  the image below suggests some changes.  they are summarized as:
1.  remove the "similarity values based on" title ... this is basically redundant with the selection box
2.  move the title to be centered over the columns.  you might even consider just changing the label to "whatever the columns are, "Mus musculus genes" or whatever is selected.
3.  relabel "comparison organism" to "target".
4.  relabel "similarity calculation" to simply "display"
5.  move the selection boxes into the navigation bar on the right-hand-side of the grid.  there's already unused space there, so i think this would be a good place to use.
6.  the whole thing could then be moved up the page.

![screen shot 2014-05-29 at 3 04 20 pm](https://cloud.githubusercontent.com/assets/5124411/3124531/5130b92e-e77e-11e3-8969-86572e323365.png)

**Comment by boesb** [comment]
Fixed (Ongoing issue)
