### ISSUE TITLE
no matches show for some diseases!

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#396]
when i go here:

http://tartini.crbs.ucsd.edu/disease/OMIM_610158

nothing shows up on the matches tab (note i am using the modelviewer branch).

however, when i do the owlsim query for the phenotypes directly:
http://owlsim.crbs.ucsd.edu//searchByAttributeSet?a=HP:0000006&a=HP:0000969&a=HP:0007705&a=HP:0012038&target=MGI&limit=100

it retrieves several matches.

why aren't they being rendered?

@sarahjkim did this creep up with your recent change that closed #315?

**Comment by sarahjkim** [comment]
I didn't make any changes. I just closed #315 because I didn't see a problem with the number of models in the tab.

**Comment by nlwashington** [comment]
ok, @BeckyBoes, this is for you to troubleshoot then.  a must before the release...it is a critical bug.

**Comment by nlwashington** [comment]
i believe this might be for those diseases that don't have an id in the ontology (as evidenced by no disease name showing up in the jumbotron).  but i don't know why that would prevent the matches tab from loading correctly @cmungall.

**Comment by nlwashington** [comment]
ok, the new version of the ontology is loaded, and the jumbotron is behaving.  and still no matches show up in the grid.

@sarahjkim , i wonder if this is a consequence of the miscalculation of "matches".  currently, the matches count doesn't take into account the results of the phenogrid, probably because the phenogrid makes a separate call.  so, what to do here?  can we initially remove the thing that turns this tab off when the count is zero and then make this particular tab dependent on the phenotype tab (this tab should always show up if the phenotype tab has count > 0 or if the table count > 0)
