### ISSUE TITLE
all gene pages should redirect to NCBIGene, if possible

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#397]
when there is an unambiguous NCBI gene mapping for a gene or locus, all gene pages should redirect to their NCBI gene page.

for example:
http://localhost:8080/gene/MGI:2137594
should redirect to
http://localhost:8080/gene/NCBIGene:212996

**Comment by kshefchek** [comment]
Should I also redirect NCBIGene_1234 to NCBIGene:1234? I noticed that all gene pages in autocomplete have an underscore rather than a colon.
