### ISSUE TITLE
zfish models not rendering in grid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#399]
i can't seem to view the zfish models in the grid.  for example,
http://localhost:8080/disease/OMIM_142945
i chose Danio rerio, and the log showed it made a call like:

http://owlsim.monarchinitiative.org//searchByAttributeSet?a=HP:0000366&a=HP:0000006&a=HP:0000126&a=HP:0000272&a=HP:0000601&a=HP:0001360&a=HP:0003829&a=HP:0009914&a=HP:0011800&a=target&a=ZFIN&limit=100

but nothing rendered on the page...  it doesn't even look like there's an empty json coming back.
@cmungall is this a result of inhibiting zfish results, or some other problem?

**Comment by boesb** [comment]
Nicole, I’m debugging on /disease/OMIM_255800 right now for Zebrafish and I get results.

**Comment by harryhoch** [comment]
As do I, but IO see nothing for OMIM_142945.

Becky, please look into what comes up when there are no matches. I saw just the table, which was fine, but I also saw “FAQ”, which probably shouldn’t be there.

On 2 Jun 2014, at 12:39 PM, BeckyBoes notifications@github.com wrote:

> Nicole, I’m debugging on /disease/OMIM_255800 right now for Zebrafish and I get results. 
> 
> From: Nicole Washington [mailto:notifications@github.com] 
> Sent: Monday, June 02, 2014 12:37 PM 
> To: monarch-initiative/monarch-app 
> Subject: [monarch-app] zfish models not rendering in grid (#399) 
> 
> i can't seem to view the zfish models in the grid. for example, 
> http://localhost:8080/disease/OMIM_142945 
> i chose Danio rerio, and the log showed it made a call like: 
> 
> http://owlsim.monarchinitiative.org//searchByAttributeSet?a=HP:0000366&a=HP:0000006&a=HP:0000126&a=HP:0000272&a=HP:0000601&a=HP:0001360&a=HP:0003829&a=HP:0009914&a=HP:0011800&a=target&a=ZFIN&limit=100http://owlsim.monarchinitiative.org/searchByAttributeSet?a=HP:0000366&a=HP:0000006&a=HP:0000126&a=HP:0000272&a=HP:0000601&a=HP:0001360&a=HP:0003829&a=HP:0009914&a=HP:0011800&a=target&a=ZFIN&limit=100 
> 
> but nothing rendered on the page... it doesn't even look like there's an empty json coming back. 
> @cmungallhttps://github.com/cmungall is this a result of inhibiting zfish results, or some other problem? 
> 
> — 
> Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/399. 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by nlwashington** [comment]
the owlsim service call i pasted in the original ticket had an error, it should have been:

http://owlsim.monarchinitiative.org//searchByAttributeSet?a=HP:0000366&a=HP:0000006&a=HP:0000126&a=HP:0000272&a=HP:0000601&a=HP:0001360&a=HP:0003829&a=HP:0009914&a=HP:0011800&target=ZFIN&limit=100

thankfully, with the new build, this is no longer an issue.  both the service calls and the phenogrid work.  i'm closing this ticket until we find the bug elsewhere.
