### ISSUE TITLE
Add ZFIN genotype-phenotype associations

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#4]
Use nif-0000-21427-10

**Comment by cmungall** [comment]
Compare with: http://beta.neuinfo.org/mynif/search.php?q=cacna&t=indexable&nif=nif-0000-21427-10&b=0&r=20

**Comment by cmungall** [comment]
TODOs:
- fix inversion in post comps (e.g. spinal cord of axon) - the latest ZFIN export has these the correct way around
- fix json-ld/rdf export
- find better way to compact information

**Comment by nlwashington** [comment]
can this be closed?
