### ISSUE TITLE
This page displays nothing on the "overview" page

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#405]
http://monarchinitiative.org/disease/OMIM_615042

Not sure if something should be showing up there?

**Comment by nicolevasilevsky** [comment]
http://monarchinitiative.org/disease/OMIM_300884

Same with this page

**Comment by mellybelly** [comment]
@nlwashington this is related to not having any text related to that OMIM entry.

**Comment by mellybelly** [comment]
@cmungall also possible to get more from merged disease file once that work is done.
