### ISSUE TITLE
remove models without matches from getSimilarModels

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#407]
right now, for zebrafish matches to OMIM:255800, it gets a bunch of "matches" with a sim score of zero.  these should be removed from the api call results....  they should at least be filtered from the monarch api call, but maybe should even be removed upstream from the owlsim calls.

**Comment by cmungall** [comment]
agreed. This would be in findMatches() in OwlSim?

**Comment by nlwashington** [comment]
yep.  this could be done either with findMatches() in owlsim, or it could be in the monarch api simsearch which simply wraps the findMatches().

**Comment by nlwashington** [comment]
it's actually whatever the server call for searchByAttributeSet maps to.

**Comment by nlwashington** [comment]
when i tried to investigate this one, there are now MANY zebrafish matches (with the improved ZP), and so i'm having a hard time finding one with scores of zero.

so, this is not a good test case, and neither are many of the other diseases/phenotypes i've been trying.  (even fever,HP_0001945, gives matches!)

but i got to thinking; i bet that in that previous case, the reason those genes were returned is that one of the scores passed the basic owlsim filters, it's just that the combined score > 0.  therefore, i think it might be the responsibility of the monarch api to do the filtering, since it's what is setting the scoring metric.

**Comment by jmcmurry** [comment]
I'm not sure how best to investigate the status of this, so perhaps someone knows off the top of their head. Can this now be closed?

**Comment by nlwashington** [comment]
i think this might be fixed.  FWIW, fever doesn't have any matches...(though i don't think that's correct behavior).  closing for now; we'll reopen if it's not fixed.
