### ISSUE TITLE
502 error for grid view should display different error message

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#409]
When there is a 502 error returned by the owlsim server, the error message "no models found" is displayed.  This should probably say something else about, perhaps that the server is down for maintenance.  

This will probably require:
1.  throwing some kind of error in the monarch api simsearch, and returning that in the json
2.  dealing gracefully with errors by the phenogrid widget.

**Comment by harryhoch** [comment]
A generalizable solution would be preferable. 

Right now, this (and several other calls) worm their way down to engine.fetchUrl(), which does the actual http call. 

If a null result returns, fetchUrl simply creates an empty object, indistinguishable from a legitimate answer with zero results.

Suggest we add a "status" flag to the result object, passing through the result of the http status of the base call. This could (with a bit of munging) be passed through the api calls to the webapp calls and then on to the REST such as the phenogrid to handle when appropriate.

@cmungall , @nlwashington, @kltm  does this sound reasonable ?

**Comment by cmungall** [comment]
Not sure what you mean by null result.

If the result is 200 then the results are returned, and these should be trusted

If the result is != 200 then an error is thrown, with the HTTP status code, in the exception object

There is an argument for refactoring fetchUrl to always return an envelope

**Comment by cmungall** [comment]
But either way, phenogrid is deployed on the client and doesn't use api.js correctly, it's communicating via the monarch REST API, which will give a 5xx if an underlying service is down - so it's up to phenogrid how it handles these codes, no?

**Comment by harryhoch** [comment]
Yes, that's what I would have thought, but I think the problem is that we're not catching the error in the app.get('/simsearch'...) call. That's probably what needs to be done. @BeckyBoes , can you look into this?

**Comment by boesb** [comment]
Yes I will.

**Comment by harryhoch** [comment]
thanks.
On Jun 6, 2014, at 12:57 PM, BeckyBoes <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes I will.

**Comment by boesb** [comment]
Closed. c9d3f8a9221d815672fffac93b8d4f4218e42f8a
