### ISSUE TITLE
acknowledgments

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#41]
add NIH funding acknowledgment to about page and footer.

**Comment by cmungall** [comment]
transfer http://monarchinitiative.org/?q=node/3

**Comment by harryhoch** [comment]
fixed for home page in https://github.com/monarch-initiative/monarch-app/commit/01a3f96f3ec074a04b3a1550f5cab2642dd859c0. need footer for other pages.

**Comment by sarahjkim** [comment]
I'm a bit confused about the NIH Grant number. There is currently a different one on the tour page (which I took from the Drupal website). Does Monarch have two grants, or is the grant number in the footer the correct one?
![screen shot 2014-01-24 at 1 02 52 am](https://f.cloud.github.com/assets/4628853/1993274/6f8c1400-84d6-11e3-91e1-dd7a0c42e659.png)

**Comment by cmungall** [comment]
the grant # should be R24OD011883

**Comment by mellybelly** [comment]
Also the team is bigger than the funding, I would like to include Sanger and Charite. Will write some text for that here shortly.

**Comment by mellybelly** [comment]
How about:
The Monarch Initiative is a collaboration between OHSU, UCSD, LBNL, the University of Pittsburgh, Sanger, and Charité and is supported generously by a NIH Office of the Director Grant #5R24OD011883.

We should also make sure to include our Sanger and Charité collaborators on our team page. Will make some comments on that in a different ticket.
