### ISSUE TITLE
add taxon/species to simsearch results when no target_species specified

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#411]
In order to best display the results of multiple species in the phenogrid, it requires knowing what organism the results map to.  For each of the matches, the taxon (id,label) needs to be added.

**Comment by nlwashington** [comment]
also relates to #282 .

**Comment by nlwashington** [comment]
fixed in db3cd57712894e406dd9ae5cacc2f38b60e93cda

**Comment by boesb** [comment]
https://github.com/nlwashington, Do I need to remove the target_species parameter if I want "All" species?  If I just put an empty string in for target_species,(target_species="") I get back only Human results.

**Comment by frdougal** [comment]
You may need to check the ringo code.  We may have set a default taxon in there.  We never had a concept of All species before.  Search the ringo code for "9606".
Chuck

**Comment by boesb** [comment]
@nlwashington ,
In api.js:
 // set defaults
    if (typeof target_species == 'undefined') {
        console.log("ERROR: no target_species supplied. Defaulting to human, 9606.");
        target_species = '10090'
    };

But if I use an empty string it's not undefined.
Maybe it's this code that includes an empty string in the same way it does undefined and null?

if (typeof target_species !== 'undefined' && target_species != '' && target_species != null) {
      var target = species_to_filter_map[target_species].target_idspace;  // HARDCODE
      taxon = { id : 'NCBITaxon:'+target_species, label : species_to_filter_map[target_species].label };
    } 
    else { target = null };

**Comment by nlwashington** [comment]
ah, i just changed that defaulting code in my latest commit in searchByPhenotypeProfile, but neglected searchByDisease.  i'll fix it in searchByDisease, and hopefully that'll take care of it.

**Comment by nlwashington** [comment]
i believe the multi-species query is truly working now, in commit 79f906688a4987a75c803b06cdd8d481ddb4edf9
