### ISSUE TITLE
Optimize queries using SciGraph

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#412]
1. Examine logs to select a candidate data type that takes a long time to populate (typically caused by iterative pseudo-joins)
2. Ensure data is dumped as ttl
3. Specify desired behavior in high level graph terms
4. Implement over SciGraph and implement in portal as optional switch-in behavior

**Comment by jmcmurry** [comment]
@cmungall @kshefchek  Has this issue been addressed? It doesn't seem to have been looked at since at least March 2015, perhaps even since creation in 2014.
