### ISSUE TITLE
big bug in first row of phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#413]
the latest commit of the modelviewer code (which has row sorting) reveals some kind of bug in the phenogrid.  the first row has a bunch of boxes, which seem invariant no matter which sorting method is employed.  furthermore, the phenotypes that are shown when the intersection is displayed, often have nothing to do with the row header.

for example, for http://localhost:8080/disease/OMIM_305400
the row header says "widows peak"
but the hover says that for sox9b the query term is "hypoplasia of the maxilla".  additionally, the row for "hypoplasia of the maxilla" doesn't have this box filled in.  the same is true for many of the phenotypes in this row. 
also, notice that when the grid is moved around, the top row keeps the same number of filled in boxes, even though that is not how that row is supposed to look.
this seems to happen even when switching organisms or switching sort order.
![screen shot 2014-06-05 at 8 14 14 pm](https://cloud.githubusercontent.com/assets/5124411/3196330/f92840de-ed28-11e3-85ed-f4d35b354a84.png)
![screen shot 2014-06-05 at 8 21 26 pm](https://cloud.githubusercontent.com/assets/5124411/3196361/ae6c1b82-ed29-11e3-9b6b-3385b765560e.png)

**Comment by boesb** [comment]
Fixed 3c7ce08c656b9e8dee71a3ce740a198b9576b563
