### ISSUE TITLE
Phenogrid lost for some (non-leaf?) diseases

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#415]
I notice that we seem to have lost the phenogrid for some diseases, etc:
http://tartini.crbs.ucsd.edu/disease/DOID_14330

Compare with older version
http://monarchinitiative.org/disease/DOID_14330

Maybe something changed that stopped it working with non-leaf diseases?

**Comment by boesb** [comment]
@cmungall  It looks like the query  http://tartini.crbs.ucsd.edu/disease/DOID_14330 does not return any phenotypes for GET http://tartini.crbs.ucsd.edu/disease/DOID_14330/phenotype_associations.json

I also tried: http://tartini.crbs.ucsd.edu/disease/OMIM_607060 (Parkinson's) and it returned an array of phenotypes and the phenogrid showed up.

**Comment by cmungall** [comment]
Hmm,, that same json is used to build the html for the list of 
phenotypes on the page, odd...

**Comment by harryhoch** [comment]
believe this is working now with latest version of phenogrid
