### ISSUE TITLE
allow searching for off-window grid results

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#417]
when i'm on a grid for a disease:

http://tartini.crbs.ucsd.edu/disease/OMIM_255800

i can easily do a "find" in firefox for one of the genes that's in the visible window.  but what i'd REALLY like to do is do a find for a gene that might not be in the visible window. 

for example, Fbn1 is one of the results that doesn't show up in the initial window, it has a rank of 61.  i'd really like to be able to search for that gene in firefox, and the viewable window would advance me to that gene.

alternatively there would be a search box that would take me there.

**Comment by harryhoch** [comment]
still undone. discussion moved to https://github.com/monarch-initiative/phenogrid/issues/140
