### ISSUE TITLE
data disappeared for mouse Shh

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#419]
i went here:
http://localhost:8080/gene/NCBIGene:20423

and the only data that was rendered was for interactions and literature.

this definitely used to have phenotypes inferred from genotypes.

**Comment by nlwashington** [comment]
see also #341

**Comment by kshefchek** [comment]
If I start the server with production configurations it is loading data for all the tabs.  But most of the data has disappeared when using the beta configs.  I'll try to track down whats causing the discrepancy.

**Comment by nlwashington** [comment]
i believe the data between beta and prod has been indexed differently (different ontology closure).  so it's possible there might be real problems.  but it could be something else.  do let us know if you track down the issue.

**Comment by kshefchek** [comment]
It looks like beta queries are not working for some resources.  For example:
http://beta.neuinfo.org/services/v1/federation/data/nif-0000-00096-5?exportType=data&filter=gene_id:%22MGI:98297%22

Returns 0 results

http://neuinfo.org/servicesv1/v1/federation/data/nif-0000-00096-5?exportType=data&filter=gene_id:%22MGI:98297%22

Returns 270

**Comment by nlwashington** [comment]
wowzers.  i'll investigate.

**Comment by nlwashington** [comment]
ok, it looks like a difference in services running on beta and prod.  filters used to require quotes, but these seem to now not be necessary.  @ccondit, perhaps you can permit legacy quotes?  since we will have to modify our existing code to deal with removing the quotes, will the updated services be pushed to prod for our release?
so, @kshefchek the fix will be to remove the quoting() function when filtering.  i can make these updates in the api.js.

**Comment by ccondit** [comment]
I've updated the vocabulary services to ignore quotes around ID queries. This should resolve this issue.

**Comment by nlwashington** [comment]
@ccondit now i'm getting parsing errors for a subset of ids.  for example:
http://beta.neuinfo.org/services/v1/federation/data/nlx_151835-1.json?exportType=data&count=1000&q=*&includeSubclasses=true&filter=disorder_id:KEGG:ds-H00598
