### ISSUE TITLE
clean up repeated disease-gene rows for equiv ids

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#420]
on a page like:

http://localhost:8080/disease/OMIM_104300

the gene tab lists many disease-gene associations, and some seem like they might be different diseases, but they aren't.

for example, we see:
OMIM:104300 associated with APP
and we also see:
MESH:D0000544 associated with APP

however, the ontology says that these two ids are equivalent.

these should probably be collapsed into a single row.
this will probably require reconciling each item in the association table with the equivalence axioms (though they probably are already pulled into the page from the previous ontoquest call).

**Comment by nlwashington** [comment]
@kshefchek changed things up; now that this is working off of scigraph ontologies, any equivalent ids are grouped together.  This is as good as it's going to get for now, until KEGG ids get into the disease ontology.  Leaving open as a reminder.

**Comment by jmcmurry** [comment]
This is a duplicate, and overtaken by events.
