### ISSUE TITLE
add inheritance as disease property

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#425]
we removed inheritance as a "phenotype" for diseases, but it should be displayed for the disease as a whole.  this could be added in a few places:

jumbotron
on the overview tab.
on the phenotype tab, but as a standalone property

@cmungall @mellybelly or @pnrobinson do you have a preference for location of display for this info?

**Comment by pnrobinson** [comment]
Inheritance is shown at the top of the phenotypes list in OMIM, and so having it at the top of the list and separated by some CSS element might be an option...

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Nicole Washington [notifications@github.com]
Gesendet: Dienstag, 10. Juni 2014 00:22
An: monarch-initiative/monarch-app
Cc: Robinson, Peter
Betreff: [monarch-app] add inheritance as disease property (#425)

we removed inheritance as a "phenotype" for diseases, but it should be displayed for the disease as a whole. this could be added in a few places:

jumbotron
on the overview tab.
on the phenotype tab, but as a standalone property

@cmungallhttps://github.com/cmungall @mellybellyhttps://github.com/mellybelly or @pnrobinsonhttps://github.com/pnrobinson do you have a preference for location of display for this info?

**Comment by nlwashington** [comment]
(it was removed from phenotype tab in #343.)

**Comment by mellybelly** [comment]
I like the idea of having it in the jumbotron.
