### ISSUE TITLE
add genes tab to phenotype pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#426]
on a page like:

http://localhost:8080/phenotype/MP_0001322

it would be nice to have a genes tab to list all of the genes that are associated with this phenotype, as direct associations or inferred from genotypes/diseases.  we may already have that information in the json blobs, but need to populate it here.

it should include:

phenotype | gene | taxon | association | evidence

where the association is either direct (from a gene-phenotype or variant-phenotype) or inferred via a genotype-phenotype or variant-disease/disease-phenotype.

optionally add cytogenic band or chromosome.

**Comment by sarahjkim** [comment]
Notes to Self:
Basic gene tab is on pheno-gene-tab branch.

To Do:
1. Add genes associated with genotype by genotype-phenotype association.
2. Limit number of diseases (and genotypes) fetched by significance of phenotype to disease/genotype. (Need association strength score of some sort like #443 for this.)
3. Need filter for duplicate genes. Some diseases return duplicate genes, and some genes are associated with multiple diseases. I should definitely get rid of duplicate genes with same disease, but I think I will keep genes associated with multiple diseases.
