### ISSUE TITLE
unmatched phenotypes button multiplies

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#427]
the unmatched phenotypes button multiplies when i redraw the grid.

for example, on http://localhost:8080/disease/OMIM_114290

it redrew the grid twice; first by resorting the rows, then by changing species.

![screen shot 2014-06-10 at 8 47 05 am](https://cloud.githubusercontent.com/assets/5124411/3232731/97280478-f0b6-11e3-97a9-7db976f813f1.png)

**Comment by nlwashington** [comment]
also, it causes the target/display menus to move wildly.  (this is after 12 redrawings)
![screen shot 2014-06-10 at 8 55 51 am](https://cloud.githubusercontent.com/assets/5124411/3232866/c5ad45c8-f0b7-11e3-931a-0ae5f0858ae6.png)

**Comment by boesb** [comment]
Fixed in 33bca4538c04ab0ae154bf3092b227c179b1353e
