### ISSUE TITLE
error in species label for matches in phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#428]
with the new species added to the phenogrid, it seems to get the identifier right, but the label wrong.  (the label says something about owlsim)

@BeckyBoes is this a pure display issue, or is the data you're getting wrong?

![screen shot 2014-06-10 at 8 53 21 am](https://cloud.githubusercontent.com/assets/5124411/3232816/64f05e5a-f0b7-11e3-90d9-94a7cf24c201.png)

**Comment by boesb** [comment]
Looks like it may be wrong data in the response:
The query below returns taxon objects like this:  "taxon":{"id":"NCBITaxon:10090","label":"OwlSim Server: http://owlsim.crbs.ucsd.edu/"}  (other examples below)

http://localhost:8282/simsearch/phenotype/?input_items=HP:0002104,HP:0000006,HP:0000126,HP:0000175,HP:0000238,HP:0000256,HP:0000260,HP:0000274,HP:0000316,HP:0000347,HP:0000348,HP:0000365,HP:0000369,HP:0000581,HP:0000878,HP:0000882,HP:0000883,HP:0001252,HP:0001508,HP:0001561,HP:0001762,HP:0002098,HP:0002564,HP:0002751,HP:0002786,HP:0002827,HP:0002866,HP:0003038,HP:0005035,HP:0005257,HP:0005280,HP:0006390,HP:0006628,HP:0008434,HP:0008477,HP:0008921,HP:0011910,HP:0012245,HP:0012745&target_species=10090

,"b":[{"id":"MGI:1920480","label":"Bmper","taxon":{"id":"NCBITaxon:10090","label":"OwlSim Server: http://owlsim.crbs.ucsd.edu/"},"matches":[{"b":{"id":"MP:0004463","IC":14.179416295466261,"label":"basisphenoid bone foramen"},"a":

{"id":"MGI:1927616","label":"Trps1","taxon":{"id":"NCBITaxon:10090","label":"OwlSim Server: http://owlsim.crbs.ucsd.edu/"},"matches":[{"b":{"id":"MP:0002427","IC":11.053128168162022,"label":"disproportionate dwarf"},"a":bud 

{"id":"MGI:1347466","label":"Foxc1","taxon":{"id":"NCBITaxon:10090","label":"OwlSim Server: http://owlsim.crbs.ucsd.edu/"}

**Comment by nlwashington** [comment]
ok, i've fixed this on master. @BeckyBoes please merge and verify that it's fixed.

**Comment by boesb** [comment]
@nlwashington code merged in 33bca4538c04ab0ae154bf3092b227c179b1353e
Fixed #428,#429
