### ISSUE TITLE
species undefined for "all" selection in phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#429]
on http://localhost:8080/disease/OMIM_114290, i selected to view "all" species in the phenogrid, and noticed that the species is listed as undefined, whether it was a disease or a gene.  (both are in the list; for example, Trps1 is a mouse gene at a score of 67, most others are a human disease; it is undefined for both)

![screen shot 2014-06-10 at 8 58 04 am](https://cloud.githubusercontent.com/assets/5124411/3232903/2c10c466-f0b8-11e3-8fb5-aae0d547a79a.png)

**Comment by boesb** [comment]
Fixed in 33bca4538c04ab0ae154bf3092b227c179b1353e
