### ISSUE TITLE
jquery-ui flakiness causing bug

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#43]
some pages return an error similar to the following:

Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost:8080/css/images/ui-bg_flat_75_ffffff_40x100.png

I think this has something to do with the way that jquery-ui is being used. It should probably be installed from scratch as per instructions.

**Comment by harryhoch** [comment]
possibly related to https://github.com/monarch-initiative/monarch-app/issues/78

**Comment by kltm** [comment]
This is simply because the style image set associated with the theme is not in the path (or maybe not there at all). #78 is more due to a problem with a file not being properly in the distribution.
