### ISSUE TITLE
Consider more abstract templating system (too much repeated structure)

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#433]
When adding code to all dynamic pages, as of this writing, over thirty templates had to be changed. I /think/ I got them all, but it's hard to be sure.

A better system might be to use a few common major shells, which then have JS, CSS, and content loaded into them. This would allow larger structural changes to be rolled out uniformly and quickly, while still allowing CSS and styling to be handled easily like they are now.

A system like this almost exists with addCoreRenders(). As an example (unfortunately on node), the pup tent femto framework could be a possible model: https://github.com/kltm/go-mme/blob/master/js/pup-tent.js

I'm not wanting to try a code drop here since it would be disruptive playing with some core bits that people are used to, but it might be worth thinking about as more pages are produced.

**Comment by harryhoch** [comment]
@kltm does pup_tent take care of this?

**Comment by kltm** [comment]
Closed or mostly closed, depending on how you look at it. I'm not sure how much of the code has been converted to pup_tent, @kshefchek was handling a lot of that. If it is mostly converted, and people used and extend it moving forward, I think it's done.

**Comment by kshefchek** [comment]
Everything in webapp.js has been switched to using pup_tent.  Although we need to update
https://github.com/monarch-initiative/monarch-app/blob/master/templates/monarch_base.mustache
to look more like
https://github.com/monarch-initiative/monarch-app/blob/master/templates/labs/blog-scratch-base.mustache
But we can break this out into a new issue.
