### ISSUE TITLE
add disease label to phenogrid phenotype list

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#434]
Please add the Disease label where it says "Phenotype profile" , so for example on the Angelman's page you'd write:

"Angelman's Disease Phenotype Profile" on the left side above the list of phenotypes. 

Basically, as you are scrolling around you forget which page you are on and this needs to be clearer.
Thanks -m

**Comment by boesb** [comment]
In latest phenogrid release.
