### ISSUE TITLE
color code the scores on phenogrid

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#435]
It would be great if there was some richness/higher score color indication on the matching diseases - e.g. make the best matching genes colored on the best score on the color scale. Right now its not clear that the best match is on the left.

**Comment by mellybelly** [comment]
@harryhoch consider some text or static wedge shape visual to indicate that best matches are towards the left. This can be placeholder before really fixing this ticket.

**Comment by harryhoch** [comment]
@mellybelly, how does this look? Please suggest any changes...
![pg-colors](https://cloud.githubusercontent.com/assets/174707/5137886/848eb060-7111-11e4-8b18-5178bb23a7e3.png)

**Comment by harryhoch** [comment]
closed via https://github.com/monarch-initiative/phenogrid/commit/f09e666f96de18630ff141034cc87a5790f76ba7

**Comment by mellybelly** [comment]
Better with the colors matching. maybe also a text statement at the top?
_best matches left to right_ or the like
