### ISSUE TITLE
highlight row/col headers when highlight over col/row

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#436]
when i highlight a phenotype (row) header, i would like the column headers highlighted where the phenotypes are actually filled in.  for example, 
http://localhost:8080/disease/OMIM_105830
(this is vs danio rerio)
if i highlight "brachycephaly", i want the matching gene cols highlighted, otx5, sox9b, end1, ext2, etc...

similarly, if i highlight the column otx5, i want the rows bracycephaly and sleep-wake cycle disturbance to be highlighted.

![screen shot 2014-06-14 at 11 13 05 am](https://cloud.githubusercontent.com/assets/5124411/3278186/ed7abb42-f3ac-11e3-827f-76e0f9baeab6.png)

**Comment by harryhoch** [comment]
This is a great idea - kickng myself for not having thought of it earlier. @BeckyBoes , can you look into this? Thanks.

**Comment by boesb** [comment]
Completed in 19e39a24017c2ec85731c21dbd359c7669a4a351
