### ISSUE TITLE
relabel row sorting

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#439]
Please relabel the row sorting to be more informative:

"Model matches" --> frequency
"LCS sums" --> frequency+uniqueness

and keep alphabetic the same.

**Comment by boesb** [comment]
Changed to:
Frequency 
Frequency + Rarity (6/26 request @nlwashington)

Fixed in latest modelviewer branch f17775ea067b1d5423be45640c730680faca34b8
