### ISSUE TITLE
Alleles object in gene JSON blobs incomplete

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#444]
The allele objects in gene JSON blobs don't appear to be well-formed.
1. info.allele[i] has both variant.variant_type and type. variant_type is empty while type is a string.
2. info.allele[i] does not have references though widgets.js is calling references in the evidence column.
![screen shot 2014-06-20 at 4 52 37 pm](https://cloud.githubusercontent.com/assets/4628853/3347144/fd1af53e-f8d5-11e3-86e8-2709058b799a.png)
![screen shot 2014-06-20 at 4 53 40 pm](https://cloud.githubusercontent.com/assets/4628853/3347153/33fdd15c-f8d6-11e3-9371-db4f77c7b3e1.png)

**Comment by nlwashington** [comment]
closing for now
