### ISSUE TITLE
missing monarch icon

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#446]
From Orion/Phenotips:
Just noticed that the Monarch logo displayed in the "What's this?" dialog for the specificity meter is broken. Apparently this URL is no longer valid?
    http://monarchinitiative.org/sites/all/themes/monarch/logo.png
Where should phenotips pull our icon from?

**Comment by sarahjkim** [comment]
http://monarchinitiative.org/image/logo.png
