### ISSUE TITLE
Many pages contain 404 and other failing links

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#448]
Updated report below:
https://github.com/monarch-initiative/monarch-app/issues/448#issuecomment-65167814
<strike>https://github.com/monarch-initiative/monarch-app/issues/448#issuecomment-60824096 </strike>

<strike>
I've run the check spider over tartini, with a weight towards novelty:
Current Tanuki status:
Base URL: http://tartini.crbs.ucsd.edu
Started at: 15:11:28 on Friday, 6/27/2014 (GMT-8)
Known external pages: 1869
Known internal pages: 4308
Collected argument sets: 7040
Attempted page visits: 508
Total good pages: 451
Total flagged pages: 40
Total error pages: 17
Total odd pages: 0
As you can see, during the process there were many problems found ("flagged" in this case mostly means 404). Specifically, completely bad links were found at:
Code: NULL
Reference: http://tartini.crbs.ucsd.edu/genotype/ZDB-EXP-041102-1
URL: http://tartini.crbs.ucsd.edu/reference/ZFIN:ZDB-PUB-131119-2
Variations repeated another 16 times.
And 404s with:
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/geneMap/15/33?highlight=33&limit=10&start=-3
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/search/advanced/clinicalSynopsis
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/statistics/geneMap
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/statistics/update
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/search/advanced/entry
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/search/advanced/geneMap
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0006
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/search/advanced/clinicalSynopsis
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/search/advanced/clinicalSynopsis
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/statistics/entry
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0011
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0008
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/search/advanced/entry
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/statistics/update
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/statistics/geneMap
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0002
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/geneMap/15/33?highlight=33&limit=10&start=-3
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/geneMap/15/33?highlight=33&limit=10&start=-3
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/statistics/geneMap
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0009
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/about
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0007
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0010
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/search/advanced/entry
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0004
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0007
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:300005.U
URL: http://tartini.crbs.ucsd.edu/geneMap/X/765?highlight=765&limit=10&start=-3
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/statistics/update
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/search/advanced/geneMap
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/api
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:300203.U
URL: http://tartini.crbs.ucsd.edu/allelicVariant/300203
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0002
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/downloads
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/allelicVariant/601623
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/help/linking
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/search/advanced/geneMap
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0007
URL: http://tartini.crbs.ucsd.edu/statistics/entry
Code: 404
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM_105830
URL: http://tartini.crbs.ucsd.edu/allele/OMIM:601623.0005
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/external
Code: 404
Reference: http://tartini.crbs.ucsd.edu/variant/OMIM:601623.0003
URL: http://tartini.crbs.ucsd.edu/downloads
The problems were a bit more varied on a few base pages, with some important seeming pages like "about" apparently not there.
</strike>

**Comment by mellybelly** [comment]
@kshefchek maybe you can help with this?

**Comment by kshefchek** [comment]
Sure, I see a lot of these are coming from variant pages, which are all redirecting to OMIM per #245, so I'm not sure if we should punt these for now since the user will never have access to these broken links.

As for the http://tartini.crbs.ucsd.edu/about, the correct URL would be http://tartini.crbs.ucsd.edu/page/about .  I'm guessing we changed the path to the about page at some point and this hasn't been updated in the variant template yet.

**Comment by kltm** [comment]
Updated report below:
https://github.com/monarch-initiative/monarch-app/issues/448#issuecomment-65167814

<strike>
Current Tanuki status:
Base URL: http://tartini.crbs.ucsd.edu
Started at: 10:59:50 on Tuesday, 10/28/2014 (GMT-8)
Known external pages: 600
Known internal pages: 3602
Collected argument sets: 4857
Attempted page visits: 830
Total good pages: 272
Total flagged pages: 555
Total error pages: 3
Total odd pages: 0
Pages that have clear serious errors (3):
Reference: http://tartini.crbs.ucsd.edu/phenotype/HP:0002322
URL: http://purl.obolibrary.org/obo/HP_0002322
Reference: http://tartini.crbs.ucsd.edu/page/about
URL: http://human-phenotype-onotology.org
Reference: http://tartini.crbs.ucsd.edu/model/ZFIN:ZDB-GENO-120411-226
URL: http://tartini.crbs.ucsd.edu/reference/ZFIN:ZDB-PUB-120207-1
The bulk of the "flagged" pages seem to have something to do with how redirects are stored in the spider (I'll fix it in the next version). However, there are some serious problems that need attention; a sampling is:
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM:305600
URL: http://tartini.crbs.ucsd.edu/variant/ClinVarInternalMeasureID:25739
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM:615524
URL: http://tartini.crbs.ucsd.edu/model/WBStrain:VC1703
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM:230800
URL: http://tartini.crbs.ucsd.edu/model/OMIA:000405-9940-222
Reference: http://tartini.crbs.ucsd.edu/disease/OMIM:230800
URL: http://tartini.crbs.ucsd.edu/variant/dbSNP:80356759
Reference: http://tartini.crbs.ucsd.edu/phenotype/HP:0002322
URL: http://tartini.crbs.ucsd.edu/disease/KEGG:ds-H01118
Reference: http://tartini.crbs.ucsd.edu/genotype/MGI:3053578
URL: http://tartini.crbs.ucsd.edu/variant/MGI:3053095
Reference: http://tartini.crbs.ucsd.edu/page/services
URL: http://tartini.crbs.ucsd.edu/phenome/
Reference: http://tartini.crbs.ucsd.edu/page/services
URL: http://tartini.crbs.ucsd.edu/docs/files/web/webapp-js.html
Also, with a two-thread spider (two users doing click load, click load), I apparently managed to occasionally overload the server enough to get response errors.
</strike>

**Comment by kltm** [comment]
@cmungall @kshefchek I've updated the report on the site.

**Comment by nlwashington** [comment]
@kshefchek some ids will no resolve in scigraph (in the near future), such as dbSNP:76763715.  however, the code doesn't catch the 404 and continue to redirect to the variant page.  can we make this happen?  (@cmungall & @ccondit, what should be the right behavior here?  the solution would be to either 1-make all identifiers resolve in the graph or 2-fall through and assume that the identifier is okay for the type.)

**Comment by nlwashington** [comment]
"ClinVarInternalMeasureID" will never resolve... i will catch those and not put in links....data source will be adjusted to use other identifiers that will resolve (which will be done in another week, when we get access to NIF re-indexing)

**Comment by kltm** [comment]
@cmungall I fixed a few annoyances in tanuki and spidered http://stage.monarchinitiative.org; the results were not too good:

```
Current Tanuki status:
Base URL: http://stage.monarchinitiative.org
Started at: 16:35:20 on Monday, 12/01/2014 (GMT-8)
Known external pages: 3025
Known internal pages: 9100
Collected argument sets: 13253
Attempted page visits: 227
Total good pages: 160
Total flagged pages: 66
Total error pages: 1
Total odd pages: 0
```

The one "error" seems to be some redirect issue around the link actually redirecting to the unusable http://www.monarch-initiative.org/ZDB-PUB-120207-1:

```
Reference: http://stage.monarchinitiative.org/model/ZFIN:ZDB-GENO-120411-226
URL: http://stage.monarchinitiative.org/reference/ZFIN:ZDB-PUB-120207-1
```

The "flagged" issues tended to be 500s, with a sampling along the lines of:

```
Reference: http://stage.monarchinitiative.org/phenotype/HP:0010669
URL: http://stage.monarchinitiative.org/disease/ORPHANET:85174

Reference: http://stage.monarchinitiative.org/phenotype/MP:0001914
URL: http://stage.monarchinitiative.org/disease/ORPHANET:98880

Reference: http://stage.monarchinitiative.org/gene/NCBIGene:7046
URL: http://stage.monarchinitiative.org/variant/dbVar:nsv532403

Reference: http://stage.monarchinitiative.org/gene/NCBIGene:7046
URL: http://stage.monarchinitiative.org/variant/dbSNP:121918713

Reference: http://stage.monarchinitiative.org/phenotype/HP:0002145
URL: http://stage.monarchinitiative.org/disease/KEGG:ds-H00078

Reference: http://stage.monarchinitiative.org/disease/ORPHANET:2796
URL: http://stage.monarchinitiative.org/variant/ClinVar:RCV000023107

Reference: http://stage.monarchinitiative.org/page/services
URL: http://stage.monarchinitiative.org/phenome/

Reference: http://stage.monarchinitiative.org/gene/NCBIGene:559072
URL: http://stage.monarchinitiative.org/variant/ZFIN:ZDB-ALT-120411-225
```

These range from a whoops link (/phenome) to some very nasty hard crashes with stack traces:

```
 TypeError: Cannot read property "0.0" from null

lib/monarch/api.js, line 5608
Script Stack

    at lib/monarch/api.js:5608 (anonymous)
    at lib/monarch/api.js:6776 (anonymous)
    at lib/monarch/web/webapp.js:1778 (anonymous)
    at stick/lib/middleware/route.js:215 (route)
    at stick/lib/middleware/params.js:102 (anonymous)
    at stick/lib/middleware/static.js:62 (static)
    at /var/home/bamboo/start-monarch-server/lib/monarch/web/sanitize.js:7 (anonymous)
    at /var/home/bamboo/start-monarch-server/lib/monarch/web/cors-middleware.js:22 (accessControl)
    at stick/lib/stick.js:37 (app)
    at ringo/jsgi/connector.js:42 (handleRequest)
```

All in all, there is like a 40% failure rate in this sampling, which seems rather high.

**Comment by cmungall** [comment]
Let's tackle stack traces first. I would recommend adding a test at the same time as fixing.

In the stack trace above, fetchClassInfo() is not being defensive enough about the values it gets back from getVocabularyByID()

Longer term, I would avoid the lexicular closure pattern (where the function 'tr' is passed) except where we are translating nif federation results to objects. There isn't any reason for it from SG queries. We should try and align what SG produces with what monarch-app needs, shouldn't need complex transforms here

**Comment by kshefchek** [comment]
I'm happy to remove all of the translation callbacks.  My idea was to keep the objects consistent when switching from ontoquest, but it is probably better in the long run to refactor these out.

Kent

**Comment by kshefchek** [comment]
Any chance we could rerun this to see if the latest bug fixes improved things?  @kltm I would be happy to take over some of the testing.

**Comment by kltm** [comment]
It would probably take a little to get the tools I'm using right now working for you. If you're interested on the side, we could discuss this next week.
Is this on staging, or just tartini?

**Comment by kshefchek** [comment]
This would be tartini, but maybe we should wait until everything is pushed to stage (if that is the plan).  Next week sounds good, is there anything I can download to play around with?  I'm assuming you do this locally and not on jenkins?

**Comment by kltm** [comment]
At some point I'll compile a usable binary for this so different people can use it easily, but right now it is an interactive tool backed by a postgres database: https://github.com/kltm/tanuki.

**Comment by kshefchek** [comment]
I'm running tanuki pointed at tartini, thanks again Seth for helping me get this set up.  The results look much better.  A few 404s for /phenotype/ZP pages (expected), although the specific pages render fine for me with the under construction message, for example:
http://tartini.crbs.ucsd.edu/phenotype/ZP:0001145 (tanuki says 404)

The rest are 502s from the pages taking some time to load.  Although with some of these pages I can see that they are loading without 502 errors.   @kltm does Tanuki give up after 60 seconds of loading or is coming from our server?  This will probably be a none issue short term once things are cached and long term once we get solr working.

Besides that, we're linking to some 404s on other websites.  The most common culprit is linking to NCBI genes that no longer exist.  I'm also seeing some failures from VEGA.

@kltm how long does this typically take to run?  I tried running over night and it hit about 2100 pages.

```
Base URL: http://tartini.crbs.ucsd.edu
Started at: 00:44:20 on Tuesday, 12/09/2014 (GMT-5)
Waiting: 5.34s (avg); 66s (max); 0s (min)
Known external pages: 45457
Known internal pages: 73386
Known redirected pages: 25656
Collected argument sets: 126557
Attempted page visits: 2200
Total good pages: 2178
Total flagged pages: 22
Total error pages: 0
Total odd pages: 0
```

**Comment by kshefchek** [comment]
Full report here: https://support.crbs.ucsd.edu/secure/attachment/19570/tanuki-report.txt

I manually checked the internal 404 and 500 failures and they loaded without issue.  Many of the 502 errors worked fine for me as well.  The majority of the flagged pages were external links to NCBI gene or vega.  All in all the internal error frequency looks much better.

**Comment by kltm** [comment]
Do I have permission on that JIRA?

**Comment by kshefchek** [comment]
@kltm Just emailed it over in case you don't have access

**Comment by kltm** [comment]
There is a timeout parameter that can be used.

Tanuki will not stop, ever---as long as there are more arguments to run, it will run them, and then wait for more. I typically check in on is every once in a while and stop it around 1000 hits, at that point you should have a pretty good idea what's going on.

There is also functionality to see what pages took a long time, etc. We can go over all the bits and pieces next week.

**Comment by kltm** [comment]
@kshefchek BTW, if you suspect that there might have been a temporary outage that caused things to get an error code the first time ('flagged or 'error), you can "mark" them with mark-problems and then rerun them with rerun-marked.

**Comment by kshefchek** [comment]
It looks like the 404s for the ZP pages are expected since we intentionally return 404 for these .  I'll try this out for the 500 and 502 errors.

**Comment by nlwashington** [comment]
can you just override those urls on the referencing pages to remove the ZP urls?

**Comment by kltm** [comment]
I think this thread is a) a little out of date given all the fixes and b) a little too long to be useful.

See #634.
