### ISSUE TITLE
New call that returns HPO categories so we can group phenotypes

### ISSUE THREAD

**Issue by boesb** [monarch-initiative/monarch-legacy#449]
Based on discussion with @harryhoch and @nlwashington 
Issue:  How do we display a phenotype that falls into more than one category?
Issue:  Does the call return a hierarchy that is displayed on the client side? OR Does the client handle the organization of categories/hierarchy?
(Test on a small dataset)

**Comment by harryhoch** [comment]
believe scigraph subclass navigation handles this.
