### ISSUE TITLE
phenotype page, genes tab, add genes related by genotype

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#450]
The genes tab currently only displays genes associated with the phenotype by disease-phenotype relationships.

```
phenotype > disease_associations > gene_associations
```

There needs to be a function to fetch Genotype-Gene associations so that we can also display genes associated with the phenotype by the genotype-phenotype relationships.

```
phenotype > genotype_associations > gene_associations
```

After this fetchGenotypeGeneAssociations function exists, we need to modify the code in fetchPhenotypeInfo to add genes inferred by this relationship.

This issue extends #426.

**Comment by nlwashington** [comment]
for example, http://localhost:8080/phenotype/FBbt:00004522PHENOTYPE has no genes or models listed.

**Comment by nlwashington** [comment]
this is partially done, but the fly ones aren't showing up for some reason.  need to verify that api looks at the fly views.

**Comment by nlwashington** [comment]
noticed that FBbt was not a curie prefix in our yaml, and therefore isn't being indexed properly in NIF.  added to yaml in commit a41754d, and awaiting views to be reindexed.

**Comment by jmcmurry** [comment]
Related to https://github.com/monarch-initiative/monarch-app/issues/614 Check back after SciGraph and Data release.

**Comment by nlwashington** [comment]
what this ticket is really about is being able infer that a given phenotype is associated with a gene, even though the original annotation was to a genotype.  this is addressed now in the cypher queries.
