### ISSUE TITLE
phenotype page, genes tab, limit diseases by association strength score

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#451]
This issue extends #426 and #443.

If there are too many disease associated with a phenotype, it takes an extremely long time to populate the genes tab. Thus, there is currently an arbitrary LIMIT of 30, and this should be changed in the fetchPhenotypeInfo function to something that takes the disease-phenotype relationship strength score into account.

**Comment by nlwashington** [comment]
no longer an issue with the new architecture.
