### ISSUE TITLE
Remove dependencies on OntoQuest

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#452]
Replace with SciGraph. Coordinate with @ccondit and Amarnath.

Illustrated in this image:
![replace-oq](https://cloud.githubusercontent.com/assets/50745/3475907/e391c810-02f6-11e4-8798-f364abe74aaf.jpg)

**Comment by cmungall** [comment]
tbd: define additional voavulary call to fetch all info for a class, including all axioms

**Comment by nlwashington** [comment]
no longer dependent.
