### ISSUE TITLE
List current nomenclature and synonym matches in search results

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#453]
Searching for DMP1 gene gives two results:
http://monarchinitiative.org/gene/NCBIGene_1758
http://monarchinitiative.org/gene/NCBIGene_9988
The latter is actually DMTF1, but has a synonym of DMP1 in NCBI. 

The problem is that on the search results page, you can't tell which is which, and the latter isn't actually DMP1. The primary nomenclature should be listed, with the matching synonyms highlighted.

**Comment by kshefchek** [comment]
This looks like an issue with vocabulary services, as both NCBIGene_1758 and NCBIGene_9988 have DMP1 as their "term" and the value for "synonyms" is null.   However, we should be able to get this information when we switch to scigraph for searching.  Compare:
http://nif-services.neuinfo.org/servicesv1/v1/vocabulary.json?vocabulury=monarch&prefix=DMP1
to
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/prefix/DMP1
@cmungall is there a plan to use scigraph for searching in the near future?

**Comment by cmungall** [comment]
Yes, #476

**Comment by kshefchek** [comment]
This is fixed on the scigraph branch (screenshots attached).  I'll go ahead and update the search results to include the synoym lists.

![dmp1](https://cloud.githubusercontent.com/assets/1467299/3911439/30ce1972-2321-11e4-9f1e-d3a519284e67.png)
![dmp1-2](https://cloud.githubusercontent.com/assets/1467299/3911441/32434c46-2321-11e4-9637-68abdb73595e.png)
