### ISSUE TITLE
equivalences not populating right

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#454]
i notice on this page:

http://monarchinitiative.org/phenotype/HP:0012649

there are 0 genotypes and diseases.

but if i click on the MP term (that is equivalent) i get a whole ton of them:
http://monarchinitiative.org/phenotype/MP_0001846

these should have the same information, right?
or is this a synchrony issue?

**Comment by cmungall** [comment]
Probably old ontology, fixed in stage: http://stage.monarchinitiative.org/phenotype/HP:0012649
