### ISSUE TITLE
strain background missing from phenotype pages for mouse

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#455]
http://monarchinitiative.org/phenotype/MP_0008892

the background column is empty

**Comment by cmungall** [comment]
Looks like this is not an issue with beta:
http://tartini.crbs.ucsd.edu/phenotype/MP_0008892

Let's check stage shortly

**Comment by cmungall** [comment]
Fixed: http://stage.monarchinitiative.org/phenotype/MP_0008892
