### ISSUE TITLE
phenotype count on genotype pages incorrect

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#456]
See for example:
http://tartini.crbs.ucsd.edu/genotype/MGI:3026722

Tab says (1) phenotype, there are a dozen or so

**Comment by mellybelly** [comment]
same on prod. @nlwashington can you look into this?

**Comment by nlwashington** [comment]
this is fixed in the genofix branch.  should be closed when merged.

**Comment by nlwashington** [comment]
fixed on merge 2a500250fb088e0a8dc4f94b73f962660d98012d
