### ISSUE TITLE
phenotype of the month for homepage

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#461]
It would be a great idea if starting with every release we could have a phenotype of the month and a short article describing the biological relations, cross-species considerations, etc. @nicolevasilevsky @nlwashington @mbrush can help choose

**Comment by iamkoehler** [comment]
Hi,

I like the "Kayser-Fleischer ring” (HP:0007957), because it was an important feature in an episode of Dr.House (http://tviv.org/House,_M.D./The_Socratic_Method) and it is used to identify the diagnosis “Wilson disease” (http://www.omim.org/entry/277900). Not sure about MODs here.

Sebastian

**Comment by nicolevasilevsky** [comment]
I like this idea!

**Comment by mellybelly** [comment]
@kltm how does this factor into your homepage design? happy to write. Where should I keep such things?

**Comment by kltm** [comment]
It didn't, as it wasn't in the mock-up for #518. I think this should just be moved over there.
