### ISSUE TITLE
still seeing NCBI gene IDs instead of collapsing into existing entries

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#467]
For example, look at:
http://monarchinitiative.org/disease/OMIM_104300
there is an entry for http://monarchinitiative.org/gene/NCBIGene:353128
but this leads to the AD8 page, which was already on the results list. 
Also due to lack of collation, its hard to know how many genes have been associated with the disease in total. 

@nlwashington may have advice
seeing same thing on stage.

**Comment by kshefchek** [comment]
Currently the code collapses rows if there are duplicate disease-gene id pairs.  In this case, one row contains a MeSH ID while the other contains an OMIM ID, so the duplicate is never caught.  I'm not exactly sure how to approach this other than uniquifying based on disease label matches (ignoring case).  This may be a little tricky in some cases, for example, the KEGG disease label is "Alzheimer's disease (AD)."  @nlwashington and @mellybelly do you think there is a better way to approach this?

**Comment by mellybelly** [comment]
I believe this is a disease ontology problem then and should be fixed upstream.
@ShahimEssaid @cmungall would be great to try to fix this for next release.

**Comment by cmungall** [comment]
Not an ontology content issue. the equivalence axiom is in the ontology.

First, the fact that some genes are showing up as IDs with no labels indicates something wrong in the underlying views, a join needs to be done somewhere.

But the main issue here is an architectural one. The ontology services and the federation services are largely unconnected, except for closures. So if the views contain a mix of MESH and OMIM IDs then this is what is shown on the page, regardless of whether or not there are equiv axioms linking them. There are two ways around this in the current architecture (1) fix at view generation time (2) dynamically fix in the monarch API layer.

(2) is not ideal as this would require multiple iterated calls, not efficient. (1) could be awkward because at the moment DISCO has virtually no ontology knowledge. The CM doesn't help here. We'd have to load the equiv axioms as a source and use that to do a join. Introducing another complex data dependency. But @nlwashington  would know better than me the pros/cons here.

Should be improved with SciGraph, where we have one system that integrates ontology and data

**Comment by cmungall** [comment]
Actually, (2) might work to a certain extent here, as the monarch already knows to some extent about the equiv axioms as it's already loaded them. It's harder if non-leaf diseases are queried. But here the view layer could do some basic lookups to replace the mesh IDs with OMIM IDs based on what is loaded.

**Comment by jgrethe** [comment]
Hi Chris,
This should probably be handled after data ingest and before the final view is generated.  This would require a default format/measure annotation for any data column/field that is to be normalized.  This would invoke ID services to perform the appropriate conversion, for example, and generate warnings/errors if conversion information is not available.  This could then generate an additional “normalized” field that could then be used in the view. This way a standard process can be defined and then utilized across sources for the same type of data.

In regards to DISCO and ontologies - DISCO is meant primarily as the ingestion engine - prior to transformation.  All the subsequent transformations are tied to the CM.  I am not sure if we would want DISCO to do this as we want to original data at first.  However, the post DISCO CM/View generation processes can potentially be altered to take this into account.

Cheers,
Jeff

On Jul 21, 2014, at 2:41 PM, Chris Mungall notifications@github.com wrote:

> Not an ontology content issue. the equivalence axiom is in the ontology.
> 
> First, the fact that some genes are showing up as IDs with no labels indicates something wrong in the underlying views, a join needs to be done somewhere.
> 
> But the main issue here is an architectural one. The ontology services and the federation services are largely unconnected, except for closures. So if the views contain a mix of MESH and OMIM IDs then this is what is shown on the page, regardless of whether or not there are equiv axioms linking them. There are two ways around this in the current architecture (1) fix at view generation time (2) dynamically fix in the monarch API layer.
> 
> (2) is not ideal as this would require multiple iterated calls, not efficient. (1) could be awkward because at the moment DISCO has virtually no ontology knowledge. The CM doesn't help here. We'd have to load the equiv axioms as a source and use that to do a join. Introducing another complex data dependency. But @nlwashington would know better than me the pros/cons here.
> 
> Should be improved with SciGraph, where we have one system that integrates ontology and data
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by nlwashington** [comment]
Ok, so (2) will work, especially now that we can do filter queries with subclasses.  

But I have questions...

So, for a place like CTD, the original annotation is often made between a MESH term and a gene.  Do you want to present to the user what was originally annotated, or convert it using the equivalences?  Ideally I would say that we want to show that original annotation to the user, but we don't really have that capability.

Let's assume that you want to present to the user the "representative" class for any given disease, no matter what it was originally annotated to.  We already do this for genes, converting them to NCBIGenes, no matter if they were originally annotated to something else (like ensembl or hgnc).  So, in the monarch API we can do a lookup to figure out what the representative class is for any disease id, and present that.  Unfortunately, it will mean doing some iterative calls to Ontoquest/SciGraph, but that will change when we move to data+ontologies together in SciGraph.  Generally, this shouldn't be so bad; there often are not many genes on any given disease-gene page.  

I will try to get to this soon, but perhaps @kshefchek might be able to tackle it before me?

**Comment by jgrethe** [comment]
As this needs to be tied into sorting and other functionality (especially if the data is being manipulated through the UI) - you would want to sort, page through the normalized data.  However, A sub-search may want to be applied across the normalized and original data.  For display one can always display a ‘orig’ tag next to the data so that a user can always see that.

Cheers,
Jeff

On Jul 22, 2014, at 11:13 AM, Nicole Washington notifications@github.com wrote:

> Ok, so (2) will work, especially now that we can do filter queries with subclasses.
> 
> But I have questions...
> 
> So, for a place like CTD, the original annotation is often made between a MESH term and a gene. Do you want to present to the user what was originally annotated, or convert it using the equivalences? Ideally I would say that we want to show that original annotation to the user, but we don't really have that capability.
> 
> Let's assume that you want to present to the user the "representative" class for any given disease, no matter what it was originally annotated to. We already do this for genes, converting them to NCBIGenes, no matter if they were originally annotated to something else (like ensembl or hgnc). So, in the monarch API we can do a lookup to figure out what the representative class is for any disease id, and present that. Unfortunately, it will mean doing some iterative calls to Ontoquest/SciGraph, but that will change when we move to data+ontologies together in SciGraph. Generally, this shouldn't be so bad; there often are not many genes on any given disease-gene page.
> 
> I will try to get to this soon, but perhaps @kshefchek might be able to tackle it before me?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0446
La Jolla, CA 92093-0446

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by kshefchek** [comment]
Sure, I can work on the second approach.

**Comment by aguptasd** [comment]
Two points. 

Let's not decide too early that the ontology+data will go to SciGraph. This would depend on the nature of data access and the expected workload. 

If you can specify the nature of iterative calls to SciGraph we will try to ensure that you don't have to iterate from your application.

**Comment by kshefchek** [comment]
" So, in the monarch API we can do a lookup to figure out what the representative class is for any disease id, and present that."  Would the correct ontoquest/scigraph call look like this:
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/all/OMIM_104300?level=1
http://kato.crbs.ucsd.edu:9000/scigraph/graph/descendants/SUBCLASS_OF/OMIM:104300.json

In the case where there are two superclasses, how would we determine the appropriate representative class.  For example, OMIM:104300 is a subclass of DOID_10652 (Alzheimer Disease) and DOID_630 (genetic disease).

**Comment by cmungall** [comment]
you should only use equivalent classes here

**Comment by kshefchek** [comment]
This is fixed on the scigraph branch, if high priority I can re-write to use ontoquest and add this to the master branch.  The function ignores Orphanet and Kegg IDs so there are still some duplicates, but it collapses MESH and OMIM classes.  For OMIM:104300 it calls scigraph twice but I can eliminate this step for disease pages as we're already getting equivalency axioms in the API, although this wouldn't be possible for gene pages.  The function doesn't seem to add much of a time cost.

![scigraph](https://cloud.githubusercontent.com/assets/1467299/4013394/c57f69cc-2a15-11e4-851f-87c6fabe2366.png)

**Comment by mellybelly** [comment]
@cmungall @aguptasd @jgrethe @kshefchek  can you all comment on what the timeframe is for when scigraph gets hooked in? it looks great!

**Comment by kshefchek** [comment]
I think we are just waiting on the addition of cross references.  @cmungall do you think the scigraph swap is feasible for the October release?

**Comment by cmungall** [comment]
Yes. cc @ccondit
