### ISSUE TITLE
Add PhenoTips as partner organization

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#468]
We need to have a place for partners such as PhenoTips, UDP etc. 
@harryhoch @nlwashington ideas for where/how we should do this?

**Comment by harryhoch** [comment]
How about a "partners" link under the "about" menu item? A static page with boxes for related groups should suffice. 

Is there anyone other than UDP and PhenoTips that we'd like to highlight?

**Comment by kshefchek** [comment]
Looks like we still need to add PhenoTips, moving to this release.
