### ISSUE TITLE
Move download option buttons

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#47]
On most pages we have the ability to download JSON or n-triples. This should be moved to a more regular consistent place where it isn't inline with the other disease/model/phenotype biology-related content.
for example http://tartini.crbs.ucsd.edu/disease/OMIM_168600

**Comment by cmungall** [comment]
What do you mean?

We can hide of the n-triples not ready for prime time. And we could simplify things by having a single per-disease json download and hide the per-disease-subtype downloads for now

**Comment by nlwashington** [comment]
I think this is effectively a duplicate of https://github.com/monarch-initiative/monarch-app/issues/39

**Comment by mellybelly** [comment]
yep sorry, its a dup.
I think that for biologist end users, the download buttons are not very relevant yet take up prime real estate mixed in with biological content. They should be available perhaps to the right of the title of the page. For example on this entry on the genotype page:
http://tartini.crbs.ucsd.edu/phenotype/MP_0000854
the download buttons could be inline with "genotype" on the right side of the panel.
