### ISSUE TITLE
switch out ontoquest to use scigraph in api.js

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#476]
_Note_: recommended that this is done on a branch

Switch out calls to ontoquest with calls to scigraph

use this URL for now
http://kato.crbs.ucsd.edu:9000/scigraph/docs/

but don't hardcode. Add a key to the json in conf/ for scigraph server for scigraph_server

**Comment by kshefchek** [comment]
@cmungall @nlwashington will we be using scigraph to generate database cross references?  It looks like we generate disease xrefs using ontoquest, for example:
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/concepts/term/OMIM_127750

However, scigraph doesn't contain this information in the vocabulary services, for example:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/id/OMIM_127750.json?callback=fn

Also, is this the correct replacement for /rel/all/{id}?level=1
Example:
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/all/OMIM_127750?level=1
Would be replaced by:
http://kato.crbs.ucsd.edu:9000/scigraph/graph/neighbors/OMIM_127750.json?depth=1&callback=fn

**Comment by kshefchek** [comment]
This has been implemented on the scigraph branch.  We're waiting on Chris C to add cross references to SciGraph before moving forward with testing and integrating into the master branch.

**Comment by kshefchek** [comment]
The scigraph branch has been updated to include disease cross references (see https://github.com/SciCrunch/SciGraph/issues/21)

The only remaining issue is that disease pages will not resolve based on equivalency.  But otherwise this should be good to go.

**Comment by kshefchek** [comment]
I've limited search and autocomplete to the categories stored in engine.getDefaultCategories()

The only remaining item is how to deal with disease page redirects.  If we were to merge the scigraph branch the app would no longer redirect disease pages, but I can bring back ontoquest to perform this specific function until we can figure out a workaround.

Also, in testing I'm getting some "500 internal server errors" coming from NIF via searchOverData(), for example: tartini.crbs.ucsd.edu/search/SHH , is anyone else having issues with NIF services?

**Comment by cmungall** [comment]
Yes:
http://build.berkeleybop.org/job/check-monarch-urls

**Comment by cmungall** [comment]
Some issues with blank nodes / anon classes showing up:

http://tartini.crbs.ucsd.edu/phenotype/MP_0000849

Will investigate if this should be handled at the SG level or post SG

**Comment by cmungall** [comment]
Filed a ticket: https://github.com/SciCrunch/SciGraph/issues/38

In the interim, we should do a check and eliminate blank nodes. These have a standard URI property, e..g neuinfo.org/anon/ - or just check the CURIE and eliminate purely numeric (an interim hack)

**Comment by kshefchek** [comment]
It looks like there were some small changes that may have broken things, for example, I was pulling the id from the curie key which is no longer returned.  I've made some quick fixes but I need to do some more testing.  I also noticed equivalency classes were updated for redirects, so I've updated to code to redirect disease pages.

**Comment by kshefchek** [comment]
I've updated the code to fix some of the errors we've been seeing with the scigraph switch.  Please let me know if any more issues pop up.

**Comment by kshefchek** [comment]
Closing, lets break out any problems into new issues.
