### ISSUE TITLE
news ticker for data updates

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#478]
overall, and for each of our major landing pages, i think we need to have a news ticker for recent updates to the data.

for a disease landing page, this might list things like:

25 new or updated phenotype descriptions (2014.07.14)
1 New disease-variant resource available (2014.07.02)
100 New Diseases added to vocabulary (2014.06.05)
46 variants added from ClinVar [ [list] ](2014.06.01)

some of this could be auto-generated, but others might need to be hand-populated.  (in fact, we might want to do this by hand for quite awhile until we nail all the requirements.)

@cmungall what is the best way to maintain this kind of data?  a simple text, xml, or document that i fill in with info?  i could start fleshing it out for initial display in our news ticker.

i can imagine wanting to track:
date | headline/short description | description | category
(where category might be the kind of landing page that it would belong)

**Comment by mellybelly** [comment]
I am also happy to be assigned a data item to write a short blurb about once a week or so too - just need a good way to choose every week and keep track.

**Comment by mellybelly** [comment]
Adding to October release to have manual version in place.

**Comment by kltm** [comment]
This can be handled within the blog using tags; it might be best to keep this all independent and operating separately.

**Comment by harryhoch** [comment]
also possible to do this via selective presentation of the monarch twitter feed

**Comment by ccondit** [comment]
What's the conclusion on where these updates should come from? A twitter hash tag (ie #disease-news)?

**Comment by nlwashington** [comment]
ooh, i like that.  but not sure if it'll be a twitter tag or a blog tag (or can it be both?).  i think we'd want to go with blog tag(s).  is that easy enough?  tweets would certainly be easier (shorter) to write.

**Comment by kltm** [comment]
Unless you want to play with the oauth2 implemented by twitter, it's easier to first try and make this work with tags through the blog.

**Comment by mellybelly** [comment]
for twitter hashtags we can follow:
@monarch-init 
@ontowonka
@uberanat
@news4go

#raredisease 

What do you think?

**Comment by kltm** [comment]
@mellybelly I think we're talking about two different things here? The twitter stuff should probably be a different issue. Somebody will need to log into twitter and create the widget.

**Comment by kltm** [comment]
I'm honestly surprised that "Rare Disease" is not the name of a local metal band.

**Comment by ccondit** [comment]
I added an argument to `_get_blog_data` restricting the data by an optional blog category. I propose that news updates for landing pages get tagged with a predefined category (ie `disease-news`). The landing page will then render linked titles with dates as per the mockup. The content of the blog post is not displayed and can be as verbose as necessary.

**Comment by ccondit** [comment]
Per UI meeting today categories for blog posts corresponding to the news ticker will be `gene-news`, `disease-news`, `model-news`, and `phenotype-news`
