### ISSUE TITLE
Add link about merged phenotype ontology to homepage

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#48]
http://f1000research.com/articles/2-30/v2

**Comment by sarahjkim** [comment]
Add to homepage or Publications (/page/pubs) page?

**Comment by mellybelly** [comment]
I think we need an ontologies page in the Documentation links. 
Most of the ontology work is happening here:
https://code.google.com/p/phenotype-ontologies/
could also just point there for now and not make a page. But probably we need some kind of explanation. I can take a shot at it if you like, Chris, and then you can finalize? 

Please add the above publication to the publications page, it doesn't appear to be there. Also, there are some names underlined and others not on the publication page. We should make this consistent.

**Comment by sarahjkim** [comment]
At the moment, there is an Ontology link in the Documentation tab, but it leads directly to https://code.google.com/p/phenotype-ontologies/ rather than having its own page. Let me know if you'd like this changed to an actual page with an explanation.
