### ISSUE TITLE
HP-MP mappings don't resolve

### ISSUE THREAD

**Issue by micheldumontier** [monarch-initiative/monarch-legacy#480]
on http://monarchinitiative.org/phenotype/HP:0000016

there is a link to 'http://monarchinitiative.org/phenotype/MP_0003622' for ischuria (MP_0003622)

which leads to a "Sorry. Something went wrong." error

however, the following URI does work:

http://monarchinitiative.org/phenotype/MP:0003622

**Comment by cmungall** [comment]
We were having server issues today, seems resolved now.
