### ISSUE TITLE
Add disco2turtle mappings for sources needed for analysis

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#483]
Need two new json conf files to make:
1. mouse and fish genotype to gene mappings
2. orthology mappings

**Comment by bryanlaraway** [comment]
It looks like for fish you have two views to choose from: the OrganismGenotypes view:
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-21427-11
and the FishEffectiveGenotypes view:
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-21427-13
Am I correct in assuming that the OrganismGenotypes view is the one you would like mapped? It has the intrinsic genotype/gvc/vslc/variant locus/sequence alteration fields, but more importantly it has one-to-one mappings from intrinsic genotype to genes.

As for mouse, assuming we're using MGI, although IMPC is available as well. For MGI, the MouseGenotypes view seems appropriate (108,533 records):
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-00096-5
Although if you also wanted IMPC, we have another MouseGenotypes view (7171 records):
http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nif-0000-00096-5
Or both?

As for the orthology mappings, did you want the Panther:Orthologs view (http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_84521-1 = 9,772,803 records, which I believe is already mapped), the Monarch:HumanOrthologs view (http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_84521-1 = 14,875 records), the Monarch:HumanCentricOrthologsAndPhenotypes (http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_152525-17 = 1,112,170 records), Kegg:Orthologs (http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_31015-4 = 59,228 records), or KEGG:PathwayGeneOrthologs (http://beta.neuinfo.org/mynif/search.php?q=*&t=indexable&nif=nlx_31015-3 = 494 records)? Or all of the above?

**Comment by nlwashington** [comment]
irrelevant now.
