### ISSUE TITLE
add /references/ to robots.txt

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#485]
We have lots of fake hits
https://www.google.com/search?q=site%3Amonarchinitiative.org+parkinsons

that are just redirects to pubmed

**Comment by pnrobinson** [comment]
There's probably a way of getting rich with this infrastructure! Pretty effective way of manipulating google!!

Dr. med. Peter N. Robinson, MSc.
Professor of Medical Genomics
Professor in the Bioinformatics Division of the Department of Mathematics and Computer Science of the Freie Universität Berlin
Institut für Medizinische Genetik und Humangenetik
Charité - Universitätsmedizin Berlin
Augustenburger Platz 1
13353 Berlin
Germany
+4930 450566006
Mobile: 0160 93769872
peter.robinson@charite.de
http://compbio.charite.de
http://www.human-phenotype-ontology.org
Introduction to Bio-Ontologies: http://www.crcpress.com/product/isbn/9781439836651
I have learned from my mistakes, and I am sure I can repeat them exactly
ORCID ID:http://orcid.org/0000-0002-0736-9199
Scopus Author ID 7403719646
Appointment request: http://doodle.com/pnrobinson

---

Von: Chris Mungall [notifications@github.com]
Gesendet: Mittwoch, 30. Juli 2014 22:42
An: monarch-initiative/monarch-app
Betreff: [monarch-app] add /references/ to robots.txt (#485)

We have lots of fake hits
https://www.google.com/search?q=site%3Amonarchinitiative.org+parkinsons

that are just redirects to pubmed

**Comment by mellybelly** [comment]
@cmungall @nlwashington @harryhoch should anything be done here?

**Comment by cmungall** [comment]
I'm not a robots expert, I think Jeff and @kltm knows more.

Whatever is decided, it's straightforward to update the robots txt file 
- just edit the delightfully named "robots.mustache" file in 
  ./templates/page/

**Comment by kltm** [comment]
There are also hits to:

stage-monarch.monarchinitiative.org
monarch.monarchinitiative.org

I'd assume that tartini would show up at some point as well (although obviously not for domain-restricted searches).

A good policy might be a different robots.txt for the different deployment types, with a deny all on non-production.

``` text
User-agent: *
Disallow: /
```

Versus:

``` text
User-agent: *
Disallow: /references/
Disallow: /other-secrets/
```

**Comment by harryhoch** [comment]
@kltm, what should go in "other-secrets"?

**Comment by jgrethe** [comment]
I would agree and strongly support the deny all on non-production sites as you don’t want duplicate content showing up with one working and one potentially not (e.g. if it is a development version).

On Sep 16, 2014, at 9:29 PM, kltm notifications@github.com wrote:

> There are also hits to:
> 
> stage-monarch.monarchinitiative.org
> monarch.monarchinitiative.org
> 
> I'd assume that tartini would show up at some point as well (although obviously not for domain-restricted searches).
> 
> A good policy might be a different robots.txt for the different deployment types, with a deny all on non-production.
> 
> User-agent: *
> Disallow: /
> 
> Versus:
> 
> User-agent: *
> Disallow: /references/
> Disallow: /other-secrets/
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by jgrethe** [comment]
Also, you probably should set a max crawl rate so that your services don’t get overloaded by crawlers.  Larry has done some experimenting with this on SciCrunch - so may be best to see what he found by changing this value.

On Sep 16, 2014, at 9:29 PM, kltm notifications@github.com wrote:

> There are also hits to:
> 
> stage-monarch.monarchinitiative.org
> monarch.monarchinitiative.org
> 
> I'd assume that tartini would show up at some point as well (although obviously not for domain-restricted searches).
> 
> A good policy might be a different robots.txt for the different deployment types, with a deny all on non-production.
> 
> User-agent: *
> Disallow: /
> 
> Versus:
> 
> User-agent: *
> Disallow: /references/
> Disallow: /other-secrets/
> 
> —
> Reply to this email directly or view it on GitHub.

---

Jeffrey S. Grethe, Ph.D.                                              email: jgrethe@ncmir.ucsd.edu  
University of California, San Diego
9500 Gilman Drive, M/C 0608
La Jolla, CA 92093-0608

work: (858) 822-0703 (
fax: (858) 246-0644
http://orcid.org/0000-0001-5212-7052
http://www.linkedin.com/in/jgrethe

This e-mail/fax message, including any attachments, is for the sole use of the intended recipient(s) and may contain confidential and privileged information. Any unauthorized review, use, disclosure or distribution is prohibited. If you are not the intended recipient, please contact the sender by reply e-mail/fax and destroy all copies of the original message.

**Comment by kltm** [comment]
@harryhoch well...any other secrets you might have...

@jgrethe yes to the rate limiting, but we've had limited success with it in practice as fewer spiders seem to respect it.

``` text
User-agent: *
Crawl-delay: 10
## References are a map-through
Disallow: /references/
Disallow: /other-secrets/
```

**Comment by kltm** [comment]
Unfortunately, the production/dev split was already in there, which means that the subdomain leak is either caused bad bots or that they're "production", just not in the right place. Would be a different bug though, so closed out.
