### ISSUE TITLE
Make downloadable PhenoGrid report

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#488]
It would be great if one could download a PDF or somesuch for a PhenoGrid report. There would need to be a little more configuration and possibly a separate tab delimited or table report of the content. 

This would be a very useful report for people to use in the justification of their choice of animal models for grant applications and IUCUC applications.

**Comment by nlwashington** [comment]
table report, perhaps like this:
http://saraquigley.github.io/uc-trends/

**Comment by boesb** [comment]
It looks like she's using the library I just mentioned to Kent - this is very doable:
We've also used the dc.js library on several projects- it combines d3.js and crossfilter.js (also written by Mike Bostick). Check out their examples - (not so much related to widgets but great for reusable components - we made widgets out of several of the dc charts).
http://dc-js.github.io/dc.js/

**Comment by nlwashington** [comment]
yes, exactly @BeckyBoes ... i found that example by linking from that site.

**Comment by mellybelly** [comment]
@harryhoch how easy is this? october or november?

**Comment by harryhoch** [comment]
still undone. discussion moved to https://github.com/monarch-initiative/phenogrid/issues/143
