### ISSUE TITLE
Add pictures to team members

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#489]
we should have a more personable presentation of team members

**Comment by nicolevasilevsky** [comment]
I am happy to help, but I don't have editing rights on the Monarch website. Harry- could you help or point me to someone who could help?
In the meantime, I can email folks and ask them to send pictures (or I can find pictures on the web and use those).

**Comment by harryhoch** [comment]
Nicole, this will take a bit of HTML hacking. Perhaps you can gather photos and we'll try to get this done for November?

**Comment by nicolevasilevsky** [comment]
will do!

**Comment by nicolevasilevsky** [comment]
we have pictures of everyone (except Larry Lui), either at a URL or in dropbox, see this spreadsheet: 
https://docs.google.com/spreadsheets/d/1iKrOLfDVP8nGjNcWT6HPxge7V_UgMLZ2VmKIJlRK37o/edit#gid=0

**Comment by jmcmurry** [comment]
Closing as this is a duplicate.
