### ISSUE TITLE
'Compare' calls not working:

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#49]
http://owlsim.crbs.ucsd.edu//compareAttributeSets data=a=HP:0000006&a=HP:0000496&a=HP:0000716&a=HP:0000726&a=HP:0000751&a=HP:0001347&a=HP:0002063&a=HP:0002067&a=HP:0002072&a=HP:0002171&a=HP:0002529&a=HP:0000708&a=HP:0001276&a=HP:0001608&a=HP:0002120&a=HP:0002353&a=HP:0002376&a=HP:0100022&b=MP:0002169

An empty array is returned.

**Comment by cmungall** [comment]
This isn't a complete surprise - there's only a single 'b=' class there, and
it is:

 MP:0002169 ! no abnormal phenotype detected

Which has no common subsumers with anything in HP (other than "Thing").

Nevertheless it's clear that we could do with more metadata here. Maybe the
payload array should be nested in another object, which provides additional
data about which classes could not be matched

On Wed, Jan 22, 2014 at 3:12 PM, Nicole Washington <notifications@github.com

**Comment by nlwashington** [comment]
This should return more informative metadata about when things don't produce good matches.

**Comment by harryhoch** [comment]
Is this still an issue?

**Comment by cmungall** [comment]
I don't think, but we should open a new non-urgent ticket for returning 
more metadata

**Comment by mellybelly** [comment]
moving to May milestone.

**Comment by nlwashington** [comment]
this will be addressed in the refactor for this method call, issue #352
