### ISSUE TITLE
New data sources explanations page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#490]
more prominent attribution of data sources page, and how each has been implemented, is needed

**Comment by nlwashington** [comment]
i've now added a "sources" page, you can get to at http://localhost:8080/sources.

this is currently a hand-populated list, that i can update as we add more sources.  ideally this would come from queries to scigraph, but that might come in the future.  @cmungall this is on the "sources" branch.  if you like, your or i can merge into master.  

also, i will keep track of the text here for now:  https://docs.google.com/spreadsheet/ccc?key=0As52ai7IteLEdF9SMlZHVFZvTWZRNlpoWEU2UU9DU3c&usp=drive_web#gid=4
note that i export this and convert to json using a simple tsv2json ruby script in our private subversion, data_export_scripts/tsv2json.rb

**Comment by nlwashington** [comment]
note that i did not yet include links on the home page or under documentation (that's probably where it should live?)

**Comment by nlwashington** [comment]
link added to about tab in commit 7fb98e8091619289bc5869d6d2df040d14e5122d
