### ISSUE TITLE
SyntaxError: Unterminated string literal on gene pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#493]
I'm getting an "unterminated string literal" error on gene pages, for example:
http://monarchinitiative.org/gene/NCBIGene:20423
http://monarchinitiative.org/gene/NCBIGene:7291

However, I don't see the error on tartini:
http://tartini.crbs.ucsd.edu/gene/NCBIGene:20423

Will investigate.

**Comment by kshefchek** [comment]
The page loads when I run locally with production configurations.  This seems to be a caching issue as it is failing here:
webapp.js:  return JSON.parse(fs.read(path));
api.js : var cached = this.cache.fetch('gene', id);

@cmungall is it possible this will be resolved when the gene caches are rebuilt?

**Comment by cmungall** [comment]
Cleared the cache for these two entries, which fixes this.

May be worth going with something like mongodb for the cacheing.

In the interim, would be useful to have some kind of checker that runs on the server
