### ISSUE TITLE
Make updates to data graph

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#494]
The data graph needs to be updated per our discussions.  We can use this issue to discuss enhancements to the graph.

Administrative:
- Move code to widgets directory (complete)
- Write documentation (TODO)

Enhancements
- Replace superclass/back button with bread crumbs (TODO)
- Add counts to bars (TODO)
- Move x axis to top (maybe both top and bottom) - moved to top
- Create arrows for subgraph navigation, remove bar clickability (complete)
- Remove arrows when no more subgraphs are available (complete)
- Resize Y axis labels if too large to fit in div area (TODO)

Code Refactoring
- Remove redundant code in transitionSubGraph function
- Make tooltip positions dynamic - currently semi hardcoded

Graphic Design
- Decrease graph height (complete)
- Align graph horizontally with Monarch homepage image
  I've moved the graph next to the homepage image; however, the current width of the container is 1586 pixels.  I'm guessing we want to the keep the page width under 1024px or have a responsive/dynamic resizing for smaller screens.  We could also discuss other methods to add content to the home page without increasing the page width, such as having tabs and slide show rotating through the tabs.  We could have a static image of the graph and have the user navigate to a "graphs" page.  I can also work to resize the homepage image along with resizing the graph to get it under 1024 pixels.

The updated graph is here:
http://tartini.crbs.ucsd.edu/labs/datagraph
For comparison the old graph is here:
http://monarchinitiative.org/labs/datagraph

**Comment by kshefchek** [comment]
I've replaced the superclass button with breadcrumbs trails with commit  https://github.com/monarch-initiative/monarch-app/commit/f4d68f1dbf33a360d77ebc9d4b43c5c35617df73.  The dynamic text resizing needs some work but otherwise everything should be functional.   Please let me know if I should update the spacing, colors, etc.

**Comment by nlwashington** [comment]
I would suggest making the breadcrumbs smaller.  I'm not sure if we really need the big buttons, a simple hyperlinked list of text joined with > would be sufficient i think?  more on the same size as the radio buttons on the right-hand side.  don't want the buttons to be the most prominent thing that the user sees.

also, is there no way to get lower than 5  terms deep?  i pursued the brain morphology, and it bottomed out at "abnormal brain morphology", but there's so many more-specific phenotypes!  

also, i found a circularity bug.  i was able to traverse:  nervous system > nervous system morphology > abnormal nervous system morphology > nervous system morphology .

also, when i went with eyes, i got some odd results...  here's the path i followed:
eye > abnormal eye morphology > abnormal eye morphology > abnormal eye morphology > abnormal eye morphology.  what i figured out by hovering over the terms is that they link to different term ids... sometimes the MP term, sometimes the HP term.  that just isn't right.

**Comment by nlwashington** [comment]
i really like the scale at the top of the graph, btw.

**Comment by kshefchek** [comment]
Sure, the breadcrumb trails can be resized or I can remove the shapes completely.  The way it is designed is that the text and polygon shape are seperate elements but are styled to look like a CSS button, for example:

"
g transform="translate(0, 0)"
   polygon points="0,0 0,40 100,40 115,20 100,0" fill="#3D6FB7" /polygon
   text
       tspan text here /tspan
   /text
/g

So the polygon can be removed (or repositioned to be a > sign) easily.  If we do this I can change the hover and cursor styling so the text acts like a hyperlink.  I'm a fan of having the text within a shape, so I would suggest just making them smaller, but either way is fine.  I orginally designed the shapes to be smaller and ended up making them larger to fit various sizes of text.

The depth of the graph is determine by the server side code.  This is set at line 1623 of webapp.js:
var info = engine.generateHistogram("HP:0000118",5,'true');

To increase the depth we just need to clear and reload the cache file.  I can regenerate the cache file with a depth of 6 (or more) if you would like.  Right now the breadcrumb positioning is dynamic, but the total width of its parent html element is not.  I can program it to dynamically increase or we can leave it as manual setting if we know the preferable depth.

The circularity is something I've also noticed.  This seems to be an issue with ontoquest, for example:

http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/subclasses/HP_0012639?level=1
MP_0003632 is listed as a subclass here HP_0012639
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/rel/subclasses/MP_0003632?level=1
HP_0012639 is listed as a subclass of MP_0003632

I can filter out all MP terms from the API if we want to disregard this ontology.  This will probably fix the circularity we're seeing in the graph.

**Comment by kshefchek** [comment]
Most of the items here are complete.  I'll make new issues for adding documentation and any refactoring.  For now I'll hold off on adding counts to the bars until I've implemented an option to switch to a log scale as this may help visualize phenotypes with lower counts.
