### ISSUE TITLE
unmatched phenotype ideas for PhenoGrid

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#495]
We should have the ability to see the unmatched phenotypes for the profile on the left list, as well as for any column. Basically, if you were interested in comparing a patient against a particular model (as in UDPICS), you want to be able to see what phenotypes do not match against the two, almost as much as those that do. 

@harryhoch I wonder if we can think of an approach that is consistent for how to display these regardless if it is on the left list or in a matched column.

This will also be very helpful in particular for debugging ZP matches, don't you think? @cmungall @nlwashington

**Comment by harryhoch** [comment]
Yes, agreed. I’ll try to give some thought on design…. one possibility would be to dynamically add/remove columns as the user selects/deselects display of unmatched phenotypes..

-harry

On Aug 5, 2014, at 1:58 PM, Melissa Haendel <notifications@github.com<mailto:notifications@github.com>> wrote:

We should have the ability to see the unmatched phenotypes for the profile on the left list, as well as for any column. Basically, if you were interested in comparing a patient against a particular model (as in UDPICS), you want to be able to see what phenotypes do not match against the two, almost as much as those that do.

@harryhochhttps://github.com/harryhoch I wonder if we can think of an approach that is consistent for how to display these regardless if it is on the left list or in a matched column.

This will also be very helpful in particular for debugging ZP matches, don't you think? @cmungallhttps://github.com/cmungall @nlwashingtonhttps://github.com/nlwashington

—
Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/495.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edumailto:harryh@pitt.edu  412 648 9300

**Comment by harryhoch** [comment]
subsumed by https://github.com/monarch-initiative/phenogrid/issues/130
