### ISSUE TITLE
species selection box misaligned

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#496]
i noticed that the species selection box is now misaligned into the middle of the grid.

also, the text of the species name key goes off the right-hand side.

for example:
http://monarchinitiative.org/disease/OMIM_608013
![screen shot 2014-08-05 at 12 04 52 pm](https://cloud.githubusercontent.com/assets/5124411/3816973/724414c8-1cd3-11e4-9f46-22530ea23697.png)

**Comment by nlwashington** [comment]
observed in firefox on mac.

**Comment by boesb** [comment]
Duplicate of  #492: Phenogrid select boxes are displaying incorrectly . Fixed in master branch.
