### ISSUE TITLE
hover is hard-coded to be gene, but shouldn't be

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#497]
in the overview, i hovered over one of the human phenotype boxes, and the row below "common" indicates "gene".  but for this view, the match is not a gene, it is a disease.  you could either change this to be simply "match", and the user can just figure it out themselves, or you need to introspect the data to figure out the data type of the match

![screen shot 2014-08-05 at 10 48 49 am](https://cloud.githubusercontent.com/assets/5124411/3817005/a0df4b68-1cd3-11e4-8540-6b7e0c0cfbba.png)

**Comment by boesb** [comment]
Now shows Disease for disease models and Gene for everything else.  This is configurable and can be modified.  Part of latest phenogrid commit: 74254c4686313df292ba493237d54af0a403a01d

**Comment by nlwashington** [comment]
I hope this is driven by the data itself (or by what will eventually be a selection box that the user selects what the target type is)…I hope it is not hardcoded in any way.  If the information isn’t in the data object, then it ought to be, and please add a ticket for that and assign to me.

**Comment by boesb** [comment]
Right now it is inferred from the species (taxon.label in the response). If that's not sufficient, we'll need to get something else back in the data object.
Human->Disease
Mouse, Zebrafish, Fly-> Gene
