### ISSUE TITLE
hover for long label has disappeared

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#498]
i tried hovering on some of the longer "match" names in the phenogrid, like diseases, and it used to show up as a hover box (the full-length label), but this behavior seems to have disappeared.  can this be brought back?

**Comment by boesb** [comment]
Fixed so info shows full title on mouseover and ellipsis removed from shortened label. Mouseout shortens title again. In latest phenogrid commit 74254c4686313df292ba493237d54af0a403a01d
