### ISSUE TITLE
refactor phenogrid in-common hover

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#499]
i'd like a bit of refactoring of the popup when hovering over a cell in the phenogrid.

i mocked up something for discussion. basically, it would just lay it out prettier, and possibly include a visual path(s) to the phenotype-in-common.  (i like this tree-view: http://bl.ocks.org/mbostock/999346, not sure if it can handle multiple-ancestors.)

![in-common_hover](https://cloud.githubusercontent.com/assets/5124411/3817563/1e2c3a0e-1cd9-11e4-8728-288ff4c6b316.png)

**Comment by nlwashington** [comment]
yes, the mockup of the graphical ontology browser is only a mockup (please don't use boxes!)  :)

**Comment by nlwashington** [comment]
there is also: https://github.com/cpettitt/dagre-d3

**Comment by harryhoch** [comment]
Yes, this is a good thing to look into.

One issue involves the API - do we have calls that provide the complete chain?

I think we might want to do something a bit more compact to start. We can probably condense all of the relevant links into a small amount of vertical space if we try..

-harry

On Aug 5, 2014, at 5:13 PM, Nicole Washington <notifications@github.com<mailto:notifications@github.com>> wrote:

there is also: https://github.com/cpettitt/dagre-d3

—
Reply to this email directly or view it on GitHubhttps://github.com/monarch-initiative/monarch-app/issues/499#issuecomment-51260775.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics
harryh@pitt.edumailto:harryh@pitt.edu  412 648 9300

**Comment by mellybelly** [comment]
I really like this idea. Note in some cases it may be possible that the leaf nodes may have multiple LCSs at the same IC, or multiple paths to the LCS.

**Comment by harryhoch** [comment]
subsumed by https://github.com/monarch-initiative/phenogrid/issues/129

**Comment by harryhoch** [comment]
actually, https://github.com/monarch-initiative/phenogrid/issues/59 instead
