### ISSUE TITLE
Add more results to each section on disease page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#5]
It seems that only a fraction of the results are showing up on the disease pages (probably true elsewhere).  

For Huntington's disease, none of the mouse models are showing up:
http://secret-harbor-1370.herokuapp.com/disease/OMIM_143100

even though they are clearly there:
http://beta.neuinfo.org/mynif/search.php?q=OMIM_143100&t=indexable&nif=nlx_152525-2&b=0&r=20&ff=Organism:mus%20musculus*Disease%20Model%20Type:asserted

**Comment by cmungall** [comment]
Looks like fed queries return the first 20:

http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-2.json?includePrimaryData=true&q=OMIM_143100

As documented here:
http://beta.neuinfo.org/services/resource_FederationService.html

I will up the count, but this is a temp solution. Some queries will naturally return > max, so we need some kind of cursor mechanism...

**Comment by cmungall** [comment]
Fix pushed to Heroku.

Works for now...
