### ISSUE TITLE
On Homepage consider making first entries clickable

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#50]
On the home page, we (nicely) have an overview of four types of entities in the system. Consider removing the "more details" link, which goes to more details of the main entity (in the attached example, "Parkinson's disease" for the disease box, and instead make the "Parkinson's disease" itself clickable and remove the "more details".

![image](https://f.cloud.github.com/assets/796636/1985235/2e8e5616-843b-11e3-86c7-317ed03d883d.png)

Also consider changing title for each box to just the title of that type "Diseases" instead of "Diseases:Parkinson's disease". Instead, move the "Highlighted Diseases" title to below that, making Parkinsons the first expanded entry, and the others following that. In this way it will be apparent that these are simply a few of the highlighted diseases we have (and that Parkinson's is one of them).

**Comment by harryhoch** [comment]
Agreed. Good points.
