### ISSUE TITLE
indicate toggle-ability of "unmatched phenotypes" in phenogrid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#500]
we were told (by a user) that the unmatched phenotypes link isn't obvious to be clickable.  perhaps add an arrow-thingy to indicate that it's able to be toggled (or highlight to show it's a link).

**Comment by boesb** [comment]
Added checkbox to toggle on/off in latest phenogrid commit 74254c4686313df292ba493237d54af0a403a01d
