### ISSUE TITLE
Possible to clean up redundant search results?

### ISSUE THREAD

**Issue by bryanlaraway** [monarch-initiative/monarch-legacy#503]
Is it possible to trim down redundant search results? For example, if you search for "Diabetes" (http://monarchinitiative.org/search/diabetes) you get a list of 20 phenotype/disease results.

Now, if you look at the first four entries for Diabetes mellitus, three are for disease and one is a phenotype, and the three diseases all point to the same disease page, which I've shown in brackets below:
disease: diabetes mellitus [http://monarchinitiative.org/disease/DOID_9351]
disease: Diabetes mellitus [http://monarchinitiative.org/disease/DOID_9351]
Phenotype: Diabetes mellitus [http://monarchinitiative.org/Phenotype/HP_0000819]
disease: Diabetes mellitus (disorder) [http://monarchinitiative.org/disease/DOID_9351]

You have similar issues with Diabetes insipidus, and with the differences between Diabetes mellitus type 2 vs Diabetes mellitus type II.

The end result is you wind up with a much larger result set than you really need, and the number of results is larger than the number of distinct links to other Monarch pages. Hopefully there is a way to handle the differences in capitalization and numeral type differences to reduce the duplicative results.

**Comment by kshefchek** [comment]
I think a lot of this, if not all, should be resolved when we switch to scigraph to generate search results.  
Compare: http://monarchinitiative.org/search/diabetes
To: http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/search/diabetes

See #476 and semi related #453

**Comment by kshefchek** [comment]
These results look better on the scigraph branch, screenshot attached.  Will close when we merge scigraph into master.
![diabetes](https://cloud.githubusercontent.com/assets/1467299/3911483/b4d7b8a4-2321-11e4-8793-d148b61f9e84.png)

**Comment by jmcmurry** [comment]
A cursory check of this on beta seems to indicate that this has been addressed. @kshefchek please confirm.
