### ISSUE TITLE
refactor gene-allele associations to reduce time cost

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#505]
Presently, the fetchGeneInfo loops on every (several?) xref ids.  this is extremely expensive and may also deliver incorrect results.

I think we need to refactor the views in DISCO upstream so that we only have to lookup using the NCBIGene identifier for any source. (this may change in the future when we have SciGraph with proper id-equivalences for genes.)  this will reduce the time for lookups, and may remove the incorrect results that are sometimes obtained.

**Comment by kshefchek** [comment]
Is there a list of xrefs we need to keep to generate results - I'm thinking just MGI, ZFIN, WB, and Ensembl.  It's worth noting that the functions called in fetchGeneInfo have a hard coded source_to_resource_map so many of these xrefs are disregarded while looping through.

Or did you want me to refactor the DISCO views to only use NCBIGene IDs?

**Comment by mellybelly** [comment]
Assigning to october but please punt if this is a longer term effort

**Comment by kshefchek** [comment]
I believe @nlwashington fixed this and I made a few tweaks to bring back the cross references.  Nicole is this okay to close?

**Comment by kshefchek** [comment]
No longer relevant.
