### ISSUE TITLE
Primary source is not correctly displayed

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#506]
We should display the most primary source of data where possible. On the interactions tab of this page I see neurolex displayed instead of Biogrid.  It is important that we get this right. @kshefchek perhaps you can fix? or @nlwashington will have ideas.

http://monarchinitiative.org/gene/NCBIGene:1910
look at interactions tab- this should be BioGrid.

**Comment by kshefchek** [comment]
It looks like this is already fixed on the master branch, but I'm unable to test our production environment locally without getting "connection refused" errors.  @nlwashington is there anything wrong with the production nif URLs?

**Comment by kshefchek** [comment]
This is fixed in beta.
