### ISSUE TITLE
Error: Unterminated string literal - for mouse gene

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#508]
http://monarchinitiative.org/gene/NCBIGene:16905

**Comment by cmungall** [comment]
Works on dev:
http://tartini.crbs.ucsd.edu/gene/NCBIGene:16905

Looks like a cache issue.

I think we need to do a try/catch, if it fails, carry on and generate info from sources as if cache entry was not there

**Comment by kshefchek** [comment]
I think this issue is fixed, although I'm not able to test it locally.  I've wrapped the offending line in a try catch.  Will close when we can test on production.

**Comment by nlwashington** [comment]
This is fixed.
