### ISSUE TITLE
Find out more button doesn't go anywhere on Phenotype page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#51]
When you are on http://tartini.crbs.ucsd.edu/phenotype/
you see "Phenotype spotlight" "Large floppy ears". The "Find out more" button goes to an empty phenotype page.

Also, instead, consider making "large floppy ears" clickable as suggested for homepage #50 
or at least we should be consistent with how we display the find out more links/buttons across the different pages

**Comment by sarahjkim** [comment]
Will be fixed by #58.
