### ISSUE TITLE
refactor landing pages for major parts of website

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#510]
We would like to refactor the landing pages for the major categories of data on our site.  This includes genes, diseases, phenotypes, and models (genotypes).  These all follow a general pattern with 4-ish sections, one of them being a graph (perhaps a variant of @kshefchek's datagraph). These might require some new service calls to be written in the api.js, but dummy calls (for summary data) should be written for now until we can write them properly.

See below for some mockups.
![gene_landing_page](https://cloud.githubusercontent.com/assets/5124411/4001311/a64d5e46-2962-11e4-87cd-886b317d7dee.png)

![model_landing_page](https://cloud.githubusercontent.com/assets/5124411/4001271/637e4422-2962-11e4-8089-05fb4d906033.png)
![phenotype_landing_page](https://cloud.githubusercontent.com/assets/5124411/4001272/63845600-2962-11e4-9ae9-011ec43c28d5.png)
![disease_landing_page](https://cloud.githubusercontent.com/assets/5124411/4001273/63870d14-2962-11e4-9768-d122966457a6.png)

**Comment by nlwashington** [comment]
for data graphs for each landing page, see issues #525, #526, #527, #528.

**Comment by mellybelly** [comment]
@harryhoch assigning to you for review at your meeting this week.

**Comment by ccondit** [comment]
These are generally refactored to have the same layout as the labs demo. @nlwashington can we discuss content tomorrow or Friday (I can come up to Berkeley)?

**Comment by nlwashington** [comment]
Yes, we'll be in Berkeley Thurs and Fri. Come whenever is best (or both!)

**Comment by nlwashington** [comment]
added gene spotlight in commit a673d3e.  is on a random rotation for a different one to show up on each page load, with selections in a config file.

**Comment by nlwashington** [comment]
so now that we can see an example of what the landing pages look like with some real stuff:
![screen shot 2014-10-08 at 9 30 45 am](https://cloud.githubusercontent.com/assets/5124411/4562912/7fa96318-4f08-11e4-8037-e94570e415ea.png)
we can see that layout is an issue.  the datagraph gets shoved off the page, which is no good...that's our gold!  we should consider changing up the order and refining the presentation.  i don't mind so much about things going off the screen, so much as i want to make sure that the good stuff shows up at the top.

first thing, would be do decrease the size of the chart.  another might be to put the items in a different order, for example with the datagraph as the first object in the top left.  in the case of gene pages, this might be especially important if we want to have multiple graphs (like disease-gene AND phenotype-gene).  alternatively, we could put the different graphs in separate tabs in the same location.

this may boil down to the question:  should the size of the window on the landing pages be fixed, and the elements within it resize accordingly?  or do we not mind the content going off the bottom?  (i would argue that we should not let the content go beyond the right side.)

here's a mockup of what it might look like if we rearranged the order, placing the graph(s) prominently in the top left.  not sure i love it (i think it's actually that i dislike horizontal bar charts).  note that you can see that some of the stuff would overflow off the bottom on the screen.  also, the stuff on the right-hand-side ought to be flow-y (rather than fixed, as it is now).
![gene_landing2](https://cloud.githubusercontent.com/assets/5124411/4563009/ad01a608-4f09-11e4-8686-8366b9172417.png)

**Comment by nlwashington** [comment]
we could also consider moving the "spotlight" to the main front page, if we want to gain the real estate.

**Comment by cmungall** [comment]
+1 to the proposed new page layout. datacharts should be primary.

Other options: you scroll down for spotlights

or

dynamically expand sections of the page. E.g.

> Datagraph (expanded by default)

Chart(s) here

> Spotlight (contracted by default) - possibly showing truncated version of text?
> 
> About genes in monarch/recent

**Comment by harryhoch** [comment]
December 2014 release
