### ISSUE TITLE
refactor datagraph for general use

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#511]
the phenotype datagraph is awesome, and we'd really like to be able to use it all over the website given different data as a parameter.

i found this nice explanation about how to design d3 charts to make them more reusable, and allows you to instantiate more than one in the same window, if desired (we might!)

http://misoproject.com/d3-chart/examples/basic.html

can you do a bit of refactoring for this purpose?
i added a new function makePhenotypeHistogramFromAssociations that makes a nice little summary of phenotypes given an association object.  this could be used to generate a phenotype histogram on any disease or gene page (currently slotted into fetchGeneInfo).    can you give it a whirl as a test?

**Comment by nlwashington** [comment]
note, that method i made doesn't do any recursive lookups, so it wouldn't let you drill down through an interactive graph... we can think about how to extend that in the future, possibly with new owlsim methods.  (i want to avoid doing iterative calls between disco, ontoquest, and/or owlsim...a single call to owlsim will probably be the fastest.)

**Comment by kshefchek** [comment]
Sure I'll get started on this.  Perhaps some input from the more seasoned D3ers in the group, @harryhoch et al. may be useful.

**Comment by harryhoch** [comment]
Nicole's D3-chart example involves the use of their widget, not unlike what we've done with phenogrid. Kent, a quick look at the phenogrid code should point you where you need in  terms of basic widgetizing. If you have further questions, let's talk...

**Comment by boesb** [comment]
Kent, this is one of the resources that I used to get started with widgets:
http://learn.jquery.com/jquery-ui/widget-factory/how-to-use-the-widget-factory/
We've also used the dc.js library on several projects- it combines d3.js and crossfilter.js (also written by Mike Bostick). Check out their examples - (not so much related to widgets but great for reusable components - we made widgets out of several of the dc charts). 
http://dc-js.github.io/dc.js/

**Comment by kshefchek** [comment]
Thanks!  I'll check out the links.

**Comment by kshefchek** [comment]
So if I'm understanding correctly, I can wrap the the datagraph script in a function in which we pass path to our json data and html div, and then call the function in a script element in the HTML, for example: 
datagraph.init("#graph","/labs/datagraph.json");
and we essentially have a reusable function/graph.  Or I could alternatively use the JQuery-UI widgeting which would require some refactoring but probably also offers some benefits.

I could make the first change now, and then refactor the graph to use JQuery-UI in parallel with the phenotype page updates, thoughts?

**Comment by harryhoch** [comment]
yes, that's right. conversion to a jquery widget is pretty straightforward...

On Aug 22, 2014, at 14:07, "kshefchek" <notifications@github.com<mailto:notifications@github.com>> wrote:

So if I'm understanding correctly, I can wrap the the datagraph script in a function in which we pass path to our json data and html div, and then call the function in a script element in the HTML, for example:
datagraph.init("#graph","/labs/datagraph.json");
and we essentially have a reusable function/graph. Or I could alternatively use the JQuery-UI widgeting which would require some refactoring but probably also offers some benefits.

I could make the first change now, and then refactor the graph to use JQuery-UI in parallel with the phenotype page updates, thoughts?

**Comment by kshefchek** [comment]
Is there an advantage to going the JQuery UI route versus just calling the function in the HTML?  See /templates/labs/datagraph.mutache

**Comment by boesb** [comment]
If the datagraph has many configuration parameters, the widget would probably be easier to work with since it has getters and setters for all the options.

**Comment by nlwashington** [comment]
just be careful with potential conflicts that might arise between JQuery UI and bootstrap.

**Comment by kshefchek** [comment]
I can move forward with refactoring to the code to be a JQuery UI widget, but I don't see any reason why we can't continue development with the current script.  If you would like to wait until I refactor the code as a widget that is fine too.

@nlwashington if you want to move forward I can tweak the code to dynamically pass more paramaters into the function, such as width, height, colors, etc.  I would also like to remove the hardcoded "groups" key in the json object as we can derive this from the other parts of the object.  That should be done early next week.

**Comment by nlwashington** [comment]
@kshefchek i'll be out for a week, so i'll check back in and see where things stand then.  biggest thing is i want the datagraph to be more configurable.  for example, i want to have a simple bargraph that happens to only have a single species (therefore stacking isn't necessary).  i may (or may not as is the case now) include the data for drilling down the ontology within the json blob, but ideally i would pass a function that would be able to fetch it dynamically upon clicking/interaction (i don't want to pre-generate or store the drill-down data).  and i could specify those kinds of things when i instantiate an instance of the datagraph.  (because that is different behavior than the pre-generated data you will need for the overview graph.)

**Comment by kshefchek** [comment]
The datagraph code has been refactored for general use and to support multiple graphs on a single page.  Any options are configured with an external js file, see https://github.com/monarch-initiative/monarch-app/blob/master/widgets/datagraph/js/config_template.js

Closing, lets break out any additional features into new issues.
