### ISSUE TITLE
Add global alliance membership info

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#512]
We should have this in our partnerships section for the next release.

**Comment by nlwashington** [comment]
this is now in the "partners" section of our about page.  @mellybelly, would you like this more prominently displayed elsewhere, or is this sufficient (please close if sufficient)?

**Comment by kshefchek** [comment]
This is in the partners section on the about page, see http://beta.monarchinitiative.org/page/about

@mellybelly please close if this is sufficient.
