### ISSUE TITLE
add genes from asserted models to genes tab

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#516]
The affected genes in the asserted models should be used to populate the genes tab.
for example:
http://monarchinitiative.org/phenotype/MP_0001425
is very depauperate on gene tab, but has lots of potential genes from models tab.

**Comment by nlwashington** [comment]
ah yes, this will probably get fixed when we refactor genotypes.  related to #401, #402.  i have started refactoring these in the genotype_fix branch ef63bc1c7103141a2a858f27eaa637e875247ed5.

**Comment by kshefchek** [comment]
@nlwashington do you want me to pick up where you left off at ef63bc1 or would you prefer to work on this?

**Comment by nlwashington** [comment]
i'll take a crack at it today (good way to return from vacation)... making new branch to move the master changes into a new genotype branch.

**Comment by nlwashington** [comment]
i've worked a bit on this, see branch genofix. 85e7a6ef3fa5f199a9c39b4ac2777a0fa08b5a48

**Comment by nlwashington** [comment]
this will be fixed when merging the genofix branch.

**Comment by nlwashington** [comment]
fixed on commit 2a500250fb088e0a8dc4f94b73f962660d98012d
http://tartini.crbs.ucsd.edu/phenotype/MP_0001425
