### ISSUE TITLE
add phenogrid to genotype pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#519]
We need a "compare" tab, similar to what is on the disease pages, to show the phenogrid comparing the genotype phenotype profile to diseases or genes.

**Comment by nlwashington** [comment]
I've taken a first pass at this in the genofix branch, on commit b8b8f9b, but it doesn't seem to be able to get the phenotypes properly (based on the console log, it isn't parsing the association object right).  @BeckyBoes can you take a look and see if you can figure out what's gone wrong?

**Comment by nlwashington** [comment]
i have added a tab, and some of the work, to get the phenogrid into the genotype pages. 
http://tartini.crbs.ucsd.edu/genotype/MGI:3043397

however, it shows up blank.  marking this as a bug now.

**Comment by harryhoch** [comment]
implemented via https://github.com/monarch-initiative/monarch-app/commit/2d88d814c4b2d8e2c3810350c640b16a2880cbae
