### ISSUE TITLE
autocomplete on gene symbol leads to a page with null category

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#52]
autocomplete on SHH takes you to a results page
http://tartini.crbs.ucsd.edu/search/SHH
where the category and Info are "null" and "undefined", though this appears to be a match on a pathway constituent.

![image](https://f.cloud.github.com/assets/796636/1987930/4a5c1a42-8461-11e3-8aaf-f3ee186a9762.png)

Furthermore, why doesn't autocomplete take me to any models with shh in the label, if it is currently string based (rather than the semantic entity "shh gene".

**Comment by cmungall** [comment]
We will remove null categories from search. BUT FIRST we need vocab index reindexed so phenotypes show up

**Comment by mellybelly** [comment]
null categories still showing up, no phenotypes showing up, and missing genes from autocomplete still. @cmungall punt till may milestone?

**Comment by nlwashington** [comment]
this appears fixed.
