### ISSUE TITLE
compare page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#522]
We have an API call that allows comparison of an entity to one or more phenotypes.  We need a nice front end that is similar.  This has now been refactored to deliver it's payload with the same json format as the search.

eventually, i imagine it having a similar interface as we currently have for "analyze", where the user can search/autocomplete to find their desired entities for comparison.

as a first pass, a little textbox where the user can enter a query id and/or a set of target ids would be good.  

the result of the compare would best show up as the phenogrid.  we should consider other ways (tabular or otherwise) of viewing it too.

this would live at /compare.

**Comment by harryhoch** [comment]
I think we should consider revising the /analyze UI to see if we can wrap /analyze and /compare in one place.

**Comment by nlwashington** [comment]
good idea @harryhoch

**Comment by mellybelly** [comment]
I am hoping in scope for october?

**Comment by jmcmurry** [comment]
I don't know all of the history, but it seems like this ticket was addressed as part of the relatively recent /analyze/phenotypes refactor. Is what is now implemented sufficient to close this current ticket?

**Comment by nlwashington** [comment]
yes, i think this can be closed.
