### ISSUE TITLE
Ordering of phenotype frequencies not documented

### ISSUE THREAD

**Issue by KimJBaran** [monarch-initiative/monarch-legacy#523]
The ordering of frequency information regarding phenotypes is not clear. It might be documented somewhere, but it is not clear where.

For example, how are "hallmark", "typical", "frequent" and "occasional" related to each other? Can I assume the following in descending order?
1. hallmark
2. typical
3. frequent
4. occasional

**Comment by nlwashington** [comment]
apologies for the lack of documentation.  you can find the descriptions of HPO frequency labels (along with their approximate mapping to %) here:

http://www.human-phenotype-ontology.org/contao/index.php/annotation-guide.html

we will look at adding documentation about these, and appropriate sort order to the column (being numerical, rather than alphabetic).

**Comment by nlwashington** [comment]
@pnrobinson will the frequency information ever be converted to classes (and where would such classes exist)?

**Comment by mellybelly** [comment]
Yes we discussed as part of the phenotype data exchange format. We should fix this. I will create a ticket in the phenotype ontology project: https://code.google.com/p/phenotype-ontologies/issues/detail?id=55

**Comment by jmcmurry** [comment]
relevant for renewal

**Comment by pnrobinson** [comment]
I am not sure I see the  action item here, but I think the questions is whether the annotation frequencies documented here (http://human-phenotype-ontology.github.io/documentation.html#annot) should be made into full-fledged classes? Another important issue is that Orphanet has a smaller list of categories, and we have been considering either adopting them or meeting in the middle. I think in retrospect that our list has too many categories, and in actuality, these categories have been rarely used by us or by other users of HPO.

**Comment by iamkoehler** [comment]
I think this is a valid candidate for a new sub-ontology. Should we do this?

**Comment by pnrobinson** [comment]
Well, I think it is OK, but remember we were speaking with Ana about agreeing to use the same frequency categories, and we still need to make a decision there. So let's talk about this before making anything public!

**Comment by mellybelly** [comment]
what is the reason to not use a data property?

**Comment by iamkoehler** [comment]
> but remember we were speaking with Ana about agreeing to use the same frequency categories, and we still need to make a decision there

I remember that, but I think we already agreed upon a new standard

> what is the reason to not use a data property?

why do we not use a data property for the age of onset then?

**Comment by jmcmurry** [comment]
I don't have a particularly strong feeling about which way to go with this, but we should settle on a plan and either flesh it out or close this ticket if it has been OBE.

**Comment by pnrobinson** [comment]
Seb, should we confirm with Ana first that we will coordinate on one system of frequencies? And document this on the HPO website?

**Comment by iamkoehler** [comment]
hi. we have now one vocabulary for frequencies, that has been developed together with Orphanet. See e.g. http://compbio.charite.de/hpoweb/showterm?id=HP:0040279

**Comment by kshefchek** [comment]
Re-opening since these classes are not in the app on the disease to phenotype tables.

**Comment by kshefchek** [comment]
these were added back to our tables with #1496
