### ISSUE TITLE
data graphs for gene landing page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#525]
Here are three examples of graphs that could be placed on the gene landing page:
Gene

1) phenotype annotation counts (this is like the current phenogrid)
x-axis:  phenotype
y-axis:  num gene-pheno associations per species

2) phenotype-gene distribution
x-axis:  phenotype
y-axis:  #unique genes per species  (or consider %genes)
this takes the associations as above, and uniquifies the associations based on gene (direct or inferred)

3) phenotype coverage of human genes per species
x-axis: phenotype
y-axis: #human genes (or orthologs) per species
this is similar to (2) but it maps each species' gene to it's human ortholog, and then counts them

let's discuss the best strategy for (2) and (3), as we probably want to do these in a script outside of the web api.

**Comment by nlwashington** [comment]
the datagraph appears to be overflowing the boundaries of the div it's in.  can it be made smaller?

![screen shot 2014-10-08 at 9 10 34 am](https://cloud.githubusercontent.com/assets/5124411/4562584/ac1cdc3e-4f05-11e4-8244-00edb2aa99b5.png)

i also notice this is a disease x gene chart, rather than a phenotype x gene graph.  can you add one of those?

**Comment by kshefchek** [comment]
I still need to implement some automatic resizing based on browser dimensions and dynamic resizing of the browser window.  But we can change the height/width by updating the datagraph object on the client side (currently generated in widgets.js).

For the phenotype graph, do we have a function in the API that generates phenotype/gene counts given a phenotype ID?

**Comment by kshefchek** [comment]
I'm seeing how we generate phenotype-gene counts in API (looks like via disease and genotype associations), I'll go ahead and add the graph.

**Comment by harryhoch** [comment]
included in December release
