### ISSUE TITLE
data graphs for phenotype landing page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#526]
Ideas for interactive data graphs for phenotype landing page (/phenotype).  these get progressively more difficult, and not all may be for our first milestone.

1) associations per phenotype (current phenogrid)
--this might allow the user to switch between types of associations - gene, genotype, disease per species
x-axis:  phenotype
y-axis:  num associations (per species)

2) num uniq genes per phenotype  (basically, phenotype coverage/distro over genome)
x-axis:  phenotype
y-axis:  # genes (per species)

3) phenotype coverage over human genome (via orthology)
x-axis:  phenotype
y-axis:  # human gene (ortholog) per species

**Comment by harryhoch** [comment]
included in December release
