### ISSUE TITLE
data graphs for disease landing page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#527]
1) phenotype distribution for human diseases 
x-axis:  phenotype
y-axis:  #diseases

2) genes involved in diseases
x-axis:  disease category  (use the disease ontology here for categories)
y-axis:  #genes
i suggest trying the following disease categories for now: 
DOID:655, DOID:150, (subtypes of DOID:7), DOID:225, DOID:0080015, DOID:630
it would be nice upon hover to see information about the genes in the set.  these disease categories can be used to fetch the relevant disease-gene associations, although once the disease page is cached, you could just retrieve the cached associations.

**Comment by kshefchek** [comment]
For 1, I'm wondering if this will generate the same counts as our phenotype annotation distrobution since both would use nlx_151835-1, unless we uniquify and/or remove equivalency.

Instead of disease counts per phenotype, what if we did phenotype count per disease and iterate over the disease ontology instead?

I've added a function to generate 2; maybe we could consider this for the gene page as well.  I am seeing larger counts in subclass groups than the total count of their parent classes.  This could be a result of shared genes across different disease classes, or something could be wrong in my code.  In the test cases the aggregate counts have been the same or a little higher than the parent class count.

**Comment by kshefchek** [comment]
Over the last few weeks I've made some additional graphs for the landing pages.  All four graphs are visible on /labs/datagraph, and I've added one for each landing page.  To start I've used functions in our API to generate counts and as a next step will write some new functions to get some additional metrics.  Here is the summary of each graph:

Phenotype page: Phenotype annotation distribution (initial graph we have been testing).  Do I need to add data from IMPC here?

Disease page: Same as the phenotype distribution but with DOID:7 as the input

Gene page:  Counts from fetchDiseaseGeneAssociations() with DOID:7 as the parent class

Genotype page: Counts from fetchGenoPhenoAsAssociationsBySpecies() with HP:0000118 - this only worked for mouse data

Everything is on the scigraph branch as I originally thought we needed to uniquify gene counts based on equivalency.  I later realized that I need to uniquify on the gene ID regardless so the equivalency check step is unnecessary.  As a next step I will be getting mouse gene counts from the MGI and IMPC resources.

**Comment by nlwashington** [comment]
hm, i tried loading /labs/datagraph on tartini, but it gives me a 502 error.  seems like a different strategy might be in order for generating the data.  perhaps with lazy loading in some way?

**Comment by kshefchek** [comment]
All of these changes are on the scigraph branch but I can merge when we're ready.

**Comment by nlwashington** [comment]
oh, scigraph branch.  missed that.  i'll give it a shot.

**Comment by nlwashington** [comment]
merge merge scigraph please!

**Comment by kshefchek** [comment]
Scigraph merged

**Comment by nlwashington** [comment]
yes, for phenotypes, be sure to add in all of the sources of phenotypes as are in the various api functions... these should include the addition of MPD, IMPC (for mouse, the former of which doesn't include any genes, it is just genotypes).  eventually, it might be nice to allow for distinguishing the contributions of the different sources of data (so, for example, we might see a non-uniform distribution of certain kinds of phenotypes by source, as i suspect we will for IMPC). 

eventually we want to add the other species as well...  you can use any of the sources included in the api if you want to give it a test (fetchGenotypePhenotype and fetchVariantPhenotype are the key functions there).  have to tried adding fish or fly or worm recently?

**Comment by kshefchek** [comment]
In testing fetchGenoPhenoAsAssociationsBySpecies() late last week it only generated mouse data.  Does NIF support subclass querying with the HP ontology for other model organisms?

**Comment by nlwashington** [comment]
@cmungall, this is the problem because of the limited cross-species bridge being used when indexing NIF, right?

**Comment by cmungall** [comment]
This should only be a major issue for ZP/zebrafish. We expect HP classes to retrieve mouse data

**Comment by kshefchek** [comment]
I've added some code to dynamically add min-width and min-height css styling to the bootstrap class based on the datagraph object.  This seems to have resolved the overlap issue in my browser, although on my phone I'm having issues with the navigation bar overlapping the graph when zooming in (it looks fine when first loading).  Although that seems to be an issue with any div, so maybe this is just a nav bar z-index thing.

**Comment by kshefchek** [comment]
I think what we have now is decent enough until the scigraph updates can improve things, closing.
