### ISSUE TITLE
Monarch team page updates

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#53]
Please remove Carlo, he's no longer with us, unfortunately.

For those of us labeled as PIs, perhaps change our bios to read "X is currently a PI of the Monarch Initiative...." that way we can all have equal importance.

For OHSU, please edit my bio to read:
Dr. Haendel has a BA from Reed College in Chemistry and a Ph.D. in Neuroscience from the University of Wisconsin, Madison. She is currently a PI of the Monarch Initiative, with the aim of providing integrated access to model systems phenotype-genotype data for the purposes of disease hypothesis exploration. She also participates in development of the eagle-i and CTSAconnect ontologies, designed to collect and disseminate information about biomedical resources and enable research profiling. Her research interests are in using ontologies to promote synthetic science though connections within biomedical data, to utilize information science during the course of research and its publication, and to enable scientific reproducibility.

Please add Bryan Laraway and Kent Shefchek to OHSU's section. 

Please add Jeremy Espino to the UPitt section. 

Please add Sarah Kim (yourself!) to the LBNL section.

We'll broadcast requests for any changes to the other bios.
Should we list the HMC team? I think that would be nice.
Also, should we have a contact us button on this page? that gets sent to info@monarchinitiative.org?

**Comment by cmungall** [comment]
@fustar @bryanlaraway can you add

**Comment by sarahjkim** [comment]
I currently need the following blurbs:

Bryan Laraway - Title & Bio
Kent Shefchek - Title & Bio
HMC Team - Team Members, Titles, Bios

Also, I could add the email addresses of the PIs to the Team Page. Let me know if you'd like this. :)

**Comment by kshefchek** [comment]
Hi Sarah, here is my bio.  Melissa, do I have a specific title?  Please feel free to swap my title out with something more accurate.

Kent is a Bioinformatics Engineer with 5 years experience in the medical and academic fields.  He is involved in a variety of research efforts, including whole genome comparitive analysis of bacterial pathogens, transcriptomic profiling of humans and microbes, and 16S analysis of host-associated microbes.  Kent has a BS in Biology from the University of Maryland, College Park and a MS in Biotechnology with a specialization in Bioinformatics from the University of Maryland, University College.

**Comment by bryanlaraway** [comment]
Hi Sarah, let me know if this works for a bio:

Bryan has a BA from Reed College in Biology, post-bac training in MIS from Oregon Institute of Technology, and is currently a Master’s student in Bioinformatics & Computational Biology at Oregon Health & Science University. He is currently a Data Wrangler for the Monarch Initiative, assisting with data ingestion.

**Comment by mellybelly** [comment]
Kent, I think you can decide what to call yourself, but here are some suggestions:
Informatics specialist
bioinformaticist
Bioinformatics engineer (as per your text)
data scientist

**Comment by kshefchek** [comment]
Sounds good, lets go with Bioinfomatics Engineer, thanks!

**Comment by nlwashington** [comment]
Would be great to add the Institutional logos to each (OHSU, LBNL, etc.)

**Comment by harryhoch** [comment]
http://www.communications.pitt.edu/images/shared/pitt.gif

**Comment by kltm** [comment]
Left a comment on the commit--I would say separate styles for every image would be rather unusual.

**Comment by clinic-lbnl** [comment]
Here are the bios for the Harvey Mudd clinic team:

Blurb about clinic:

The Harvey Mudd College Clinic Program is part of a capstone experience for juniors and seniors from all majors.  Teams of 4 or 5 students work with a sponsoring organization on a specific problem over the course of a year.  Our clinic project is working with the Monarch Initiative team to improve the efficiency of the current algorithm for disease comparison in biological ontologies.

Bios:

Marina Johnson:
Marina is currently a senior at Harvey Mudd College, graduating in May with a Bachelors of Science in Mathematics. Marina's prior experiences with product engineering and software testing have been useful in her role as project manager of the Monarch Initiative Clinic Team.   After graduation Marina plans to work in financial modeling at Morgan Stanley, where she hopes to continue to pursue management and technical work.

Ileane O’Leary:
Ileane is currently a senior at Harvey Mudd College, graduating in May with a Bachelors of Science in Joint Computer Science and Mathematics. This past summer, Ileane participated in an NSF funded research project focusing on information retrieval in large graphs at the School of Informatics and Computing at Indiana University. She has been excited to continue pursuing her interest in large graphs as a member of the Monarch Initiative Clinic Team. After graduation, Ileane has accepted a position at SOASTA, a provider of cloud based testing for websites and mobile apps.

Spencer Harris:
Spike is a senior at Harvey Mudd College, graduating this May with a Bachelor of Science in Joint Mathematics and Computer Science. His research interests include combinatorics, complex analysis, and algorithms. After graduation, Spike plans to pursue several avenues of professional development, with a long term goal of starting his own business.

Ki Wan Gkoo:
Ki Wan Gkoo is a junior at Harvey Mudd College and is pursuing a joint computer science & mathematics degree. His extensive coding experience has contributed to the team's bench marking of Monarch Initiative software. His research interests include algorithms and artificial intelligence. This summer, Ki Wan plans to further develop his technical skills as a software development intern at Google.

Kyle Roskamp:
Kyle is a senior chemistry / mathematics double major at Pomona College.  His research interests include atmospheric and environmental chemistry, as well as graph theory and clustering algorithms.  Next year he plans to pursue a Ph.D. in chemistry at either Penn State or UCI.

Professor Bernoff:
Andrew Bernoff is the Diana and Kenneth Jonsson Professor of Mathematics at Harvey Mudd College.  His research specializes in bridging the gaps between Mathematics, Physics, Biology and Engineering with a particular emphasis on using dynamical systems methods to understand experiments and natural phenomena.  Prof. Bernoff was an undergraduate at MIT where he received BS degrees in Mathematics and Physics.  In 1978 he was awarded a Marshall Scholarship to pursue a PhD at the University of Cambridge in England. His PhD studies were on the application of dynamical systems methods in fluid mechanics in the Department of Applied Mathematics and Theoretical Physics (DAMTP).  He is passionate about mentoring undergraduate research, coaching the Harvey Mudd College Putnam Team, and supporting Harvey Mudd College’s Clinic Program, a year-long practicum in which teams of undergraduates work for industrial sponsors on real-world problems and applications.  His research program centers on understanding the behavior of fluids at small scales and modeling the swarming of organisms, in particular locusts.
