### ISSUE TITLE
phenogrid not showing up

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#531]
something happened in the recent commits...(puptent?)  phenogrid is not showing up on tartini.

http://tartini.crbs.ucsd.edu/disease/OMIM_309350
@kshefchek @kltm @harryhoch

**Comment by kshefchek** [comment]
From firebug:
TypeError: this.options.flydata.b is undefined
modeltype.js (line 1039)

Pulled the phenogrid-config branch and it is working, so presumably this will be fixed when branches are merged.

**Comment by harryhoch** [comment]
@kshefchek , correct. That code has been significantly refactored in phenogrid_config. Put a temporary fix in at https://github.com/monarch-initiative/monarch-app/commit/d114ca0cb85e66989fb4f58631137863b33bac26. Should be good to go now.

@nlwashington, I don't think this had anything to do with pup_tent, and that version of modeltype.js hadn't been touched in a month. is it possible that something on the owlsim results got changed?

**Comment by nlwashington** [comment]
@harryhoch , no i don't think owlsim had anything to do with this.  the last i knew several days ago i fixed something that made the grid work, and haven't touched owlsim since.

**Comment by harryhoch** [comment]
weird. the phenogrid code hadn't been changed in weeks either. Is it possible that some of the underlying data changed?
