### ISSUE TITLE
retData.source error when selecting new species

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#532]
when i select a new species to view in the phenogrid (such as Danio rerio), the widget disappears.

http://tartini.crbs.ucsd.edu/disease/OMIM_255800

console says that retData.source is undefined in modeltype.js

**Comment by harryhoch** [comment]
fixed via https://github.com/monarch-initiative/monarch-app/commit/b895605d49d11e0644f0c4937ed37e87f9ae7375.
