### ISSUE TITLE
similarity scores differing wildly

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#536]
getting very different results from similarity scores on production vs. dev. Dev. results in phenogrid:
![master](https://cloud.githubusercontent.com/assets/174707/4287255/89e92008-3da0-11e4-9810-d533471a5163.png)

vs. production:
![production](https://cloud.githubusercontent.com/assets/174707/4287260/913a337e-3da0-11e4-8742-c423a392eb4a.png)

Code is otherwise identical. Not sure if this is a bug, but it seems important to determine which of these is correct

**Comment by nlwashington** [comment]
i am not worried about this.  the scores are now scaled for all items to the best possible match (which is the query to itself), and now caps at 100.
