### ISSUE TITLE
make pubs page prettier

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#541]
http://monarchinitiative.org/page/pubs

this is wall-o-text.  this should be made prettier.  and perhaps updated?

**Comment by nicolevasilevsky** [comment]
I can help update it if I can get editing rights on the website (as long as it's not too complicated to update it.) :)

I agree it could be prettier, and it would be nice to include hyperlinks where available.

**Comment by nlwashington** [comment]
i also like how these guys put a F1000 recommended button...  we have at least one of those papers too!  http://depts.washington.edu/millab/main2.php?page=Publications&navy=3

**Comment by nicolevasilevsky** [comment]
I am working on this. Please see this google doc for the list of current publications and please add any additional publications I missed in the doc.
https://docs.google.com/document/d/1Zv0Tlq5AWd6M9AIV2sdWhgqc19dtee-rDCuWh7Mveyw/edit

**Comment by nlwashington** [comment]
these are now added to the app.  thanks, @nicolevasilevsky.
