### ISSUE TITLE
add analytics to blog

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#544]
we need to add google analytics to our blogger site.

please create a new key.

**Comment by kltm** [comment]
hmmm...seems already built-in actually:

https://www.blogger.com/blogger.g?blogID=7254295243929612792#overviewstats

**Comment by nlwashington** [comment]
Yes, but it's a bit limited. The settings page has a spot for an analytics Id. Maybe it can do more?
