### ISSUE TITLE
phenotype counts wrong

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#545]
From Maryann
Went to Monarch and did the following:

Select:  Find models of disease
Select Model highlight:  
Mouse: Ndrg1/Ndrg1 [involves: 129S1/Sv \* 129X1/SvJ \* C57BL/6]
Result:   Phenotypes (1)
Select:  Phenotype tab
Result:    > 1 phenotype is listed

What is the (1) referring to?

I think this duplicates #456 and is fixed on dev branch by @nlwashington

**Comment by nlwashington** [comment]
as said by @mellybelly, this is fixed on tartini.
