### ISSUE TITLE
classes missing in autocomplete

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#548]
there seem to be some classes that i can't reach using the autocomplete, on either tartini or prod.

i don't seem to find any of the fish phenotypes.  for example, 'absent fin' doesn't show up at all, nor does 'swim bladder'.

however, if i do a general search (by typing 'fin' and then enter (without selecting anything in the dropdown), i can see several kinds of fin phenotypes, but none show up with an autocomplete.
http://tartini.crbs.ucsd.edu/search/fin

http://tartini.crbs.ucsd.edu/search/swim bladder

where did they go?

**Comment by kshefchek** [comment]
I can take a look tomorrow, has anything changed in ontoquest?  I believe the ontoquest calls are slightly different for search and autocomplete but this shouldn't account for much difference (if any) if you're looking at identical terms.

Perhaps we can merge scigraph and test once https://github.com/SciCrunch/SciGraph/issues/37 is fixed.

**Comment by cmungall** [comment]
> Perhaps we can merge scigraph and test once SciCrunch/SciGraph#37 is fixed.

+1

No reason to spend time debugging OQ

**Comment by nlwashington** [comment]
yep, let's just push scigraph and make sure it works there.

**Comment by nlwashington** [comment]
these don't appear in the autocomplete yet, even after the switch to scigraph branch.

**Comment by cmungall** [comment]
It may be because ZP classes start "abnormal(ly)...", and something in the parentheses affects it

It's actually not such a bad thing that ZP classes can't be found until #356 is fixed (and even when it is, ZP is a confusing ontology)

**Comment by kshefchek** [comment]
It looks like this has to do with the limit being set to 20, compare
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/fin.json?limit:20
to
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/fin.json

Should the limit be increased?

**Comment by kshefchek** [comment]
It appears we can autocomplete on zebrafish phenotypes now, closing.
