### ISSUE TITLE
odd cacheing behavior for disease pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#549]
i've noticed that disease pages don't always cache, or the do cache and the fetch*Info doesn't recognize that there is a cache, and/or they cache both a version where the filename has an underscore or a colon.  i think this is especially true when using redirection.

**Comment by cmungall** [comment]
is this deterministic / reproducible?

**Comment by nlwashington** [comment]
we no longer rely on cacheing.
