### ISSUE TITLE
Standardize indentation in monarch-app source

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#557]
@kshefchek - I think you use tab symbols? What editor do you use?

I have emacs javascript-mode set up to use 4 spaces for each level of indentation. My druthers would be to standardize on this

**Comment by kltm** [comment]
I use emacs js2-mode, which also seems to be 4 spaces.

**Comment by kshefchek** [comment]
I'm using eclipse and need to update to the newest version (which fixes this) on one of my computers.

**Comment by harryhoch** [comment]
+1 on emacs. @cmungall, @kltm, do you have any .emacs hacks you're using, or is it straight js-mode?

on a related note, is there any way to re-indent a whole file without github picking up every line as a diff?

**Comment by cmungall** [comment]
not AFAIK. I would just do this as an isolated commit, preferably when we're all on a single branch

**Comment by kshefchek** [comment]
The eclipse issue is fixed for me moving forward, and I'm not currently developing on any branches if we wanted to remove the tab characters.

**Comment by cmungall** [comment]
I'm going for it...

**Comment by cmungall** [comment]
My what a lot of code we have!

**Comment by kshefchek** [comment]
We probably need to clean up widgets.js and webapp.js as well, I can update them if you would like.

**Comment by harryhoch** [comment]
I shudder to think what the results would look like, but perhaps we should even go through the code with something like jslint?
