### ISSUE TITLE
scigraph merger resulting in some TypeErrors in webapp

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#558]
the merger with scigraph has wreaked a bit of havoc on some pages, giving:
TypeError: Cannot read property "http://www.geneontology.org/formats/oboInOwl#hasDbXref" from undefined

two examples:
http://tartini.crbs.ucsd.edu/disease
and 
http://tartini.crbs.ucsd.edu/genotype/MGI_3043397/phenotype_associations.json
(note that the genotype page loads fine, it's the fetching of the json that seems to be problematic.)

**Comment by kshefchek** [comment]
I've made this disease xref code a little more defensive, please let me know if you see any more errors.
