### ISSUE TITLE
simsearch by phenotype returns "Empty JSON string"

### ISSUE THREAD

**Issue by frdougal** [monarch-initiative/monarch-legacy#56]
This URL http://tartini.crbs.ucsd.edu/simsearch/phenotype/?input_items=HP:0002360,HP:0002015,HP:0002063,HP:0002322&target_species=10090

returns SyntaxError: Empty JSON string.  I need this call to get the comparison wodget working.

**Comment by nlwashington** [comment]
Was a problem in owlsim code.  Fixed.
