### ISSUE TITLE
some diseases not resolving

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#562]
this doesn't resolve any more:
http://tartini.crbs.ucsd.edu/disease/OMIM:157900

neither does the altid which should redirect to it:
http://monarchinitiative.org/disease/MESH:C535807

note that it works on prod:
http://monarchinitiative.org/disease/OMIM:157900

**Comment by kshefchek** [comment]
http://geoffrey.crbs.ucsd.edu:9000 is up, but queries are no longer working, for example:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/id/DOID:4.json?callback=fn

If you run in production mode it will use kato instead, which should work if kato is configured for the equivalency redirects.

**Comment by nlwashington** [comment]
@ccondit can you verify status of geoffrey?

**Comment by ccondit** [comment]
Should be back up - not sure what the problem was. Give it another shot.
