### ISSUE TITLE
Remove classes with no counts in datagraphs

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#563]
I've written a function to remove classes with zero counts for the datagraphs.  @nlwashington thoughts on this?  Do we want to keep these to show users the structure of an ontology?

**Comment by harryhoch** [comment]
Showing the structure would be more predictable....

**Comment by kshefchek** [comment]
Predictable from an end user perpesctive or from a programming perspective (or both)?

**Comment by harryhoch** [comment]
end -user.

**Comment by kshefchek** [comment]
That works, I'm suggesting this to clean up some of the graphs where we only have data for about 20% of classes.  Often in these cases the y axis labels get squished together, but I can add some code to dynamically resize the labels (we already do this to adjust for long labels).

On a related note, currently we allow a user to drill down into a class even if it contains zero counts.  Should I remove this feature?  Or is it a possible a user would want to explore subclasses regardless of the number of annotation counts.

**Comment by harryhoch** [comment]
@kshefchek , that sounds like a good plan.  

I think it's ok to allow drill-down or zero counts. It's good for folks to be able to understand what is _not_ there...
