### ISSUE TITLE
failed to load page due to bad NIF request

### ISSUE THREAD

**Issue by nathandunn** [monarch-initiative/monarch-legacy#565]
Here is the bad request generated off of this page:  http://localhost:8080/disease/OMIM_260300

I get the same on tartini: http://tartini.crbs.ucsd.edu/disease/OMIM_260300

but not on production:  http://monarchinitiative.org/disease/OMIM_260300

Getting a 404:
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-3.json
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-1.json
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525.json

This does work:
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-2.json

. . . would it be appropriate to just back-track through the versions?   Not sure.

From below:

[info] REFS:[{"id":"PMID:20301402","label":"GeneReviews","url":"http://www.ncbi.nlm.nih.gov/pubmed/20301402"},{"id":"PMID:19038853","label":"PMID:19038853","url":"http://www.ncbi.nlm.nih.gov/pubmed/19038853"}](lib/monarch/api.js:6978)
[info] [object Object](lib/monarch/api.js:6978)
|all_variant_results| uniq=4
FETCHING: http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-3.json data={"exportType":"data","count":1000,"q":"OMIM:260300"}
RESULT: [object Object]
STATUS: 404
Status != 200. ExchangeObj source=({connection:sun.net.www.protocol.http.HttpURLConnection:http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-3.json?exportType=data&count=1000&q=OMIM%3A260300, done:true, content:"Failed to find resource with ID: nlx_152525-3", contentBytes:{}})
[error] Throwing error:[object Object](lib/monarch/web/webapp.js:367)
[warn]   :type=fetchUrl (lib/monarch/web/webapp.js:369)
[warn]   :url=http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-3.json (lib/monarch/web/webapp.js:369)
[warn]   :status=404 (lib/monarch/web/webapp.js:369)
[warn]   :message=error fetching http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-3.json response code=404 src=({connection:sun.net.www.protocol.http.HttpURLConnection:http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-3.json?exportType=data&count=1000&q=OMIM%3A260300, done:true, content:"Failed to find resource with ID: nlx_152525-3", contentBytes:{}}) (lib/monarch/web/webapp.js:369)
[error] Stack trace= (lib/monarch/web/webapp.js:372)
Using pre-set configuration: 
This is a development server
Using pre-set configuration:

**Comment by nlwashington** [comment]
oh, that might be due to a recent change (this AM) i made to the data...  we weren't really using those data at all, and it was bulking up the api... i thought i had removed the api calls from the app, but clearly i didn't!  yikes.  let me see what i can do.  glad i didn't break prod.

**Comment by nlwashington** [comment]
fixed in commit 468e543

**Comment by nathandunn** [comment]
that did it thanks
