### ISSUE TITLE
add alternative names to genes pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#568]
The gene pages don't appear to list synonyms or alternative names.  

For example:
http://tartini.crbs.ucsd.edu/gene/NCBIGene_9060
Is this one: http://www.ncbi.nlm.nih.gov/gene?cmd=Retrieve&list_uids=9060
should show:  SK2; BCYM4; ATPSK2

**Comment by kshefchek** [comment]
We can get these from scigraph, although possibly just with human genes for now.  Would this go in the jumbotron or in the cross references table (or somewhere else)?

**Comment by mellybelly** [comment]
This is great- also know that no one source has them all so collating them is very valuable.
I think the jumbotron would be better.

**Comment by nlwashington** [comment]
there’s a couple of places… there are some synonyms in the nif-0000-02801-1, so let’s start with that.

**Comment by kshefchek** [comment]
Added synonyms from nif-0000-02801-1, are there any other resources I can add?

**Comment by nlwashington** [comment]
for now, let's just do this.  eventually, we'll be able to get the synonyms directly from scigraph.
