### ISSUE TITLE
Browse Anatomy decisions

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#57]
Currently in the Browse menu (http://tartini.crbs.ucsd.edu/anatomy/), we have enabled browsing of Uberon/CL. However, the links go to pages like this: http://tartini.crbs.ucsd.edu/anatomy/UBERON_0004446
which while they have the uberon anatomy info don't have links to expression or phenotypes yet, have "To Do" listed as the source, and need some cleanup on the definitions (e.g. An epiphysis that is part of a phalanx [Automatically generated definition]. [definition]).

Should we either disallow anatomy navigation for now, or hide some of these features? Or at least say something like "coming soon" instead of "ToDo".

Note this has implications for the current homepage lower right quadrant as well.

**Comment by harryhoch** [comment]
I suggest disallow. 
On 24 Jan 2014, at 2:53 PM, Melissa Haendel notifications@github.com wrote:

> Currently in the Browse menu (http://tartini.crbs.ucsd.edu/anatomy/), we have enabled browsing of Uberon/CL. However, the links go to pages like this: http://tartini.crbs.ucsd.edu/anatomy/UBERON_0004446
> which while they have the uberon anatomy info don't have links to expression or phenotypes yet, have "To Do" listed as the source, and need some cleanup on the definitions (e.g. An epiphysis that is part of a phalanx [Automatically generated definition]. [definition]).
> 
> Should we either disallow anatomy navigation for now, or hide some of these features? Or at least say something like "coming soon" instead of "ToDo".
> 
> Note this has implications for the current homepage lower right quadrant as well.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300
