### ISSUE TITLE
Update team members page on Monarch website

### ISSUE THREAD

**Issue by nicolevasilevsky** [monarch-initiative/monarch-legacy#574]
We need to update the list of monarch team members page on the Monarch site. I also wonder if this would be better underneath the "about" tab. There isn't actually any contact info for any of us, so it seems a bit confusing under the "contact" tab.

http://monarchinitiative.org/page/team

**Comment by harryhoch** [comment]
agreed about the move. 
will update the Pitt section.

**Comment by mellybelly** [comment]
@harryhoch or @kltm can you make suggestions for how to improve this page? Its terribly long and hard to find people. The team needs to look strong and diverse.

**Comment by harryhoch** [comment]
It would take a bit of HTML/Javascript coding, but we could do something like this if we had good figures: 
http://www.rdcollab.com/people/

**Comment by nicolevasilevsky** [comment]
I like this one too:
http://md2k.org/about/meet-our-team/

I like the bottom half with the pictures and titles, then it links to longer descriptions.

I can help gather the photos, text if needed.

**Comment by mellybelly** [comment]
I like the first one better, more overview-ey and less org-chart-ey. 
but both are really a lot nicer than what we have now.

**Comment by nlwashington** [comment]
if we're giving examples, i like these:
http://betaworks.com/#team
http://www.littlelines.com/about

**Comment by kltm** [comment]
I don't think I'll have time for this, but the most bang-for-the-buck thing to do would be to stay within the framework and use the BS3 scrollspy mechanism (notice the right as you scroll down):

 http://getbootstrap.com/javascript/

**Comment by mellybelly** [comment]
Can someone make this happen for our June release? Our team looks so sad :-(
I like this one: http://centerforopenscience.org/about_team/
@kltm please reassign to @kshefchek if you don't have time, but I thought you would have the most insight.

**Comment by kltm** [comment]
Maybe a couple of days to get something good? I'd reiterate https://github.com/monarch-initiative/monarch-app/issues/574#event-297788742 that the most efficient attack on this would probably be within BS3 or an aligned plugin, but I don't see having that kind of time short-term. I'll check the couch though.

(Although, frankly, I'm fine with text descriptions and hyperlinks--they work if somebody is trying to track you down.)

**Comment by kltm** [comment]
From today's meeting, at a low priority (will cross as completed):
- ~~YAMLify the person content~~
- ~~create new template for page~~
- add to output
  - ~~pics~~
  - ~~contact info~~
- ~~TOC~~

Other people need to:
- send me any contact information for themselves or their institution they want added
- any pictures of themselves they want added

**Comment by jnguyenx** [comment]
Here's a Bootstrap snippet that I like:

http://bootsnipp.com/snippets/featured/fancy-tabs-responsive

The problem is that you have to click to see the description.

Otherwise there's this more fancy snippet:

http://bootsnipp.com/snippets/featured/dynamic-avatar-blur

**Comment by kltm** [comment]
Okay, I've gone as far as I think I'm going to be able to get before your release. Somebody else should be able to pick this up pretty easily now and try to make it a little spiffier--the template is now much more compact and can be easily changed to try different things. Changes from the old page are TOC, optional people pictures and contact info, and YAML-driven.

The institution/people information is now stored in conf/monarch-team.yaml. For now, it needs to be changed into JSON to be used by webapp.js, so:

``` shell
npm install
./node_modules/.bin/js-yaml ./conf/monarch-team.yaml > ./conf/monarch-team.json
```

The first command only needs to be run the first time. If you have some other YAML to JSON tool, that's fine too. People can also check that the YAML file is correct with kwalify and conf/monarch-team.schema.yaml.

For an example of a user using all of the fields, look at "Rocky" in monarch-team.yaml.

It's currently setup for all social icons and people pictures to be square (and smallish).

At least the following images will need to be changed to something appropriate before moving to production:
- image/logo-email.png
- image/logo-facebook.png
- image/logo-twitter.png
- image/logo-website.png
- image/person-unknown.png

**Comment by kltm** [comment]
knocked back to @kshefchek as requested https://github.com/monarch-initiative/monarch-app/issues/574#issuecomment-99277003

**Comment by kltm** [comment]
Add to add to that, the template to modify is here: templates/page/team.mustache

**Comment by jmcmurry** [comment]
I see that @kltm has marked contact info as crossed out in his May 7 comment. I think this could be because the mustache template now accommodates contact info, and not because the data itself has been actually collated. I have a list of some email addresses and names from Nicole today.
1) Do people want to use these email addresses? I personally am a little bit reluctant, would rather avoid the spambots.

**Comment by kltm** [comment]
The template and config now accommodate, so crossed out; the information was not collected as it was assumed that people/groups would add what they felt appropriate.

I, personally, would really rather not be spammed. There is no real way of allowing contacting without allowing spam, but one way to keep it centralized at least is to have a contact form. There are also JS ways of slowing down spambots, but this will be less effective over time.

**Comment by jmcmurry** [comment]
@kltm agreed. I will leave it to each person to decide for themselves. However, it would be nice if folks can let me know when they are done so that the ticket can be closed at least in terms of content. Re-styling can be the next step.

**Comment by nicolevasilevsky** [comment]
My bio is done. Thanks!

**Comment by mellybelly** [comment]
one more person to add to the team page for OHSU @markengelstad  
Mark can you send @jmcmurry a picture?

**Comment by jmcmurry** [comment]
@markengelstad could you send a picture please? I would like to close the content part of this ticket.

**Comment by jmcmurry** [comment]
Nicole V got some pics up on ohsu site; will repurpose these...

**Comment by monicacecilia** [comment]
Wire went quiet for 2 years. 
Functional page with info is available at http://monarchinitiative.org/page/team
IMHO it could use a facelift, but we'll worry about that later.

:bowtie:
