### ISSUE TITLE
request entity too large for Shh comparison - 413

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#575]
i am currently getting a 413 error (request entity too large) when doing the simsearch call for Shh and drosophila:

http://owlsim.crbs.ucsd.edu/searchByAttributeSet?a=MP%3A0000033&a=MP%3A0000041&a=MP%3A0000074&a=MP%3A0000077&a=MP%3A0000087&a=MP%3A0000088&a=MP%3A0000090&a=MP%3A0000094&a=MP%3A0000102&a=MP%3A0000107&a=MP%3A0000109&a=MP%3A0000118&a=MP%3A0000128&a=MP%3A0000137&a=MP%3A0000138&a=MP%3A0000141&a=MP%3A0000149&a=MP%3A0000150&a=MP%3A0000159&a=MP%3A0000163&a=MP%3A0000164&a=MP%3A0000166&a=MP%3A0000266&a=MP%3A0000270&a=MP%3A0000291&a=MP%3A0000352&a=MP%3A0000377&a=MP%3A0000378&a=MP%3A0000383&a=MP%3A0000388&a=MP%3A0000414&a=MP%3A0000428&a=MP%3A0000432&a=MP%3A0000433&a=MP%3A0000434&a=MP%3A0000438&a=MP%3A0000443&a=MP%3A0000453&a=MP%3A0000455&a=MP%3A0000460&a=MP%3A0000462&a=MP%3A0000467&a=MP%3A0000468&a=MP%3A0000473&a=MP%3A0000474&a=MP%3A0000484&a=MP%3A0000495&a=MP%3A0000496&a=MP%3A0000519&a=MP%3A0000536&a=MP%3A0000547&a=MP%3A0000551&a=MP%3A0000554&a=MP%3A0000556&a=MP%3A0000557&a=MP%3A0000558&a=MP%3A0000561&a=MP%3A0000562&a=MP%3A0000564&a=MP%3A0000565&a=MP%3A0000566&a=MP%3A0000571&a=MP%3A0000572&a=MP%3A0000639&a=MP%3A0000646&a=MP%3A0000755&a=MP%3A0000767&a=MP%3A0000774&a=MP%3A0000780&a=MP%3A0000783&a=MP%3A0000787&a=MP%3A0000808&a=MP%3A0000820&a=MP%3A0000830&a=MP%3A0000832&a=MP%3A0000849&a=MP%3A0000851&a=MP%3A0000852&a=MP%3A0000854&a=MP%3A0000872&a=MP%3A0000873&a=MP%3A0000875&a=MP%3A0000880&a=MP%3A0000886&a=MP%3A0000889&a=MP%3A0000897&a=MP%3A0000914&a=MP%3A0000925&a=MP%3A0000926&a=MP%3A0000929&a=MP%3A0000932&a=MP%3A0000934&a=MP%3A0000937&a=MP%3A0000939&a=MP%3A0000955&a=MP%3A0000956&a=MP%3A0001046&a=MP%3A0001175&a=MP%3A0001176&a=MP%3A0001178&a=MP%3A0001181&a=MP%3A0001218&a=MP%3A0001219&a=MP%3A0001222&a=MP%3A0001243&a=MP%3A0001262&a=MP%3A0001265&a=MP%3A0001284&a=MP%3A0001286&a=MP%3A0001293&a=MP%3A0001297&a=MP%3A0001302&a=MP%3A0001325&a=MP%3A0001330&a=MP%3A0001340&a=MP%3A0001393&a=MP%3A0001399&a=MP%3A0001402&a=MP%3A0001406&a=MP%3A0001489&a=MP%3A0001513&a=MP%3A0001622&a=MP%3A0001672&a=MP%3A0001691&a=MP%3A0001697&a=MP%3A0001698&a=MP%3A0001700&a=MP%3A0001704&a=MP%3A0001718&a=MP%3A0001719&a=MP%3A0001730&a=MP%3A0001732&a=MP%3A0001748&a=MP%3A0001785&a=MP%3A0001861&a=MP%3A0001906&a=MP%3A0001935&a=MP%3A0001954&a=MP%3A0002006&a=MP%3A0002058&a=MP%3A0002060&a=MP%3A0002064&a=MP%3A0002066&a=MP%3A0002080&a=MP%3A0002081&a=MP%3A0002083&a=MP%3A0002092&a=MP%3A0002102&a=MP%3A0002109&a=MP%3A0002110&a=MP%3A0002114&a=MP%3A0002115&a=MP%3A0002116&a=MP%3A0002127&a=MP%3A0002132&a=MP%3A0002135&a=MP%3A0002151&a=MP%3A0002169&a=MP%3A0002175&a=MP%3A0002182&a=MP%3A0002184&a=MP%3A0002191&a=MP%3A0002196&a=MP%3A0002233&a=MP%3A0002234&a=MP%3A0002235&a=MP%3A0002264&a=MP%3A0002282&a=MP%3A0002284&a=MP%3A0002543&a=MP%3A0002544&a=MP%3A0002576&a=MP%3A0002633&a=MP%3A0002650&a=MP%3A0002665&a=MP%3A0002691&a=MP%3A0002726&a=MP%3A0002728&a=MP%3A0002741&a=MP%3A0002764&a=MP%3A0002765&a=MP%3A0002768&a=MP%3A0002818&a=MP%3A0002858&a=MP%3A0002874&a=MP%3A0002898&a=MP%3A0002908&a=MP%3A0002909&a=MP%3A0002932&a=MP%3A0002948&a=MP%3A0002950&a=MP%3A0002989&a=MP%3A0002990&a=MP%3A0003012&a=MP%3A0003054&a=MP%3A0003069&a=MP%3A0003078&a=MP%3A0003115&a=MP%3A0003120&a=MP%3A0003130&a=MP%3A0003161&a=MP%3A0003189&a=MP%3A0003244&a=MP%3A0003271&a=MP%3A0003283&a=MP%3A0003321&a=MP%3A0003345&a=MP%3A0003424&a=MP%3A0003425&a=MP%3A0003446&a=MP%3A0003451&a=MP%3A0003626&a=MP%3A0003631&a=MP%3A0003632&a=MP%3A0003634&a=MP%3A0003641&a=MP%3A0003672&a=MP%3A0003704&a=MP%3A0003710&a=MP%3A0003723&a=MP%3A0003743&a=MP%3A0003793&a=MP%3A0003809&a=MP%3A0003885&a=MP%3A0003923&a=MP%3A0003932&a=MP%3A0003953&a=MP%3A0003984&a=MP%3A0004007&a=MP%3A0004098&a=MP%3A0004100&a=MP%3A0004101&a=MP%3A0004137&a=MP%3A0004173&a=MP%3A0004180&a=MP%3A0004196&a=MP%3A0004200&a=MP%3A0004201&a=MP%3A0004251&a=MP%3A0004268&a=MP%3A0004269&a=MP%3A0004274&a=MP%3A0004275&a=MP%3A0004276&a=MP%3A0004277&a=MP%3A0004313&a=MP%3A0004315&a=MP%3A0004354&a=MP%3A0004355&a=MP%3A0004358&a=MP%3A0004369&a=MP%3A0004372&a=MP%3A0004391&a=MP%3A0004419&a=MP%3A0004423&a=MP%3A0004442&a=MP%3A0004473&a=MP%3A0004505&a=MP%3A0004506&a=MP%3A0004507&a=MP%3A0004508&a=MP%3A0004509&a=MP%3A0004538&a=MP%3A0004551&a=MP%3A0004553&a=MP%3A0004576&a=MP%3A0004620&a=MP%3A0004634&a=MP%3A0004658&a=MP%3A0004712&a=MP%3A0004872&a=MP%3A0004880&a=MP%3A0004980&a=MP%3A0004981&a=MP%3A0005076&a=MP%3A0005104&a=MP%3A0005109&a=MP%3A0005157&a=MP%3A0005163&a=MP%3A0005213&a=MP%3A0005296&a=MP%3A0005298&a=MP%3A0005306&a=MP%3A0005325&a=MP%3A0005358&a=MP%3A0005359&a=MP%3A0005371&a=MP%3A0005376&a=MP%3A0005380&a=MP%3A0005381&a=MP%3A0005384&a=MP%3A0005385&a=MP%3A0005386&a=MP%3A0005388&a=MP%3A0005389&a=MP%3A0005390&a=MP%3A0005391&a=MP%3A0005430&a=MP%3A0005493&a=MP%3A0005508&a=MP%3A0005592&a=MP%3A0005606&a=MP%3A0005621&a=MP%3A0005643&a=MP%3A0005650&a=MP%3A0006030&a=MP%3A0006042&a=MP%3A0006097&a=MP%3A0006098&a=MP%3A0006126&a=MP%3A0006197&a=MP%3A0006261&a=MP%3A0006279&a=MP%3A0006290&a=MP%3A0006306&a=MP%3A0006382&a=MP%3A0006402&a=MP%3A0008004&a=MP%3A0008056&a=MP%3A0008291&a=MP%3A0008302&a=MP%3A0008489&a=MP%3A0008540&a=MP%3A0008789&a=MP%3A0008947&a=MP%3A0008948&a=MP%3A0008985&a=MP%3A0009204&a=MP%3A0009211&a=MP%3A0009545&a=MP%3A0009584&a=MP%3A0009703&a=MP%3A0009743&a=MP%3A0009844&a=MP%3A0009883&a=MP%3A0009887&a=MP%3A0009888&a=MP%3A0009890&a=MP%3A0009901&a=MP%3A0009903&a=MP%3A0009905&a=MP%3A0009937&a=MP%3A0010030&a=MP%3A0010059&a=MP%3A0010149&a=MP%3A0010493&a=MP%3A0010646&a=MP%3A0010701&a=MP%3A0010768&a=MP%3A0010771&a=MP%3A0010784&a=MP%3A0010825&a=MP%3A0010897&a=MP%3A0010907&a=MP%3A0010915&a=MP%3A0010940&a=MP%3A0010942&a=MP%3A0010949&a=MP%3A0010975&a=MP%3A0010976&a=MP%3A0010994&a=MP%3A0011011&a=MP%3A0011024&a=MP%3A0011028&a=MP%3A0011071&a=MP%3A0011085&a=MP%3A0011086&a=MP%3A0011087&a=MP%3A0011089&a=MP%3A0011090&a=MP%3A0011098&a=MP%3A0011100&a=MP%3A0011101&a=MP%3A0011108&a=MP%3A0011109&a=MP%3A0011333&a=MP%3A0011360&a=MP%3A0011378&a=MP%3A0011380&a=MP%3A0011426&a=MP%3A0011732&a=MP%3A0011805&a=MP%3A0012089&a=MP%3A0012091&a=MP%3A0012139&a=MP%3A0012257&a=MP%3A0012270&a=MP%3A0012517&a=MP%3A0012528&target=FBgenoInternal&limit=10

this causes the phenogrid not to load.  we need to fix the owlsim call and fix the api to handle gracefully when the results don't come back.  Shh is a favorite.

**Comment by kltm** [comment]
Either the server needs to take larger requests or the request needs to be a POST.

**Comment by cmungall** [comment]
owlsim takes POST, so can the wrapper call be modified?

**Comment by harryhoch** [comment]
Nicole, I assume that you did this via the interface and that the simsearch call was what was generated in populating the phenogrid?

The obvious change to engine.searchByAttributeSet will make this a post. Are we ok with having that be the default behavior?
