### ISSUE TITLE
Add general purpose testing suite for scientists and developers (includes Selenium testing)

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#576]
Develop selenium tests for UI

**Comment by kltm** [comment]
This ticket is to seed this with work done on geneontology/amigo#176 and geneontology/go-site#50.
There will be an ongoing effort to fill this out as part of the development/QA process.
Pinging on @cmungall .

**Comment by kltm** [comment]
Added Jenkins test (untested, but will see soon enough).
