### ISSUE TITLE
autocomplete not searching synonyms quite well

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#577]
Some synonyms not showing up in autocomplete

"impaired contractility of detrusor muscle"
"renal inflamation"

but 
"quivering"
does show up.

renal inflamation does show up in a scigraph result

**Comment by kshefchek** [comment]
For testing, what term are you entering and what are the expected results?  Could this have to do with the 20 term limit for autocomplete?

**Comment by nlwashington** [comment]
the 3 items quoted above are what is typed into the search autocomplete box.  here's the scigraph query of them:

http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/prefix/impaired%20contractility%20of%20detrusor%20muscle?limit=20&searchSynonyms=true&callback=fn

http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/prefix/renal%20infl?limit=20&searchSynonyms=true&callback=fn

http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/prefix/quivering?limit=20&searchSynonyms=true&callback=fn

**Comment by kshefchek** [comment]
Looks like there was a whitespace issue.  A regex/replace fixes it, although is there a more elegant solution for URL encoding?

This was the error I was seeing:
[error] Throwing error:TypeError: Cannot call method "decodeToString" of undefined (ringo/httpclient.js#315) (lib/monarch/web/webapp.js:376)
[warn]   :message=Cannot call method "decodeToString" of undefined (lib/monarch/web/webapp.js:378)

As for the synonyms, were currently storing these but not displaying them in the drop down box.  Am I understanding correctly that we want to see these in the drop down box along with the autocomplete results?

**Comment by kshefchek** [comment]
Disregard that last message, encodeURI() should fix the whitespace issue.

**Comment by kshefchek** [comment]
This is working now, see:

http://tartini.crbs.ucsd.edu/autocomplete/impaired%20contractility%20of%20detrusor%20muscle.json
http://tartini.crbs.ucsd.edu/autocomplete/renal%20inflammation.json
