### ISSUE TITLE
refactor analyze page; undo cookies, use REST-y calls

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#578]
The current analyze page needs to be refactored.  It currently uses a cookie mechanism to save state, but is causing some odd behavior of inserting selected phenotypes into empty searches.

This should be refactored so that the selected phenotypes are added (and introduced into a query via the search button) that they get inserted into the URL:
http://tartini.crbs.ucsd.edu/analyze/phenotypes/?input_items=MP_0004123&limit=100&target_species=

the server can then take care of returning the labels of the terms upon loading.

any time the selected terms are removed or new ones added (followed by a search refresh), a new url is built and page is loaded.  this will also make it easier to enter/link to the analyze page from external pages with a list of phenotypes.

**Comment by VincentIII** [comment]
Fix with commit: https://github.com/monarch-initiative/monarch-app/commit/74e8fe19ae8c99b3ec6f1abb3ee17da9b791c24a

**Comment by cmungall** [comment]
Reopening as the the committed change to api.js uses fetchPhenotypeInfo() to fetch labels, this takes too long

**Comment by harryhoch** [comment]
@cmungall, is there a good alternative that we might use instead?

**Comment by cmungall** [comment]
fetchClassInfo (which wraps a call to SG)

e.g.

```
cls = engine.fetchClassInfo(id);
labels = cls.label;
```

for optimized results: fetchClassInfo(id,{level:0})

which doesn't bother with graph info, which you don't need

**Comment by harryhoch** [comment]
thanks. @VincentIII, please look into this ASAP.

**Comment by cmungall** [comment]
Once this is done the test suite should pass: http://build.berkeleybop.org/view/Monarch/

(the naming of the tests is a bit confusing, sorry)

**Comment by harryhoch** [comment]
fixed with https://github.com/monarch-initiative/monarch-app/commit/45d33b129c97871d330eefb382ff79772b79e829, so no need to worry about @VincentIII. @cmungall, I don't see it passing just yet, but I will check back soon.

**Comment by cmungall** [comment]
Thx, fix pushed to stage, works great now, happy TG!
