### ISSUE TITLE
better description/docs/design on objects

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#579]
the json objects that are returned in the current monarch-app are loaded with redundancy, and were stitched together a bit adhoc.  the json that is returned is really that designed to populate a set of "association tables", but maybe not what we should serve up?

i think given what we know now, we probably should go back to some first-principles for the top-level objects, and spec out what should be included.  for example, on gene pages l ike:
http://tartini.crbs.ucsd.edu/gene/NCBIGene:7291.json
i suspect that we should not have the "literature" and "pmidinfo", the latter of which i think is a convenience for the literature tab, but i don't know what the first one is for?
i also find it odd that the orthologs are actually ortholog-associations, and that the self gene is referenced in each association.  (why isn't it just a list of genes with provenance for the orthology call?).  similarly for the disease_association... it lists the same gene over and over... of course it's the same gene, we're on a gene page!
when i run this on my localhost, i also have phenotype_associations along with a phenotype_list, which repeats a lot of the information.

i ran across this again as i started to update the "orthologs" object for a gene.  i wanted to add an ortholog list to the genes in the disease_associations, but found that i was just repeating the same list over and over again, when it was just in the top level object.  

i think we need to carefully think about what kind of information should be returned in the objects for a page... should the json be plainly what we need to render the page, with all sorts of redundancy?  or should it be a nice, clean, well-defined object, which is distinct from the way it is rendered?

**Comment by kltm** [comment]
As a thought, another way of approaching this in a more structured way would be that while there are "objects" returned, the operations on them are defined by JS classes and their subclasses, using the JSON blobs as constructor arguments. For example:

https://kltm.github.io/bbop-js/docs/files/rest/response-js.html
https://kltm.github.io/bbopx-js/docs/files/barista/response-js.html

This would make programmatic operations and probing much easier (for example, defining what a "legit" return is for 404s without spreading ad hoc code outside the class), while still giving access to raw JSON if necessary for things like mustache templates.

**Comment by kltm** [comment]
Design and documentation would also fall more naturally into class documentation.

**Comment by cmungall** [comment]
Suggest closing as no longer relevant. Possible new ticket about JSON API
