### ISSUE TITLE
Monarch About page has layout issues with images

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#580]
There are serious layout issues on the new "About" page, with images often getting outside of the containers bounds. I suspect that the BS3 image structure and classes are not applied properly.

The process of fixing these may be related to the larger refresh of templates and structure when switching to the new ones being developed for the home page.

![screenshot from 2014-10-30 14 55 54](https://cloud.githubusercontent.com/assets/2687900/4852879/4ef11174-6080-11e4-96e0-b22827fc24f1.png)

**Comment by jmcmurry** [comment]
This is super old and it isn't happening on my machine. @kltm could you comment about a) whether you're still seeing it b) if so, what your environment is? If you're not seeing it anymore, lets close. Thanks

**Comment by kltm** [comment]
Looks like somebody got that along the way.
