### ISSUE TITLE
Testing with Familial Mediterranean Fever

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/monarch-legacy#581]
ORPHANET:342 and OMIM_249100 should be merged into the one disease they are. They've got different number of annotations and likely more differences/similarities, but they're the same disease. 

In addition there is another OMIM record for FMF which is autosomal dominant.

Be sensible to have these rationally connected.

**Comment by mellybelly** [comment]
migrated to https://github.com/monarch-initiative/human-disease-ontology/issues/23
