### ISSUE TITLE
Source names need hover description

### ISSUE THREAD

**Issue by selewis** [monarch-initiative/monarch-legacy#583]
Any time there is a mini (micro) source icon the hover should display the full name of the source (so the user doesn't have to look someone else to figure out what the source actually is).

**Comment by jmcmurry** [comment]
This appears to have been implemented where I have seen it.
![screen shot 2015-10-09 at 16 07 17](https://cloud.githubusercontent.com/assets/3658863/10407471/e54d04ba-6e9f-11e5-947c-5523ab9ed75e.png)
If there is a context where it is still missing, please so describe and reopen, thanks.
I'm going to provisionally close.
