### ISSUE TITLE
find images for banner

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#587]
find images to overlay in banner on homepage. 
@kltm let me know if there are any constraints other than licensing.

**Comment by kltm** [comment]
Given our current color scheme, lighter primary colors on black backgrounds would be optimal.
Anything darker that I could convert to a black background would be fine as well, but slightly more work; and on from there.

**Comment by mellybelly** [comment]
http://commons.wikimedia.org/wiki/File:Ovamat4wb.jpg
(use only top half)
CC-BY-SA 3.0

<strike>http://commons.wikimedia.org/wiki/File:Zebrafish-Embryo-dark-field.jpg</strike>
<strike>(use left half)</strike>
<strike>CC-BY 2.5</strike>

http://commons.wikimedia.org/wiki/File:Zebrafish95-300.jpg
possibly too light a background
PD

<strike>http://upload.wikimedia.org/wikipedia/commons/7/7d/Haeckel_Anthropogenie_1874.jpg</strike>
<strike>(use either half, i like left half but has some glare)</strike>
<strike>quality</strike>

<strike>https://commons.wikimedia.org/wiki/File:Drosophila_melanogaster_brain_expression_patterns.jpg</strike>
<strike>(use colored right half)</strike>
<strike>CC-BY 2.0</strike>

<strike>http://www.vetmed.vt.edu/education/curriculum/vm8054/labs/lab8/IMAGES/Chickbon.JPG</strike>
<strike>(probably too light but cool!)</strike>
<strike>http://www.vetmed.vt.edu/education/curriculum/vm8054/labs/lab8/lab8.htm</strike>
<strike>restrictive copyright</strike>

https://commons.wikimedia.org/wiki/File:Cajal_cortex_drawings.png
(light background but classic and can be overlayed)
PD

https://commons.wikimedia.org/wiki/File:Slcla3_in_Bergmann_Glia.jpg
PD

https://commons.wikimedia.org/wiki/File:Astrocyte5.jpg
CC-BY-SA 3.0

**Comment by kltm** [comment]
Great, thank you! I can work with these for the landing. Will also have to likely add attributions to the bottom/footer unless all PD.

For #518.

**Comment by mellybelly** [comment]
Note these were all labeled for distribution in Google.

**Comment by kltm** [comment]
Distributable may still have various attribution clauses in the license. I'll check on the ones we end up using.

**Comment by kltm** [comment]
Updated the information on @mellybelly images to include original sources and licensing.

**Comment by kltm** [comment]
And for the images currently in use in the demo:

https://commons.wikimedia.org/wiki/File:High_School_Biology_Cover.jpg
CC-BY-SA 3.0

https://commons.wikimedia.org/wiki/File:GinkgoLeaves.jpg
CC-BY-SA 3.0

https://commons.wikimedia.org/wiki/File:White_flowers_b.jpg
CC-BY-SA 3.0

<strike>https://commons.wikimedia.org/wiki/File:HIV_on_macrophage.png</strike>
<strike>CC-BY 2.5</strike>

**Comment by kltm** [comment]
I will likely just choose things using CC-BY-SA 3.0 to keep the attributions, etc. as simple as possible. Edit lists above.
