### ISSUE TITLE
Add phenotype annotation distribution to home page

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#592]

**Comment by kshefchek** [comment]
I've added the datagraph to home page and created a test page here:
http://tartini.crbs.ucsd.edu/labs/scratch-homepage

Unfortunately it is not yet resizable, but it is small enough that this shouldn't be a major issue.

I've also added some functionality to switch the breadcrumb shapes on/off via the configuration file (see #590) if we want to explore using pure text breadcrumbs.

**Comment by kltm** [comment]
Looking good.
However, it's pretty easy to find window sizes such that controls and key information are not visible on the screen, such as (alas) my default browser size and when using a phone. is the resizability looking feasible #591?

**Comment by kshefchek** [comment]
It's definitely feasible, I'm hoping to have something in the next few days.

**Comment by kshefchek** [comment]
@kltm what do you think is a good width to fit mobile screens?  Right now the graph is ~465 pixels wide, so theoretically this should fit most modern phones.  I've tested on an iphone 4 and 5, which both have 640px when held veritcally, and I'm noticing on browser load the page is slightly "zoomed in" and user would have to zoom out to see the entire graph.  I'm assuming this is something bootstrap is controlling?

Rather than hack around this, I'm thinking in the interim while I develop the fully dynamic resizing, is just have multiple configuration variables in the config js file, since this is what determines the sizes of various graph elements.  I talked about this briefly on the last call and it would be very easy to implement and test with the idea that this is just a temporary fix.

**Comment by kltm** [comment]
Mobiles and tablets are all over the place--without analytics, you can't really tell.
I can't speak for others, but I feel like the best solution here is to maintain correct sizing, even at the cost of functionality. I'd say leave the images (or whatever) in until the widget can conform to the space that it is given, at least initially.

**Comment by harryhoch** [comment]
@kshefchek is this done enough to close out? Or do we have more in mind?

**Comment by jmcmurry** [comment]
@kshefchek is this done enough to close out? Or do we have more in mind?

**Comment by kshefchek** [comment]
Closing for now, please reopen if we want to revisit adding the chart to the home page
