### ISSUE TITLE
Add headings to search result tables and display "no results" message when applicable

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#593]

**Comment by kshefchek** [comment]
How does this look?  Not the most aesthetically pleasing but I could add styling if needed.
![search-1](https://cloud.githubusercontent.com/assets/1467299/5149706/77d1db12-7199-11e4-9c14-6d1bbd1fc75b.png)

![screen-2](https://cloud.githubusercontent.com/assets/1467299/5149709/7d82b950-7199-11e4-87ca-468ab306e3fd.png)

**Comment by mellybelly** [comment]
Definitely much better!

Not sure if most users will know what an ontology is though. 
Perhaps "exact match"? or "category match"?
Also hoping we'll be able to show _what_ is matching?

@nlwashington or @harryhoch might have ideas too

**Comment by harryhoch** [comment]
Agreed. Can we give a sentence or two of description of what the ontology and/or site searches are likely to provide?

**Comment by kshefchek** [comment]
@mellybelly - sure, I'll go with "Exact Match" for now.
@harryhoch - Were you thinking an info icon, similar to the phenogrid, or just something in the html under the headings?

**Comment by harryhoch** [comment]
some text would be helpful, right under the headings.

**Comment by kshefchek** [comment]
How does this sound?
Exact Match
Results for {{term}} searching phenotypes, diseases, genes, and models
Site Search
Results for {{term}} using a general search over all text fields

Do we want these descriptions to show up only when results are generated?

**Comment by mellybelly** [comment]
I like that Kent, and yes only show when results are generated.
