### ISSUE TITLE
definitions not displayed on phenotype pages

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#599]
i don't think that phenotype definitions are showing up.

for example:
http://tartini.crbs.ucsd.edu/phenotype/HP:0100750

but there is a textual definition here:
http://www.human-phenotype-ontology.org/hpoweb/showterm?id=HP:0100750
"Collapse of part of a lung associated with absence of inflation (air) of that part."

note that it shows up in the scigraph query:
http://kato.crbs.ucsd.edu:9000/scigraph/vocabulary/id/HP:0100750?callback=fn

**Comment by kshefchek** [comment]
The definition is missing from geoffrey and lurch:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/id/HP:0100750.json?callback=fn
http://lurch.crbs.ucsd.edu:9000/scigraph/vocabulary/id/HP:0100750.json?callback=fn
@ccondit was this moved to another query service on scigraph?

**Comment by ccondit** [comment]
@kshefchek definitions should be back now (on dev and beta).

**Comment by kshefchek** [comment]
Thanks!
