### ISSUE TITLE
albinism has no models with the phenotype

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#601]
it seems that the human phenotype of albinism http://tartini.crbs.ucsd.edu/phenotype/HP_0001022

should be related to the mouse phenotype of albinism:  http://tartini.crbs.ucsd.edu/phenotype/MP:0005171

but they are only related via abnormal hair/coat phenotype.

**Comment by selewis** [comment]
Shouldn't this (also) go on the ontology tracker?

On Tue, Nov 25, 2014 at 1:21 PM, Nicole Washington <notifications@github.com

**Comment by iamkoehler** [comment]
I do not see the exact word “albinism” in MP. This is the reason why the text-matching based method won’t work here. I’ll look into the logical definitions.

Thanks,
Sebastian

**Comment by iamkoehler** [comment]
Seems that this is the best we can get at the moment.

MP: fur or hair is devoid of coloration and appears white
HP: An abnormal reduction in the amount of pigmentation (reduced or absent) of skin, hair and eye (iris and retina).

The first thing that these two have in common is the "abnormal hair/coat phenotype”.

Sebastian

**Comment by mellybelly** [comment]
added to phenotype tracker, and closing here. 
https://code.google.com/p/phenotype-ontologies/issues/detail?id=114
