### ISSUE TITLE
bring back direct-tab navigation with #

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#606]
We used to be able to open right to a specific tab in our app on any given page using the standard bookmarking style with the hash.  But this doesn't seem to be working anymore.

For example, with this url:
http://stage-monarch.monarchinitiative.org/disease/OMIM:158320#Genes
I want to go straight to the genes tab, but it doesn't do anything but go to the main page.

Can this be brought back?  (Might be part of the major refactor anyway.)

**Comment by kshefchek** [comment]
Worked on this yesterday and couldn't figure it out.  The templates look right and I can't see anything in the tabs.js or monarch-common.js that could be overriding the behavior of the anchors.  Do we know around when this stopped working?

**Comment by kltm** [comment]
I'm having a little (lot) of trouble figuring out what drives the desired behaviour here--there are a lot of libraries involved. What are you using to drive this? For example, in AmiGO we have something like:

``` javascript
    // Tabify the layout if we can (may be in a non-tabby version).
    var dtabs = jQuery("#display-tabs");
    if( dtabs ){
        ll('Found tabbing, apply...');

    // Since we're a tabby version, we're going to try and open
    // any tabs defined by fragments.
    if( window && window.location && window.location.hash &&
        window.location.hash != "" && window.location.hash != "#" ){
            var fragname = window.location.hash;
        jQuery('#display-tabs a[href="' + fragname + '"]').tab('show');
    }else{
            jQuery("#display-tabs a:first").tab('show');
    }
    }
```

**Comment by kshefchek** [comment]
I can't find any js code that would acheive this in our app.  Maybe it was removed at some point?  I'll try adding your jQuery snipped to see if this fixes it.

**Comment by kshefchek** [comment]
Something like this works:

``` javascript
if ( window && window.location && window.location.hash &&
        window.location.hash != "" && window.location.hash != "#" ){
        var fragname = window.location.hash;

        $('.first.category').hide();
        $(fragname).show();

        $('.contenttab').css({'color': 'white', 'background-color': '#999', 'border-bottom': '1px solid black'});
        $('.tabcontainer a[href="' + fragname + '"]').children('.contenttab').css({'color': 'black', 'background-color': 'white', 'border-bottom': '1px solid white'}); 
    }
```

However, I'm not able to override the default scrolling of some tabs, for example, the literature tab will not open at the top of the page:
http://localhost:8080/disease/OMIM_158320#literature

**Comment by kshefchek** [comment]
Correction, so when loading a table that is longer than the window height, the page will scroll to first row of the table, but not the column headers which what I would expect. @kltm any idea how to fix this?

**Comment by kltm** [comment]
@kshefchek I think what you want to do here is a little different--the code is performing correctly as specified.

The purpose of the '#literature' fragment here is to advance the page to that point. If you use firebug or similar to highlight the divs, you can see it is doing exactly that: advancing to the div with the id "literature". Likely what you'd want then is for the "literature" id to be assigned to the tab rather than the content.

Also, the navbar is not really being helpful here, bringing the "top" down lower. It may be easier to have all fragments go to the same spot, then munge them to lift the correct tab (although that would rather break non-JS browsers).

**Comment by kshefchek** [comment]
This still works but getting content is broken with the new lazy loading, will fix.
