### ISSUE TITLE
carosel buttons don't work

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#607]
on the new front page, the things in the carousel that seem to be buttons don't have button behavior when i click (they highlight when i hover, but nothing happens when i click).  are they buttons?  are they supposed to go to the disease/gene/pheno/model landing pages?  or do they just change the carousel?  (maybe this is intended behavior?)

**Comment by kltm** [comment]
They just change the carousel. Is that not the behaviour you're getting?

**Comment by mellybelly** [comment]
So I too am confused about the carousel behavior. I keep expecting the buttons to be buttons, but instead I have to click "More", where I am actually expecting more text. 
I wonder if removing the buttons and using the dots approach, with a link on the titles, would work better? @harryhoch @nlwashington what do you think?

**Comment by kltm** [comment]
As specced, the "buttons" replaced the "current slide squares" for navigation of the carousel--they were moved from the side [Explore] section that existed earlier. If the buttons are removed, there would be no navigation between slides. They could be made to look less like buttons, with the "More >>" element (the actual navigation element) emphasized.
