### ISSUE TITLE
Improve SciGraph access layer in API

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#608]
The SciGraph code in the API could use some refactoring, action items include:
- remove foreach callbacks to translate the output in favor of adapting the API code upstream (this is trivial for vocab services, the api may need some reworking for the graph output)
- Handle 404s, in this case should we return null, or an empty list or a scigraph style object, for example, {path:[],list:[]}; @cmungall what are your thoughts here?
- Any of other functionality?  For fetchClassInfo() when fetching information about an ID do we need to handle lists of >1?  Right now we just take the top hit.

**Comment by kshefchek** [comment]
An issue I'm running into with vocab services is that we have everything built around the id and label keys for building our tables, xrefs, etc. while SciGraph returns a curie (or a fragment) and a list of labels.  Would it be best to iterate over the list of results and add an ID or update our code downstream to handle the curie/fragment keys?

**Comment by kltm** [comment]
Is there something to discuss in here with reference to high-order refactoring? At some point it would be good to turn all resource responses into sub-classable objects that have testable APIs,  easily traceable fall-through behaviour, error throwing, etc.

**Comment by kshefchek** [comment]
Short term I want to reduce some of the complexity and improve error handling.  Long term this would be part of the high-order refactoring.

**Comment by cmungall** [comment]
The curie corresponds to the id field in the monarch code.

Unique label assumption is not safe for ontologies in the wild, but for the ontologies we care about, should mostly be satisfied. Exceptions arise where we have import chains containing ontologies out of sync, or ontologies out of sync with data. Here we may have >1 label (rarely) or 0 labels.

We can't assume unique label, but we can assume that if >1 label, picking an arbitrary one is good enough.

We can't assume there is alays a label, but we need systems in place upstream to avoid this as much as possible.

**Comment by kshefchek** [comment]
There seem to be scenarios where we only get a fragment and no curie.  I want to say worm for flybase is an example I've ran into.  So theres a handful of places where I'm checking both, storing the curie as the id and if it's not available storing the fragment as the id.

**Comment by cmungall** [comment]
Should be fixed by updating SG context yaml-ld

**Comment by cmungall** [comment]
This is the file to update: https://github.com/monarch-initiative/monarch-app/blob/master/conf/monarch-curie-prefixes.yaml

@ccondit and Larry will coordinate to have the bamboo jobs that deploy SG use this

**Comment by ccondit** [comment]
All environments have been configured to use this URL and geoffrey is now deployed with this change. Note that if the contents of the URL change the environments will need to be redeployed to see the updates.

**Comment by nlwashington** [comment]
there were many prefixes in the monarch-context file that seem to not be in the monarch-curie-prefixes file.  did you mean to strip away many of them?  for example, the various FB ontology prefixes aren't ported.

so now there is monarch-context, monarch-curie-prefixes, and monarch-prefixes in the conf/.  @cmungall  can you document what the differences are in the files, and where we should add new curies?

**Comment by cmungall** [comment]
There was no intentional stripping, the curies file just happened to have a different history.

We discussed the possibility of using the full context file in SciGraph but that complicates things for now, so we need some semi-automatic procedure for syncing the two, leaving open til this is done, in the interim we have to manually sync

**Comment by kshefchek** [comment]
At this point I've made the changes suggested by @cmungall during my visit in Dec, will close for now and open a new ticket for improvements via subclassing and testing.
