### ISSUE TITLE
Analyze Phenotype Search not displaying results

### ISSUE THREAD

**Issue by VincentIII** [monarch-initiative/monarch-legacy#609]
If I try to search something on Analyze Phenotype, the auto complete does not show the labels of the results, but seems to populate with an accurate number of possible results.  When clicking any of these blanks, nothing is populated below.
![bug1](https://cloud.githubusercontent.com/assets/800672/5287299/05811136-7af9-11e4-93e9-6f9f3d9beeae.png)

**Comment by kshefchek** [comment]
Looks like I broke this.  The analyze page was expecting "id" and "term" as keys.  This from our old ontology service Ontoquest.  I recently updated our API to directly handle the output from SciGraph, although we're still modifying the direct json output to add id and label keys.

I've updated Analyze.js to get the label key.  This should be working now,

**Comment by VincentIII** [comment]
Looks like I get results now, but it seems there is a lot of duplicates.  Not sure if related or separate issue

**Comment by kshefchek** [comment]
This should be fixed now, let me know if you still see duplicates.
