### ISSUE TITLE
Search bar on pages shifting results to the left

### ISSUE THREAD

**Issue by VincentIII** [monarch-initiative/monarch-legacy#610]
When searching on any page other than the index, the results are displayed heavily shifted to the left and cut off by the browser's frame, making it very difficult to view.  When selecting a result, it works and directs you to the correct page however.  The search on the front page works fine.

![bug2](https://cloud.githubusercontent.com/assets/800672/5287325/336d7fa8-7af9-11e4-8339-562ecf009b12.png)

**Comment by kshefchek** [comment]
Was this related to #621? Or an issue with mobile screens?  I do notice this using my phone and wonder if we need to either dynmically decrease the font size or add an ellipse for long names.

**Comment by VincentIII** [comment]
Looks like on Chrome it was fixed with the #621 fix.  When looking on it on Chrome Mobile it auto-adjusts to screen size and I'm not getting cut-off anymore
