### ISSUE TITLE
phenogrid missing from NCBIGene:20273

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#612]
i don't see the phenogrid on 
http://stage-monarch.monarchinitiative.org/gene/NCBIGene:20273

**Comment by kshefchek** [comment]
This is the error output:
TypeError: this.state.data[species].metadata is undefined
phenogrid.js (line 1096, col 6)

**Comment by nlwashington** [comment]
similarly, missing from genotype pages:
http://stage-monarch.monarchinitiative.org/genotype/MGI:3716845

**Comment by VincentIII** [comment]
Do we know of any genes where it does work?  And it looks like genotype "works" as of one of the recent updates, just looks a bit off

![screenshot from 2014-12-05 10 05 22](https://cloud.githubusercontent.com/assets/800672/5317624/5d7e60c8-7c66-11e4-99e3-6f0524b89c0e.png)

**Comment by VincentIII** [comment]
Fixed with https://github.com/monarch-initiative/monarch-app/commit/98c3a6906e9c4d3d81da8eab9242e8319f22d255
