### ISSUE TITLE
fly publications not pubmed

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#615]
i notice here:
http://stage-monarch.monarchinitiative.org/gene/NCBIGene:39958

that the fly publications are the internal identifiers, and not pmids.  this needs fixing upstream.

**Comment by bryanlaraway** [comment]
Just about have this fixed, but not all Flybase internal publication IDs have associated pmids. Do we just want pmids, or do we want to preferentially bring in any other reference sources, such as PubMed Central or DOI?

**Comment by selewis** [comment]
FlyBase practice is to create internal publication IDs for all abstracts at
the annual Drosophila Conference, for selected personal communications, for
some truly ancient information, and similar exceptional cases. It would be
a shame to lose these chains of evidence that will never have PubMed IDs.

-S

**Comment by bryanlaraway** [comment]
NLW: This looks ready to go. You might take a peek before hitting the beta deployment review approval in DISCO.

selewis: I have a preference order for this field set to pull in Pubmed ID > PubmedCentral ID > DOI > ISBN > Flybase Internal Publication ID, so a publication ID should always be captured for that field. I'm not sure that it would work for the intentions of this particular publication_id field, but I could certainly see about creating an additional field that aggregates all of the publication identifiers, and perhaps any descriptive text that might capture those other information types.

**Comment by nlwashington** [comment]
@bryanlaraway can you link the remaining FBpubInternal identifiers to FBrf's?  For example:
http://flybase.org/reports/FBrf0174570.html

**Comment by bryanlaraway** [comment]
@nlwashington Deploying the fix for the Flybase Phenotypes publication_id column now. Going with order of preference: PMID > PMCID > DOI > ISBN > FB:FBrf > FBpubInternal > null. Not sure how many of these will actually pull in the FBrf types, as many of those may already have publication IDs that show up sooner in the preference order. Also, not all of these phenotypes map to the IDs I've selected here other than the internal publication identifiers, so I'm leaving in the FBpubInternal as a final option.

**Comment by jmcmurry** [comment]
Looking at beta.monarchinitiative.org/gene/NCBIGene:39958, I don't see any references listed at all.
![screen shot 2015-10-08 at 10 55 16](https://cloud.githubusercontent.com/assets/3658863/10375033/283bf038-6dab-11e5-8c03-ae15ac217416.png)
This makes me wonder whether it is a regression or whether it was never addressed at all?

**Comment by cmungall** [comment]
This appears to be fixed:

![image](https://cloud.githubusercontent.com/assets/50745/21120367/bdb98048-c07b-11e6-8d73-286a1fae4da4.png)

PMIDs where they exist, FBrfs for suppl. material etc.
