### ISSUE TITLE
Add ability to query by ID in Analyze phenotypes search

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#623]
(reassign as needed)

One should have the ability to paste in a set of phenotype terms, either by label or by ID into the interface.

**Comment by harryhoch** [comment]
@VincentIII, can you take a look? This should be relatively straightforward with a bit of pre-processing on the input side

**Comment by nlwashington** [comment]
Duplicates #269.

**Comment by nlwashington** [comment]
I think we will need this kind of behavior for the AMIA demo.

**Comment by mellybelly** [comment]
same as #269
