### ISSUE TITLE
Replace hardcoded getConf() payload with js compiled from yaml

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#629]
Current GolrScratch has a hardcoded list for getConf() - replace this with js that comes from yaml in conf/golr-views

@kltm will add to Makefile for compilation step

**Comment by kltm** [comment]
@cmungall or @kshefchek the script has been added, but it looks like there is no metadata directory to operate on:

``` bash
./scripts/confyaml2json.pl -h
```

**Comment by kltm** [comment]
All the ducks should be in a row now; assuming that you have your OWLTOOLS_BIN environmental variable correctly defined:

``` bash
make reconfigure-golr
cat ./conf/schema.xml
cat ./conf/golr-conf.json
```
