### ISSUE TITLE
ping service for monarch-app and owlsim?

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#630]
for testing of connectivity and availability, it would be great to have a simple "ping" service for both monarch-app and owlsim.....get /ping with a response like "ok" would suffice...

**Comment by kltm** [comment]
We've started implementing something like this for GO services:

http://go-genkisugi.rhcloud.com/status
http://barista.berkeleybop.org/status

with @cmungall  we were working on a format to make detection, aggregation, and internal analytics reporting easy. I could add this to monarch-app and we could then maybe share the downstream tools.

**Comment by harryhoch** [comment]
yes, please.

**Comment by cmungall** [comment]
For the owlsim server, coordinate with @ccondit who wrote the dropwizard/jersey layer https://github.com/SciCrunch/SciGraph/tree/master/SciGraph-core

**Comment by ccondit** [comment]
I don't think the owlsim v3 services are running anywhere yet. Once they are there are a host of options to monitor them available with dropwizard (these are for SciGraph):
http://geoffrey.crbs.ucsd.edu:9001/ping
http://geoffrey.crbs.ucsd.edu:9001/healthcheck
http://geoffrey.crbs.ucsd.edu:9001/metrics?pretty=true

**Comment by kltm** [comment]
I've added a petty /status route and backed it with a few trivial stats.
