### ISSUE TITLE
limit analyze phenotypes to phenotypes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#632]
I think we should remove diseases from the autocomplete and just have phenotypes on the Analyze Phenotypes page (for now).

**Comment by harryhoch** [comment]
@kshefchek , let me know if you need me to change the analyze page to a new call to make this happen.

**Comment by kshefchek** [comment]
This is fixed now.  The analyze page correctly calls /autocomplete/Phenotype, I just had to update the scigraph function in the API so that /autocomplete/{category} pages work.

**Comment by harryhoch** [comment]
great, Kent. thanks.
