### ISSUE TITLE
Create new scratch view of ZFIN genotype-phenotype and gene-phenotype associations

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#633]
@nlwashington has created the triples from source using https://github.com/monarch-initiative/dipper/blob/master/sources/ZFIN.py - for now this has to be executed manually but we'll have something like a jenkins job running soon. 

@ccondit will take the SciGraph triples that come from this and produce a json/solr that conforms to views in https://github.com/monarch-initiative/monarch-app/tree/master/conf/golr-views by adding code here: 
https://github.com/SciCrunch/SciGraph/tree/master/SciGraph-dump/src/main/groovy

@kshefchek will add new scratch pages/tabs. I think we will want a few different ones.
- On the existing phenotype page, a gene tab and a genotypes tab
- A new scratch gene or genotype page, with a phenotypes tab

Sorry if it seems a bit convoluted with different repos at the moment, we'll make this more streamlined later.

**Comment by kshefchek** [comment]
Zebrafish pages should be working see:
http://beta.monarchinitiative.org/gene/NCBIGene:30444
http://beta.monarchinitiative.org/phenotype/ZP:0002780
