### ISSUE TITLE
Pages contain bad links

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#634]
This is an update of #448.

These links are off:

```
Reference: http://monarchinitiative.org/page/releases
URL: http://wwww.flybase.org

Reference: http://monarchinitiative.org/page/about
URL: http://www.diseaseontology.org

Reference: http://monarchinitiative.org/page/about
URL: http://human-phenotype-onotology.org
```

There also seems to be an issue with URLs like this (example from http://monarchinitiative.org/gene/NCBIGene:100000160):

 http://monarchinitiative.org/variant/MONARCH:ZDB-MRPHLNO-080626-5_10_mg_ml_ZDB-GENE-980526-488

These URLs seem to rewrite and resolve to something with a non-legal schema. An example using wget:

```
/tmp$:) wget http://monarchinitiative.org/variant/MONARCH:ZDB-MRPHLNO-130911-3__ZDB-GENE-030323-1--2014-12-22 21:41:36--
http://monarchinitiative.org/variant/MONARCH:ZDB-MRPHLNO-130911-3__ZDB-GENE-030323-1
Resolving monarchinitiative.org (monarchinitiative.org)... 198.202.94.117
Connecting to monarchinitiative.org
(monarchinitiative.org)|198.202.94.117|:80... connected.
HTTP request sent, awaiting response... 303 See Other
Location: MONARCH:ZDB-MRPHLNO-130911-3__ZDB-GENE-030323-1 [following]
MONARCH:ZDB-MRPHLNO-130911-3__ZDB-GENE-030323-1: Unsupported scheme
‘MONARCH’.
```

It looks like a URL is being transformed into just the final bit of the path, so the final namespace looks like a URL scheme to the client.

Examples of other errors (single example per general URL):

 <strike>Reference: http://monarchinitiative.org/phenotype/HP:0000218</strike>
 <strike>URL: http://monarchinitiative.org/phenotype/MP_0003757</strike>

```
Reference: http://monarchinitiative.org/phenotype/HP:0000303
URL: http://monarchinitiative.org/disease/KEGG:ds-H00523

Original: http://monarchinitiative.org/gene/ZFIN:ZDB-GENE-030323-1
Reference: http://monarchinitiative.org/gene/NCBIGene:352940
URL: http://monarchinitiative.org/gene/NCBIGene:100330721

Reference: http://monarchinitiative.org/phenotype/MP_0001286
URL: http://monarchinitiative.org/disease/ORPHANET:220497

Reference: http://monarchinitiative.org/gene/NCBIGene:387733
URL: http://www.ncbi.nlm.nih.gov/sites/entrez?cmd=Retrieve&db=gene&list_uids=401461790

Reference: http://monarchinitiative.org/phenotype/HP:0001250
URL: http://monarchinitiative.org/phenotype/HP:0007359

Reference: http://monarchinitiative.org/model/
URL: http://monarchinitiative.org/gene/ZFIN:ZDB-GENE-041014-322

Reference: http://monarchinitiative.org/model
URL: http://monarchinitiative.org/phenotype/MP:0000159

Reference: http://monarchinitiative.org/page/pubs
URL: http://genomebiology.com/2014/15/9/423

Reference: http://monarchinitiative.org/gene/NCBIGene:245699
URL: http://vega.sanger.ac.uk/perl/searchview?idx=All&q=OTTDARG00000019936&species=all

Original: http://monarchinitiative.org/gene/ZFIN:ZDB-GENE-030323-1
Reference: http://monarchinitiative.org/gene/NCBIGene:352940
URL: http://monarchinitiative.org/phenotype/ZP:0000458
```

**Comment by kltm** [comment]
Poking everybody who was on the other bug: @mellybelly @nlwashington @cmungall

**Comment by cmungall** [comment]
This one is an example of a prevalent pattern and should be addressed:

```
Reference: http://monarchinitiative.org/phenotype/HP:0000218
URL: http://monarchinitiative.org/phenotype/MP_0003757
```

This must have been broken in the switch from OQ->SG. The code used to liberal in whether it accepted fragments or CURIES, it would always translate the to the appropriate form for whatever downstream query is required

**Comment by cmungall** [comment]
I retract my last comment, both forms work. It only appeared one form wasn't working because we're getting upstream issues from production federation services:
https://support.crbs.ucsd.edu/browse/NIF-13590

Seth, this will be adding noise to the tanuki report I'm afraid

**Comment by kshefchek** [comment]
/phenotype/MP_0003757 works for me locally and on production, is there another example that is failing?

**Comment by kshefchek** [comment]
@kltm I ran tanuki yesterday and didn't see these, but I did receive many of the schema errors on various threads.  Is there a way to get this information back when theres a schema error?

**Comment by kltm** [comment]
@kshefchek That nasty business with the transformation into the "monarch" URL schema prevented tanuki at my end from making any real progress on internal links; I pushed a fix a little bit ago for kappa (the agent that tanuki uses) to accept the bad schema as an error. (I also added a new reporting flag to minimize the output to make pasting into the tracker easier.)

**Comment by kltm** [comment]
@kshefchek the full error for that one is:

```
Generic ID: 3999
Argument set ID: 2348
Page ID: 2166
Date: 20141223144417
Processing time: 129
Code: 500
Success: 1
Flagged: 1
Reference: http://monarchinitiative.org/phenotype/HP:0000218
URL: http://monarchinitiative.org/phenotype/MP_0003757
```

Long wait time and then 500--as Chris mentioned, that was probably upstream. I re-ran all errors, from last night this morning, so it was down for something like twelve hours. It does seem fine now however. I'll strike it.

**Comment by mellybelly** [comment]
@kltm can this be closed now?

**Comment by kltm** [comment]
@mellybelly I would suggest rerunning the spider. Is there a final updated URL to test against?

**Comment by kshefchek** [comment]
Maybe we could make a ticket for each release to run tanuki and assign to me or @kltm.  I think the above issues have been resolved.
