### ISSUE TITLE
MGI source link is broken

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#635]
for example, this one: http://monarchinitiative.org/model/MGI:3759227
when you click on the source MGI link, you end up on a page at MGI that says "No accession id found. Please verify that your request contains an id parameter."

Seems to be the case for others I have looked at as well.
Is this a problem with the genotype vs. allele display issue at MGI?

**Comment by nlwashington** [comment]
ah, i guess you can’t access the genotypes via a general “accession” number.

the genotype links for MGI will need to be changed to this format: 

http://www.informatics.jax.org/allele/genoview/MGI:3759227
