### ISSUE TITLE
Link to Monarch Initiative on github org page is wrong

### ISSUE THREAD

**Issue by Relequestual** [monarch-initiative/monarch-legacy#637]
Hi Team,

The link to your site your github org page has a typo

https://github.com/monarch-initiative
Link is just under the orgs name, missing a "t" so results in failed page load.

**Comment by harryhoch** [comment]
fixed. thanks for pointing this out.

**Comment by Relequestual** [comment]
You're Welcome Harry. Sounds like we may be working together at some point in the not too distant future =]

**Comment by harryhoch** [comment]
Great. Happy to have your input...
