### ISSUE TITLE
Bring antibody model into import chain

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#639]
We will need some preliminary implementation of the REO antibody model to use in SciGraph/Dipper to bring in some antibody data.

**Comment by jgrethe** [comment]
Should we review the model during one of our standard call times?

**Comment by mellybelly** [comment]
sure that would be great, probably the monday afternoon ontology slot?

**Comment by mellybelly** [comment]
closing this as moving to dipper issue tracker https://github.com/monarch-initiative/dipper/issues/31

**Comment by mellybelly** [comment]
closing as replaced by https://github.com/monarch-initiative/dipper/issues/31

**Comment by jgrethe** [comment]
The ontology slot would probably be best - however next Monday is a holiday
