### ISSUE TITLE
Manage transition to new version of SciGraph API

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#642]
The SG API is likely to change see https://github.com/SciCrunch/SciGraph/issues/55 cc @ccondit 

We use using /neighbors in Monarch, possibly suboptimally. We should switch, but this has to be carefully synchronized across dev and production.

Suggest we tackle when I'm back on the 22nd Jan

**Comment by twhetzel** [comment]
Also needs to be synchronized with projects using the SciCrunch web framework (Resource Identification Portal, dkNET, etc.) since this platform is also moving to use the SciGraph API  cc @debanks

**Comment by mellybelly** [comment]
@kshefchek I think this is finished for this release?
