### ISSUE TITLE
myocolonus equiv missing

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#645]
http://localhost:8080/phenotype/HP:0001336
used to be displayed as equivalent to 
http://localhost:8080/phenotype/MP:0000243

but this display seems gone now.  in fact, any hierarchy seems gone.

note that DO i observe diseases related to the mouse term on the mouse term page, and mouse genes on the human page.

note that these pages do not redirect to one or the other.  @cmungall is this an ontology issue?  i can't seem to find the equivalences with services on kato.

**Comment by cmungall** [comment]
I don't think it's an ontology problem. The axiom is there in the ontology. @kshefchek can you point me at the relevant part of the code and I can see if I can work out a test case for SciGraph

**Comment by kshefchek** [comment]
I think there was a change made to the structure of the json output:
http://kato.crbs.ucsd.edu:9000/scigraph/graph/neighbors/HP:0001336.json?depth=1&blankNodes=false&callback=fn

http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/HP:0001336.json?depth=1&blankNodes=false&direction=both

Will update the app the handle the new output.  @cmungal this is fetched in fetchClassInfo()

**Comment by kshefchek** [comment]
I've updated the api to handle the new scigraph format.  However, I'm still making a new array rather than using the Scigraph object directly.  The issue here is having labels and ids in two separate arrays, we need to either merge the two or perform a look up when generating the html.
