### ISSUE TITLE
No phenotypes for coronary heart disease

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#65]
does it seem right that there's no phenotypes for coronary heart disease?

http://tartini.crbs.ucsd.edu/disease/DOID_3393

if that is the case, then we need to remove it from the "highlighted diseases", because it doesn't highlight anything.

**Comment by cmungall** [comment]
I included it in the highlighted diseases for this reason.

What do we do about non-genetic diseases? Seems safest to remove them altogether for this release (in which case OrphaNet would have made more sense as our disease ontology).

Alternately we could do a push to get genes in for these, e.g. from GWAS, the GeneRIF-mined associations provided by DO... A bit risky now I think.

**Comment by nlwashington** [comment]
Yeah, I imagine we'll get annotations to these from GWAS and ClinVar.  Probably for the next release, but let's leave this open.

**Comment by cmungall** [comment]
Text could do with some massaging...

![screen shot 2014-01-28 at 5 01 27 pm](https://f.cloud.github.com/assets/50745/2025684/f9eff2a8-8880-11e3-8217-4865c63f70ed.png)

**Comment by mellybelly** [comment]
Should we hide these for now? or at least remove from highlighted diseases?
(text above looks good, though, if decide to keep).

**Comment by cmungall** [comment]
What do you mean by hide?

We should definitely remove from highlighted

**Comment by cmungall** [comment]
Fixed in refactored pages
