### ISSUE TITLE
Add gene-to-genotype REST call in monarch-app

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#650]
Proposed:

```
/query/gene-to-genotype/:id.json
```

and/or

```
/query/genes-to-genotype/:idlist.json
```

For the latter we should probably use POST

**Comment by kltm** [comment]
To clarify, in this case you mean POST in the sense that you wouldn't have a list in the URL, but rather a more API-like call?

**Comment by nlwashington** [comment]
this is as good of a time as any to keep the GA4GH schemas in mind; we should try to be compliant with them in these cases.  (keep in mind, however, i don't see any query methods in the current schemas that allow you to query for variants of a specific gene....the closest i see is SearchVariantsRequest, but it expects coordinates, not identifiers.

**Comment by selewis** [comment]
We can (and should) also drive the GA4GH schemas ourselves. As near as I
can see all it takes is stepping forward to make it happen with them. No
need to wait for any permission.

-S

**Comment by nlwashington** [comment]
@harryhoch please comment on exactly what you would like us to deliver when wrapping the scigraph/rosie query.  if you want a list of genotypes linked to a gene with no explanation of how we arrived at them, then we can deliver a json list by processing the graph delivered from scigraph.

**Comment by harryhoch** [comment]
@nlwashington, I think it would be ideal to have  the option of either getting the whole mess as is, or getting it filtered down to just the genotypes with no explanation. This could be two separate calls, or perhaps an optional flag for the filtered case?

**Comment by nlwashington** [comment]
ok, after losts of discussion today with @cmungall and @ccondit , we're going to serve this up at this url:

http://tartini.crbs.ucsd.edu/dynamic/gene/MGI:98297/genotype/nodes.json

generally, monarch-app will simply wrap the scigraph services directly.  we're in a bit of transition of scigraph right now, and the actual service for this particular function is named differently, so i've written a wrapper around it in our webapp layer.  this service does not handle a list of genes yet.  you will need to iterate.  although the results aren't exactly right from this call today (you get a list of genotypes and alleles), for development purposes please assume that it is right.  but hopefully you can code to this service call and it will be fairly stable.  the last part, "/nodes" will get you just the end result of the query, without the graph structure.

**Comment by mellybelly** [comment]
assigning to @ccondit but please reassign or close if you like

**Comment by nlwashington** [comment]
this is now accessible by wrapping rosie, simply replace the url domain with the local monarch configuration (tartini.crbs.ucsd.edu or monarchinitiative.org).
like this:
http://whatever.domain.you.want/scigraph/dynamic/genes/NCBIGene:14183/genotypes/targets.json
on your localhost, it is:
http://localhost:8080/scigraph/dynamic/genes/NCBIGene:14183/genotypes/targets.json

if you want just the list of genotypes, you add the "/targets.json" as above.

if you want the "whole mess" with the graph, you leave off the "/targets".  there are several options that you can get; the bbop.json format is the default; but you can also get graphson, xml, gml, etc.

**Comment by davism84** [comment]
@nlwashington I'm getting a proxy error with the link below.  

http://tartini.crbs.ucsd.edu/scigraph/dynamic/genes/NCBIGene:14183/genotypes/targets.json

However, if I substitute a localhost call it will return results, but takes over a minute to return the results.
http://localhost:8080/scigraph/dynamic/genes/NCBIGene:14183/genotypes/targets.json

I also noticed that when I do a compare call 

http://localhost:8080/compare/HP_0001251+HP_0002074+HP_0001300+HP_0001336/MGI:5560741+MGI:5560742

it’s now failing on these calls

Status: 404
http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/MGI:5560741+MGI:5560742.json
