### ISSUE TITLE
Add info about NIF Annotate services to doc page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#651]
We should put a link or doc about the annotate API on the monarch page so users can programmatically access with our import chain:
http://monarchinitiative.org/annotate/text

**Comment by kshefchek** [comment]
Moving milestone to this release, @mellybelly can you provide more detail about what we want here?

**Comment by jmcmurry** [comment]
@mellybelly, this tool is cool, but what do you mean about "programmatically access with our import chain"?

**Comment by mellybelly** [comment]
Essentially what we'd like to be able to provide is for programmatic users to access our text annotation services using any portions of our import chain that they specify. @tudorgroza may wish update our services at some point, but for now probably just need some documentation.

**Comment by cmungall** [comment]
I think what you're asking for is a link to here: http://datagraph.monarchinitiative.org/docs/#!/annotations/getEntities

There is currently no way to restrict the annotator to any portion of the import chain, but this would be the wrong level of abstraction for most users, who know nothing and should know nothing about our owl:imports graph. You can currently restrict by categories (need docs here on what categories are in monarch). And if you are capable of using the API you're capable of doing any kind of post-filtering on it.

**Comment by mellybelly** [comment]
ok so just need to update doc and call er good then?
