### ISSUE TITLE
HPO codes are shown with encoded colons

### ISSUE THREAD

**Issue by Relequestual** [monarch-initiative/monarch-legacy#654]
When doing a Phenotype Profile Analysis query, the phenotypes added show the code, but the code has the colon encoded. This is on the query view and the table view.
![screen shot 2015-02-12 at 16 01 28](https://cloud.githubusercontent.com/assets/731158/6171074/ae7fb8fa-b2d0-11e4-8f19-82ad4a44fb63.png)
![screen shot 2015-02-12 at 16 01 40](https://cloud.githubusercontent.com/assets/731158/6171073/ae7f638c-b2d0-11e4-81e8-7cde163f7633.png)

**Comment by Relequestual** [comment]
Found another instance of this. http://monarchinitiative.org/analyze/phenotypes/
Add a phenotype, then search. The resulting page has the same encoded colon.

**Comment by kshefchek** [comment]
It's only fixed on our beta site, we could reopen until our next release if that makes sense.

**Comment by Relequestual** [comment]
Oh right! I'd probably add it to a milestone personally, but I don't know if that would fit with your workflow.

**Comment by cmungall** [comment]
+1

**Comment by Relequestual** [comment]
Sorted!
