### ISSUE TITLE
Add registry of identifier prefixes

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#656]
It would be great if Monarch could have a list of recommended prefixes somewhere available on the site. 
This could be made available on the Monarch "data sources page" http://monarchinitiative.org/sources
Which it sort of is now in the right hand column but not explicitly.

This is also something that would be handy on the SciGraph Documentation page for querying or folks using services.

@nlwashington may also have thoughts. 
Just tired of seeing a lot of variation in the prefixes and maybe we can make it a little better if we just start exposing how we do things wrt to identifiers.

**Comment by ghost** [comment]
[JIRA comment](https://support.crbs.ucsd.edu/browse/NIF-14219?focusedCommentId=134552&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-134552)

**Comment by nlwashington** [comment]
well, there's a couple of places these should come from:
we have a curie-prefix mapping that expands to the full IRI.  that is good.

the other is the xrefs file that we've leveraged from GO, (originally xrefs.abbr, which we now keep as xrefs.json).  this is what we use to create the external links on our website, and includes the prefixes of many ids (more than we use).

@cmungall i believe there is a new place that these are being maintained by GO?

**Comment by kltm** [comment]
Upstream:
 https://github.com/geneontology/go-site/blob/master/metadata/db-xrefs.yaml
Consumable:
 http://build.berkeleybop.org/view/GO/job/db-xrefs-yaml2json/
as well as the other db-xrefs-\* jobs.

**Comment by cmungall** [comment]
Ticket of relevance: https://github.com/geneontology/go-site/issues/47

As Nicole mentions, there's two different use cases here: how to expand a CURIE/id to a URI that uniquely identifiers a thing within the uber triple graph store, and how to expand a CURIE/id to a URL where we want to send humans. In the ideal semweb world these would be the same thing but they're not and there is a whole world of ideological war we don't want to get into here.

**Comment by mellybelly** [comment]
Could automate this from SciGraph.

**Comment by jmcmurry** [comment]
"In the ideal semweb world [CURIE-->http URI and CURIE-->URL] would be the same thing but they're not and there is a whole world of ideological war we don't want to get into here." - @cmungall 

Wholeheartedly agreed. In the meantime, to move this ticket forward a little bit, I've added some basic identifier documentation here: https://github.com/monarch-initiative/dipper#identifiers. It does not get into the subtlety between the URL/URI scenarios above. In fact, _I'm_ not even clear on whether the resolving namespaces in that map correspond to A) all URLs, B) all URIs, or C) some mix of the two. Perhaps the map should be explicit in this regard? 

IMHO, when we hyperlink CURIEs from our interface, they should lead to human readable pages, or at least be resolvable. Hyperlinks that don't resolve are frustrating to humans. Feedback welcome.

**Comment by jmcmurry** [comment]
I think this has been overtaken by events, is well addressed by ID21C and the existing identifiers documentation. Closing.
