### ISSUE TITLE
production test suite failing

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#657]
http://build.berkeleybop.org/view/Monarch/job/check-monarch-production-urls

```
undefinedTypeError: Cannot call method "forEach" of undefined
   at ScriptRuntime.java:3691
   at ScriptRuntime.java:3669
   at ScriptRuntime.java:3697
   at ScriptRuntime.java:3716
   at ScriptRuntime.java:3735
   at ScriptRuntime.java:2258
   at ScriptRuntime.java:2251
   at lib/monarch/api.js:5692
```

@kshefchek is this to do with the differences between production and dev for the SG service calls?

**Comment by kshefchek** [comment]
That would be my guess, what would be the best way to resolve?  Push beta scigraph to kato?

**Comment by kshefchek** [comment]
Consensus was to disable this test until next release given that pushing beta scigraph to kato will break the production site, but this test runs on the beta version of the API.
