### ISSUE TITLE
Fix getAnnotationSufficiencyScoreFromAssociations() in fetchGeneInfo()

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#661]
Currently throws "Cannot call method "decodeToString" of undefined"  Appears to be related to calling owlsim/getAttributeInformationProfile.

**Comment by kshefchek** [comment]
Everything appears to be defined, I think this is an issue with sending too many IDs to owlsim.  @nlwashington @cmungall Should we set a limit to the number of phenotypes we use to generate the annotation sufficiency score?

**Comment by nlwashington** [comment]
might need to change to a post instead of a get?  (or was that done already?)

**Comment by kshefchek** [comment]
Looks like it is already a post.

**Comment by kshefchek** [comment]
No longer relevant, please reopen if we're still using this function somewhere.
