### ISSUE TITLE
Explain how the analyze/phenotypes page works

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#662]
This page:
http://tartini.crbs.ucsd.edu/analyze/phenotypes/

Doesn't really explain what it's for, how to use it, or how to interpret the results.  We need some documentation (perhaps at the top, or in a column) on this page that guides the user through the workflow.

**Comment by jmcmurry** [comment]
I believe that this has now been addressed; please reopen if not.
