### ISSUE TITLE
autocomplete for non-human genes in advanced gene search

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#663]
On our nascent analyze genes page could potentially have a organism selector that would allow users to choose the gene file on which to autocomplete, allowing them to go straight to their favorite model organism specific gene. For example, we can autocomplete on human SHH but not zebrafish shhb. 
@nlwashington may have other ideas.

**Comment by kshefchek** [comment]
This was fixed at some point, some @ccondit and @nlwashington magic.
