### ISSUE TITLE
Develop and implement module strategy

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#665]
Phenogrid and presumably other widgets will be part of monarch-app, but will also be used as standalone components by third parties.   As a result, inclusion of the phenogrid code in the monarch-app repository is non-optimal. 

We need a strategy for including components like phenogrid  "by reference". Monarch-app should simply get the required code when needed.  Possible approaches for managing this include:
1. ad-hoc scripts: already implemented for phenogrid. Advantages - flexibility. Disadvantages - may not play well with some environments. These scripts posed a problem for deployment on tartini.
2. Git submodules  - http://www.git-scm.com/book/en/v2/Git-Tools-Submodules. Pros - integrate well with the git ecosystem. Cons - I personally have not used them. Some comments on the web hint at possible challenges.
3. npm/bower, or other configuration manager -. Pros - widely used. Cons - more focused on node.js so not directly applicable. 

Thoughts? Other alternatives?

**Comment by kltm** [comment]
I think 3 is hands down the best here. While there can be some looking at what the best combination is, if you want dependency management by version, tools along those lines will be needed.

It should be noted that there is a lot of talk and some action on the part of the npm people to make it a more general JS and resource handling tool.

**Comment by nlwashington** [comment]
@jnguyenx had some ideas about this today.

**Comment by kltm** [comment]
As a note, monarch app is already using:
- undercore
- bbop-js
- mustache
- pup-tent
- phenogrid
  - any sub-dependencies there
- ??? (feel free to fill in)

In the future, when converting over to things like Sass, getting together compressed bundles for resources, etc., you'll want to have access to a better tool chain as well.

**Comment by jnguyenx** [comment]
Another solution is to expose the Phenogrid through a CDN and have versioned distributions. For example one would import the necessary Phenogrid js and css (eg. http://phenogrid.org/1.2.1/phenogrid.js, http://phenogrid.org/1.2.1/phenogrid.css, etc...).

A dev versioned can be delivered continuously to http://phenogrid.org/DEV/... so the monarch app would benefit from the bleeding edge changes through this special version.

Last, if one wants to follow the latest production version with the risk to get something non-backward compatible, we can add a symlink pointing to the latest distribution and the URL would be http://phenogrid.org/PRO/...

Pros
- Very easy for someone new to import the phenogrid into his project, without having to use bower & co.
- One source of truth.
- Easy to put in place through scripts.

Cons
- What's happening in case of heavy traffic?

**Comment by kltm** [comment]
@jnguyenx I think CDNs can be a good distribution method in some cases, but somewhat orthogonal to module handling, dependencies, and development.

For example, are you bundling all of the required modules for phenogrid with it, and how do you keep track of version collisions and upgrades? If other pieces of JS need to interact with specific versions of Phenogrid in specific ways, and different versions of monarch-app have different requirements, I think what you end up with starts looking like npm (or similar) anyways.

**Comment by jnguyenx** [comment]
You should definitely not embed your dependencies in the bundle, that's the best way to get conflicts.

Popular frameworks offer the following distributions type: (ie: angularjs, facebook react, etc..)
- zip
- CDN
- npm
- bower

They must have a simlpe way to deliver to all these platforms with a single command, maybe with Grunt? We'll need to inspect their github repos to see that.

Anyhow I find CDN very handy for fast prototyping, but larger applications certainly need a proper dependency management system.

**Comment by nlwashington** [comment]
ok, @harryhoch what is the status of this?  it is very confusing for outside developers to know what code base to contribute to...  do they make pull requests against @monarch-initiative/phenogrid ? or @monarch-initiative/monarch-app's version of the grid.  we can't keep maintaining two repositories...it's confusing.

**Comment by kshefchek** [comment]
+1
If we can't use npm then it seems Grunt or Gulp are the next best options.

**Comment by harryhoch** [comment]
@nlwashington thanks for raising this timely issue. I just got a phenogrid pull request earlier today (our first), so I think this questions does merit some serious consideration.

I'd like to step back to consider this from first principles.  Requirements:
1.  A configuration management system that allows us to assemble the components of monarch-app from various homes without duplicating code in the monarch-app repository.
2. Each component should be retrievable from a well-defined spot  (github, npm, etc.)
3. Some form of semantic versioning should be enforced.
4. Components should be pulled in and managed in a manner that allows for comprehensibility and clarity -ie, we know which things are there, and why they are there.
5.  The proliferation of jquery\* file should be handled and clarified.
6. Ideally, we would have a single component that would install/build/run in an ant/maven-like model.

That's my starting point. Please feel free to elaborate - I'm sure I've missed something.

now, I've looked at npm, and it seems to be a bit  painful in terms of wanting to always stick things in a common spot. Not ideal. 

Grunt/gulp are similar - I think gulp is the current favorite. Mostly described as "maven for javascript". I took a look at this and didn't get very far - I think @kltm had some ideas, but I didn't quite understand what he had in mind - see https://github.com/monarch-initiative/monarch-app/issues/597 for discussion. There was some mention of possible code, but I haven't seen it. 

@kltm, any further thoughts? 

I certainly agree that this should be a priority.

**Comment by kltm** [comment]
Yes, strong opinions here. npm + gulp (+ browserify, etc.) is the way to go. npm handles the project dependencies from a package.json, browserify via gulp assembles the runtime for the browser and gives a unified programming environment on both the client and server. It's bliss. If it's necessary for this release a few people can sit down and work this out in a day or an afternoon (depending on how much people now about the system interrelations).

**Comment by harryhoch** [comment]
@kltm, no problem with those tools, I just haven't grokked the zen of how to get to that point. Can you point to an example?

Is it important for the release? I don't know. 
I'm happy  to help with this, but getting my time for a full day or afternoon is not likely to happen any time soon.  Can we do it asynchronously? @davism84, can you help out?

**Comment by kltm** [comment]
@harryhoch 
Okay, I pushed ahead on some stuff for noctua I was putting off (geneontology/noctua#119, including progress list), and while I haven't gotten it all to where I want it to be, it is sufficiently along  it can be used as an example for monarch-app. Also, interestingly, the setup has no problem using both the old and the new code deployment strategies at the same time (thanks pup-tent!), so it would be possible to do this more piecemeal than I initially thought.

How about we can go over it together sometime next week with anybody interested in the conversion? Or, if this is a lower priority (release coming), I can finish up all my edge cases and we can do this at our leisure later on.

**Comment by kltm** [comment]
Lost @cmungall off the issue transferring over here.

**Comment by harryhoch** [comment]
@kltm, thanks. This sounds pretty good. I'm guessing that  < 1 hour with you explaining the model should be sufficient to put this together for monarch-app.

@nlwashington, @davism84, what do you think about priority?  It seems to me that getting this right could make a substantial difference. 

How about sometime Monday afternoon, between 12 & 2 pm pt?

**Comment by kltm** [comment]
@harryhoch 1pm PDT (or latest time for you) would work best for me--takes a little time for everything to reboot on Mondays. :cat:

**Comment by harryhoch** [comment]
let's do 1pm pt. I'll circulate a hangout invite. @davism84, if you're interested....

**Comment by cmungall** [comment]
I have a 1pm but you should all go ahead

**Comment by kltm** [comment]
It might be useful to get @kshefchek in as well--he'll be doing some work on other widgets and it would be good to get everybody on the same page.

**Comment by kltm** [comment]
@harryhoch there is now a working demo of both a jQuery widget and another separate program using the widget in both client and server in geneontology/go-exp. I think there is a pretty complete example of how things could work there, at least conceptually. It's somewhat documented, but we could go over it at some point.

**Comment by harryhoch** [comment]
ok, thanks. I'll take a look.

**Comment by kltm** [comment]
As well, at the other end of the spectrum from the geneontology/go-exp examples, geneontology/noctua is now a working example of a project with complicated dependencies all being managed by npm, package.json, gulp, etc.

**Comment by kltm** [comment]
As a side note for more long term migration, it looks like the ringo dependencies are all usable from npm

```
stick
common-utils/objects
buffer
base64-js
ieee754
is-array
```

**Comment by harryhoch** [comment]
fixed by https://github.com/monarch-initiative/monarch-app/pull/812
