### ISSUE TITLE
Add ability to compare phenotypes to list of genes on analyze page

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#666]
I've added a text area for users to input a list of gene IDs on the analyze page; however, this functionality is not yet implemented in webapp.js.  We need to update the analyze rest call to include a parameter for a set of genes.  @VincentIII @davism84 @nlwashington could use some suggestions on how to best implement.

**Comment by kshefchek** [comment]
Testing with this URL:
http://tartini.crbs.ucsd.edu/compare/HP_0000238/NCBIGene:8928+NCBIGene:57930+NCBIGene:100064793+NCBIGene:714987+NCBIGene:100019271+NCBIGene:14106+NCBIGene:464468+NCBIGene:100154027+NCBIGene:300054

I'm running into an issue with phenogrid here:

//Returns axis data from a ID of models or phenotypes
    _getAxisData: function(key) {

and then here:

/\* we only have 3 color,s but that will do for now */
    _getColorForModelValue: function(self,species,score) {
        //This is for the new "Overview" target option
        var selectedScale = self.state.colorScale[species][self.state.selectedCalculation]; 
        return selectedScale(score);

I believe the issue has to do with the HP term no including a taxon and label, for example:

"a": {

```
"id": "HP_0000238",
"label": "Hydrocephalus",
"type": "phenotype",
"taxon": 
```

{

```
"id": "",
"label": "Not Specified"
```

},
"id_list":

```
[
    "HP:0000238"
]
```

}

Will update the API call to include this information.

**Comment by VincentIII** [comment]
That sounds about right.  When things crash at that point it tends to be more of an incomplete data issue instead of a null-data issue.  I normally see it if its missing the calculation values for sorting, but it would make sense it would do the same when the taxon is missing

**Comment by kshefchek** [comment]
Adding this in didn't fix it unfortunately.  @VincentIII do you see anything else in that json structure that is missing?  I'm still getting a hashcode key error coming from _getAxisData: function(key) {}

**Comment by VincentIII** [comment]
Would you happen to know what it is passing to _getAxisData when it gives the error?

**Comment by kshefchek** [comment]
An undefined valued, just not sure where it is coming from (what should be defined here?)

Here are my logs when I print the key value at the top of the function: 
testing: http://tartini.crbs.ucsd.edu/compare/HP_0000238/NCBIGene:8928

NCBIGene_8928
phenogrid.js (line 1100)
undefined
phenogrid.js (line 1100)

**Comment by VincentIII** [comment]
It should be passing to there an ID, either on the phenotype side or the model side.  

This is what I'm seeing as a working JSON dump from what is currently being used.  The only major difference I'm seeing is the lack of a id_list here and the structure for the 'a' section being different.  I'm not sure if thats helpful at all though http://pastebin.com/E44EVHiP

**Comment by kshefchek** [comment]
I tried changing the structure of A to a list of ids but no dice.  If it makes a difference, this is failing in the
_createXLabels() function after the first loop here:
.each(function(d,i) { 
                var labelM = self._getAxisData(d).label;
                self._convertLabelHTML(self, this, self._getShortLabel(labelM,self.state.labelCharDisplayCount),d);
});

**Comment by VincentIII** [comment]
Sounds like then something with the model data isn't getting passed or defined properly.  Maybe do a dump of the this.state.xAxis and the this.state.filteredXAxis to see if there is any corrupt/incomplete data in there

**Comment by kshefchek** [comment]
They look pretty minimal at this point in the script:

X Axis:{"properties":{"replaceDuplicateKey":true,"equals":null}}
phenogrid.js (line 2368)
Filtered X Axis:{"properties":{"replaceDuplicateKey":true,"equals":null}}

**Comment by VincentIII** [comment]
Did you print them via this.state.xAxis.entries()?  Those data structures are hashtables built by JSHashtable, so a simple print shouldn't work.

**Comment by kshefchek** [comment]
So it works for the first iteration and then fails, this is what it prints the first time around:

X Axis:[["NCBIGene_14106",{"label":"Foxh1","species":"Mus musculus","taxon":"NCBITaxon:10090","type":"gene","pos":2,"opos":12,"rank":2,"score":27}],["NCBIGene_57930",{"label":"foxh1","species":"Danio rerio","taxon":"NCBITaxon:7955","type":"gene","pos":1,"opos":21,"rank":1,"score":41}],["NCBIGene_8928",{"label":"FOXH1","species":"Homo sapiens","taxon":"NCBITaxon:9606","type":"gene","pos":0,"opos":0,"rank":0,"score":30}]]
phenogrid.js (line 2368)
Filtered X Axis:[["NCBIGene_8928",{"label":"FOXH1","species":"Homo sapiens","taxon":"NCBITaxon:9606","type":"gene","pos":0,"opos":0,"rank":0,"score":30}],["NCBIGene_57930",{"label":"foxh1","species":"Danio rerio","taxon":"NCBITaxon:7955","type":"gene","pos":1,"opos":21,"rank":1,"score":41}],["NCBIGene_14106",{"label":"Foxh1","species":"Mus musculus","taxon":"NCBITaxon:10090","type":"gene","pos":2,"opos":12,"rank":2,"score":27}]]

**Comment by kshefchek** [comment]
Oddly enough it works for just one gene works:

![phenogrid](https://cloud.githubusercontent.com/assets/1467299/6534697/3f3a0376-c3f4-11e4-8c42-d1f853dfd110.png)

**Comment by VincentIII** [comment]
It seems it might be a bug with how it creates Overview positioning.  The value OPOS is made from the POS value (position on it's respective axis) but in consideration for how it would be in the overview section, which is the first 10 of each.  Right now OPOS is being built by adding a multiple of 10, based on the ordering of the species, to the position value, so the first of the Danio Rerio would have an OPOS of 20, first of Mus Musculus would have one of 10 and so on.  

I'm not sure if this issue was caused by a recent change in how the model_score is determined or if its one in how overview is created.  (Or a bit of both)

**Comment by kshefchek** [comment]
If I update the config file with:
"targetSpeciesName" : "Homo sapiens"
It renders the grid, so it must be overview related.  I'll make some changes so this will work with the compare function.

If we edit phenogrid.js do we push it to monarch-app or the phenogrid repo? I noticed the two files are different in each place.

**Comment by harryhoch** [comment]
Kent:

thanks. 

for now, please push to monarch-app. we will sync the phenogrid repo soon.

thanks,

harry

> On 6 Mar 2015, at 4:13 PM, Kent Shefchek notifications@github.com wrote:
> 
> If I update the config file with:
> "targetSpeciesName" : "Homo sapiens"
> It renders the grid, so it must be overview related. I'll make some changes so this will work with the compare function.
> 
> If we edit phenogrid.js do we push it to monarch-app or the phenogrid repo? I noticed the two files are different in each place.
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300
