### ISSUE TITLE
Some pages have no titles

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#669]
The following pages have no title:

 /disease
 /phenotype
 /gene
 /model 

As a trivial side note, most titles are of the form: "Monarch blah blah blah". The following pages are different:

 /annotate/text
 /page/about
 /sources

**Comment by kltm** [comment]
A fix to this requires a fix to monarch-app/tests/behave/maui_basic.feature

**Comment by kltm** [comment]
@kshefchek did you update monarch-app/tests/behave/maui_basic.feature?

**Comment by kshefchek** [comment]
Just updated the file, @kltm how do we run these tests locally? Are they on Jenkins?

**Comment by kltm** [comment]
Yes and yes.
I resent the email to m-dev, but the important URL is:

https://github.com/monarch-initiative/monarch-app/tree/master/tests/behave
