### ISSUE TITLE
show MOD gene links on gene pages

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#671]
eg. this Monarch zebrafish gene page should have a link to the ZFIN gene page:
http://monarchinitiative.org/gene/NCBIGene:557740

**Comment by kshefchek** [comment]
Seems to show up on tartini:
http://tartini.crbs.ucsd.edu/gene/NCBIGene:557740
@nlwashington @bryanlaraway any idea why we can generate this on beta federation services and not production?
http://beta.neuinfo.org/services/v1/federation/data/nlx_152525-4?exportType=data&filter=source:NCBIGene&filter=id:557740&filter=mapped_source:ZFIN
http://neuinfo.org/servicesv1/v1/federation/data/nlx_152525-4?exportType=data&filter=source:NCBIGene&filter=id:557740&filter=mapped_source:ZFIN

**Comment by jmcmurry** [comment]
I'm not sure whether this has been addressed to satisfaction.
I do see the ZFIN ID listed under equivalents, however it doesn't link to a ZFIN page, it links to a Monarch page, which in turn links out to a ZFIN page. I believe that this is the desired behavior and will provisionally close this.
![screen shot 2015-10-08 at 10 39 36](https://cloud.githubusercontent.com/assets/3658863/10374680/482a1610-6da9-11e5-974e-ad3baec62e6c.png)
![screen shot 2015-10-08 at 10 42 42](https://cloud.githubusercontent.com/assets/3658863/10374690/58dc52ac-6da9-11e5-839a-826bf020cb9f.png)
