### ISSUE TITLE
disease/model organism links in Phenogrid demo

### ISSUE THREAD

**Issue by hambone06** [monarch-initiative/monarch-legacy#675]
When I attempt to follow the links in the demo phenogrid (http://tartini.crbs.ucsd.edu/labs/analyze/phenotypes/) I keep getting error pages

**Comment by hambone06** [comment]
It is not all genes/OMIM entries
Entries with an empty overview page:
http://tartini.crbs.ucsd.edu/disease/OMIM:210600
http://tartini.crbs.ucsd.edu/gene/ORPHANET:84
Gene pages with proxy errors
http://tartini.crbs.ucsd.edu/gene/NCBIGene:100710
http://tartini.crbs.ucsd.edu/gene/NCBIGene:19701

**Comment by cmungall** [comment]
Seems to be fixed in refactored pages, e.g:

http://beta.monarchinitiative.org/disease/OMIM:210600
