### ISSUE TITLE
Make a generic version of a golr schema for multiple different kinds of association types

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#678]
Currently we have:
- [gene-to-phenotype](https://github.com/monarch-initiative/monarch-app/blob/master/conf/golr-views/gene-to-phenotype-config.yaml)
- [disease-to-phenotype](https://github.com/monarch-initiative/monarch-app/blob/master/conf/golr-views/disease-to-phenotype-config.yaml)

These are (a) named rather specifically; we want to have a more generic schema (b) jimmied into the existing go schema

We should create a generic view for monarch that handles multiple association types, following roughly the oban model, with the ability to store generic chains or graphs of evidence intervening the subject and object.

cc @ccondit @nlwashington @kltm @kshefchek

**Comment by kltm** [comment]
They both look like modifications to the amigo association schemas. Is there a link for the oban model? (I only found whiskey and a few probably unrelated models.)

**Comment by cmungall** [comment]
See [this commit](https://github.com/monarch-initiative/monarch-app/commit/f8a365676120bc01bbd3fbb3328b668484437e83) for how they differ.

[OBAN ttl](https://github.com/jamesmalone/OBAN/blob/master/ontology/oban_core.ttl)

**Comment by cmungall** [comment]
TODO: fix boost_weights

**Comment by cmungall** [comment]
For more context on this ticket, see: https://github.com/SciCrunch/SciGraph/issues/46

**Comment by nlwashington** [comment]
seems reasonable; i made a few comments in the commit related to some things that still seem very GO-specific (for example, panther families)

**Comment by kltm** [comment]
@cmungall remember that as well as the main configuration sets, _boost_weights_, _results_weights_, and _filter_weights_ must also be renamed/added/removed accordingly--they seem to have already slipped in oban-config.yaml for "panther_*".

**Comment by cmungall** [comment]
@kltm I didn't forget them - I wrote a TODO :-)

**Comment by cmungall** [comment]
@ccondit wanted to place a cypher query inside the yaml for controlling the closure. Thing is, it may be more complex than this. We may want to configure relations based on association type / categories of the subject and object

**Comment by ccondit** [comment]
I would think the following items should be in the YAML:
- The Cypher query
- An optional mapping of a projected node to a set of directed relationship types (would default to type and subClassOf)
- A map to handle the projection since I think the queries will generally need to `RETURN *` in order to collect the evidence.

**Comment by kltm** [comment]
@cmungall Whoops, my eyes went over that.

Could the cipher query just be reassembled out of the bits of the property list a la:
https://github.com/geneontology/amigo/blob/master/metadata/ont-config.yaml#L140

**Comment by kltm** [comment]
@ccondit beat me--it looks like that would not fit in the flat properties list.

**Comment by ccondit** [comment]
This is loaded on geoffrey for disease->phenotype.
http://geoffrey.crbs.ucsd.edu:8080/solr/golr/admin/

**Comment by jmcmurry** [comment]
@kshefchek @cmungall this is a very long running ticket with a lot of progress. Could one of you perhaps summarize what tasks remain to be done to close it?

**Comment by cmungall** [comment]
Done. See docs in conf/golr-views for how this works.
