### ISSUE TITLE
After using autocomplete for search back button does not return to Home

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/monarch-legacy#679]
I was just testing out the behavior tests on Monarch and for both the case when I click on an autocomplete suggestion OR click on the "Go" button to initiate a search, when I use the back button it takes me back to the Google search result page that I used to get to the Monarch app vs. the Home page of the Monarch app.

**Comment by kshefchek** [comment]
cc @kltm

**Comment by kltm** [comment]
It depends on the nature of the "forwarding". This is something that can happen, for example, if you're directly manipulating the URL rather than legitimately going to a new page.

**Comment by kshefchek** [comment]
It looks like we're overriding the default behavior of the form/button and using window.location.replace to redirect to the new page.

**Comment by kshefchek** [comment]
@kltm are there any issues with just replacing

```
    window.location.replace(url);
```

with

```
    window.location.href = url;
```

This seems to fix it for me.

**Comment by kltm** [comment]
Whatever works. Certainly in the former case, you are _literally_ replacing the URL, so it does not appear in the browser history. Keep in mind that different browsers may have their variations.
