### ISSUE TITLE
Citation links don't resolve

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#68]
For example, on this page:
http://tartini.crbs.ucsd.edu/model/MGI:1856108
on the phenotypes tab, there is a list of citations. 
These go to a monarch page that says page could not be found.

**Comment by cmungall** [comment]
Problem at DISCO/Ingest config stage:

http://alpha.neuinfo.org/services/v1/federation/data/nif-0000-00096-6.json?includePrimaryData=true&count=1000&q=MGI_1856108&includeSubclasses=true&

Note the field is "publicaton_id", should be "publication_id"

Will implement workaround

**Comment by cmungall** [comment]
Even with a workaround, the link ends up here:

$MONARCH/reference/PMID:9820556

need a generic redirect mechanism

**Comment by nlwashington** [comment]
in the services, you might be able to get the marked-up url that is created in the concept mapping stage.

**Comment by mellybelly** [comment]
Who should this be assigned to to resolve? necessary for release? are there other similar NIF links that are broken?

**Comment by cmungall** [comment]
Now redirects to pubmed.

Removed this from milestones as it works; leaving open as we need to undo https://github.com/monarch-initiative/monarch-app/commit/a9ebdfd4f05ab277f475b13d62c24636935848dd once changes made to ingest

**Comment by cmungall** [comment]
Re yr last question - see issue #87

**Comment by nlwashington** [comment]
i have now corrected the spelling of publication in the mouse phenotypes view.

note that there is now a field called publication_url that directs you to the right place (some PMIDs take you to pubmed, some Jrefs take you to MGI)

**Comment by nlwashington** [comment]
seems like this is done.  closing.
