### ISSUE TITLE
rename datagraph widget

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#682]
i think we need to come up with a new name for the "datagraph", since it doesn't really explain what it does, and is actually the barchart-style explorer/navigator of our data.

proposals to be collected in this ticket, and voted.

ideas:
*Ontology-based Data Explorer  (OnDEx or ODE)
*Ontology-Based Navigator of Data (OBaND)

once we come up with a new name, let's refactor the code to change it, and references in the ticketing system.  then we can actually use the word "datagraph" to refer to/describe the thing that is scigraph.

please suggest/vote @kshefchek @mellybelly @cmungall

**Comment by nlwashington** [comment]
(btw, i don't love my suggestions, but they're just something to get the conversation going)

**Comment by nlwashington** [comment]
Monarch Ontology Data Explorer (MODE)

**Comment by nlwashington** [comment]
Data and Ontology Visual Explorer (DOVE) !

Then, we could have "dove charts" (for a bar chart), and "dove graphs" (for connectivity diagrams). Do you love it @mellybelly?

**Comment by mellybelly** [comment]
OMG YES> and I even can imagine some logos...
Can be implemented in third party sites ostensibly...

**Comment by jmcmurry** [comment]
+1 for DOVE

On Tue, Apr 21, 2015 at 5:04 PM, Melissa Haendel <notifications@github.com>
wrote:

> OMG YES> and I even can imagine some logos...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/monarch-initiative/monarch-app/issues/682#issuecomment-94854065>
> .
>



-- 
----------------------------------
mcmurry.julie@gmail.com +44 756 837 5107 skype: mcmurry.julie
----------------------------------

**Comment by cmungall** [comment]
I LOVE DOVE

**Comment by micheldumontier** [comment]
+1

Michel Dumontier
Associate Professor of Medicine (Biomedical Informatics), Stanford
University
Chair, W3C Semantic Web for Health Care and the Life Sciences Interest Group
http://dumontierlab.com
