### ISSUE TITLE
Figures on the about page overflow panels on wider screens

### ISSUE THREAD

**Issue by Relequestual** [monarch-initiative/monarch-legacy#685]
![screen shot 2015-04-17 at 10 27 38](https://cloud.githubusercontent.com/assets/731158/7199404/6e75ed76-e4ec-11e4-97c9-7f13fa8f82f0.png)
To fix this, add...

```
.panel-body {
    overflow: hidden;
}
```

![screen shot 2015-04-17 at 10 29 29](https://cloud.githubusercontent.com/assets/731158/7199434/a9be8ad2-e4ec-11e4-8db3-3a31e70f0e89.png)

I don't know where you want this in your css or I'd make a pull request =]

**Comment by cmungall** [comment]
Thanks Ben!

**Comment by kshefchek** [comment]
It looks like this may have been fixed already, I see this issue on production but not on our beta site.  Will close and add a milestone to the ticket.
