### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by memartone** [monarch-initiative/monarch-legacy#688]
http://monarchinitiative.org/Phenotype,quality/FBcv_0000398

Got a page not found error

**Comment by cmungall** [comment]
Thanks. Do you recall how you ended up on that page? Was it via an autocomplete or search...

**Comment by jmcmurry** [comment]
This is a pretty old ticket, the origin of which was not documented; If we can't repeat it, or don't remember we should probably close it.

**Comment by nlwashington** [comment]
that path probably the result of incorrectly processing multiple categories on terms in autocomplete.  it has been fixed, afaik.
