### ISSUE TITLE
slow response from some gene-to-genotype dynamic queries

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#689]
from @davism84:
These are some example of slow returns

http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genes/MGI:101926/genotypes/targets.json

http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genes/MGI:1277234/genotypes/targets.json

http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genes/MGI:101926/genotypes/targets.json

I’m mainly getting errors on the compare call  with the following error:

TypeError: Cannot read property "id" from undefined
                at lib/monarch/api.js:4208 (anonymous)
                at lib/monarch/api.js:4324 (anonymous)
                at lib/monarch/web/webapp.js:1912 (anonymous)

here’s some examples

http://tartini.crbs.ucsd.edu/compare/HP_0000023+HP_0001156+HP_0002650+HP_0009748+HP_0003311+HP_0000431+HP_0004279+HP_0000316+HP_0000349+HP_0000327/MGI:3767611+MGI:3767626+MGI:3769575+MGI:3769576+MGI:3769577+MGI:3769578

http://tartini.crbs.ucsd.edu/compare/HP_0007018+HP_0003311+HP_0001159+HP_0000316+HP_0003196+HP_0001156+HP_0002650+HP_0000823+HP_0000508+HP_0000767+HP_0003318/MGI:5428939+MGI:5450053+MGI:5450054+MGI:5509044

http://tartini.crbs.ucsd.edu/compare/HP_0002938+HP_0003273+HP_0002751+HP_0006473+HP_0000768+HP_0000926+HP_0003417+HP_0000470+HP_0002750+HP_0003202/MGI:2448311+MGI:3845245+MGI:4366488+MGI:3845248+MGI:3845244+MGI:3829264

http://tartini.crbs.ucsd.edu/compare/HP_0002938/MGI:2448311

**Comment by nlwashington** [comment]
@davism84 , correct me if i am wrong...
right now, phenogrid executes the following when trying to expand genes to genotypes in the grid:
1.  given a `gene_id`, fetch the genotypes using a query in monarch that directly wraps the rosie query: `http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genes/<gene_id>/genotypes/targets.json`
2.  given the list of genotypes that are returned, execute a compare call like: `http://tartini.crbs.ucsd.edu/compare/pheno1+pheno2+...+phenoN/genotype1+genotype2+genotype3`

then, in the monarch-api, this will iterate over the genotype list, and build profiles of each of their phenotypes by executing either the old getGenotypeInfo or the new getPhenotypes that fetches them from rosie.  once the list of phenotypes is acquired, it will iteratively request comparisons of the query profile from the owlsim server.

now, the `Cannot read property "id" from undefined` is a bug.  that should get fixed, but is not a slow response issue.

here is where a golr query will serve us well, because you'll be able to simply query with the gene of interest and get back the phenotypes, without having to go through the middleman queries.  that would be better.

so, @cmungall should we have a function that is a get_genotype_phenotype_associations(id), where the id can be any id like gene or genotype or phenotype (or whatever the other facets might be?)  the first iteration might be to wrap the iterative queries (pulling that logic out of phenogrid completely), and then when we have this golr set up, we can swap in the golr to make it faster?  then, all mike has to do is call the single service?

**Comment by kshefchek** [comment]
Is it possible production owlsim is down/having issues?

**Comment by davism84** [comment]
@nlwashington @kshefchek @harryhoch 

I starting back on the gene/genotype expansion.  It appears that the following call is no longer working.  is there a new preferred way to get this info?

http://rosie.crbs.ucsd.edu:9000/scigraph/dynamic/genes/MGI:3036234/genotypes/targets.json

**Comment by kshefchek** [comment]
We removed the "targets" dynamic queries to clean things up.  I can add this one back in and rebuild the server, will update here when it is back.

**Comment by nlwashington** [comment]
we should think about the right strategy here...  (we asked about the usage of this feature before removing it, and we were told it wasn't needed.)  should this be a call to scigraph directly, or a golr call?  (in fact, it ought to be to a monarch service that should wrap whatever the right thing is...

**Comment by kshefchek** [comment]
I've added it back for the meantime although it seems we're not getting results back when we should (this is on http://duckworth.crbs.ucsd.edu:9000).
Having a Monarch service for this could be useful, should we break that out into a ticket?

**Comment by harryhoch** [comment]
@nlwashington , @cmungall , @kshefchek, re-initiating this discussion based on our call of 8/27/15.  

The goal here is to support expansion of phenogrid to constitutent genotypes associated with a gene identified as being a relevant model for a set of phenotypes. 

At it's most basic, this would just involve getting the list of genotypes for a gene, with IDs and labels. These could then be resubmitted to owlsim for a compare call. 

Alternatively, we might wrap this as one call that would get the genotypes and then process the results through owlsim directly. This would move complexity from the client to the server side.

see also https://github.com/monarch-initiative/monarch-app/issues/650 for relevant discussion.

**Comment by kshefchek** [comment]
I've added an API call pull these from golr, see 85ff71defdfd261a3e66c71068f4cab8d874d0c2, @harryhoch can this be closed?

**Comment by harryhoch** [comment]
I think this is a question fo @yuanzhou. Zhou, what do you think?

**Comment by yuanzhou** [comment]
@nlwashington @harryhoch @kshefchek Thanks for Kent's help, now I could get the genotypes of a specific gene using the API, for example: http://beta.monarchinitiative.org/gene/MGI:98956/genotype_list.json

It's also very fast to get the json back.

As discussed earlier in this issue, we can use the `compare` api to get matches of phenotypes and genotypes. I've encountered errors with using `MONARCH:` prefixed genotype IDs, see #1004. Can anyone troubleshot this data issue?
