### ISSUE TITLE
Add category and taxon to facets in golr scratch widget

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#692]
Branching off of #687

@ccondit has filled in some additional fields in the golr load (subject category and taxon) - we should expose these in the scratch widget

**Comment by cmungall** [comment]
Reopening: still need:
- subject_taxon doesn't apppear to be CURIE-ized
- subject_taxon_label required
- I would expect 7955 and 9606 to also show as taxa for zebrafish and mouse genes?

**Comment by cmungall** [comment]
Another oddity: /labs/widget-scratch/disease/DOID:14330 -- 'Waisman syndrome' shows up as a gene?

**Comment by ccondit** [comment]
@nlwashington what do I need to add to the graph to get the complete declaration for these NCBI taxons? There's not a label because there wasn't one declared during the import to SciGraph

**Comment by nlwashington** [comment]
Here's an example of Mus musculus in ontobee: http://purl.obolibrary.org/obo/NCBITaxon_10090.  You can see how deep it is, so @cmungall will get us a slimmed version of NCBITaxon.

For the purposes of categories, we could either say subclass of all organisms NCBITaxon:1, or subclass of Eukaryotes NCBITaxon:2759.  (We are not dealing with Bacteria.)

Most of the data we're dealing with at the moment are Metazoans, which would trim things even more NCBITaxon:33208.

@cmungall may have an opinion about which to use.

**Comment by cmungall** [comment]
for now I just added this to monarch.owl

```
+        <owl:imports rdf:resource="http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl"/>
```

it's OTT for our purposes - I'll make a more select one later

**Comment by ccondit** [comment]
@nlwashington - looks like DIPPER is using `http://www.ncbi.nlm.nih.gov/taxonomy/10090` instead of `http://purl.obolibrary.org/obo/NCBITaxon_10090`. How should this get resolved?

**Comment by cmungall** [comment]
that's weird, it looks like dipper is using NCBITaxon:nnnn throughout

**Comment by ccondit** [comment]
http://nif-crawler.neuinfo.org/monarch/ttl/mgi.ttl has lots of references to http://www.ncbi.nlm.nih.gov/taxonomy/10090

**Comment by nlwashington** [comment]
yes, very odd because 'NCBITaxon' : 'http://purl.obolibrary.org/obo/NCBITaxon_'
 is in the curiemap.

**Comment by nlwashington** [comment]
maybe mgi was processed long enough ago that it wasn't updated to the new curiemap.

it's been awhile since it was processed. we can run the bamboo job again.

**Comment by nlwashington** [comment]
ok, these should be gone out of the most recent MGI processing.  try reloading duckworth/golr with the suite of the revised files (on or after 28-Apr-2015).

**Comment by ccondit** [comment]
It appears these are resolved with the latest duckworth load.
