### ISSUE TITLE
Storing relationships closures in Golr / OBAN

### ISSUE THREAD

**Issue by ccondit** [monarch-initiative/monarch-legacy#698]
To store gene homologs in Golr (which has a pattern like this):
(gene)-[:RO_HOM0000017!]-(homolog)
it's required that the specific child of RO_HOM0000017 be searchable (along with its closure). Which field in the Golr schema should be used for this?

And how should a case involving a chain of properties needing to be searchable (with closures) be handled?

/cc @nlwashington

**Comment by cmungall** [comment]
Reflexive  superPropertieswould be stored in `relation_closure`; that 
was you can search using a broader relation

(aside: looks like we're missing RO from our CURIE map)

**Comment by ccondit** [comment]
Gene to gene relationships are now materialized in Golr:
http://geoffrey.crbs.ucsd.edu:8080/solr/golr/select/?q=subject_category%3Agene+object_category%3Agene&version=2.2&start=0&rows=10&indent=on

see also: SciGraph/SciGraph#46
