### ISSUE TITLE
Grey out tabs with no data

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#70]
Not all tabs are populated

**Comment by sarahjkim** [comment]
The only tab I noticed was empty was the Phenotype pages' Genotype tab. Was there anything else I missed?
Also, did you just want the tab grey to show that it is not populated or did you want the tab to not be clickable (doesn't do anything or show anything)?

**Comment by cmungall** [comment]
The idea here is to grey-out if the tab has no data for the particular entity we're looking at - so this has to be dynamic.

See the phenotype tab in the disease page for an example (in this particular case we don't grey out, we provide a message, but the idea is the same)

We'll need to add something to the info object like this:

```
        info.hasPhenotypes = (info.phenotype_associations.length > 0);
```

(see /disease/:id.:fmt? in webapp.js for an example)

Then in disease.mustach we have a switch:

```
            {{#hasPhenotypes}}
             {{{phenotypeTable}}}
            {{/hasPhenotypes}}
            {{^hasPhenotypes}}
            <p><i>No phenotypes currently associated with disease</i></p>
            <h4>Why are there no phenotypes?</h4>
            <p>This pre-release of the Monarch system only
            includes disease-phenotype associations from a
            selected set of resources, and are primarily limited
            to genetic diseases. Future releases will aggregate
            data from a wider range of sources, including common
            diseases.</p>  {{/hasPhenotypes}}
```

The idea is the same, except we want the tab to be greyed rather than displaying alternate text.

Then we need a logic switch in the template:
