### ISSUE TITLE
autocomplete selection not resolving to page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#700]
when i type in the gene label 'ZRS', i select the first match from the autocomplete.

but it sends me to:
http://tartini.crbs.ucsd.edu/gene/OBO%3ANCBIGene_64327

but it should send me to:
http://tartini.crbs.ucsd.edu/gene/NCBIGene_64327

**Comment by cmungall** [comment]
Does our SG instance use the same curie map as dipper?

**Comment by kshefchek** [comment]
Related: https://github.com/SciGraph/SciGraph/issues/92

Per @nlwashington in that ticket:

```
    This us in flux. Thus is the issue if differences between genes in
    monarch.owl vs ncbigene.ttl...genes are coming in two places
```

**Comment by cmungall** [comment]
I think this is unrelated?

**Comment by kshefchek** [comment]
I think it's related but maybe I'm misunderstanding the issue.  Autocomplete is pulling IDs directly from SciGraph, so if the NCBIGene IDs in SciGraph have the prefix OBO:NCBIGene_ then that's the issue.

If this is correct (for now) then I can modify the curie post-SciGraph either on the server or client side.

**Comment by kshefchek** [comment]
Added in a temporary fix so autocompleting and searches on genes redirect correctly, will leave open until things are fixed on the SciGraph side.

**Comment by kshefchek** [comment]
Will remove hack and close given the scigraph fix here: https://github.com/SciGraph/SciGraph/issues/92

**Comment by cmungall** [comment]
Note that the page we get sent to uses escaped characters. It still works, but we should avoid this
