### ISSUE TITLE
Remove MONARCH:AssocID from evidence in results table from golr views

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#702]
This is a subtask for a #687

```
     - fix evidence
```

@ccondit is something that can be removed when generating the golr view?  Or is it possible we may use the association ID in another viewer (such as a DAG view).

**Comment by ccondit** [comment]
Seems strange to just exclude those nodes. Perhaps we should revisit how the evidence is collected?

/cc @nlwashington @cmungall

**Comment by kshefchek** [comment]
It should be just as easy to remove it on the front end if it makes sense to keep them.

**Comment by kltm** [comment]
We had a discussion here with @cmungall, @nlwashington, and @ccondit about evidence in monarch.
The takeaway from that for this ticket is:
- the golr data will be rejiggered to expose a broader range of aspects of the evidence graph in simpler ways (e.g. there will be the proper reference id/label pairs to make some columns work properly out of the box without having to invoke handler functions).
- at some point you'll work with the graph objects more directly to create displays, but not in the near term for the results table

**Comment by cmungall** [comment]
Also with #705 we can show the fine-grained details (this will require the graph object)
