### ISSUE TITLE
pemphigus vs Pemphigus Erythematosus

### ISSUE THREAD

**Issue by memartone** [monarch-initiative/monarch-legacy#707]
I searched Monarch for pemphigus and got zero results:  http://monarchinitiative.org/disease/DOID:9182
I searched for Pemphigus Erythematosus and got 5 human phenotypes.  

But I would expect that if I searched for Pemphigus, that it would give me some indication of related diseases or where results would be found, but I didn't see any.

**Comment by cmungall** [comment]
Thanks! This is a disease ontology issue so I'm moving this to a ticket here: https://github.com/monarch-initiative/human-disease-ontology/issues/34

Will close this one when the above is done

**Comment by cmungall** [comment]
closing as it's an ontology issue, follow tracker link above
