### ISSUE TITLE
About page - Image not shown correctly

### ISSUE THREAD

**Issue by iamkoehler** [monarch-initiative/monarch-legacy#708]
The image on the about page (http://monarchinitiative.org/page/about) is not displayed properly. See attached screenshot. I am on MacOS using Chrome.

![screen shot 2015-05-16 at 14 24 49](https://cloud.githubusercontent.com/assets/5172897/7666111/c13a15f8-fbd7-11e4-8bd4-5e0f486cdb1c.png)

**Comment by cmungall** [comment]
Thanks. Fixed in beta http://beta.monarchinitiative.org/page/about so I'll close (but unfortunately you might not see for a bit)
