### ISSUE TITLE
cytoscape demo has kato service URL hardcoded

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#709]
I think this predates when we had SciGraph in the conf

One of these files is loaded on startup:
https://github.com/monarch-initiative/monarch-app/blob/master/conf/server_config_dev.json
https://github.com/monarch-initiative/monarch-app/blob/master/conf/server_config_production.json

The demo should pull the URL for SG from here

**Comment by cmungall** [comment]
It would be great to revive this before the Sept release

**Comment by kltm** [comment]
If it's a priority to get this going again, let me get clear of the evidence issues in noctua and I can add a lick of paint to whatever is in there.

**Comment by cmungall** [comment]
It may require boths licks of paint, and tweaks at the SG services level

**Comment by kshefchek** [comment]
Is it worth considering the Neo4J graph vis browser?  It is built with d3 so it should fit well with rest of our d3 widgets.  http://neo4j.com/developer/guide-data-visualization/

**Comment by harryhoch** [comment]
@kshefchek, I think the  the neo4j browser or something else d3-ish (neo4j is a pretty thin wrapper) are definitely worth considering, but the real question involves determining the goals of this view.

**Comment by cmungall** [comment]
neo4j browser: seems to expose the underlying structure too much, we'd at least need to be able to customize (e.g. use labels for rendering nodes, special logic for blank nodes, etc)

goals: interactive discovery based exploration, highlight connectivity of our data

**Comment by kshefchek** [comment]
also jsPlumb as a possible solution (cc @jnguyenx).

**Comment by cmungall** [comment]
jsPlumb great for editing small networks - maybe less so for this use case?

**Comment by kltm** [comment]
I'd second that, emphasizing that jsPlumb is great for rich editorial things and having full control over entity contents, while cytoscape.js is much faster, has great baked in layouts and grouping operations, and really terrific for high level overviews.
