### ISSUE TITLE
Update styling of bbop live widget (golr tables)

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#710]
This is a subtask of #687 
The golr tables should be updated to fit the Monarch color palette.  There are additional stylistic changes that could be made.
- Space between first, prev, next, last
- Make divs/buttons in filter area smaller

Post additional stylistic changes here.  Some can be done with css; however, some things may be coded into the bbop widgets. @kltm what is the best way to approach this?

**Comment by kltm** [comment]
There should be a ton of CSS classes already in there. Just override what's there.

**Comment by kshefchek** [comment]
@kltm for example if I want to update the spacing of the paging buttons, it looks like the div IDs are automatically generated in the widget code, and the classes are from BS3.  In this case would I need to change the bbop widget code to add additional styling?

**Comment by kshefchek** [comment]
Wait nevermind, I think I have it figured out.
