### ISSUE TITLE
missing hiererchy for ZP:0007079

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#712]
[abnormal(ly) located in pancreatic ductal cell towards hepatic duct](http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/ZP:0007079?depth=4&blankNodes=false&direction=both) is not connected to anything on geoffrey.  do you know why @cmungall or @ccondit ?

**Comment by ccondit** [comment]
Connect to bNodes:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/ZP:0007079?depth=1&blankNodes=true&direction=both
Does that help?

**Comment by ccondit** [comment]
Actually looks like the graph on geoffrey was very old. Should be there now:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/ZP:0007079
