### ISSUE TITLE
add higher limit for viewing results in table

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#714]
we need to permit viewing more of the association results... either ALL or at least 1000.  this needs to be added to the configuration for available options in the selection box.

**Comment by kshefchek** [comment]
cc @kltm this may require a bbop pull request on my end

**Comment by kltm** [comment]
Likely live_pager.js.
Completely untested fix put in at + bbop@2.3.2

**Comment by kltm** [comment]
Bump the version in package.json and run

```
npm install
```

to get it.
