### ISSUE TITLE
make facet selection a checkbox

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#715]
i would prefer the facet selection to be a simple checkbox, rather than two buttons next to each.  for example 
![screen shot 2015-05-21 at 5 24 14 pm](https://cloud.githubusercontent.com/assets/5124411/7761721/3f32cb08-ffde-11e4-9a5d-f43014cc54d0.png)

this would be much more compact, so we can fit more on the page.

**Comment by kshefchek** [comment]
We decided this couldn't be done since we have both positive and negative filters.  Let's brainstorm and break out into new issue with different requirements.
