### ISSUE TITLE
ECO labels not showing up in table

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#719]
the labels for any evidence code ids are not showing up in the association table.

**Comment by kshefchek** [comment]
@ccondit should we be pulling data from evidence or evidence_closure?  If evidence is correct then the issue is that there is not an evidence_label field, although I could pull this from evidence_closure_label need be.

**Comment by kltm** [comment]
If there is an automatic mechanism to handle things, then that mechanism should be used in preference to a hack. The fields should have matching partners if ID fields need to display labels.

**Comment by kshefchek** [comment]
Fair enough @kltm, so
1. We need an evidence_label feld
or 
2. We need to pull data from evidence_closure as opposed to evidence

**Comment by kltm** [comment]
I'd assume that it's 1 as the closures can be large, have no structure, and are mostly there for filtering purposes--a bit of a mess to display all the time.

**Comment by ccondit** [comment]
See SciGraph/golr-loader#3

**Comment by kshefchek** [comment]
reassinging to myself as the golr results look correct now, thanks @ccondit!

**Comment by kshefchek** [comment]
This is fixed with the exception of lists of IDs.  Issue filed here: #729
