### ISSUE TITLE
Long list of IDs requires post for simsearch

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#720]
The folks at ZFIN have identified a problem with long lists of IDs going to simsearch - see
https://github.com/monarch-initiative/phenogrid/issues/78.

Changing /simsearch/phenotype to accept a POST as well as a get seems to be the clean starting point.  I think we could add 

app.post('/simsearch/phenotype.:fmt?', function(request, fmt) {..}

alongside the existing 

app.get('/simsearch/phenotype.:fmt?', function(request, fmt) {..}) 

and have both call the same function. This would require chaning phenogrid to post rather than get, but that should not pose a problem.

@kltm, @cmungall, do you see any concerns with this approach?

**Comment by kshefchek** [comment]
We do this on the analyze page, see [post](https://github.com/monarch-initiative/monarch-app/blob/17edb32e42296b76723476428e835d65575c6302/lib/monarch/web/webapp.js#L3329) and [get](https://github.com/monarch-initiative/monarch-app/blob/17edb32e42296b76723476428e835d65575c6302/lib/monarch/web/webapp.js#L3418)

**Comment by harryhoch** [comment]
yes. I saw that. so, no reason to be concerned about doing this for simsearch?

**Comment by kshefchek** [comment]
Taking a look at this now.  We're running into issues where phenogrid fails due to having too many HP terms and it prevents the rest of the Golr Ajax calls from running.  So we need to write a post route (and parse the data being posted) and also incorporate any phenogrid client side code into puptent so we can execute the ajax calls in a certain order (or make sure it fails without killing all the client side code).  See SHH as an example: http://beta.monarchinitiative.org/gene/NCBIGene:6469

**Comment by kshefchek** [comment]
Hacky fix put in here https://github.com/monarch-initiative/monarch-app/commit/030fcfb2ba2c24fcc8b4cfced35efdaab1a443ee, @harryhoch @davism84 I will think of a better way but maybe this will be cleaned up in the phenogrid refactor.

**Comment by harryhoch** [comment]
@kshefchek, I will to look at this code, but it sounds to me like we need at the very least to have  a discussion about the requests and plans. I'm a bit concerned about the "incorporate any phenogrid client code into puptent so we can execute the ajax calls in a certain order" comment.  Seems to me to be more than a bit fragile....

**Comment by harryhoch** [comment]
ok, I sort of understand the changes, but I'm curious, @kshefchek, is there any reason not to just implement a POST for /simsearch and have this code always POST - never GET?

keeping this issue open as long as the solution is hacky...

**Comment by kshefchek** [comment]
So simsearch should always be a post; however, the compare call is still only configured as a get, so that is the reason for the if else spaghetti.

The pup tent bit is in regards to ordering functions inside the jquery document ready function.  Right now we have a few document readies floating around, but I haven't made any updates to consolidate things.

**Comment by harryhoch** [comment]
Ok. We should discuss sometime soon.

**Comment by kshefchek** [comment]
Looks like this was changed to a GET again on the phenogrid side, @yuanzhou or @davism84 could you change any simsearch calls to a POST.  Pages with large numbers of phenotypes fail as a result, see http://beta.monarchinitiative.org/gene/NCBIGene:100

**Comment by harryhoch** [comment]
yes, @yuanzhou, @davism84, please look at this.

**Comment by yuanzhou** [comment]
@kshefchek is there anything I can help with? I did see the 414 error (Request-URI Too Large) after clicking http://beta.monarchinitiative.org/gene/NCBIGene:100, and the phenogrid loading indicator stays there.

FYI @kshefchek , right now the phenogrid uses the bundled and minified phenogrid-bundle.js, for your debugging, you can disable the uglify in gulpfile.js and type `gulp bundle` again to create a non-minified version.

**Comment by yuanzhou** [comment]
I'm also thinking that if we can get rod of the "HP:" for each phenotype ID in the URI when composing the URI in phenogrid, and add that prefix back once monarch-app receives the HTTP request. @kshefchek @harryhoch  Not sure if this change will make a big difference. HTTP POST should be able to resolve this data restriction issue too.

**Comment by kshefchek** [comment]
I've fixed it locally, (just recopied the commit referenced above).  I'll make a fork and a pull request.

**Comment by yuanzhou** [comment]
@kshefchek I've added my questions in the PR page: https://github.com/monarch-initiative/phenogrid/pull/124

**Comment by kshefchek** [comment]
Does it even make sense to send this many phenotypes to the phenogrid, should we set a lower limit?

**Comment by harryhoch** [comment]
@yuanzhou, can we close this?

**Comment by yuanzhou** [comment]
Switched from http get to http post for ajax request to simsearch. Resolved the 414 and 413 errors.
