### ISSUE TITLE
Add query filter on object_closure OR subject_closure for GOlr views

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#723]
We need to filter results on an id matching the object_closure or subject_closure in a GOlr view.  Depends on berkeleybop/bbop-js#5 cc @kltm

**Comment by kltm** [comment]
Okay, for the time being we'll split into separate tabs for the different aspects; we'll revisit this maybe after the next release.

**Comment by kshefchek** [comment]
cc @nlwashington and @ccondit as this is a follow up from yesterdays convo.

**Comment by nlwashington** [comment]
So, not being able to do OR queries is possibly a blocker for this release.  We need "OR" queries for the ortholog tab.  It doesn't make sense to partition the orthologs into separate tabs just because sometimes the gene is the subject and other times it's the object.  The only workaround would be for us to materialize the inverse orthology relationships...which we can do, but seems like an extra step that shouldn't have to be done.

**Comment by jmcmurry** [comment]
@kshefchek and @kltm could you break this down into the steps we need to make this work? No need to tackle them just yet, but it has been out there for a while so just want to better understand any blockers or difficulties.

**Comment by kshefchek** [comment]
This is my understanding, @kltm please correct me

Solr/Golr supports mixing logical OR/AND filters ([for example](http://sirius.monarchinitiative.org:8080/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=1000&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&facet.method=enum&fq=subject_closure:%22MGI:2676312%22%20OR%20object_closure:%22MGI:2676312%22&facet.field=subject_category&facet.field=subject_taxon&facet.field=subject_closure_label&facet.field=relation_closure_label&facet.field=evidence_closure_label&facet.field=object_category&facet.field=object_taxon&facet.field=object_closure_label&q=*:*))

I think this functionality is supported in the javascript API via this function: http://kltm.github.io/bbop-js/docs/files/golr/manager-js.html#bbop.golr.manager.add_query_filter_as_string but I see this is still open: https://github.com/berkeleybop/bbop-js/issues/5

There are implications here with how to handle this in the bbop filter widget, but this no longer an issue for us since we've disabled this widget.

So we could theoretically start implementing this in the monarch-app if needed (ortholog tabs?)

**Comment by cmungall** [comment]
I thought we no longer needed this, as we prepoluate the inferred symmetric relationships?

**Comment by kltm** [comment]
This was my understanding as well.

**Comment by kshefchek** [comment]
My understanding was that this for a single table view if we ever decide to go down that route?

**Comment by cmungall** [comment]
Not following

**Comment by kshefchek** [comment]
We originally created this ticket when we were discussing having a single large table with all our data versus breaking things into tabs.

**Comment by kshefchek** [comment]
I'm going to close as we don't have any actionable items here, and it's possible I misunderstood the problem when making the ticket.
