### ISSUE TITLE
new data dumpers for owlsim engine

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#725]
we need new data dumpers for getting the geno-pheno data out of scigraph and into owlsim.  these are to replace the old shell code that lived in our private svn.

@cmungall do you want these to only do the "basic filtering" like we did previously, or include all data (genotypes, inferred gene-disease like for human, etc)?

**Comment by nlwashington** [comment]
@cmungall do you want a separate project for these?

**Comment by nlwashington** [comment]
these will probably require new cypher queries.  should these go into golr?

**Comment by cmungall** [comment]
This is what I think we decided:

the logic for basic filtering would go into the cypher/sg code that produces the golr documents. We would include a qualifier which is something like `single-gene` which corresponds sort-of wiith the previous logic for `basic-filter`.

The dumper code would then become essentially a wget/curl to golr with `fq` set to whatever we call the filter, plus `fq`s for the species. This would be a bamboo job, and we would deposit things in a parallel directory to http://nif-crawler.neuinfo.org/monarch/ttl/
