### ISSUE TITLE
Write test for new UI checks for equivalent disease classes 

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#726]
Use this one:

DOID:3491 ! Turner syndrome

should show the same data as Orphanet:881

migrated from
monarch-initiative/hpo-annotation-data#3

**Comment by jmcmurry** [comment]
@cmungall could you clarify, please? I expected this ticket to be about dissimilarity in the pages, but Orphanet:881 is an XREF but NOT an equivalent identifier in Monarch or in DOID. 

The identifier that _is_ listed as a true equivalent is the MESH:D014424, which appropriately redirects from [MESH:D014424](http://beta.monarchinitiative.org/disease/MESH:D014424) to [DOID:3491](http://beta.monarchinitiative.org/disease/DOID:3491) in Monarch.

Therefore, unsurprisingly perhaps, for [Orphanet:881](http://beta.monarchinitiative.org/disease/Orphanet:881) we get a 404

```
http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/Orphanet:881.js…lankNodes=false&relationshipType=subClassOf&direction=OUTGOING&project=%2A 
Failed to load resource: the server responded with a status of 404 (Not Found)
```

Was the ticket prompted by:
A) a broken link internal to Monarch (if so where?)
B) the case where a user might see the curie pattern and manually tweak the URL hoping for a result

**Comment by cmungall** [comment]
Will be fixed after next SciGraph ontology load
