### ISSUE TITLE
Add heritability information to new disease pages

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#727]
On our current disease pages we place heritability information in the jumbotron.  Is it possible to get this information from scigraph and/or the golr tables? cc @nlwashington

**Comment by jmcmurry** [comment]
I don't see any heritability information in the disease page jumbotron.
http://beta.monarchinitiative.org/disease/DOID:3491
@kshefchek could you provide an example of what you're looking for and where?

**Comment by kshefchek** [comment]
added with #1496

**Comment by jmcmurry** [comment]
Yayyyyy!
