### ISSUE TITLE
Add mapping field to disambiguate lists of ids and labels in golr results

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#729]
Having data in arrays/lists from solr seems to break the handler and linker classes (things return null).  Will add a test in linker.js.tests to catch this.

@kltm any advice to handle this?

**Comment by kltm** [comment]
It's fine with this things at our end, we have tons of lists coming back. They are handled as separate iterations within the same cell. For example, direct annotation and synonyms here:

 http://amigo2.berkeleybop.org/amigo/search/bioentity

**Comment by kshefchek** [comment]
Interesting, not sure why there's an issue with our handler/linker then.  Will look back at amigo to make sure I didn't remove anything related.  Is it possible it's related to having both strings and lists for the same field?  It seems to default to the ID as text rather than converting to an anchor/img tag or label as plain html text.

**Comment by kltm** [comment]
IIRC, you removed some of the handling with your custom overload.

**Comment by kshefchek** [comment]
@ktlm are you referring to overriding the process_entry function?  I just added one line and left the rest as is:

```
    var category = anchor._golr_response.get_doc_field(did, field_id+'_category');
```

So not sure why this would break things, but I'm taking a closer look now.

Shot in the dark, but what would happen if it's a list of two identical IDs and two identical labels?  Is it possible this would confuse things and fall back to the IDs?

**Comment by kltm** [comment]
Probably not.

Assuming that they are coming in like that, the handling function has no conception of other things in the list so duplicates would not matter.

**Comment by kshefchek** [comment]
In debugging it seems to be 

```
    var ilabel = anchor._golr_response.get_doc_label(did, field_id, bit);
```

Is returning null, do we need some additional field in the golr document?  I'm seeing it's try to get fields called *_map, _closure_map, _list_map

Referencing [this](https://github.com/berkeleybop/bbop-js/blob/master/lib/bbop/golr/response.js#L507)

**Comment by kltm** [comment]
Yes, those are in the requirements for the ids to map to labels--Solr lists are not ordered.

**Comment by kshefchek** [comment]
So is this is a golr data issue?  If so cc'ing @ccondit

**Comment by kltm** [comment]
If that is the root cause here, yes: if you want to be able to map labels and ids to each other, the _map fields must be appropriately populated (like you already have for several other fields).

**Comment by kshefchek** [comment]
Okay, it's possible they are there we're just need to add them to conf files, exploring now.

**Comment by kshefchek** [comment]
I don't think we generate those fields, although I could be wrong.  @kltm could you explain to @ccondit what is needed for the bbop widget to work?

**Comment by kltm** [comment]
Since this is already done other places, it should hopefully be self-evident: https://github.com/monarch-initiative/monarch-app/issues/729#issuecomment-106957623

**Comment by cmungall** [comment]
@kltm can you point to some golr specs documenting what should go in the map fields?

**Comment by kltm** [comment]
Hrm, it's unfortunately a little weakly documented since it's all automatic in the OWLTools GOlr loader, so parts are not explicit like we need here.

I've updated some information here for starters: https://github.com/berkeleybop/bbop-js/wiki/Schema .

**Comment by jmcmurry** [comment]
@kshefchek please provide update with clarification of any blockers, thanks

**Comment by cmungall** [comment]
Can this be closed @kshefchek ?

**Comment by kshefchek** [comment]
This has been implemented (credit @ccondit), closing.
