### ISSUE TITLE
Multiple-phenotype  input page

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#73]
Use the http://sproutsocial.github.io/inputosaurus-text/ widget to allow input of multiple HP terms for a phenotype profile search, displaying results with /analyze/phenotypes

**Comment by cmungall** [comment]
@kltm what do you think of this widget?

**Comment by kltm** [comment]
I couldn't get the demos to work, so I can't say I'd be thrilled with that. Also, it doesn't seem to be an official plug-in, so it's just independently maintained (less than a year) by a couple of people for whatever jQuery release their using.

As well, looking at the code, they aren't using $ safely, so it would be incompatible with other libraries and some jQuery use cases.

Is there a use case where this is a better fit than the official one?
http://jqueryui.com/autocomplete/

**Comment by harryhoch** [comment]
Different purposes.  Autocomplete is good for picking one term at a time. We need a good way to track multiple requests, as in multiple phenotype terms in one widget. Nothing officially blessed in jquery ui fits. I'll look for something safer.

**Comment by harryhoch** [comment]
How about http://aehlke.github.io/tag-it/

**Comment by cmungall** [comment]
I showed Seth this
http://www.sanger.ac.uk/resources/databases/exomiser/query/

He says it would be easy to do this with jquery autocomplete, with a few lines of code writing to a div element

**Comment by harryhoch** [comment]
ok. that's fine. If Seth can get to this soon, I'll leave it to him. I probably won't be able to touch it anytime this week...

**Comment by kltm** [comment]
Happy to help, but I'll need a spec for what exactly is wanted and how I should provide it. I'll assume that Chris will provide.

**Comment by cmungall** [comment]
The page is here: /analyze/phenotypes/

It currently allows you to enter IDs into a box - this is the part needing replaced.

Don't worry about categories for now - for first pass just use anything you can get from an autocompete.

You should only need to modify:
- lib/webapp/monarch.js - /analyze/:datatype.:fmt?
- templates/analyze.mustache

To see how we plug AC in:
- templates/navlist.mustache
- js/search.js

@sarahjkim will give this the same L&F as the newer pages.

**Comment by kltm** [comment]
I've pushed an attempt at basic functionality (old version commented out). It looks like the IDs are a bit bum, so somebody will have to look at that.

**Comment by cmungall** [comment]
Looks good.
http://tartini.crbs.ucsd.edu/analyze/phenotypes/

We will take care of finessing the text.

The main problem is that phenotype classes are not available in the autocomplete; this is being taken care of upstream, we should be able to test properly then.

**Comment by sarahjkim** [comment]
I like how you can analyze cats or practically any string for that matter. :D /analyze/cats/
