### ISSUE TITLE
Create bamboo job to load ontologies into golr

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#730]
@kltm can you check the command line:

```
owltools monarch.owl  --reasoner elk --solr-url URL  --solr-config ont-config.yaml  --solr-load-ontology --solr-load-ontology-general
```

(adjusting paths for the two files as appropriate)

I will provide the yaml

**Comment by cmungall** [comment]
cc @jnguyenx -- when this is done phenotua can use the same golr as monarch-app

**Comment by kltm** [comment]
**--solr-load-ontology-general** only if you have a general schema I believe.

**Comment by kltm** [comment]
Paring down our full load to remove anything GO-specific, maybe something like:

``` shell
owltools file1.owl file2.owl --merge-support-ontologies --reasoner elk --solr-url http://golr.foo.com --solr-purge --solr-config ont-config.yaml --solr-load-ontology
```

**Comment by jmcmurry** [comment]
@kltm can this be closed?

**Comment by kltm** [comment]
I have no truck with the bamboo jobs and I believe there is no push to use owltools at this point; removing self. Not sure who the right person would be...
