### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#731]
README.md has barely changed, but now we have a different install path involving npm and gulp

**Comment by kltm** [comment]
Yeeeah...
So far, it's kind of "optional" as you only need it to do some things that could be some other way anyways, so I thought it would be confusing to add it to the official installation docs (and in the process make it look like node is a req, which it will be anyways but...).

It might be an idea to add it to the "developers" README instead for the time being.

**Comment by jmcmurry** [comment]
I would love for @DoctorBud to have a look at the README and developers README and make appropriate changes while recently encountered install challenges are fresh in our minds.

**Comment by DoctorBud** [comment]
The current README is up-to-date compared to when this ticket was composed. It documents the NodeJS server, how to use WebPack, and how to test/debug. Closing this ticket.
