### ISSUE TITLE
Remove dependencies on cache

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#736]
the new golr-enabled pages should ideally not rely on a cache

It looks like this is done, although there is one case:
`cache/phenotypeprofile/key--6831774267.json`

I suppose this is useful for the Compare widget, but can we come up with a different way of doing this? 
It appears that this is cacheing an owlsim call.. not quite sure why this is being done at this stage? Doesn't phenogrid make the call?

**Comment by harryhoch** [comment]
yes, I added that cache in for phenogrid purposes.

app.get('/simsearch/phenotype..") gets called from phenogrid to do the compare, and 

engine.searchByPhenotypeProfile checks the cache, based on a hashCode of the sorted phenotype list. 

The goal is to speed up phenogrid data access  (and avoid recomputes ) for complex owlsim calculations. I don't think this data should go into golr, should it?

**Comment by cmungall** [comment]
I like the idea of a single cache for simplicity and golr is servingthe purpose of a fast faceted cache for SG... but it sounds like in practical terms it's fine to keep the profilecache for now

**Comment by kltm** [comment]
How large are these files?
