### ISSUE TITLE
Investigate lazy loading of tables within each tab

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#738]
New golr-enabled pages are so much faster, and with (almost) no cache! But can we improve?

See firebug screenshot

![screen shot 2015-06-03 at 9 58 54 am](https://cloud.githubusercontent.com/assets/50745/7966192/4814d24a-09d7-11e5-889f-abe03a0e7cf1.png)

Note that on rendering a page, n golr queries are performed, where `n = |Tabs|`

Can we get a lower latency for loading a page by only loading a molr table within each tab once the tab is selected? Or would that be frustrating for the user? Or too complicated?

Nathan did an experiment like this with the old pages, we could investigate that.

**Comment by cmungall** [comment]
I'd particularly like to investigate lazy loading of the phenogrid tab, since the first time around this incurs a large server hit (second time around is OK, see, #736, but remember now we have phenogrid on other pages like for variants, of which there may be many)

**Comment by kltm** [comment]
Specifically for phenogrid, as an alternative/additional approach, what about warm-ups and caching? My understanding is that monarch data is presented at the frequency of a release, which would mean that caching could save an awful lot of time total versus still having to make an attempt every time.

As well, giving more cache to the Solr server, or putting a caching proxy in front of it (as we did in early AmiGO configurations), can help give a speed boost.

**Comment by cmungall** [comment]
The calls phenogrid makes to owlsim are cached (#736), not sure what you mean by warmups

**Comment by kltm** [comment]
Warm-ups could behave like a spider. Maybe starting with top pages and just working around; bonus points for warming a page's children in anticipation for a future visit. Again, supplementary approach if phenogrid needs the time it does (can parts of the different computations be cached, or does it need to work as a whole?) and is a problem for the user experience.

**Comment by kshefchek** [comment]
I've updated the pages so that the golr tables and phenogrid will only load when clicking the tabs.  Things are working but we've lost the phenogrid ajax loader, see #813. @cmungall please close if this is sufficient.

**Comment by cmungall** [comment]
nice!

![Uploading Screen Shot 2015-07-13 at 10.36.30 AM.png…]()
