### ISSUE TITLE
Restore counts on tabs in new molr-enabled pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#739]
Currently the user has to click on a tab to see if there is any data there.

The strategy here is dependent on #738 - if do an initial solr query for every tab in advance then we should have sufficient info to populate numbers.

However, a better strategy would be to launch a distinct molr query with the subject query set to the ID and `&rows=0&facet=true&facet.field=subject_category` which should give the numbers for each category/tab.

Note: this will be annotation count, not entity count. But this is no different from the legacy interface

**Comment by kltm** [comment]
(Naturally doing this with the API rather than manipulating the URL directly.)

**Comment by kshefchek** [comment]
Counts restored.  These are the counts coming back from the golr document using the API, so it will be number of associations rather than unique number of x (where x is phenotypes, diseases, etc.)  It's the same number that shows up in the paging widget if you were to explore a single table.  Please reopen if this is not the desired behavior.

**Comment by cmungall** [comment]
I'm opening for further discussion. It looks like you did this via server side golr calls. This increases the page latency and seems inefficient the same calls get made on the client

**Comment by kshefchek** [comment]
@cmungall the calls on the server side do not return data, only the result and facet counts, so they should be a bit quicker than the calls on the client.  However, yes we could just get these counts when we get the data on the client side.  But that would rule out lazy loading of tabs, unless we want to have this initial call on the client and then load the data when clicking on the tab.  Let me know the desired behavior and I'll implement.

**Comment by cmungall** [comment]
Assuming any performance hit is acceptable for now, punted to 2015-09

**Comment by jmcmurry** [comment]
#738 now closed; I believe this ticket can be too. Please reopen if I'm mistaken
