### ISSUE TITLE
Handle IDs with underscore rather than colon

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#741]
Pages with an underscore instead of a colon display different results, for example:

http://beta.monarchinitiative.org/disease/OMIM_255800
vs
http://beta.monarchinitiative.org/disease/OMIM:255800

Should we forward to the colonized version of the ID? cc @cmungall

**Comment by cmungall** [comment]
Yes, forward to the CURIE, we're all CURIEs now.
