### ISSUE TITLE
Customize molr table and facets for different pages/tabs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#743]

**Comment by cmungall** [comment]
The more I think about this, the less I like the idea of cloning and editing the derived file. There is too much repetition, we should strive for DRY

Instead I think we should have a very small yaml file for each page-tab combo that overrides fields in the parent generic oban-config.yaml. We would typically override `result_weights` and `filter_weights` (for columns and facets) and then override the description field for a small number of fields.

For example, for gene-phenotype would would omit the subject, subject category and subject_taxon from the weights, as these are fixed  (field defs can stay in the file, they are harmless).

We would also override the desc of Object to be Phenotype.

**Comment by kshefchek** [comment]
I've added a script to merge two yaml configuration files, for example [single-tab](https://raw.githubusercontent.com/monarch-initiative/monarch-app/7036a0ad949/conf/golr-views/single-tab/gene-phenotype.yaml) and the [oban config](https://raw.githubusercontent.com/monarch-initiative/monarch-app/7036a0ad9/conf/golr-views/oban-config.yaml),  as well as updated the webapp and client side script to allow us to pass different golr views from server to client, see 724a66b, fcebbd5, and 7036a0a.

The merge script is just a wrapper over Seth's merge subroutine in confyaml2json.pl with some lines added to merge the fields list.

I've also added a shell script that wraps this merging with the JSON conversion.  I've just tested it on the Gene pages with the phenotype tab with @cmungall's file above, but will add the rest today.

**Comment by cmungall** [comment]
Fantastic, let's take this as far as doing an example tab on one of the beta pages, then close this ticket (and open up new ones for specific tabs as needed)

**Comment by kshefchek** [comment]
@cmungall sounds good, will wait for golr to come back up and will close.

I've written another script (uncomitted) to automate the process of renaming the subject and object column for each tab.  We could also incorporate the filters if they are repeated across tabs, but I'm guessing this will take some manual edits.

**Comment by cmungall** [comment]
hmm not sure about the level of automation here

**Comment by kshefchek** [comment]
I just wrote a simple perl script to generate the basic structure of these tab specific yaml files, see [script](https://github.com/monarch-initiative/monarch-app/blob/master/scripts/make-tab-yaml.pl) and [wrapper](https://github.com/monarch-initiative/monarch-app/blob/master/scripts/make-all-tab-yamls.sh).  We'll still need to manually tweak these for each table.  All of the descriptions are still generic as well.
