### ISSUE TITLE
Customizing facet UI widget shown in molr view

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#744]
Assumes #743 is completed (i.e. we have configured _which_ facets get shown on LHS)

Some of these are low priority and negotiable, and some may replicate what ison the amigo tracker. This is just to give @kltm and @kshefchek information to figure out if existing widget can be used or a new one would be better
## Cosmetic
- Total NNN seems redundant
- Remove free text filter (many GO users want this gone too)
- If no facets have been selected:
  - Remove text "no current user filters".
- If facets have been selected:
  - Replace text "User filters" with a term that is less architecture-exposing, e.g. just "filters"
  - Use the description field rather than underscore-separated field id in the display
- Remove "your search is pinned to the following filters" box (this is redundant with the fact that we know we are in tab T for page P)
- Remove "nothing to filter" text when there are no facet values; grey out box?
- Allow facet widget to be collapsed?
## Harder
- show hierarchy in facets - this will definitely be synced with amigo and may require solr5
- bar charts (or pie charts fur mutually disjoint) for subset of facets 
- combine facets with phenogrid

**Comment by kshefchek** [comment]
+1 for removing the total number in the filter widget.  We just need to add a ajax loader to the paging widget.

**Comment by kltm** [comment]
IIRC, you're going to want to pull the spinner out into its own widget rather than trying to embed it elsewhere.

**Comment by jmcmurry** [comment]
I believe the consensus was to move toward a custom faceting approach in the fullness of time, so I will provisionally close this bbob-widget-specific ticket. Please reopen and clarify if needed.
