### ISSUE TITLE
model subject/object inverted?

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#747]
on this page:
http://beta.monarchinitiative.org/disease/DOID:14330

it seems that the cell line "model" is the object rather than the subject of the association.   is that expected?  i would expect the cell line to be the subject, and the disease to be the object,  but it's the other way around.   is that at the golr loading level, @ccondit, or interface @kshefchek ?

**Comment by kshefchek** [comment]
The data is directly from golr, so this is probably occurring when that data is loaded into golr.

**Comment by ccondit** [comment]
We originally setup the disease as the subject and the model as the object. I can easily switch them around if that makes more sense.

**Comment by ccondit** [comment]
Update the config but will require a Golr reload.
