### ISSUE TITLE
Add orthologs back onto molr-enabled gene pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#748]
May required golr loading changes

**Comment by cmungall** [comment]
Ensure #667 is ported back in

**Comment by kshefchek** [comment]
The gene pages should have an ortholog tab generated from the golr tables, see http://beta.monarchinitiative.org/gene/NCBIGene:6469

**Comment by cmungall** [comment]
No data in the tab

This could be an ID mapping issue; also we may need to make sure we populate reciprocally

**Comment by cmungall** [comment]
See also #751 - the MGI page shows orthologs to the ENSG, but the ENSG page does not have reciprocal

**Comment by kshefchek** [comment]
It is likely a data ingest (biogrid or panther) issue, I'll take a look and assign there once I have can gather more info.

**Comment by cmungall** [comment]
Also: tab should be called "Homologs" (orthology is a subclass of homology). Consider changing the variable names in the code too

**Comment by cmungall** [comment]
Evidence source should be: Panther?

**Comment by nlwashington** [comment]
For human genes, Panther curates to ENSEMBL.  So, that means we need to have xrefs in most other sources between ENSEMBL and NCBIGene.  But, those are missing, and I only discovered this a couple days ago.  This is traced to the fact that both NCBIGene and BioGrid are missing the ENSEMBL id mappings.  Of 50K human genes, only 22K have ENSEMBL id xrefs.  I've contacted their help lists and waiting to hear back.  We need to look into getting the xref mappings from ensembl directly next.

**Comment by kshefchek** [comment]
We're getting some data back now, but it seems some data is still missing, see http://beta.monarchinitiative.org/gene/NCBIGene:6469

**Comment by nlwashington** [comment]
We need to materialize both directions of relationships for homology in golr.  @ccondit to implement.  So, even if the pattern matches:
 S  homologous_to O

we need to add S and O as both a subject and object.

**Comment by cmungall** [comment]
Looks like this is done
