### ISSUE TITLE
Add pathways back into molr-enabled pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#749]

**Comment by kshefchek** [comment]
All pages should have a pathways tab, we just need to update with the correct category and filters.  I think right now they are set to filter on process.

**Comment by kshefchek** [comment]
pathway tabs are working now

**Comment by cmungall** [comment]
Need to fix linkouts (apologies if this is already a separate ticket; if so re-close and link to from here)

e.g. http://beta.monarchinitiative.org/pathway/REACT:6900
