### ISSUE TITLE
jumbotron navigation

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#75]
jumbotron should stay fixed in position, even if the page is scrolled .

**Comment by cmungall** [comment]
do you mean the info piece at the top of the page?

**Comment by harryhoch** [comment]
yes
On Jan 27, 2014, at 5:37 PM, Chris Mungall notifications@github.com wrote:

> do you mean the info piece at the top of the page?
> 
> —
> Reply to this email directly or view it on GitHub.

---

Harry Hochheiser
University of Pittsburgh
Department of Biomedical Informatics 
harryh@pitt.edu         412 648 9300

**Comment by sarahjkim** [comment]
I personally think that the jumbotron/info piece should not be fixed. It takes up a lot of room on most pages, and users should be able to scroll away from it to see more content. But if everyone else wants it fixed, that can be easily done.

**Comment by cmungall** [comment]
How about we make this change on a separate branch? That way we can do a visual comparison and decide whether or not to merge in

**Comment by harryhoch** [comment]
I'm all for the notion of direct comparison of design/layout ideas. Once the dust settles a bit, i will try to suggest some possibilities for iterative revisions...
