### ISSUE TITLE
Verify taxon fields

### ISSUE THREAD

**Issue by ccondit** [monarch-initiative/monarch-legacy#750]
Looks like something is wrong with calculating the taxon connections in Golr. There are plenty of mouse taxon (in both the subject and object) and 56 human taxon in `object_taxon` but that's it.

To find the taxon we follow this pattern:

```
(subject|object)-[:subClassOf|type|part_of|RO_0002162]->(taxon)
```

Should this be updated?

/cc @cmungall

**Comment by cmungall** [comment]
The pattern looks good to me

**Comment by ccondit** [comment]
I don't see this pattern for http://www.ncbi.nlm.nih.gov/gene/388552, for instance.

**Comment by nlwashington** [comment]
i think it should be:

<pre>(subject|object)-[:subClassOf|type|BFO_0000051!|RO_0002162]->(taxon)</pre>
