### ISSUE TITLE
MGI gene pages failing

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#751]
E.g. http://beta.monarchinitiative.org/gene/MGI:1333812

**Comment by kshefchek** [comment]
I can't get the golr service to load, although I may be behind a firewall.  It's possible @ccondit is reloading the tables at the moment.

**Comment by ccondit** [comment]
This works for me:
http://geoffrey.crbs.ucsd.edu:8080/solr/golr/select/?q=subject_closure%3AMGI%5C%3A1333812&version=2.2&start=0&rows=10&indent=on

(no firewall).

**Comment by kshefchek** [comment]
okay, must be a firewall issue for me, I'm on a guest network.

**Comment by kltm** [comment]
Is this a dev/testing thing only, or do the production servers also use non-standard ports? If so, this is a fairly common issue that should probably be addressed in a separate item.

**Comment by kshefchek** [comment]
Our production servers are also on ports 8080 and 9000, should we break that out into a separate issue?

@cmungall does this page work for you now?

**Comment by cmungall** [comment]
works now
