### ISSUE TITLE
Redirect if category is incorrect

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#757]
Example:
beta.monarchinitiative.org/gene/MGI:3894845 

This is actually a variant but it is treating it as if a gene. SG should hold the category

**Comment by kshefchek** [comment]
@cmungall do you remember where you found this link?  We should also figure out why this is being categorized as a gene in the solr index.

**Comment by cmungall** [comment]
I don't recall if I arrived there or if I was manufacturing perverse URLs for the fun of it, sorry.

**Comment by kshefchek** [comment]
I've added a route that reroutes an ID to the appropriate category, for example:

http://beta.monarchinitiative.org/resolve/ClinVarVariant:159648
http://beta.monarchinitiative.org/resolve/HP:0006645

I've also added some behave tests to test the url forwarding functionality.  This should work for all IDs but models, which don't have a category at the moment.

**Comment by kshefchek** [comment]
I think we can close, but perhaps we should change the route naming, @jmcmurry mentioned maybed /id/:id instead of /resolve/:id

**Comment by jmcmurry** [comment]
Having slept on it, I'm fine with the /resolve/:id. However I do think we need to think about external resolution [monarchinitiative.org/resolve/RRID:MGI:3894845 --> MGI page for mouse] as well as longer term internal resolution/redirection for our own pages eg. monarchinitiative.org/resolve/MGI:12345 --> monarchinitiative.org/variant/MGI:3894845. Would those two scenarios live under different resolving namespaces? Would the prepending of the RRID alone be adequate to signal that the traffic should be directed elsewhere? What about metadata pages? These are pretty big questions that we should think carefully about before implementing and advertising. @mellybelly?

**Comment by jmcmurry** [comment]
both resolve and the bare id now work
