### ISSUE TITLE
need licenses on everything

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#762]
We need to make sure we are consistent and clear about our licensing and attribution in all parts of the system. Julie, your first task!

**Comment by jmcmurry** [comment]
Yay! Do you have a license preference or is choosing one part of the task?
Sometimes of course dependencies restrict the choices, but, in a blue sky
scenario?

**Comment by jgrethe** [comment]
The license choice would partly be driven by OHSU’s policies (as the prime institution) and what was written into the original data sharing plan for the proposal. 

Cheers,
Jeff

**Comment by kltm** [comment]
Would this be for data and/or code? I'd assume that the most permissive licenses available (CC-BY 4.0 and 3-clause BSD) would be the default stance. Tagging @cmungall .

**Comment by jmcmurry** [comment]
This is a duplicate of https://github.com/monarch-initiative/monarch-app/issues/636
