### ISSUE TITLE
link for noto from search doesn't work

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#766]
i searched for "noto" in the search box and hit enter.  (did not select from autocomplete.)

i clicked on the link to the one that matched lowercase "noto".

it sent me to this link:
http://beta.monarchinitiative.org/gene,sequence%20feature/NCBIGene:30260

notice that it puts two types before the gene id.  so it won't resolve.  it should probably be just a gene.

**Comment by kshefchek** [comment]
The current behavior is to create a URL based on the category returned by SciGraph, which in this case is a list.  We could fix this on the server (autocomplete) or the client script search_form.js.  However, is there ever a case where a user might want to pick one category over the other?  We would need some intermediate page or display that allows a user to pick which page to go to.

A quick fix would just be to filter out 'sequence_feature' and any other non-supported categories.

**Comment by kshefchek** [comment]
Correction, this only affects search as autocomplete filters on gene, disease, phenotype, and genotype.

**Comment by kshefchek** [comment]
The original bug is fixed so I'll close the ticket.  Please reopen or create a new ticket if we need support for ambiguous categories.
