### ISSUE TITLE
Golr on Geoffrey out of heap space

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#769]
Queries are returning HTTP Status 500 - Java heap space java.lang.OutOfMemoryError: Java heap space, cc @ccondit and @llui

**Comment by ccondit** [comment]
Restarted Solr for now. @llui - any thoughts on a more permanent solution?

**Comment by llui** [comment]
I'll increase the heap space allocated to the JVM.  Let me know when I can restart GOLR on geoffrey.  I'd like to do the same to sirius as well(production).

**Comment by llui** [comment]
Heap has been increased on both Solr servers.  From 128MB to 1GB.

**Comment by kshefchek** [comment]
It appears I've taken down the geoffrey instance in testing, could I get a reboot?  No rush as I've switched beta to sirius for now.

**Comment by ccondit** [comment]
Should be up now
