### ISSUE TITLE
Create separate configurations for dev and production

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#77]

**Comment by cmungall** [comment]
Left open, until we can switch URLs in prod conf to prod URLs

**Comment by yuanzhou** [comment]
My commit of fixed bug 77 refers to the bug 77 in monarch-initiative/phenogrid repo, not this repo. 

https://github.com/monarch-initiative/phenogrid/issues/77

Since the phenogrid in monarch-app repo is a duplicate of the monarch-initiative/phenogrid repo's master branch.
