### ISSUE TITLE
Run tanuki on beta site

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#773]
Will require some updates to [tanuki](https://github.com/kltm/tanuki) to crawl over client generated content, cc @kltm.

**Comment by kltm** [comment]
This will, unfortunately, have to be a low priority for the time being. Probably the easiest way to do it would be to use Armed Bear to get access to PhantomJS or similar.

**Comment by kshefchek** [comment]
I've ran tanuki a few times and we're not getting many errors, just on legacy pages and external links to GO Phenotype links, for example http://purl.obolibrary.org/obo/GO_0016049PHENOTYPE on http://beta.monarchinitiative.org/phenotype/GO:0016049PHENOTYPE

However, we're not getting much coverage of our site with all of the client side content, so take these results with a grain of salt.  Will close for now as I don't think we'll be able to update tanuki for this release.

**Comment by kltm** [comment]
Just to verify, you're using both internal and extra crawling agents?

This is now an open issue here: kltm/tanuki#1
Pull requests welcomed.

**Comment by kshefchek** [comment]
@kltm that's correct (if you mean external)

**Comment by kltm** [comment]
True.

**Comment by kshefchek** [comment]
It also might be tricky since we don't load the GOlr tables until you click on a tab, but it would be easy to remove this on a branch and use that to test.

**Comment by kltm** [comment]
Again, it might be fine, but that would depend on how many simultaneous connections are allowed and how many tabs there are. Anyways, it's always to test the application as-is, rather than having a special branch--the tanuki agent would have to be smart enough to do these things.
