### ISSUE TITLE
missing jquery.min.map (jQuery)

### ISSUE THREAD

**Issue by kltm** [monarch-initiative/monarch-legacy#78]
On many jQuery actions, the server throws an error like:

Wrapped java.io.FileNotFoundException: .../local/src/git/monarch-app/js/jquery.min.map (No such file or directory)

It seems to be a minor annoyance that will be fixed in the future:

https://stackoverflow.com/questions/18365315/jquerys-jquery-1-10-2-min-map-is-triggering-a-404-not-found

However, the server should not be throwing uncaught exceptions.

**Comment by sarahjkim** [comment]
I realized that we have been hotlinking to files of bootstrap.js and bootstrap.css instead of including them in our local files. This may have caused the problems? Is there a reason we are hotlinking? I changed this in the most recent commit, but we can undo easily if there was a reason.

**Comment by kltm** [comment]
I don't think that's related unless they have recently changed the way they build packages. That said, there is little reason not to have them local--it guarantees minimal turnaround and is one less dependency on a remote resource.
