### ISSUE TITLE
Display of anonymous variants on gene page

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#784]
variant tab here: 
http://beta.monarchinitiative.org/gene/ENSEMBL:ENSG00000157168

The anonymous variants recapitulate what is in the disease tab (semantically, the disease tab is about anonymous variants anyway). The display of anon variants is possibly a bit confusing "some...". Additionally, the IDs look like what happens when you stringify a blank node in the OWLAPI; however, when you follow a link you do get to a page with a label, but not much else: http://beta.monarchinitiative.org/variant/_:genid1079105

perhaps the simplest thing is skip all blank nodes in a subject or object position when generating golr? They would still be used as intermediates in cypher queries of course. Would we lose anything this way?

**Comment by jmcmurry** [comment]
One thought for the blank nodes would be to provide additional information in some kind of hover over or pop-up rather than in its own page. This could reduce the likelihood of 404s from Address Bar Copy (ABC)

**Comment by cmungall** [comment]
Looks like this was fixed, no more blank nodes

Like the hover but no need in this case

**Comment by cmungall** [comment]
http://beta.monarchinitiative.org/model/Coriell:AG00780 -- variants tab, there are "some..." links

**Comment by kshefchek** [comment]
Changing the golr load probably isn't doable for this release, but I can update these so that they do not link to a variant page.

**Comment by kshefchek** [comment]
Disabling internal linking to blank nodes with a829a692a0a1c87fd45fa975fe582a69db01c723

**Comment by jmcmurry** [comment]
@cmungall  Which is the desired behavior?
1. Show rows corresponding to blank nodes, but do not link the text from "some sequence alteration on ...". This is what is happening now on beta.
![screen shot 2015-10-13 at 11 02 08](https://cloud.githubusercontent.com/assets/3658863/10463653/9c219e1a-719a-11e5-8662-cc77f31d275a.png)
1. The rows corresponding to blank nodes should not be shown at all.

**Comment by nlwashington** [comment]
if we don't show the blank noes at all (even without variation), we may occasionally loose some useful annotations.  the labels are generated by me; is there something else you'd like as an alternative?

i think in the case of the "some sequence alteration on chr2"... that one we really don't know what the cause is; all we have is the karyotype information that we know affects chr2.

**Comment by jmcmurry** [comment]
@nlwashington These are good points; I think it looks fine as it is, but just wanted to understand the scope of the ticket to see whether it could be closed. Sounds like the answer is yes.

**Comment by nlwashington** [comment]
also, FYI, in this case above, I have not finished the karyotype parser to get all the parts, so I am unable to make a more-atomic label other than figuring out that there is some kind of affect on a given chromosome.  it will be better addressed when https://github.com/monarch-initiative/dipper/issues/77 is complete.
