### ISSUE TITLE
Review choices of gene/disease/etc spotlights

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#785]
Example:

http://beta.monarchinitiative.org/gene   gene spotlight, nrg1
http://beta.monarchinitiative.org/gene/NCBIGene:796461  follow homology links for human to
http://beta.monarchinitiative.org/gene/ENSEMBL:ENSG00000157168

this gene lacks a label. not sure if this is systematic with ensembl or a one-off. Either way, we should review our choices of spotlights and make sure that they are not just our favorite biology but they actually don't shed light on problematic features or data

**Comment by jmcmurry** [comment]
http://beta.monarchinitiative.org/gene/NCBIGene:796461 is just churning with no result

**Comment by kshefchek** [comment]
@jmcmurry the tabs should be working now

**Comment by nlwashington** [comment]
i think the expected behavior is that if there's no label for a node, then it should look for equivalences, and display one of them as the label.  and all labels and synonyms for all equivalents should show up for any identifier in the "overview" tab.

**Comment by cmungall** [comment]
Re: equivalencies, see #852

**Comment by kshefchek** [comment]
Model Spotlight: kcnk5b<ty86d>/kcnk5b<+> [n.s.]; cx43<MO2-cx43 (n.s.)>
Goes to page: http://beta.monarchinitiative.org/model/MONARCH:ZDB-GENO-080206-1_ZDB-GENE-991105-4_ZDB-MRPHLNO-080818-1_ which has nothing on it, will replace with a better ID
