### ISSUE TITLE
Provide GOlr results as JSON download

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#786]
Right now the JSON documents are sparse given all of the data is generated on the client side.  We need to add some functionality to generate this data server side and provide as a JSON blob.

**Comment by cmungall** [comment]
not sure what you mean...

**Comment by kshefchek** [comment]
On the legacy pages we allow people to download a JSON object that contains information on the page, would we not want that on the new pages?  Or should we ditch this in favor of a tsv or csv file and json-ld down the line.

**Comment by kltm** [comment]
Was the JSON download stuff actually used? I always thought it a bit odd.
Either way, the manager supports both TSV and and JSON (raw response) outputs.

**Comment by kshefchek** [comment]
Should we get rid of the JSON buttons and replace them with TSV?

**Comment by cmungall** [comment]
@kltm - We had some prototype users at the NCBO hackathon, but I think it's OK to abandon for now

@kshefchek - yes, tsv for now (and possibly the flat solr json too, dog food principle). We can certainly point at other options too, e.g. SG
