### ISSUE TITLE
Installation error on Macbook

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#787]
It was find after I ran `sudo ./install.sh`, but I got the following error message after running `sudo ./start-server.sh`

![screen shot 2015-07-02 at 10 20 56 pm](https://cloud.githubusercontent.com/assets/195873/8491536/d9876f92-2108-11e5-910e-f7615b240a4c.png)

**Comment by kshefchek** [comment]
Could you try without sudo? I wonder if this installs ringo in a different directory.

**Comment by cmungall** [comment]
What was the output of `sudo ./install.sh`?
