### ISSUE TITLE
Phenogrid HPO expansion error 

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#788]
@ccondit

It seems that we are having troubles with the HPO functionality.  The URL that Vincent used was the following:

http://beta.monarchinitiative.org/neighborhood/HP_0003273/2/out/subClassOf.json, but this link returns a json with error message:

{"code":500,"message":"There was an error processing your request. It has been logged (ID c85fe7ed0ef5499f)."}

Has this been changed?  When is the appropriate URL?

When I tested the monarch-app, I saw this error in the console

```
FETCHING: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/HP_0000327.json data={"depth":"10","relationshipType":"subClassOf","direction":"out"}
RESULT: [object Object]
STATUS: 500
```

I'm guessing this might be the reason why the HPO tree is not showing up after clicking the expend button.

**Comment by kshefchek** [comment]
this should work: http://beta.monarchinitiative.org/neighborhood/HP_0003273/2/OUTGOING/subClassOf.json

in/out was changed to INCOMING and OUTGOING (case sensitive)

**Comment by nlwashington** [comment]
looks like the query should be formulated like (using whatever server is appropriate:

http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/HP:0003273?depth=2&blankNodes=false&relationshipType=subClassOf&direction=OUTGOING

in the future, you can test the services here:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/docs/

please close if this solves your issue.

**Comment by yuanzhou** [comment]
Thanks for the quick response. Problem solved! And it also looks like some phenotype ids are prefixed with "OBO:" now, so I had to change the hard-coded part in phenogrid by adding this "OBO:" as a filter. Mike helped me figure this out. Credit goes to @davism84
