### ISSUE TITLE
Remove ontoquest from unit tests

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#789]
We eventually need to remove any testing of resources that we're no longer using.  To start we could remove ontoquest as ontologies are driven from SciGraph even on the production site.

We're currently failing because it appears ontoquest stage is down, failing at this call:
http://nif-services-stage.neuinfo.org/ontoquest-lamhdi/concepts/term/HP_0003325

**Comment by cmungall** [comment]
Let's remove it and create behave tests in its place. We'll get @jmcmurry set up with behave this week.
