### ISSUE TITLE
Buggy model viewer

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#79]
I think the line height is strange in the model viewer: http://tartini.crbs.ucsd.edu/disease/OMIM_270400 (Model tab).
![screen shot 2014-01-28 at 2 56 51 pm](https://f.cloud.github.com/assets/4628853/2024832/a037ddae-886f-11e3-9ca7-d79bc81b1bb6.png)

Not completely sure what is wrong.

**Comment by harryhoch** [comment]
fixed
