### ISSUE TITLE
Phenotype URLs should not allow non-phenotype classes

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#792]
Example:
http://beta.monarchinitiative.org/phenotype/HP:0012823

```
Phenotype: Clinical modifier

This subontology is designed to provide terms to characterize and specify the phenotypic abnormalities defined in the Phenotypic abnormality subontology, with respect to severity, laterality, age of onset, and other aspects
```

**Comment by kshefchek** [comment]
@cmungall were you pointed to this URL from another page?

**Comment by cmungall** [comment]
I navigated here from the ontology hierarchy in the overview tab. So fixing that may have the side effect of making this ticket moot.

**Comment by kshefchek** [comment]
Which page had this in the overview tab?

**Comment by cmungall** [comment]
http://beta.monarchinitiative.org/Phenotype/HP:0000707
UP->
http://beta.monarchinitiative.org/phenotype/HP:0000118
UP->
http://beta.monarchinitiative.org/phenotype/HP:0000001
DOWN->
http://beta.monarchinitiative.org/phenotype/HP:0012823
