### ISSUE TITLE
Review field selections for each tab in each page

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#794]
Need to review the choices for each field x tab x page combo; both column headings and filters.

The scope of this ticket is limited to 
1. Should the field by included in this tab for this page? If the field is always blank or always the same (e.g. "disease taxon") then it's a candidate for exclusion
2. Is the label for the field appropriate? Shorter labels are preferred to avoid ugly overflow on column headings, so long as no ambiguity is introduced. Also exposing architecture is to be avoided. E.g. never use the word "closure"

Assigned to @kshefchek to do work with @jmcmurry @mellybelly @nlwashington (after the first few commits tracked in this ticket can transfer to @jmcmurry)

**Comment by cmungall** [comment]
check
- columns in the right order
- new coumns needed? If so, file a ticket
- links for each value go to a non-empty page

**Comment by nlwashington** [comment]
pathway tab on disease page column order doesn't make sense...

the pathway should be involved in the disease...  so the columns should be:
pathway | relationship | disease | evidence | source
(remove taxons - don't think taxon makes sense here right now)

also, need to show relationships in relationship column of disease-gene tab - it's confusing without it.

**Comment by kshefchek** [comment]
@nlwashington in regards to relationships, are they in the golr document but not showing up in the table?

**Comment by nlwashington** [comment]
some associations just don't appear to make sense unless there's more information.  for example, http://beta.monarchinitiative.org/gene/MGI:1914267 lists apparently contrasting phenotypes.  listing either a description (attached to the associations in the evidence), and/or the relationships/elements that are part of the inference would help here.  

maybe what would help is to list the thing that is the annotated entity that is connected to the phenotype.  so on the gene pages, the genotype is what the phenotype is attached to.  there could be a column that lists "inferred from", and then would list whatever is the direct connection to the phenotype.

**Comment by nlwashington** [comment]
disease page:
http://beta.monarchinitiative.org/disease/DOID:0050568

phenotype tab - either the taxon columns should not be shown or they should not be shown if all the values are blank (or the same)

**Comment by cmungall** [comment]
See also #757

**Comment by nlwashington** [comment]
for relationships, they are now in the "evidence_graph".

**Comment by kshefchek** [comment]
In regards to presenting relationships via the evidence graph, should we break this out into a new issue and punt on it for this release?

**Comment by nlwashington** [comment]
on model (genotype) pages:
http://beta.monarchinitiative.org/model/Coriell:ND00094
the column headers are backwards from the data on disease tab.

**Comment by cmungall** [comment]
'phenotype taxon' also needs to die

e.g.
http://beta.monarchinitiative.org/variant/MGI:2652946
phenotype tab

**Comment by cmungall** [comment]
Also: variant page needs a gene tab, e..g http://beta.monarchinitiative.org/variant/MGI:2652946

**Comment by nlwashington** [comment]
on a gene page, the genotype tab only really needs the genotype column, and maybe the genotype taxon.  all other columns are unnecessary.

**Comment by cmungall** [comment]
Let's take care of the last request and then call this done

**Comment by kshefchek** [comment]
@nlwashington do we want evidence and source as well or just genotype and taxon?

**Comment by cmungall** [comment]
We still have 'disease taxon' in http://beta.monarchinitiative.org/disease/DOID:0060072 (pheno tab). This needs to go

**Comment by kshefchek** [comment]
Closing per https://github.com/monarch-initiative/monarch-app/issues/794#issuecomment-125693731, please reopen if there are any other issues.
