### ISSUE TITLE
no genotypes or phenotypes for MGI:2386599

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#798]
http://beta.monarchinitiative.org/variant/MGI:2386599

but according to http://www.informatics.jax.org/allele/MGI:2386599

it should have MGI:3796842 and MGI:3796843

may be data or interface... @ccondit or @kshefchek

**Comment by nlwashington** [comment]
phenotypes should probably be inferred from the genotype.  @cmungall is it safe to go ahead and do this with a bit of logic in the cypher query, like if there is only one indicated variation in a genotype, then we can infer the phenotype to be due to the variant?

**Comment by kshefchek** [comment]
I've created a labs page to allow us to explore the golr data without any filters to see if any missing data is the result of a filter being placed on a tab.  The page is routed to /labs/golr/:id but it seems our beta site is not updating (will touch base with @llui today).

For this ID the only thing I see if a variant is_allele_of Fmn1, which we should probably include on the page somewhere (the overview tab maybe?), but no phenotypes or genotypes.

**Comment by nlwashington** [comment]
@jmcmurry you could write a test for the genotypes.
@ccondit we should test with the new golr load.

**Comment by nlwashington** [comment]
this is working now.
