### ISSUE TITLE
phenogrid stickytooltip is breaking gene pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#799]
E.g. http://beta.monarchinitiative.org/gene/NCBIGene:211323

![screen shot 2015-07-08 at 12 22 29 pm](https://cloud.githubusercontent.com/assets/50745/8579887/18da009e-256c-11e5-8fc4-7a3e2ee35eeb.png)

**Comment by harryhoch** [comment]
@yuanzhou, please coordinate with Kent if necessary

**Comment by kshefchek** [comment]
@harryhoch this was just me breaking things when removing the stickytooltip.css from the webapp, accidentally removed stickytooltip.js file from the pages as well, but this has been added back.

**Comment by kshefchek** [comment]
fixed with c2e18f6ac20f017b52c27bb70b8002ebbecc42cd
