### ISSUE TITLE
Add csv export to results pages

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#80]
For example, most users would want a csv export from a page like this:

http://tartini.crbs.ucsd.edu/analyze/phenotypes/?target=ZFIN&input_items=HP_0001252,HP:0012470,HP_0001212,HP_0001782,HP_0011832,HP_0000430,HP_0012510,HP_0000446,HP_0007598,HP_0012428&limit=100

@harryhoch @nlwashington not sure who to assign to.

**Comment by harryhoch** [comment]
This is probably something could be generically done for most data types, using an extended version of the "formattedResults" call in webapp.js

**Comment by cmungall** [comment]
it would have to be done on a view by view basis, as there is no one way to turn a tree to rows.

Or we could just redirect straight to the flat view in NIF

**Comment by mellybelly** [comment]
It would be great if we could enable some sort of data export function for our release. @cmungall @nlwashington is this doable?

**Comment by mellybelly** [comment]
@nlwashington leaving this on october release but you can move it if you think it is a stretch.

**Comment by cmungall** [comment]
Succeeded by #758

Comments in this ticket, e.g. _it would have to be done on a view by view basis, as there is no one way to turn a tree to rows._ are no longer pertinent to the new portal, so I am closing this ticket in favor of the new one

**Comment by jmcmurry** [comment]
Phenogrid now has an export as svg option, but I agree that some kind of text export would be better, even if it is json. However, we might want to consider holding off on any more export mechanisms until we deal with the user registration issue. @mellybelly please advise

**Comment by jmcmurry** [comment]
Related to https://github.com/monarch-initiative/impact/issues/15

**Comment by jmcmurry** [comment]
I believe that this can be closed; TSV and JSON are now available. Please reopen if necessary and clarify what needs to be done.
