### ISSUE TITLE
models not found for OMIM:166220

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#808]
on this page:
http://beta.monarchinitiative.org/disease/OMIM:166220

the models tab is empty.

but we should see: Coriell:GM17428 , Coriell:GM17505, Coriell:GM17506

@kshefchek and @ccondit to investigate.  this may come through upon reload

**Comment by kshefchek** [comment]
Filter should be on subject instead of object, fixing now...
