### ISSUE TITLE
how to put the ontology/db source into monarch-app

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#809]
In our various app pages that are populated by golr, we want to be able to show where a given association is defined (such as declared in OMIM or MGI or IMPC or ...).  

This may be complicated by the fact that a given association may be inferred through a more complex graph involving multiple sources.  

We need a place in our association golr schema to put the source of the nodes/edges in any given graph.  What should this be called/look like?

These are now defined (in duckworth) via the isDefinedBy relationship, which can be found on some nodes and all edges.
@ccondit to implement in golr

**Comment by kshefchek** [comment]
I've added the source icons to the golr tables (similar to the legacy tables) with 8453e2bfc4b95f11c1a425f8d9905eb50073da8f
