### ISSUE TITLE
display searched terms when showing results

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#81]
Whenever a user searches for something, the landing page they get to should display their search. Something to the effect of "You searched for 'small ears'". This is especially important for multiple term searches on phenotypes, but applies equally to other pages. It would be great if the display could show the labels, with the IDs perhaps in a hover over. If the user enters IDs, perhaps the inverse could be true, though we'll have to discuss that scenario.

@harryhoch please assign

**Comment by harryhoch** [comment]
I'll try to look at this later today/tonight.

**Comment by harryhoch** [comment]
Partially resolved by https://github.com/monarch-initiative/monarch-app/commit/7d3ca47e260435e06d73e6786c5837dbb1d551b4. Basic term is provided on search page, but no good IDs are currently available for displaying as tooltips.  Similarly, we can't really type in IDs at the moment...

**Comment by cmungall** [comment]
shall we bump this from this release?

**Comment by harryhoch** [comment]
If it's too hard to do something now, I guess so, but it will be hard for people to use/interpret this page..
