### ISSUE TITLE
Restore annotation sufficiency to phenotype tabs

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#811]
The star rating is not visible on beta

When restoring, keep efficiency in mind. Consider adding after page has loaded

**Comment by nlwashington** [comment]
is this related to #821 ?

**Comment by kshefchek** [comment]
This is unrelated, we haven't added the annotation sufficiency box back in to the golr tables as we need to generate this on the client side.

**Comment by kshefchek** [comment]
Do we want to set a limit for number of phenotypes to send to the scoring service?  We may have performance issues with IDs with a large number of phenotypes.  We will also need to update the route to accept a post.

**Comment by cmungall** [comment]
For a generic disease we may have 100ks of phenotype, doesn't make sense here. Can we make it work just for leaves just now?

**Comment by kshefchek** [comment]
Sure, that is doable.
