### ISSUE TITLE
Add content to phenogrid about page on /page/phenogrid

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#814]
We seem to have lost content on the phenogrid about page, compare 
http://beta.monarchinitiative.org/page/phenogrid
to
http://monarchinitiative.org/page/phenogrid

Can we bring back the content that is currently on the production site or is this now out of date?

**Comment by harryhoch** [comment]
@kshefchek, this is all content that comes from the index.html example in the phenogrid repo. Likely to undergo significant revision as we go to the npm-ified' versions, but it's not clear exactly when that change will be complete. 

@yuanzhou , @doctorbud, will we be ready in the next few days to update this page?

**Comment by yuanzhou** [comment]
@kshefchek and @harryhoch, I cleaned up the phenogrid index.html and put instructions into README.md (https://github.com/monarch-initiative/phenogrid/blob/master/README.md), will add more content there in the next couple of days.

What is the purpose of http://beta.monarchinitiative.org/page/phenogrid?

**Comment by yuanzhou** [comment]
Content added and styled.
