### ISSUE TITLE
Make the "compare" tab the first (and default) tab

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#818]
I go to http://beta.monarchinitiative.org/disease/DOID:863
Consider ordering the tabs as follows:
- Compare
- Phenotypes
- Genes
- Genotypes
- Models
- Variants
- Pathways
- Overview

Also, consider making the "Compare" tab the default one.

The combination of these two steps (reordering, and default) would raise the profile of the Phenogrid and provide the user with a more immediate path to entry. (For the following release, we can work on buffing up the "overview" tab to be more engaging and more of a true overview, but that is harder to do for now).

**Comment by cmungall** [comment]
Slight variation: relabel "Overview" to be "Ontology" or "Hierarchy" for P and D pages (as that's what it is). For other pages the info could probably be shifted elsewhere and the tab eliminated.

**Comment by cmungall** [comment]
2015-07-23 call: we agreed to do this for the release

**Comment by yuanzhou** [comment]
http://beta.monarchinitiative.org/disease/DOID%3A5723 

This disease page still shows the compare in the last tab. @kshefchek

**Comment by cmungall** [comment]
Intentional. Disease groupings (lots of phenotypes, slow grid, child nodes) show hierarchy first. Leaf diseases (no children, more compact grid) are grid first
