### ISSUE TITLE
need search disambiguation page

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#82]
eventually (not for the sneak peak) we will need a search disambiguation page, so that a user can type in whatever text they want into the search box, and see a list of results, that they can then click on to take them to other parts of the system.  these could be grouped by "type" (as in gene, genotype, phenotype, disease, etc.)

i don't think that this should be solved by categories in the autocomplete.

for example, we could use such a thing when a user goes to the url for a genotype, but uses an allele id...  since it is ambiguous if they want to see the allele, or if they want to see a genotype that happens to contain that allele.

**Comment by harryhoch** [comment]
We have a JIRA ticket that addresses this issue...
https://support.crbs.ucsd.edu/browse/LAMHDI-221

**Comment by mellybelly** [comment]
also consider how eagle-i and other searches append the autocomplete with the category

**Comment by mellybelly** [comment]
related to #291 
also moving to july release

**Comment by nlwashington** [comment]
closing this for now as we have an working solution.  new tickets should be opened with new requested features.
