### ISSUE TITLE
Annotation profile scoring service not working, HTTP 500

### ISSUE THREAD

**Issue by danielpgross** [monarch-initiative/monarch-legacy#821]
Requests to the endpoint at http://monarchinitiative.org/score are returning HTML output and an HTTP 500, instead of the expected JSON output and HTTP 200.

Here are some example requests that are triggering the behaviour:
http://monarchinitiative.org/score?annotation_profile={"features":[{"id":"HP:0001533"}]}
http://monarchinitiative.org/score?annotation_profile={"features":[{"id":"HP:0004325"},{"id":"HP:0004324","isPresent":"false"}]}

**Comment by nlwashington** [comment]
i am not sure why this is down; i can run production on my localhost and all is well.  @cmungall @llui or @kshefchek does something need rebooting? who has access to the logs?

**Comment by nlwashington** [comment]
but i see that it does fail against our dev instance.  (is our production machine pointing at dev owlsim right now?)

**Comment by cmungall** [comment]
Works on both prod and beta

This ticket should be closed once we have an integration test to prevent this happening again

**Comment by nlwashington** [comment]
@danielpgross has all been stable since the fix?

**Comment by danielpgross** [comment]
@nlwashington yes, things are working fine again. Thank you!
