### ISSUE TITLE
Move +/- filter buttons to left side of filter area

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#824]
The filters are very hard to navigate on a mac as the horizontal scoll bar does not show up in some cases.  A short term solution is moving the buttons to the left side but we should propose a longer term re-design, see http://beta.monarchinitiative.org/phenotype/HP:0002007 as an example.

**Comment by kltm** [comment]
You actually probably want to look into increasing the width of the left column containing the filters. You can see that there is little problem in the AmiGO pages that use it.

The reason they are so small seems to be, at least in part, conflicts with other CSS in the page.

**Comment by kshefchek** [comment]
I think the buttons are smaller due to some css I added.  But should we increase the size of the bootstrap column (from 2 to 3?) Or do you mean another setting.

**Comment by kltm** [comment]
Not a setting, but getting the CSS to allow a wider column for the filters (allowing the buttons to be seen on all cases).

**Comment by kshefchek** [comment]
Closing for now as the widget has been removed and we may consider a larger redesign.
