### ISSUE TITLE
Specific Disease pages not found 

### ISSUE THREAD

**Issue by ybradford** [monarch-initiative/monarch-legacy#825]
Searching for Campomelic Dysplasia, Usher syndrome I get an error message 'Not found. Sorry your page could not be found' 
Campomelic Dysplasia http://monarchinitiative.org/disease/ORPHANET%3A140 
Usher Syndrome http://monarchinitiative.org/disease/ORPHANET%3A886

Possibly related to Orphanet identifiers as I an find a page for Parkinson Disease 1, autosomal dominant http://monarchinitiative.org/disease/OMIM%3A168601
and Diabetes mellitus http://monarchinitiative.org/disease/DOID%3A9351

**Comment by cmungall** [comment]
Looks like this was fixed in the refactor - try these on beta http://beta.monarchinitiative.org

CD:
http://beta.monarchinitiative.org/disease/OMIM%3A114290

Usher:
http://beta.monarchinitiative.org/disease/DOID%3A0050439

**Comment by cmungall** [comment]
@ybradford  - do you want give beta a whirl and see if it works for you?

**Comment by ybradford** [comment]
@cmungall  this looks to be working on the beta site. thanks.
