### ISSUE TITLE
genotype label missing in jumbotron 

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#828]
the genotype label seems to be missing in the jumbotron for:
http://beta.monarchinitiative.org/genotype/ZFIN:ZDB-GENO-000821-1

even though it is available in the golr tables.

i suspect this is because you're populating the jumbotron with the label from the vocab server...but this label will only be available in the data server.

for labels in the jumbotron, i think they should be populated like:
1.  vocab server if the class exists and there's a label
2.  vocab server if the class exists, with a label from an equivalent class if no label exists (perhaps say where the label came from?)
3.  data server if the class doesn't exist on vocab
4.  data server if the class doesn't exist on vocab, with label from equiv class/ sameAs inst if no label exists.

**Comment by kshefchek** [comment]
Right now disease and phenotype pages go to the vocab server, everything else the data server.  Will update with this workflow.

**Comment by kshefchek** [comment]
This should be fixed when we update rosie.
