### ISSUE TITLE
Kabuki syndrome grouping class has no information

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#829]
mondo:

```
 / DOID:4 ! disease
  is_a DC:0000547 ! Kabuki Syndrome *** 
   is_a OMIM:147920 ! Kabuki syndrome ***  [SYNONYM: "KABUK1" (exact)] [SYNONYM: "KABUKI SYNDROME 1; KABUK1" (exact)]
   is_a OMIM:300867 ! Kabuki Syndrome 2 ***  [SYNONYM: "KABUK2" (exact)] [SYNONYM: "KABUKI SYNDROME 2; KABUK2" (exact)]
```

leaf looks fine:
http://beta.monarchinitiative.org/disease/OMIM:147920

but the parent has no info:
http://beta.monarchinitiative.org/disease/OBO:DC:0000547

possible issues:
1. datagraph is out of sync with ontology graph (@ccondit is there an easy way to introspect and check?)
2. something to do with DCs are CURIEs?
3. ...?

**Comment by kshefchek** [comment]
@cmungall okay to punt on this?

**Comment by cmungall** [comment]
we should at least have labels, but now we seem to be missing labels on the leaf nodes too - what's up?

**Comment by kshefchek** [comment]
I believe beta SciGraph is still being reloaded.

**Comment by ccondit** [comment]
SciGraph should be good to go:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/OMIM:147920
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/OBO:DC_0000547

Is this a mismatch about processing CURIEs?

**Comment by kshefchek** [comment]
Beta runs off geoffrey, should I temporarily move it to duckworth?

**Comment by kshefchek** [comment]
Looks like mondo was down during the last load, @ccondit reloading now.

**Comment by ccondit** [comment]
Should be good to go. Geoffrey resolves both IDs now.

**Comment by cmungall** [comment]
Kent, do you know why we're getting an error here?
http://beta.monarchinitiative.org/disease/OBO:DC:0000547

**Comment by kshefchek** [comment]
Possibly because there are no phenotypes.  I think that is the default message when the widget fails.

**Comment by cmungall** [comment]
Hmm, this explains it http://rosie.crbs.ucsd.edu:9000/scigraph/graph/neighbors/OBO:DC:0000547?depth=1&direction=BOTH&project=*   ... 404 from SG

**Comment by cmungall** [comment]
doh, there's no way that URL would ever work, not even a valid CURIE

here's what up. In mondo, the Purl for the class is .../obo/DC_nnnn, no CURIE is declared so we fall back to the generic OBO prefix, making OBO:DC_nnnnn ... but our processing rules in mon-app turn this into a double-colon ID somewhere.

We should investigate this but also add the CURIE
