### ISSUE TITLE
Gene page should show species

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#831]
Should be one hop away in SciGraph?

**Comment by nlwashington** [comment]
yes, in_taxon = RO:0002162.

**Comment by nlwashington** [comment]
hm.  it should be but isn't here:
http://rosie.crbs.ucsd.edu:9000/scigraph/graph/neighbors/NCBIGene:6469?depth=1&blankNodes=false&relationshipType=RO%3A0002162&direction=BOTH&project=%2A
probably is in duckworth, when it's back up.

**Comment by kshefchek** [comment]
I still don't see this information in either duckworth or rosie, should be easy to add it once it's there.

**Comment by cmungall** [comment]
It's on rosie and duckworth, but the relationshipType is RO_0002162 (fragment, not CURIE)

**Comment by kshefchek** [comment]
This could be part of a larger refactor of generating all info on the client side (getting rid of fetchClassInfo, etc.).

**Comment by cmungall** [comment]
It could be part of a refactor... but can we just just have species for now?

**Comment by kshefchek** [comment]
Sure, was meaning to tackle it today.  Do we want it on the overview tab or the jumbotron?

**Comment by kshefchek** [comment]
Added with 6c84b3eb07da397d7162c7472457ccf58a26b369
