### ISSUE TITLE
Autocomplete on genes shows different results from search

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#832]
Search:
http://beta.monarchinitiative.org/search/SH3KBP1

1st 3 are from 3 species, but typing the same string into the search box only gives 2 possibilities in autocomplete

(also: are we getting rid of the site search at the bottom? and can we include taxon?)

**Comment by nlwashington** [comment]
the search results come from the data graph, whereas the autocomplete comes from the vocab.

we are loading only 3 species into the vocab of genes right now; that means that i'm pulling in the other species of genes in the data load (probably panther or something else), but not importing them from ncbigene (which is what we build the vocab from).

i am VERY happy to add more species to the ncbigene load - if you give me the go-ahead i will.   BUT, i don't think that the taxon shows up in the vocab services... not sure how we should go about delivering that... if you want that we either have to include the taxon as a node property, or might have to move to golr serving the ontologies. @ccondit should comment.

**Comment by kshefchek** [comment]
Are we loading human genes into the vocab/ontology graph?  I can't seem to autocomplete on human genes which may be an issue.

**Comment by kshefchek** [comment]
site search removed with c4e71b3c9a8bdc62b4093bd5721c8e58fe73109d

**Comment by nlwashington** [comment]
yes, they should be there.  http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/id/NCBIGene:6469

**Comment by nlwashington** [comment]
and here's autocomplete:
http://geoffrey.crbs.ucsd.edu:9000/scigraph/vocabulary/autocomplete/SHH?limit=20&searchSynonyms=true&searchAbbreviations=false&searchAcronyms=false&includeDeprecated=false

**Comment by kshefchek** [comment]
Looks like a category issue, is there a reason SHH is not being categorized as a gene?

**Comment by kshefchek** [comment]
This was an API issue.  We were filtering out duplicate labels (not sure why) but this has been removed.
