### ISSUE TITLE
Image path and HTML pages path errors on Phenotype Profile Analysis page

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#840]
![capture](https://cloud.githubusercontent.com/assets/195873/8856487/335548f6-3139-11e5-8dcd-439b6f598535.PNG)

http://beta.monarchinitiative.org/analyze/phenotypes/?input_items=MP%3A0001399+HP%3A0006801&mode=search&target_species=all&limit=100

I've fixed the TypeError issue (https://github.com/monarch-initiative/phenogrid/issues/119) for displaying phenogrid on the anaylze results page. But also noticed that the logo and help text popup content are missing. Prob due to the missing `imagePath` and `htmlPath`. We added these two paths for overwriting purpose in `phenogridloader-no-species.js`, @DoctorBud, do you know which file handles the Analysis page? I went to add these two paths in `genotypepages.js` but didn't resolve this issue.

**Comment by DoctorBud** [comment]
Fixed in https://github.com/monarch-initiative/monarch-app/pull/841
