### ISSUE TITLE
minor revisions to home page

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#842]
1. clean up clutter
2. horizontally align bottoms of various regions. 
3. fix slide show

**Comment by mellybelly** [comment]
@DoctorBud can you review low hanging fruit improvements for homepage in next 48hrs?

**Comment by DoctorBud** [comment]
Yes. It's what I was hoping to do anyway. Glad there's a ticket now.

**Comment by cmungall** [comment]
I have mostly been organizing things into the First official release milestone

**Comment by cmungall** [comment]
is this done? if not can we do it OR punt until next release?

**Comment by harryhoch** [comment]
@DoctorBud, what do you think?

**Comment by kshefchek** [comment]
Moving to the September release but feel free to close or move the milestone.

**Comment by DoctorBud** [comment]
I've tweaked the Home Page some more, and have some screenshots to see.

Here's the app on a large screen, with the new Monarch state of the Carousel showing...

Notice that Monarch is underlined with a gray line, indicating it's the currently shown topic.

The 'Learn about Monarch' button will take the user to the About Monarch Page.

Notice that only the right columns are using Panels (rounded rectangles). The Main Event Carousel does not.

I've also reduced the container margin for the page, to yield more above-the-fold real-estate.

Similarly, I reduced the real-estate for the Splash Image.

<img width="911" alt="zoomedout" src="https://cloud.githubusercontent.com/assets/2450553/8970531/0cc61498-35ff-11e5-9cf6-8457b3d4d125.png">

**Comment by DoctorBud** [comment]
Here's the Models tab:

<img width="1008" alt="models" src="https://cloud.githubusercontent.com/assets/2450553/8970695/e668e676-35ff-11e5-99d3-42b8dab6e1f9.png">

**Comment by DoctorBud** [comment]
And the Genes tab, but this time we have a narrower screen and the Monarch tab is displayed on its own line.

<img width="845" alt="genes" src="https://cloud.githubusercontent.com/assets/2450553/8970726/133d49ee-3600-11e5-8ee2-9ffddee514c9.png">

**Comment by DoctorBud** [comment]
Here's the Phenotype tab displayed on an iPhone 6 (Simulator).

<img width="376" alt="phonepheno" src="https://cloud.githubusercontent.com/assets/2450553/8970759/5222a4a6-3600-11e5-8f66-cddb915c86bd.png">

**Comment by harryhoch** [comment]
@DoctorBud, I like this generally, but I'm not sure about the "Monarch" inclusion alongside disease phenoytpes, models, and genes. The concern is that readers might see "Monarch" as being a peer to those other groups, when it's really their sum total.

**Comment by mellybelly** [comment]
Thanks @DoctorBud 
few comments:
I also don't understand the monarch button. do we need the small buttons in the carousel if the big buttons get brought back on the homepage? do we need the carousel?

Advanced search vs "analyze phenotypes" - neither are really a good description. Its not really a search its a compare. Perhaps a "compare phenotypes" title and a little phenogrid or a triptych showing comparisons? I like the description but maybe need to reconcile the title and the button text somehow.
Also this tool is key feature of monarch, maybe move "about"?

There is a duplication in the about on the right and the about in the header strip.

**Comment by DoctorBud** [comment]
Thanks for the feedback.

The 4 items in the About Monarch section were present in the previous version, but were just bullet points. Yes, they duplicate the About items in the navbar menu. I'm fine with deleting them, and therefore that section.

I like the idea of expanding the Advanced Search (renaming it to Compare Phentotypes) and adding a phenogrid image.

I'll lose the Monarch tab and its diagram. I'll restore Welcome to Monarch, which will be outside of the carousel.

We don't need the carousel; I assumed that folks liked it so I tried to preserve it and make it handle the orphaned bar-chart views. I can try out a simple linear list where the user sees all 4 categories and their descriptions and we move the bar charts somewhere.

**Comment by mellybelly** [comment]
I think just a refactoring of what goes where- should about be in the bar or on the right? we have to fill the page somehow. 

I don't love the carousel, i still don't really get that I can't click on the icon. 
I DO like that with the carousel we can highlight some disease, model, etc.

think radically if you like!
I can also make you a picture that shows phenotype comparisons, something like this but just a two-way one, if you prefer over a phenogrid
![image](https://cloud.githubusercontent.com/assets/796636/8971550/6980e152-361f-11e5-934a-043206685c72.png)

**Comment by DoctorBud** [comment]
Right now, the carousel buttons are used as Indicators of the current state of the carousel, and they are used as Controls to position the carousel. It's trivial to make them instead Controls that Launch the user to the final target, but then they'd lose their ability to control the Carousel. Right now, the Launch button is the big dark gray button that has imperatives like 'Understand the Genetics' or 'Find Models of Disease' (the dark gray color can/should be tuned to something more indicative of a button, but something less garish that a Bootstrap Primary Blue, if we decide to retain any of this UI).

The Carousel is arguably valuable because it allows for more content to be displayed and revealed without scrolling.

**Comment by DoctorBud** [comment]
Here's my 'short-term' view...

The big advantage of a Phenogrid image (similar to the bar charts) is that even when it is scaled down to illegibility, most people know that it represents some sort of info visualization. Your diagram above may require some fiddling to survive downscaling. An abstraction or simplification might survive scaling enough to still be meaningful and/or intriguing.

I'd advocate the use of a Phenogrid image (I'd use a 3-species comparison, which is more colorful) here because it's something I can do without bothering you, and it's consistent with the other screenshots of actual Monarch features.

**Comment by cmungall** [comment]
+1 to @DoctorBud's comments

**Comment by DoctorBud** [comment]
Here's what I have using a Phenogrid 3-way (I've abandoned the About section, also):

<img width="336" alt="comparephenotypes" src="https://cloud.githubusercontent.com/assets/2450553/8972957/2c1a06e6-3614-11e5-83ad-755841e02947.png">

**Comment by mellybelly** [comment]
I like it. change to "find models and diseases similar to..."

**Comment by harryhoch** [comment]
+10

**Comment by mellybelly** [comment]
go for it, i like phenogrid.

**Comment by DoctorBud** [comment]
Created a PR to merge to master. It contains a new layout and graphics for the home page. See https://github.com/monarch-initiative/monarch-app/pull/869.

Here are some screenshots..

<img width="1037" alt="homemonarch" src="https://cloud.githubusercontent.com/assets/2450553/9022536/6ce1966a-382d-11e5-96db-6db54c19c690.png">

<img width="779" alt="homediseases" src="https://cloud.githubusercontent.com/assets/2450553/9022539/7bb5f118-382d-11e5-8182-332ee6bac94c.png">

<img width="888" alt="homemodels" src="https://cloud.githubusercontent.com/assets/2450553/9022540/9753e952-382d-11e5-80bf-39fba2557436.png">

**Comment by harryhoch** [comment]
very nice, @DoctorBud, thanks.  Should/can we try to push this to the release, or wait until next time?

**Comment by cmungall** [comment]
+1 to incorporating into release

**Comment by harryhoch** [comment]
agreed

On Aug 1, 2015, at 12:56, Chris Mungall <notifications@github.com<mailto:notifications@github.com>> wrote:

+1 to incorporating into release

##

**Comment by mellybelly** [comment]
I like it!

**Comment by jmcmurry** [comment]
I'm going to paste a few screenshots one at a time, for consideration. Note that the site will not look its best with the current color scheme, but imho, is still an improvement. The changes represented below are only icons and banner. They make a big difference to the look, but are low-risk changes.

**Comment by jmcmurry** [comment]
Some icon possibilities.
![screen shot 2015-08-02 at 01 29 07](https://cloud.githubusercontent.com/assets/3658863/9025345/fbeabdd6-38b5-11e5-9f6d-1023dfd440f4.png)

**Comment by jmcmurry** [comment]
Swapping out the icons only. Pls ignore alignment for now; these are all just illustrator for conversation purposes.

![screen shot 2015-08-02 at 00 57 23](https://cloud.githubusercontent.com/assets/3658863/9025350/2fc1b0e2-38b6-11e5-8c42-594e9c5cb1fe.png)

**Comment by jmcmurry** [comment]
Swapping out icons and the banner for a dark banner.
![screen shot 2015-08-02 at 00 54 36](https://cloud.githubusercontent.com/assets/3658863/9025355/7a1bc628-38b6-11e5-9fad-913c7835dd17.png)

**Comment by jmcmurry** [comment]
Swapping out icons and the banner for a light banner.
![screen shot 2015-08-02 at 01 21 36](https://cloud.githubusercontent.com/assets/3658863/9025361/9d65b45e-38b6-11e5-9cca-2f58d9ea7b4f.png)

**Comment by mellybelly** [comment]
@jmcmurry I like the new icons. I also like the new networkey jumbotron, but wonder if it was light if the rest of the site should be dark grey, or vice versa?

RE Icons, for phenotypes the goal was to show variation somehow - maybe try playing with the three eyes one again, stretch them a bit to fill some space?

**Comment by jmcmurry** [comment]
Carousel home image ("about monarch") now near completion, so final call for feedback.
With or without the magnifying glass icon? I'm too close to this to decide.
Both are below.

![screen shot 2015-08-04 at 22 59 46](https://cloud.githubusercontent.com/assets/3658863/9079234/e937a656-3afc-11e5-8315-3559aa953761.png)
![screen shot 2015-08-04 at 22 59 30](https://cloud.githubusercontent.com/assets/3658863/9079235/e94a542c-3afc-11e5-9b60-cd7354e0d7ba.png)

Thanks :)

**Comment by harryhoch** [comment]
I think I like the magnifying glass, but it's only a slight preference.

**Comment by mellybelly** [comment]
I like the magnifying glass too!

**Comment by nicolevasilevsky** [comment]
Both look really good!

**Comment by jmcmurry** [comment]
Homepage will always be a work in progress, but this particular ticket can now be closed.
