### ISSUE TITLE
info buttons don't work on the grid

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#845]
when i'm here:
http://beta.monarchinitiative.org/disease/OMIM:305400

i selected to flip axis.
i tried clicking on any of the info buttons, but none of them worked.

**Comment by harryhoch** [comment]
@yuanzhou, I think this is a straightforward fix -  we just need to add 

"var self=this;" 

to the start of configureFaqs...

**Comment by yuanzhou** [comment]
@harryhoch You are right. I noticed that too this morning. We didn't notice this before in the console because we were not using the strict mode. With JSHint we use strict mode. I've already fixed those.

**Comment by harryhoch** [comment]
great. thanks
