### ISSUE TITLE
some grouping classes don't resolve

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#847]
i navigated on the data graph like this:
<img width="804" alt="screen shot 2015-07-24 at 11 08 24 am" src="https://cloud.githubusercontent.com/assets/5124411/8881420/8449ae4e-31f4-11e5-92f1-de55acfa62bb.png">

and then clicked on the bar, which took me to:
http://beta.monarchinitiative.org/phenotype/OBO:DC:0000525
this doesn't resolve.
i also tried 
http://beta.monarchinitiative.org/phenotype/DC:0000525
but it doesn't resolve.

these should be in the ontology, right? @cmungall @kshefchek

**Comment by kshefchek** [comment]
They are not in geoffrey or GOlr (http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/OBO:DC:0000525?project=%2A)
Can we check to see if they are in the owl files and were loaded successfully?

**Comment by kshefchek** [comment]
http://beta.monarchinitiative.org/phenotype/DC:0000525 appears to resolve now.
