### ISSUE TITLE
add faceting for charts

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#849]
i want to be able to facet on the species (show/hide) on the various dove charts.

**Comment by jmcmurry** [comment]
This is especially important now that we have loads more species. There are now lots more scenarios in which visualizing the less-frequent species in the graph is impossible due to their being eclipsed by human and mouse.

**Comment by jmcmurry** [comment]
cc: @DoctorBud let's have a think about this in light of search faceting...
