### ISSUE TITLE
Search results should show taxon

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#851]
E.g

http://beta.monarchinitiative.org/search/SH3KBP1

Autocomplete too

consult with @kltm, we have exact same issue in amigo

**Comment by kshefchek** [comment]
Our search is just a wrapper for SciGraphs: /vocabulary/search/{term}.  I don't see taxon in the results there but will look into adding.

**Comment by nlwashington** [comment]
@ccondit if we add the taxon as a "category", would this solve the problem?  is that possible to add categories that are from matching patterns (in this case `gene_id--[RO:in_taxon]--> taxon_id`) rather than just simple subclass relationships?

**Comment by ccondit** [comment]
@nlwashington we'd have to implement some new code to do this. Should be doable, though.

**Comment by kshefchek** [comment]
I've put in a front end fix for this by calling the neighbors service that allows for multiple IDs.  I've also fixed the issue with equivalent classes showing up.  This has been tested with the older versions of scigraph (rosie) so the latest equivalence merge features still need to be tested.
