### ISSUE TITLE
Redirect to equivalent class when node lacks information

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#852]
Example; ENSG00000157168 has no label and limited info in SG:
http://duckworth.crbs.ucsd.edu:9000/scigraph/graph/neighbors/ENSEMBL:ENSG00000157168?depth=1&direction=BOTH&project=*

Here is how it looks for us:
http://beta.monarchinitiative.org/gene/ENSEMBL:ENSG00000157168

We have diseases (via equivalence axioms) which is nice

Similar for the equivalent OMIM gene ID
http://beta.monarchinitiative.org/gene/OMIM:142445
(with added Error message)

Proposal:

If a node has no label, and has an equivalence axiom to something with a label, redirect page. At the very least, provide a link for the user to go to the other page

**Comment by cmungall** [comment]
Same for disease

http://beta.monarchinitiative.org/disease/DOID:8584
http://beta.monarchinitiative.org/disease/MESH:C538493
http://beta.monarchinitiative.org/disease/OMIM:113970 Burkitt lymphoma

**Comment by cmungall** [comment]
Different example, equivalents but with labels

http://beta.monarchinitiative.org/gene/OMIM:608958
http://beta.monarchinitiative.org/gene/NCBIGene:100
http://beta.monarchinitiative.org/gene/ENSEMBL:ENSMUSG00000020230

**Comment by cmungall** [comment]
Order of precedence:
- OMIM > DOID > Orphanet > MESH
- {MGI,ZFIN} > NCBIGene > OMIM > ENSEMBL

Algorithm: if we are on a page for ID, and ID lacks a label, then find equivalents and work down the order of precedence until we have an ID with a label.

**Comment by kshefchek** [comment]
Closing this for now.  @nlwashington would this be useful for other pages, genotypes maybe?
