### ISSUE TITLE
identifiers with period symbols (such as OMIM variants) do not route

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#853]
Example
http://beta.monarchinitiative.org/variant/OMIM:608958.0022

Is being parsed as OMIM:608958, because this looks like a `OMIM:608958.FORMAT` type URL

@ccondit applied a fix here:
https://github.com/ccondit/monarch-app/commit/1425ec2372e0db11004076c7c05183350c33c34d

This should also be applied to variants

**Comment by cmungall** [comment]
Ah, we actually used to deal with this (in a hacky way):

```
app.get('/legacy/variant/:id.:fmt?', function(request, id, fmt) {
    //since we don't have allele or variant pages,
    //we will redirect to the sources for now
    //var newId = engine.resolveClassId(id);
    var url;
    if (id.match(/^OMIM/)){
        url = makeExternalURL(id+"."+fmt);
    } else {
        url = makeExternalURL(id);
    }
    engine.log("redirecting: "+id+" to source at "+url);
    return response.redirect(url);
});
```

Then in the genericised refactored:

```
app.get('/variant/:id.:fmt?', fetchVariantPage);
```

**Comment by cmungall** [comment]
Note that we have removed the json button, so simply deprecating the .json will suffice

**Comment by kshefchek** [comment]
I also attempted a fix with 9531bc5675b62f41294dda0d86a4af3d2903571a

**Comment by cmungall** [comment]
Oops, are our fixes redundant?

**Comment by kshefchek** [comment]
Actually, it was still broken after my fix because the id variable did not
include the information after the period.  I'll remove that code.
