### ISSUE TITLE
autocomplete doesn't work on internal delimited strings

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#856]
for example, "marie" does not complete on Charcot-Marie-Tooth disease

<img width="381" alt="screen shot 2015-07-25 at 3 27 37 pm" src="https://cloud.githubusercontent.com/assets/796636/8891512/e1a7b9b2-32e1-11e5-93fd-72e3a6fac46c.png">

**Comment by jmcmurry** [comment]
This is related to both #1282 (punctuation) and to #1305 (default to boolean AND)

**Comment by kshefchek** [comment]
works now after the solr switch
