### ISSUE TITLE
Implement different pages for diseases and disease groupings

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#857]
Disease groupings (e.g. "neurodegenerative disease") can potentially have 1000s of phenotypes, makes no sense to have phenogrid as first tab, or even at all. For disease groupings, the hierarchy is naturally more interesting, as the user is likely to want to explore downwards, so making the hierarchy the first tab is probably best. 

Diseases/leaves (e.g. OMIM) should always be scalable for phenogrid, so we make this prominent. I would argue the hierarchy is less interesting and as the only valid direction is up, this may affect how we show things visually.

Caveat: not always straightforward, e.g. ordo may consider some OMIMs to be groupings, with 'etiological subtypes' and similar beneath. I suggest we adopt simple graph leaf=disease, non-leaf=grouping, a simple SG test.

Yes this is very last minute for the next release but I think this is necessary, e.g. to avoid phenogrid spinning on high level nodes.

**Comment by kshefchek** [comment]
We already check if a disease is a leaf node for the annotation sufficiency score so this should be an easy fix.

**Comment by kshefchek** [comment]
I've done something similar with other pages - if there are no phenotypes the page will start on the overview tab with the compare tab greyed out.
