### ISSUE TITLE
bring back the gene summary

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#863]
we used to get the ncbi gene summaries via services from MyGene.info.

can those be brought back?
http://beta.monarchinitiative.org/gene/NCBIGene:6469

this can be fetched by 
http://mygene.info/v2/gene/6469?fields=summary
where the 6469 is the NCBIGene id

**Comment by jmcmurry** [comment]
+1 ... I didn't know they were ever there, however. How hard is this to bring back? @kshefchek?

**Comment by kshefchek** [comment]
Added with b23487c

**Comment by kshefchek** [comment]
Reopening as these are no longer working.

**Comment by cmungall** [comment]
not sure why it would stop working but seem slike a good time to switch to mygene v3

**Comment by kshefchek** [comment]
fixed with #1496
