### ISSUE TITLE
RO:0003301 links do not resolve

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#864]
Currently linked to http://purl.obolibrary.org/obo/RO_0003301
On our site here:  http://beta.monarchinitiative.org/disease/DOID:0060072 (models tab)

**Comment by cmungall** [comment]
The URL is correct, it's just that we're ahead of the release. I will cut a new one

**Comment by jmcmurry** [comment]
This has been addressed

**Comment by cmungall** [comment]
Looks like a fantastic way to summarize clinvar

However, it's not clear how we want to prioritize this given issues with data quality. @monicacecilia discuss on leadership call?

**Comment by iimpulse** [comment]
2 Visualizations: if number of genes is > 1 show stacked chart, otherwise pie chart
