### ISSUE TITLE
Add taxon to autocomplete dropdown

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#865]
I removed filtering based on label and category with this commit: https://github.com/monarch-initiative/monarch-app/commit/283a315363c2d13f16e298eb3b9a754b642e2360

But now we have issues with duplicate gene labels (from equivalent gene IDs).

![autocomplete](https://cloud.githubusercontent.com/assets/1467299/8965813/b2ed9976-35e2-11e5-8557-3e124a1a68e4.png)

**Comment by nlwashington** [comment]
it's multiple gene ids, but also that we've now added 10 species, all of whom have Shh's.

**Comment by cmungall** [comment]
See #851
