### ISSUE TITLE
missing labels for genes

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/monarch-legacy#867]
I've noticed a few gene's missing their labels (see picture attached).  if i run in my localhost mode, the labels for the particular gene appears, but when run against beta.monarchinitiative the label attribute is not present.  here's the url that I was using:

http://beta.monarchinitiative.org/simsearch/phenotype?input_items=HP:0000726+HP:0000746+HP:0001300+HP:0002367+HP:0000012+HP:0000716+HP:0000739+HP:0001332+HP:0001347+HP:0002063+HP:0002067+HP:0002172+HP:0002322+HP:0007159&target_species=10090

specifically if you look for id **MGI:3616191** in the json.  (also here's a missing one for zfin   **ZFIN:ZDB-GENE-070117-146**)

@cmungall @nlwashington 

![missinglabels](https://cloud.githubusercontent.com/assets/10049022/8970119/de1fece2-3615-11e5-9f51-181a4ee153c6.png)

**Comment by kshefchek** [comment]
Perhaps the discrepancy is due to caching the simsearch results.  @davism84 if you clear out the cache/phenotypeprofile/*.json it should match beta.  Taking a look at why we've lost the labels.

**Comment by kshefchek** [comment]
I also cleared the cache on beta and it seems the labels are back, although I no longer see this ID.

**Comment by davism84** [comment]
it seems to be working fine now @kshefchek
