### ISSUE TITLE
Phenogrid pops up a strange widget on disease pages

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#870]
http://stage.monarchinitiative.org/disease/OMIM:305400

<img width="1440" alt="screen shot 2015-08-01 at 10 25 55 am" src="https://cloud.githubusercontent.com/assets/50745/9022785/bbf89a46-3837-11e5-9137-1d9c26f40239.png">

**Comment by cmungall** [comment]
today both monarch-stage and owlsim-stage were down. I restarted the former, but not the latter, which appears to be the cause. Restarting now

**Comment by cmungall** [comment]
The problem was owlsim server was down. Fixed now it's up

**Comment by pnrobinson** [comment]
@monicacecilia This would be one additional way of saying "What model can I use to study this disease"? This would be a decent entry point for cases where the molecular diagnosis is not known. Ideally, we would also make a tutorial of where to go from here to other parts of the app.
I would suggest let's keep it simple for the first step -- Let the user load a Phenopacket and click "GO" to get the phenogrid. I think the current UI is unnecessarily complicated, and this should become the "iPhone" version of the phenogrid -- you do not need to read the instructions to get it to work!

**Comment by monicacecilia** [comment]
Okay. We can keep it as a separate function from the Phenotype Profile Search.
