### ISSUE TITLE
Analyze phenotypes failing on stage

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#871]
http://stage.monarchinitiative.org/analyze/phenotypes/?input_items=MP%3A0020310+MP%3A0011464+UBERON%3A0003517PHENOTYPE&mode=search&target_species=all&limit=100

Arrived here from http://stage.monarchinitiative.org/analyze/phenotypes and selecting 3 phenotypes

**Comment by harryhoch** [comment]
@cmungall, this just worked for me. Please see if you can replicate.

**Comment by cmungall** [comment]
today both monarch-stage and owlsim-stage were down. I restarted the former, but not the latter, which was the cause. Restarting has fixed

**Comment by kshefchek** [comment]
I think we link out to OMIM when it's available and Orphanet if it's not (@iimpulse wrote this and may be able to comment further).  Presumably OMIM does not have "neonatal Marfan syndrome" but if it does this would be a Mondo issue.

**Comment by kshefchek** [comment]
ah sorry I did not read this closely, so if an OMIM link out doesn't exist we should not call the Orphanet page a "clinical synopsis", this should be an easy fix
