### ISSUE TITLE
Do not make phenotype labels ontology specific

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#873]
From @pnrobinson 

> When you run the PhenoGrid starting from a mouse model, you can "click on icon to expand HPO info". However, the ontology is MPO rather than HPO. A similar comment applies to fish terms on the left. 
> Maybe we should replace this for now with "click to expand phenotype info"

**Comment by harryhoch** [comment]
this is a phenogrid bug. moving over to that issue repo.  See https://github.com/monarch-initiative/phenogrid/issues/145
