### ISSUE TITLE
gene tab disease page shows orthology

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#883]
the gene tab on disease pages shows orthology relationships.  this is not right.

http://beta.monarchinitiative.org/disease/DOID:10595

is this misconfigured, @kshefchek ?  or is this coming from upstream?

**Comment by kshefchek** [comment]
DOID:10595 is part of the object closure for NCBIGene:9131

We could get around this by filtering the object_category on disease.  That should get rid of these genes but we may also want to figure why a disease is part of gene closure.

**Comment by kshefchek** [comment]
This is fixed but I'm leaving open as we should determine the underlying cause of a disease being in a gene closure.

**Comment by nlwashington** [comment]
this is another of those a gene is a disease things that we are getting from the omim import.  @cmungall needs to fix in the mondo build.

**Comment by cmungall** [comment]
Just to confirm this is the problem node here: http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/OMIM:300169.json
?

**Comment by cmungall** [comment]
I am not sure that mondo is the issue here. OMIM:300169 is not present in mondo (could this be from an earlier version). Also if it were in mondo, then we would see a SubClassOf relationship from http://geoffrey.crbs.ucsd.edu:9000/scigraph/graph/neighbors/OMIM:300169.json to a disease class.

Mysterious

**Comment by nlwashington** [comment]
hm. you are right, this is odd.  even in omim it is listed as a gene:  http://omim.org/entry/300169

but, if i click on that link, i notice that it is getting a category of "disease".

it is coming from somewhere, but i'm not sure where.

@ccondit is adding these categories.  but how is this one getting added, if it's not a subclass of disease?

**Comment by ccondit** [comment]
Looks like `NCBIGene:9131` is equivalent to `OMIM:310490` (which is a disease). At least according to ncbigenes.ttl.

**Comment by nlwashington** [comment]
ok, so i think that the NCBI mappings to OMIM are fraught with errors, like this.  due to the fragile nature of the whole OMIM identifier business, i will try to refactor all our sources to only pull the equivalences from OMIM itself.  see refactor ticket https://github.com/monarch-initiative/dipper/issues/185

**Comment by jmcmurry** [comment]
This particular bug seems no longer to be present; however the underlying disease is a gene stuff has cropped up in other tickets so I will close this one.
