### ISSUE TITLE
some RO labels not showing

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#885]
Looking at this page:
http://beta.monarchinitiative.org/disease/OMIM:609311
there is a "tool tip" that appears when you hover the mouse over RO_0003301
Two issues:
(i) The tool tip just repeats RO_0003301 but it should provide the English language name of the term
(ii) the link is broken (http://www.ontobee.org/browser/rdf.php?o=RO&iri=http://purl.obolibrary.org/obo/RO_0003301).
(from @pnrobinson, transferred from https://github.com/monarch-initiative/dipper/issues/178)

**Comment by cmungall** [comment]
The link is fine, it's a pre-release relaton, I will take care of it

**Comment by kshefchek** [comment]
Closing as duplicate of #864
