### ISSUE TITLE
Phenogrid screenshot on home page needs to be updated

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#886]
![capture](https://cloud.githubusercontent.com/assets/195873/9061063/26403bba-3a87-11e5-889f-45d8dd7c70f7.PNG)

Since we are using one color scale, this screenshot on monarch-app's homepage needs to be updated.

**Comment by harryhoch** [comment]
@yuanzhou , agreed. can you make the change? I think this can go right into production and master - shouldn't need review

**Comment by yuanzhou** [comment]
@harryhoch Already updated. Once monarch-app staging site gets rebuilt, the new screenshot will be there. https://github.com/monarch-initiative/monarch-app/commit/8ab6ac3bd4dd6fac3c21e72e4eb73a58903502fd
