### ISSUE TITLE
Combine the button text with the subtext

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#892]
To economize on vertical space and therefore enable more of the carousel images to be "above the fold", please combine the button text with its subtext. Because these are actions (investigate, explore etc.), they suggest clickability. I would perhaps also add a chevron to reinforce the clickability.( See apple's homepage "start listening now > " for an example.

These blurbs of text are trimmed down and also are importantly of comparable length.
- Monarch provides a rich landscape of phenotypes, diseases, models, and genes for translational research.
- Investigate genetic underpinnings of disease by comparing diseases and their phenotypes across species.
- Explore phenotypes that may be similar across various diseases or across species.
- Find candidate genes by comparing human disease phenotypes with those of animal and in vitro models.
- Learn about the diseases and phenotypes associated with your favorite gene and its orthologs in other models.

Feedback welcome.

**Comment by cmungall** [comment]
Punt til next release?

**Comment by jmcmurry** [comment]
This was fixed, sorry
