### ISSUE TITLE
Still some repeats in Dove Graph Categories?

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#895]
![screen shot 2015-08-07 at 00 30 19](https://cloud.githubusercontent.com/assets/3658863/9130904/93040202-3c9b-11e5-89f0-991aa348f569.png)

**Comment by kshefchek** [comment]
This is coming from equivalencies in the ontology.  We could filter out duplicate labels but this won't get rid of all of them (ie Skin Photosensitiviy and Photosensitivy in the above example might also be duplicates).

**Comment by jmcmurry** [comment]
Hi Ken, Thanks for clarifying. As far as I can tell, there's no reason not to collapse duplicate labels. The scenarios I looked at had exactly equivalent data corresponding and it looks ... confusing. Perhaps I'm missing something? I'm far less concerned about synonyms, but we can flag that issue for followup later?

**Comment by cmungall** [comment]
It'd be a hack and would not work all the time unless you build advanced
nlp into client

**Comment by jmcmurry** [comment]
Hi Chris, the hack you're referring to would be for synonyms and not  uniquification based on exact matches? Or am I missing something?

**Comment by cmungall** [comment]
Not sure what you mean

There are declared logical equivalencies and lexical matches. Anything based on lexical matches will either miss things or incorrectly collapse

**Comment by cmungall** [comment]
Need a decision on this soon. Full fix postponed. As a temp fix could suffix labels with source

**Comment by kshefchek** [comment]
We can leave as is, or filter out labels knowing there’s the chance we might remove a class, or we can add the ID prefix next to the label in parenthesis.

**Comment by nlwashington** [comment]
I think we don't hack it, and leave the things that have apparently the same labels.  they will get cleaned up in the future when we fix https://github.com/SciGraph/SciGraph/issues/135.

chris' option would be a reasonable interim-fix.

**Comment by jmcmurry** [comment]
Thanks for clarifying. Until now I hadn't realized that they were _not_
exact source matches (just equivalent string matched labels).
Therefore agreed fine to postpone a fix. We are already providing the full
label text in tooltip; so perhaps that could also include the source there.
Perhaps that is what you had in mind all along?

In addition to addressing the apparent duplication, source could be useful
in its own right. However, it could be a lot of clutter, so I don't feel
strongly about it. I agree it is fine to prioritize other things.

**Comment by kshefchek** [comment]
I've added the ID prefix to the text you see when hovering over a y axis label, please close if this is sufficient.

**Comment by jmcmurry** [comment]
I think it is sufficient for now; we can revisit after SciGraph/SciGraph#135 is addressed.

**Comment by kshefchek** [comment]
This should be fixed with the latest cliqueMerge code in SciGraph, leaving open as I need to go through and make sure parts of the hard coded portions of the phenotype and disease ontologies are all clique leaders.
