### ISSUE TITLE
http://stage.monarchinitiative.org/simsearch/phenotype 500 error

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#896]
I went to http://stage.monarchinitiative.org/disease/OMIM:305400, after switching the species from overview to homo, got this error:

![capture](https://cloud.githubusercontent.com/assets/195873/9136664/864adfd6-3ce6-11e5-8a9c-f7b7e95aaf57.PNG)

**Comment by kshefchek** [comment]
We should be failing better, but I think calling simsearch without any phenotypes is expected to fail regardless.  The disease page linked above seems fine.  @yuanzhou how did you get to the empty simsearch page?

**Comment by yuanzhou** [comment]
@kshefchek  If you go to the phenogrid dropdown menu at the bottom, the default species is Overview, if you select Homo or any other species, you will see an empty popup with this 500 error in console.

The same page from beta (http://beta.monarchinitiative.org/disease/OMIM:305400) doesn't have this issue.

**Comment by cmungall** [comment]
Let's try and get a hotfix for this in, provided it's straightforward
