### ISSUE TITLE
PhenoGrid notes shows up upon page load

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#903]
loading this page:
http://stage.monarchinitiative.org/disease/OMIM:309560
shows an empty phenogrid notes page in the upper corner. What is the correct behavior?
Also note that PhenoGrid is taking a terribly long time to load on this page.

<img width="1440" alt="screen shot 2015-08-08 at 9 14 20 am" src="https://cloud.githubusercontent.com/assets/796636/9151159/fc226ea0-3dad-11e5-91fc-d15f602a790e.png">

**Comment by kshefchek** [comment]
I believe this is the same bug as  #896.  Odd because the same page on beta works http://beta.monarchinitiative.org/disease/OMIM:309560, could this be a stage owlsim or an issue with not updating to the latest phenogrid?

**Comment by cmungall** [comment]
Confirmed. I have contacted Larry to see what the issue with the VM that 
stage-owlsim is running on.
