### ISSUE TITLE
missing disease descriptions in jumbotron

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#904]
Should we see disease descriptions from mondo in the jumbotron, or in the overview page?

For example, http://stage.monarchinitiative.org/disease/OMIM:305400 has the following in mondo:

Aarskog-Scott syndrome, also known as faciogenital dysplasia, is an X-linked disorder characterized by short stature, hypertelorism, shawl scrotum, and brachydactyly, although there is wide phenotypic variability and other features, such as joint hyperextensibility, short nose, widow's peak, and inguinal hernia, may also occur. Most patients do not have mental retardation, but some may have neurobehavioral features. Carrier females may present with subtle features, such as widow's peak or short stature (summary by {28:Orrico et al., 2010}).

**Comment by kshefchek** [comment]
The definition is on our beta scigraph but not the staging scigraph server, see http://beta.monarchinitiative.org/disease/OMIM:305400

@cmungall do you know why there’s a discrepancy?

**Comment by jmcmurry** [comment]
Definitions are working on beta now so I will provisionally close the ticket.
Definitions are intentionally no longer in the jumbotron but in the body.
I don't know why it works on beta but on production we get the "your page not found" message.
@cmungall  @kshefchek please reopen if you know the reason for this and if it is still something we need to worry about.
