### ISSUE TITLE
News and events window on homepage should show most recent blog post

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#906]
Currently its showing an older IMPC data load post

**Comment by kltm** [comment]
It looks fine now. IIRC, there is a cache involved, so new posts may not be instantaneous.

**Comment by cmungall** [comment]
is the cache in monarch-app?

**Comment by kltm** [comment]
IIRC, yes. Although it has been some time since I was in there...

**Comment by kltm** [comment]
See around "_get_blog_data", say from L2850:
https://github.com/monarch-initiative/monarch-app/blob/master/lib/monarch/web/webapp.js#L2844
