### ISSUE TITLE
Some truncated phenotype labels in dove graphs not shown in full

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/monarch-legacy#916]
Recreate: From Explore Genes (http://beta.monarchinitiative.org/gene), navigate to Cardiovascular system > Vascualture.  Scroll down and click the last phenotype in the list (Decreased Process Quality . . .).  There is no way to see the full phenotype label for this class. Even the hover over label is truncated.  

This seems to be true for all truncated labels on this page.  But on other pages I do see the full label when I hover.

**Comment by kshefchek** [comment]
Fixed with https://github.com/monarch-initiative/monarch-app/commit/29c91736f7f3ef3bf2610a9054861b7d0f8da7a8
