### ISSUE TITLE
ZFIN gene variant lists incomplete - only showing expression variants

### ISSUE THREAD

**Issue by mbrush** [monarch-initiative/monarch-legacy#922]
See variants tab on:
http://beta.monarchinitiative.org/gene/NCBIGene:796461 for nrg1 gene variants.
http://beta.monarchinitiative.org/gene/NCBIGene:30269 for shha gene variants

List only showing expression variants (MO-targeted) for these, and variant labels are not complete/informative (all have same label as gene label). For example, the nrg1 variant page shows 5 expression variants, all labeled 'nrg1'.  No sequence variants are shown (and there are at least three as we see here: http://zfin.org/ZDB-GENE-050302-113)

For now we need to show full labels for expression variants and be sure to get sequence variants in.  Longer term we should distinguish expression variants from sequence variants better in the UI  (esp as the concept of expression--variant genes will be new to most)

Note, gene variant pages from other organisms seems ok (e.g. mouse shh here http://beta.monarchinitiative.org/gene/MGI:98297 . . .but of course we only have sequence variants for these).

@kshefchek and @nlwashington can we trace the problem here?

**Comment by nlwashington** [comment]
hm.  i don't know why the labels aren't rendering right.  (my guess is something about the stuff between < and >.  they are not hyperlinked, presumably because they are bnodes.  @kshefchek to fix.

i see the correct data in duckworth, but is apparently missing in golr. @jnguyenx and i will write a test and fix.

**Comment by nlwashington** [comment]
the golr query was incomplete; this has now been fixed in commit https://github.com/monarch-initiative/configs/commit/cd1af4d9512b489c0ba4de401743bb977b3ee799 and will show up in the next golr load (at which time we can close this ticket).

assigning to @kshefchek to fix the label issues.

**Comment by kshefchek** [comment]
Labels should be fixed now, will leave open until the GOlr reload to confirm the fix.
