### ISSUE TITLE
Loading disease takes too long

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#926]
http://monarchinitiative.org/disease/OMIM:105830

![capture](https://cloud.githubusercontent.com/assets/195873/9384740/7d20915a-4720-11e5-8685-b6ec34884481.PNG)

It takes so long (sometimes 38 secs) to load the phenotype_list.json. This makes testing very inefficient. Same issue with beta server. @kshefchek can you look into this?

**Comment by cmungall** [comment]
Do we have a separate unit test for this API call?

Why is this being called? The only phenotype_list.json call I see in webapp is for the experimental patient pages

**Comment by kshefchek** [comment]
We test the underlying function in the apitest.js script, but just that it runs and we don't time it, this could be improved.

This is called by the phenogrid launcher, but should happen after page load, see https://github.com/monarch-initiative/monarch-app/blob/master/js/phenogridloader-no-species.js#L13

This disease only has 57 phenotypes so golr should return this pretty quickly.  This may be a golr server issue.

**Comment by cmungall** [comment]
I tried it. Returned in <0.5s

**Comment by cmungall** [comment]
Hmm, uncached phenotype sets are still quite slow. Need to investigate

**Comment by cmungall** [comment]
The whole site was down. Larry reployed. Try it now

**Comment by cmungall** [comment]
http://beta.monarchinitiative.org/gene/NCBIGene:8813 takes ~1s
http://monarchinitiative.org/gene/NCBIGene:8813 -- not returning

**Comment by cmungall** [comment]
Seems owlsim was down too. production now point to beta owlsim, things seem fine

**Comment by yuanzhou** [comment]
Just tested, http://monarchinitiative.org/disease/OMIM:105830 seems to be working fine. But if you have monarch-app installed locally, e.g., http://localhost:8282/disease/OMIM:105830 still took 49 seconds from my test just now.

**Comment by cmungall** [comment]
Can you narrow this down any further? Which call?
