### ISSUE TITLE
pubmed links

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#93]
links to papers should give paper info (author, year, title, or something similar, instead of just saying "pubmed" . NIF Publication info services might be used for this purpose

**Comment by cmungall** [comment]
I think we'd want to avoid multiple iterated service calls, some pages may have lots of PMIDs. In most cases we have additional metadata required captured upstream anywy

**Comment by nlwashington** [comment]
We may push the literature citations into a separate tab, and those will be populated with a call to the literature service to show the short citations.  see #123.
