### ISSUE TITLE
Software documentation is out of date

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#930]
http://monarchinitiative.org/page/software
should be replaced with new architecture diagram and links to Dipper, SciGraph, etc.

**Comment by jmcmurry** [comment]
Also some documentation on the NodeJS updates would be welcome.  @DoctorBud @kshefchek

**Comment by cmungall** [comment]
I don't think we should have >1 line about the nodeJS on the front-facing site. Docs should be located where they will be least likely to go stale. README.md and standard node docs good for node
