### ISSUE TITLE
Installation error on Ubuntu-14.04

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#933]
I was playing with the behave test this morning on Ubuntu 14.04, it was working fine without monarch-app installed. By the time I was running the install.sh script and start-server.sh, I got the following error:

![capture](https://cloud.githubusercontent.com/assets/195873/9523434/f3dc4b18-4ca7-11e5-8f92-9ed080592a91.PNG)

Last week, a coworker of mine was installing monarch-app on his macbook, he had trouble too. Something related to stick. Please look into this.

**Comment by kshefchek** [comment]
You're getting the error:

```
    /usr/bin/env: node: No such file or directory
```

Could you try installing node and rerunning the install script?  When you type "whereis node' it should return /usr/bin/node or some bin directory on your path.

It seems most the errors related to the install script are related to node, npm, or gulp issues specific to different platforms.  It also seems using --force can occasionally cause errors if something is not rebuilt correctly.

**Comment by yuanzhou** [comment]
Thanks @kshefchek , got this resolved by doing

```
sudo ln -s /usr/bin/nodejs /usr/bin/node
```
