### ISSUE TITLE
Behave test question

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#934]
Tan the behave test today and got the following error:

![capture](https://cloud.githubusercontent.com/assets/195873/9526568/0e2e7cec-4cb8-11e5-9312-b90a778b40c2.PNG)

**Comment by kshefchek** [comment]
The build is currently passing, @yuanzhou are you running your behave tests against beta or your localhost?

**Comment by yuanzhou** [comment]
@kshefchek I simply followed the instructions here https://github.com/monarch-initiative/monarch-app/tree/master/tests/behave

And noticed that the behave tests run against tartini.crbs.ucsd.edu

**Comment by kshefchek** [comment]
Is your master branch up to date?

**Comment by yuanzhou** [comment]
I just grabbed the most recent master branch of monarch-app, and tested again without running the `install.sh` and `start-server.sh` since I had the following installation error:

![capture](https://cloud.githubusercontent.com/assets/195873/9528275/b3a9fa58-4cc1-11e5-93fc-b5400b937d27.PNG)

For the testing itself, I could run the test without installing monarch-app, it still runs againt tartini. but NO FAILURE this time. I don't know if I should install monarch-app first then run the tests to see if it still runs against tartini. But having the installation error.

**Comment by yuanzhou** [comment]
@kshefchek FYI, I did another fresh installation, no error this time, really weird. Installed monarch-app, and then ran the behave tests. It turned out that behave tests run against tartini by default, once I have the monarch-app install, it still runs against tartini, unless I specify the server URL to the behave tests.

```
TARGET=http://localhost:8282 behave
```

In this case, 8282 is the port number I used for my specific CentOS system.

**Comment by yuanzhou** [comment]
And I noticed that in the `tests/behave/environment.py`, line 19 shows 

```
context.target = 'http://tartini.crbs.ucsd.edu'
```

Should this default URL be monarchinitiative.org now? 

@kshefchek @cmungall @harryhoch

**Comment by kshefchek** [comment]
I would say let's keep it on beta/tartini, since this should be up to date with master, although we should also have tests running against master (on jenkins?).

On travis it is set to the localhost since we boot the server and run the tests in headless mode against the localhost.

**Comment by cmungall** [comment]
Yes, don't hardcode tartini, but beta.monarchinitiative.org is fine
