### ISSUE TITLE
Node start script should allow for configuration between alpha/beta/stage/production

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#937]
previously we had seperate scripts that wrapped js to load the appropriate json file from conf/

This way wasn't ideal, but we should have a way of doing the equivalent before the next release

**Comment by jmcmurry** [comment]
nodejs

**Comment by DoctorBud** [comment]
This has been addressed by allowing the webapp_launcher.js script to have an environment parameter that can be 'dev', 'production', or 'stage'. The start-server.sh script will use 'dev' by default, unless the environment symbol RUNENV is set to an alternate environment (e.g., 'production' or 'stage').

Please close this ticket (I don't have permissions to do so).
