### ISSUE TITLE
fix pathway info on pathways tab 

### ISSUE THREAD

**Issue by harryhoch** [monarch-initiative/monarch-legacy#94]
Pathway pages for disease pages like http://tartini.crbs.ucsd.edu/disease/OMIM_270400 show multiple disease as related by Kegg pathways. This relationship should be clarified. Also, pathways are currently just labeled as "kegg". Pathway names should be used instead.

**Comment by nlwashington** [comment]
unfolded pathways to be one-per-row, in commit 9d988ba8a8d78fbe6ebbbbf6266d6b1597ca2dc1
