### ISSUE TITLE
MESH term loading as a gene page

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#941]
We should not have MESH terms as gene pages:
http://beta.monarchinitiative.org/gene/MESH:D003117
I linked to this page from here:
http://monarchinitiative.org/disease/OMIM:303800
on the pathway tab, I clicked the "disease" "color vision defects"

This is probably an orphan MESH term with no equivalencies that is somehow not being typed correctly? In this case should probably be a phenotype.

**Comment by nlwashington** [comment]
if i look at this on a phenotype page:
http://monarchinitiative.org/phenotype/MESH:D003117
it has genes!, and a placement in the hierarchy.  so i think possibly a poorly constructed link on the pathway tab on the disease page.

**Comment by kshefchek** [comment]
The category in [golr](http://sirius.monarchinitiative.org:8080/solr/golr/select?defType=edismax&qt=standard&indent=on&wt=json&rows=10&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&fq=subject_closure:%22OMIM:303800%22&fq=object_category:%22pathway%22&facet.field=relation_closure_label&facet.field=evidence_closure_label&facet.field=subject_closure_label&facet.field=object_closure_label&facet.field=subject_taxon_closure_label&facet.field=object_taxon_closure_label&q=*:*&packet=1&callback_type=search) is gene, looking into it now...

**Comment by kshefchek** [comment]
It's an issue with the disease-pathway.yaml file (we're hardcoding the category as gene).  @jnguyenx can you rerun this on the latest golr load?

**Comment by kshefchek** [comment]
Fixed with https://github.com/monarch-initiative/configs/commit/690646f5ef8cc57aa47fb50f84e5c143dced5f83 , will leave open until we update GOlr

This is a disease (color vision defects, http://beta.monarchinitiative.org/disease/MESH:D003117, subclass of OMIM:303800)
