### ISSUE TITLE
equivalent classes are both displaying in ontology view

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#943]
we should collapse the equivalent terms in the ontology browser
![equivalenciesshowing](https://cloud.githubusercontent.com/assets/796636/9645131/bd1a5026-517e-11e5-92ef-d8cc52207d83.png)

see two children that are the same, they are in fact equivalent MP and HP classes

**Comment by kshefchek** [comment]
Fixed with 8313394d494723739281d8c4e073ae5caa2aa31f
