### ISSUE TITLE
Installation Error on Centos 6.6

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#946]
Just grabbed the monarch-app github master branch and did a fresh installation. Failed and got this error: 

![capture](https://cloud.githubusercontent.com/assets/195873/9662051/b25eaaf8-522b-11e5-8272-f39282b9f521.PNG)

**Comment by kshefchek** [comment]
After running do you see any changes to the node_modules directory in monarch-app?  I wonder if running as root will result in the files being placed in a different directory.

**Comment by yuanzhou** [comment]
Very interesting, I tried it again this morning and the fresh installation worked. I didn't do any other changes, still used root. 

One thing I noticed that this time was it says the port number was in use even thought I didn't have anything else running on that port number. I ended up changing to a different port number and it worked. Didn't encounter this issue before.
