### ISSUE TITLE
Missing label on phenotype page for FBcv:0000451

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#947]
when i autocomplete on "wound"
one of the things that it shows me is "wound healing defective"

i select that, and it takes me here:
http://monarchinitiative.org/phenotype/OBO:FBcv:0000451

should it actually be http://monarchinitiative.org/phenotype/FBcv:0000451  ?

regardless, the page has no label.  but it clearly knew about it on autocomplete box.

also, it shows no parents.  this seems like a problem.  @jnguyenx or @cmungall are we loading FBcv?

**Comment by kshefchek** [comment]
This partially has to do with converting underscores to colons (to handle fragments), I've remove this temporarily on phenotype pages: see http://beta.monarchinitiative.org/phenotype/OBO:FBcv_0000451

**Comment by kshefchek** [comment]
This is fixed on beta.
