### ISSUE TITLE
differences between parent/child in navigator

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#948]
http://beta.monarchinitiative.org/phenotype/GO:0007623PHENOTYPE
shows it has a child:
http://beta.monarchinitiative.org/phenotype/FBcv:0000394

but on
http://beta.monarchinitiative.org/phenotype/FBcv:0000394
it does not show any parents.

**Comment by kshefchek** [comment]
Fixed by using UPHENO:0001002 as the root.
