### ISSUE TITLE
Description for diseases

### ISSUE THREAD

**Issue by sarahjkim** [monarch-initiative/monarch-legacy#95]
I think all the phenotype pages have descriptions in the top block. However, the disease specific pages are all missing descriptions. (I don't see a description variable in the JSON blob.) I think this would be nice to have.
![screen shot 2014-02-03 at 1 37 13 pm](https://f.cloud.github.com/assets/4628853/2070437/be8f78ba-8d1b-11e3-8b83-44640e08b65b.png)
[Phenotype pages have description.]
![screen shot 2014-02-03 at 1 37 26 pm](https://f.cloud.github.com/assets/4628853/2070438/be9078a0-8d1b-11e3-8262-47c5fef31778.png)
[Disease pages don't have description.]

**Comment by nlwashington** [comment]
Yep, this is a "feature" of some of the underlying data.  There is a data ticket related to this in JIRA:  https://support.crbs.ucsd.edu/browse/LAMHDI-277

Right now, the description comes from the definition of the disease term in the ontology.  We are going to try to supplement this with descriptions from additional resources.

**Comment by sarahjkim** [comment]
Oh okay. Sorry I didn't see the ticket in JIRA (because I don't have access to it).
