### ISSUE TITLE
add species column to results list

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#950]
for example on this results page: http://beta.monarchinitiative.org/search/pitx1
I don't know which pitx1 genes are from which species.

**Comment by nlwashington** [comment]
a fix is being tested now.

**Comment by cmungall** [comment]
This is ubiquitous

SciGraph autocomplete:
https://github.com/SciGraph/SciGraph/issues/63

text annotator:
https://github.com/monarch-initiative/monarch-app/issues/925

Noctua:
https://github.com/geneontology/noctua/issues/188

AmiGO:
https://github.com/geneontology/amigo/issues/132#issuecomment-60323490

The species-context issue is not related to genes, but this is certainly where the manifestations are particularly painful. We have it somewhat with species-specific ontologies, although we have more control in the monarch app where we aggressively merge, but will show up again in a global phenotua instance serving zebrafish, fly and human. Once we add protein complexes it will pop up once again.

If a hack is required for this release then let's go ahead, but ultimately this needs a global fix. This means either:
1. Maintain a ubiquitous assumption that the label field is unique, and enforce this as best as possible upstream (e.g. by suffixing labels on sources that do not conform: do essentially what PRO does and make labels like "Shh human")
2. Abandon label uniqueness and enforce defensiveness on all UI components. This will require all UI components being both smarter and more configurable, for example, to specify an additional context-providing field. One possibility is to make the category(ies) the context-providing field. In other words the tuple of `(label,category*)` is assumed to be unique-enough

cc @kltm

**Comment by jmcmurry** [comment]
The fix helps a lot, though there are species missing in some rows at the bottom. I don't see a pattern as to why. In the case of a search on "Pax2", there are four rows affected: (NCBIGene:733478 is Xenopus (Silurana) tropicalis, NCBIGene:5076 and NCBIGene:5076 are Homo sapiens. NCBIGene:293992 is Rattus norvegicus). 

Given that there are ostensibly duplicate rows ( eg. two entries for PAX2 for Bos Bovis), it would be good to also include a column for Gene ID to disambiguate such rows. In the case I mentioned, these do not appear to be equivalent identifiers for the same Gene.

![screen shot 2015-10-01 at 22 16 58](https://cloud.githubusercontent.com/assets/3658863/10254463/c1cf227c-68f8-11e5-8181-b8e78a22c639.png)

**Comment by mellybelly** [comment]
So I think that these two Bos taurus entries are a little different, maybe one is from a Hereford breed build? NCBI should differentiate these better if they are indeed different  "species" ?

http://www.ncbi.nlm.nih.gov/gene?cmd=Retrieve&list_uids=100297382
versus
http://www.ncbi.nlm.nih.gov/gene?cmd=Retrieve&list_uids=617341

Also, the first link in the search results for Bos Bovis goes to the latter Bos taurus record in Monarch.

**Comment by jmcmurry** [comment]
We need to evaluate the extent of such issues with the NCBI source data and then contact them to see if they can resolve it.

**Comment by jmcmurry** [comment]
Should this actually be a dipper ticket instead?

**Comment by kshefchek** [comment]
Closing, this is now implemented with a single call to the neighbors service.

**Comment by cmungall** [comment]
How is performance?

**Comment by kshefchek** [comment]
Autocomplete still seems reasonably responsive.  We actually end up with three calls to scigraph autocomplete -> neighbors (taxon) -> neighbors (equivalents), although we can get rid of the equivalent filtering soon.  I haven't performed any formal load testing.

**Comment by kshefchek** [comment]
For search, beta takes a little bit longer to load.  When testing on "allergy" production returns a result in about 600-700ms.  Beta takes about 1 second.  Still reasonable in my opinion.

Beta: https://app.loadimpact.com/load-test/2ab32049-63b3-474e-8602-29b8e1c095bf
Production: https://app.loadimpact.com/load-test/235f8ab3-8163-4d7f-9392-668806de058f
