### ISSUE TITLE
resolution of ":" vs. "_" curies

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#957]
I don't get the same page when I go to 
http://monarchinitiative.org/model/MGI:3586676
as when I go to:
http://monarchinitiative.org/model/MGI_3586676

Shouldn't these both resolve to the former page?

**Comment by jmcmurry** [comment]
On a related note I mistyped the URL as http://monarchinitiative.org/model/MG:3586676 and found that the page resolved, albeit blank. This is also the case on beta. 

We should probably have a meaningful message if the requested ID doesn't exist. An easy fix, but not a huge priority as this is not a common use case.

![screen shot 2015-10-01 at 15 52 09](https://cloud.githubusercontent.com/assets/3658863/10235824/c89ac614-6854-11e5-8fe6-c52a2c4072e1.png)
