### ISSUE TITLE
Error when searching "Guillan Barre Syndrome"

### ISSUE THREAD

**Issue by memartone** [monarch-initiative/monarch-legacy#96]
Sorry.  I hit return.  I searched for "Guillan Barre Syndrome" on tartini.  When I selected it, I got the following error:

Java class "[Lorg.mozilla.javascript.ScriptStackElement;" has no public instance field or method named "toJSON".
lib/monarch/web/webapp.js, line 198

Script Stack

```
at lib/monarch/web/webapp.js:198 (errorReponse)
at lib/monarch/web/webapp.js:385 (anonymous)
at stick/lib/middleware/route.js:215 (route)
at stick/lib/middleware/params.js:102 (anonymous)
at stick/lib/middleware/static.js:62 (static)
at /var/home/jenkins-slave/workspace/start-monarch-server/lib/monarch/web/sanitize.js:7 (anonymous)
at stick/lib/stick.js:37 (app)
at ringo/jsgi/connector.js:42 (handleRequest)
```

**Comment by cmungall** [comment]
It looks like this might have been fixed by Seth's fix in #92 

In any case, things could do with improving here.

Using spaces has zero results:
http://tartini.crbs.ucsd.edu/search/guillain%20barre%20Syndrome

Correct hyphenation appears to be required:
http://tartini.crbs.ucsd.edu/search/Guillain-Barre%20syndrome

**Comment by cmungall** [comment]
Oh my mistake, you are right. It seems when we navigate to the disease page itself

http://tartini.crbs.ucsd.edu/disease/OMIM_139393

The dreaded stack trace comes up.

**Comment by cmungall** [comment]
I just fixed this, should be up on tartini shortly

@sarahjkim - see my fix in the above commit, we can discuss on wednesday

@nlwashington - just an aside, the page is v slow the first time, let's discuss strategies re multiple federation queries
