### ISSUE TITLE
Fix monarch homolog service

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#960]
Currently the homolog service is broken with the latest version of scigraph:
http://beta.monarchinitiative.org/query/orthologs/NCBIGene:6469.json

This is the result of removing fragments.

TODO:
- change underlying query to use curie version of RO id rather than fragment
- change processing of graph to use RO iri rather than fragment
- remove filtering of ids other than ensembl, mgi, and zfin (can't remember why I did this)

**Comment by cmungall** [comment]
Filtering: perhaps this is related to the fact that we have various species without phenotypes, and it doesn't look so great when people land on gene pages of these species

@nlwashington and I discussed putting an extra 3 fields:
1. `gene A` has >0 phenotype
2. `gene B` ahs >0 phenotype
3. Either 1 or 2

(the 3rd is useful to avoid annoying disjunction at Solr level)

**Comment by kshefchek** [comment]
This service is used to generate homologs on the analyze page when comparing phenotypes to genes.  It currently uses scigraph as it was developed before we had golr up and running.  For the use case above, we should probably use a new function that calls golr.

**Comment by jmcmurry** [comment]
What downstream UI components rely on the ortholog service?

**Comment by kshefchek** [comment]
This particular one, just the ortholog and paralog buttons on the analyze page.

**Comment by kshefchek** [comment]
This can be closed by making a note here to transfer the above requests to a new ticket.
