### ISSUE TITLE
invalid response for target_species=7955

### ISSUE THREAD

**Issue by davism84** [monarch-initiative/monarch-legacy#962]
/disease/DOID:3463

for Fish; this never comes back
http://monarchinitiative.org/simsearch/phenotype?input_items=HP:0000319,HP:0000385,HP:0002561,HP:0000455,HP:0003186,HP:0000453,HP:0010311&target_species=7955

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /simsearch/phenotype.

Reason: Error reading from remote server

Is there something up with target_species=7955 compares?  It seems I'm running into a lot of return errors on this species in particular.  @nlwashington   @cmungall

**Comment by cmungall** [comment]
On 18 Sep 2015, at 12:49, Michael Davis wrote:

> /disease/DOID:3463
> 
> for Fish; this never comes back
> http://monarchinitiative.org/simsearch/phenotype?input_items=HP:0000319,HP:0000385,HP:0002561,HP:0000455,HP:0003186,HP:0000453,HP:0010311&target_species=7955

Comes back in <0.25s for me. Network issue?

**Comment by davism84** [comment]
yes must have been network issues. Now the compare is working just fine. @cmungall   I'm closing this out.  thx
