### ISSUE TITLE
Autocomplete behavior with articles (eg. 'abnormality of dental' vs 'abnormality of THE dental')

### ISSUE THREAD

**Issue by markengelstad** [monarch-initiative/monarch-legacy#965]
On the analyze phenotypes page, in the create a phenotype profile search bar:  

included or omitting articles (words) like 'the' gives different search results. 
Example:  I'm searching for the phenotype 'abnormality of dental root' . 

I enter 'abnormality of dental' and get autocomplete options:  color, enamel, structure, morphology
I enter 'abnormality of THE dental' and get autocomplete options: root, pulp

so, if i try the first option, i am going to conclude that the term i'm searching for doesn't exist... unless i know enough to try different article combinations.

**Comment by kshefchek** [comment]
'abnormality of dental' now returns abnormality of dental root (6th in list)
