### ISSUE TITLE
Fix behave tests to be compatible with latest phenogrid version

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#967]
It looks like the tests in [maui_phenogrid.feature](https://github.com/monarch-initiative/monarch-app/blob/master/tests/behave/maui_phenogrid.feature) need to be adapted to the last version of phenogrid.  The test appear to be failing when waiting for pg_svg_area, for example:
https://github.com/monarch-initiative/monarch-app/blob/08fd7442d/tests/behave/maui_phenogrid.feature#L8

**Comment by kshefchek** [comment]
cc @yuanzhou, I'm happy to fix if you could point me in the right direction.

**Comment by yuanzhou** [comment]
@kshefchek I've updated those behave tests.

**Comment by kshefchek** [comment]
Looks like we're still faling here:
  maui_phenogrid.feature:18  Loading the iframe content for Monarch Phenotype Grid Widget loads a page with the correct title

Is this an issue with the test of the headless browser issues on travis?

**Comment by yuanzhou** [comment]
Looks like `/node_modules/phenogrid/index.html` is a cross species comparison not the single species view. So it should just say "Phenotype Similarity Comparison".

**Comment by kshefchek** [comment]
Looks like it was fixed in @doctorbud's PR
