### ISSUE TITLE
Input Validation Needed for "Analyze Phenotypes" Entry Point 

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#968]
http://beta.monarchinitiative.org/analyze/phenotypes is much better than it was. Thanks Zhou! Two additional tweaks to recommend though...
    1) Consider making the 'Submit' button (and settings panel) inactive, and the phenotype entry field also highlighted until user enters at least one phenotype
    2) In grey (suggestion) font, provide a corresponding phenotype that corresponds to LHX1 suggestion in the Genes panel.

This is to a) ease the user in with one thing at a time and b) avoid misleading users into searching for all phenotypes we have on record for a given gene or species or some combination of the two. As of this writing, when either of those queries is executed we get a 'no results' message which is not really what we mean.

**Comment by nlwashington** [comment]
+1

**Comment by yuanzhou** [comment]
@jmcmurry Just to clarify that I didn't work on the "Analyze Phenotypes" page, Phenogrid is embedded in the results tab. I think @kshefchek is the right person to make the changes that you've suggested.

In addition to what you've mentioned above, I feel the Search tab and Results tab are better to be merged into one tab, or show the results on the same page of the search page.

The other thing is the search data is submitted via HTTP get, so you can see them in the URL. If we refresh the page, we still see the previous search data and results, which is not very intuitive. I assume the refresh of the page will reset everything. So if we show the results on the same page via ajax, the refresh will reset the input form.

**Comment by yuanzhou** [comment]
@jmcmurry is this a phenogrid issue?

**Comment by jmcmurry** [comment]
Not really, no; the phenogrid label could be removed. In response to your thread above, the "no results" response was one Kent thought you had fixed (was previously just an error). Doesn't really matter, though.

**Comment by yuanzhou** [comment]
Just a side note here, I'll be fixing the ''compare" and "upload" of this phenotype analyze page since they are two cases that should be supported by Phenogrid, it's mentioned here: https://github.com/monarch-initiative/phenogrid/issues/203
