### ISSUE TITLE
Unsupported parameters used in new phenogrid constructor - Analyze.js

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#970]
In the refactored phenogrid, we've also normalized the parameters that can be put in the phenogrid constructor. In monarch-app's `/js/Analyze.js` file, there are two parameters are provided in the constructor but not supported by the refactored phenogrid. `owlSimFunction` and `geneList`. Did we ever use them? @harryhoch @kshefchek 

![capture](https://cloud.githubusercontent.com/assets/195873/10165464/7910d96c-668d-11e5-8937-d9a33653459f.PNG)

**Comment by harryhoch** [comment]
I'm not familiar with this code. @kshefchek ?

**Comment by kshefchek** [comment]
We use those parameters for the "compare to list of genes" setting on the analyze page.

**Comment by yuanzhou** [comment]
Thanks @kshefchek Looks like the new phenogrid has gotten rid of the `geneList` from config, and `owlSimFunction` is still there for some checks in the if statement. For example:

```
if (this.state.owlSimFunction === 'exomiser') {
    this.state.selectedCalculation = 2; // Force the color to Uniqueness
}
```

and

```
if (this.state.owlSimFunction !== 'compare' && this.state.owlSimFunction !== 'exomiser')
```

I'll prob need to ask @davism84 for more details. Will keep you posted.

**Comment by yuanzhou** [comment]
After talking to Mike, it turned out that the `owlSimFunction` is just ported from the old phenogrid and needs more work and testing, and `geneList` has gone from the current phenogrid. I'll close this issue here and reference it in phenogrid's issue list so I keep track of this.
