### ISSUE TITLE
"EOM:" prefixed phenotypes

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#973]
I was on `http://beta.monarchinitiative.org/disease/OMIM:255800` for testing phenogrid, and noticed this from the phenotypes TSV file:

![capture](https://cloud.githubusercontent.com/assets/195873/10176863/46320eb6-66c5-11e5-9a36-53db0ebf9e43.PNG)

Are those "EOM:" prefixed phenotypes correct? Their ID numbers look like really random. 

Click the image to view a readable version.

**Comment by nicolevasilevsky** [comment]
I think those are from the "elements of morphology": https://elementsofmorphology.nih.gov/

**Comment by cmungall** [comment]
Yes. Try pasting one in after /phenotype/ and see if it resolves

**Comment by yuanzhou** [comment]
@cmungall  Tried http://monarchinitiative.org/phenotype/EOM:77bdc627bdaf29d3, no info.

**Comment by nlwashington** [comment]
So, that resolves here:
https://elementsofmorphology.nih.gov/index.cgi?tid=e29866db35162165

no prefix / purl to resolve it yet.  in curie_map we use the obo purl.

**Comment by yuanzhou** [comment]
Yes, it also resolves for:

https://elementsofmorphology.nih.gov/index.cgi?tid=77bdc627bdaf29d3

**Comment by yuanzhou** [comment]
@nlwashington 
http://beta.monarchinitiative.org/disease/OMIM:105830

![capture](https://cloud.githubusercontent.com/assets/195873/10232476/02873928-6857-11e5-9bd2-78bfb361511e.PNG)

If you click one of those Fbbt phenotypes, you will see the URL looks like `FBbt:00005383PHENOTYPE`, is this a data error?

**Comment by cmungall** [comment]
No
