### ISSUE TITLE
disease hierarchy is not being displayed

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#974]
Everything looks like root:

http://beta.monarchinitiative.org/disease/OMIM:255800

**Comment by kshefchek** [comment]
This is the result of the equivalence merge with the latest scigraph load.  I need to add some code to make this work with the neighborhood view, but we first need a scigraph service to return the cliqueLeader given an ID.

**Comment by kshefchek** [comment]
cc @jnguyenx
