### ISSUE TITLE
"--port" flag in start-server.sh never worked

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#976]
I have been using port 8080 for other systems, so I wanted to use port 8282 for example for monarch-app, every time I tried `./start-server.sh --port 8282` it always used 8080, seems that --port flag never worked. I had to manually edit the `start-server.sh`. Please fix this. 

FYI, I was accessing CentOS via SSH.

**Comment by harryhoch** [comment]
try 

export PORT=8282 && ./start-server.sh

**Comment by yuanzhou** [comment]
Thanks @harryhoch, what you suggested worked for me.

**Comment by yuanzhou** [comment]
Suggested by @DoctorBud, I also tried 

```
PORT=8282 ./start-server.sh
```

 and 

```
NODE_PATH=./lib/monarch node lib/monarch/web/webapp_launcher.js --port 8282
```

Both worked.
