### ISSUE TITLE
association pages not working (nodejs?)

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#978]
hi,

i can't seem to get this one to show up on beta:
http://monarchinitiative.org/association/MONARCH:0249a6fb82e7d1358bb6fed4dba93f84

even though it shows up on prod.

was this code removed?  if so, can it be put back?

nicole

**Comment by cmungall** [comment]
Flinging back over the wall to Kent as I think he wrote it. Lost in the node refactor?

**Comment by nlwashington** [comment]
That's what I was wondering if it was lost in refactor.
