### ISSUE TITLE
Interesting findings after switching to nodejs version of monarch-app

### ISSUE THREAD

**Issue by yuanzhou** [monarch-initiative/monarch-legacy#979]
I'm running CentOS 6.7 on VirtualBox, and set up the port forwarding for SSH (2222->22) as well as HTTPD (8080->80). This way I can access to the Linux via my Windows. When I was running RingoJS version of monarch-app, I did port forwarding 8282->8282 so I can access monarch-app in my windows browser by going to `http://localhost:8282/`, but this doesn't work for the NodeJS version of monarch-app. 

I did another test this morning to confirm my findings. I downloaded the August release version (https://github.com/monarch-initiative/monarch-app/tree/c767eccfdbd3cd65fa8049af7328eb65638d0f87) and no problem with accessing monarch-app from my windows PC's browser. But couldn't see monarch-app via `localhost:8282` in my windows PC after I did a fresh install of the most recent monarch-app, which is NodeJS based.

**Comment by DoctorBud** [comment]
By default, monarch-app runs on port 8080, so you might want to forward 8282 to 8080 instead of forwarding to 8282.

I’m not sure why 8282 ever worked for you, unless you were invoking the server with —port 8282 or you have the PORT env variable defined. It's also possible that you have a jetty.xml file that specifies 8282, and RingoJS uses Jetty so it would 'see' that file and use port 8282. NodeJS does not use Jetty or look at that file.

If you want to run on port 8282, you can either use the `—port 8282` option, which works with both the RingoJS and NodeJS version of monarch-app. I just verified this with the following command:

`NODE_PATH=./lib/monarch node lib/monarch/web/webapp_launcher.js --port 8282`

Alternatively, you can define PORT and run start-server.sh:

`PORT=8282 ./start-server.sh`

If you don't specify the port via the above, monarch-app runs on port 8080 by default.

**Comment by yuanzhou** [comment]
Previously, I edited `start-server.sh` and manually changed 8080 to 8282 in that file. I just tested with what you suggested but on port 8484 because I never used 8484 before so there's shouldn't be any conflicts. But 8484 didn't work neither. I've stopped iptables and I'm running SSH and HTTPD via port forwarding with no problem.

Also tried just to forward 8484 to 8080, no luck.

![capture](https://cloud.githubusercontent.com/assets/195873/10253351/f023fa82-690a-11e5-965a-96adee7e0161.PNG)

I did `NODE_PATH=./lib/monarch node lib/monarch/web/webapp_launcher.js --port 8484` with a fresh install of monarch-app from the github master branch. And did port forwarding from 8484->8484, still couldn’t see monarch-app in browser. I could see it inside the VM using CentOS desktop browser with `localhost:8484` though.

Yesterday I had trouble with specifying –port for start-server.sh, see #976  Harry told me to use this `export PORT=8282 && ./start-server.sh`  and it worked. I think it’s equivalent to `PORT=8282 ./start-server.sh` as well as `NODE_PATH=./lib/monarch node lib/monarch/web/webapp_launcher.js --port 8282` since `start-server.sh` calls `webapp_launcher.js` with the port variable.

**Comment by yuanzhou** [comment]
And here is output of all running ports on TCP.

![capture](https://cloud.githubusercontent.com/assets/195873/10253762/2d9af1ac-690d-11e5-97b9-eb3e044fb27a.PNG)

As you can see, monarch-app is running node on 8080, and httpd on 80, ssh on 22. Both port forwarding works for httpd and ssh, but just couldn't get it work for node server. That's why I'm guessing if switching from RingoJS to Nodejs caused this issue. But honestly I have no clue of how to resolve this.

**Comment by DoctorBud** [comment]
Is this still an issue? As you've discovered, the port can be specified via an environment variable PORT when using start-server.sh, and can be specified via `--port` when using webapp_launcher.js.

Zhou, please reply to this and close the ticket.

**Comment by yuanzhou** [comment]
Still not resolved. It might be just for my PC and VM settings. I'll reexamine later.

**Comment by yuanzhou** [comment]
## Notes about this issue from @DoctorBud :

It’s a bug in `webapp.js` that is easily fixed:

```
    app = new Hapi.Server();
    app.connection({
        host: 'localhost',
```

should be:

```
    app = new Hapi.Server();
    app.connection({
        host: ‘0.0.0.0',
```

The backstory is that ‘localhost’ doesn’t always resolve to the ‘network’ you’d expect, especially when there are multiple network adaptors in play, as is the case with a virtualbox. By using 0.0.0.0, we are saying to Hapi that it should listen on ALL interfaces, which includes the tunneled network. That’s how I understand it, at least.

**Comment by DoctorBud** [comment]
Added this comment to webapp.js when I fixed this in PR https://github.com/monarch-initiative/monarch-app/issues/977
    // From http://hapijs.com/api
    //      address - sets the host name or IP address the connection will listen on.
    //      If not configured, defaults to host if present, otherwise to all available
    //      network interfaces (i.e. '0.0.0.0'). Set to 127.0.0.1 or localhost to
    //      restrict connection to only those coming from the same machine.
