### ISSUE TITLE
Describe what "related diseases" are

### ISSUE THREAD

**Issue by nlwashington** [monarch-initiative/monarch-legacy#98]
We need to describe what the tab for "related diseases" means.

Also, we need a description of "similar models".

I think it could be a (?) "what's this" expand-o box/popup that tells the user that we use owlsim etc etc.  i can come up with some text.

**Comment by mellybelly** [comment]
How about a hover-over, that says something like:
For Related Diseases:
"View diseases that have the most phenotypes in common"

For Similar Models:
"View models that have phenotypes in common"

may as well have a pop up for all the tabs, so here are a few more:
Phenotypes:
"View phenotypes related to the disease or model"

Genes:
"View genes known to be variant in the disease or model"

Alleles:
"View known variants associated with the disease"

Pathways
"View phenotypes on pathway view containing variant genes"

**Comment by sarahjkim** [comment]
@nlwashington @mellybelly Sorry it took me so long to get to this. I finished the tab hovers for the disease page. Could I get text for the following tabs? I didn't know what to put in them, so I'm just using a "Placeholder text" right now.

Phenotype: Disease, Genotypes
Genotype (Model): Related Diseases

**Comment by mellybelly** [comment]
Phenotype: Disease: View diseases with this phenotype
Phenotype: Genotype: View genotypes with this phenotype
Genotype (Model): Related Diseases: Find diseases that are phenotypically similar
