### ISSUE TITLE
Two equivalent search results for Parkinson's (one for MESH, one for DOID); both are missing taxon

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#981]
If you do a search for Parkinson's (http://beta.monarchinitiative.org/search/parkinsons) you get two results, one corresponding to DOID and another to MESH:

![screen shot 2015-10-02 at 13 36 44](https://cloud.githubusercontent.com/assets/3658863/10258373/7c4172cc-6912-11e5-9fed-972850a130cf.png)

But then if you look at http://beta.monarchinitiative.org/disease/DOID:14330 the equivalence with MESH seems to be present. 

![screen shot 2015-10-02 at 15 24 43](https://cloud.githubusercontent.com/assets/3658863/10259138/cbc96fdc-6919-11e5-9abd-8356803e26b1.png)

As a downstream consequence of this, you click on the hyperlinked mesh term http://beta.monarchinitiative.org/disease/MESH:D010300, you get a 404. This secondary problem should go away if the records are correctly collapsed since the link will not be visible in the first place.

![screen shot 2015-10-02 at 15 16 46](https://cloud.githubusercontent.com/assets/3658863/10259040/b62bca86-6918-11e5-9d52-cc69796073af.png)

Also notable is that taxon column is present (yay!) but both rows are missing corresponding designation.

**Comment by kshefchek** [comment]
It looks like we don't have this information in scigraph [example query](http://rosie.crbs.ucsd.edu:9000/scigraph/graph/neighbors?id=DOID:14330&depth=1&blankNodes=false&relationshipType=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FRO_0002162&direction=BOTH&project=*) @nlwashington will we eventually add disease taxon information?  Right now this column will only populate for genes.

**Comment by kshefchek** [comment]
Fixed with a4cfbbf, adding disease-taxon relationships should be moved to dipper.
