### ISSUE TITLE
On beta, disease pages load very slowly

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#982]
Disease pages are taking several seconds (>15) to load.
I suppose this has to do with all of the queries required to represent the hierarchy and siblings all the way to root, however, it is one of the first entry points into the system, so we may want to consider a faster, simpler view to start with.

http://beta.monarchinitiative.org/disease/MESH:D010300

**Comment by cmungall** [comment]
there's no reason why this should take this long. SciGraph _must_ be able to compute what is required in milliseconds, this is an ultra-basic traversal involving a handful of nodes. If we are making multiple calls that signifies the API does not do what we need it to do.

**Comment by cmungall** [comment]
In fact this node is Parkinson's Disease. There are six ancestors total in mondo.

**Comment by kshefchek** [comment]
The neighborhood view is client driven.  It is likely the calls to golr to get tab counts which will become client driven soon.

**Comment by cmungall** [comment]
sometimes solr is sluggish before it warms up. Be good to do multiple tests see what the distribution of timings is

**Comment by kshefchek** [comment]
Closing as this should be fixed on beta.  Will perform load testing when we switch back to beta golr to see how the larger index has affected performance.
