### ISSUE TITLE
species filtering is broken on /analyze/phenotypes on beta

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/monarch-legacy#987]
prod works:

http://monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0008392&mode=search&target_species=10090&limit=100

beta includes humans:

http://beta.monarchinitiative.org/analyze/phenotypes/?input_items=HP%3A0008392&mode=search&target_species=10090&limit=100

**Comment by jmcmurry** [comment]
Can't reproduce
