### ISSUE TITLE
Add disease model association distribution to models landing page

### ISSUE THREAD

**Issue by jmcmurry** [monarch-initiative/monarch-legacy#989]
In a few places, I'm a bit perplexed as to why we don't see models as results.

Take for instance when I navigate to [browse-->models](http://beta.monarchinitiative.org/model) and click on a bar corresponding to any given phenotype:
![screen shot 2015-10-08 at 16 39 40](https://cloud.githubusercontent.com/assets/3658863/10382681/50f6925a-6ddb-11e5-9bd9-0b9d16af8055.png)

Ostensibly, there are for instance 58K mouse models of cardiovascular system disease, however when click on the bar, I get zero in the models tab. This is true in production and in beta and on every single phenotype category and every single species. Screenshots below:

I would rather expect to see lots of models, but don't see any.
![screen shot 2015-10-08 at 16 35 25](https://cloud.githubusercontent.com/assets/3658863/10382637/d6a02458-6dda-11e5-8419-9fb2859412ef.png)

![screen shot 2015-10-08 at 16 35 02](https://cloud.githubusercontent.com/assets/3658863/10382639/d6a20426-6dda-11e5-9623-ddaec2e05000.png)

![screen shot 2015-10-08 at 16 34 37](https://cloud.githubusercontent.com/assets/3658863/10382642/d6a40b36-6dda-11e5-9b2e-b142228389c2.png)

Any idea what is going on here? Is this another instance of a problem that will be resolved when data and scigraph are released?

**Comment by kshefchek** [comment]
We still duplicate the model and genotype landing pages, will break these out into separate pages.
