### ISSUE TITLE
Some diseases have too many related diseases

### ISSUE THREAD

**Issue by mellybelly** [monarch-initiative/monarch-legacy#99]
For example, http://tartini.crbs.ucsd.edu/disease/OMIM_260300
has 1000 related diseases. 
Perhaps need a different cut-off?

**Comment by cmungall** [comment]
The actual tab for related diseases seems to have a cutoff

It's not really meaningful to report num. of related diseases here, since everything is related to some degree.

Also need to provide more info on the related disease tab, that these are related by degree of phenotypic similarity.

**Comment by mellybelly** [comment]
See also #98

**Comment by sarahjkim** [comment]
Fixed as of commit a1b0fd5046.
