### ISSUE TITLE
Rank species in autocomplete and search for genes

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/monarch-legacy#990]
We want to display human and model organisms in which we know have information first in any search or autocompleted list of results (human, mouse, zebrafish, fly).  One option would be to simply filter out other species.

**Comment by kshefchek** [comment]
We can do this now using the bf (boost function) on edge counts.  However, we should be careful to only do this when auto completing on a specific type (scoped autocomplete), since edge counts are not normalized across types.

[Example without edge boost](https://solr-dev.monarchinitiative.org/solr/search/select/?defType=edismax&qt=standard&indent=on&wt=json&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&hl.snippets=1&facet.field=id&q=shh+%22shh%22&qf=label_searchable^1&qf=definition_searchable^1&qf=synonym_searchable^1&qf=iri_searchable^2&qf=id_searchable^2&qf=equivalent_iri_searchable^1&qf=equivalent_curie_searchable^1&qf=taxon_label_searchable^1&qf=taxon_label_synonym_searchable^1&qf=iri_std^3&qf=iri_kw^3&qf=iri_eng^3&qf=id_std^3&qf=id_kw^3&qf=id_eng^3&qf=label_std^2&qf=label_kw^2&qf=label_eng^2&qf=definition_std^1&qf=definition_kw^1&qf=definition_eng^1&qf=synonym_std^1&qf=synonym_kw^1&qf=synonym_eng^1&qf=category_std^1&qf=category_kw^1&qf=category_eng^1&qf=equivalent_iri_std^1&qf=equivalent_iri_kw^1&qf=equivalent_iri_eng^1&qf=equivalent_curie_std^1&qf=equivalent_curie_kw^1&qf=equivalent_curie_eng^1&qf=taxon_label_std^1&qf=taxon_label_kw^1&qf=taxon_label_eng^1&qf=taxon_label_synonym_std^1&qf=taxon_label_synonym_kw^1&qf=taxon_label_synonym_eng^1&hl.fragsize=0)

[Example with edge boost](https://solr-dev.monarchinitiative.org/solr/search/select/?defType=edismax&qt=standard&indent=on&wt=json&start=0&fl=*,score&facet=true&facet.mincount=1&facet.sort=count&json.nl=arrarr&facet.limit=25&hl=true&hl.simple.pre=%3Cem%20class=%22hilite%22%3E&hl.snippets=1&facet.field=id&q=shh+%22shh%22&qf=label_searchable^1&qf=definition_searchable^1&qf=synonym_searchable^1&qf=iri_searchable^2&qf=id_searchable^2&qf=equivalent_iri_searchable^1&qf=equivalent_curie_searchable^1&qf=taxon_label_searchable^1&qf=taxon_label_synonym_searchable^1&qf=iri_std^3&qf=iri_kw^3&qf=iri_eng^3&qf=id_std^3&qf=id_kw^3&qf=id_eng^3&qf=label_std^2&qf=label_kw^2&qf=label_eng^2&qf=definition_std^1&qf=definition_kw^1&qf=definition_eng^1&qf=synonym_std^1&qf=synonym_kw^1&qf=synonym_eng^1&qf=category_std^1&qf=category_kw^1&qf=category_eng^1&qf=equivalent_iri_std^1&qf=equivalent_iri_kw^1&qf=equivalent_iri_eng^1&qf=equivalent_curie_std^1&qf=equivalent_curie_kw^1&qf=equivalent_curie_eng^1&qf=taxon_label_std^1&qf=taxon_label_kw^1&qf=taxon_label_eng^1&qf=taxon_label_synonym_std^1&qf=taxon_label_synonym_kw^1&qf=taxon_label_synonym_eng^1&hl.fragsize=0&bf=pow(edges,0.334))

EDIT: updated with solr relevancy score + cubed root of the edge count

**Comment by cmungall** [comment]
@kltm we'd want this in amigo too. is this something that should be ported to bbop-manager?

**Comment by kltm** [comment]
@cmungall Absolutely.

**Comment by kshefchek** [comment]
done on alpha
